### PR TITLE
fix(visibility): Private extensions

### LINKED ISSUE #10718: Can access private item inside extension method
### Aim

Noticed during https://github.com/noir-lang/noir/pull/10717

I wasn't sure what https://github.com/noir-lang/noir/blob/e5587f8509fbc92ebd15ad8c13a6e44b96d1154b/compiler/noirc_frontend/src/elaborator/path_resolution.rs#L702 was trying to achieve. Nothing broke when I removed it, so at least a test is missing. Analysing it revealed a case that is different from Rust.

The following program compiles in Noir, but it would not compile in Rust:
```rust
pub mod foo {
    pub struct Foo {
        z: u32,
    }

    impl Foo {
        pub fn new() -> Self {
            Self { z: 0 }
        }
        fn x() -> u32 {
            0
        }
        fn y(_self: Self) -> u32 {
            0
        }
    }
}

mod bar {
    use super::foo::Foo;
    impl Foo {
        pub fn extension() {
            let f = Foo::new();
            let _x = Foo::x();
            let _y = f.y();
            // let _z = f.z;
        }
    }
}

fn main() {}

```

### Expected Behavior

I would expect that when we define an `impl` for a type defined in another module, we only get access to its public parts. If we try to access the private field `z`, this is actually enforced, but with methods it's not.

### Bug

The program compiles in Noir. In Rust we get errors:

```
error[E0624]: associated function `x` is private
  --> src/main.rs:24:27
   |
10 |         fn x() -> u32 {
   |         ------------- private associated function defined here
...
24 |             let _x = Foo::x();
   |                           ^ private associated function

error[E0624]: method `y` is private
  --> src/main.rs:25:24
   |
13 |         fn y(self) -> u32 {
   |         ----------------- private method defined here
...
25 |             let _y = f.y();
   |                        ^ private method
```

### To Reproduce

https://play.rust-lang.org/?version=stable&mode=debug&edition=2024&gist=d46ab274a4c78dc0ffbb40b20f25c412

vs 
```
cargo run -q -p nargo_cli -- compile --force 
```

### Workaround

None

### Workaround Description

_No response_

### Additional Context

_No response_

### Project Impact

None

### Blocker Context

_No response_

### Nargo Version

nargo version = 1.0.0-beta.15 noirc version = 1.0.0-beta.15+aac7281225fd2dd293a69a0979127e74af853d3e (git version hash: aac7281225fd2dd293a69a0979127e74af853d3e, is dirty: true)

### NoirJS Version

_No response_

### Proving Backend Tooling & Version

_No response_

### Would you like to submit a PR for this Issue?

None

### Support Needs

_No response_

### PR DESCRIPTION
**Pull request by aakoshh**
# Description

## Problem

Resolves #10718

## Summary

Changes the rules around visibility so that if we define an `impl` block for a type defined in a different module (an "extension" of a type in the same crate), then we only have access to the public methods defined in the source module and other extensions, and vice versa. 

## User Documentation

Check one:
- [x] No user documentation needed.
- [ ] Changes in _docs/_ included in this PR.
- [ ] **[For Experimental Features]** Changes in _docs/_ to be submitted in a separate PR.

# PR Checklist

- [x] I have tested the changes locally.
- [ ] I have formatted the changes with [Prettier](https://prettier.io/) and/or `cargo fmt` on default settings.

### CODE REVIEW

**Comment by asterite** [comment]
It's a bit strange that there are circuit changes 🤔

**Comment by aakoshh** [comment]
> It's a bit strange that there are circuit changes 

Yeah; usually it's because this branch is behind `master`.

File: compiler/noirc_frontend/src/hir/resolution/visibility.rs [hunk 1]
```diff
@@ -166,10 +167,24 @@ pub fn method_call_is_visible(
...
+                        // we should only access public parts defined in other modules, or private
+                        // ones defined in the same extension.
+                        let def_map = &def_maps[&current_module.krate];
+                        return module_is_descendant_of_target(
+                            def_map,
+                            current_module.local_id,
+                            func_meta.source_module,
+                        );
+                    } else {
+                        return true;
```
Comment (asterite) [inline compiler/noirc_frontend/src/hir/resolution/visibility.rs:189]: I think I understand why if it's `pub(crate)` we don't need to check that the crate is the same, and this applies to impls and trait impls, but a comment here might be helpful.

Comment (aakoshh) [reply compiler/noirc_frontend/src/hir/resolution/visibility.rs:189]: Added a comment. I added a check on the equality, then I figured as long as the type IDs are the same, it means the crate is the same. Maybe if we weren't in the self type the extra check would be needed. The `ForeignImpl` error should prevent that though.
