### PR TITLE
fix: use enable_side_effects for u128 multiplication overflow checks

### LINKED ISSUE #9099: ACIR vs Brillig: failed assertion on unreached branch; constant u128 multiplication overflow
### Aim

The following Noir program failed in ACIR and solved in Brillig
```noir
fn main(condition: bool) -> pub bool {
  if condition {
    let a: u128 = 0;
    let b = !a;
    let _ = b * b;
  }
  condition
}
```
with Prover.toml
```toml
"condition" = 0
```

### Expected Behavior

ACIR solved

### `nargo execute`
```
nargo execute
error: Assertion failed: attempt to multiply with overflow
  ┌─ /home/defkit/work/hui/src/main.nr:5:13
  │
5 │     let _ = b * b;
  │             -----
  │
  = Call stack:
    1. /home/defkit/work/hui/src/main.nr:5:13

Failed assertion
```

### `nargo execute --force-brillig`
```
nargo execute --force-brillig
[hui] Circuit witness successfully solved
[hui] Circuit output: Field(0)
[hui] Witness saved to /home/defkit/work/hui/target/hui.gz
```

By the way, when I use `--show-ssa` I also receive assertion is always false for ACIR
```
After Dead Instruction Elimination (3rd):
acir(inline) predicate_pure fn main f0 {
  b0(v0: u1):
    enable_side_effects v0
    constrain u128 1 == u128 0, "attempt to multiply with overflow"
    enable_side_effects u1 1
    return v0
}

bug: Assertion is always false
  ┌─ src/main.nr:5:13
  │
5 │     let _ = b * b;
  │             ----- As a result, the compiled circuit is ensured to fail. Other assertions may also fail during execution
  │
  = Call stack:
    1. src/main.nr:5:13

error: Assertion failed: attempt to multiply with overflow
  ┌─ /home/defkit/work/hui/src/main.nr:5:13
  │
5 │     let _ = b * b;
  │             -----
  │
  = Call stack:
    1. /home/defkit/work/hui/src/main.nr:5:13

Failed assertion
```

### To Reproduce

1.
2.
3.
4.

### Workaround

None

### Workaround Description

_No response_

### Additional Context

_No response_

### Project Impact

None

### Blocker Context

_No response_

### Nargo Version

_No response_

### NoirJS Version

_No response_

### Proving Backend Tooling & Version

_No response_

### Would you like to submit a PR for this Issue?

None

### Support Needs

_No response_

### PR DESCRIPTION
**Pull request by guipublic**
# Description

## Problem\*

Resolves #9099 

## Summary\*
u128 overflow checks take the current 'enable_side_effects' into account so that the check is disabled if there if side effects are disabled as well.

## Documentation\*

Check one:
- [X] No documentation needed.
- [ ] Documentation included in this PR.
- [ ] **[For Experimental Features]** Documentation to be submitted in a separate PR.

# PR Checklist\*

- [X] I have tested the changes locally.
- [X] I have formatted the changes with [Prettier](https://prettier.io/) and/or `cargo fmt` on default settings.

### CODE REVIEW

File: compiler/noirc_evaluator/src/ssa/opt/simple_optimization.rs [hunk 1]
```diff
@@ -95,6 +101,7 @@ pub(crate) struct SimpleOptimizationContext<'dfg, 'mapping> {
     pub(crate) block_id: BasicBlockId,
     pub(crate) instruction_id: InstructionId,
     pub(crate) dfg: &'dfg mut DataFlowGraph,
+    pub(crate) enable_side_effects: ValueId,
```
Comment (asterite) [inline compiler/noirc_evaluator/src/ssa/opt/simple_optimization.rs:104]: Nice! We could use this in `remove_unreachable_instructions` as well. No need to do it in this PR, I can do it in a follow-up PR.

**Comment by guipublic** [comment]
> Looks great! Could you add a regression test?

I already added a unit test, do you think it is better to have an additional test in test_programs?

**Comment by asterite** [comment]
Ooooh... I missed the unit test. I saw the issue had Noir code and couldn't find it in this PR, but like this it's fine, sorry!

**Comment by asterite** [comment]
But, hmm... it might be good to have the failing file as a regression test as it's a more complete scenario. Up to you.

**Review by asterite — APPROVED** [review]
