### PR TITLE
fix: Defunctionalize foreign functions in pre-SSA pass over mAST

### LINKED ISSUE #10154: Handle `#[oracle]` function pointers in defunctionalize
https://cantina.xyz/code/5387827b-5629-4d61-beda-76d82161d335/findings/2

Using an `#[oracle]` as a function _value_ is not handled by the dispatcher. 

We discussed that we can either:
* Handle such functions in the dispatcher creation, or
* Find all uses of such function values and _wrap_ them in a normal function during defunctionalization

The 2nd option means we don't have to figure out an ID for them, and after this everything just works as before. This would be similar to how we inject dummy functions for signatures that don't occur.

Also applies for intrinsics.

### LINKED ISSUE #10156: Crash: Trying to print an `#[oracle]` function
### Aim

Related to https://github.com/noir-lang/noir/issues/10152

The following code crashes during compilation:

```rust
pub fn main() {
    println(bar);
}

#[oracle(barnacle)]
unconstrained fn bar() -> Field {}
```

### Expected Behavior

Not to crash.

### Bug

```
❯ cargo run -q -p nargo_cli -- compile --force --silence-warnings

The application panicked (crashed).
Message:  internal error: entered unreachable code: Functions cannot be constant values
Location: compiler/noirc_evaluator/src/ssa/opt/constant_folding/interpret.rs:115
```

So the problem is that we pass functions to foreign calls as their ID. The `PrintableValue` and `PrintableType` handle this, although it's not actually displayed by the `PrintForeignCallHandler`. These values don't have IDs, though, and apparently constant folding also doesn't expect to have to pass functions to the SSA interpreter, which is understandable since by then no function values should be passed around.

We could avoid this if we wrap all occurrences of oracles being passed as values with a normal function that we _can_ refer to by ID. 

The question is where should we do this: trying to `interpret` the above code panics because when I implemented printing in the SSA interpreter I left a `panic!` for intrinsics and foreign functions, since they don't have an ID. Perhaps we can hash their names. In any case, if we wanted to do any wrapping, and be able to interpret the _Initial SSA_, then this wrapping must be done in the monomorphizer.

### To Reproduce

_No response_

### Workaround

None

### Workaround Description

_No response_

### Additional Context

_No response_

### Project Impact

None

### Blocker Context

_No response_

### Nargo Version

_No response_

### NoirJS Version

_No response_

### Proving Backend Tooling & Version

_No response_

### Would you like to submit a PR for this Issue?

None

### Support Needs

_No response_

### PR DESCRIPTION
**Pull request by aakoshh**
# Description

## Problem\*

Resolves #10156
Resolves #10154 

## Summary\*

Adds a new `create_foreign_proxies` method to the monomorphized `Program`, similar to `handle_ownership`, which is executed in `monomorphize_debug`, as a pass on the AST before SSA generation. 

The pass finds all instances where we use a "foreign" function as a value - where "foreign" can be intrinsic, oracle or built-in function identifier -, creates proxy functions to call them, and replaces the definition in the identifiers with the ID of the new global function. After this pass we should only ever see function values refer to global functions, and only direct calls refer to intrinsic/builtin/oracle functions. 

Further changes:
* Added a `defuncitonalize_pre_check` to ascertain that we no longer have non-global functions as values.
* Moved the `visitor` module from the AST fuzzer to the monomorphization module.
* Added extra logic to the `to_hir_type` function in the AST fuzzer, to handle function types and convert them back to non-tuple HIR type. Made the `Monomorphizer` public so that I can add a property based test that `Monomorphizer::convert_type` and `Type::to_hir_type` are on the same page. (We already agreed that the `Monomorphizer` can be public in https://github.com/noir-lang/noir/pull/9979).
* Changed the SSA interpreter to not panic if an `Intrinsic` or `Oracle` has to be printed, but use the hash instead, although now this shouldn't come up, since there will always be a wrapper with a global ID.

## Additional Context

Started by handling oracle and intrinsic functions in the SSA interpreter printing so that Initial SSA can be processed, thinking I'd be replacing these values during the `defuncitonalize` pass with wrapper functions, but then realised the wrapping will have to happen in the monomorphizer, which will solve it even for the Initial SSA.

I looked at the monomorphizer queue, and thought that while it would be possible to extend the queue mechanism to non-global functions, it would go against the grain of it more than adding a post-processing pass to create new function. The current queue processing logic expects to be able to find the definition of a function in the NodeInterner, whereas these new ones would not exists, and would have to be projected based on the definition of something else. 

I thought this can be achieved without making the monomorphizer more complicated by traversing the AST. 

I found it a little surprising that an identifier for a function looks something like this: 
```rust
Ident { 
  name: "as_witness", 
  definition: Definition::Intrinsic(Intrinsic:AsWitness), 
  type: Type::Tuple(vec![
    Type::Function {..., unconstrained: false}, 
    Type::Function {..., unconstrained: true}
  ])
}
```
This is true in both of these cases:
```rust
foo(as_witness);
as_witness(0);
```
The first one will appear in the AST as `Call` with an `arguments` of `vec![Tuple(vec![Ident, Ident])]`, where both idents are the same, carrying both constrained and unconstrained in their type:
```rust
foo((as_witness$as_witness, as_witness$as_witness));
```
while the second has just 1 `Ident` in `Call::func`, but its type is again a tuple of functions:
```rust
as_witness$as_witness(0);
```
I initially thought there would be two idents with the same definition (e.g. `Intrinsic`), and the `Ident::typ` would be `Type::Function`. 

The fact at there is a `Expression::Tuple` makes it easy to detect when we are dealing with a function value, and then seek confirmation from the `Ident::typ` which should also be a tuple of `Type::Function` with `false` and `true` for `unconstrained`.

### Example

```rust
unconstrained fn main() {
    foo(bar);
    unsafe {
        bar(0);
    }
}

unconstrained fn foo(f: unconstrained fn(Field) -> ()) {
    f(0);
}

#[oracle(my_oracle)]
unconstrained fn bar(f: Field) {}
```

```console
❯ cargo run -q -p nargo_cli -- compile --force --silence-warnings --show-ssa-pass Initial --show-monomorphized

unconstrained fn main$f0() -> () {
    foo$f1((bar$f2, bar$f3));;
    {
        bar$my_oracle(0);
    }
}
unconstrained fn foo$f1(f$l0: (fn(Field) -> (), unconstrained fn(Field) -> ())) -> () {
    f$l0.1(0);
}
#[inline_always]
fn bar_proxy$f2(p0$l0: Field) -> () {
    bar$my_oracle(p0$l0)
}
#[inline_always]
unconstrained fn bar_proxy$f3(p0$l0: Field) -> () {
    bar$my_oracle(p0$l0)
}

After Initial SSA:
brillig(inline) fn main f0 {
  b0():
    call f1(f2, f3)
    call my_oracle(Field 0)
    return
}
brillig(inline) fn foo f1 {
  b0(v0: function, v1: function):
    call v1(Field 0)
    return
}
acir(inline_always) fn bar_proxy f2 {
  b0(v0: Field):
    call my_oracle(v0)
    return
}
brillig(inline_always) fn bar_proxy f3 {
  b0(v0: Field):
    call my_oracle(v0)
    return
}
```

## Documentation\*

Check one:
- [x] No documentation needed.
- [ ] Documentation included in this PR.
- [ ] **[For Experimental Features]** Documentation to be submitted in a separate PR.

# PR Checklist\*

- [x] I have tested the changes locally.
- [ ] I have formatted the changes with [Prettier](https://prettier.io/) and/or `cargo fmt` on default settings.

### CODE REVIEW

File: compiler/noirc_frontend/src/monomorphization/proxies.rs [hunk 1]
```diff
@@ -0,0 +1,316 @@
...
+    };
+
+    let call = {
+        let func = Ident {
+            id: next_ident_id(),
+            location: None,
+            definition: ident.definition,
+            mutable: ident.mutable,
+            name: ident.name,
+            typ: func_typ, // Pick the version based on constrained-ness.
```
Comment (aakoshh) [inline compiler/noirc_frontend/src/monomorphization/proxies.rs]: I just realise this is different than what my debug showed. I think to match what the monomorphizer does this needs to be `ident.typ`, which keeps the type as a `Tuple` of `Function`s even in direct calls.

Comment (aakoshh) [reply compiler/noirc_frontend/src/monomorphization/proxies.rs]: Kept both to match how I saw it working in direct calls, keeping a tuple of function defs.

**Comment by jfecher** [comment]
> The current queue processing logic expects to be able to find the definition of a function in the NodeInterner, whereas these new ones would not exists, and would have to be projected based on the definition of something else.

Can you elaborate on this? I'm not sure why we'd need a new pass for this versus adding a `if is oracle { ... }` check when monomorphizing a function, and if so monomorphize a function wrapper for it with just a call to the real oracle inside.

**Comment by aakoshh** [comment]
When the monomorphizer encounters a call, it looks up the definition of the called function, and if it hasn't existed yet, it enqueues it, knowing that its ID will be the same. Then, we pick an ID from the queue and elaborate it by looking up the definition of it in the interner. 

To change this, what I thought I'd have to do is check that the call I'm making to is an oracle, and then come up with some ID I can call instead of the oracle, and enqueue that ID for monomorphization, but when we get that ID from the queue, there is no regular definition for it in the interner like there is for local functions, and instead it needs to rely on other information to synthesise a function. 

I'm sure this is all doable, but I thought it would be much easier to write it as a separate pass, which I was already familiar with, then for me add this aspect to the monomorphizer itself.

**Comment by aakoshh** [comment]
>  adding a `if is oracle { ... }` check when monomorphizing a function

I'm not sure where this check would be added to be honest. As I understood we only monomorphized user-defined functions, while oracle and intrinsics did not need to be enqueued for monomorphization, they were functions identified by "name". That's why I didn't want to go into this: the queue does not expect a foreign function in it, and then I don't know what definition to look up for them in the thing that processes the queue, so I would have had to add more context data captured during the enqueueing of the foreign function. 

I thought encapsulating all this into a separate pass that doesn't need to touch anything in the elaborator is cleaner. I wasn't sure if it somehow makes the elaborator "incomplete" that it produces code that isn't meant to be final, but since ownership analysis also modifies the AST, and there is no way to skip this, we can consider it part of the elaboration, even if the means to achieve it lay outside the purview of the queue processing logic.

**Comment by aakoshh** [comment]
I see that the looking up the definition itself is the same `FuncMeta`, so I suppose that's where the `if oracle` would go in `Monomorphizer::function`. The fields that go in the queue would potentially go unused, since they are not used in `Monomorphizer::lookup_function` for foreign function. So when an item appears in the queue that refers to a foreign function, it already has its AST `FuncId` assigned, and we could produce a wrapper for it, instead of looking up its body expression, which it doesn't have.

What I wasn't sure about is that the `Monomorphizer::function_reference` is obviously used when we use a function as a value, but we call `lookup_function` also when we call a function, in which case we don't need to create a wrapper for foreign functions. 

Altogether, yes, this seems doable, but I found it more straight forward to recognise when a function is a value in the mAST, and knew how to generate a body for it. Since the machinery in the `Monomorphizer` mostly based on IDs that refer to the interner, it didn't seem like conjuring up an `ast::Expression` when there isn't a body with a `HirExpression` would benefit from being done there. 

For example it didn't look like I can call `Monomorphizer::function_call`, unless somehow I add extra information in the function definition of these proxy functions with the ID of the original call expression, and this time make it without redirecting to a proxy. Once again, I chose the "obvious" approach based on the mAST, over figuring out the exact ways of the `Monomorphizer`.

File: compiler/noirc_frontend/src/monomorphization/ast.rs [hunk 2]
```diff
@@ -530,6 +531,76 @@ impl Type {
             _ => None,
         }
     }
+
+    /// Convert the type back into a HIR equivalent (not necessarily the original HIR type).
+    ///
+    /// Aims to maintain parity with [Monomorphizer::convert_type](crate::monomorphization::Monomorphizer::convert_type).
+    pub fn to_hir_type(&self) -> hir_def::types::Type {
```
Comment (jfecher) [inline compiler/noirc_frontend/src/monomorphization/ast.rs]: I am a bit worried that this is more to maintain over time. The Hir -> Mast transformation wasn't meant to be reversible in general.

File: compiler/noirc_frontend/src/monomorphization/mod.rs [hunk 3]
```diff
@@ -203,8 +205,11 @@ pub fn monomorphize_debug(
         debug_variables,
         debug_functions,
         debug_types,
-    );
-    Ok(program.handle_ownership())
+    )
+    .handle_ownership()
+    .create_foreign_proxies();
```
Comment (jfecher) [inline compiler/noirc_frontend/src/monomorphization/mod.rs:210]: Would it be easier if we handled this even earlier? E.g. in the elaborator whenever an oracle function is defined we could create a wrapper for it there.

**Review by jfecher — COMMENTED** [review]
I'm going to try some alternate methods of this PR to see if they pan out or if they're worse than expected. This has been up for a little while already so if they don't pan out I'll approve and we can get this merged to solve the issue now.

File: compiler/noirc_frontend/src/monomorphization/ast.rs (hunk 2 above)
Comment (aakoshh) [reply compiler/noirc_frontend/src/monomorphization/ast.rs]: It had to be done in order for AST generation, in order to be able to produce a function signature needed for the artifact. Perhaps we can keep it private, and only expose it with a feature flag for the AST fuzzer to use.

File: compiler/noirc_frontend/src/monomorphization/mod.rs (hunk 3 above)
Comment (aakoshh) [reply compiler/noirc_frontend/src/monomorphization/mod.rs:210]: I guess that depends on who you ask. For me personally, this was easier and more self contained than trying to do it in the monomorphizer, because here I have context: while traversing the AST I see when a function is used in a call, and when it's used as a value, whereas in the monomorphizer I thought I would have to pass along some flag: do I want the oracle/intrinsic/builtin resolves as a callable, or do I want it resolved into a proxy? 

I know even less about the elaborator, so I can't tell how easy it is there, but @TomAFrench immediately posed a question to confirm that direct calls have not been wrapped in proxies. 

Perhaps @vezenovm has an idea about it?

File: compiler/noirc_frontend/src/monomorphization/ast.rs (hunk 2 above)
Comment (aakoshh) [reply compiler/noirc_frontend/src/monomorphization/ast.rs]: I also added a `test_to_hir_type_roundtrip` test in the fuzzer which makes sure that the property promised by this function holds, which should help with maintaining its parity. Basically it says that (HIR-to-)mAST-to-HIR-to-MAST-HIR is stable except for the first HIR. The test relies on the random generation of `Program`, that's why it's there.

Comment (aakoshh) [reply compiler/noirc_frontend/src/monomorphization/ast.rs]: Hm, I knew that in the fuzzer we only really used the `Function::func_sig` for the `main` method, so even though I implemented this `to_hir_type` to generate a signature for any function, it was discarded for all but the main entrypoint; I see now that e.g. `Monomorphizer::lambda_no_capture` actually uses `FunctionSignature::default()`, doesn't even bother to produce a signature. Perhaps we could use that for the proxies as well, and then `to_hir_type` can go back to live in the fuzzer.

Comment (aakoshh) [reply compiler/noirc_frontend/src/monomorphization/ast.rs]: I moved the `to_hir_type` back into the AST fuzzer module, so even though it needs to be maintained, it's not part of the public API. 

It is used not only for generating the signatures for functions, which are unused for all but the main, but also to:
* generate the type metadata for things passed to `println`
* generate `Match` statements, where it's used in the `Constructor`

File: compiler/noirc_frontend/src/monomorphization/mod.rs (hunk 3 above)
Comment (jfecher) [reply compiler/noirc_frontend/src/monomorphization/mod.rs:210]: > do I want the oracle/intrinsic/builtin resolves as a callable, or do I want it resolved into a proxy?

My idea to simplify things was to just always wrap oracles in an extra function wrapper

Comment (aakoshh) [reply compiler/noirc_frontend/src/monomorphization/mod.rs:210]: Right, I wasn't sure but suspected that might be what you meant, which is why I mentioned that Tom had the opposite expectation.

Comment (vezenovm) [reply compiler/noirc_frontend/src/monomorphization/mod.rs:210]: We do have a feature request to remove the need to wrap oracle calls in Noir code for direct calls as well https://github.com/noir-lang/noir/issues/9671. Perhaps it would be simplest to just wrap all oracles in the necessary function wrapper. We do not then have to distinguish between functions called directly or called by value. #9671
was originally low priority from a pure UX standpoint, but now that we have some cases where a missing wrapper causes bugs we might just want to always auto-gen the wrapper ourselves in all cases.

Comment (aakoshh) [reply compiler/noirc_frontend/src/monomorphization/mod.rs:210]: Just for clarification: despite the title (now changed to remove `#[oracle]`), this function handles intrinsics, built-in, and oracle functions as well, while #9671 is specifically about oracles.

Comment (vezenovm) [reply compiler/noirc_frontend/src/monomorphization/mod.rs:210]: > Just for clarification: despite the title (now changed to remove `#[oracle]`), this function handles intrinsics, built-in, and oracle functions as well, while #9671 is specifically about oracles.

Yeah I see that now. We may have to make this wrapper for all these cases. It is a bit unfortunate for intrinsics but the wrapper should be removed during inlining.

Comment (vezenovm) [reply compiler/noirc_frontend/src/monomorphization/mod.rs:210]: I am going to look if this can be easily done in the elaborator.

Comment (vezenovm) [reply compiler/noirc_frontend/src/monomorphization/mod.rs:210]: I have a draft that works for oracles. I will branch off of this PR.

Comment (vezenovm) [reply compiler/noirc_frontend/src/monomorphization/mod.rs:210]: Wrapping in the elaborator can be found here https://github.com/noir-lang/noir/pull/10351. @jfecher what do you think about going this route? 

If we figure out a nice way to do it for intrinsics as well we then get the benefit of #9671 also being resolved which provides a UX benefit.

Comment (jfecher) [reply compiler/noirc_frontend/src/monomorphization/mod.rs:210]: I do like the approach in that PR a bit better - I appreciate that it solves another issue and I think it'd require less upkeep over time. E.g. this PR requires we maintain a monomorphized type -> Hir type translation which isn't needed in the other PR.

It is a bit unfortunate how much work is involved in that PR just to create a wrapper function but that's a separate issue.

Comment (aakoshh) [reply compiler/noirc_frontend/src/monomorphization/mod.rs:210]: To be clear, the `ast::Type -> hir::Type` has to be maintained, just not in this module. I appreciate the fuzzer is not your concern, just wanted to say the code still exists and it's part of CI.

Comment (jfecher) [reply compiler/noirc_frontend/src/monomorphization/mod.rs:210]: > just wanted to say the code still exists and it's part of CI.

Ah, ok, thanks - I didn't realize that.

Comment (aakoshh) [reply compiler/noirc_frontend/src/monomorphization/mod.rs:210]: Yeah, like I said, the fuzzer needed this method to be able to produce the HIR types for `Match` and the meta-data for `println`. It is no longer used by the pass over the AST added in this PR; the proxy functions get the default signature instead.

On a different note, to answer the question in this thread, subjectively this PR feels _simpler_ to me: it doesn't need any modification to existing components to solve the issue in the ticket for all 3 kinds of foreign functions, while the alternative PR involves a bit of scope creep in its motivation to change the UX by removing the need for wrapping oracles, changing the language itself, relying on inlining to undo some of the "unfortunate" work it will do for built-ins and intrinsics. 

Since removing the pass in this PR is as easy as deleting a module and removing a line, I'd humbly put forward that we merge this, and then finish the alternative, so that it can properly focus on the UX aspect by removing the need for wrapping (that is, not rejecting unwrapped oracle functions), update the docs, etc. As I understand it will make this pass unneeded, since foreign functions will never appear as values, so it will be easy enough to delete the proxies module when it's done.

Comment (vezenovm) [reply compiler/noirc_frontend/src/monomorphization/mod.rs:210]: I am alright with merging this PR as I agree it is easy to revert and it fixes a bug.  

I do find https://github.com/noir-lang/noir/pull/10351 to be more correct as I would expect the elaborator to spit out a valid HIR (which means wrappers for oracle/intrinsic functions). But as you mentioned this would require some doc changes and other work so it can be done in a follow-up. I still have to look deeper and confirm, but I imagine the wrapping for intrinsics would be very similar to oracles.
