### PR TITLE
fix(ssa): Clear the SSA interpreter `call_stack` between top level calls

### LINKED ISSUE #10891: SSA interpreter `call_stack` not cleared between calls in constant folding
### Aim

Came up as an observation in https://github.com/noir-lang/noir/pull/10883

In `constant_folding::fold_constants_with_brillig` we reuse the same `Interpreter` instance, so that globals only have to be calculated once. If the call fails due to some constraint failure, the state of the interpreter will stay as is. https://github.com/noir-lang/noir/pull/10883 fixed the `side_effect_variable` to not affect the next call by moving the flat into the `CallContext`, however the `call_stack` stays.

The effect is that every time a call fails, we accumulate more `CallContext` in the stack that won't be cleared until we drop the interpreter instance. 

Luckily we don't use anything but the last and the first context in any function, so the correctness of the interpreter should not be affected. The only visible side effect is if one uses `--trace`, then we can see a `back in function ...` call after the top level function exits, if there was an earlier failure.

Here's some code to demonstrate:

```rust
fn main() {
    // safety: this will fail
    unsafe {
        bar(10);
    }
    // safety: this will succeed
    unsafe {
        foo(10);
        foo(20);
    }
}

unconstrained fn foo(x: u32) {
    assert(x != 0);
}
unconstrained fn bar(x: u32) {
    assert(x == 0);
}
```

### Expected Behavior

If `--trace` was enabled, we should see:
```
enter function bar
enter function foo
exit function foo
enter function foo
exit function foo
```
Note that `bar` never prints `exit` because it fails.

### Bug

```console
$ cargo run -q -p nargo_cli -- interpret --force --show-ssa-pass "step 41" --show-ssa-pass "step 42" --ssa-pass "step 42"

After Constant Folding using constraints (step 41):
acir(inline) predicate_pure fn main f0 {
  b0():
    call f1(u32 10)
    call f2(u32 10)
    call f2(u32 20)
    return
}
brillig(inline) predicate_pure fn bar f1 {
  b0(v0: u32):
    constrain v0 == u32 0
    return
}
brillig(inline) predicate_pure fn foo f2 {
  b0(v0: u32):
    v2 = eq v0, u32 0
    constrain v2 == u1 0
    return
}


enter function f1 (bar)
v0 = u32 10

enter function f2 (foo)
v0 = u32 10
v2 = u1 0
exit function f2 (foo)

back in function f1 (bar)

enter function f2 (foo)
v0 = u32 20
v2 = u1 0
exit function f2 (foo)

back in function f1 (bar)
After Inlining Brillig Calls (step 42):
acir(inline) predicate_pure fn main f0 {
  b0():
    call f1(u32 10)
    return
}
brillig(inline) predicate_pure fn bar f1 {
  b0(v0: u32):
    constrain v0 == u32 0
    return
}
brillig(inline) predicate_pure fn foo f2 {
  b0(v0: u32):
    v2 = eq v0, u32 0
    constrain v2 == u1 0
    return
}

--- Interpreter result after Inlining Brillig Calls (step 42):
Err(constrain v0 == v1 failed:
    u32 10 != u32 0)
---
The interpreter encountered an error on one or more passes.
```

Notice how `back in function f1 (bar)` is displayed twice, even though `bar` obviously never calls `foo`.

The `reset_state` added in https://github.com/noir-lang/noir/pull/10883 could contains `self.call_stack.truncate(1)` to keep only the global context.

### To Reproduce

In order to demonstrate the bug, we need to enable tracing in constant folding:
```rust
let mut interpreter = Interpreter::new_from_functions(
                &brillig_functions,
                InterpreterOptions {
                    trace: true, // This is normally disabled
                    no_foreign_calls: true,
                    step_limit: Some(DEFAULT_INTERPRETER_STEP_LIMIT),
                    ..Default::default()
                },
                std::io::empty(),
            );
```

### Workaround

None

### Workaround Description

_No response_

### Additional Context

_No response_

### Project Impact

None

### Blocker Context

_No response_

### Nargo Version

nargo version = 1.0.0-beta.16 noirc version = 1.0.0-beta.16+01bd2cc7a9c8b5fb80df1b74ff5e7927b437a2ab (git version hash: e0058471230a3b1782cf31c1c49bb5c7096d7316, is dirty: true)

### NoirJS Version

_No response_

### Proving Backend Tooling & Version

_No response_

### Would you like to submit a PR for this Issue?

None

### Support Needs

_No response_

### PR DESCRIPTION
**Pull request by aakoshh**
# Description

## Problem

Resolves #10891 

## Summary

* Adds an `Interpreter::interpret_function` (similar to `Interpreter::interpret_globals` and `Ssa::interpret_function`) as an entry point for a top level function call. This function calls `Interpreter::call_function`, but before that it sets the `step_counter` to 0 and truncates the `call_stack` to 1, to make sure we don't carry over state from any previous calls. 
* Makes `Interpreter::call_function` private, so we always interact with the `interpret_*` methods.
* Removes `Interpreter::reset_step_counter`, as it is now included in the `interpret_function` method.

## User Documentation

Check one:
- [x] No user documentation needed.
- [ ] Changes in _docs/_ included in this PR.
- [ ] **[For Experimental Features]** Changes in _docs/_ to be submitted in a separate PR.

# PR Checklist

- [x] I have tested the changes locally.
- [ ] I have formatted the changes with [Prettier](https://prettier.io/) and/or `cargo fmt` on default settings.

### CODE REVIEW

File: compiler/noirc_evaluator/src/ssa/interpreter/mod.rs [hunk 1]
```diff
@@ -241,11 +238,24 @@ impl<'ssa, W: Write> Interpreter<'ssa, W> {
...
+    /// This resets any previous call stack and step counter.
+    pub(crate) fn interpret_function(
         &mut self,
         function_id: FunctionId,
-        mut arguments: Vec<Value>,
+        arguments: Vec<Value>,
     ) -> IResults {
+        self.step_counter = 0;
+        self.call_stack.truncate(1);
+        self.call_function(function_id, arguments)
```
Comment (TomAFrench) [inline compiler/noirc_evaluator/src/ssa/interpreter/mod.rs:251]: I'm wondering whether we need an assertion on here similar to how we do for `interpret_globals` to avoid the interpreter from being changed to call this internally rather than `call_function`.

Comment (TomAFrench) [reply compiler/noirc_evaluator/src/ssa/interpreter/mod.rs:251]: Not sure we can do this without requiring a 2 step process for what would now be an `interpret_function` call so 🤷

**Review by TomAFrench — APPROVED** [review]

File: compiler/noirc_evaluator/src/ssa/interpreter/mod.rs (hunk 1 above)
Comment (aakoshh) [reply compiler/noirc_evaluator/src/ssa/interpreter/mod.rs:251]: I don't think we can do so, because in `interpret_globals` I'm asserting that `call_stack` only has 1 item, but here I know it can have multiple items if the previous call errored out on some instruction. We _could_ catch that and reset the state in `interpret_call` itself, but then, should we want to provide a call stack with the error, it should change the return type to include any useful context that still ives in `call_stack`. 

But in general, I added the assertion to `interpret_globals` because it's a public function, and calling it after a failed call would I imagine insert the variables into the last faulty context, rather than the globals, which then would be lost when we call this method. 

OTOH I think we can say that _not_ calling this method internally is the responsibility of the developer who understands the `Interpreter`, and should know how to operate the private methods correctly.
