### PR TITLE
fix: SignedField Eq and Hash implementations

### LINKED ISSUE #10621: Field equality in comptime somtimes doesn't hold
### Aim

This code:

```noir
fn main() {
    comptime {
        let x = -1;
        let y = 0x30644e72e131a029b85045b68181585d2833e84879b9709143e1f593f0000000;
        assert_eq(x, y);
    }
}
```

fails to compile (the assertion fails). However, they both represent the same value.

In non-comptime code it compiles fine:

```noir
fn main() {
    let x = -1;
    let y = 0x30644e72e131a029b85045b68181585d2833e84879b9709143e1f593f0000000;
    assert_eq(x, y);
}
```

The reason is that the `Eq` and `PartialEq` impl for `SignedField` compare `is_negative` and `field` separately, but this shouldn't be done if the underlying type is Field.

Used in these test programs: regression_8755, regression_9208, regression_9303

### Expected Behavior

The code should compile.

### Bug

It doesn't compile.

### To Reproduce

1.
2.
3.
4.

### Workaround

None

### Workaround Description

_No response_

### Additional Context

_No response_

### Project Impact

None

### Blocker Context

_No response_

### Nargo Version

_No response_

### NoirJS Version

_No response_

### Proving Backend Tooling & Version

_No response_

### Would you like to submit a PR for this Issue?

None

### Support Needs

_No response_

### PR DESCRIPTION
**Pull request by asterite**
# Description

## Problem

Resolves #10621

## User Documentation

Check one:
- [x] No user documentation needed.
- [ ] Changes in _docs/_ included in this PR.
- [ ] **[For Experimental Features]** Changes in _docs/_ to be submitted in a separate PR.

# PR Checklist

- [x] I have tested the changes locally.
- [x] I have formatted the changes with [Prettier](https://prettier.io/) and/or `cargo fmt` on default settings.

### CODE REVIEW

File: compiler/noirc_frontend/src/signed_field.rs [hunk 1]
```diff
@@ -436,4 +461,13 @@ mod tests {
...
         assert_eq!(SignedField::from(i128::MIN + 1).to_i128(), i128::MIN + 1);
     }
+
+    #[test]
+    fn equality() {
+        let a = SignedField::negative(FieldElement::one());
+        let b = SignedField::positive(-FieldElement::one());
+        assert_eq!(a, a);
+        assert_eq!(b, b);
+        assert_eq!(a, b);
```
Comment (vezenovm) [inline compiler/noirc_frontend/src/signed_field.rs:471]:
```suggestion
        assert_eq!(a, b);
        assert_eq!(b, a);
```
Should we just cover all cases? I only mention this because we only negate the rhs in the `PartialEq` impl
