### PR TITLE
fix: transform into constrain_not_equal outside enable_side_effects

### LINKED ISSUE #10929: `make_constrain_not_equal` pass results in difference in SSA interpreter output
The fuzzer has detected that interpreting the below program changes result after the `make_constrain_not_equal` pass.

```noir
fn main(mut a: pub Field, b: pub bool) -> pub u128 {
        let mut ctx_limit: u32 = 25_u32;
        if (unsafe { func_3_proxy(322326658008292202661234090600460777756_u128, ctx_limit) } >= unsafe { func_3_proxy(273818118061596656641966752267043936186_u128, ctx_limit) }) {
            a = a;
            assert((if b {
                unsafe { func_3_proxy((a as u128), ctx_limit) }
            } else {
                (a as u128)
            } != (a as u128)), "QPA");
            {
                let c = a;
                match c {
                    182371754848183609373039506320688229211 => (),
                    _ => {
                        let d = b;
                        match d {
                            
                            _ => {
                                a = {
                                    {
                                        let e = b;
                                        match e {
                                            false => (),
                                            false => (),
                                            _ => {
                                                a = (unsafe { func_3_proxy(38135835996832772550011944599143641109_u128, ctx_limit) } as Field);
                                                a = -if b {
                                                    (a / (b as Field))
                                                } else {
                                                    (b as Field)
                                                };
                                                a = a;
                                            },
                                        }
                                    };
                                    (b as Field)
                                };
                                a = 29086135136495469340643132352324776904;
                            },
                        }
                    },
                }
            };
            (a as u128)
        } else {
            184539200160576198489113337810682205219_u128
        }
    }
    unconstrained fn func_3(mut a: u128, _ctx_limit: &mut u32) -> u128 {
        if false {
            {
                let mut idx_b: u32 = 0_u32;
                loop {
                    if (idx_b == 5_u32) {
                        break
                    } else {
                        idx_b = (idx_b + 1_u32);
                        for idx_c in 19_u8 .. 24_u8 {
                            assert((if true {
                                let d = idx_c;
                                match d {
                                    
                                    _ => 13422469849279651987_u64,
                                }
                            } else {
                                12449225912920832957_u64
                            } >= (idx_c as u64)), "UDB");
                            continue;
                        };
                        for idx_e in -2607797929310401928_i64 .. -2607797929310401924_i64 {
                            break;
                            {
                                let mut idx_f: u32 = 0_u32;
                                while false {
                                    if (idx_f == 3_u32) {
                                        break
                                    } else {
                                        idx_f = (idx_f + 1_u32);
                                        println(idx_e);
                                        break;
                                    }
                                }
                            };
                        };
                        assert((153598641187101191142514484530191480170_u128 <= 68035476338953489591340303022185605724_u128), "VVU");
                    }
                }
            };
            158412214502149019484161754799452040040_u128
        } else {
            239001476155835873462206944775311375441_u128
        }
    }
    unconstrained fn func_3_proxy(mut a: u128, mut ctx_limit: u32) -> u128 {
        func_3(a, (&mut ctx_limit))
    }

```

### PR DESCRIPTION
**Pull request by guipublic**
# Description

## Problem

Resolves #10929 

## Summary
Do not substitute constrain with constrain_not_equal when there are side_effects.

## User Documentation

Check one:
- [X] No user documentation needed.
- [ ] Changes in _docs/_ included in this PR.
- [ ] **[For Experimental Features]** Changes in _docs/_ to be submitted in a separate PR.

# PR Checklist

- [X] I have tested the changes locally.
- [X] I have formatted the changes with [Prettier](https://prettier.io/) and/or `cargo fmt` on default settings.

### CODE REVIEW

**Comment by guipublic** [comment]
> This seems like a hack which doesn't resolve the underlying issue. I can see handling for a predicate in the SSA interpreter (and also in ACIRgen, although unrelated to this fuzzing failure) and so we should nail down why that handling is not working.

The SSA semantic is modified by the make_constrain_not_equal pass if there is enable_side_effect, because it transforms a constrain into a constrain_not_equal. But they behave differently in case of enable_side_effect. So the issue is not in the interpreter.

**Comment by TomAFrench** [comment]
In ACIRgen we're passing in `current_side_effects_enabled_var` as a predicate to `ConstrainNotEqual`

https://github.com/noir-lang/noir/blob/f1d6f5601135f38c5b76ebb6b4c438a01c314c8a/compiler/noirc_evaluator/src/acir/mod.rs#L444-L448

This then disables the constraint that an inverse must exist for `lhs - rhs` so we're disabling the instruction

https://github.com/noir-lang/noir/blob/f1d6f5601135f38c5b76ebb6b4c438a01c314c8a/compiler/noirc_evaluator/src/acir/acir_context/mod.rs#L518-L521

In the SSA interpreter we explicitly look at whether side effects are enabled and skip the check if they aren't.

https://github.com/noir-lang/noir/blob/f1d6f5601135f38c5b76ebb6b4c438a01c314c8a/compiler/noirc_evaluator/src/ssa/interpreter/mod.rs#L614C27-L636

We're clearly attempting to have this instruction respond to the side effects variable so that it doesn't trigger a failure if it's zero. `ConstrainNotEqual` _should_ be disabled by `enable_side_effects` so it's incorrect to just say "oh well, let's just disable it" because then we have all this logic which is being made irrelevant.

**Comment by aakoshh** [comment]
Could you take the integration test I added in https://github.com/noir-lang/noir/pull/10936 to this PR as well? At least that's what I usually do: take the minimised program as an integration test, and come up with a simplified SSA in a unit test that shows just enough of the problem to act as a "specification".

File: compiler/noirc_evaluator/src/ssa/opt/make_constrain_not_equal.rs [hunk 1]
```diff
@@ -137,4 +149,32 @@ mod tests {
...
+            v15 = not v1
+            v17 = truncate v0 to 128 bits, max_bit_size: 254
+            v18 = cast v17 as u128
+            v19 = cast v1 as u128
+            v20 = cast v15 as u128
+            v21 = unchecked_mul v19, u128 239001476155835873462206944775311375441
+            v22 = unchecked_mul v20, v18
+            v23 = unchecked_add v21, v22
+            v26 = eq v23, v18
+            constrain v26 == u1 0, "QPA"
```
Comment (aakoshh) [inline compiler/noirc_evaluator/src/ssa/opt/make_constrain_not_equal.rs]:
```suggestion
            enable_side_effects v1            
            constrain v0 == u1 0
```
That would be enough I think, and the complex stuff could be in the regression test.

File: compiler/noirc_evaluator/src/ssa/opt/make_constrain_not_equal.rs [hunk 2]
```diff
@@ -137,4 +149,32 @@ mod tests {
...
         assert_ssa_does_not_change(src, Ssa::make_constrain_not_equal);
     }
+
+    #[test]
+    /// https://github.com/noir-lang/noir/issues/10929
+    /// When side effects is not one, the transformation
+    /// should NOT happen because `Constrain` and `ConstrainNotEqual` have different
+    /// semantics with respect to `enable_side_effects`:
+    /// - `Constrain` ignores `enable_side_effects` (always executes)
+    /// - `ConstrainNotEqual` respects `enable_side_effects` (only executes when enabled)
```
Comment (aakoshh) [inline compiler/noirc_evaluator/src/ssa/opt/make_constrain_not_equal.rs:159]:
```suggestion
    /// - `Constrain` ignores `enable_side_effects` (always executes)
    /// - `ConstrainNotEqual` respects `enable_side_effects` (only executes when enabled)
    /// Because `Constrain` ignores side effects, during the `remove_enable_side_effects`
    /// pass it might end up under a different side effect than it started with after flattening, 
    /// which makes it unsafe to transform it into `ConstrainNotEqual`. Since we don't validate
    /// whether an arbitrary SSA has a side effect variable above `Constrain` which is compatible
    /// with its variables, the conservative thing to do is to only transform if we know it it is safe.
```

File: compiler/noirc_evaluator/src/ssa/opt/make_constrain_not_equal.rs [hunk 3]
```diff
@@ -137,4 +149,28 @@ mod tests {
...
+    /// whether an arbitrary SSA has a side effect variable above `Constrain` which is compatible
+    /// with its variables, the conservative thing to do is to only transform if we know it it is safe.
+    fn regression_10929() {
+        let src = r#"
+        acir(inline) predicate_pure fn main f0 {
+          b0(v0: Field, v1: u1):
+            enable_side_effects v1            
+            constrain v0 == u1 0
+            return
+        }
```
Comment (TomAFrench) [inline compiler/noirc_evaluator/src/ssa/opt/make_constrain_not_equal.rs:174]:
```suggestion
        acir(inline) predicate_pure fn main f0 {
          b0(v0: Field, v1: Field, v2: u1):
            enable_side_effects v2
            v3 = eq v0, v1
            constrain v3 == u1 0
            return
        }
```

Pulling this from my PR as the existing code doesn't follow type rules and wouldn't trigger the neq optimization anyway.

File: compiler/noirc_evaluator/src/ssa/opt/make_constrain_not_equal.rs [hunk 4]
```diff
@@ -137,4 +149,29 @@ mod tests {
...
+
+    #[test]
+    /// https://github.com/noir-lang/noir/issues/10929
+    /// When side effects is not one, the transformation
+    /// should NOT happen because `Constrain` and `ConstrainNotEqual` have different
+    /// semantics with respect to `enable_side_effects`:
+    /// - `Constrain` ignores `enable_side_effects` (always executes)
+    /// - `ConstrainNotEqual` respects `enable_side_effects` (only executes when enabled)
+    /// Because `Constrain` ignores side effects, during the `remove_enable_side_effects`
+    /// pass it might end up under a different side effect than it started with after flattening,
```
Comment (TomAFrench) [inline compiler/noirc_evaluator/src/ssa/opt/make_constrain_not_equal.rs]:
```suggestion
    /// pass it might end up under a different side effect than it started with after flattening,
```

File: compiler/noirc_evaluator/src/ssa/opt/make_constrain_not_equal.rs [hunk 5]
```diff
@@ -137,4 +149,29 @@ mod tests {
...
     }
+
+    #[test]
+    /// https://github.com/noir-lang/noir/issues/10929
+    /// When side effects is not one, the transformation
+    /// should NOT happen because `Constrain` and `ConstrainNotEqual` have different
+    /// semantics with respect to `enable_side_effects`:
+    /// - `Constrain` ignores `enable_side_effects` (always executes)
+    /// - `ConstrainNotEqual` respects `enable_side_effects` (only executes when enabled)
+    /// Because `Constrain` ignores side effects, during the `remove_enable_side_effects`
```
Comment (TomAFrench) [inline compiler/noirc_evaluator/src/ssa/opt/make_constrain_not_equal.rs:161]:
```suggestion
    ///
    /// Because `Constrain` ignores side effects, during the `remove_enable_side_effects`
```

**Review by TomAFrench — APPROVED** [review]
