### PR TITLE
fix(compiler): Improve error message for impl on primitive types (#10430)

### LINKED ISSUE #10430: Error message when writing `impl` for primitive type could be improved
This code:

```noir
impl i32 {}

fn main() {}
```

gives this error:

```
error: Non-struct type used in impl
  ┌─ src/main.nr:5:6
  │
5 │ impl Alias {}
  │      ----- Only struct types may have implementation methods
```

The error is not telling the truth: primitive types can have implementation methods, it's just that they must be defined in the standard library crate.

The same Rust code gives this error:

```
error[E0390]: cannot define inherent `impl` for primitive types
 --> foo/src/main.rs:1:1
  |
1 | impl i32 {}
  | ^^^^^^^^
  |
  = help: consider using an extension trait instead
```

which is slightly better.

### PR DESCRIPTION
**Pull request by CECILIA-MULANDI**
The error message now correctly distinguishes between primitive types (which can have impls in stdlib) and other non-struct types (which cannot have impls). This matches Rust's error message style.

# Description

## Problem

Resolves #10430

## Summary

Improves the error message when attempting to define `impl` for primitive types.
The previous message incorrectly stated that primitive types cannot have 
implementation methods. The new message clarifies that primitive types can 
have impls, but only when defined in the standard library.

## Additional Context

The error message now correctly distinguishes between primitive types 
(which can have impls in stdlib) and other non-struct types (which 
cannot have impls). This matches Rust's error message style.

## Changes
- Updated `NonStructTypeInImpl` error enum to track if type is primitive
- Show different error messages for primitive vs other non-struct types
- Updated tests and snapshots to match new error messages

## User Documentation

Check one:

- [x] No user documentation needed.

- [ ] Changes in _docs/_ included in this PR.

- [ ] **[For Experimental Features]** Changes in _docs/_ to be submitted in a separate PR.

# PR Checklist

- [x] I have tested the changes locally.

- [x] I have formatted the changes with [Prettier](https://prettier.io/) and/or `cargo fmt` on default settings.

### CODE REVIEW

File: compiler/noirc_frontend/src/hir/def_collector/errors.rs [hunk 1]
```diff
@@ -193,11 +193,21 @@ impl<'a> From<&'a DefCollectorErrorKind> for Diagnostic {
...
-            DefCollectorErrorKind::NonStructTypeInImpl { location } => Diagnostic::simple_error(
-                "Non-struct type used in impl".into(),
-                "Only struct types may have implementation methods".into(),
-                *location,
-            ),
+            DefCollectorErrorKind::NonStructTypeInImpl { location, is_primitive } =>{
+                if *is_primitive {
+                    Diagnostic::simple_error(
+                        "cannot define inherent `impl` for primitive types".into(),
+                        "primitive types can only have implementation methods defined in the standard library".into(),
```
Comment (jfecher) [inline compiler/noirc_frontend/src/hir/def_collector/errors.rs]:
```suggestion
                        "Cannot define inherent `impl` for primitive types".into(),
                        "Primitive types can only have implementation methods defined in the standard library".into(),
```

File: compiler/noirc_frontend/src/tests/structs.rs [hunk 2]
```diff
@@ -222,8 +222,8 @@ fn errors_on_impl_for_primitive_type_outside_stdlib() {
     let src = r#"
     // User code (not stdlib) cannot impl methods on primitive types
     impl Field {
-         ^^^^^ Non-struct type used in impl
-         ~~~~~ Only struct types may have implementation methods
+         ^^^^^ cannot define inherent `impl` for primitive types
+         ~~~~~ primitive types can only have implementation methods defined in the standard library
```
Comment (jfecher) [inline compiler/noirc_frontend/src/tests/structs.rs]:
```suggestion
         ^^^^^ Cannot define inherent `impl` for primitive types
         ~~~~~ Primitive types can only have implementation methods defined in the standard library
```

File: tooling/nargo_cli/tests/snapshots/compile_failure/dep_impl_primitive/execute__tests__stderr.snap [hunk 3]
```diff
@@ -9,11 +9,11 @@ warning: unused import bad_impl
   │     -------- unused import
   │
 
-error: Non-struct type used in impl
+error: cannot define inherent `impl` for primitive types
```
Comment (jfecher) [inline tooling/nargo_cli/tests/snapshots/compile_failure/dep_impl_primitive/execute__tests__stderr.snap]:
```suggestion
error: Cannot define inherent `impl` for primitive types
```

File: tooling/nargo_cli/tests/snapshots/compile_failure/dep_impl_primitive/execute__tests__stderr.snap [hunk 4]
```diff
@@ -9,11 +9,11 @@ warning: unused import bad_impl
...
   ┌─ test_programs/test_libraries/bad_impl/src/lib.nr:1:6
   │
 1 │ impl Field {
-  │      ----- Only struct types may have implementation methods
+  │      ----- primitive types can only have implementation methods defined in the standard library
```
Comment (jfecher) [inline tooling/nargo_cli/tests/snapshots/compile_failure/dep_impl_primitive/execute__tests__stderr.snap]:
```suggestion
  │      ----- Primitive types can only have implementation methods defined in the standard library
```
