### PR TITLE
fix(nargo): Make dependencies section optional in TOML

### LINKED ISSUE #2114: Nargo.toml package config requires dependency section
### Aim

Currently, a Nargo.toml configured in "package"-style requires the `[dependencies]` section even if you have no dependencies.

### Expected Behavior

This section should not be required.

### Bug

Nargo crashes with an error that says your Nargo.toml is malformed if you don't have this section.

### To Reproduce

1.
2.
3.
4.

### Installation Method

None

### Nargo Version

_No response_

### Additional Context

_No response_

### Would you like to submit a PR for this Issue?

Maybe

### Support Needs

_No response_

### PR DESCRIPTION
**Pull request by phated**
# Description

## Problem\*

Resolves #2114 

## Summary\*

This makes the `[dependencies]` section of the Nargo.toml optional because it is weird that we'd require the section if we have no dependencies.

## Documentation

- [ ] This PR requires documentation updates when merged.

  

  - [ ] I will submit a noir-lang/docs PR.

  

  - [ ] I will request for and support Dev Rel's help in documenting this PR.

  
  

## Additional Context

# PR Checklist\*

- [x] I have tested the changes locally.
- [x] I have formatted the changes with [Prettier](https://prettier.io/) and/or `cargo fmt` on default settings.

### CODE REVIEW

File: crates/nargo_cli/src/manifest.rs [hunk 1]
```diff
@@ -15,19 +15,21 @@ use crate::{errors::ManifestError, git::clone_git_repo};
 #[derive(Debug, Deserialize, Clone)]
 struct PackageConfig {
     package: PackageMetadata,
-    dependencies: BTreeMap<String, DependencyConfig>,
+    dependencies: Option<BTreeMap<String, DependencyConfig>>,
```
Comment (TomAFrench) [inline crates/nargo_cli/src/manifest.rs:18]:
```suggestion
    #[serde(default)]
    dependencies: BTreeMap<String, DependencyConfig>,
```

Thoughts on this solution instead? This keeps our own logic cleaner imo

Comment (phated) [reply crates/nargo_cli/src/manifest.rs:18]: I generally like to be explicit when things are optional, but I don't have a preference here. I'll try it locally and push

Comment (phated) [reply crates/nargo_cli/src/manifest.rs]: Done!

**Review by TomAFrench — APPROVED** [review]
