### PR TITLE
fix(acir): Array dynamic flatten

### LINKED ISSUE #4258: Compiler panics with `Cannot flatten a dynamic array` when returning an array from memory
### Aim

I would like to prove the following program

```rust
fn main(mut x: [Field; 256], index: u8) -> pub [Field; 256] {
    x[index] = 0;
    x
}
```

### Expected Behavior

This should be able to be compiled to a circuit where I write `x` into memory, write `0` at index `index` in this memory, then read out the entirety of the block of memory to form the return value.

### Bug

The compiler panics with 

```
The application panicked (crashed).
Message:  internal error: entered unreachable code: Cannot flatten a dynamic array
Location: compiler/noirc_evaluator/src/ssa/acir_gen/acir_ir/acir_variable.rs:1411

This is a bug. We may have already fixed this in newer versions of Nargo so try searching for similar issues at https://github.com/noir-lang/noir/issues/.
If there isn't an open issue for this bug, consider opening one at https://github.com/noir-lang/noir/issues/new?labels=bug&template=bug_report.yml
```

### To Reproduce

1. compile the above program

### Installation Method

Compiled from source

### Nargo Version

noirc version = 0.23.0+bdf64ed81d7f34d6478ed9bde5b69e45d171d5f0

### Additional Context

_No response_

### Would you like to submit a PR for this Issue?

No

### Support Needs

_No response_

### PR DESCRIPTION
**Pull request by vezenovm**
# Description

## Problem\*

Resolves #4258 

## Summary\*

There are some instances where we want to flatten a single AcirValue into its AcirVars. We were operating under the assumption that we cannot flatten dynamic arrays. I have changed the `flatten` method to be on an `AcirContext` so that we can read from dynamic memory when appropriate. 

I have added two tests performing what is done in the issue.
1. Returning a dynamic array from main
2. Preparing a dynamic array as inputs to a black box function

## Additional Context

Further investigation should be done to see if we should fully remove the `flatten()` method on `AcirValue` and move to only using the `flatten` which lives on the AcirContext. I chose to leave that for separate work though and scope this PR to just the bug fix in the issue.

## Documentation\*

Check one:
- [X] No documentation needed.
- [ ] Documentation included in this PR.
- [ ] **[Exceptional Case]** Documentation to be submitted in a separate PR.

# PR Checklist\*

- [X] I have tested the changes locally.
- [X] I have formatted the changes with [Prettier](https://prettier.io/) and/or `cargo fmt` on default settings.

### CODE REVIEW

**Review by jfecher — APPROVED** [review]
:+1:

File: compiler/noirc_frontend/src/debug/mod.rs [hunk 1]
```diff
@@ -470,21 +471,24 @@ pub fn build_debug_crate_file() -> String {
         .to_string(),
         (1..=MAX_MEMBER_ASSIGN_DEPTH)
             .map(|n| {
+                // The variable signature has to be generic as Noir supports using any polymorphic integer as an index.
+                // If we were to set a specific type for index signatures here, such as `Field`, we will error in
+                // type checking if we attempt to index with a different type such as `u8`.
                 let var_sig =
-                    (0..n).map(|i| format!["_v{i}: Field"]).collect::<Vec<String>>().join(", ");
```
Comment (vezenovm) [inline compiler/noirc_frontend/src/debug/mod.rs:474]: For the new `array_dynamic_main_output` test I was hitting these errors only in the debugger:
```
error: Expected type Field, found type u8
  ┌─ /mnt/user-data/maxim/noir/test_programs/execution_success/array_dynamic_main_output/src/main.nr:2:7
  │
2 │     x[index] = 0;
  │       -----
  │
Aborting due to 1 previous error
```
It was due to us specifying that we want a `Field` when indices can be any polymorphic integer as mentioned in the comment. Pinging @ggiraldez @mverzilli for awareness. I did the fix in this PR rather than a separate one as it is pretty contained.

**Comment by vezenovm** [comment]
Pinging this discussion to the main thread so it does not get lost (https://github.com/noir-lang/noir/pull/4351#discussion_r1486908013). We were hitting type checking errors in the debugger but not with normal execution. This is due to some errors in the debugger instrumentation. We should probably consider whether we want the debugger to run in a separate repo/CI as the debugger is currently blocking this PR with a compiler fix from being merged.

**Comment by ggiraldez** [comment]
> Pinging this discussion to the main thread so it does not get lost ([#4351 (comment)](https://github.com/noir-lang/noir/pull/4351#discussion_r1486908013)). We were hitting type checking errors in the debugger but not with normal execution. This is due to some errors in the debugger instrumentation. We should probably consider whether we want the debugger to run in a separate repo/CI as a bug scoped only to the debugger blocked this PR with a compiler fix from being merged. (Of course I could have switched `index` to use a Field but I feel modifying our tests to pass errors in the debugger is not the way to go).

It's not ideal, but we have a list of cases to ignore for the debugger. See the file `tooling/debugger/ignored-tests.txt`. We are aware that there are some edge cases we're still not handling correctly and because we're reusing the same cases as execution success, we adopted this mechanism.

**Review by TomAFrench — APPROVED** [review]

**Comment by TomAFrench** [comment]
Huh, looks like the rust tests are failing on here but merging isn't being blocked.
