### PR TITLE
fix: correct size for HeapValueType::Array size

### LINKED ISSUE #11125: Semantic vs semi-flattened size mismatch causes incorrect foreign call handling
This is a mirror of https://audithub.veridise.com/app/organizations/161/projects/521/project-viewer?version=1201&issue=747

---

<h2 data-pm-slice="1 1 []">Description</h2><p>Noir programs can invoke external functions through foreign calls. When the Brillig codegen encounters an SSA <code>Instruction::Call</code> targeting a <code>Value::ForeignFunction</code>, it emits an <code>Opcode::ForeignCall</code> via <code>convert_ssa_foreign_call()</code> in <code>brillig_call/code_gen_call.rs</code>. This opcode is built from four components: input values and types, and output values and types. These are derived through a pipeline that converts SSA types → Brillig variables (<code>Vec&lt;ValueOrArray&gt;</code>) → foreign call descriptors (<code>Vec&lt;HeapValueType&gt;</code>).</p><p>In SSA, arrays and slices may contain tuples, but SSA has no tuple type. Instead, tuple elements are flattened into a <code>CompositeType = Vec&lt;Type&gt;</code>. Arrays and slices are represented as:</p><ul><li><p><code>Type::Array(CompositeType, semantic_length)</code>.</p></li><li><p><code>Type::Slice(CompositeType)</code>.</p></li></ul><p>The <strong>semantic length</strong> corresponds to the number of elements in Noir, while <code>element_size()</code> (defined in <code>ssa/ir/types.rs</code>) returns the width of each element after tuple flattening, the length of the <code>CompositeType</code> vector. For example, for a Noir type <code>[(u32, bool); 3]</code>:</p>

Component | Value | Meaning
-- | -- | --
CompositeType | [u32, bool] | Flattened tuple fields
Semantic length | 3 | Number of tuples in the array
element_size() | 2 | Width of the tuple (CompositeType.len())

<p>When SSA values are lowered to Brillig, arrays allocate <code>element_size × semantic_length</code> memory slots, producing a <strong>semi-flattened size</strong> (via <code>allocate_value_with_type()</code> in <code>brillig_block_variables.rs</code>). This size is stored in <code>BrilligArray.size</code> and propagated unchanged into foreign call value descriptors (<code>HeapArray.size</code>). Similarly, when SSA types are converted to foreign call type descriptors via <code>type_to_heap_value_type()</code> in <code>brillig_variable.rs</code>, <code>HeapValueType::Array.size</code> is set to this same semi-flattened size:</p><pre><code class="language-rust">Type::Array(elem_type, size) =&gt; HeapValueType::Array {
    value_types: elem_type.as_ref().iter().map(type_to_heap_value_type).collect(),
    size: typ.element_size() * *size as usize,  // semi-flattened size
},
</code></pre><p>The <code>value_types</code> field captures the flattened tuple structure. As a result, both the data (<code>HeapArray</code> and <code>HeapVector</code>) and the type descriptor (<code>HeapValueType::Array</code>) consistently encode sizes as semi-flattened memory sizes, not semantic lengths.</p><p>However, the VM runtime in <code>acvm-repo/brillig_vm/src/foreign_call.rs</code> inconsistently interprets these size fields. The <code>flattened_size()</code> method in <code>acvm-repo/brillig/src/opcodes.rs</code> treats the <code>size</code> field as a semantic length and multiplies by element size:</p><pre><code class="language-rust">HeapValueType::Array { value_types, size } =&gt; {
    let element_size =
        value_types.iter().map(|t| t.flattened_size()).sum::&lt;Option&lt;usize&gt;&gt;();
    element_size.map(|element_size| element_size * size)
}
</code></pre><p>This double-multiplication leads to incorrect calculations for arrays/slices of tuples. The following sections detail where this mismatch manifests.</p><h2>Impact</h2><h3>1. Foreign Call Slice Input Truncation</h3><p>Before passing slice inputs to a foreign call, <code>process_foreign_call()</code> truncates data to remove trailing garbage. The truncation length is computed as <code>semantic_length × type_size</code>, where <code>type_size</code> is obtained via <code>vector_element_size()</code>:</p><pre><code class="language-rust">HeapValueType::Vector { value_types } =&gt; {
    if let Some(length) = vector_length {
        let type_size = vector_element_size(value_types);
        let mut fields = input.fields();
        fields.truncate(length * type_size);
        ...
    }
}
</code></pre><p>For example, consider a slice of nested arrays <code>[[(u32, u32); 3]]</code> with semantic length 2:</p><ul><li><p>Codegen sets the nested array's <code>size</code> to 6 (semi-flattened: 3 tuples × 2 fields).</p></li><li><p>At runtime, <code>flattened_size()</code> computes <code>(1+1) × 6 = 12</code> instead of the correct 6.</p></li><li><p>Truncation keeps <code>2 × 12 = 24</code> fields instead of the correct 12, exposing the dummy data.</p></li></ul><h3>2. Array Output Size Validation</h3><p>When writing foreign call results to an array destination in <code>write_foreign_call_result()</code>, the VM validates that the returned data matches the expected size:</p><pre><code class="language-rust">if value_type
    .flattened_size()
    .is_some_and(|flattened_size| output_fields.len() != flattened_size)
{
    return Err(format!(
        "Foreign call return value does not match expected size. Expected {} but got {}",
        value_type.flattened_size().unwrap(),
        output_fields.len(),
    ));
}
</code></pre><p>Since <code>flattened_size()</code> interprets <code>HeapValueType::Array.size</code> as a semantic length and multiplies by element width, it computes an incorrect expected size for arrays of tuples.</p><p>For example, for an output array of type <code>[(u32, bool); 3]</code>:</p><ul><li><p>Codegen sets <code>size = 6</code> (semi-flattened).</p></li><li><p>At runtime, <code>flattened_size()</code> computes <code>(1+1) × 6 = 12</code>.</p></li><li><p>If the foreign call correctly returns 6 fields, the validation fails with "Expected 12 but got 6".</p></li></ul><h3>3. Redundant Branch in All-Simple Array Handling</h3><p>When writing array output where <code>all_simple(value_types)</code> is true, the code checks <code>values.len() != *size</code> to decide between two write paths:</p><pre><code class="language-rust">if values.len() != *size {
    // write flattened values path
} else {
    self.write_values_to_memory(*pointer, true, values, value_types)?;
}
</code></pre><p>In the all-simple case, the flattened size (<code>values.len()</code>) and the semi-flattened size (<code>size</code>) should always be equal. This condition should either be removed or replaced with an <code>unreachable!()</code> panic to assert the invariant and catch unexpected violations.</p><h3>4. Flattened Values Write Over-Read</h3><p>When <code>write_flattened_values_to_memory()</code> writes foreign call results to a nested array destination, it uses a nested loop structure:</p><p>This loop writes <code>size × value_types.len()</code> values. If <code>size</code> represents the semi-flattened size (as set by codegen), the tuple width is double-counted. For example, with an array type <code>[(u32, u32); 3]</code>:</p><pre><code class="language-rust">HeapValueType::Array { value_types, size } =&gt; {
    let mut current_pointer = destination;
    for _ in 0..*size {
        for typ in value_types {
            match typ {
                HeapValueType::Simple(bit_size) =&gt; {
                    self.write_value_to_memory(current_pointer, &amp;values[*values_idx], *bit_size)?;
                    *values_idx += 1;
                    current_pointer = current_pointer.offset(1);
                }
                ...
            }
        }
    }
}
</code></pre><ul><li><p>Codegen sets <code>size = 6</code> (semi-flattened: 3 tuples × 2 fields).</p></li><li><p><code>value_types = [Simple(u32), Simple(u32)]</code> (length 2).</p></li><li><p>Loop attempts to write <code>6 × 2 = 12</code> values and advances <code>values_idx</code> 12 times.</p></li><li><p>But the actual flattened data contains only 6 values.</p></li></ul><p>This causes a buffer over-read from the <code>values</code> array, potentially reading garbage data or causing an index out-of-bounds panic. If the over-read doesn't panic, the extra garbage values are written to heap memory, corrupting subsequent data structures.</p><h2>Recommendation</h2><p>The core issue is semantic ambiguity in size interpretation. During codegen, size fields in Brillig values (<code>HeapArray.size</code>, <code>HeapVector.size</code>) and type descriptors (<code>HeapValueType::Array.size</code>) are set to the <strong>semi-flattened size</strong>, the total memory slots accounting for tuple element widths. However, VM runtime paths inconsistently interpret these same fields as <strong>semantic lengths</strong> and re-multiply by element widths, causing double-counting for arrays/slices of tuples.</p>

### LINKED ISSUE #11166: Unused mutation in `brillig_gen/entry_point.rs`
I'm getting a warning in vscode that we're mutating `array.size` here but never use the mutated value.

https://github.com/noir-lang/noir/blob/7e6c06fb952abd5ee737c8aed29430d915511dee/compiler/noirc_evaluator/src/brillig/brillig_ir/entry_point.rs#L129

We should spend some time to determine whether this mutation is unnecessary and can be removed or if this is hinting at a deeper issue (I'm a bit paranoid about brillig array lengths atm)

cc @asterite

### PR DESCRIPTION
**Pull request by asterite**
# Description

## Problem

Resolves #11125
Resolves #11166

## Summary

The issue was that HeapValueType::Array size held a semi-flattened size, but in reality it should hold the non-flattened size. The final flattened size is computed when needed, if needed.

## Additional Context

I'm trying to come up with ways to use wrapper structs to avoid these issues but I'm still not sure how.

## User Documentation

Check one:
- [x] No user documentation needed.
- [ ] Changes in _docs/_ included in this PR.
- [ ] **[For Experimental Features]** Changes in _docs/_ to be submitted in a separate PR.

# PR Checklist

- [x] I have tested the changes locally.
- [x] I have formatted the changes with [Prettier](https://prettier.io/) and/or `cargo fmt` on default settings.

### CODE REVIEW

File: acvm-repo/brillig_vm/src/foreign_call.rs [hunk 1]
```diff
@@ -167,13 +171,16 @@ impl<F: AcirField, B: BlackBoxFunctionSolver<F>> VM<'_, F, B> {
 
     /// Reads an array/vector from memory but recursively reads pointers to
     /// nested arrays/vectors according to the sequence of value types.
+    ///
+    /// The given `size` is the total number of `HeadValueType`s to read, which must
```
Comment (aakoshh) [inline acvm-repo/brillig_vm/src/foreign_call.rs]:
```suggestion
    /// The given `size` is the total number of `HeapValueType`s to read, which must
```

File: acvm-repo/brillig_vm/src/foreign_call.rs [hunk 2]
```diff
@@ -195,13 +202,14 @@ impl<F: AcirField, B: BlackBoxFunctionSolver<F>> VM<'_, F, B> {
                         HeapValueType::Simple(_) => {
                             vec![self.memory.read(value_address)]
                         }
-                        HeapValueType::Array { value_types, size } => {
+                        HeapValueType::Array { value_types, size: type_size } => {
                             let array_address =
                                 ArrayAddress::from(self.memory.read_ref(value_address));
+                            let semi_flattened_size = *type_size * value_types.len();
```
Comment (aakoshh) [inline acvm-repo/brillig_vm/src/foreign_call.rs]: Why do we call this "semi" flattened size?

File: compiler/noirc_evaluator/src/brillig/brillig_ir/brillig_variable.rs [hunk 3]
```diff
@@ -153,7 +153,7 @@ pub(crate) fn type_to_heap_value_type(typ: &Type) -> HeapValueType {
         ),
         Type::Array(elem_type, size) => HeapValueType::Array {
             value_types: elem_type.as_ref().iter().map(type_to_heap_value_type).collect(),
-            size: typ.element_size() * *size as usize,
+            size: *size as usize,
```
Comment (aakoshh) [inline compiler/noirc_evaluator/src/brillig/brillig_ir/brillig_variable.rs]: Do you think this could be a breaking change for the ACVM?

File: acvm-repo/brillig_vm/src/foreign_call.rs (hunk 2 above)
Comment (aakoshh) [inline acvm-repo/brillig_vm/src/foreign_call.rs]: So for a `HeapVector` we read the `size` from the memory [here](https://github.com/noir-lang/noir/blob/730c078bf639ab8e0222155e4ee1b814c996a5c4/acvm-repo/brillig_vm/src/foreign_call.rs#L159) and it is already the "semi flattened size" that we can use to call `read_slice_of_values_from_memory`. 

Wouldn't it make sense to have the same "semi flattened size" be put in `HeapArray`, because it is statically known, rather than the "type size" which needs to be further multiplied? That way, both "Heap*" types have the same "size", just one is in the `HeapValueType` and the other in memory. 

In other words, instead of storing the type size `type_to_heap_value_type`, we could replace this:
```
size: typ.element_size() * *size as usize
```
with this:
```
size: value_types.len() * *size as usize
```

Comment (aakoshh) [reply acvm-repo/brillig_vm/src/foreign_call.rs]: `BrilligArray::size` is also (semi-)flattened.

Comment (aakoshh) [reply acvm-repo/brillig_vm/src/foreign_call.rs]: Oh, I see the `HeapArray::size` is still flattened, just `HeapArrayType::size` isn't 😵‍💫 

`write_flattened_values_to_memory` seems to assume that `HeapArrayType::size` is the semantic length, not flattened 🤔

File: compiler/noirc_evaluator/src/brillig/brillig_ir/brillig_variable.rs (hunk 3 above)
Comment (aakoshh) [inline compiler/noirc_evaluator/src/brillig/brillig_ir/brillig_variable.rs]: It would be nice to add documentation to `HeapValueType::Array::size` and `HeapArray::size` to explain the difference between their contents.

File: acvm-repo/brillig_vm/src/foreign_call.rs (hunk 2 above)
Comment (aakoshh) [reply acvm-repo/brillig_vm/src/foreign_call.rs]: And `HeapVector::size` _is_ semantic length, unlike the size _inside_ the vector structure, so I suppose it makes sense that `HeapArrayType::size` can be semantic as well 🤷

Comment (aakoshh) [reply acvm-repo/brillig_vm/src/foreign_call.rs]: I guess this is to differentiate from the `flattened_size` which recursively aggregates. 

It's still confusing that we had a multiplication with `element_size()` as well, but we aren't using that here. Should that equal `value_types.len()`? 

It would be good to try to encapsulate this logic into some sort of method where it can be documented, so this multiplication isn't scattered around. Perhaps add `HeapValueType::semi_flattened_size(&self) -> Option<usize>`?

File: acvm-repo/brillig_vm/src/foreign_call.rs (hunk 1 above)
Comment (asterite) [reply acvm-repo/brillig_vm/src/foreign_call.rs]: Haha, oops! 😅

File: acvm-repo/brillig_vm/src/foreign_call.rs (hunk 2 above)
Comment (asterite) [reply acvm-repo/brillig_vm/src/foreign_call.rs]: I agree, it's pretty confusing. The idea Tom and Jake discussed, which I didn't get to implement yet, was to use newtypes for each of the different meanings. I was thinking of having `SemanticLength` and `SemiFlattenedLength`, maybe also `FlattenedLength` though I'm not sure if that's used. But this is just an idea, I still have to experiment with this.

File: compiler/noirc_evaluator/src/brillig/brillig_ir/brillig_variable.rs (hunk 3 above)
Comment (asterite) [reply compiler/noirc_evaluator/src/brillig/brillig_ir/brillig_variable.rs]: I think no. Or at least all tests pass. Or do you mean the other VM that's not in this repo?

File: acvm-repo/brillig/src/opcodes.rs [hunk 4]
```diff
@@ -184,12 +191,12 @@ pub struct HeapArray {
     /// That is to say, the address retrieved from the pointer doesn't need any more offsetting.
     pub pointer: MemoryAddress,
     /// Statically known size of the array.
-    pub size: usize,
+    pub size: SemiFlattenedLength,
```
Comment (vezenovm) [inline acvm-repo/brillig/src/opcodes.rs:200]: Just noting this will be a serialization change. It should be pretty manageable in Brillig as backends should ignore Brillig opcodes. 

EDIT: It does affect AVM though

File: compiler/noirc_evaluator/src/brillig/brillig_ir/brillig_variable.rs (hunk 3 above)
Comment (aakoshh) [reply compiler/noirc_evaluator/src/brillig/brillig_ir/brillig_variable.rs]: Yes, sorry, I meant the AVM team 🙃 
They pushed back on changing how we deal with foreign calls regarding returning multiple vectors, which would require them setting the free memory pointer, like I tried to do in the Brillig VM. As I understand they simulate Brillig opcodes, so if the meaning of values change, they are also affected.

File: acvm-repo/brillig/src/opcodes.rs (hunk 4 above)
Comment (aakoshh) [reply acvm-repo/brillig/src/opcodes.rs:200]: If it's a transparent value, a _newtype_, then it is still serialised as its internal value, so it shouldn't be breaking, just a bit of change in C++ code they don't use.

Comment (asterite) [reply acvm-repo/brillig/src/opcodes.rs:200]: So it's okay to push changes to the generated C++?

File: acvm-repo/brillig_vm/src/foreign_call.rs [hunk 5]
```diff
@@ -339,7 +353,8 @@ impl<F: AcirField, B: BlackBoxFunctionSolver<F>> VM<'_, F, B> {
                             return Err("Foreign call returned a single value for an array type"
                                 .to_string());
                         };
-                        if values.len() != *size {
+                        // TODO(lengths): check this comparison, it looks off
+                        if values.len() != size.0 {
```
Comment (asterite) [inline acvm-repo/brillig_vm/src/foreign_call.rs]: I couldn't find a single test where this condition holds. I wonder if we should turn this into an assertion... unless we can think of a program that triggers this.

File: acvm-repo/brillig/src/opcodes.rs (hunk 4 above)
Comment (aakoshh) [reply acvm-repo/brillig/src/opcodes.rs:200]: I think so

File: compiler/noirc_evaluator/src/brillig/brillig_gen/brillig_call/mod.rs [hunk 6]
```diff
@@ -132,8 +133,11 @@ impl<Registers: RegisterAllocator> BrilligBlock<'_, Registers> {
                 match element_type {
                     Type::Array(_, nested_size) => {
                         // Allocate a pointer for an array on the stack.
-                        let inner_array =
-                            self.brillig_context.allocate_brillig_array(*nested_size as usize);
+                        // TODO(lengths): this looks off. `nested_size` seems to be a SemanticLength,
+                        // yet for allocating a Brillig array we need a SemiFlattenedLength.
```
Comment (asterite) [inline compiler/noirc_evaluator/src/brillig/brillig_gen/brillig_call/mod.rs]: This one is a bit strange. `nested_size` comes directly from the SSA Array type. There, the size represents a semantic length. And I think we need to allocate the semi-flattened length, not the semantic length.

Comment (asterite) [reply compiler/noirc_evaluator/src/brillig/brillig_gen/brillig_call/mod.rs]: This is effectively a bug. This Noir code:

```noir
use std::{mem::zeroed, test::OracleMock};

fn main() {}

#[oracle(foo)]
unconstrained fn foo() -> [[(u8, u8); 3]; 4] {}

#[test]
unconstrained fn test_foo() {
    let value: [[(u8, u8); 3]; 4] = zeroed();
    let _ = OracleMock::mock("foo").returns(value);
    println(foo());
}
```

When executed with `nargo test --show-output` in `master` gives:

```
Assertion failed: 'Foreign call return value does not match expected size. Expected 48 but got 24'
```

It makes sense because of the bug this PR is trying to solve. But then in this PR we get:

```
--- test_foo stdout ---
[[(0, 0), (0, 0), (0, 0)], [(0, 0), (0, 0), (0, 0)], [(0, 0), (0, 0), (0, 0)], [(0, 0), (0, 1), (123, 34)]]
```

The last values are wrong.

Comment (asterite) [reply compiler/noirc_evaluator/src/brillig/brillig_gen/brillig_call/mod.rs]: This is fixed now. I added that regression test.

File: compiler/noirc_evaluator/src/brillig/brillig_ir/codegen_control_flow.rs [hunk 7]
```diff
@@ -376,8 +386,11 @@ impl<F: AcirField + DebugToString, Registers: RegisterAllocator> BrilligContext<
                             nested_array_item_type,
                             nested_array_item_count,
                         ) => {
-                            let deflattened_nested_array =
-                                self.allocate_brillig_array(*nested_array_item_count);
+                            // TODO(lengths): this looks off as to allocate an array we need a semi-flattened length,
+                            // yet nested_array_item_count is a semantic length.
```
Comment (asterite) [inline compiler/noirc_evaluator/src/brillig/brillig_ir/codegen_control_flow.rs]: This one looks off to me but in practice it seems to be working fine.

@vezenovm Do you know why this code is like this? Usually memory for brillig arrays is allocated for the semi-flattened length, but here we allocate exactly the number of array elements (semantic length). I'm not sure how this is working with nested tuples, but it seems to be working well.

File: compiler/noirc_evaluator/src/brillig/brillig_ir/entry_point.rs [hunk 8]
```diff
@@ -159,9 +165,13 @@ impl<F: AcirField + DebugToString> BrilligContext<F, Stack> {
...
                     self.allocate_single_addr(*bit_size).map(BrilligVariable::from)
                 }
-                BrilligParameter::Array(_, _) => {
-                    let flattened_size = Self::flattened_size(argument);
-                    self.allocate_brillig_array(flattened_size).map(BrilligVariable::from)
+                BrilligParameter::Array(..) => {
+                    let flattened_size: FlattenedLength = Self::flattened_size(argument);
+
+                    // TODO(lengths): this looks off as to allocate a brillig array we need a semi-flattened length,
+                    // but here we have the fully flattened length
```
Comment (asterite) [inline compiler/noirc_evaluator/src/brillig/brillig_ir/entry_point.rs]: @vezenovm But maybe this is fine as this array is for a function entry point, so all the elements are flattened? I don't know what the returned `BrilligArray` is used for, though. Maybe it doesn't matter as this is paired with the other code to read flattened arrays for return values.

File: acvm-repo/brillig_vm/src/foreign_call.rs (hunk 5 above)
Comment (asterite) [reply acvm-repo/brillig_vm/src/foreign_call.rs]: @guipublic Do you remember why we have this logic? It seems to have been introduced in https://github.com/noir-lang/noir/commit/a30814f1f767bf874cd7e2969f5061c68f16b9a7

File: acvm-repo/brillig/src/opcodes.rs (hunk 4 above)
Comment (asterite) [reply acvm-repo/brillig/src/opcodes.rs:200]: Thanks. I updated the generated code but for some reason CI is still failing 😕 (it works on my machine)

File: compiler/noirc_evaluator/src/brillig/brillig_ir/codegen_control_flow.rs (hunk 7 above)
Comment (vezenovm) [reply compiler/noirc_evaluator/src/brillig/brillig_ir/codegen_control_flow.rs]: The semi flattened length is what we get from SSA from flattening tuples right? So wouldn't `nested_array_item_count` be the semi flat length?

File: compiler/noirc_evaluator/src/brillig/brillig_ir/entry_point.rs (hunk 8 above)
Comment (vezenovm) [reply compiler/noirc_evaluator/src/brillig/brillig_ir/entry_point.rs]: > I don't know what the returned BrilligArray is used for, though

It will be used to code gen the opcodes for the entry point. This length is used above in `codegen_entry_point`. We do need the fully flattened length here if you look at the implementation inside of `codegen_entry_point`. The calldata pointer needs to be incremented by the entire flattened size of the array. It feels strange to wrap a `FlattenedLength` in a `SemiFlattenedLength`.

File: compiler/noirc_evaluator/src/brillig/brillig_ir/entry_point.rs [hunk 9]
```diff
@@ -73,8 +76,11 @@ impl<F: AcirField + DebugToString> BrilligContext<F, Stack> {
         // We need to allocate the variable for every argument first so any register allocation doesn't mangle the expected order.
         let mut argument_variables = self.allocate_function_arguments(arguments);
 
-        let calldata_size = Self::flattened_tuple_size(arguments);
-        let return_data_size = Self::flattened_tuple_size(return_parameters);
+        let calldata_size: FlattenedLength = Self::flattened_tuple_size(arguments);
```
Comment (vezenovm) [inline compiler/noirc_evaluator/src/brillig/brillig_ir/entry_point.rs]: We're using `FlattenedLength` to refer to single array lengths as well as the length of multiple arguments/parameters?

File: compiler/noirc_evaluator/src/brillig/brillig_ir/codegen_control_flow.rs (hunk 7 above)
Comment (aakoshh) [reply compiler/noirc_evaluator/src/brillig/brillig_ir/codegen_control_flow.rs]: It's the size from the SSA `Type` (I think that's semantic): 
https://github.com/noir-lang/noir/blob/6fa7bedf556a30fa3a4b9b0feaa83d8bb96f9131/compiler/noirc_evaluator/src/brillig/brillig_gen/brillig_fn.rs#L100-L107

File: compiler/noirc_evaluator/src/brillig/brillig_ir/entry_point.rs (hunk 8 above)
Comment (vezenovm) [reply compiler/noirc_evaluator/src/brillig/brillig_ir/entry_point.rs]: We do call into `deflatten_array` in `codegen_entry_point`.

Comment (aakoshh) [reply compiler/noirc_evaluator/src/brillig/brillig_ir/entry_point.rs]: This will be overwritten:
```
                    // After deflattening, we have to adjust the size of the array.
                    array.size = item_type.len() * item_count;
```

File: compiler/noirc_evaluator/src/brillig/brillig_ir/codegen_control_flow.rs (hunk 7 above)
Comment (vezenovm) [reply compiler/noirc_evaluator/src/brillig/brillig_ir/codegen_control_flow.rs]: Ah you're right it is the semantic length. We allocate a deflattened nested array using this semantic length. We then recursively call into `flatten_array` to keep flattening the nested array.

**Comment by vezenovm** [comment]
I know it is a big change but this PR makes me feel like we should bite the bullet and remove nested arrays from SSA and thus its downstream passes. These types feel like a bandaid that provide some clarity to contributors but maintain the existing complexity (the bug this PR aims to solve is caused by this complexity). Let alone, these length types still have to be introduced into ACIR gen (not in this PR ofc) and we have not even started looking at updating the length types for slice intrinsics or SSA itself. cc @TomAFrench @jfecher

File: compiler/noirc_evaluator/src/brillig/brillig_ir/entry_point.rs (hunk 8 above)
Comment (asterite) [reply compiler/noirc_evaluator/src/brillig/brillig_ir/entry_point.rs]: Good catch! I think this can be written without mutating the array then, and computing the flattened length here instead of on the other side. I'll try it.

Comment (asterite) [reply compiler/noirc_evaluator/src/brillig/brillig_ir/entry_point.rs]: It worked! One TODO less.

File: compiler/noirc_evaluator/src/brillig/brillig_ir/entry_point.rs (hunk 9 above)
Comment (asterite) [reply compiler/noirc_evaluator/src/brillig/brillig_ir/entry_point.rs]: I think I understand what you mean. In this case I should have used `ElementsFlattenedLength`, which represents the flattened length of a list of types, independently of an array's semantic length. I'll change it.

File: compiler/noirc_evaluator/src/brillig/brillig_ir/codegen_control_flow.rs (hunk 7 above)
Comment (asterite) [reply compiler/noirc_evaluator/src/brillig/brillig_ir/codegen_control_flow.rs]: I documented this, so now the TODO is gone.

File: compiler/noirc_evaluator/src/brillig/brillig_ir/entry_point.rs (hunk 9 above)
Comment (asterite) [reply compiler/noirc_evaluator/src/brillig/brillig_ir/entry_point.rs]: Done! I changed this method back to returning `usize` as the strong type wasn't used at all (we always immediately unwrap the value to use it).

File: acvm-repo/brillig_vm/src/foreign_call.rs (hunk 5 above)
Comment (asterite) [reply acvm-repo/brillig_vm/src/foreign_call.rs]: I changed this to an assertion. No test fails.

**Comment by asterite** [comment]
> I know it is a big change but this PR makes me feel like we should bite the bullet and remove nested arrays from SSA and thus its downstream passes.

I agree with this. But... wouldn't it help to have these strong types in the meantime until that refactor is done? It could help to know what sizes are expected where. That said, if there's an open PR already and this would introduce more merge conflicts, then maybe we shouldn't continue working on this PR (though it would be nice to extract the couple of commits that fix things).

File: compiler/noirc_evaluator/src/brillig/brillig_ir/brillig_variable.rs (hunk 3 above)
Comment (asterite) [reply compiler/noirc_evaluator/src/brillig/brillig_ir/brillig_variable.rs]: Now each have a different type. `HeapArray::size` is `SemiFlattenedLength` and `HeapValueType::Array::size` is `SemanticLength`, so the types already tell the difference.

Comment (asterite) [reply compiler/noirc_evaluator/src/brillig/brillig_ir/brillig_variable.rs]: I see. But I think this change is required. The `size` here must be the semantic length. Otherwise if we use the semi-flattened length here, it must be deflattened somewhere else, later on, here in our code and also in the AVM as I suspect the bugs we have here also exist on the AVM.

**Comment by vezenovm** [comment]
> I agree with this. But... wouldn't it help to have these strong types in the meantime until that refactor is done? It could help to know what sizes are expected where

Agreed, it would definitely help to have these types in the meantime. I was worried when I first reviewed as there were still a few blockers which look to be resolved now. I see there are some merge conflicts now (most likely due to the serialization PR). Happy to re-review once those are resoled.

**Comment by asterite** [comment]
@vezenovm Done!

**Comment by asterite** [comment]
I ended up changing the new types to wrap a `u32` instead of `usize` because of https://github.com/noir-lang/noir/pull/10933 . I think that's more correct and involves less casts. I also see many more places where `usize` could be changed to `u32` but, as mentioned in #10933, it might be better to do it in a separate PR.

File: acvm-repo/brillig/src/lengths.rs [hunk 10]
```diff
@@ -0,0 +1,155 @@
...
+    }
+}
+
+impl std::fmt::Display for ElementsLength {
+    fn fmt(&self, f: &mut std::fmt::Formatter<'_>) -> std::fmt::Result {
+        write!(f, "{}", self.0)
+    }
+}
+
+/// Represents the number of value/memory slots required to represent an array or vector.
```
Comment (vezenovm) [inline acvm-repo/brillig/src/lengths.rs:76]: Maybe we should mention by what this is determined. We could add that in our SSA tuples are flattened so the number of value slots needed to represent an array is different than the semantic length.

File: acvm-repo/brillig/src/opcodes.rs [hunk 11]
```diff
@@ -127,18 +130,21 @@ impl HeapValueType {
...
+                let elements_flattened_size =
+                    value_types.iter().map(|t| t.flattened_size()).sum::<Option<FlattenedLength>>();
+                let elements_flattened_size =
+                    elements_flattened_size.map(|elements_flattened_size| {
+                        elements_flattened_size.as_elements_flattened_length()
+                    });
+
+                // Next we multiply it by the size of the array
+                elements_flattened_size
+                    .map(|elements_flattened_size| elements_flattened_size * *size)
```
Comment (vezenovm) [inline acvm-repo/brillig/src/opcodes.rs]:
```suggestion
                // Next we multiply it by the size of the array
                let elements_flattened_size =
                    elements_flattened_size.map(|elements_flattened_size| {
                        elements_flattened_size.as_elements_flattened_length() * *size
                    });
```
I don't see a reason to split the type conversion and the multiplication of the size

File: compiler/noirc_evaluator/src/brillig/brillig_ir/codegen_control_flow.rs [hunk 12]
```diff
@@ -370,14 +376,17 @@ impl<F: AcirField + DebugToString, Registers: RegisterAllocator> BrilligContext<
...
-                            target_offset += 1;
                         }
                         BrilligParameter::Array(
                             nested_array_item_type,
                             nested_array_item_count,
                         ) => {
-                            let deflattened_nested_array =
-                                self.allocate_brillig_array(*nested_array_item_count);
+                            // Usually we need to pass a semi-flattened length to `allocate_brillig_array`.
+                            // However, since we are deflattenning arrays, we need to allocate as many elements
```
Comment (vezenovm) [inline compiler/noirc_evaluator/src/brillig/brillig_ir/codegen_control_flow.rs]:
```suggestion
                            // However, since we are deflattening arrays, we need to allocate as many elements
```

File: acvm-repo/brillig/src/lengths.rs [hunk 13]
```diff
@@ -0,0 +1,155 @@
...
+}
+
+/// Represents the total number of fields required to represent the entirety of an array or vector.
+/// For example in the array `[(u8, u16, [u32; 4]); 8]` the flattened length is 48: 8 * (1 + 1 + 4).
+#[derive(Debug, Copy, Clone, Eq, PartialEq, PartialOrd, Ord, Serialize, Deserialize, Hash)]
+pub struct FlattenedLength(pub u32);
+
+impl FlattenedLength {
+    /// Assumes this flattened length represents a single entry in an array or vector,
+    pub fn as_elements_flattened_length(self) -> ElementsFlattenedLength {
```
Comment (vezenovm) [inline acvm-repo/brillig/src/lengths.rs]: We could switch this to a `impl From<FlattenedLength> for ElementsFlattenedLength`
