### PR TITLE
fix: Apply self type from generic trait constraint before instantiating identifiers

### LINKED ISSUE #5063: Expression type is ambigious when using trait generics that instantiate variables
### Aim

After the addition of the turbofish operator (https://github.com/noir-lang/noir/pull/3542) we should be able to use trait generics without them being bound to a parameter or return value. 

I want to be able to use a trait generic to instantiate an object using its trait methods and then further use those trait methods. For example the following code should work (after https://github.com/noir-lang/noir/pull/5041): 
```rust
fn hash_simple_array<H>(input: [Field; 2]) -> Field where H: Hasher + Default {
    let mut hasher = H::default();
    hasher.write(input[0]);
    hasher.write(input[1]);
    hasher.finish()
}
```

### Expected Behavior

The program above should pass.

### Bug

Instead when attempting to use the result of `H::default()` we get an error `Expression type is ambiguous`. 
Screenshot 2024-05-21 at 1 14 44 PM

### To Reproduce

1. Compile the snippet above

### Project Impact

Blocker

### Impact Context

This blocks us being able to document and advertise turbofish

### Workaround

None

### Workaround Description

_No response_

### Additional Context

_No response_

### Installation Method

None

### Nargo Version

_No response_

### NoirJS Version

_No response_

### Would you like to submit a PR for this Issue?

None

### Support Needs

_No response_

### PR DESCRIPTION
**Pull request by vezenovm**
# Description

## Problem\*

Resolves #5063 

## Summary\*

After the turbofish PRs we want the ability to instantiate a variable from a generic trait. This was possible but it required a redundant type annotiation like such (assume `H` has been specified with a `where` clause):
```rust
let hasher: H = H::default()
```
Similarly to trait generics, we now add type bindings from a trait constraint if the trait impl is assumed to exist. 
We now can just do:
```rust
let hasher = H::default()
```

## Documentation\*

Check one:
- [X] No documentation needed.
- [ ] Documentation included in this PR.
- [] **[For Experimental Features]** Documentation to be submitted in a separate PR.

# PR Checklist\*

- [X] I have tested the changes locally.
- [X] I have formatted the changes with [Prettier](https://prettier.io/) and/or `cargo fmt` on default settings.

### CODE REVIEW

File: compiler/noirc_frontend/src/tests.rs [hunk 1]
```diff
@@ -1430,16 +1430,17 @@ fn specify_method_types_with_turbofish() {
         }
         
         impl<T> Foo<T> {
-            fn generic_method<U>(_self: Self) where U: Default {
+            fn generic_method<U>(_self: Self) -> U where U: Default {
```
Comment (vezenovm) [inline compiler/noirc_frontend/src/tests.rs:1433]: We had a mismatch in the expected and actual type returned here now that `Self` for the trait method actually is bound to `U`

**Comment by jfecher** [comment]
Can you check whether this fixes https://github.com/noir-lang/noir/issues/5065 and https://github.com/noir-lang/noir/issues/4732 as well?

**Review by jfecher — APPROVED** [review]
LGTM
