### PR TITLE
fix: validate loop range have identical types in comptime

### LINKED ISSUE #10688: For with different types in range crashes the compiler
### Aim

This code:

```noir
fn main() {
    comptime {
        for _ in 1_i8..2_u8 {}
    }
}
```

produces this error:

```
The application panicked (crashed).
Message:  Checked above that value is signed type
Location: compiler/noirc_frontend/src/hir/comptime/interpreter.rs:1385
```

The reason is that the comptime interpreter assumes the range end type is the same as the range start type, and panics otherwise, which is what happens here.

When fixing this, make sure this code also doesn't crash:

```noir
fn main() {
    comptime {
        for _ in 1_u8..2_i8 {}
    }
}
```

### Expected Behavior

The compiler should produce an error, not crash.

### Bug

The compiler crashes.

### To Reproduce

1.
2.
3.
4.

### Workaround

None

### Workaround Description

_No response_

### Additional Context

_No response_

### Project Impact

None

### Blocker Context

_No response_

### Nargo Version

_No response_

### NoirJS Version

_No response_

### Proving Backend Tooling & Version

_No response_

### Would you like to submit a PR for this Issue?

None

### Support Needs

_No response_

### PR DESCRIPTION
**Pull request by guipublic**
# Description

## Problem

Resolves #10688

## User Documentation

Check one:
- [X] No user documentation needed.
- [ ] Changes in _docs/_ included in this PR.
- [ ] **[For Experimental Features]** Changes in _docs/_ to be submitted in a separate PR.

# PR Checklist

- [X] I have tested the changes locally.
- [X] I have formatted the changes with [Prettier](https://prettier.io/) and/or `cargo fmt` on default settings.

### CODE REVIEW

File: compiler/noirc_frontend/src/hir/comptime/interpreter.rs [hunk 1]
```diff
@@ -1376,9 +1376,20 @@ impl<'local, 'interner> Interpreter<'local, 'interner> {
     fn evaluate_for(&mut self, for_: HirForStatement) -> IResult<Value> {
         let start_value = self.evaluate(for_.start_range)?;
         let end_value = self.evaluate(for_.end_range)?;
-        let loop_index_type = start_value.get_type();
+        let start_type = start_value.get_type();
+        let end_type = end_value.get_type();
+
+        // Check that start and end have the same type
+        if start_type != end_type {
```
Comment (jfecher) [inline compiler/noirc_frontend/src/hir/comptime/interpreter.rs]: We should avoid calling `==` or `!=` on types, it will be incorrect when type variables are involved. You can use `.unify().is_ok()` instead

```suggestion
        if start_type.unify(&end_type).is_ok() {
```

File: compiler/noirc_frontend/src/hir/comptime/interpreter.rs [hunk 2]
```diff
@@ -1376,9 +1376,20 @@ impl<'local, 'interner> Interpreter<'local, 'interner> {
     fn evaluate_for(&mut self, for_: HirForStatement) -> IResult<Value> {
         let start_value = self.evaluate(for_.start_range)?;
         let end_value = self.evaluate(for_.end_range)?;
-        let loop_index_type = start_value.get_type();
+        let start_type = start_value.get_type();
+        let end_type = end_value.get_type();
+
+        // Check that start and end have the same type
+        if start_type.unify(&end_type).is_ok() {
```
Comment (jfecher) [inline compiler/noirc_frontend/src/hir/comptime/interpreter.rs]:
```suggestion
        if start_type.unify(&end_type).is_err() {
```
Accidentally reversed the condition
