### PR TITLE
fix: error on wrong Ordering trait, instead of panic.

### LINKED ISSUE #10805: Panic when using ill-formed Ord trait in comptime
### Aim

```noir
struct Foo {}
      
// Intentionally malformed Ord impl with type error
impl Ord for Foo {
    fn cmp(self, _other: Self) -> std::cmp::Ordering::less() {
        std::cmp::Ordering::less()
    }
}

fn main() {
    comptime {
        let a = Foo {};
        let b = Foo {};
        let _ = a < b;
    }
}
```

### Expected Behavior

I expect the program to error gracefully with type errors.

### Bug

Instead we get a panic in the comptime interpreter:
```
The application panicked (crashed).
Message:  internal error: entered unreachable code: `cmp` should always return an Ordering value
Location: compiler/noirc_frontend/src/hir/comptime/interpreter.rs:951
```

### To Reproduce

1. Run `nargo compile` on the program above

### Workaround

None

### Workaround Description

_No response_

### Additional Context

_No response_

### Project Impact

Nice-to-have

### Blocker Context

_No response_

### Nargo Version

nargo version = 1.0.0-beta.16 noirc version = 1.0.0-beta.16+2a925b031d6480def78e2722451e6ed9d4f87fca (git version hash: 2a925b031d6480def78e2722451e6ed9d4f87fca, is dirty: true)

### NoirJS Version

_No response_

### Proving Backend Tooling & Version

_No response_

### Would you like to submit a PR for this Issue?

None

### Support Needs

_No response_

### PR DESCRIPTION
**Pull request by guipublic**
# Description

## Problem

Resolves #10805 

## Summary
return error instead of a panic.

## User Documentation

Check one:
- [X] No user documentation needed.
- [ ] Changes in _docs/_ included in this PR.
- [ ] **[For Experimental Features]** Changes in _docs/_ to be submitted in a separate PR.

# PR Checklist

- [X] I have tested the changes locally.
- [X] I have formatted the changes with [Prettier](https://prettier.io/) and/or `cargo fmt` on default settings.

### CODE REVIEW

File: compiler/noirc_frontend/src/hir/comptime/interpreter.rs [hunk 1]
```diff
@@ -946,14 +948,34 @@ impl<'local, 'interner> Interpreter<'local, 'interner> {
...
         };
+        // Error if there is no ordering field
+        if field_ordering.is_none() {
+            return Err(InterpreterError::TypeMismatch {
+                expected: "Ordering".to_string(),
+                actual: ordering.get_type().into_owned(),
+                location,
+            });
+        }
+        let ordering = field_ordering.unwrap();
```
Comment (aakoshh) [inline compiler/noirc_frontend/src/hir/comptime/interpreter.rs]:
```suggestion
        let Some(ordering) = field_ordering else {
            return Err(InterpreterError::TypeMismatch {
                expected: "Ordering".to_string(),
                actual: ordering.get_type().into_owned(),
                location,
            });
        }
```

File: compiler/noirc_frontend/src/hir/comptime/interpreter.rs [hunk 2]
```diff
@@ -946,14 +948,34 @@ impl<'local, 'interner> Interpreter<'local, 'interner> {
...
+        ordering: Value,
+        operator: BinaryOpKind,
+        location: Location,
+    ) -> IResult<Value> {
+        let field_ordering = match &ordering {
+            Value::Struct(fields, _) => {
+                let first_field = fields.iter().next();
+                match first_field {
+                    Some((_, value)) => match &*value.borrow() {
+                        Value::Field(ordering) => Some(*ordering),
```
Comment (aakoshh) [inline compiler/noirc_frontend/src/hir/comptime/interpreter.rs]: Technically this still accepts any `struct` where the first field is a `Field`. Should we check that the `Type` in the `Struct` bears the expected `name` for example?

Comment (jfecher) [reply compiler/noirc_frontend/src/hir/comptime/interpreter.rs]: For built-in functions we rely on getting the type via the type signature of the called function. We can't rely on the types from impls but I wonder if there's a way we could access the original trait and its return type here.

Comment (guipublic) [reply compiler/noirc_frontend/src/hir/comptime/interpreter.rs]: I added a check on Ordering name.
