### PR TITLE
fix(elaborator): Disambiguate associated types from ordered generics

### LINKED ISSUE #10864: Missing error when returning type parameter in place of associated type
### Aim

I attempted to compile the following programs:

1.

```noir
pub trait Foo<Bar> {
    type Bar;

    fn foo(x: Bar) -> Self::Bar { x }
}

fn main() { }
```

2.

```noir
pub trait Foo<Bar> {
    type Bar;

    fn foo(x: Self::Bar) -> Bar { x }
}
```

### Expected Behavior

I expected errors similar to:

1. `error: expected type Self::Bar, found type Bar`
2. `error: expected type Bar, found type Self::Bar`

### Bug

1.

```
❯ ~/.nargo/bin/nargo compile
```

2.

```
❯ ~/.nargo/bin/nargo compile
```

### To Reproduce

1.
2.
3.
4.

### Workaround

None

### Workaround Description

_No response_

### Additional Context

_No response_

### Project Impact

None

### Blocker Context

_No response_

### Nargo Version

_No response_

### NoirJS Version

_No response_

### Proving Backend Tooling & Version

_No response_

### Would you like to submit a PR for this Issue?

None

### Support Needs

_No response_

### PR DESCRIPTION
**Pull request by aakoshh**
# Description

## Problem

Resolves #10864 

## Summary

Changes the `name` assigned to `NamedGeneric` to be `Self::{type}` or `<{object} as {trait}>::{type}` for associated types, to disambiguate this generic from non-associated generics of the trait. 

## Additional Context

This does not solve https://github.com/noir-lang/noir/issues/10858, the following is still rejected:
```noir
pub trait Foo {
    type Bar;
    fn foo_bar() -> <Self as Foo>::Bar;
}
fn main() {}
```
Because of this such types currently get the name `Self::Bar`. I'll try to solve that as a follow up. 

I also found that the current fix doesn't work across different traits that share the same associated type name, even if I uncomment the special casing for `Self` and render them as `<Self as Foo>::Bar`: https://github.com/noir-lang/noir/issues/11347 Since there is no mixing of ordered and named generics there, I think we can treat it as a follow up.(It turns out names don't even matter there).

## User Documentation

Check one:
- [x] No user documentation needed.
- [ ] Changes in _docs/_ included in this PR.
- [ ] **[For Experimental Features]** Changes in _docs/_ to be submitted in a separate PR.

# PR Checklist

- [x] I have tested the changes locally.
- [ ] I have formatted the changes with [Prettier](https://prettier.io/) and/or `cargo fmt` on default settings.

### CODE REVIEW

**Comment by jfecher** [comment]
> Resolves https://github.com/noir-lang/noir/issues/10864

I'd honestly be fine rejecting this code outright as well.

Seems like in general though we're using these names too often. An invariant of `Type::Generic` is that you should only ever have 1 set of generics in scope. You shouldn't ever have to match generics from one context against another. In situations where that may arise the types always need to be instantiated, such as when we instantiate variables referring to generic functions. Maybe we're missing an instantiation somewhere when doing these trait checks or some other check we have is hacky and bypassing them.

I do think it would be easier rejecting the code in the original issue and would lead to slightly simpler compiler code (it just seems confusing to me to allow type parameters & associated types of the same name in 1 trait), but if we want to allow it then we'd need to rename one of them internally as you've done here. My paragraph above still stands in regards to having multiple trait constraints though.

> but even if I go back to render the type as <Self as Eggs>::Item it doesn't reject it, so there is some other reason

It may be using unbound type variables for these types under the hood.

File: compiler/noirc_frontend/src/hir_def/types.rs [hunk 1]
```diff
@@ -1042,12 +1067,20 @@ impl TypeVariable {
...
+    ) -> Type {
+        Type::NamedGeneric(NamedGeneric::new(self, false, name, as_trait))
     }
 
-    pub(crate) fn into_implicit_named_generic(self, name: Rc<String>) -> Type {
-        Type::NamedGeneric(NamedGeneric { type_var: self, name, implicit: true })
+    pub(crate) fn into_implicit_named_generic(
+        self,
+        name: &Rc<String>,
+        as_trait: Option<(&str, &str)>,
```
Comment (jfecher) [inline compiler/noirc_frontend/src/hir_def/types.rs:1091]: Docs on what this `(&str, &str)` pair means please

**Comment by aakoshh** [comment]
@jfecher thank you for the insights into how it should work. I'm not sure where we might be missing something, but I found an instance where the `NamedGeneric` was already assigned this `<{object} as {trait}>::{name}` label instead of just `name`:

https://github.com/noir-lang/noir/blob/f00ead976b22b35a2746c6db06fd77609cabe6ea/compiler/noirc_frontend/src/elaborator/traits.rs#L392

I tried to make sure it's more difficult to miss these by adding them to them method.

> I do think it would be easier rejecting the code in the original issue and would lead to slightly simpler compiler code

I think that might be an illusion of simplicity, since we'd still be using that pattern, but it would be (at least for me) less clear where it needs to be applied and where it doesn't. With this change hopefully it's a bit simpler to think about it: if you deal with associated types, please pass the trait on, otherwise don't.

The error messages are also more akin to Rust's this way, always putting associated types into context.

> It may be using unbound type variables for these types under the hood.

I had a look: https://github.com/noir-lang/noir/issues/11347#issuecomment-3806077998

It turns out that the generics were added _implicitly_, which is why it doesn't go into [this](https://github.com/noir-lang/noir/blob/f00ead976b22b35a2746c6db06fd77609cabe6ea/compiler/noirc_frontend/src/hir_def/types/unification.rs#L223) rule but stop at the [equality check](https://github.com/noir-lang/noir/blob/f00ead976b22b35a2746c6db06fd77609cabe6ea/compiler/noirc_frontend/src/hir_def/types/unification.rs#L102-L105). 

I am not sure exactly what's so special about these being implicit, but it's a soundness bug: it allows me to pass invalid data, and if it satisfies SSA then it goes along with it.

**Comment by aakoshh** [comment]
@jfecher  I opened https://github.com/noir-lang/noir/pull/11351 to fix that other issue, but it's also based on this change. If we didn't add more context to the names, then it would need a different solution as the names in the example are the same, but both are just associated types, no mixing with ordered.

**Comment by jfecher** [comment]
> I'm not sure where we might be missing something, but I found an instance where the NamedGeneric was already assigned this <{object} as {trait}>::{name} label instead of just name:

I think that was originally added so that when the type showed up in error messages it was more clear where it originated from.

> I opened https://github.com/noir-lang/noir/pull/11351 to fix that other issue, but it's also based on this change. If we didn't add more context to the names, then it would need a different solution as the names in the example are the same, but both are just associated types, no mixing with ordered.

I'm fine with going through with this PR, just a bit worried since it exposes just how stringly-typed our current system is. E.g. maybe we should only compare by their typevariableid

**Comment by aakoshh** [comment]
@jfecher I agree with the stringiness being a problem. I actually started this PR by adding an optional `TraitId` to the `NamedGeneric` and comparing that in https://github.com/noir-lang/noir/pull/11346/commits/b3c4e32baa14ab1f2e4a638483cd8dd03d48a4e6

It worked, but the error message was still saying "expected Bar but got Bar", so I went down the route of following the `<{object} as {trait>::{name}` example, thinking that you really wanted unification to be based on stuffing the `name` with more information. Thanks for sharing that it was meant for debug purposes.

I created another ticket where the same trait and type appears across different modules, to show that comparing names the way I do in this PR is still insufficient:
https://github.com/noir-lang/noir/issues/11358

I'll open another one tomorrow to add back the `TraitId` and then the name can be info only.

**Comment by jfecher** [comment]
@aakoshh I'd rather an approach based on the typevariableids that are already there. As is done in e.g. https://github.com/noir-lang/noir/pull/11354. I think with #11358 specifically (I tested it with that PR) there must be unbound type variables that are being bound to each other first. This would be consistent with your note that these types are set equal to each other first, then tested.

**Comment by aakoshh** [comment]
@jfecher that sounds good. Just to confirm you are seeing that sometimes the type variables are different, but they should still unify, right?

(Actually with the `TraitId` it wouldn't cover the same item from different objects, so it would need that information as well).

**Comment by jfecher** [comment]
@aakoshh I'm not 100% sure what you mean but I always expect the same named generic to have the same type variable id and for different ones to have different ids.

For the type variable comment I was speculating that we may allow unification of associated types when they're only implicitly specified. E.g we treat
```noir
fn foo<T: Iterator>(x: T) {}
```
as
```noir
fn foo<T: Iterator<Item = _>>(x: T) {}
```
or at least that was my theory but https://github.com/noir-lang/noir/pull/7026 shows we've always added them as actual, but implicit NamedGenerics. The behavior we're seeing does look like type variables being bound over though so perhaps that is still happening somewhere.
