### PR TITLE
fix: improve misleading error message when object type is unknown

### LINKED ISSUE #7798: Misleading error message when object type is unknown in method call
### Aim

The error message given for this code is misleading.

```noir
fn foo<let N: u32>() -> [Field; N] {
  let mut bar = std::mem::zeroed();
  for i in 0..bar.len() { .... } 
  bar
}
```

### Expected Behavior

Currently the error message is:

```
error: No method named 'len' found for type '[Field; N]'
  ┌─ src/main.nr:3:15
  │
3 │   for i in 0..bar.len() { 
  │     
```

which is misleading because `[Field; N]` does have a `len` method.

### Bug

Instead, it should say that `bar`'s type is unknown at that point, like in Rust.

### To Reproduce

1.
2.
3.
4.

### Workaround

None

### Workaround Description

_No response_

### Additional Context

Originally reported by @nventuro 

### Project Impact

None

### Blocker Context

_No response_

### Nargo Version

_No response_

### NoirJS Version

_No response_

### Proving Backend Tooling & Version

_No response_

### Would you like to submit a PR for this Issue?

None

### Support Needs

_No response_

### PR DESCRIPTION
**Pull request by asterite**
# Description

## Problem

Resolves #7798

## Documentation

Check one:
- [x] No documentation needed.
- [ ] Documentation included in this PR.
- [ ] **[For Experimental Features]** Documentation to be submitted in a separate PR.

# PR Checklist

- [x] I have tested the changes locally.
- [x] I have formatted the changes with [Prettier](https://prettier.io/) and/or `cargo fmt` on default settings.

### CODE REVIEW

**Review by michaeljklein — APPROVED** [review]

File: compiler/noirc_frontend/src/tests.rs [hunk 1]
```diff
@@ -4183,3 +4183,21 @@ fn mutable_reference_to_array_element_as_func_arg() {
...
     check_errors(src);
 }
+
+#[test]
+fn object_type_must_be_known_in_method_call() {
+    let src = r#"
+    pub fn foo<let N: u32>() -> [Field; N] {
+        let mut bar = _;
+                      ^ in expressions, `_` can only be used on the left-hand side of an assignment
+                      ~ `_` not allowed here
```
Comment (jfecher) [inline compiler/noirc_frontend/src/tests.rs:4193]: Does this really reproduce the original error? I'm not sure if bar's type would be an unbound typevar here or the error type. To guarantee it is unbound you could do something a bit roundabout:
```rs
let array = [];
let bar = array[0]; // this would panic at runtime but we don't run the program
```

**Review by jfecher — APPROVED** [review]

File: compiler/noirc_frontend/src/tests.rs (hunk 1 above)
Comment (asterite) [reply compiler/noirc_frontend/src/tests.rs]: Nice, thanks! I was looking of a way to get an untyped value but couldn't figure out how. I checked that with `_` the error message is the same, but it just adds noise to the test.
