### PR TITLE
fix(ssa refactor): Prevent stores in 'then' branch from affecting the 'else' branch

### LINKED ISSUE #1826: `else` branch of an `if` uses the stores from the `then` branch
### Aim

Proving the code:
```rs
fn main() {
    let mut j = 0;
    let mut i = 2;

    if i < 2 {
        j += i * 10;
        i += 1;
    } else if i < 4 {
        j += i * 100;
        i += 1;
    }

    println(j);
}
```

### Expected Behavior

For `200` to be printed

### Bug

`310` is actually printed out because the `flatten_cfg` pass merges stores at the end of an if, but does not undo any stores from the `then` branch before the `else` branch is run. So the `else` branch sees `j = 20` and `i = 3` instead of `j = 0` and `i = 2`.

### To Reproduce

1.
2.
3.
4.

### Installation Method

None

### Nargo Version

_No response_

### Additional Context

_No response_

### Would you like to submit a PR for this Issue?

No

### Support Needs

_No response_

### PR DESCRIPTION
**Pull request by jfecher**
# Description

## Problem\*

Resolves #1826

## Summary\*

Previously, any stores in the `then` branch of an `if` would be picked up by the `else` branch as well (See the linked issue for more details). This PR adds an extra step to the flattening pass to restore the old values of each store between the then and else branches to fix this.

I've also altered the `merge_stores_with_offset` test since we no longer support offsets from allocations after the switch to immutable arrays. I changed the test to a simple merge stores test but with an else block.

## Documentation

- [ ] This PR requires documentation updates when merged.

  

  - [ ] I will submit a noir-lang/docs PR.

  

  - [ ] I will request for and support Dev Rel's help in documenting this PR.

  
  

## Additional Context

# PR Checklist\*

- [x] I have tested the changes locally.
- [x] I have formatted the changes with [Prettier](https://prettier.io/) and/or `cargo fmt` on default settings.

### CODE REVIEW

File: crates/noirc_evaluator/src/ssa_refactor/opt/flatten_cfg.rs [hunk 1]
```diff
@@ -572,9 +576,27 @@ impl<'f> Context<'f> {
...
+            } else {
+                new_map.insert(address, (store.old_value, store.new_value, store.old_value));
+            }
+        }
+
+        let then_condition = then_branch.condition;
+        let else_condition = else_branch.condition;
+
+        for (address, (then_case, else_case, old_value)) in new_map {
+            println!("Merging {address} := {then_case}, {else_case}, old: {old_value}");
```
Comment (kevaundray) [inline crates/noirc_evaluator/src/ssa_refactor/opt/flatten_cfg.rs:599]:
```suggestion
```

File: crates/noirc_evaluator/src/ssa_refactor/opt/flatten_cfg.rs [hunk 2]
```diff
@@ -572,9 +576,27 @@ impl<'f> Context<'f> {
...
     fn merge_stores(&mut self, then_branch: Branch, else_branch: Branch) {
-        let mut merge_store = |address, then_case, else_case, old_value| {
-            let then_condition = then_branch.condition;
-            let else_condition = else_branch.condition;
+        // Address -> (then_value, else_value, value_before_the_if)
+        let mut new_map = HashMap::with_capacity(then_branch.store_values.len());
+
+        for (address, store) in then_branch.store_values {
+            new_map.insert(address, (store.new_value, store.old_value, store.old_value));
+            // merge_store(address, store.new_value, store.old_value, store.old_value);
```
Comment (kevaundray) [inline crates/noirc_evaluator/src/ssa_refactor/opt/flatten_cfg.rs:584]:
```suggestion
```

**Review by kevaundray — APPROVED** [review]
