### PR TITLE
fix: type-check turbofish in trait before function call

### LINKED ISSUE #6310: Enable turbofish for traits
### Problem

This should compile:

```noir
trait Foo<T> {
    fn foo(x: T) -> Self;
}

struct Bar {}

impl Foo<i32> for Bar {
    fn foo(x: i32) -> Self {
        Bar {}
    }
}

fn main() {
    let bar: Bar = Foo::<i32>::foo(42);
}
```

### Happy Case

The above code compiles.

### Workaround

None

### Workaround Description

_No response_

### Additional Context

_No response_

### Project Impact

None

### Blocker Context

_No response_

### Would you like to submit a PR for this Issue?

None

### Support Needs

_No response_

### PR DESCRIPTION
**Pull request by asterite**
# Description

## Problem

Resolves #6310

## Documentation

Check one:
- [x] No documentation needed.
- [ ] Documentation included in this PR.
- [ ] **[For Experimental Features]** Documentation to be submitted in a separate PR.

# PR Checklist

- [x] I have tested the changes locally.
- [x] I have formatted the changes with [Prettier](https://prettier.io/) and/or `cargo fmt` on default settings.

### CODE REVIEW

File: compiler/noirc_frontend/src/elaborator/patterns.rs [hunk 1]
```diff
@@ -581,10 +614,20 @@ impl<'context> Elaborator<'context> {
...
-            PathResolutionItem::TraitFunction(_trait_id, Some(generics), _func_id) => {
-                // TODO: https://github.com/noir-lang/noir/issues/6310
-                self.push_err(TypeCheckError::UnsupportedTurbofishUsage { span: generics.span });
-                Vec::new()
+            PathResolutionItem::TraitFunction(trait_id, Some(generics), _func_id) => {
+                let trait_ = self.interner.get_trait(trait_id);
+                let trait_generics = vecmap(&trait_.generics, |generic| {
+                    self.interner.next_type_variable_with_kind(generic.kind())
+                });
+                let kinds = vecmap(&trait_.generics, |generic| generic.kind());
```
Comment (aakoshh) [inline compiler/noirc_frontend/src/elaborator/patterns.rs:622]:
```suggestion
                let kinds = vecmap(&trait_.generics, |generic| generic.kind());
                let trait_generics = vecmap(kinds, self.interner.next_type_variable_with_kind);                
```
Not sure it compiles, just thought it would make it easier to see that the generics come from the kinds.

Comment (asterite) [reply compiler/noirc_frontend/src/elaborator/patterns.rs]: It didn't work with that syntax, but I pushed a change for that.

**Review by jfecher — APPROVED** [review]
