### PR TITLE
fix: Implement new mem2reg pass

### LINKED ISSUE #2316: Mem2Reg pass may produce incorrect code when mutable references are aliased
### Aim

In the following code, after the call to `increment` the value of x remains unchanged: 

```rust
fn increment(mut r: &mut Field) {
    *r = *r + 1;
}

fn main() {
    let mut x = 100;
    let mut xref = &mut x;
    increment(xref);
    assert(*xref == 101); // fails! x is still 100
}
```

This bug is very similar to (possibly the same as) https://github.com/noir-lang/noir/issues/2255, but there the mutable variable of type MutRef is a parameter, and here it's a local.

The SSA for increment is correct, the bug is in main:
```
acir fn main f0 {
  b0():
    v1 = allocate
    store Field 100 at v1
    v2 = allocate     // copying x
    store v1 at v2
    v4 = load v2      // reference to the copy
    call f1(v4)       // this modifies the copy
    v5 = load v2
    v6 = load v5
    v8 = eq v6, Field 101
    constrain v8
    return
}
```

### Expected Behavior

the example proves properly

### Bug

it doesn't

### To Reproduce

_No response_

### Installation Method

Compiled from source

### Nargo Version

_No response_

### Additional Context

_No response_

### Would you like to submit a PR for this Issue?

Yes

### Support Needs

_No response_

### LINKED ISSUE #2406: Implement a new Mem2Reg Algorithm
### Problem

Our existing mem2reg algorithm is insufficient in that it needs to be expanded to handle aliasing and invalidation of references after they are passed to function calls. This is currently blocking a few PRs and issues, most notably https://github.com/noir-lang/noir/pull/2348 which is required to fix issues such as https://github.com/noir-lang/noir/issues/2382.

### Happy Case

We implement a new mem2reg algorithm as detailed here: https://hackmd.io/@JakeF/S1FA9rTnh

### Alternatives Considered

_No response_

### Additional Context

_No response_

### Would you like to submit a PR for this Issue?

No

### Support Needs

_No response_

### PR DESCRIPTION
**Pull request by jfecher**
# Description

## Problem\*

Resolves #2406
Resolves #2316
Resolves https://github.com/noir-lang/noir/issues/2417

## Summary\*

Overhauls the mem2reg pass in the SSA to handle function calls and aliases.

~~There are some TODOs as part of this PR - I do not plan on implementing these as part of the PR and will create issues for them tomorrow. Most notable of them is that aliases within array values are not tracked.~~

~~I still need to write more documentation for this pass as well. It is missing much of the overall pass architecture documentation from the hackmd document linked in the issue. This PR is also currently missing additional test cases for the new features.~~

## Documentation

- [ ] This PR requires documentation updates when merged.

  

  - [ ] I will submit a noir-lang/docs PR.

  

  - [ ] I will request for and support Dev Rel's help in documenting this PR.

  
  

## Additional Context

Note that in some tests, the expected number of stores that are removed has changed. The new pass will keep each store that is still possibly used as well as the final store in each block. This is because the final store may still be needed when another block is branched to afterward.

# PR Checklist\*

- [x] I have tested the changes locally.
- [x] I have formatted the changes with [Prettier](https://prettier.io/) and/or `cargo fmt` on default settings.

### CODE REVIEW

**Comment by jfecher** [comment]
This PR is ready for review

File: crates/noirc_evaluator/src/ssa/opt/mem2reg.rs [hunk 1]
```diff
@@ -1,378 +1,475 @@
...
+//! - On `Instruction::Allocate`:
+//!   - Register a new reference was made with itself as its only alias
+//! - On `Instruction::Load { address }`:
+//!   - If `address` is known to only have a single alias (including itself) and if the value of
+//!     that alias is known, replace the value of the load with the known value.
+//!   - Furthermore, if the result of the load is a reference, mark that reference as an alias
+//!     of the reference it dereferences to (if known).
+//!     - If which reference it dereferences to is not known, this load result has no aliases.
+//! - On `Instruction::Store { address, value }`:
+//!   - If the address of the store is known:
```
Comment (vezenovm) [inline crates/noirc_evaluator/src/ssa/opt/mem2reg.rs:32]:
```suggestion
//!   - If the address of the store is `Known(value)`:
```

File: crates/noirc_evaluator/src/ssa/opt/mem2reg.rs [hunk 2]
```diff
@@ -1,378 +1,475 @@
...
+//! Finally, if this is the only block in the function, we can remove any Stores that were not
+//! referenced by the terminator instruction.
+//!
+//! Repeating this algorithm for each block in the function in program order should result in
+//! optimizing out most known loads. However, identifying all aliases correctly has been proven 
+//! undecidable in general (Landi, 1992). So this pass will not always optimize out all loads
+//! that could theoretically be optimized out. This pass can be performed at any time in the
+//! SSA optimization pipeline, although it will be more successful the simpler the program's CFG is.
+//! This pass is currently performed several times to enable other passes - most notably being
+//! performed before loop unrolling to try to allow for mutable variables used for for loop indices.
```
Comment (vezenovm) [inline crates/noirc_evaluator/src/ssa/opt/mem2reg.rs]:
```suggestion
//! performed before loop unrolling to try to allow for mutable variables used for loop indices. 
```

File: crates/noirc_evaluator/src/ssa/opt/mem2reg.rs [hunk 3]
```diff
@@ -1,378 +1,501 @@
...
+//! Finally, if this is the only block in the function, we can remove any Stores that were not
+//! referenced by the terminator instruction.
+//!
+//! Repeating this algorithm for each block in the function in program order should result in
+//! optimizing out most known loads. However, identifying all aliases correctly has been proven
+//! undecidable in general (Landi, 1992). So this pass will not always optimize out all loads
+//! that could theoretically be optimized out. This pass can be performed at any time in the
+//! SSA optimization pipeline, although it will be more successful the simpler the program's CFG is.
+//! This pass is currently performed several times to enable other passes - most notably being
+//! performed before loop unrolling to try to allow for mutable variables used for for loop indices.
```
Comment (vezenovm) [inline crates/noirc_evaluator/src/ssa/opt/mem2reg.rs:63]:
```suggestion
//! performed before loop unrolling to try to allow for mutable variables used for loop indices.
```

File: crates/noirc_evaluator/src/ssa/opt/mem2reg.rs [hunk 4]
```diff
@@ -1,378 +1,501 @@
...
-                    if has_common_successor {
-                        protected_allocations.insert(address);
-                    }
-                    address = self.fetch_load_value_to_substitute(block_id, address);
+    /// The value of each reference at the start of the given block is the unification
+    /// of the value of the same reference at the end of its predecessor blocks.
+    fn find_starting_references(&mut self, block: BasicBlockId) -> Block {
+        let mut predecessors = self.cfg.predecessors(block);
+
+        if let Some(first_predecessor) = predecessors.next() {
```
Comment (vezenovm) [inline crates/noirc_evaluator/src/ssa/opt/mem2reg.rs:177]: Is there is an issue with unifying values across multiple predecessors? Should we add a check that `first_predecessor` actually dominates `block` ?

File: crates/noirc_evaluator/src/ssa/opt/mem2reg.rs [hunk 5]
```diff
@@ -1,378 +1,501 @@
...
-        }
+        self.handle_terminator(function, block, &mut references, &mut last_stores);
 
-        // Substitute load result values
-        for (result_value, new_value) in load_values_to_substitute_per_block {
-            let result_value = dfg.resolve(*result_value);
-            dfg.set_value_from_id(result_value, *new_value);
+        // If there's only 1 block in the function total, we can remove any remaining last stores
+        // as well. We can't do this if there are multiple blocks since subsequent blocks may
+        // reference these stores.
```
Comment (vezenovm) [inline crates/noirc_evaluator/src/ssa/opt/mem2reg.rs:214]: Is this fine even if we have a function with 1 block that has remaining stores, but the remaining stores are to aliases passed into the function?

Comment (vezenovm) [reply crates/noirc_evaluator/src/ssa/opt/mem2reg.rs:214]: Nevermind I see in the definition of `remove_stores_that_do_not_alias_parameters` you check against aliases. Could we add that to this comment as well?

File: crates/noirc_evaluator/src/ssa/opt/mem2reg.rs [hunk 6]
```diff
@@ -1,378 +1,503 @@
...
-            for successor in successors {
-                if !visited.contains(&successor) {
-                    stack.push(successor);
+impl Block {
+    /// If the given reference id points to a known value, return the value
+    fn get_known_value(&self, address: ValueId) -> Option<ValueId> {
+        if let Some(expression) = self.expressions.get(&address) {
+            if let Some(aliases) = self.aliases.get(expression) {
+                // We could allow multiple aliases if we check that the reference
+                // value in each is equal.
```
Comment (vezenovm) [inline crates/noirc_evaluator/src/ssa/opt/mem2reg.rs:376]: Should we make an issue for this or is it already being worked on?

File: crates/noirc_evaluator/src/ssa/opt/mem2reg.rs [hunk 7]
```diff
@@ -578,9 +703,9 @@ mod tests {
         assert_eq!(count_loads(main.entry_block(), &main.dfg), 0);
         assert_eq!(count_loads(b1, &main.dfg), 0);
 
-        // All stores should be removed
-        assert_eq!(count_stores(main.entry_block(), &main.dfg), 0);
-        assert_eq!(count_stores(b1, &main.dfg), 0);
+        // Neither store is removed since they are each the last in the block and there are multiple blocks
```
Comment (vezenovm) [inline crates/noirc_evaluator/src/ssa/opt/mem2reg.rs:706]: So even though we can resolve v3 and v4 is this due to v0 potentially being an alias?

**Review by vezenovm — COMMENTED** [review]
Nice, the documentation and code reads well. Mainly a couple nits and questions

File: crates/noirc_evaluator/src/ssa/opt/mem2reg.rs (hunk 2 above)
Comment (jfecher) [reply crates/noirc_evaluator/src/ssa/opt/mem2reg.rs]: The repeated for is correct here, its for "for loop" indices

File: crates/noirc_evaluator/src/ssa/opt/mem2reg.rs (hunk 3 above)
Comment (vezenovm) [reply crates/noirc_evaluator/src/ssa/opt/mem2reg.rs:63]: I accidentally commented this twice

File: crates/noirc_evaluator/src/ssa/opt/mem2reg.rs (hunk 2 above)
Comment (jfecher) [reply crates/noirc_evaluator/src/ssa/opt/mem2reg.rs]: Ah, I see that it still means the same without it though so I'll remove it

Comment (vezenovm) [reply crates/noirc_evaluator/src/ssa/opt/mem2reg.rs]: Could we say "as for loop indices" then?

File: crates/noirc_evaluator/src/ssa/opt/mem2reg.rs (hunk 4 above)
Comment (jfecher) [reply crates/noirc_evaluator/src/ssa/opt/mem2reg.rs:177]: I'm not sure what this comment means - we do unify values across multiple (direct) predecessors. The domination check is unneeded since all predecessors do not need to dominate the block.

File: crates/noirc_evaluator/src/ssa/opt/mem2reg.rs (hunk 2 above)
Comment (TomAFrench) [reply crates/noirc_evaluator/src/ssa/opt/mem2reg.rs]: I tend to use "for-loop" in cases like this.

File: crates/noirc_evaluator/src/ssa/opt/mem2reg.rs (hunk 5 above)
Comment (jfecher) [reply crates/noirc_evaluator/src/ssa/opt/mem2reg.rs:214]: I think the function name is descriptive enough here such that we don't need to add to the comment.

File: crates/noirc_evaluator/src/ssa/opt/mem2reg.rs (hunk 6 above)
Comment (jfecher) [reply crates/noirc_evaluator/src/ssa/opt/mem2reg.rs:376]: I'll make an issue. It shouldn't be too hard to implement, I just thought it was a somewhat rare case where a reference is aliased to multiple others which all are known to store the same value. Perhaps this assumption was incorrect though.

File: crates/noirc_evaluator/src/ssa/opt/mem2reg.rs (hunk 4 above)
Comment (vezenovm) [reply crates/noirc_evaluator/src/ssa/opt/mem2reg.rs:177]: Ah I misread how this method was going over the predecessors, I see now. And makes sense with the domination check you are correct.

File: crates/noirc_evaluator/src/ssa/opt/mem2reg.rs (hunk 5 above)
Comment (vezenovm) [reply crates/noirc_evaluator/src/ssa/opt/mem2reg.rs:214]: Yeah fair enough

File: crates/noirc_evaluator/src/ssa/opt/mem2reg.rs (hunk 6 above)
Comment (jfecher) [reply crates/noirc_evaluator/src/ssa/opt/mem2reg.rs:376]: #2443

File: crates/noirc_evaluator/src/ssa/opt/mem2reg.rs (hunk 7 above)
Comment (jfecher) [reply crates/noirc_evaluator/src/ssa/opt/mem2reg.rs:706]: The mem2reg pass only tries to remove the last store in a block if it is also the only block in the function.

We could expand the analysis across multiple blocks and we'd have to check if there were no unoptimized loads between that store and every successor of that block. I think this would be too much bookkeeping since it requires us to track block successors now as well and it is unneeded since after flattening there will only be one block remaining anyway. For brillig functions which do not flatten (in the future when we apply optimizations to them), we still try to optimize out loads as normal but there may be some stores remaining since only multiple stores within the same block would be removed.

File: crates/noirc_evaluator/src/ssa/opt/mem2reg.rs (hunk 2 above)
Comment (jfecher) [reply crates/noirc_evaluator/src/ssa/opt/mem2reg.rs]: I just took your suggestion since "loop indices" works, we don't need to specify it is a for loop.

**Review by vezenovm — APPROVED** [review]
LGTM
