### PR TITLE
fix(brillig): Use value set for tracking max live count

### LINKED ISSUE #12297: variable_liveness: max_live_count for MakeArray doesn't take results into account
### Aim

When computing the maximum number of live variables at any point in time, for MakeArray we take into account that we need temporary registers for each unique element in the array, then the maximum count is the current count plus this number of unique elements:

https://github.com/noir-lang/noir/blob/6276ac789952446ac24965ef93c018cb842dd53a/compiler/noirc_evaluator/src/brillig/brillig_gen/variable_liveness.rs#L452-L457

However, at the same time we also need a register for the result of the MakeArray instruction, and that is not taken into account here.

The results are tracked later on, separately, but at this point the unique elements in MakeArray are not included:

https://github.com/noir-lang/noir/blob/6276ac789952446ac24965ef93c018cb842dd53a/compiler/noirc_evaluator/src/brillig/brillig_gen/variable_liveness.rs#L459-L462

With the current spilling configuration (particularly SPILL_MARGIN being 32) there's no Noir program that can trigger this bug, but maybe the issue should be fixed in any case.

Claude came up with some tests that demonstrate this bug:

```rust
    #[test]
    fn make_array_peak_includes_result() {
        // brillig fn main f0 {
        //   b0():
        //     v0 = make_array [Field 1, Field 2, Field 3] : [Field; 3]
        //     return v0
        // }
        //
        // During MakeArray, the result register (v0) is allocated first, then the 3 element
        // registers are written into it. All 4 are simultaneously live at the peak, so
        // max_live_count should be 4, not 3.
        use std::sync::Arc;

        use acvm::acir::brillig::lengths::SemanticLength;
        use im::vector;

        let main_id = Id::test_new(1);
        let mut builder = FunctionBuilder::new("main".into(), main_id);
        builder.set_runtime(RuntimeType::Brillig(InlineType::default()));

        let one = builder.field_constant(1u128);
        let two = builder.field_constant(2u128);
        let three = builder.field_constant(3u128);

        let array_type = Type::Array(Arc::new(vec![Type::field()]), SemanticLength(3));
        let v0 = builder.insert_make_array(vector![one, two, three], array_type);
        builder.terminate_with_return(vec![v0]);

        let ssa = builder.finish();
        let func = ssa.main();
        let constants = ConstantAllocation::from_function(func);
        let liveness = VariableLiveness::from_function(func, &constants);

        // 3 unique element registers + 1 result register = 4 simultaneously live
        assert_eq!(liveness.max_live_count, 4);
    }
```

```rust
/// Regression test for the `compute_max_live_count` bug where `MakeArray` does not
/// count the result register as simultaneously live with the element registers.
///
/// During Brillig codegen the result register is allocated first (via `define_variable`),
/// then all element registers are written into it. So at the peak, `results.len()`
/// result registers and `unique_elements.len()` element registers are live at the same time.
/// The old code only took `max(current_count + elements, current_count + results)` but never
/// `current_count + elements + results`.
///
/// With `frame_size = 36` and `SPILL_MARGIN = 32`, spill is triggered when
/// `max_live_count + 32 >= 36`, i.e. `max_live_count >= 4`.
///
/// For an array `[Field 1, Field 2, Field 3]` with no other live variables:
///   - correct:  max_live_count = 3 (elements) + 1 (result) = 4 → spill triggered
///   - buggy:    max_live_count = max(3, 1) = 3            → no spill
///
/// A spill prologue `sp[1] = @1` at instruction 0 proves the correct decision was made.
#[test]
fn brillig_make_array_peak_count_includes_result() {
    let src = "
    brillig(inline) fn main f0 {
      b0():
        v0 = make_array [Field 1, Field 2, Field 3] : [Field; 3]
        return v0
    }
    ";

    // frame_size=36, SPILL_MARGIN=32 → threshold is max_live_count >= 4.
    // Correct count = 4 → spill triggered → prologue emitted.
    let layout = LayoutConfig::new(36, 16, MAX_SCRATCH_SPACE);
    let options = BrilligOptions { layout, ..Default::default() };
    let brillig = ssa_to_brillig_artifacts_with_options(src, &options);
    let main = &brillig.ssa_function_to_brillig[&Id::test_new(0)];

    // The spill prologue `sp[1] = @1` at instruction 0 is only emitted when
    // max_live_count >= 4. Without the fix, max_live_count = 3 and no prologue appears.
    assert!(main.to_string().contains("sp[1] = @1"), "expected spill prologue but got:\n{}", main);
}
```

### Expected Behavior

The max count should be one more than the unique elements in the MakeArray instructions.

### Bug

The MakeArray results are not included in the count.

### To Reproduce

1.
2.
3.
4.

### Workaround

None

### Workaround Description

_No response_

### Additional Context

_No response_

### Project Impact

Nice-to-have

### Blocker Context

_No response_

### Nargo Version

_No response_

### NoirJS Version

_No response_

### Proving Backend Tooling & Version

_No response_

### Would you like to submit a PR for this Issue?

None

### Support Needs

_No response_

### LINKED ISSUE #12305: variable_liveness: compute_max_live_count does not count constants
### Problem

Constants are variables that can be allocated in a block, as we can see on line 341: `defined_vars.extend(constants.allocated_in_block(block_id));`

However they are not defined by regular instructions, but by an ad-hoc mechanism (see `initialize_constants()` in brillig_block.rs).
So they are not taken into account in compute_max_live_count().
There is a workaround for MakeArray instructions (that can consume a lot of constants), but the workaround does not target constants specifically and ends-up counting non-constant values twice.
The following test demonstrates the issue:
```
    #[test]
    fn max_live_count_undercounts_constants_outside_make_array() {
        let src = "
        brillig(inline) fn main f0 {
          b0(v0: Field):
            v1 = add v0, Field 1
            return v1
        }
        ";
        let ssa = Ssa::from_str(src).unwrap();
        let func = ssa.main();
        let constants = ConstantAllocation::from_function(func);
        let liveness = VariableLiveness::from_function(func, &constants);

        // Sanity: the constant `Field 1` is indeed allocated in b0,
        let allocated_in_entry = constants.allocated_in_block(func.entry_block());
        assert!(
            !allocated_in_entry.is_empty(),
            "expected Field 1 to be allocated in the entry block, but nothing was"
        );

        // The true peak is 3 registers: v0 + Field 1 + v1 must coexist during
        // the add. The current implementation reports only 2 because constants
        // used by instructions are never added to `current_count` (except for MakeArray).
        assert!(
            liveness.max_live_count >= 3,
            "expected max_live_count >= 3 (v0 + Field 1 + v1 live during the add), \
             got {}. Constants used by non-MakeArray instructions are not counted.",
            liveness.max_live_count
        );
    }
```

### Happy Case

We already have all the required information in `ConstantAllocation`, that we just need to pass to `compute_max_live_count`
Then we can simply take into account constants allocated before every instruction.
We also need to count it for the terminator instruction, and remove the special case for MakeArray instruction.

```rust
fn compute_max_live_count(mut self, func: &Function, constants: &ConstantAllocation) -> Self {
    let mut max_count: usize = 0;

    for block_id in func.reachable_blocks() {
        let block = &func.dfg[block_id];
        let last_uses = self.get_last_uses(&block_id);

        // Initial live set at block entry
        let mut live_set: HashSet<ValueId> = self.get_live_in(&block_id).iter().copied().collect();
        live_set.extend(self.defined_block_params(&block_id));
        max_count = max_count.max(live_set.len());

        for instruction_id in block.instructions() {
            // Materialize constants allocated at this instruction location
            if let Some(new_consts) = constants
                .allocated_at_location(block_id, InstructionLocation::Instruction(*instruction_id))
            {
                live_set.extend(new_consts.iter().copied());
                max_count = max_count.max(live_set.len());
            }

            // Add results defined by this instruction.
            let results = func.dfg.instruction_results(*instruction_id);
            live_set.extend(results.iter().copied());
            max_count = max_count.max(live_set.len());

           // Subtract variables that die after this instruction.
            if let Some(dead) = last_uses.get(instruction_id) {
                for d in dead {
                    live_set.remove(d);
                }
            }
        }

        // Also handle constants allocated at the terminator
        if let Some(new_consts) =
            constants.allocated_at_location(block_id, InstructionLocation::Terminator)
        {
            live_set.extend(new_consts.iter().copied());
            max_count = max_count.max(live_set.len());
        }
    }

    self.max_live_count = max_count;
    self
}
```

### Workaround

None

### Workaround Description

_No response_

### Additional Context

_No response_

### Project Impact

None

### Blocker Context

_No response_

### Would you like to submit a PR for this Issue?

None

### Support Needs

_No response_

### PR DESCRIPTION
**Pull request by vezenovm**
# Description

## Problem

Resolves #12305
Resolves #12297

## Summary

- `compute_max_live_count` did not account for constants materialized at instruction locations, undercounting peak register pressure (e.g. v1 = add v0, Field 1 reported 2 live instead of 3)
- Switched from a plain counter to a `HashSet<ValueId>` live set, adding constants via `ConstantAllocation::allocated_at_location` at each instruction and the terminator. The set prevents double-counting values that are both constants and array elements 
- Added regression test `max_live_count_includes_constants_outside_make_array` from #12305
- #12297 by extending the current `live_set` before each `max_count` update for both the `MakeArray` elements and the instruction results

## User Documentation

Check one:
- [X] No user documentation needed.
- [ ] Changes in _docs/_ included in this PR.
- [ ] **[For Experimental Features]** Changes in _docs/_ to be submitted in a separate PR.

# PR Checklist

- [X] I have tested the changes locally.
- [X] I have formatted the changes with [Prettier](https://prettier.io/) and/or `cargo fmt` on default settings.

### CODE REVIEW

**Review by jfecher — COMMENTED** [review]
LGTM. I'll leave for an auditor @asterite or @guipublic to give the final 👍

File: compiler/noirc_evaluator/src/brillig/brillig_gen/variable_liveness.rs [hunk 1]
```diff
@@ -1073,6 +1091,38 @@ mod tests {
...
+
+        // The constant `Field 1` should be allocated in b0.
+        let allocated_in_entry = constants.allocated_in_block(func.entry_block());
+        assert!(
+            !allocated_in_entry.is_empty(),
+            "expected Field 1 to be allocated in the entry block, but nothing was"
+        );
+
+        // The true peak is 3 registers: v0 + Field 1 + v1 must coexist during
+        // the add. The current implementation reports only 2 because constants
```
Comment (asterite) [inline compiler/noirc_evaluator/src/brillig/brillig_gen/variable_liveness.rs]: Is this comment outdated?

**Review by asterite — APPROVED** [review]

File: compiler/noirc_evaluator/src/brillig/brillig_gen/variable_liveness.rs (hunk 1 above)
Comment (vezenovm) [reply compiler/noirc_evaluator/src/brillig/brillig_gen/variable_liveness.rs]: yes will update
