### PR TITLE
fix: correct proptest Arbitrary for NumericType

### LINKED ISSUE #7933: `proptest_derive::Arbitrary` generating invalid bitsizes
### Aim

This is part of the `compiler>noirc_evaluator>src>ssa>ir>types.rs`. 
When creating a proptest that is generating different `NumericTypes`, `proptest_derive::Arbitrary` can generate invalid bit lengths, e.g. `u129`. For instance, the following test would output 
```bash
Test failed: attempt to multiply with overflow.
minimal failing input: input = Unsigned {
    bit_size: 129,
}
```

```rust
#[derive(Copy, Clone, Debug, PartialEq, Eq, Hash, Ord, PartialOrd, Serialize, Deserialize)]
#[cfg_attr(test, derive(proptest_derive::Arbitrary))]
pub enum NumericType {
    Signed { bit_size: u32 },
    Unsigned { bit_size: u32 },
    NativeField,
}

impl NumericType {
    pub(crate) fn max_value(&self) -> Result<FieldElement, String> {
        match self {
            NumericType::Unsigned { bit_size } => {
                if *bit_size == 128 {
                    Ok(FieldElement::from(u128::MAX))
                } else {
                    Ok(FieldElement::from(2u128.pow(*bit_size) - 1))
                }
            }
            NumericType::Signed { bit_size } => {
                Err("Cannot get max value for signed type".to_string())
            }
            NumericType::NativeField => {
                Err("Cannot get max value for native field type".to_string())
            }
        }
    }
}

#[cfg(test)]
mod tests {
    use super::*;
    use proptest::prelude::*;

    proptest! {
        #[test]
        fn test_max_value_is_in_limits(input: NumericType) {
            let max_value = input.max_value();
            if let Ok(max_value) = max_value {
                prop_assert!(input.value_is_outside_limits(SignedField::from(max_value)).is_none());
            }
        }
    }
}

``` 

I've hacked around this by checking the `bit_length` in the `max_value` function, but it is not ideal. 

### Expected Behavior

the `proptest_derive::Arbitrary` should only generate valid types (`u128,u64,u32,u16,u8, Field`).

### Bug

provided in the description 

### To Reproduce

1.
2.
3.
4.

### Workaround

None

### Workaround Description

_No response_

### Additional Context

_No response_

### Project Impact

None

### Blocker Context

_No response_

### Nargo Version

_No response_

### NoirJS Version

_No response_

### Proving Backend Tooling & Version

_No response_

### Would you like to submit a PR for this Issue?

None

### Support Needs

_No response_

### PR DESCRIPTION
**Pull request by asterite**
# Description

## Problem

Resolves #7933

## Additional Context

I'm not familiar with the proptest library so let me know if there's a more idiomatic way of doing this.

## Documentation

Check one:
- [x] No documentation needed.
- [ ] Documentation included in this PR.
- [ ] **[For Experimental Features]** Documentation to be submitted in a separate PR.

# PR Checklist

- [x] I have tested the changes locally.
- [x] I have formatted the changes with [Prettier](https://prettier.io/) and/or `cargo fmt` on default settings.

### CODE REVIEW

File: compiler/noirc_evaluator/src/ssa/ir/types.rs [hunk 1]
```diff
@@ -101,6 +100,32 @@ impl NumericType {
...
+
+    use super::NumericType;
+
+    impl Arbitrary for NumericType {
+        type Parameters = ();
+        type Strategy = BoxedStrategy<Self>;
+
+        fn arbitrary_with(_args: Self::Parameters) -> Self::Strategy {
+            let signed = prop_oneof!(Just(8), Just(16), Just(32), Just(64));
+            let unsigned = prop_oneof!(Just(8), Just(16), Just(32), Just(64), Just(128));
```
Comment (jfecher) [inline compiler/noirc_evaluator/src/ssa/ir/types.rs:118]: Should we add `u1` here too?

Comment (asterite) [reply compiler/noirc_evaluator/src/ssa/ir/types.rs]: Thanks, added!

**Review by TomAFrench — APPROVED** [review]
