### PR TITLE
Fix #419 by disallowing bitwise operations on fields during type checking

### LINKED ISSUE #419: Proof creation involving bit shift results in runtime error
# Description

## Aim

To create a proof for the following (contrived) program:

```
fn main(x : Field, y : pub Field) {
    let z: Field = 2 << 2;
    constrain x + y == z;
}
```

## Expected behavior

A proof should be created. A proof is successfully created if the line

`let z: Field = 2 << 2;`

is replaced with the following line:

`let z: Field = (2 - y + y) << 2;`

## Bug

The following runtime error results from an invocation of `nargo prove`:

> thread 'main' panicked at 'internal error: entered unreachable code: operation not allowed for FieldElement', crates/noirc_evaluator/src/ssa/node.rs:1033:5
> note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace

Running with `RUST_BACKTRACE=full` yields:

> thread 'main' panicked at 'internal error: entered unreachable code: operation not allowed for FieldElement', crates/noirc_evaluator/src/ssa/node.rs:1033:5
> stack backtrace:
>    0:     0x5624108633cd - std::backtrace_rs::backtrace::libunwind::trace::h9135f25bc195152c
>                                at /rustc/a55dd71d5fb0ec5a6a3a9e8c27b2127ba491ce52/library/std/src/../../backtrace/src/backtrace/libunwind.rs:93:5
>    1:     0x5624108633cd - std::backtrace_rs::backtrace::trace_unsynchronized::h015ee85be510df51
>                                at /rustc/a55dd71d5fb0ec5a6a3a9e8c27b2127ba491ce52/library/std/src/../../backtrace/src/backtrace/mod.rs:66:5
>    2:     0x5624108633cd - std::sys_common::backtrace::_print_fmt::h5fad03caa9652a2c
>                                at /rustc/a55dd71d5fb0ec5a6a3a9e8c27b2127ba491ce52/library/std/src/sys_common/backtrace.rs:66:5
>    3:     0x5624108633cd - <std::sys_common::backtrace::_print::DisplayBacktrace as core::fmt::Display>::fmt::h2b42ca28d244e5c7
>                                at /rustc/a55dd71d5fb0ec5a6a3a9e8c27b2127ba491ce52/library/std/src/sys_common/backtrace.rs:45:22
>    4:     0x56241088906c - core::fmt::write::h401e827d053130ed
>                                at /rustc/a55dd71d5fb0ec5a6a3a9e8c27b2127ba491ce52/library/core/src/fmt/mod.rs:1198:17
>    5:     0x56241085daf1 - std::io::Write::write_fmt::hffec93268f5cde32
>                                at /rustc/a55dd71d5fb0ec5a6a3a9e8c27b2127ba491ce52/library/std/src/io/mod.rs:1672:15
>    6:     0x562410864bc5 - std::sys_common::backtrace::_print::h180c4c706ee1d3fb
>                                at /rustc/a55dd71d5fb0ec5a6a3a9e8c27b2127ba491ce52/library/std/src/sys_common/backtrace.rs:48:5
>    7:     0x562410864bc5 - std::sys_common::backtrace::print::hd0c35d18765761c9
>                                at /rustc/a55dd71d5fb0ec5a6a3a9e8c27b2127ba491ce52/library/std/src/sys_common/backtrace.rs:35:9
>    8:     0x562410864bc5 - std::panicking::default_hook::{{closure}}::h1f023310983bc730
>                                at /rustc/a55dd71d5fb0ec5a6a3a9e8c27b2127ba491ce52/library/std/src/panicking.rs:295:22
>    9:     0x5624108648e1 - std::panicking::default_hook::h188fec3334afd5be
>                                at /rustc/a55dd71d5fb0ec5a6a3a9e8c27b2127ba491ce52/library/std/src/panicking.rs:314:9
>   10:     0x562410865156 - std::panicking::rust_panic_with_hook::hf26e9d4f97b40096
>                                at /rustc/a55dd71d5fb0ec5a6a3a9e8c27b2127ba491ce52/library/std/src/panicking.rs:698:17
>   11:     0x562410865047 - std::panicking::begin_panic_handler::{{closure}}::hfab912107608087a
>                                at /rustc/a55dd71d5fb0ec5a6a3a9e8c27b2127ba491ce52/library/std/src/panicking.rs:588:13
>   12:     0x5624108638c4 - std::sys_common::backtrace::__rust_end_short_backtrace::h434b685ce8d9965b
>                                at /rustc/a55dd71d5fb0ec5a6a3a9e8c27b2127ba491ce52/library/std/src/sys_common/backtrace.rs:138:18
>   13:     0x562410864d79 - rust_begin_unwind
>                                at /rustc/a55dd71d5fb0ec5a6a3a9e8c27b2127ba491ce52/library/std/src/panicking.rs:584:5
>   14:     0x56240ff69f33 - core::panicking::panic_fmt::ha6dc7f2ab2479463
>                                at /rustc/a55dd71d5fb0ec5a6a3a9e8c27b2127ba491ce52/library/core/src/panicking.rs:142:14
>   15:     0x5624104fcf51 - core::panicking::unreachable_display::hfff35c31f35084d4
>   16:     0x5624105011ea - noirc_evaluator::ssa::node::Instruction::evaluate::hfff62f5111dbbfc1
>   17:     0x5624104f05a7 - noirc_evaluator::ssa::optim::simplify::h1ab2a26ce417d814
>   18:     0x56241049f4e7 - noirc_evaluator::ssa::context::SsaContext::new_instruction::h3797fe3f7e461a28
>   19:     0x5624104a57ed - noirc_evaluator::ssa::code_gen::IRGenerator::codegen_infix_expression::h800a47e415108afc
>   20:     0x5624104a7b28 - noirc_evaluator::ssa::code_gen::IRGenerator::codegen_expression::h77acaec0aa984e71
>   21:     0x5624104a78c1 - noirc_evaluator::ssa::code_gen::IRGenerator::codegen_expression::h77acaec0aa984e71
>   22:     0x5624104aa5ea - noirc_evaluator::ssa::code_gen::IRGenerator::codegen_block::h7da7d6609fff1c59
>   23:     0x5624104a7c11 - noirc_evaluator::ssa::code_gen::IRGenerator::codegen_expression::h77acaec0aa984e71
>   24:     0x5624104a4ff7 - noirc_evaluator::ssa::code_gen::IRGenerator::codegen_main::h0de8617e12b585ef
>   25:     0x56241049a6fe - noirc_evaluator::Evaluator::evaluate_main_alt::h443c7ebdcb47c2a4
>   26:     0x562410499d1e - noirc_evaluator::create_circuit::h7715ad204eb2728f
>   27:     0x56241049299d - noirc_driver::Driver::into_compiled_program::hb83e38630098dc7b
>   28:     0x56240ff8f57b - nargo::cli::prove_cmd::run::h3eb7ab435ee3e927
>   29:     0x56240ff6f9e1 - nargo::cli::start_cli::h7596c61ea437bf5f
>   30:     0x56240ff6af03 - std::sys_common::backtrace::__rust_begin_short_backtrace::h80fbff91545ac137
>   31:     0x56240ff6ae99 - std::rt::lang_start::{{closure}}::h2d9613884a42737b
>   32:     0x5624108577ee - core::ops::function::impls::<impl core::ops::function::FnOnce<A> for &F>::call_once::hcdfee62722e5e4b8
>                                at /rustc/a55dd71d5fb0ec5a6a3a9e8c27b2127ba491ce52/library/core/src/ops/function.rs:280:13
>   33:     0x5624108577ee - std::panicking::try::do_call::h84ca51609826746f
>                                at /rustc/a55dd71d5fb0ec5a6a3a9e8c27b2127ba491ce52/library/std/src/panicking.rs:492:40
>   34:     0x5624108577ee - std::panicking::try::hd58075e533b8e0cb
>                                at /rustc/a55dd71d5fb0ec5a6a3a9e8c27b2127ba491ce52/library/std/src/panicking.rs:456:19
>   35:     0x5624108577ee - std::panic::catch_unwind::h1ebac24d83cb6ce2
>                                at /rustc/a55dd71d5fb0ec5a6a3a9e8c27b2127ba491ce52/library/std/src/panic.rs:137:14
>   36:     0x5624108577ee - std::rt::lang_start_internal::{{closure}}::h0145388a1edd1640
>                                at /rustc/a55dd71d5fb0ec5a6a3a9e8c27b2127ba491ce52/library/std/src/rt.rs:128:48
>   37:     0x5624108577ee - std::panicking::try::do_call::h7630182e534a0a32
>                                at /rustc/a55dd71d5fb0ec5a6a3a9e8c27b2127ba491ce52/library/std/src/panicking.rs:492:40
>   38:     0x5624108577ee - std::panicking::try::h05b6544f0c6331dc
>                                at /rustc/a55dd71d5fb0ec5a6a3a9e8c27b2127ba491ce52/library/std/src/panicking.rs:456:19
>   39:     0x5624108577ee - std::panic::catch_unwind::h77b2ba8fd3309f34
>                                at /rustc/a55dd71d5fb0ec5a6a3a9e8c27b2127ba491ce52/library/std/src/panic.rs:137:14
>   40:     0x5624108577ee - std::rt::lang_start_internal::h6612c8a7a6861b8b
>                                at /rustc/a55dd71d5fb0ec5a6a3a9e8c27b2127ba491ce52/library/std/src/rt.rs:128:20
>   41:     0x56240ff6aef2 - main
>   42:     0x7f3915a3c290 - <unknown>
>   43:     0x7f3915a3c34a - __libc_start_main
>   44:     0x56240ff6adb5 - _start
>                                at /build/glibc/src/glibc/csu/../sysdeps/x86_64/start.S:115
>   45:                0x0 - <unknown>

# To reproduce

1. (Optional) Populate Prover.toml with appropriate values for x and y (e.g. `x="2"`, `y="6"`).
2. Run `nargo build`, which succeeds.
3. Run `nargo prove proof`, which results in a runtime error.

# Environment

- OS: Arch Linux

For `nargo` users

- _noir-lang/noir_ commit cloned: 22a92a9345ac763903563754a591ed2670aafca9
- Proving backend
  - [X] default
    - Clang:
     clang version 14.0.6
     Target: x86_64-pc-linux-gnu
     Thread model: posix
     InstalledDir: /usr/bin

  - [ ] wasm-base

### PR DESCRIPTION
**Pull request by jfecher**
# Related issue(s)

Resolves #419

# Description

## Summary of changes

This PR makes it a type error to use any of `&`, `|`, `^`, `<<`, or `>>` on a `Field` type. The error message suggests users cast to a sized integer type beforehand.

In the case the operand types for a bitwise operator are still unknown, this PR introduces a delayed type error that is checked when the function as a whole is finished. This allows for cases like `let x: u8 = 2 << 3;` to be valid as the types of `2` and `3` are later resolved to `u8`, while still keeping ambiguous cases invalid. If the types are still ambiguous when the function is finished type checking, an error is issues explaining type annotations are needed to know how many bits to perform the bitwise operations on.

## Test additions / changes

None

# Checklist

- [x] I have tested the changes locally.
- [x] I have formatted the changes with [Prettier](https://prettier.io/) and/or `cargo fmt` with default settings.
- [x] I have [linked](https://docs.github.com/en/issues/tracking-your-work-with-issues/linking-a-pull-request-to-an-issue) this PR to the issue(s) that it resolves.
- [x] I have reviewed the changes on GitHub, line by line.
- [x] I have ensured all changes are covered in the description.

# Additional context

The delayed type error mechanism added by this PR is a workaround over splitting `PolymorphicInt` into `PolymorphicInt` and `PolymorphicIntOrField` which turned out to be more work.

### CODE REVIEW

**Comment by jfecher** [comment]
Example of what these errors look like: 
```
error: Bitwise operations are invalid on Field types. Try casting the operands to a sized integer type first.
  ┌─ /.../src/main.nr:4:13
  │
4 │     let b = a << 4;
  │             ------

error: The number of bits to use for this bitwise operation is ambiguous. The type of at least one operand should be specified before this point
  ┌─ /.../src/main.nr:6:14
  │
6 │     let _c = 2 << 4;
  │              ------

error: aborting due to 2 previous errors
exit 1
```

File: crates/noirc_frontend/src/hir/type_check/expr.rs [hunk 1]
```diff
@@ -479,59 +485,84 @@ pub fn infix_operand_type_rules(
...
+                let other = other.follow_bindings();
+
+                // This will be an error if these types later resolve to a Field, or stay
+                // polymorphic as the bit size will be unknown. Delay this error until the function
+                // finishes resolving so we can still allow cases like `let x: u8 = 1 << 2;`.
+                interner.push_delayed_type_check(Box::new(move || {
+                    if other.is_field() {
+                        Err(make_error("Bitwise operations are invalid on Field types. Try casting the operands to a sized integer type first.".into()))
+                    } else if other.is_bindable() {
+                        Err(make_error("The number of bits to use for this bitwise operation is ambiguous. The type of at least one operand should be specified before this point".into()))
```
Comment (vezenovm) [inline crates/noirc_frontend/src/hir/type_check/expr.rs:529]: This is kind of a nit pick but technically couldn't we say "The type of at least one operand or the resulting value should be specified before this point". In your example if I changed `let _c = 2 << 4;` to `let _c: u8 = 2 << 4;` this would be valid. Technically the message is not incorrect because casting either operand will also make the statement valid, just was thinking we could make it more descriptive.

Comment (jfecher) [reply crates/noirc_frontend/src/hir/type_check/expr.rs:529]: Yes, good point. The message was originally made before I added the delayed system when it was not previously influenced by the return type, hence the wording. I added the delay system when I ran the tests and saw that our stdlib would need to be changed as it used `1 << 4` or similar quite a bit. Code with literals like that is also common, so I'll reword the error message.

**Review by vezenovm — APPROVED** [review]
I think PR is good. I left one question but it is non-blocking. When CI passes we can merge

**Review by vezenovm — APPROVED** [review]
This looks good to me now
