### PR TITLE
fix: perform SSA constraints check on final SSA

### LINKED ISSUE #7292: "Separate subgraph" bug misfires on indirect Brillig call with return value
### Aim

Attempted to compile a program that calls an unconstrained function and asserts that the result is zero:

```noir
unconstrained fn foo<T>(_x: T) -> Field {
    0
}

fn bar<T>(x: T) -> Field {
    /// Safety: test
    unsafe { foo(x) }
}

fn main() {
    let x: Field = 0;
    assert(bar(x) == 0);
}
```

### Expected Behavior

Expected the program to compile without errors or `bug`'s.

### Bug

`nargo compile` returns:

```bash
bug: Input to Brillig function is in a separate subgraph to output
  ┌─ src/main.nr:7:14
  │
7 │     unsafe { foo(x) }
  │              ------ There is no path from the output of this Brillig call to either return values or inputs of the circuit, which creates an independent subgraph. This is quite likely a soundness vulnerability
  │
  = Call stack:
    1. src/main.nr:12:12
    2. src/main.nr:7:14
```

However, the Brillig call is completely constrained:
- All arguments to `foo` are constrained (i.e. constant)
- `foo`'s result is constrained to be zero

### To Reproduce

1.
2.
3.
4.

### Workaround

Yes

### Workaround Description

Ignore `bug` warning

### Additional Context

_No response_

### Project Impact

Nice-to-have

### Blocker Context

_No response_

### Nargo Version

nargo version = 1.0.0-beta.1 noirc version = 1.0.0-beta.1+3a42eb5c68f9616f0ebe367c894f0376ba41e0ef (git version hash: 3a42eb5c68f9616f0ebe367c894f0376ba41e0ef, is dirty: false)

### NoirJS Version

_No response_

### Proving Backend Tooling & Version

_No response_

### Would you like to submit a PR for this Issue?

None

### Support Needs

_No response_

### PR DESCRIPTION
**Pull request by TomAFrench**
# Description

## Problem\*

Resolves #7292 

## Summary\*

We're currently performing the safety checks on the SSA before we do constant folding with brillig calls. This prevents bugs being shown for unconstrained calls which are optimized out. 

## Documentation\*

Check one:
- [x] No documentation needed.
- [ ] Documentation included in this PR.
- [ ] **[For Experimental Features]** Documentation to be submitted in a separate PR.

# PR Checklist\*

- [x] I have tested the changes locally.
- [x] I have formatted the changes with [Prettier](https://prettier.io/) and/or `cargo fmt` on default settings.

### CODE REVIEW

File: compiler/noirc_evaluator/src/ssa.rs [hunk 1]
```diff
@@ -130,7 +114,7 @@ pub(crate) fn optimize_into_acir(
     let ssa_gen_span = span!(Level::TRACE, "ssa_generation");
     let ssa_gen_span_guard = ssa_gen_span.enter();
 
-    let ssa = SsaBuilder {
+    let mut ssa = SsaBuilder {
```
Comment (aakoshh) [inline compiler/noirc_evaluator/src/ssa.rs:117]: Strange that using `&mut` somehow makes the `.par_bridge` used in the checks work, even though it shouldn't actually need mutation.

**Review by aakoshh — APPROVED** [review]
Just want to clarify the comments you left:

>  This prevents bugs being shown for unconstrained calls which are optimized out.

It sounds like you want to show bugs for calls which have been optimised away, which is what happened before this PR, so I assume you mean the opposite, perhaps "this PR prevents" or "This allows bugs...". 

I suppose there is no way to tell when exactly a function is removed, so running the checks on the final state is the right thing to do, which will only show bugs that are still present.

**Comment by TomAFrench** [comment]
Yeah, I mean "this PR" here

File: compiler/noirc_evaluator/src/ssa.rs (hunk 1 above)
Comment (TomAFrench) [reply compiler/noirc_evaluator/src/ssa.rs:117]: Yeah it's some interior mutability issue which having a mutable reference allows us to sidestep.
