### PR TITLE
fix: handle ambiguous trait methods in assumed traits

### LINKED ISSUE #10382: Ambiguous trait method is not detected on generic
### Aim

This code:

```noir
pub trait One {
    fn method() {
        println("one");
    }
}

pub trait Two {
    fn method() {
        println("two");
    }
}

pub struct Foo {}
impl One for Foo {}
impl Two for Foo {}

fn foo<T: One + Two>() {
    T::method();
}

fn main() {
    foo::<Foo>();
}
```

Should not compile as `T::method` inside `foo` is ambiguos. However, it compiles fine.

The output is "one". If we change it to `T: Two + One` then the output is "two".

The reason is that when we search the target method we go over all trait constraints. Once we find one with a matching type and method we return it, but we don't continue iterating to see if we can find another match to say the call is ambiguous:

https://github.com/noir-lang/noir/blob/dbd6f971dfa578069eb117ede56099f7af129623/compiler/noirc_frontend/src/elaborator/types.rs#L1945-L1960

The same happens when calling a method on a variable that has type `T`:

```noir
pub trait One {
    fn method(_self: Self) {
        println("one");
    }
}

pub trait Two {
    fn method(_self: Self) {
        println("two");
    }
}

pub struct Foo {}
impl One for Foo {}
impl Two for Foo {}

fn foo<T: One + Two>(x: T) {
    x.method();
}

fn main() {
    foo(Foo {});
}
```

### Expected Behavior

The compiler should give an error.

### Bug

The compiler doesn't give an error.

### To Reproduce

1.
2.
3.
4.

### Workaround

None

### Workaround Description

_No response_

### Additional Context

_No response_

### Project Impact

None

### Blocker Context

_No response_

### Nargo Version

_No response_

### NoirJS Version

_No response_

### Proving Backend Tooling & Version

_No response_

### Would you like to submit a PR for this Issue?

None

### Support Needs

_No response_

### LINKED ISSUE #10383: Ambiguous trait method on parent-child relationship
Related to #10382

This code:

```noir
trait Parent {
    fn foo();
}

trait Child: Parent {
    fn foo();
}

pub fn foo<T: Child>() {
    T::foo();
}

fn main() {}
```

compiles fine. However, the method is ambiguous because it's not clear if `Child::foo` os `Parent::foo` should be called.

In Rust this gives an error:

```
error[E0034]: multiple applicable items in scope
  --> foo/src/main.rs:10:8
   |
10 |     T::foo();
   |        ^^^ multiple `foo` found
   |
note: candidate #1 is defined in the trait `Child`
  --> foo/src/main.rs:6:5
   |
6  |     fn foo();
   |     ^^^^^^^^^
note: candidate #2 is defined in the trait `Parent`
  --> foo/src/main.rs:2:5
   |
2  |     fn foo();
   |     ^^^^^^^^^
help: use fully-qualified syntax to disambiguate
   |
10 -     T::foo();
10 +     <T as Child>::foo();
   |
10 -     T::foo();
10 +     <T as Parent>::foo();
```

Even though it's a bit contrived that a child method will use the same name as a parent method, the compiler should consider this case.

### PR DESCRIPTION
**Pull request by asterite**
# Description

## Problem

Resolves #10382
Resolves #10383

## Summary

I had to do some refactors to implement this.

## User Documentation

Check one:
- [x] No user documentation needed.
- [ ] Changes in _docs/_ included in this PR.
- [ ] **[For Experimental Features]** Changes in _docs/_ to be submitted in a separate PR.

# PR Checklist

- [x] I have tested the changes locally.
- [x] I have formatted the changes with [Prettier](https://prettier.io/) and/or `cargo fmt` on default settings.

### CODE REVIEW

File: compiler/noirc_frontend/src/elaborator/types.rs [hunk 1]
```diff
@@ -2081,18 +2194,27 @@ impl Elaborator<'_> {
         None
     }
 
-    fn lookup_method_in_trait(
+    /// Looks up a method in the given trait and its parent traits, recursively.
+    /// Mulitple matches are possible if a method with the same name exists in, for example,
```
Comment (asterite) [inline compiler/noirc_frontend/src/elaborator/types.rs]:
```suggestion
    /// Multiple matches are possible if a method with the same name exists in, for example,
```

**Review by TomAFrench — APPROVED** [review]
