### PR TITLE
fix: error on types that are too big

### LINKED ISSUE #11174: Unbounded memory allocation from exponential type instantiation
### Aim

Take this Noir program:
```noir
fn wrap<T>(x: T) -> (T, T) {
    (x, x)
}
fn main() {
    let v0 = 1;
    let v1 = wrap(v0);
    let v2 = wrap(v1);
    let v3 = wrap(v2);
    let v4 = wrap(v3);
}
```
Let's run it with `--show-monomorphized`:
```
fn main$f0() -> () {
    let v0$l0 = 1;
    let v1$l1 = wrap$f1(v0$l0);
    let v2$l2 = wrap$f2(v1$l1);
    let v3$l3 = wrap$f3(v2$l2);
    let v4$l4 = wrap$f4(v3$l3)
}
fn wrap$f1(x$l5: Field) -> (Field, Field) {
    (x$l5, x$l5)
}
fn wrap$f2(x$l6: (Field, Field)) -> ((Field, Field), (Field, Field)) {
    (x$l6, x$l6)
}
fn wrap$f3(x$l7: ((Field, Field), (Field, Field))) -> (((Field, Field), (Field, Field)), ((Field, Field), (Field, Field))) {
    (x$l7, x$l7)
}
fn wrap$f4(x$l8: (((Field, Field), (Field, Field)), ((Field, Field), (Field, Field)))) -> ((((Field, Field), (Field, Field)), ((Field, Field), (Field, Field))), (((Field, Field), (Field, Field)), ((Field, Field), (Field, Field)))) {
    (x$l8, x$l8)
}
```
As you can see at each level of nesting we double the type size. This can lead to OOM crashes. 

We can do a minimal reproduction in a unit test under a memory limit:
```rust
#[test]
fn exponential_generic_instantiation_oom() {
    // Each wrap level doubles the type size: wrap<T> -> (T, T)
    const DEPTH: usize = 20;

    let mut vars = String::from("let v0 = 1;\n");
    for i in 1..=DEPTH {
        vars.push_str(&format!("        let v{} = wrap(v{});\n", i, i - 1));
    }

    let src = format!(r#"
    fn wrap<T>(x: T) -> (T, T) {{ (x, x) }}
    fn main() {{
        {}
    }}
    "#, vars);

    let _ = get_monomorphized(&src);
}
```

### Expected Behavior

I would expect the compiler to fail gracefully and prevent attempting to compile such as program. 

I would expect some type of monomorphization/instantiation limit. This limit is slightly different than a type depth limit. We probably need a limit on the number of fields a type can have. For example 20 levels of `wrap` would only have a depth of 20 (which is pretty shallow). But 2^20 is 1,048,576 fields in the type. 

### Bug

The monomorphization pass currently has no limits on generic instantiation. This means an adversary can generate exponentially growing types. 

If we run the unit test above we crash with the following:
```
memory allocation of 192 bytes failed
[1]    128750 IOT instruction (core dumped)  bash -c 
```

### To Reproduce

On Ubuntu 24

1. Paste the unit test above into the monomorphization unit tests module
2. cargo test -p noirc_frontend --lib --no-run
3. Fetch the commit from the executable (Executable unittests src/lib.rs (target/debug/deps/noirc_frontend-8d6e7e33bab84c72))
4. Run `bash -c 'ulimit -v 4000000 && ./target/debug/deps/noirc_frontend-8d6e7e33bab84c72 exponential_generic_instantiation_oom'` with the relevant commit. This runs the test with a 4 GB limit.

### Workaround

Yes

### Workaround Description

Anyone service running the compiler on untrusted code should assume there is the potential of OOM crashes and should add their own handling. 

### Additional Context

_No response_

### Project Impact

Nice-to-have

### Blocker Context

_No response_

### Nargo Version

nargo version = 1.0.0-beta.17 noirc version = 1.0.0-beta.17+c2b99a8593d70abda260c91ca51a69ff8e10ca2d (git version hash: c2b99a8593d70abda260c91ca51a69ff8e10ca2d, is dirty: false)

### NoirJS Version

_No response_

### Proving Backend Tooling & Version

_No response_

### Would you like to submit a PR for this Issue?

None

### Support Needs

_No response_

### PR DESCRIPTION
**Pull request by guipublic**
# Description

## Problem

Resolves #11174 

## Summary
Avoid oom on big types, error instead.

## User Documentation

Check one:
- [X] No user documentation needed.
- [ ] Changes in _docs/_ included in this PR.
- [ ] **[For Experimental Features]** Changes in _docs/_ to be submitted in a separate PR.

# PR Checklist

- [X] I have tested the changes locally.
- [X] I have formatted the changes with [Prettier](https://prettier.io/) and/or `cargo fmt` on default settings.

### CODE REVIEW

File: compiler/noirc_frontend/src/monomorphization/tests.rs [hunk 1]
```diff
@@ -1353,3 +1353,88 @@ fn closure_capture_chain_oom() {
...
+    "#
+    );
+    assert!(get_monomorphized(&src).is_ok());
+}
+
+#[test]
+fn unbounded_monomorphization_queue() {
+    // Generate many unique monomorphic functions via different array sizes.
+    // Each [Field; N] is a distinct type, creating foo<[Field; N]>.
+    const NUM_MONOMORPHIC_FUNCTIONS: usize = 9000;
```
Comment (vezenovm) [inline compiler/noirc_frontend/src/monomorphization/tests.rs]: Just noting that the function queue is separate from the type complexity. I know you said you were not able to hit the OOM limit, but if you increase this size you eventually will hit a memory limit depending upon the system.

File: compiler/noirc_frontend/src/monomorphization/tests.rs [hunk 2]
```diff
@@ -1353,3 +1353,88 @@ fn closure_capture_chain_oom() {
     ";
     let _ = get_monomorphized(src);
 }
+
+#[test]
+fn deeply_nested_closures() {
+    const DEPTH: usize = 20;
```
Comment (vezenovm) [inline compiler/noirc_frontend/src/monomorphization/tests.rs]: Similarly to https://github.com/noir-lang/noir/pull/11398/changes#r2746758856, the memory growth here is the lambda stack vs. the number of type nodes.
