### PR TITLE
fix(ssa refactor): Fix array elements not being mapped to new values

### LINKED ISSUE #1688: Array elements orphaned in loop unrolling
### Aim

The test named `merkle_insert` should compile

### Expected Behavior

^

### Bug

It errors:
```
The application panicked (crashed).
Message:  internal error: entered unreachable code: ICE: Id(20) should have been in cache Param { block: Id(6), position: 0, typ: Numeric(NativeField) }
Location: crates/noirc_evaluator/src/ssa_refactor/acir_gen/mod.rs:345
```
It appears there's no definition of `v20` after loop unrolling - formally it was defined as a block parameter.

```
After Inlining:
...
  b6(v20: Field, v21: Field):
    v26 = call pedersen([v20, v21], u32 0)
```

```
After Unrolling:
...
  b607(v42348: Field, v42349: Field):
    v42350 = call pedersen([v20, v21], u32 0)
```

### To Reproduce

1.
2.
3.
4.

### Installation Method

None

### Nargo Version

_No response_

### Additional Context

_No response_

### Would you like to submit a PR for this Issue?

No

### Support Needs

_No response_

### PR DESCRIPTION
**Pull request by jfecher**
# Description

## Problem\*

Resolves #1688 but at what cost? I've spammed `.clone()`s everywhere due to the function for mapping ValueIds now requiring an `&mut self`. I'm not satisfied with this approach as a result. I've tried replacing each with the set_value_from_id approach but it caused bugs in loop unrolling presumably from setting the same valueids on each loop iteration.

## Documentation

- [ ] This PR requires documentation updates when merged.

  

  - [ ] I will submit a noir-lang/docs PR.

  

  - [ ] I will request for and support Dev Rel's help in documenting this PR.

  
  

## Additional Context

# PR Checklist\*

- [x] I have tested the changes locally.
- [x] I have formatted the changes with [Prettier](https://prettier.io/) and/or `cargo fmt` on default settings.

### CODE REVIEW

File: crates/noirc_evaluator/src/ssa_refactor/ir/function_inserter.rs [hunk 1]
```diff
@@ -0,0 +1,129 @@
...
+                super::value::Value::Array { array, element_type } => {
+                    let array = array.clone();
+                    let element_type = element_type.clone();
+                    let new_array = array.iter().map(|id| self.resolve(*id)).collect();
+                    let new_id = self.function.dfg.make_array(new_array, element_type);
+                    self.values.insert(value, new_id);
+                    new_id
+                }
+                _ => value,
+            },
```
Comment (jfecher) [inline crates/noirc_evaluator/src/ssa_refactor/ir/function_inserter.rs:43]: This is where the main fix of this PR. The rest is a mix of refactorings so that I can use a FunctionInserter instead of copying this fix everywhere, and added `.clone()` calls.

**Comment by jfecher** [comment]
Also fixes #1698

**Review by joss-aztec — APPROVED** [review]
I could only find 6 additional clones - your lamentation had me ready for worse!
