### PR TITLE
fix: hoist and then deduplicate

### LINKED ISSUE #10030: Strange edge case of array/loop handling in Brillig
### Aim

The following program:
```
fn main() {
    comptime {
        unsafe {
            foo();
        }
    }
}
unconstrained fn foo() -> [bool; 1] {
    let mut a: [bool; 1] = [true];
    let mut i: u32 = 0;
    while i < 1 {
        let mut j: u32 = 0;
        while j < 2 {
            a[0] = a[0] == a[0];
            println(("inner", a));
            a = [((a[0] as Field) != (a[0] as Field))];
            j = j + 1;
        }
        println(("outer", a));
        i = i + 1;
    }
    [false]
}
```

prints out 

```
(inner, [true])
(inner, [true])
(outer, [false])
```

However, removing `comptime` makes it print 

```
(inner, [true])
(inner, [true])
(outer, [true])
```

Seemingly further slight changes to the code - even those that should not affect anything, such as removing the inner `println`, or making `a` the return value - would "fix" it to correspond to the comptime output.

### Expected Behavior

The printed output should be 

```
(inner, [true])
(inner, [true])
(outer, [false])
```

### Bug

With `comptime`:
```
$ nargo execute --force
(inner, [true])                            
(inner, [true])                         
(outer, [false])                                                                                                                                                                              
[test1] Circuit witness successfully solved
[test1] Witness saved to target/test1.gz
```

Without `comptime`:
```
$ nargo execute --force
(inner, [true])                            
(inner, [true])                         
(outer, [true])                                                                                                                                                                              
[test1] Circuit witness successfully solved
[test1] Witness saved to target/test1.gz
```

### To Reproduce

1.
2.
3.
4.

### Workaround

None

### Workaround Description

_No response_

### Additional Context

_No response_

### Project Impact

None

### Blocker Context

_No response_

### Nargo Version

_No response_

### NoirJS Version

_No response_

### Proving Backend Tooling & Version

_No response_

### Would you like to submit a PR for this Issue?

None

### Support Needs

_No response_

### PR DESCRIPTION
**Pull request by guipublic**
# Description

## Problem\*

Resolves #10030
## Summary\*
Following the great investigations from @aakoshh in the issue's comments, one can see that this is a reference count issue.
When there is a make_array in block A, and another identical one in block B;
if block A dominates B, we can safely remove the second instruction. In that case, the reference count is increased, in case the redundant array was mutated afterwards.
However, when there is no dominator relation between A and B, the second instruction is removed and inserted in a common dominator, without increasing the reference count.
We then rely on a next constant folding to remove the instruction from A.

The fix consists of not removing the second instruction, but still inserting a copy of the instruction in the common dominator. The next constant folding will properly remove instructions in A and B and insert reference counts as needed.

## Documentation\*

Check one:
- [X] No documentation needed.
- [ ] Documentation included in this PR.
- [ ] **[For Experimental Features]** Documentation to be submitted in a separate PR.

# PR Checklist\*

- [X] I have tested the changes locally.
- [X] I have formatted the changes with [Prettier](https://prettier.io/) and/or `cargo fmt` on default settings.

### CODE REVIEW

File: compiler/noirc_evaluator/src/ssa/opt/constant_folding/mod.rs [hunk 1]
```diff
@@ -279,11 +279,16 @@ impl Context {
                     return;
                 }
                 CacheResult::NeedToHoistToCommonBlock(dominator) => {
-                    // Just change the block to insert in the common dominator instead.
-                    // This will only move the current instance of the instruction right now.
+                    // Insert a copy of the instruction in the common dominator.
                     // When constant folding is run a second time later on, it'll catch
-                    // that the previous instance can be deduplicated to this instance.
-                    block = dominator;
```
Comment (aakoshh) [inline compiler/noirc_evaluator/src/ssa/opt/constant_folding/mod.rs:331]: This will have some other effects as well with regards to caching, which I changed a bit in https://github.com/noir-lang/noir/pull/10019

Every instruction we insert is attempted to be cached. So far it went into the dominator, but the cache ignored all but the first insertion, so if e.g. `b1` dominated all of `b2`, `b3` and `b4`, and we found a duplicate of an instruction in all 3 blocks, then when we see the duplicate in `b3`, we insert it into `b1`, then do the same in `b4`, creating a 2nd copy in `b1`, etc. I changed that so that when we insert into the cache, if the new block dominates the previous, then it takes over, so when we see the instruction for the 3rd time in `b4`, it can readily reuse the one in `b1`, no copy needs to be made. 

This has the benefit that even with one less loop, we end up with a lower amount of duplication. Since that PR explicitly is about looping until there are no more hoists, or we run out of looping budget, trying to minimise copies can avoid that "we just needed one more loop, but had to stop" being worse than if we did nothing. 

So, while I agree that your solution is simpler and elegant, there is this downside to it.

**Comment by Savio-Sou** [comment]
Resolves NOIR-88.

File: compiler/noirc_evaluator/src/ssa/opt/constant_folding/mod.rs (hunk 1 above)
Comment (guipublic) [reply compiler/noirc_evaluator/src/ssa/opt/constant_folding/mod.rs:331]: If we do hoist and deduplicate at the same time, we still need another run of constant folding to take care of the second instruction. By that time, the two instructions are deduplicated with the one in the common dominator, in both cases: 'hoist then dedup', or 'hoist and dedup'. So I don't think there is much difference between the two approaches in term of performance.
However, hoisting do require proper handling of the instruction result (as highlighted by the CI failures), so in any cases I need to duplicate some code; either the ref-count mechanism (for hoist and dedup) or the instruction insertion (for hoist then dedup).
Since the ref-count mechanism is simpler, I am finally keeping the 'hoist and dedup'  behaviour.

**Review by aakoshh — APPROVED** [review]
🙌

**Comment by aakoshh** [comment]
I guess the regressions make sense, hopefully https://github.com/noir-lang/noir/pull/10019 can reclaim some of it. 
cc @vezenovm
