### PR TITLE
fix: avoid possible overflow during truncation

### LINKED ISSUE #10810: Truncation may cause a field overflow
### Aim

The function `convert_ssa_truncate` translates a truncation operation from Aztec's SSA representation to ACIR. This particular function performs some preprocessing and validation before creating the actual truncation operation. When doing so, if the sub-expression of the truncation is a subtraction of value smaller than the field size, a power of two is added (`2^max_bit_size`) to the variable before truncating. According to the comments, this is required to prevent an underflow as shown below.

```rust
fn convert_ssa_truncate(
    &mut self,
    value_id: ValueId,
    bit_size: u32,
    mut max_bit_size: u32,
    dfg: &DataFlowGraph,
) -> Result<AcirVar, RuntimeError> {
    ...
    let mut var = self.convert_numeric_value(value_id, dfg)?;
    match &dfg[value_id] {
        Value::Instruction { instruction, .. } => {
            if matches!(
                &dfg[*instruction],
                Instruction::Binary(Binary { operator: BinaryOp::Sub { .. }, .. })
            ) {
                // Subtractions must first have the integer modulus added before truncation can be
                // applied. This is done in order to prevent underflow.
                //
                // FieldElements have max bit size equals to max_num_bits so
                // we filter out this bit size because there is no underflow
                // for FieldElements. Furthermore, adding a power of two
                // would be incorrect for a FieldElement (cf. #8519).
                if max_bit_size < FieldElement::max_num_bits() {
                    let integer_modulus = power_of_two::<FieldElement>(max_bit_size);
                    let integer_modulus = self.acir_context.add_constant(integer_modulus);
                    var = self.acir_context.add_var(var, integer_modulus)?;
                    max_bit_size += 1;
                }
            }
        }

        ...
    };

    self.acir_context.truncate_var(var, bit_size, max_bit_size)
}
```

The condition does not prevent this adjustment when `max_bit_size == FieldElement::max_num_bits() - 1`. In this specific case, the addition of `2^max_bit_size` can exceed the field modulus for large values, causing an overflow.

### Expected Behavior

In the case where `max_bit_size == FieldElement::max_num_bits() - 1`, the value should not overflow

### Bug

The addition of `2^max_bit_size` can overflow the field modulus for large values. Since the result of the addition between the input value and `2^max_bit_size` is later provided to the truncation operation, the result of the truncation will likely be incorrect.

As an example, consider the case where `max_bit_size = FieldElement::max_num_bits() - 1` and the truncated value is `2^max_bit_size - 1`. In this specific case, the result of this addition would be `2^{FieldElement::max_num_bits()} - 1` which is likely to overflow the field.

Note that the `max_bit_size` is a property of the SSA truncation operation and we believe that it usually corresponds to Noir's integer type sizes. It therefore is unlikely that this corner case could be exploited.

### To Reproduce

1.
2.
3.
4.

### Workaround

None

### Workaround Description

_No response_

### Additional Context

https://app.audithub.dev/app/organizations/161/projects/462/project-viewer?version=1133&issueId=661

### Project Impact

None

### Blocker Context

_No response_

### Nargo Version

_No response_

### NoirJS Version

_No response_

### Proving Backend Tooling & Version

_No response_

### Would you like to submit a PR for this Issue?

None

### Support Needs

_No response_

### PR DESCRIPTION
**Pull request by guipublic**
# Description

## Problem

Resolves #10810 

## Summary
explicitly check for the edge case

## User Documentation

Check one:
- [X] No user documentation needed.
- [ ] Changes in _docs/_ included in this PR.
- [ ] **[For Experimental Features]** Changes in _docs/_ to be submitted in a separate PR.

# PR Checklist

- [X] I have tested the changes locally.
- [X] I have formatted the changes with [Prettier](https://prettier.io/) and/or `cargo fmt` on default settings.

### CODE REVIEW

File: compiler/noirc_evaluator/src/acir/mod.rs [hunk 1]
```diff
@@ -848,6 +848,13 @@ impl<'a> Context<'a> {
                     // for FieldElements. Furthermore, adding a power of two
                     // would be incorrect for a FieldElement (cf. #8519).
                     if max_bit_size < FieldElement::max_num_bits() {
+                        // When max_bit_size is max_num_bits() - 1, adding
+                        // 2**max_bit_size to an element of max_bit_size bits
+                        // gives an element of max_num_bits() bits which may overflow
+                        assert!(
+                            max_bit_size != FieldElement::max_num_bits() - 1,
+                            "potential underflow in subtraction when max_bit_size is {max_bit_size}"
+                        );
```
Comment (aakoshh) [inline compiler/noirc_evaluator/src/acir/mod.rs:857]: Can this happen under normal circumstances? Is there no way to handle it?

Comment (guipublic) [reply compiler/noirc_evaluator/src/acir/mod.rs:857]: I don't think it can happen
