### PR TITLE
fix: deserialize odd length hex literals

### LINKED ISSUE #3235: Single digit hex literals result in an InvalidIntegerLiteral error
### Aim

Writing `0x4` in a program

### Expected Behavior

The integer `4`

### Bug

```
error: InvalidIntegerLiteral : "0x4" is not a integer
   ┌─ /../short/src/main.nr:35:9
   │
35 │         0x4
   │         ---
   │
```

### To Reproduce

1.
2.
3.
4.

### Installation Method

None

### Nargo Version

_No response_

### Additional Context

_No response_

### Would you like to submit a PR for this Issue?

No

### Support Needs

_No response_

### PR DESCRIPTION
**Pull request by sambarnes**
# Description

single digit (or generally, odd length) hex literals such as `0x4` result in an `InvalidIntegerLiteral` error

## Problem\*

Resolves #3235

## Summary\*

i just prefixed all odd-length hex literals with another `0`, happy to change course if there's a better/more efficient way here (i'm kinda rust noob)

## Documentation\*

Check one:
- [x] No documentation needed.
- [ ] Documentation included in this PR.
- [ ] **[Exceptional Case]** Documentation to be submitted in a separate PR.

# PR Checklist\*

- [x] I have tested the changes locally.
- [x] I have formatted the changes with [Prettier](https://prettier.io/) and/or `cargo fmt` on default settings.

### CODE REVIEW

File: acvm-repo/acir_field/src/generic_ark.rs [hunk 1]
```diff
@@ -446,6 +449,25 @@ mod tests {
...
+                crate::generic_ark::FieldElement::<ark_bn254::Fr>::from(i as i128);
+            let odd_field_element =
+                crate::generic_ark::FieldElement::<ark_bn254::Fr>::from_hex(case.0).unwrap();
+            let even_field_element =
+                crate::generic_ark::FieldElement::<ark_bn254::Fr>::from_hex(case.1).unwrap();
+
+            assert_eq!(i_field_element, odd_field_element);
+            assert_eq!(odd_field_element, even_field_element);
+        }
+    }
```
Comment (sambarnes) [inline acvm-repo/acir_field/src/generic_ark.rs:469]: is there another place i should be testing the high level issue? to ensure that it works all the way up in top level `.nr` code

or is this sufficient?

Comment (kevaundray) [reply acvm-repo/acir_field/src/generic_ark.rs:469]: I think an example program in https://github.com/noir-lang/noir/tree/master/test_programs/execution_success would be good incase we switch from arkworks to another dependency for our field implementation

Comment (sambarnes) [reply acvm-repo/acir_field/src/generic_ark.rs:469]: aye aye 🫡 added in 1155e9f

just stuck it in the only existing test_program i saw with hex literals -- happy to break it out into its own if ya think the separation is warranted

Comment (kevaundray) [reply acvm-repo/acir_field/src/generic_ark.rs:469]: Looks great!

File: acvm-repo/acir_field/src/generic_ark.rs [hunk 2]
```diff
@@ -272,7 +272,10 @@ impl<F: PrimeField> FieldElement<F> {
     }
     pub fn from_hex(hex_str: &str) -> Option<FieldElement<F>> {
         let value = hex_str.strip_prefix("0x").unwrap_or(hex_str);
-        let hex_as_bytes = hex::decode(value).ok()?;
+        // Values of odd length require an additional "0" prefix
+        let sanitized_value =
+            if value.len() % 2 == 0 { value.to_string() } else { format!("0{}", value) };
+        let hex_as_bytes = hex::decode(sanitized_value).ok()?;
         Some(FieldElement::from_be_bytes_reduce(&hex_as_bytes))
```
Comment (kevaundray) [inline acvm-repo/acir_field/src/generic_ark.rs:279]: For reference; we are adding a zero to beginning of the string because we are interpretting it in big endian fomat, see `from_be_bytes_reduce`

**Review by kevaundray — APPROVED** [review]
