### PR TITLE
fix(lsp): Ensure lsp does not crawl past the root specified

### LINKED ISSUE #2261: Searching for Nargo.toml should not crawl past root
### Problem

Currently, the function that searches for `Nargo.toml` will look in every directory up to the root of you filesystem. However, this search should stop at some given root directory (usually the pwd of the nargo process, but maybe a `--program-dir` passed or the workspace root in the LSP)

### Happy Case

The search should stop at some root.

### Alternatives Considered

_No response_

### Additional Context

_No response_

### Would you like to submit a PR for this Issue?

Maybe

### Support Needs

_No response_

### PR DESCRIPTION
**Pull request by phated**
# Description

## Problem\*

Resolves #2261 

## Summary\*

This reworks the crawling for Nargo.toml files. When searching for the `program_dir`, we still search to the root using `find_package_root`; however, `find_package_manifest` requires a root where we stop the crawling. Additionally, we now read the `<program_dir>/Nargo.toml` exactly instead of traversing.

These changes allowed me to fix a problem with the LSP where it would crawl past the `root_uri` and find a Nargo.toml outside of the directory you have opened.

## Documentation

- [ ] This PR requires documentation updates when merged.

  

  - [ ] I will submit a noir-lang/docs PR.

  

  - [ ] I will request for and support Dev Rel's help in documenting this PR.

  
  

## Additional Context

# PR Checklist\*

- [x] I have tested the changes locally.
- [x] I have formatted the changes with [Prettier](https://prettier.io/) and/or `cargo fmt` on default settings.

### CODE REVIEW

File: crates/lsp/src/lib.rs [hunk 1]
```diff
@@ -144,7 +148,17 @@ fn on_code_lens_request(
...
     };
 
-    let toml_path = match find_package_manifest(&file_path) {
+    let root_path = match &state.root_path {
+        Some(root) => root,
+        None => {
+            return future::ready(Err(ResponseError::new(
+                ErrorCode::REQUEST_FAILED,
+                "Could not find project root",
+            )))
```
Comment (kobyhallx) [inline crates/lsp/src/lib.rs:157]: Wondering about browser case here...?

File: crates/nargo_toml/src/lib.rs [hunk 2]
```diff
@@ -18,48 +17,84 @@ mod git;
...
-///
-/// Returns a `CliError` if no parent directories of `current_path` contain a manifest file.
-pub fn find_package_manifest(current_path: &Path) -> Result<PathBuf, ManifestError> {
-    current_path
-        .ancestors()
-        .find_map(|dir| find_file(dir, "Nargo", "toml"))
-        .ok_or_else(|| ManifestError::MissingFile(current_path.to_path_buf()))
-}
+// TODO: We are probably going to need a "filepath utils" crate soon
+fn path_root(path: &Path) -> PathBuf {
```
Comment (TomAFrench) [inline crates/nargo_toml/src/lib.rs:34]:
```rust
fn path_root(path: &Path) -> PathBuf {
    let mut components = path.components();

    match (components.next(), components.next()) {
        // Preserve prefix if one exists
        (Some(prefix @ Component::Prefix(_)), Some(root_component @ Component::RootDir)) => {
            PathBuf::from(prefix.as_os_str()).join(root_component.as_os_str())
        }
        (Some(root_component @ Component::RootDir), _) => PathBuf::from(root_component.as_os_str()),

        _ => PathBuf::new(),
    }
}
```

This is equivalent, no? I think the current implementation is a bit odd with how it iterates over all components when it knows that it's going to take 2 at most.

Comment (phated) [reply crates/nargo_toml/src/lib.rs:34]: I believe that's wrong because workspace members can be specified at any depth:
```toml
[workspace]
members = ["crates/foo/bar/baz", "some/other/path"]
```
And we want to traverse to the workspace file.

File: crates/lsp/src/lib.rs [hunk 3]
```diff
@@ -269,7 +283,18 @@ fn on_did_save_text_document(
...
+    let root_path = match &state.root_path {
+        Some(root) => root,
+        None => {
+            return ControlFlow::Break(Err(ResponseError::new(
+                ErrorCode::REQUEST_FAILED,
+                "Could not find project root",
+            )
+            .into()));
+        }
+    };
```
[the remark this answers is not in the document]
Comment (phated) [reply crates/lsp/src/lib.rs:295]: Coming from ocaml, it's easier for me to think about these as matches 😛

[the remark this answers is not in the document]
Comment (TomAFrench) [reply crates/lsp/src/lib.rs:295]: No worries :laughing: I think this is a bit of a marmite syntax tbf.

File: crates/nargo_toml/src/lib.rs [hunk 4]
```diff
@@ -18,48 +17,71 @@ mod git;
...
+    }
 }
 
-// There is no distinction between files and folders
-fn find_artifact(entries: ReadDir, artifact_name: &str) -> Option<PathBuf> {
-    let entry = entries
-        .into_iter()
-        .flatten()
-        .find(|entry| entry.file_name().to_str() == Some(artifact_name))?;
+/// Returns the [Path] of the `Nargo.toml` file by searching from `current_path` and stopping at `root_path`.
```
Comment (TomAFrench) [inline crates/nargo_toml/src/lib.rs:47]:
```suggestion
/// Returns the [PathBuf] of the `Nargo.toml` file by searching from `current_path` and stopping at `root_path`.
```

File: crates/nargo_toml/src/lib.rs [hunk 5]
```diff
@@ -18,48 +17,71 @@ mod git;
...
+        Err(ManifestError::NoCommonAncestor {
+            root: root_path.to_path_buf(),
+            current: current_path.to_path_buf(),
+        })
+    }
 }
-
-fn list_files_and_folders_in<P: AsRef<Path>>(path: P) -> Option<ReadDir> {
-    std::fs::read_dir(path).ok()
+/// Returns the [Path] of the `Nargo.toml` file in the `current_path` directory.
```
Comment (TomAFrench) [inline crates/nargo_toml/src/lib.rs:75]:
```suggestion
/// Returns the [PathBuf] of the `Nargo.toml` file in the `current_path` directory.
```

**Review by TomAFrench — COMMENTED** [review]
Looks good. I just want to check that we're not creating an additional need for us to make paths absolute in order to find the package manifest that we haven't accounted for elsewhere.

**Review by TomAFrench — CHANGES_REQUESTED** [review]
This currently panics if you do `nargo --program-dir ./foo compile` but if you do `nargo --program-dir /absolute/path/to/foo compile` then we succeed.

We should normalize the paths we're passing into these functions to avoid this

**Comment by TomAFrench** [comment]
Oof, looks like this is on master actually.

**Comment by phated** [comment]
> Oof, looks like this is on master actually.

Yeah, I didn't change the way that program-dir was searched. I don't think it ever supported relative paths

**Comment by TomAFrench** [comment]
I've addresses this panic in https://github.com/noir-lang/noir/pull/2324

File: crates/nargo_toml/src/lib.rs [hunk 6]
```diff
@@ -18,48 +17,71 @@ mod git;
...
-        .flatten()
-        .find(|entry| entry.file_name().to_str() == Some(artifact_name))?;
+/// Returns the [Path] of the `Nargo.toml` file by searching from `current_path` and stopping at `root_path`.
+///
+/// Returns a [ManifestError] if no parent directories of `current_path` contain a manifest file.
+pub fn find_package_manifest(
+    root_path: &Path,
+    current_path: &Path,
+) -> Result<PathBuf, ManifestError> {
+    if current_path.starts_with(root_path) {
```
[the remark this answers is not in the document]
Comment (phated) [reply crates/nargo_toml/src/lib.rs:54]: Yeah, this assumes paths are absolute
