### PR TITLE
fix: lsp find struct reference in return locations and paths

### LINKED ISSUE #5394: LSP "rename struct" misses a few location
### Aim

LSP "rename struct" should refactor all occurrences of a struct. Right now that's not the case.

### Expected Behavior

Given this program:

```rust
struct Foo {
  field: Field,
}

impl Foo {
  fn foo() {}
}

fn main() {
  Foo::foo(); // <-- this "Foo" isn't renamed
}

fn foo() -> Foo { // <-- this "Foo" isn't renamed
}
```

when I right-click in "Foo", choose "Rename symbol" and choose another name. All "Foo" are renamed.

### Bug

The "Foo"s marked at the given locations aren't renamed when trying to rename "Foo". So, essentially:
- "Foo" showing up in the middle of a "path"
- "Foo" in a return type

### To Reproduce

_No response_

### Project Impact

Blocker

### Impact Context

_No response_

### Workaround

None

### Workaround Description

_No response_

### Additional Context

_No response_

### Installation Method

None

### Nargo Version

_No response_

### NoirJS Version

_No response_

### Would you like to submit a PR for this Issue?

Yes

### Support Needs

_No response_

### PR DESCRIPTION
**Pull request by asterite**
# Description

## Problem

Resolves #5394

## Summary

Finds struct locations in return types and inside paths.

## Additional Context

Making it work for the return type was simple: the code to register it is now done a bit earlier so it works in all cases where a type is referred as the last segment in a Path.

Making it work when the type is in the middle of a Path (like in `foo::Foo::new`) was a bit trickier: the existing Path lookup only cared about (and registered) the result of the last segment. So now there's code to register each segment in turn... but this is only done if running in LSP mode. So in `foo::Foo::new`, `foo` is linked to a module and `Foo` is linked to a struct. The existing code relied on the `DependencyId` for this, but a "module" dependency didn't exist... to avoid introducing new variants that are only used in this reference tracking I instead created a new enum, `ReferenceId`.

## Documentation

Check one:
- [x] No documentation needed.
- [ ] Documentation included in this PR.
- [ ] **[For Experimental Features]** Documentation to be submitted in a separate PR.

# PR Checklist

- [x] I have tested the changes locally.
- [x] I have formatted the changes with [Prettier](https://prettier.io/) and/or `cargo fmt` on default settings.

### CODE REVIEW

File: compiler/noirc_frontend/src/hir/resolution/path_resolver.rs [hunk 1]
```diff
@@ -1,16 +1,20 @@
...
 
 pub trait PathResolver {
     /// Resolve the given path returning the resolved ModuleDefId.
+    /// If `dependencies` is `Some`, a `DependencyId` for each segment in `path`
+    /// will be pushed.
     fn resolve(
         &self,
         def_maps: &BTreeMap<CrateId, CrateDefMap>,
         path: Path,
+        dependencies: &mut Option<&mut Vec<DependencyId>>,
```
Comment (asterite) [inline compiler/noirc_frontend/src/hir/resolution/path_resolver.rs:17]: Is there a more idiomatic way to do this? This is mainly to avoid allocating a `Vec` unless really needed.

File: compiler/noirc_frontend/src/node_interner.rs [hunk 2]
```diff
@@ -228,7 +228,9 @@ pub struct NodeInterner {
 /// ```
 #[derive(Debug, Copy, Clone, PartialEq, Eq, Hash)]
 pub enum DependencyId {
+    Module(ModuleId),
```
Comment (asterite) [inline compiler/noirc_frontend/src/node_interner.rs:231]: It seems `DependencyId` already existed in the compiler before introducing LSP, and for LSP it's used to track references... for example a `Variable` might reference a `Struct`, etc.

In this PR I added two new dependencies: `Module` and `Trait`. This is because in this path:

```rust
foo::bar::Baz::new
```

we can track that `foo` points to a `Module`, same for `Bar`, then `Baz` points to a struct (or a trait), etc. With this, clicking `foo` would take you to the `foo` module (this isn't implemented yet, though! But I needed this so that clicking `Baz` in the middle of the path works)

I'm wondering if a different type to track references might be better... something like `pub enum ReferenceId` that would be the same as `DependencyId` except that it also has `Module` and `Trait`... mainly to avoid ignoring `Module` and `Trait` in pattern matches around `dependency_graph`... what do you think?

File: compiler/noirc_frontend/src/hir/resolution/path_resolver.rs [hunk 3]
```diff
@@ -1,16 +1,20 @@
...
 
 pub trait PathResolver {
     /// Resolve the given path returning the resolved ModuleDefId.
+    /// If `path_references` is `Some`, a `ReferenceId` for each segment in `path`
+    /// will be resolved and pushed.
     fn resolve(
         &self,
         def_maps: &BTreeMap<CrateId, CrateDefMap>,
         path: Path,
+        path_references: &mut Option<&mut Vec<ReferenceId>>,
```
Comment (asterite) [inline compiler/noirc_frontend/src/hir/resolution/path_resolver.rs:17]: Is there a more idiomatic way to do this? I want to avoid allocating a `Vec` when not in LSP mode.

Alternatively, I tried changing this to be a callback (`dyn FnMut`) but then it told me that the trait cannot be used as an object... I'm a bit lost as I'm just beginning with Rust. Any help is appreciated! 🙏

Comment (asterite) [reply compiler/noirc_frontend/src/hir/resolution/path_resolver.rs:17]: Searching the internet, it seems it's common to use `Option<&mut ...>` or `&mut Option<&mut ...>` for this, so maybe it's fine 🤷

**Comment by asterite** [comment]
Actually, given that this wasn't already working well, and this makes it closer to working well, we could merge this PR then I can work on the other things in a separate PR... mainly because I have two other PRs on top of this branch (to avoid merge conflicts) :-)

File: compiler/noirc_frontend/src/hir/resolution/path_resolver.rs (hunk 3 above)
Comment (TomAFrench) [reply compiler/noirc_frontend/src/hir/resolution/path_resolver.rs:17]: Took a look at this and it seems like there's not a clean way around this. We can revisit in future when looking at the `PathResolver trait more generally.

**Review by TomAFrench — APPROVED** [review]
