### PR TITLE
fix: disallow no-predicates on entry points

### LINKED ISSUE #10774: ICE for a main function with the `#[no_predicates]` attribute
## Description

The following code is problematic
```noir
#[no_predicates]
fn main() {}
```
Compilation results in
```sh
The application panicked (crashed).
Message:  All ACIR functions marked with #[no_predicates] should be inlined before ACIR gen. This is an SSA exclusive codegen attribute
Location: compiler/noirc_evaluator/src/acir/mod.rs:153
```

## Noir Version

https://github.com/noir-lang/noir/commit/334ac7d7a2b1ad637c96400b04b23d41e10a172f

### PR DESCRIPTION
**Pull request by guipublic**
# Description

## Problem

Resolves #10774 

## Summary
Error if no-predicates attribute is used on entry point function.
The attribute is only relevant for a function called by an entry point, but not for the entry point itself.

## User Documentation

Check one:
- [X] No user documentation needed.
- [ ] Changes in _docs/_ included in this PR.
- [ ] **[For Experimental Features]** Changes in _docs/_ to be submitted in a separate PR.

# PR Checklist

- [X] I have tested the changes locally.
- [X] I have formatted the changes with [Prettier](https://prettier.io/) and/or `cargo fmt` on default settings.

### CODE REVIEW

File: compiler/noirc_frontend/src/elaborator/lints.rs [hunk 1]
```diff
@@ -73,6 +73,26 @@ pub(super) fn inlining_attributes(
...
 
+/// The `#[no_predicates]` attribute is not allowed on entry point functions
+/// since it's meant to control inlining into the entry point.
+pub(super) fn no_predicates_on_entry_point(
+    func: &FuncMeta,
+    modifiers: &FunctionModifiers,
+) -> Option<ResolverError> {
+    if func.is_entry_point {
+        let attribute = modifiers.attributes.function()?;
+        if attribute.kind.is_no_predicates() {
```
Comment (vezenovm) [inline compiler/noirc_frontend/src/elaborator/lints.rs]: nit:we could collapse this if statement into a single conditional

File: compiler/noirc_frontend/src/elaborator/lints.rs [hunk 2]
```diff
@@ -73,6 +73,26 @@ pub(super) fn inlining_attributes(
...
+            let ident = func_meta_name_ident(func, modifiers);
+            return Some(ResolverError::NoPredicatesAttributeOnEntryPoint {
+                ident,
+                location: attribute.location,
+            });
+        }
+    }
+
+    None
```
Comment (jfecher) [inline compiler/noirc_frontend/src/elaborator/lints.rs]:
```suggestion
    let attribute = modifiers.attributes.function()?;
    (func.is_entry_point && attribute.kind.is_no_predicates()).then(|| {
        let ident = func_meta_name_ident(func, modifiers);
        ResolverError::NoPredicatesAttributeOnEntryPoint {
            ident,
            location: attribute.location,
        }
    })
```

Comment (jfecher) [reply compiler/noirc_frontend/src/elaborator/lints.rs]: Just resolving the "nit:we could collapse this if statement into a single conditional" comment

File: compiler/noirc_frontend/src/elaborator/lints.rs [hunk 3]
```diff
@@ -73,6 +73,22 @@ pub(super) fn inlining_attributes(
...
+/// since it's meant to control inlining into the entry point.
+pub(super) fn no_predicates_on_entry_point(
+    func: &FuncMeta,
+    modifiers: &FunctionModifiers,
+) -> Option<ResolverError> {
+    let attribute = modifiers.attributes.function()?;
+    (func.is_entry_point && attribute.kind.is_no_predicates()).then(|| {
+        let ident = func_meta_name_ident(func, modifiers);
+        ResolverError::NoPredicatesAttributeOnEntryPoint {
+            ident,
```
Comment (jfecher) [inline compiler/noirc_frontend/src/elaborator/lints.rs]:
```suggestion
        ResolverError::NoPredicatesAttributeOnEntryPoint {
            ident: func_meta_name_ident(func, modifiers),
```
More condensing
