### PR TITLE
fix: non-comptime globals can refer to comptime types

### LINKED ISSUE #10365: Non-comptime globals can refer to comptime types
### Aim

This code:

```noir
global foo: Quoted = quote { 1};

fn main() {
    let _ = foo;
}
```

produces this error:

```
The application panicked (crashed).
Message:  internal error: entered unreachable code: unquote expression remaining in runtime code
Location: compiler/noirc_frontend/src/monomorphization/mod.rs:655
```

### Expected Behavior

The compiler should give an error saying that comptime types are not allowed in non-comptime globals.

### Bug

The compiler crashes insted.

### To Reproduce

1.
2.
3.
4.

### Workaround

None

### Workaround Description

_No response_

### Additional Context

_No response_

### Project Impact

None

### Blocker Context

_No response_

### Nargo Version

_No response_

### NoirJS Version

_No response_

### Proving Backend Tooling & Version

_No response_

### Would you like to submit a PR for this Issue?

None

### Support Needs

_No response_

### PR DESCRIPTION
**Pull request by asterite**
# Description

## Problem

Resolves #10365

## Summary

There are two commits here, each solves one problem. See the code comments for an explanation of what's done here.

## User Documentation

Check one:
- [x] No user documentation needed.
- [ ] Changes in _docs/_ included in this PR.
- [ ] **[For Experimental Features]** Changes in _docs/_ to be submitted in a separate PR.

# PR Checklist

- [x] I have tested the changes locally.
- [x] I have formatted the changes with [Prettier](https://prettier.io/) and/or `cargo fmt` on default settings.

### CODE REVIEW

File: compiler/noirc_frontend/src/elaborator/types.rs [hunk 1]
```diff
@@ -395,7 +395,8 @@ impl Elaborator<'_> {
                 );
                 if let Type::Quoted(quoted) = typ {
                     let in_function = matches!(self.current_item, Some(DependencyId::Function(_)));
-                    if in_function && !self.in_comptime_context() {
+                    let in_global = matches!(self.current_item, Some(DependencyId::Global(_)));
+                    if (in_function || in_global) && !self.in_comptime_context() {
```
Comment (jfecher) [inline compiler/noirc_frontend/src/elaborator/types.rs]: So we don't issue an error if we're not within a function or global. I suppose this means we can sneak in comptime types past the frontend if we declare a struct that holds them and uses that but we should at least still error during monomorphization.
