### PR TITLE
fix: Add more thorough check for whether a type is valid when passing it from constrained code to unconstrained code

### LINKED ISSUE #5008: ICE: unreacheable code
### Aim

This is a follow up to https://github.com/noir-lang/noir/issues/4497. I did some more trimming and arrived at a minimal example that results in a compiler crash.

### Bug

The following program crashes:

```rust
struct Bar {
    value: Field,
}

struct Foo{
    bar: &mut Bar,
}

impl Foo {
    unconstrained fn crash_fn(self) {}
}

fn main() {
    let foo = Foo { bar: &mut Bar { value: 0 } };

    foo.crash_fn();
}
```

The error message is

```
The application panicked (crashed).
Message:  internal error: entered unreachable code: Expected all allocate instructions to be removed before acir_gen
Location: compiler/noirc_evaluator/src/ssa/acir_gen/mod.rs:689
```

I couldn't distill this down any further. The crash is avoided with any of these changes:
 - if `main` is `unconstrained`
 - if `crash_fn` is not `unconstrained`
 - if `bar` takes a `&` and not a `&mut`
 - if `Bar` has no members
 - if `crash_fn` doesn't take `self`

So it seems like the bug is related to some odd combination of all of the above.

### To Reproduce

Compile the program above.

### Project Impact

Blocker

### Impact Context

This blocks some currently open PRs, such as https://github.com/AztecProtocol/aztec-packages/pull/4940.

### Workaround

None

### Workaround Description

_No response_

### Additional Context

_No response_

### Installation Method

Compiled from source

### Nargo Version

nargo version = 0.28.0 noirc version = 0.28.0+98eb519766ae219d2f10550944bba83f30f7662c (git version hash: 98eb519766ae219d2f10550944bba83f30f7662c, is dirty: false)

### PR DESCRIPTION
**Pull request by jfecher**
# Description

## Problem\*

Resolves #5008 

## Summary\*

Thank you to @nventuro for the minimal example and @TomAFrench for looking into this. As a result it was a quick fix.

## Additional Context

All type system fixes must currently be duplicated in the elaborator so I've included this there as well.

## Documentation\*

Check one:
- [x] No documentation needed.
- [ ] Documentation included in this PR.
- [ ] **[For Experimental Features]** Documentation to be submitted in a separate PR.

# PR Checklist\*

- [x] I have tested the changes locally.
- [x] I have formatted the changes with [Prettier](https://prettier.io/) and/or `cargo fmt` on default settings.

### CODE REVIEW

File: compiler/noirc_frontend/src/hir_def/types.rs [hunk 1]
```diff
@@ -779,6 +779,45 @@ impl Type {
...
+            | Type::NamedGeneric(_, _)
+            | Type::Function(_, _, _)
+            | Type::FmtString(_, _)
+            | Type::Error => true,
+
+            Type::Slice(_)
+            | Type::MutableReference(_)
+            | Type::Forall(_, _)
+            | Type::Code
+            | Type::TraitAsType(..) => false,
```
Comment (jfecher) [inline compiler/noirc_frontend/src/hir_def/types.rs:801]: Compared to the other "is_valid_for" functions, this is more permissive since it allows FmtStrings and Functions.

**Review by TomAFrench — APPROVED** [review]
LGTM!

**Comment by jfecher** [comment]
I'm not familiar enough with the debugger to know why it seems to be passing mutable references from constrained -> unconstrained or if it needs to do so or not. So I'm putting this PR on hold for now.

File: compiler/noirc_frontend/src/hir/type_check/expr.rs [hunk 2]
```diff
@@ -340,7 +340,7 @@ impl<'interner> TypeChecker<'interner> {
         // Check that we are not passing a mutable reference from a constrained runtime to an unconstrained runtime
         if is_current_func_constrained && is_unconstrained_call {
             for (typ, _, _) in args.iter() {
-                if matches!(&typ.follow_bindings(), Type::MutableReference(_)) {
+                if typ.is_valid_for_unconstrained_boundary() {
```
Comment (TomAFrench) [inline compiler/noirc_frontend/src/hir/type_check/expr.rs:343]:
```suggestion
                if !typ.is_valid_for_unconstrained_boundary() {
```

**Comment by nventuro** [comment]
As of 0.30, code like the above errors out with

```
 error: Could not resolve some references to the array. All references must be resolved at compile time
```

**Comment by TomAFrench** [comment]
@jfecher Looks like the issue with the debugger isn't so much mutable references but that this PR has disallowed slices being arguments to unconstrained functions whereas previously they were only disallowed from being returned from unconstrained functions.
