### PR TITLE
fix: preserve generic kind on trait methods

### LINKED ISSUE #6100: Numeric generics on trait methods results in failure to unify types
The nightly canary on some of the external libraries have been tripped:

https://github.com/noir-lang/noir_string_search/actions/runs/10937870108/job/30364704587
https://github.com/noir-lang/noir-edwards/actions/runs/10937805460/job/30364499322

```
┌─ src/lib.nr:3:43
  │
3 │ pub use utils::{conditional_select, lt_f, DebugRandomEngine};
  │                                           ----------------- DebugRandomEngine is private
  │

warning: cannot re-export DebugRandomEngine because it has less visibility than this use statement
  ┌─ src/lib.nr:3:43
  │
3 │ pub use utils::{conditional_select, lt_f, DebugRandomEngine};
  │                                           ----------------- consider marking DebugRandomEngine as pub
  │

error: Parameter #2 of method `match_chunks` must be of type [Field; HaystackChunks], not [Field; HaystackChunks]
    ┌─ src/lib.nr:170:[9](https://github.com/noir-lang/noir_string_search/actions/runs/10937870108/job/30364704587#step:4:10)
    │
170 │         haystack: [Field; HaystackChunks],
    │         --------
    │
```

### PR DESCRIPTION
**Pull request by TomAFrench**
# Description

## Problem\*

Resolves #6100 

## Summary\*

It seems that #5156 has resulted in problems in unifying numeric generics in trait impl methods.

## Documentation\*

Check one:
- [x] No documentation needed.
- [ ] Documentation included in this PR.
- [ ] **[For Experimental Features]** Documentation to be submitted in a separate PR.

# PR Checklist\*

- [x] I have tested the changes locally.
- [x] I have formatted the changes with [Prettier](https://prettier.io/) and/or `cargo fmt` on default settings.

### CODE REVIEW

**Comment by TomAFrench** [comment]
cc @michaeljklein

File: compiler/noirc_frontend/src/elaborator/traits.rs [hunk 1]
```diff
@@ -288,10 +288,10 @@ pub(crate) fn check_trait_impl_method_matches_declaration(
         // Substitute each generic on the trait function with the corresponding generic on the impl function
         for (
             ResolvedGeneric { type_var: trait_fn_generic, .. },
-            ResolvedGeneric { name, type_var: impl_fn_generic, .. },
+            ResolvedGeneric { name, type_var: impl_fn_generic, kind, .. },
         ) in trait_fn_meta.direct_generics.iter().zip(&meta.direct_generics)
         {
-            let arg = Type::NamedGeneric(impl_fn_generic.clone(), name.clone(), Kind::Normal);
+            let arg = Type::NamedGeneric(impl_fn_generic.clone(), name.clone(), kind.clone());
             bindings.insert(trait_fn_generic.id(), (trait_fn_generic.clone(), arg));
```
Comment (TomAFrench) [inline compiler/noirc_frontend/src/elaborator/traits.rs:295]: This change just updates this snippet to match the equivalent for `where` clauses.

**Review by michaeljklein — APPROVED** [review]
