### PR TITLE
fix: correct way to track type recursion

### LINKED ISSUE #11507: Compiler crash: Oracle returns multiple vector regression
### Aim

I was looking to adopt the `SeenDataTypes` pattern for the `Type::visit` method added in https://github.com/noir-lang/noir/pull/11417 when I noticed that it's not use quite correctly in `vector_count`. 

The following code crashes the compiler:
```noir
struct Foo {
    xs: [u32],
}
struct Bar {
    a: Foo,
    b: Foo,
}

#[oracle(bar)]
unconstrained fn bar() -> Bar {}

unconstrained fn main() {
    let _bar = bar();
}
```

### Expected Behavior

The code should be rejected due to returning multiple vector, the same was as it is for example for this code:
```rust
struct Bar {
    a: [u32],
    b: [u32],
}
```

gives:
```
error: Oracle functions cannot return multiple vectors
   ┌─ src/main.nr:10:18
   │
10 │ unconstrained fn bar() -> Bar {}
```

### Bug

```console
❯ cargo run -p nargo_cli -- compile --show-monomorphized --force --show-ssa-pass Initial
    Finished `dev` profile [optimized + debuginfo] target(s) in 0.24s
     Running `/Users/aakoshh/Work/aztec/noir/target/debug/nargo compile --show-monomorphized --force --show-ssa-pass Initial`
unconstrained fn main$f0() -> () {
    let _bar$l0 = bar$bar()
}

After Initial SSA:
brillig(inline) fn main f0 {
  b0():
    v1, v2, v3, v4 = call bar() -> (u32, [u32], u32, [u32])
    return
}

The application panicked (crashed).
Message:  a previous vector has already been allocated at the free memory pointer
Location: compiler/noirc_evaluator/src/brillig/brillig_gen/brillig_call/mod.rs:87
```

### To Reproduce

See above. The trick is to return multiple vectors wrapped in the same `struct` name. `vector_count` will only consider it once, and count them as 0 the second time around. 

### Workaround

None

### Workaround Description

I recommended in https://github.com/noir-lang/noir/pull/11448#discussion_r2783250783 that we switch to an immutable context, so that we can consider types as seen multiple times if they are siblings:
```rust
#[derive(Clone)]
struct TypeRecursionContext {
  depth: u32, 
  seen_data_types: im::HashSet<(TypeId, Vec<Type>)>
}

impl TypeRecursionContext {
  fn recur(mut self) -> Self {
    if self.depth >= TYPE_RECURSION_LIMIT {
        panic!("Types are too deep!");
    }
    self.depth += 1;
    self
  }
  fn insert_data_type(&mut self, date_type_id: TypeId, generics: Vec<Type>) -> bool {
    self.seen_data_type.insert((data_type_id, generics))
  }
}
```
and use it like this:
```rust
fn vector_count(typ: &Type, ctx: mut TypeRecursionContext) -> usize {
...
            Type::DataType(def, args) => {
                let struct_type = def.borrow();
                if ctx.insert_data_type(struct_type.id, args.clone()) {
                    if let Some(fields) = struct_type.get_fields(args) {
                        fields.iter().map(|(_, typ, _)| vector_count(typ, ctx.clone().recur())).sum()
                    } else if let Some(variants) = struct_type.get_variants(args) {
                        variants
                            .iter()
                            .flat_map(|(_, types)| types)
                            .map(|typ| vector_count(typ, ctx.clone().recur()))
                            .sum()
                    } else {
                        0
                    }
                } else {
                    // If we bump into a recursive type, we stop counting.
                    // "zero" isn't strictly correct here, but the recursive type will be an error
                    // already so this count won't matter in the end.
                    0
                }
            }
```
The expectation is that if we encounter the same data type after we had to clone the context to pass it to a recursive call, then it's okay to count it as 0, but if we encounter it during the recursive call to one field, and then another field, that still counts as two encounters. 

The cloning also makes it easy to increment the `depth`, and panic if the types are deeper then `TYPE_RECURSION_LIMIT`, which could be used to avoid #11491 

### Additional Context

_No response_

### Project Impact

None

### Blocker Context

_No response_

### Nargo Version

_No response_

### NoirJS Version

_No response_

### Proving Backend Tooling & Version

_No response_

### Would you like to submit a PR for this Issue?

None

### Support Needs

_No response_

### PR DESCRIPTION
**Pull request by asterite**
# Description

## Problem

Resolves #11507

## User Documentation

Check one:
- [x] No user documentation needed.
- [ ] Changes in _docs/_ included in this PR.
- [ ] **[For Experimental Features]** Changes in _docs/_ to be submitted in a separate PR.

# PR Checklist

- [x] I have tested the changes locally.
- [x] I have formatted the changes with [Prettier](https://prettier.io/) and/or `cargo fmt` on default settings.

### CODE REVIEW

File: compiler/noirc_frontend/src/elaborator/lints.rs [hunk 1]
```diff
@@ -157,23 +158,31 @@ pub(super) fn oracle_returns_multiple_vectors(
...
         match typ {
-            Type::Array(_, item) => vector_count(item, seen_data_types),
-            Type::Vector(typ) => 1 + vector_count(typ, seen_data_types),
-            Type::FmtString(_, item) => vector_count(item, seen_data_types),
-            Type::Tuple(items) => items.iter().map(|typ| vector_count(typ, seen_data_types)).sum(),
+            Type::Array(_, item) => vector_count(item, type_recursion_context),
+            Type::Vector(typ) => 1 + vector_count(typ, type_recursion_context),
+            Type::FmtString(_, item) => vector_count(item, type_recursion_context),
+            Type::Tuple(items) => {
+                items.iter().map(|typ| vector_count(typ, type_recursion_context)).sum()
```
Comment (aakoshh) [inline compiler/noirc_frontend/src/elaborator/lints.rs]: Thanks for adopting my idea! I would have intended it though to be a parameter passed by value, ie. `mut type_recursion_context`, not `&mut`, and `.recur()` would be called every time, to increase the depth. 

`.clone()` is required when we have multiple fields we need to independently recurse into, and we don't want types visited in one to contaminate another.

Comment (aakoshh) [reply compiler/noirc_frontend/src/elaborator/lints.rs]: That way it would handle the case if the 1000 aliases as well

File: compiler/noirc_frontend/src/hir_def/types/recursion.rs [hunk 2]
```diff
@@ -0,0 +1,24 @@
...
+pub(crate) struct TypeRecursionContext {
+    depth: u32,
+    type_recursion_context: im::HashSet<(TypeId, Vec<Type>)>,
+}
+
+impl TypeRecursionContext {
+    /// Increases the recursion depth.
+    pub(crate) fn recur(mut self) -> Self {
+        if self.depth >= TYPE_RECURSION_LIMIT {
+            panic!("Types are too deep!");
```
Comment (aakoshh) [inline compiler/noirc_frontend/src/hir_def/types/recursion.rs]:
```suggestion
            panic!("Type recursion limit reached - types are too large");
```
Sorry, that's the message tests are expecting, I just didn't remember the exact wording.

File: compiler/noirc_frontend/src/elaborator/lints.rs (hunk 1 above)
Comment (asterite) [reply compiler/noirc_frontend/src/elaborator/lints.rs]: Done! I saw it wasn't `&mut ...` in your comment but yesterday when I tried it it gave me an error that I couldn't understand... I must have been tired, I just tried it and it makes perfect sense. It's also nice that it forces you to clone when it's needed (though it doesn't force you to `recur`, but that's not a big deal).

I also noticed one of the methods was already dealing with recursion in this way, for aliases, so I went ahead and started tracking aliases everywhere.

**Review by aakoshh — APPROVED** [review]
LGTM! 

I was trying to think of a way to force calling `.recur()` with `PhantomData`, but nothing simple comes to mind right now.
