### PR TITLE
fix: correct range for overlfowing/underflowing integer assignment

### LINKED ISSUE #5419: Integer literal overflow/underflow doesn't always error when assigning to explicitly typed variable
### Aim

The compiler should error when an integer literal is assigned to a variable with an explicit integer type, and that literal is outside the range of the integer.

This is already the case, but only for unsigned integers, but only if positive values exceed the maximum. What's missing:
- check that negative values can't be assigned to unsigned integers
- check min/max against signed integers

This is similar to #5372, except that here the compiler does an early check with explicitly annotated types, and in the related issue the check is done later on, once unknown types are resolved.

### Expected Behavior

All of these programs should error:

```rust
fn main() {
  let x: u8 = -1;
}
```

```rust
fn main() {
  let x: i8 = -129;
}
```

```rust
fn main() {
  let x: i8 = 128;
}
```

### Bug

The above programs don't error.

### To Reproduce

_No response_

### Project Impact

None

### Impact Context

_No response_

### Workaround

None

### Workaround Description

_No response_

### Additional Context

_No response_

### Installation Method

None

### Nargo Version

_No response_

### NoirJS Version

_No response_

### Would you like to submit a PR for this Issue?

Yes

### Support Needs

_No response_

### PR DESCRIPTION
**Pull request by asterite**
# Description

## Problem

Resolves #5419

## Summary

This is similar to #5372, except that here the compiler does an early check with explicitly annotated types, and in the related issue the check is done later on, once unknown types are resolved.

Also in this PR:
- a test was moved from `test_programs` to `noirc_frontend/src/tests.rs` because the error produced here can be caught there
- the error message produced in both places is now exactly the same (showing the possible range of values, which helps to know why you exceeded the min/max)

## Additional Context

None

## Documentation

Check one:
- [x] No documentation needed.
- [ ] Documentation included in this PR.
- [ ] **[For Experimental Features]** Documentation to be submitted in a separate PR.

# PR Checklist\*

- [x] I have tested the changes locally.
- [x] I have formatted the changes with [Prettier](https://prettier.io/) and/or `cargo fmt` on default settings.

### CODE REVIEW

File: compiler/noirc_frontend/src/tests.rs [hunk 1]
```diff
@@ -1907,3 +1907,79 @@ fn comptime_let() {
...
+            error.to_string(),
+            "The value `2⁷` cannot fit into `i8` which has range `-128..=127`"
+        );
+    } else {
+        panic!("Expected OverflowingAssignment error, got {:?}", errors[0].0);
+    }
+}
+
+#[test]
+fn underflowing_i8() {
```
Comment (michaeljklein) [inline compiler/noirc_frontend/src/tests.rs:1969]: Please add to `cspell.json`: https://github.com/noir-lang/noir/blob/1dcd0733f66f500b0da8957bdb8b804d886f0a6f/cspell.json

File: compiler/noirc_frontend/src/elaborator/statements.rs [hunk 2]
```diff
@@ -86,8 +86,8 @@ impl<'context> Elaborator<'context> {
                     expr_span,
                 }
             });
-            if annotated_type.is_unsigned() {
-                let errors = lints::overflowing_uint(self.interner, &expression, &annotated_type);
+            if annotated_type.is_unsigned() || annotated_type.is_signed() {
```
Comment (michaeljklein) [inline compiler/noirc_frontend/src/elaborator/statements.rs:89]: Could this be an `is_integer` function? It appears that both `is_unsigned` and `is_signed` check for integers and then assert signed/unsigned.

```rust
matches!(self.follow_bindings(), Type::Integer(Signedness::Unsigned, _))
```

**Review by michaeljklein — CHANGES_REQUESTED** [review]

File: compiler/noirc_frontend/src/tests.rs (hunk 1 above)
Comment (asterite) [reply compiler/noirc_frontend/src/tests.rs:1969]: Nice! I didn't know how those "unknown word" checks are configured, it's a nice thing to have.

File: compiler/noirc_frontend/src/elaborator/statements.rs (hunk 2 above)
Comment (asterite) [reply compiler/noirc_frontend/src/elaborator/statements.rs]: Makes sense, done! I think I didn't do it because in another part of the code there's an integer type that's "field", but here it seems it's just those two.

**Review by michaeljklein — APPROVED** [review]
