### PR TITLE
fix(ssa): Remove unused calls to pure functions

### LINKED ISSUE #8233: Only Brillig: `attempted to subtract with overflow`
### Aim

The following program behaves different between Brillig and ACIR:

```rust
global G_A: u128 = 34475917616803563277280217276819298828;
fn main(c: bool) -> pub u32 {
    let mut d: [Field; 1] = func_3(779302847);
    d = if c {
        d[0] = (G_A as Field);
        d
    } else { d };
    1948156509
}

fn func_3(b: u32) -> [Field; 1] {
    [
        if true {
            if (if (!false) { 1061432097 } else { (b >> 41) } < (506440519 - 3531841762)) {
                if true {
                    ((G_A as Field) - (297742546099112882246414176413370796930 + (b as Field)))
                } else {
                    (G_A as Field)
                }
            } else {
                (G_A as Field)
            }
        } else {
            (b as Field)
        },
    ]
}
```

### Expected Behavior

They should agree. 

This is similar to the last 3 bugs I created. It's defining a variable that won't ultimately be used in the return value, but we set one of its elements based on the input. 

### Bug

```console
bash-5.2$ cargo run -q -p nargo_cli -- execute --force-brillig
error: Assertion failed: attempt to subtract with overflow
   ┌─ src/main.nr:14:66
   │
14 │             if (if (!false) { 1061432097 } else { (b >> 41) } < (506440519 - 3531841762)) {
   │                                                                  ----------------------
   │
   = Call stack:
     1. src/main.nr:3:29
     2. src/main.nr:14:66

Failed assertion
bash-5.2$ cargo run -q -p nargo_cli -- execute --force-brillig
[regression_fuzz_testing] Circuit witness successfully solved
[regression_fuzz_testing] Witness saved to target/regression_fuzz_testing.gz
[regression_fuzz_testing] Circuit output: Field(1948156509)
bash-5.2$ cargo run -q -p nargo_cli -- execute 
warning: Return variable contains a constant value
  ┌─ src/main.nr:8:5
  │
8 │     1948156509
  │     ---------- This variable contains a value which is constrained to be a constant. Consider removing this value as additional return values increase proving/verification time
  │
  = Call stack:
    1. src/main.nr:8:5

[regression_fuzz_testing] Circuit witness successfully solved
[regression_fuzz_testing] Witness saved to target/regression_fuzz_testing.gz
[regression_fuzz_testing] Circuit output: Field(1948156509)

```

### To Reproduce

See above.

### Workaround

None

### Workaround Description

_No response_

### Additional Context

_No response_

### Project Impact

None

### Blocker Context

_No response_

### Nargo Version

nargo version = 1.0.0-beta.4 noirc version = 1.0.0-beta.4+ae008d31e289ddb086b4c69e3fd287c5167fc4dc (git version hash: 9f595ea5ff5da20490c263de3283ee23d9f8bde8, is dirty: true)

### NoirJS Version

_No response_

### Proving Backend Tooling & Version

_No response_

### Would you like to submit a PR for this Issue?

None

### Support Needs

_No response_

### PR DESCRIPTION
**Pull request by vezenovm**
# Description

## Problem\*

Resolves no issue, but a basic optimization that we were missing out on.

## Summary\*

We were marking all calls as being side effectual during DIE, causing us to not eliminate calls to pure functions. Pure w/ predicates functions can be handled in a separate PR that accesses whether the current predicate is false. In ACIR, as the pure function is inlined all of its internal instructions were ultimately removed. While in Brillig, the function call remained thus triggering a failure that we did not see in Brillig. 

## Documentation\*

Check one:
- [ ] No documentation needed.
- [X] Documentation included in this PR.
- [ ] **[For Experimental Features]** Documentation to be submitted in a separate PR.

# PR Checklist\*

- [X] I have tested the changes locally.
- [X] I have formatted the changes with [Prettier](https://prettier.io/) and/or `cargo fmt` on default settings.

### CODE REVIEW

File: compiler/noirc_evaluator/src/ssa/opt/die.rs [hunk 1]
```diff
@@ -390,7 +391,14 @@ fn can_be_eliminated_if_unused(
             Value::ForeignFunction(_) => false,
 
             // We must assume that functions contain a side effect as we cannot inspect more deeply.
```
Comment (TomAFrench) [inline compiler/noirc_evaluator/src/ssa/opt/die.rs:393]:
```suggestion
```

Seems like this comment is superceded

File: compiler/noirc_evaluator/src/ssa/opt/die.rs [hunk 2]
```diff
@@ -390,7 +391,14 @@ fn can_be_eliminated_if_unused(
...
-            Value::Function(_) => false,
+            // We use purity to determine whether functions contain side effects.
+            // If we have an impure function, we cannot remove it even if it is unused.
+            Value::Function(function_id) => match function.dfg.purity_of(function_id) {
+                Some(Purity::Pure) => true,
+                Some(Purity::PureWithPredicate) => true,
```
Comment (jfecher) [inline compiler/noirc_evaluator/src/ssa/opt/die.rs:398]: Is this right? Seems like this case should depend on the predicate value. E.g. a function with a `constrain` inside will be marked as this and we don't want to remove those unless we know the predicate is false.

Comment (vezenovm) [reply compiler/noirc_evaluator/src/ssa/opt/die.rs:397]: Yeah you are correct. I just wanted to see the effects here. I hadn't looked deeply into the purity types but I see now that we mark functions with `constrain` as being `PureWithPredicate`. I am most likely going to add some more granular purity types.

Comment (jfecher) [reply compiler/noirc_evaluator/src/ssa/opt/die.rs:397]: What would the more granular cases be for?

Comment (vezenovm) [reply compiler/noirc_evaluator/src/ssa/opt/die.rs:397]: I was thinking along the lines of that handling `constrain` and binary ops are different depending on whether we want to deduplicate, hoist, or eliminate. However, after looking a bit deeper we probably just want to not eliminate checked binary ops at all as suggested by @TomAFrench. 

For now, I think I will just switch `PureWithPredicate` to `false`. We can add checking whether the predicate is false in a separate PR, as we will need to handle checking both control dependence for Brillig and the side effects var for ACIR.

File: compiler/noirc_evaluator/src/ssa/opt/die.rs [hunk 3]
```diff
@@ -389,8 +390,14 @@ fn can_be_eliminated_if_unused(
             // from the ACVM to the external world during execution.
             Value::ForeignFunction(_) => false,
 
-            // We must assume that functions contain a side effect as we cannot inspect more deeply.
-            Value::Function(_) => false,
+            // We use purity to determine whether functions contain side effects.
+            // If we have an impure function, we cannot remove it even if it is unused.
+            Value::Function(function_id) => match function.dfg.purity_of(function_id) {
+                Some(Purity::Pure) => true,
+                Some(Purity::PureWithPredicate) => true,
```
Comment (vezenovm) [inline compiler/noirc_evaluator/src/ssa/opt/die.rs:397]:
```suggestion
                Some(Purity::PureWithPredicate) => false,
```

File: compiler/noirc_evaluator/src/ssa/opt/die.rs (hunk 2 above)
Comment (vezenovm) [reply compiler/noirc_evaluator/src/ssa/opt/die.rs]: Tracking here https://github.com/noir-lang/noir/issues/8302

**Comment by vezenovm** [comment]
@jfecher @TomAFrench This doesn't really make an meaningful changes in our test programs but I added a unit test to display the functionality.

**Review by TomAFrench — APPROVED** [review]
LGTM
