### PR TITLE
fix: Correct off-by-one errors in lexer spans

### LINKED ISSUE #1683: Codespans are off-by-one
### Aim

While building #1676, I encountered the LSP ranges being off-by-one, but that didn't seem to be displayed by the CLI reporter. This seems to be due to a `+ 1` on the end of the span before we report them, but that is hiding an overall issue with our span start/ends.

### Expected Behavior

Spans should give the correct start and end.

### Bug

Some or all spans seem to be off-by-one.

### To Reproduce

It's easiest to notice this once #1676 lands because you can just write some incorrect noir code and you'll have a red underline that doesn't overlay the entire symbol.

### Installation Method

None

### Nargo Version

_No response_

### Additional Context

I opened #1682 to remove that `+ 1` so we can find and solve the underlying issue.

### Would you like to submit a PR for this Issue?

No

### Support Needs

_No response_

### PR DESCRIPTION
**Pull request by TomAFrench**
# Description

## Problem\*

Closes #1682 
Resolves #1683

## Summary\*

This PR addresses the off-by-one errors in how we deal with spans in a way which makes sense to me.

For example in `parse_block_comment` we're creating a span which goes from the start of the comment to the very last character in the file. We should then have an inclusive span here. Similarly when we have a `&&` we were previously creating a span of size 1 which doesn't really make sense for when we're capturing two characters.

Based on this, I noticed that `from_position` was creating exclusive end spans whereas we're calling it in the same way where logically we should have inclusive spans. I then switched this and the red squigglies are all appearing where I expect them to be.

## Documentation

- [ ] This PR requires documentation updates when merged.

  

  - [ ] I will submit a noir-lang/docs PR.

  

  - [ ] I will request for and support Dev Rel's help in documenting this PR.

  
  

## Additional Context

# PR Checklist\*

- [x] I have tested the changes locally.
- [x] I have formatted the changes with [Prettier](https://prettier.io/) and/or `cargo fmt` on default settings.

### CODE REVIEW

**Review by phated — COMMENTED** [review]
I'll give this a try in a bit

File: crates/noirc_frontend/src/lexer/lexer.rs [hunk 1]
```diff
@@ -331,7 +331,7 @@ impl<'a> Lexer<'a> {
     }
 
     fn parse_block_comment(&mut self) -> SpannedTokenResult {
-        let span = Span::new(self.position..self.position + 1);
```
Comment (TomAFrench) [inline crates/noirc_frontend/src/lexer/lexer.rs:334]: This is a change to how we display this error. Previously we'd only show a red squiggly over the first `*` of the comment but now we go from that `*` to the end of the file.

Motivation being that it's more noticeable and fits better with a "hey your comment is covering everything" error.

**Review by jfecher — DISMISSED** [review]

**Review by phated — CHANGES_REQUESTED** [review]
Screenshot 2023-08-22 at 3 19 30 PM

I found more span problems even with these changes included. I'll push up my changes shortly

**Comment by phated** [comment]
Two more issues with strings:
Screenshot 2023-08-22 at 3 25 19 PM

**Comment by phated** [comment]
Pushed my new changes that fix all of the above:
Screenshot 2023-08-22 at 3 26 11 PM

**Review by phated — APPROVED** [review]
Approving, but I made changes so let's get other feedback

**Review by jfecher — APPROVED** [review]
LGTM. If any more off by one spans are found we can fix them as part of another PR
