### PR TITLE
fix: format last statement in block with optional semicolon

### LINKED ISSUE #7735: `nargo fmt` panics when the last assignment in a block lacks an optional semicolon
### Aim

Attempted to run `nargo fmt` on a program that omits a semicolon from the last assignment in a block, as enabled by https://github.com/noir-lang/noir/pull/7718:

```noir
fn main() {
    let mut x: Field = 0;
    {
        x = 1
    }
    assert_eq(x, 1);
}
```

### Expected Behavior

Expected the formatting to be successful or fail with a user error.

### Bug

`nargo compile` and `nargo execute` succeed:

```bash
❯ ~/.nargo/bin/nargo compile

❯ ~/.nargo/bin/nargo execute
[test_closure_missing_semicolon_fmt] Circuit witness successfully solved
..
```

But formatting panics:

```bash
❯ ~/.nargo/bin/nargo fmt
The application panicked (crashed).
Message:  Expected token Semicolon, got: RightBrace
Location: tooling/nargo_fmt/src/formatter.rs:195

This is a bug. We may have already fixed this in newer versions of Nargo so try searching for similar issues at https://github.com/noir-lang/noir/issues/.
If there isn't an open issue for this bug, consider opening one at https://github.com/noir-lang/noir/issues/new?labels=bug&template=bug_report.yml
```

### To Reproduce

1.
2.
3.
4.

### Workaround

Yes

### Workaround Description

Add the optional semicolon

### Additional Context

_No response_

### Project Impact

Nice-to-have

### Blocker Context

_No response_

### Nargo Version

nargo version = 1.0.nargo version = 1.0.0-beta.3 noirc version = 1.0.0-beta.3+45ad637273cef317eba42feaf2be0e59d34065ed (git version hash: 45ad637273cef317eba42feaf2be0e59d34065ed, is dirty: false)0-beta.3 noirc version = 1.0.0-beta.3+45ad637273cef317eba42feaf2be0e59d34065ed (git version hash: 45ad637273cef317eba42feaf2be0e59d34065ed, is dirty: false)

### NoirJS Version

_No response_

### Proving Backend Tooling & Version

_No response_

### Would you like to submit a PR for this Issue?

None

### Support Needs

_No response_

### PR DESCRIPTION
**Pull request by asterite**
# Description

## Problem

Resolves #7735

## Documentation

Check one:
- [x] No documentation needed.
- [ ] Documentation included in this PR.
- [ ] **[For Experimental Features]** Documentation to be submitted in a separate PR.

# PR Checklist

- [x] I have tested the changes locally.
- [x] I have formatted the changes with [Prettier](https://prettier.io/) and/or `cargo fmt` on default settings.

### CODE REVIEW

File: tooling/nargo_fmt/src/formatter/expression.rs [hunk 1]
```diff
@@ -2476,4 +2476,43 @@ global y = 1;
...
+        break
+    }
+    assert_eq(x, 1);
+}
+";
+        assert_format(src, src);
+    }
+
+    #[test]
+    fn format_last_continue_in_block_without_semicoln() {
```
Comment (TomAFrench) [inline tooling/nargo_fmt/src/formatter/expression.rs:2507]:
```suggestion
    fn format_last_assignment_in_block_without_semicolon() {
        let src = "fn main() {
    let mut x: Field = 0;
    {
        x = 1
    }
    assert_eq(x, 1);
}
";
        assert_format(src, src);
    }

    #[test]
    fn format_last_break_in_block_without_semicolon() {
        let src = "fn main() {
    let mut x: Field = 0;
    {
        break
    }
    assert_eq(x, 1);
}
";
        assert_format(src, src);
    }

    #[test]
    fn format_last_continue_in_block_without_semicolon() {
```
