### PR TITLE
fix: predicate the user-supplied index inside get_flattened_index

### LINKED ISSUE #12451: Completeness bug: inconsistency between brillig and ACIR inside a disabled if branch (ACIR rejects valid witness)
### Expected Behavior

**prover.toml:**
```
i = "999"
cond = false
```

**main.nr:**
```
fn main(i: u32, cond: bool) -> pub u32 {
let arr: [u32; 3] = [10, 20, 30];
let mut s: [u32] = arr.as_slice();
if cond {
let (s2, _) = s.remove(i);
s = s2;
}
s.len() as u32
}
```

**expected behavior should just be a successful run, since the code branch inside "if cond" should have been disabled**

### Bug

**An error was unexpectedly reported:**

nargo execute
error: Index out of bounds, array has size 3, but index was 999
   ┌─ src/main.nr:21:23
   │
21 │         let (s2, _) = s.remove(i);
   │                       --------
   │
   = Call stack:
     1. src/main.nr:21:23

Failed to solve program: 'Index out of bounds, array has size 3, but index was 999'

**When the "--force-brillig" flag is applied, the call was treated correctly as a no-op (unlike when "--force-brillig" was not turned on)**

[repro_remove_homog] Circuit witness successfully solved
[repro_remove_homog] Witness saved to target/repro_remove_homog.gz
[repro_remove_homog] Circuit output: 3

### Workaround

_No response_

### Project Impact

Valid programs that call Vec::remove or Vec::insert inside a conditional branch fail to execute in ACIR when the index is out of bounds for the disabled branch.

### Nargo Version

nargo version = 1.0.0-beta.20 noirc version = 1.0.0-beta.20+5f685966dadbb42bffb46994fd49c502601525b4 (git version hash: 5f685966dadbb42bffb46994fd49c502601525b4, is dirty: false)

### NoirJS Version

_No response_

### Proving Backend

_No response_

### Would you like to submit a PR for this Issue?

Maybe

### PR DESCRIPTION
**Pull request by AztecBot**
## Bug

In ACIR mode, `slice.remove(i)` and `slice.insert(i, ...)` inside a disabled `if` branch leak an "Index out of bounds" runtime error when the user-supplied index is out of range, even though the surrounding side-effects predicate is `false`. Brillig handles the same programs correctly.

```rust
// Both crash in ACIR with cond=false, i=999.
fn main_remove(i: u32, cond: bool) -> pub u32 {
    let mut s: [u32] = [10, 20, 30].as_vector();
    if cond { let (s2, _) = s.remove(i); s = s2; }
    s.len() as u32
}

fn main_insert(i: u32, cond: bool) -> pub u32 {
    let mut s: [u32] = [10, 20, 30].as_vector();
    if cond { s = s.insert(i, 42); }
    s.len() as u32
}
```

## Root cause

`Context::get_flattened_index` (`compiler/noirc_evaluator/src/acir/arrays.rs`) only gated the index by the side-effects predicate inside the *heterogeneous* (variable element-size) branch. The *homogeneous* branch — taken whenever the vector has constant element size, including all primitive `[T]` slices — returned the raw `var_index * step_size` and ignored `is_safe_index`.

Three intrinsic conversions consume that index for memory operations:

1. **`convert_vector_remove`** — reads the popped element from the source block at `flat_user_index`. With `i = 999` the read at index 999 fails the ACVM bounds check.
2. **`convert_vector_insert`** — uses `flat_user_index` in `is_after_insert = (i >= flat_user_index)`. When the user index is huge `is_after_insert` is `0` for every iteration, so `shifted_index = i` (the unshifted path), which overruns the source block when `i >= original_size`.
3. **`convert_vector_push_back`** (dynamic-length branch) — the index it passes is `vector_length * elements_to_push.len()` (SSA-tracked length, not user-supplied) and the result block is sized for `length + 1`, so the write was already in bounds. Audited; not affected.

The `array_get` / `array_set` codepath did not have this bug because `convert_array_operation_inputs` was always clamping the index via a separate `predicated_index` helper (offset-aware, offset = 0 for primitive arrays). The vector intrinsics were missing that step, and the predication was a property of the call site rather than of the flat-index helper itself.

## Fix

Move the predicate gate into `get_flattened_index`, above the homogeneous/heterogeneous fork:

```rust
let var_index = if is_safe_index {
    var_index
} else {
    self.acir_context.mul_var(var_index, self.current_side_effects_enabled_var)?
};
```

`is_safe_index = false` now uniformly means "safe to use as a memory address — on a disabled branch the index collapses to `0`, which is always in bounds for a non-empty array/vector." `mul_var` constant-folds `x*1 → x` and `x*0 → 0` (`acir_context/mod.rs:618`), so the gate is free when the predicate is statically known and only adds a single multiplication when it's dynamic.

Vector intrinsics no longer need any explicit predication around `get_flattened_index` — they consume its output directly.

`convert_array_operation_inputs` keeps its disabled-branch fallback bias toward `offset` (rather than `0`) because `apply_index_side_effects` relies on the dummy at `block[offset]` being type-compatible with the read's result type to skip masking (e.g. for `[(Field, u8, u8); 3]`, reading `.counter` falls back to offset `1` so the dummy is a `u8`, not the `Field` at offset `0`). The previous `predicated_index` helper has been inlined and rewritten to add `offset * (1 - predicate)` instead of multiplying by the predicate a second time — this avoids a redundant boolean `* predicate` (since `predicate^2 == predicate` but `mul_var` doesn't know that) and matches the original constraint count.

## Tests

Two regression tests under `test_programs/execution_success/`:

- `vector_remove_oob_index_invalid_pred/` — `s.remove(999)` in a disabled branch, expects `len = 3`.
- `vector_insert_oob_index_invalid_pred/` — `s.insert(999, 42)` in a disabled branch, expects `len = 3`.

Both fail in ACIR before the fix with `Index out of bounds`; both pass in ACIR and Brillig after.

The two existing `generates_predicated_index_*` snapshot tests are updated to reflect that the predicate gate now appears once (from `get_flattened_index`) instead of being introduced by `predicated_index`.

## Verification

- New tests (16 variants each — forcebrillig × inliner × interpret/expand): all pass
- 442 `vector_*` execution tests: all pass
- 698 `array_*` execution tests: all pass
- 1397 `noirc_evaluator` unit tests: all pass
- `cargo fmt --check` clean

Detailed audit of every `get_flattened_index` caller: https://gist.github.com/AztecBot/af6c4ebf981046903257dfe271c9b0b8

### CODE REVIEW

File: compiler/noirc_evaluator/src/acir/call/intrinsics/vector_ops.rs [hunk 1]
```diff
@@ -778,14 +778,26 @@ impl Context<'_> {
...
+        // gate `flat_user_index` by the side-effects predicate, so the upcoming memory
+        // read at this index needs explicit predication: when side effects are disabled
+        // the read falls back to index 0, which is always in bounds for a non-empty vector.
+        // `mul_var` constant-folds when the predicate is a known `0` or `1`, so this is
+        // free in those cases and only adds a gate when the predicate is dynamic.
+        let safe_user_index = if is_safe_index {
+            flat_user_index
+        } else {
+            self.acir_context.mul_var(flat_user_index, self.current_side_effects_enabled_var)?
+        };
```
Comment (TomAFrench) [inline compiler/noirc_evaluator/src/acir/call/intrinsics/vector_ops.rs]:
```suggestion
       
        let safe_user_index = if is_safe_index {
            flat_user_index
        } else {
            // `mul_var` constant-folds when the predicate is a known `0` or `1`, so this is
            // free in those cases and only adds a gate when the predicate is dynamic.
            self.acir_context.mul_var(flat_user_index, self.current_side_effects_enabled_var)?
        };
```

File: compiler/noirc_evaluator/src/acir/call/intrinsics/vector_ops.rs [hunk 2]
```diff
@@ -778,14 +778,27 @@ impl Context<'_> {
             ElementTypeSizesArrayShift::None,
         )?;
 
+        // For homogeneous (constant-element-size) vectors `get_flattened_index` does not
+        // gate `flat_user_index` by the side-effects predicate, so the upcoming memory
+        // read at this index needs explicit predication: when side effects are disabled
+        // the read falls back to index 0, which is always in bounds for a non-empty vector.
+
```
Comment (TomAFrench) [inline compiler/noirc_evaluator/src/acir/call/intrinsics/vector_ops.rs]:
```suggestion
```

**Review by asterite — APPROVED** [review]
