### PR TITLE
fix: validate binary operations which do not allow fields

### LINKED ISSUE #9627: ACIR vs Brillig: ACIR allows bitwise ops for fields
### Aim

The following SSA 
```
fn main f0 {
  b0(v0: u1, v1: Field, v2: Field, v3: u1, v4: Field, v5: u1, v6: u1):
    jmp b1()
  b1():
    v7 = and v2, v1
    return v7
}
```
Failed to compile in Brillig and solved in ACIR

### Expected Behavior

ACIR failed

### Bug

```
ACIR compiled and successfully executed, but brillig compilation failed. Execution result of acir only 0. Brillig compilation failed with: RuntimeError("Compilation error RuntimeError(InternalError(General { message: \"Panic occurred: Panic: Unsupported operation: And on a field at compiler/noirc_evaluator/src/brillig/brillig_ir/instructions.rs:490\", call_stack: [] }))")
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
```

### To Reproduce

1.
2.
3.
4.

### Workaround

None

### Workaround Description

_No response_

### Additional Context

_No response_

### Project Impact

None

### Blocker Context

_No response_

### Nargo Version

_No response_

### NoirJS Version

_No response_

### Proving Backend Tooling & Version

_No response_

### Would you like to submit a PR for this Issue?

None

### Support Needs

_No response_

### PR DESCRIPTION
**Pull request by TomAFrench**
# Description

## Problem\*

Resolves #9627 

## Summary\*

These programs were not possible except through constructing invalid SSA. This PR adds additional SSA validation to catch these cases. I've also beefed up ACIRgen to panic rather than assuming that we've caught this case in the frontend.

## Documentation\*

Check one:
- [x] No documentation needed.
- [ ] Documentation included in this PR.
- [ ] **[For Experimental Features]** Documentation to be submitted in a separate PR.

# PR Checklist\*

- [x] I have tested the changes locally.
- [x] I have formatted the changes with [Prettier](https://prettier.io/) and/or `cargo fmt` on default settings.

### CODE REVIEW

File: compiler/noirc_evaluator/src/ssa/validation/mod.rs [hunk 1]
```diff
@@ -148,26 +148,23 @@ impl<'f> Validator<'f> {
...
+
+                if matches!(
+                    operator,
+                    BinaryOp::Lt
+                        | BinaryOp::And
+                        | BinaryOp::Or
+                        | BinaryOp::Xor
+                        | BinaryOp::Shl
+                        | BinaryOp::Shr
+                ) {
```
Comment (vezenovm) [inline compiler/noirc_evaluator/src/ssa/validation/mod.rs]: Should we not also check `matches!(lhs_type, Type::Numeric(NumericType::NativeField))` here?

Comment (TomAFrench) [reply compiler/noirc_evaluator/src/ssa/validation/mod.rs]: Ah lol yeah. I was shifting code around a bit and must have forgotten.

**Review by vezenovm — APPROVED** [review]

File: compiler/noirc_evaluator/src/ssa/validation/mod.rs [hunk 2]
```diff
@@ -203,6 +203,30 @@ impl<'f> Validator<'f> {
...
+                                            )
+                                        ),
+                                        "Bitwise operation performed on non-integer type"
+                                    );
+                                }
+                                BlackBoxFunc::Keccakf1600 => {
+                                    assert_eq!(arguments.len(), 1);
+                                    assert_eq!(
+                                        dfg.type_of_value(arguments[0]),
+                                        Type::Array(Arc::new(vec![Type::unsigned(8)]), 25)
```
Comment (TomAFrench) [inline compiler/noirc_evaluator/src/ssa/validation/mod.rs]:
```suggestion
                                        Type::Array(Arc::new(vec![Type::unsigned(64)]), 25)
```

**Comment by TomAFrench** [comment]
Not merging this yet as this shouldn't be changing the ACIRgen output so doing some investigation.

File: compiler/noirc_evaluator/src/acir/acir_context/mod.rs [hunk 3]
```diff
@@ -379,18 +379,23 @@ impl<F: AcirField, B: BlackBoxFunctionSolver<F>> AcirContext<F, B> {
...
-            // a ^ b == a + b - 2*a*b
-            let prod = self.mul_var(lhs, rhs)?;
-            let sum = self.add_var(lhs, rhs)?;
-            self.add_mul_var(sum, -F::from(2_u128), prod)
-        } else {
-            let inputs = vec![AcirValue::Var(lhs, typ.clone()), AcirValue::Var(rhs, typ)];
-            let outputs = self.black_box_function(BlackBoxFunc::XOR, inputs, 1)?;
-            Ok(outputs[0])
+        match typ.to_numeric_type() {
+            NumericType::Signed { bit_size: 1 } | NumericType::Unsigned { bit_size: 1 } => {
```
Comment (asterite) [inline compiler/noirc_evaluator/src/acir/acir_context/mod.rs:383]: I think there's no `i1`, but this is also harmless so it's probably fine.
