### PR TITLE
fix: allow nested fmtstr

### LINKED ISSUE #9274: format strings cannot be printed
### Bug

This code:

```rust
comptime fn my_macro(s: TypeDefinition) -> Quoted {
    let name = s.name();
    let typ = s.as_type();

    quote {
        impl $typ {
            fn random_func(self)  {
                let note_name = f"$name";
                std::static_assert(false, f"{note_name}");
            }
        }
    }
}

#[my_macro]
struct MyStruct {
    a: u32,
    b: u32,
}

fn main() -> pub Field {
    let my_struct = MyStruct { a: 1, b: 2 };
    my_struct.random_func();
    0
}
```

fails to compile with:

```
The application panicked (crashed).
Message:  internal error: entered unreachable code: format strings cannot be printed
Location: compiler/noirc_frontend/src/hir_def/types.rs:2716

This is a bug. We may have already fixed this in newer versions of Nargo so try searching for similar issues at https://github.com/noir-lang/noir/issues/.
If there isn't an open issue for this bug, consider opening one at https://github.com/noir-lang/noir/issues/new?labels=bug&template=bug_report.yml
```

### Nargo Version

nargo version = 1.0.0-beta.8

### PR DESCRIPTION
**Pull request by asterite**
# Description

## Problem

Resolves #9274

## Summary

I noticed that nested fmtstr did work in comptime so I checked if it would be possible to actually support this at runtime. It turns out that it is (after spending some time figuring out how things are encoded).

## Documentation

Check one:
- [x] No documentation needed.
- [ ] Documentation included in this PR.
- [ ] **[For Experimental Features]** Documentation to be submitted in a separate PR.

# PR Checklist

- [x] I have tested the changes locally.
- [x] I have formatted the changes with [Prettier](https://prettier.io/) and/or `cargo fmt` on default settings.

### CODE REVIEW

File: compiler/noirc_frontend/src/hir_def/types.rs [hunk 1]
```diff
@@ -2746,7 +2746,13 @@ impl From<&Type> for PrintableType {
                     .expect("Cannot print variable sized strings");
                 PrintableType::String { length: size }
             }
-            Type::FmtString(_, _) => unreachable!("format strings cannot be printed"),
+            Type::FmtString(size, typ) => {
+                let dummy_location = Location::dummy();
+                let size = size
+                    .evaluate_to_u32(dummy_location)
+                    .expect("Cannot print variable sized strings");
```
Comment (jfecher) [inline compiler/noirc_frontend/src/hir_def/types.rs:2753]: Maybe we should issue an actual error here instead of moving the panic to a less common situation?
Although the error message would use the dummy location it seems. I wonder if we can forward the location from the println somehow.

**Review by jfecher — COMMENTED** [review]
Nice! Just one concern on a potential new panic

File: compiler/noirc_frontend/src/hir_def/types.rs (hunk 1 above)
Comment (asterite) [reply compiler/noirc_frontend/src/hir_def/types.rs:2753]: Do you know if it's possible for `evaluate_to_u32` to fail here? My thinking is that this happens after monomorphization and if was dynamic it would have errored by now.

That said, I'll try to get a location here.

Comment (asterite) [reply compiler/noirc_frontend/src/hir_def/types.rs:2753]: Hm, it seems monomorphization type handling doesn't happen for these arguments so what I said above is wrong.

Comment (asterite) [reply compiler/noirc_frontend/src/hir_def/types.rs:2753]: Changing this would require some form of Result, and at least in one part of the code there's no Result returned from a function that calls this, so...
Before making this change, it would be nice to find a way to trigger this failure. A similar panic exists for the string case but I don't know if it's possible to end up with `str<N>` or `fmtstr<N, T>` where `N` is not a constant.

Comment (vezenovm) [reply compiler/noirc_frontend/src/hir_def/types.rs:2753]: > A similar panic exists for the string case but I don't know if it's possible to end up with `str<N>` or `fmtstr<N, T>` where `N` is not a constant.

Strings are treated as arrays so `N` should always be constant. We do the same things for strings, moving away from this panic feels like a separate issue to this PR.
