### PR TITLE
fix: restore side effects in interpreter between calls

### LINKED ISSUE #10842: SSA interpreter does not reset side effect variable during recursion
### Aim

Discovered while trying to answer why we do this:
https://github.com/noir-lang/noir/blob/16cad49bed299e97f664251e6086f3c6a61c0ba2/compiler/noirc_evaluator/src/ssa/opt/remove_enable_side_effects.rs#L80-L89

I set `condition_is_one` to always `false` and ran the integration tests. The SSA interpreter failed on the `fold_fibonacci` test, while `execute` and `execute --force-brillig` keeps working.

### Expected Behavior

The SSA interpreter should agree with the other execution methods.

### Bug

```console
❯ RUST_BACKTRACE=1 cargo run -q -p nargo_cli -- interpret --force --show-ssa-pass "step 28" --show-ssa-pass "step 29" --ssa-pass "step 28" --ssa-pass "step 29"

After Simplify conditionals for unconstrained (step 28):
acir(inline) predicate_pure fn main f0 {
  b0(v0: u32):
    v2 = call f1(v0) -> u32
    constrain v2 == u32 55
    return
}
acir(fold) predicate_pure fn fibonacci f1 {
  b0(v0: u32):
    v2 = lt u32 1, v0
    v3 = not v2
    enable_side_effects v2
    v4 = sub v0, u32 1
    v6 = call f1(v4) -> u32
    v8 = sub v0, u32 2
    v9 = call f1(v8) -> u32
    v10 = add v6, v9
    enable_side_effects u1 1
    v12 = cast v3 as u32
    v13 = cast v2 as u32
    v14 = unchecked_mul v12, v0
    v15 = unchecked_mul v13, v10
    v16 = unchecked_add v14, v15
    return v16
}

--- Interpreter result after Simplify conditionals for unconstrained (step 28):
Ok()
---
After EnableSideEffectsIf removal (step 29):
acir(inline) predicate_pure fn main f0 {
  b0(v0: u32):
    v2 = call f1(v0) -> u32
    constrain v2 == u32 55
    return
}
acir(fold) predicate_pure fn fibonacci f1 {
  b0(v0: u32):
    v2 = lt u32 1, v0
    v3 = not v2
    enable_side_effects v2
    v4 = sub v0, u32 1
    v6 = call f1(v4) -> u32
    v8 = sub v0, u32 2
    v9 = call f1(v8) -> u32
    v10 = add v6, v9
    v11 = cast v3 as u32
    v12 = cast v2 as u32
    v13 = unchecked_mul v11, v0
    v14 = unchecked_mul v12, v10
    v15 = unchecked_add v13, v14
    return v15
}

--- Interpreter result after EnableSideEffectsIf removal (step 29):
Err(constrain v2 == v3 failed:
    u32 0 != u32 55)
---
The interpreter encountered an error on one or more passes.
```

The 1st SSA works, but the 2nd fails, with the only difference being the absence of `enable_side_effects u1 1` after the `add`. What is confusing about this is that `cast` and `unchecked_mul` don't use the predicate, so it shouldn't matter. 

Some debugging with `--trace` revealed that as the values are being returned from recursive calls, `v10 = add v6, v9` always set `v10` to 0, even when `v2` was 1. That's because the last recursion set `v2` to 0, which resulted in the `Interpreter::side_effects_enabled` being set to 0, and without the `enable_side_effects 1` it was never reset. 

Since the fully fledged ACIR still works without the reset, I'm wondering if `side_effects_enabled` should be part of the `CallContext` instead of the `Interpreter` itself.

There is further risk that constant folding could be affected, where we reuse the interpreter.

### To Reproduce

Change the code like this:
```
 if condition_is_one && false {
                    last_side_effects_enabled_instruction = None;
                    context.insert_current_instruction();
                } else {
```

### Workaround

None

### Workaround Description

_No response_

### Additional Context

_No response_

### Project Impact

None

### Blocker Context

_No response_

### Nargo Version

nargo version = 1.0.0-beta.16 noirc version = 1.0.0-beta.16+16cad49bed299e97f664251e6086f3c6a61c0ba2 (git version hash: 16cad49bed299e97f664251e6086f3c6a61c0ba2, is dirty: true)

### NoirJS Version

_No response_

### Proving Backend Tooling & Version

_No response_

### Would you like to submit a PR for this Issue?

None

### Support Needs

_No response_

### PR DESCRIPTION
**Pull request by guipublic**
# Description

## Problem

Resolves #10842

## Summary
Side effect is a property of the Interpreter which need to be restored between function calls

## User Documentation

Check one:
- [X] No user documentation needed.
- [ ] Changes in _docs/_ included in this PR.
- [ ] **[For Experimental Features]** Changes in _docs/_ to be submitted in a separate PR.

# PR Checklist

- [X] I have tested the changes locally.
- [X] I have formatted the changes with [Prettier](https://prettier.io/) and/or `cargo fmt` on default settings.

### CODE REVIEW

**Review by TomAFrench — DISMISSED** [review]

File: compiler/noirc_evaluator/src/ssa/interpreter/tests/instructions.rs [hunk 1]
```diff
@@ -1099,6 +1099,35 @@ fn nop() {
...
+    // If side_effects_enabled state is leaked, the constrain_not_equal would be skipped
+    // and the program would succeed even though the values are equal.
+    let error = expect_error(
+        "
+        acir(inline) fn main f0 {
+          b0():
+            call f1()
+            // After returning from f1, side_effects should be enabled again
+            // This constrain should fail because 1 == 1
+            constrain u1 1 != u1 1
```
Comment (aakoshh) [inline compiler/noirc_evaluator/src/ssa/interpreter/tests/instructions.rs:1116]: I was scratching my head for a while on this: I forgot that while `Constrain` ignores the `side_effect_enabled` variable, `ConstrainNotEqual` does not.

File: compiler/noirc_evaluator/src/ssa/interpreter/mod.rs [hunk 2]
```diff
@@ -332,6 +338,9 @@ impl<'ssa, W: Write> Interpreter<'ssa, W> {
 
         self.call_stack.pop();
 
+        // Restore the caller's side_effects_enabled state
+        self.side_effects_enabled = saved_side_effects_enabled;
```
Comment (aakoshh) [inline compiler/noirc_evaluator/src/ssa/interpreter/mod.rs]: This is why I thought the `call_stack` would be a nice home for the side effect. It gets saved and restored at the same time as we push/pop it.

File: compiler/noirc_evaluator/src/ssa/interpreter/tests/instructions.rs (hunk 1 above)
Comment (aakoshh) [reply compiler/noirc_evaluator/src/ssa/interpreter/tests/instructions.rs:1116]: I'm a bit worried that `ConstrainNotEqual` might change in the future to _not_ require an ACIR predicate, and perhaps using something more obvious like `Add` would be better.

**Comment by aakoshh** [comment]
I was wondering if this is relevant between blocks. My theory is that it is not, because `EnableSideEffectsIf` is introduced during flattening, after which there is only one block, right?

**Comment by vezenovm** [comment]
> My theory is that it is not, because `EnableSideEffectsIf` is introduced during flattening, after which there is only one block, right?

Yeah once this variable exists there should be a single block in a function.

**Comment by aakoshh** [comment]
Cool, perhaps that could be a pre-check for flattening

File: compiler/noirc_evaluator/src/ssa/interpreter/mod.rs (hunk 2 above)
Comment (guipublic) [reply compiler/noirc_evaluator/src/ssa/interpreter/mod.rs]: Yes, it's a good point. I moved it into the call_stack.

File: compiler/noirc_evaluator/src/ssa/interpreter/mod.rs [hunk 3]
```diff
@@ -124,19 +128,20 @@ impl<'ssa, W: Write> Interpreter<'ssa, W> {
...
+    /// Resets interpreter state for reuse between top-level calls.
     ///
-    /// This can be used when the interpreter is reused between calls,
-    /// to reset the budget before interpreting the next entry point.
-    pub(crate) fn reset_step_counter(&mut self) {
+    /// This resets the step counter and side_effects_enabled state,
+    /// preparing the interpreter to interpret a new entry point.
+    pub(crate) fn reset_state(&mut self) {
         self.step_counter = 0;
+        self.call_context_mut().side_effects_enabled = true;
```
Comment (aakoshh) [inline compiler/noirc_evaluator/src/ssa/interpreter/mod.rs]: If it's based on the call context, I don't think it needs to be restored, does it?

OTOH, I'm not sure if the interpreter returns an `Err` such as a constraint failure, does the call context stack get cleaned up? I don't think it does. So instead of modifying it, the `call_stack` should be truncated back to contain only the first (global) context.

File: compiler/noirc_evaluator/src/ssa/interpreter/tests/instructions.rs (hunk 1 above)
Comment (guipublic) [reply compiler/noirc_evaluator/src/ssa/interpreter/tests/instructions.rs:1116]: Done, I added another test.

File: compiler/noirc_evaluator/src/ssa/interpreter/mod.rs (hunk 3 above)
Comment (guipublic) [reply compiler/noirc_evaluator/src/ssa/interpreter/mod.rs]: yes side_effects_enabled is not needed anymore here.
In case of error, the interpreter will stop execution so I don't think this is an issue.

Comment (aakoshh) [reply compiler/noirc_evaluator/src/ssa/interpreter/mod.rs]: The problem is that in constant folding we reuse the interpreter instance to evaluate the next brillig call which has constant arguments. If we don't clear the interpreter `call_stack`, it's going to push a call context on top of the previous call, and instead of starting with a `call_stack` that consists only of the global context, it will have the the stack of call context from wherever the previous call failed.

Comment (aakoshh) [reply compiler/noirc_evaluator/src/ssa/interpreter/mod.rs]: Best thing would most likely be to stop reusing and create a fresh instance each time.

Comment (guipublic) [reply compiler/noirc_evaluator/src/ssa/interpreter/mod.rs]: brillig calls are not impacted by side_effects
Also, it will push a new call context for each function.

Comment (aakoshh) [reply compiler/noirc_evaluator/src/ssa/interpreter/mod.rs]: True, but the `call_stack` contains variable bindings as well. If all is well I expect a variable lookup would not bubble up beyond the entry of the current call, however we are 1) leaking memory to some extent by not freeing resources and 2) making it harder to reach the global context, because we have to skip over all the failed call stacks until we find their variable ID in the first frame (although it might realise it's a global and go there directly, I'm not sure).

Comment (aakoshh) [reply compiler/noirc_evaluator/src/ssa/interpreter/mod.rs]: I think the motivation for reuse is so globals only get computed once.

Comment (aakoshh) [reply compiler/noirc_evaluator/src/ssa/interpreter/mod.rs]: Sorry, there is no transitive lookups in the `scope`, so that's not a problem. Then we are just growing it with each failure, and the only observable side effect would probably be when the current top level call ends, it would print "back in function ..." with whatever the previously failed function was.

Comment (aakoshh) [reply compiler/noirc_evaluator/src/ssa/interpreter/mod.rs]: We discussed that this is out of scope for this bug. 
Created https://github.com/noir-lang/noir/issues/10891 to capture just the accumulation of the call stack.
