### PR TITLE
fix: check types crossing boundaries during monomorphization too

### LINKED ISSUE #7288: Passing a mutable reference to Brillig indirectly fails with wrong error at SSA
### Aim

Attempted to call an unconstrained function on a mutable reference indirectly.

```noir
unconstrained fn foo<T>(x: T) -> T {
    x
}

fn bar<T>(x: T) -> T {
    unsafe { foo(x) }
}

fn main(x: Field, y: pub Field) {
    let mut y = 0;
    let x = &mut y;
    assert(*(unsafe { bar(x) }) == 0);
}
```

### Expected Behavior

Expected a clear front-end error.

### Bug

Compilation doesn't fail until it reaches SSA and fails with an invalid error message:

```bash
error: Could not resolve some references to the array. All references must be resolved at compile time
   ┌─ src/main.nr:10:17
   │
10 │     let mut y = 0;
   │                 -
   │
   = Call stack:
     1. src/main.nr:10:17

Aborting due to 1 previous error
```

NOTE: "to the array" in this error is a bug because the program lacks arrays. 

### To Reproduce

1.
2.
3.
4.

### Workaround

None

### Workaround Description

_No response_

### Additional Context

_No response_

### Project Impact

Nice-to-have

### Blocker Context

_No response_

### Nargo Version

nargo version = 1.0.0-beta.1 noirc version = 1.0.0-beta.1+3a42eb5c68f9616f0ebe367c894f0376ba41e0ef (git version hash: 3a42eb5c68f9616f0ebe367c894f0376ba41e0ef, is dirty: false)

### NoirJS Version

_No response_

### Proving Backend Tooling & Version

_No response_

### Would you like to submit a PR for this Issue?

None

### Support Needs

_No response_

### LINKED ISSUE #10216: Panic when printing a slice containing a dynamic mutable value
### Aim

I attempted to compile a `main.nr` containing the following:

```noir
fn main(mut x: u32) {
    let xs = &[&mut x];
    println(xs);
}
```

### Expected Behavior

I expected the program to compile successfully or else fail with a user-level error

### Bug

```bash
❯ ~/.nargo/bin/nargo compile
The application panicked (crashed).
Message:  Expected RuntimeError to have a location. Error message: Could not resolve some references to the array. All references must be resolved at compile time
Location: compiler/noirc_evaluator/src/errors.rs:248
```

### To Reproduce

1.
2.
3.
4.

### Workaround

None

### Workaround Description

_No response_

### Additional Context

_No response_

### Project Impact

None

### Blocker Context

_No response_

### Nargo Version

nargo version = 1.0.0-beta.14
noirc version = 1.0.0-beta.14+3f4b2849da02163ed82936f8917767b7a43b1c3c
(git version hash: 3f4b2849da02163ed82936f8917767b7a43b1c3c, is dirty: false)

### NoirJS Version

_No response_

### Proving Backend Tooling & Version

_No response_

### Would you like to submit a PR for this Issue?

None

### Support Needs

_No response_

### LINKED ISSUE #10217: Panic when asserting equality on a dynamic mutable value in a slice
### Aim

I attempted to compile a `main.nr` containing the following:

```noir
fn main(mut x: u32) {
    let xs = &[&mut x];
    println(xs);
    assert(*xs[0] == 0);
}
```

### Expected Behavior

I expected the program to compile successfully or else fail with a user-level error

### Bug

```bash
❯ ~/.nargo/bin/nargo compile
The application panicked (crashed).
Message:  Load instruction exists before `array_set_optimization` pass
Location: compiler/noirc_evaluator/src/ssa/opt/array_set.rs:221
```

### To Reproduce

1.
2.
3.
4.

### Workaround

None

### Workaround Description

_No response_

### Additional Context

_No response_

### Project Impact

None

### Blocker Context

_No response_

### Nargo Version

nargo version = 1.0.0-beta.14
noirc version = 1.0.0-beta.14+3f4b2849da02163ed82936f8917767b7a43b1c3c
(git version hash: 3f4b2849da02163ed82936f8917767b7a43b1c3c, is dirty: false)

### NoirJS Version

_No response_

### Proving Backend Tooling & Version

_No response_

### Would you like to submit a PR for this Issue?

None

### Support Needs

_No response_

### LINKED ISSUE #10259: Returning slices from Brillig via generics is allowed by shouldn't
### Aim

This code:

```noir
unconstrained fn foo<T>(x: T) -> T {
    x
}

fn bar<T>(x: T) -> T {
    unsafe {
        foo(x)
    }
}

fn main(x: Field) {
    let xs = &[x, x + 1, x + 2];
    unsafe { bar(xs) };
}
```

when compiled, triggers this error:

```
The application panicked (crashed).
Message:  internal error: entered unreachable code: The type [Field] cannot be represented in ACIR
Location: compiler/noirc_evaluator/src/acir/types.rs:74
```

This is similar to #7288 but when slices is returned.

### Expected Behavior

The code above should not compile, saying that slices cannot be returned from an unconstrained context.

### Bug

The compiler crashes.

### To Reproduce

1.
2.
3.
4.

### Workaround

None

### Workaround Description

_No response_

### Additional Context

_No response_

### Project Impact

None

### Blocker Context

_No response_

### Nargo Version

_No response_

### NoirJS Version

_No response_

### Proving Backend Tooling & Version

_No response_

### Would you like to submit a PR for this Issue?

None

### Support Needs

_No response_

### LINKED ISSUE #10281: Mutable reference can be passed from constrained to unconstrained inside lambda
### Aim

This is related to #7288 except that in this case there are no generic arguments.

Here's the code:

```noir
fn main() {
    // Safety: testing
    let f = unsafe { get_fn() };
    f();
}

unconstrained fn get_fn() -> fn() {
    || bar(&mut 0)
}

unconstrained fn bar(ref: &mut Field) {
    println(*ref);
}
```

What happens is that `f` is called from a constrained context. The call to `bar` happens in an unconstrained context and the compiler doesn't realize that it could actually happen in a constrained context if that function escapes the unconstrained boundary. Then the call `f` -> `bar` switches from constrained to unconstrained, even though it's not immediately clear that this happens.

Then when the program is compiled we get this error:

```
error: Could not resolve some references to the array. All references must be resolved at compile time
  ┌─ src/main.nr:8:17
  │
8 │     || bar(&mut 0)
  │                 -
  │
  = Call stack:
    1. src/main.nr:4:5
    2. src/main.nr:8:17

Aborting due to 1 previous error
```

### Expected Behavior

The compiler should still fail to compile, but the message should be clearer (probably detected during frontend/monomorphization and not during SSA-gen).

### Bug

The compiler errors with an unclear message.

### To Reproduce

1.
2.
3.
4.

### Workaround

None

### Workaround Description

_No response_

### Additional Context

_No response_

### Project Impact

None

### Blocker Context

_No response_

### Nargo Version

_No response_

### NoirJS Version

_No response_

### Proving Backend Tooling & Version

_No response_

### Would you like to submit a PR for this Issue?

None

### Support Needs

_No response_

### LINKED ISSUE #10379: Printing a format string with a mutable variable erroring with "Could not resolve some references to the array"
### Aim

I attempted to compile the following program:

```noir
fn main() {
  let mut x: Field = 0;
  let y = &mut x;
  println(f"{y}");
}
```

### Expected Behavior

I expected the program to compile successfully or else fail with an error mentioning support for printing or formatting mutable references

### Bug

```bash
❯ ~/.nargo/bin/nargo compile
error: Could not resolve some references to the array. All references must be resolved at compile time
  ┌─ src/main.nr:2:22
  │
2 │   let mut x: Field = 0;
  │                      -
  │
  = Call stack:
    1. src/main.nr:2:22

Aborting due to 1 previous error
```

### To Reproduce

1.
2.
3.
4.

### Workaround

```noir
fn main() {
  let mut x: Field = 0;
  let y = &mut x;
  let z = *y;
  println(f"{z}");
}
```

### Workaround Description

_No response_

### Additional Context

_No response_

### Project Impact

None

### Blocker Context

_No response_

### Nargo Version

nargo version = 1.0.0-beta.14 noirc version = 1.0.0-beta.14+27c9f674ed4a6f65c7b48f6b73ae37ffbb9969ba (git version hash: 27c9f674ed4a6f65c7b48f6b73ae37ffbb9969ba, is dirty: false)

### NoirJS Version

_No response_

### Proving Backend Tooling & Version

_No response_

### Would you like to submit a PR for this Issue?

None

### Support Needs

_No response_

### PR DESCRIPTION
**Pull request by asterite**
# Description

## Problem

Resolves #7288
Resolves #10216
Resolves #10217
Resolves #10259
Resolves #10281
Resolves #10379

## Summary

Revival of #10264

In reality the above issues were kind of fixed already after we (@aakoshh) started detecting this during SSA. The issues is that the error message in SSA wasn't very helpful for fixing the issue.

For example for #7288 we got:

```
error: Trying to pass a reference from ACIR function 'bar f1' to unconstrained 'foo f2' in argument v0: &mut Field
```

Now we get:

```
error: Cannot pass mutable reference `&mut Field` from a constrained runtime to an unconstrained runtime
  ┌─ src/main.nr:7:13
  │
7 │         foo(x)
  │             -
```

It's the same case for #10216, #10217 and #10379.

For #10259, `master` panics, but here it's fixed:

```
error: Slice `[Field]` cannot be returned from an unconstrained runtime to a constrained runtime
  ┌─ src/main.nr:7:9
  │
7 │         foo(x)
  │         ------
```

#10281 was already fixed in master, this PR changes nothing.

### List of changes here

1. Now lambdas can be explicitly unconstrained. This isn't strictly necessary, but for completeness I think that's nice to have. That is, you can now do `let f = unconstrained |x| x + 1;`
2. Passing of mutable references, and slices, between runtimes is now checked during monomorphization in addition to partially checking it in the frontend (can't check generics until monomorphization) and the SSA (where error messages aren't very nice).

In #10264 there was some code blocking it:

```noir
unconstrained fn main() {
    foo(|x| bar(x))
}

unconstrained fn foo(f: fn(&mut Field)) {
    let x = &mut 0;
    f(x);
}

unconstrained fn bar(_: &mut Field) {}
```

But with the changes that are in master it works fine, as that `fn` is assumed to be unconstrained because it happens in an unconstrained function.

## Additional Context

At this point I feel that we might not need the `constrained fn` and `dual fn` variants. Maybe not allowing constrained functions to escape unconstrained boundaries solved everything, not sure.

## User Documentation

Check one:
- [x] No user documentation needed.
- [ ] Changes in _docs/_ included in this PR.
- [ ] **[For Experimental Features]** Changes in _docs/_ to be submitted in a separate PR.

# PR Checklist

- [x] I have tested the changes locally.
- [x] I have formatted the changes with [Prettier](https://prettier.io/) and/or `cargo fmt` on default settings.

### CODE REVIEW

File: compiler/noirc_frontend/src/parser/parser/lambda.rs [hunk 1]
```diff
@@ -1,19 +1,27 @@
...
     /// LambdaParameter
     ///     = Pattern OptionalTypeAnnotation
     pub(super) fn parse_lambda(&mut self) -> Option<ExpressionKind> {
+        let unconstrained = if self.at_keyword(Keyword::Unconstrained) && self.next_is(Token::Pipe)
+        {
+            self.bump(); // consume 'unconstrained' if present
+            true
+        } else {
+            false
+        };
```
Comment (jfecher) [inline compiler/noirc_frontend/src/parser/parser/lambda.rs]:
```suggestion
        let unconstrained = self.next_is(Token::Pipe) && self.eat_keyword(Keyword::Unconstrained);
```

Comment (asterite) [reply compiler/noirc_frontend/src/parser/parser/lambda.rs]: Nice! Much simpler.
