### PR TITLE
fix: Clean error when attemping to return a slice from Brillig to ACIR

### LINKED ISSUE #2535: The type [u32]  cannot be represented in ACIR
### Aim

Given an array, the program tries to get another of length `y`.
```
use dep::std;
use dep::std::collections::vec::Vec;

global DEPTH: Field = 40000;
fn main(x: [u32; DEPTH], y: u32) {
    let mut new_x = Vec::new();
    new_x = clear(x, y);
}

unconstrained fn clear(x: [u32; DEPTH], y: u32) -> Vec<u32> { 
  let mut a = Vec::new();
  for i in 0..y{
    a.push(x[i]);
  }
  a
}
```

### Expected Behavior

Should have run successfully, to populate `new_x` with values 

### Bug

But when running it gives an error:
 _internal error: entered unreachable code: The type [u32]  cannot be represented in ACIR_

### To Reproduce

1.
2.
3.
4.

### Installation Method

None

### Nargo Version

_No response_

### Additional Context

_No response_

### Would you like to submit a PR for this Issue?

Yes

### Support Needs

_No response_

### PR DESCRIPTION
**Pull request by vezenovm**
# Description

## Problem\*

Resolves #2535 

## Summary\*

We currently panic when attempting to return a slice from an unconstrained runtime to an ACIR runtime. In some cases such as in the linked issue the panic is not very clear at all. 

New error:
Screenshot 2024-02-06 at 1 33 39 PM

## Documentation\*

Check one:
- [ ] No documentation needed.
- [ ] Documentation included in this PR.
- [ ] **[Exceptional Case]** Documentation to be submitted in a separate PR.

# PR Checklist\*

- [ ] I have tested the changes locally.
- [ ] I have formatted the changes with [Prettier](https://prettier.io/) and/or `cargo fmt` on default settings.

### CODE REVIEW

File: compiler/noirc_evaluator/src/errors.rs [hunk 1]
```diff
@@ -46,6 +46,8 @@ pub enum RuntimeError {
     NestedSlice { call_stack: CallStack },
     #[error("Big Integer modulus do no match")]
     BigIntModulus { call_stack: CallStack },
+    #[error("Slices cannot be return from an unconstrained runtime to a constrained runtime")]
```
Comment (TomAFrench) [inline compiler/noirc_evaluator/src/errors.rs:49]:
```suggestion
    #[error("Slices cannot be returned from an unconstrained runtime to a constrained runtime")]
```

**Review by TomAFrench — APPROVED** [review]

File: compiler/noirc_evaluator/src/errors.rs [hunk 2]
```diff
@@ -171,6 +174,17 @@ impl RuntimeError {
...
                 )
             }
+            RuntimeError::UnconstrainedSliceReturnToConstrained { .. } => {
+                let primary_message = self.to_string();
+                let location =
+                    self.call_stack().back().expect("Expected RuntimeError to have a location");
+
+                Diagnostic::simple_error(
+                    primary_message,
+                    "If attempting to return a `Vec` type, `Vec` contains a slice internally.".to_string(),
```
Comment (jfecher) [inline compiler/noirc_evaluator/src/errors.rs:184]: I'm not a fan of these hyper-specific taglines which might now apply to the actual cause of the error from the user. If we're not specifically checking for Vec, we shouldn't mention it in the error message imo. Otherwise it makes the message sound more confusing / imprecise.

Comment (vezenovm) [reply compiler/noirc_evaluator/src/errors.rs:184]: Yeah that is a fair point. I tried to mitigate with the language "If attempting". I did it this way as this issues an error when we do codegen on the call which isn't super clear about the return type itself. I figured if a user wrote a struct with a slice in it they would know, but for `Vec` they may be unsure as it is one of our stdlib types.
