### PR TITLE
fix: error when calling verify_proof_with_type in brillig

### LINKED ISSUE #9374: RecursiveAggregation silently succeeds as no-op in Brillig
### Aim

If someone attempts to use RecursiveAggregation (e.g., verify_proof) in Brillig it will look as though verification is always successful. Even for invalid proofs.

### Expected Behavior

We should have a clean error that we do not support recursive aggregation in `unconstrained` Noir (Brillig).

### Bug

The `RecursiveAggregation` opcode in Brillig is transformed into a no-op https://github.com/noir-lang/noir/blob/cb6b7e34ece13f2b99a0dc3d845b3254f8c20c5f/compiler/noirc_evaluator/src/brillig/brillig_gen/brillig_black_box.rs#L220

This is confusing for users who may be attempting to verify recursive proofs in unconstrained Noir (specifically in Aztec public contracts). A clear error is necessary to not cause confusion and we should panic if `RecursiveAggregation` ever reaches Brillig gen. 

Aztec's rollup tests still use Brillig to check for logical correctness. To add an error and keep those tests we probably will need to add a debug env var or compilation flag that keeps recursion as a no-op.

### To Reproduce

1. Run an unconstrained program with a call to `std::verify_proof`

### Workaround

None

### Workaround Description

_No response_

### Additional Context

_No response_

### Project Impact

Nice-to-have

### Blocker Context

_No response_

### Nargo Version

nargo version = 1.0.0-beta.9 noirc version = 1.0.0-beta.9+cceeec0d4f379632eae2f3228d2b8cefb07af7ee (git version hash: 472d432f4b8a78d97ab2e88a4c26c6fae963e94e, is dirty: false)

### NoirJS Version

_No response_

### Proving Backend Tooling & Version

_No response_

### Would you like to submit a PR for this Issue?

None

### Support Needs

_No response_

### LINKED ISSUE #11092: Unconstrained functions should disallow calls to `std::verify_proof_with_type`
We currently allow calls to `std::verify_proof_with_type` in an unconstrained context despite the fact that this is never meaningful. We should add a lint which emits an error if this function is called in an unconstrained context.

```noir
unconstrained fn main() {
    std::verify_proof_with_type([], [], [], 0, 0);
}
```

We can then update brillig-gen / brillig VM to mark this blackbox function as unreachable.

### PR DESCRIPTION
**Pull request by guipublic**
# Description

## Problem

Resolves #11092
Resolves #9374

## User Documentation

Check one:
- [X] No user documentation needed.
- [ ] Changes in _docs/_ included in this PR.
- [ ] **[For Experimental Features]** Changes in _docs/_ to be submitted in a separate PR.

# PR Checklist

- [X] I have tested the changes locally.
- [X] I have formatted the changes with [Prettier](https://prettier.io/) and/or `cargo fmt` on default settings.

### CODE REVIEW

File: compiler/noirc_frontend/src/elaborator/lints.rs [hunk 1]
```diff
@@ -291,6 +291,28 @@ pub(super) fn unconstrained_function_return(
...
+pub(super) fn error_if_verify_proof_with_type(
+    interner: &NodeInterner,
+    func_expr_id: ExprId,
+) -> Option<TypeCheckError> {
+    // Called function
+    let func_id = interner.lookup_function_from_expr(&func_expr_id)?;
+    let func_name = interner.function_name(&func_id);
+
+    // Check if it is verify_proof_with_type and is from the standard library
+    if func_name == "verify_proof_with_type" {
```
Comment (vezenovm) [inline compiler/noirc_frontend/src/elaborator/lints.rs:304]: We should check the builtin attribute rather than the function name and whether it is from the stdlib. We can fetch the function modifiers which contain a function's attributes. We can then rely on the separate checks we have that builtins can only be declared in the stdlib.

**Comment by vezenovm** [comment]
We should also add an unreachable for this opcode in Brillig gen https://github.com/noir-lang/noir/issues/9374.

File: compiler/noirc_frontend/src/elaborator/lints.rs (hunk 1 above)
Comment (guipublic) [reply compiler/noirc_frontend/src/elaborator/lints.rs:304]: `std::verify_proof_with_type()` does not have builtin attribute, it is a wrapper over the blackbox function.

Comment (TomAFrench) [reply compiler/noirc_frontend/src/elaborator/lints.rs:304]: Yeah, it's a bit unfortunate but the fact that the we have a wrapper function causes some headaches when it comes to diagnostics.

Comment (vezenovm) [reply compiler/noirc_frontend/src/elaborator/lints.rs:304]: Can we not then check against that black box attribute https://github.com/noir-lang/noir/blob/6e7a757eaf5da6313c99878da9b026e09957c213/noir_stdlib/src/lib.nr#L92 instead. `verify_proof_with_type` is just a wrapper.

Comment (TomAFrench) [reply compiler/noirc_frontend/src/elaborator/lints.rs:304]: The issue then is that the diagnostic gets shown in the stdlib rather than in user code iirc.

Comment (vezenovm) [reply compiler/noirc_frontend/src/elaborator/lints.rs:304]: > The issue then is that the diagnostic gets shown in the stdlib rather than in user code iirc.

There will still be a call stack to the origin of the call, but yeah I believe this would be the case

Comment (TomAFrench) [reply compiler/noirc_frontend/src/elaborator/lints.rs:304]: This review is currently blocking this PR btw.

Comment (vezenovm) [reply compiler/noirc_frontend/src/elaborator/lints.rs:304]: I approved, but I do feel it is still better to use the attribute as we are forced to add redundant stdlib checks here.

Comment (TomAFrench) [reply compiler/noirc_frontend/src/elaborator/lints.rs:304]: We can revisit in future to clean up how we handle compiler errors in the stdlib with wrappers but this should be enough for now.
