### PR TITLE
fix(SSA): disallow using `lt` with fields

### LINKED ISSUE #8571: ACIR vs Brillig: lt op
### Aim

The following SSA programs fails in ACIR and executes in Brillig 
```
fn main f0 {
  b0(v0: Field, v1: Field, v2: Field, v3: Field, v4: Field, v5: u1, v6: u1):
    v7 = lt v1, v2
    return v7
}
```

### Expected Behavior

Same results for brillig and acir execution

### Bug

Brillig compiled and successfully executed, but ACIR compilation failed. Execution result of brillig only 0. ACIR compilation failed with: RuntimeError("Compilation error RuntimeError(InternalError(General { message: \"Panic occurred: Panic: assertion failed: max_bits + 1 < F::max_num_bits() at compiler/noirc_evaluator/src/acir/acir_context/mod.rs:1295\", call_stack: [] }))")

### To Reproduce

1.
2.
3.
4.

### Workaround

None

### Workaround Description

_No response_

### Additional Context

_No response_

### Project Impact

None

### Blocker Context

_No response_

### Nargo Version

_No response_

### NoirJS Version

_No response_

### Proving Backend Tooling & Version

_No response_

### Would you like to submit a PR for this Issue?

None

### Support Needs

_No response_

### PR DESCRIPTION
**Pull request by asterite**
# Description

## Problem

Resolves #8571

## Documentation

Check one:
- [x] No documentation needed.
- [ ] Documentation included in this PR.
- [ ] **[For Experimental Features]** Documentation to be submitted in a separate PR.

# PR Checklist

- [x] I have tested the changes locally.
- [x] I have formatted the changes with [Prettier](https://prettier.io/) and/or `cargo fmt` on default settings.

### CODE REVIEW

**Review by jfecher — APPROVED** [review]
This was already disallowed in the frontend so it makes sense not to support it in SSA either

File: compiler/noirc_evaluator/src/ssa/ir/dfg.rs [hunk 1]
```diff
@@ -223,11 +224,23 @@ impl DataFlowGraph {
...
         id
     }
 
+    fn validate_instruction(&self, instruction: &Instruction) {
+        if let Instruction::Binary(Binary { lhs, rhs: _, operator: BinaryOp::Lt }) = instruction {
+            // Assume rhs_type is the same as lhs_type
+            let lhs_type = self.type_of_value(*lhs);
+            if matches!(lhs_type, Type::Numeric(NumericType::NativeField)) {
+                panic!("Cannot use `lt` with field elements");
+            }
```
Comment (aakoshh) [inline compiler/noirc_evaluator/src/ssa/ir/dfg.rs:240]: Could https://github.com/noir-lang/noir/blob/354c5aa6a432d28c0d62be6fc8114f1add09f44e/compiler/noirc_frontend/src/ast/expression.rs#L332 be of use?
