### PR TITLE
fix: do not check length for empty zst arrays in the interpreter

### LINKED ISSUE #11118: Length of ZST arrays differ
### Aim

Discovered while working on https://github.com/noir-lang/noir/pull/11104

Test `regression_10198` errors in the ssa interpreter when replacing its vector literals with `.as_vector()` calls:
```noir
fn main(index: u32) {
    let vector: [()] = [(), (), ()].as_vector();
    println(vector);

    let mut vector: [()] = [(), (), ()].as_vector();
    vector[index] = ();
    println(vector);
}
```
In the SSA we can see the culprit in the arrays that get created:
```
    v1 = make_array [] : [(); 3]
    v2 = make_array [] : [()]
    call f1(u1 1, u32 3, v2)
    v6 = make_array [] : [(); 3]
    v7 = make_array [] : [()]
    v8 = allocate -> &mut u32
    ...
```
`v1` and `v6` are the original arrays before they're converted to slices. They're each meant to have 3 `()` elements but both have 0 instead. The converted slices also have 0. Our check to filter out ZSTs is removing the array elements entirely.

This is only failing in the ssa interpreter and not normal execution because it is failing on a type-check of the array value. It seems the rest of our pipeline handles this ZST case otherwise.

```
Err(The value assigned to `v1` expects a type `[(); 3]` but it got assigned a value with type `[(); 0]` )
```
This example works with vector literals because the intermediate array values are no longer present and an empty slice has the same type as a slice of length three.

### Expected Behavior

ZST arrays should still type-check in the ssa interpreter

### Bug

ZST arrays do not type-check in the ssa interpreter

### To Reproduce

1.
2.
3.
4.

### Workaround

None

### Workaround Description

_No response_

### Additional Context

_No response_

### Project Impact

None

### Blocker Context

_No response_

### Nargo Version

_No response_

### NoirJS Version

_No response_

### Proving Backend Tooling & Version

_No response_

### Would you like to submit a PR for this Issue?

None

### Support Needs

_No response_

### PR DESCRIPTION
**Pull request by guipublic**
# Description

## Problem

Resolves #11118

## User Documentation

Check one:
- [X] No user documentation needed.
- [ ] Changes in _docs/_ included in this PR.
- [ ] **[For Experimental Features]** Changes in _docs/_ to be submitted in a separate PR.

# PR Checklist

- [X] I have tested the changes locally.
- [X] I have formatted the changes with [Prettier](https://prettier.io/) and/or `cargo fmt` on default settings.

### CODE REVIEW

File: compiler/noirc_evaluator/src/ssa/interpreter/tests/mod.rs [hunk 1]
```diff
@@ -1878,3 +1878,47 @@ fn call_stack_is_cleared_between_entry_calls() {
...
+    call print(v0, v1, v2, v21, u1 0)
+    return
+}
+    "#;
+    let ssa = Ssa::from_str(src).unwrap();
+    let input = from_constant(1u128.into(), NumericType::unsigned(32));
+    let result = ssa.interpret(vec![input]);
+    // v2 matches type [(); 3] in the interpreter because it is an empty ZST array.
+    assert!(result.is_ok());
+}
```
Comment (aakoshh) [inline compiler/noirc_evaluator/src/ssa/interpreter/tests/mod.rs:1896]: On `master` I think I am able to replicate the error with the following test:
```rust
#[test]
fn allow_empty_zst_array() {
    let src = r#"
acir(inline) fn main f0 {
  b0():
    v0 = make_array [] : [(); 3]
    return
}
    "#;
    let ssa = Ssa::from_str(src).unwrap();
    let _ = ssa.interpret(vec![]).unwrap();
}
```

I'd recommend that we keep these unit tests to a minimum that needs to happen to show what should work, and we put the regression involving prints and all into the `execution_success` integration/regression tests, which verify that the stdout is correct and matches across all environments.

Comment (guipublic) [reply compiler/noirc_evaluator/src/ssa/interpreter/tests/mod.rs:1896]: In general I try to keep the same code as in the issue for a regression test, but I fine with this simpler one.
Done.
