### PR TITLE
fix(frontend)!: Restrict numeric generic types to unsigned ints up to `u32`

### LINKED ISSUE #5571: Expand Type::Constant to support larger bit sizes and signed integers
### Aim

Our type-level integer is currently too restrictive with the addition of explicit numeric generics. They currently are only supported as [`u32` values ](https://github.com/noir-lang/noir/blob/4e2c08d545178a3b495e0acaaad9f8c51f5d3418/compiler/noirc_frontend/src/hir_def/types.rs#L105). 

### Expected Behavior

We should be able to support types larger than `u32` for numeric generics as well as signed integers. 

### Bug

Different bugs can come about. One was found here (https://github.com/noir-lang/noir/issues/5552) and other unexpected behavior can occur if a value larger than a `u32` is used in a numeric generic.
e.g. the following will panic:
```rust
    fn big<let N: u64>() -> u64 {
        N
    }

    fn main() {
        let _ = big::<18446744073709551615>();
    }
```

### To Reproduce

1. Run the following snippet with `nargo compile` and see the failure

### Project Impact

Nice-to-have

### Impact Context

In between a nice-to-have and a blocker for full numeric generics.

### Workaround

None

### Workaround Description

_No response_

### Additional Context

_No response_

### Installation Method

Compiled from source

### Nargo Version

0.32.0+8897de81c088983d8c1f5a2c610c19301f0bdded

### NoirJS Version

_No response_

### Would you like to submit a PR for this Issue?

None

### Support Needs

_No response_

### PR DESCRIPTION
**Pull request by vezenovm**
# Description

## Problem\*

Resolves #5571 

The issue references expanding the supported type-level integers, however, after a team discussion we decided to simply restrict the supported numeric generics. If other kinds of numeric generics become highly requested we can then re-assess whether we want to expand support for type level constants.

## Summary\*

A new parser combinator for numeric generics was introduced to differentiate with the existing `type_expression` combinator. This is due to usage of `or_not` in the `generic_type_args` parser. Due to the `or_not` combinator the expression error was being ignored. Thus, the new numeric generic expression combinator returns an optional expression along with its parsed type.

## Additional Context

This program:
```rust
    fn big<let N: u64>() -> u64 {
        N
    }

    fn main() {
        let _ = big::<18446744073709551615>();
    }
```
gives the following error:
Screenshot 2024-07-23 at 12 18 00 PM

The previous errors were very unclear:
Screenshot 2024-07-22 at 5 59 04 PM

## Documentation\*

Check one:
- [ ] No documentation needed.
- [ ] Documentation included in this PR.
- [X] **[For Experimental Features]** Documentation to be submitted in a separate PR.

# PR Checklist\*

- [X] I have tested the changes locally.
- [X] I have formatted the changes with [Prettier](https://prettier.io/) and/or `cargo fmt` on default settings.

### CODE REVIEW

File: compiler/noirc_frontend/src/parser/parser/types.rs [hunk 1]
```diff
@@ -201,8 +203,16 @@ pub(super) fn generic_type_args<'a>(
         // separator afterward. Failing early here ensures we try the `type_expression`
         // parser afterward.
         .then_ignore(one_of([Token::Comma, Token::Greater]).rewind())
-        .or(type_expression()
-            .map_with_span(|expr, span| UnresolvedTypeData::Expression(expr).with_span(span)))
+        .or(numeric_generic_type_expression().validate(|(type_arg, err_expr), span, emit| {
+            if let UnresolvedTypeData::Error = type_arg.typ {
+                let err_expr = err_expr.expect("Error expression is expected with an error type");
```
Comment (jfecher) [inline compiler/noirc_frontend/src/parser/parser/types.rs:208]:
```suggestion
            if let Some(err_expr) = err_expr {
```
I'm also not really a fan of the 2 step verification of map_with_span in `numeric_generic_type_expression` and the `validate` here. It'd be simpler if we just did it all here I think - it also gets rid of the "returning a tuple instead of an enum on error" pattern.

File: compiler/noirc_frontend/src/parser/parser/types.rs [hunk 2]
```diff
@@ -235,6 +245,23 @@ pub(super) fn slice_type(
...
+        match expr {
+            Ok(type_expression) => {
+                (UnresolvedTypeData::Expression(type_expression).with_span(span), None)
+            }
+            Err(err_expr) => (UnresolvedType::error(span), Some(err_expr)),
+        }
+    })
+}
+
+fn type_expression_inner() -> impl NoirParser<Expression> {
```
Comment (jfecher) [inline compiler/noirc_frontend/src/parser/parser/types.rs:264]: Why are we splitting out type expressions from numeric generic type expressions? When would a type expression not be from a numeric generic? We should treat all instances of these the same, including in array and string types where this is still used.

File: compiler/noirc_frontend/src/parser/parser/types.rs [hunk 3]
```diff
@@ -235,6 +245,23 @@ pub(super) fn slice_type(
 }
 
 pub(super) fn type_expression() -> impl NoirParser<UnresolvedTypeExpression> {
+    type_expression_inner().try_map(UnresolvedTypeExpression::from_expr)
+}
```
Comment (jfecher) [inline compiler/noirc_frontend/src/parser/parser/types.rs:249]: Can you remove the `pub(super)` on these functions? They were here before but I just looked and we don't actually use these outside this file.

**Review by jfecher — CHANGES_REQUESTED** [review]

File: compiler/noirc_frontend/src/parser/parser/types.rs (hunk 2 above)
Comment (vezenovm) [reply compiler/noirc_frontend/src/parser/parser/types.rs:264]: > A new parser combinator for numeric generics was introduced to differentiate with the existing type_expression combinator. This is due to usage of or_not in the generic_type_args parser. Due to the or_not combinator the expression error was being ignored. 

From the PR description

File: compiler/noirc_frontend/src/parser/parser/types.rs (hunk 3 above)
Comment (vezenovm) [reply compiler/noirc_frontend/src/parser/parser/types.rs:240]: done

File: compiler/noirc_frontend/src/parser/parser/types.rs (hunk 2 above)
Comment (vezenovm) [reply compiler/noirc_frontend/src/parser/parser/types.rs:259]: I renamed to `type_expression_validated` to make this more clear that we want to emit a parser error and not halt the parser in the case of a bad type expression.

Comment (jfecher) [reply compiler/noirc_frontend/src/parser/parser/types.rs:259]: Wouldn't we still want to use the same parser for here and array/string types though?

**Review by jfecher — APPROVED** [review]
:+1:

File: compiler/noirc_frontend/src/parser/parser/types.rs (hunk 2 above)
Comment (vezenovm) [reply compiler/noirc_frontend/src/parser/parser/types.rs:257]: Confused what you mean? We are using the same parser internally?

Comment (jfecher) [reply compiler/noirc_frontend/src/parser/parser/types.rs:257]: I was wondering why they didn't both use `type_expression_validated` since they used to call the same `type_expression()` function originally but it is not that important

Comment (vezenovm) [reply compiler/noirc_frontend/src/parser/parser/types.rs:257]: I just didn't want this change to leak into the other parsers that are fine with the parsing halting and do not use `or_not`. I can experiment with using `type_expression_validated` with the array/string types.
