### PR TITLE
fix: check for signed division overflow

### LINKED ISSUE #9847: ACIR vs Brillig: Brillig failed with Attempt to divide with overflow on signed integer divison
### Aim

The following Noir code 
```noir
fn main(v0: i8, v1: u1, v2: i8) -> pub u32 {
  let v14 = v2 / v0;
  let v15 = v2 / v14;
  v1 as u32
}
```
With 
```toml
"v0" = 81
"v1" = 0
"v2" = "-128"
```

Solved in acir and failed in brillig. It fails on nightly version and does not fail on nargo version = 1.0.0-beta.12

### Expected Behavior

Brillig solved 

### `nargo execute`
[nargo_tests] Circuit output: 0
### `nargo execute --force-brillig`
```
error: Assertion failed: Attempt to divide with overflow
  ┌─ src/main.nr:3:13
  │
3 │   let v15 = v2 / v14;
  │             --------
  │
  = Call stack:
    1. src/main.nr:3:13

Failed assertion
```

### To Reproduce

1.
2.
3.
4.

### Workaround

None

### Workaround Description

_No response_

### Additional Context

_No response_

### Project Impact

None

### Blocker Context

_No response_

### Nargo Version

_No response_

### NoirJS Version

_No response_

### Proving Backend Tooling & Version

_No response_

### Would you like to submit a PR for this Issue?

None

### Support Needs

_No response_

### PR DESCRIPTION
**Pull request by guipublic**
# Description

## Problem\*

Resolves #9847

## Summary\*
check for overflow during signed division

## Documentation\*

Check one:
- [X] No documentation needed.
- [ ] Documentation included in this PR.
- [ ] **[For Experimental Features]** Documentation to be submitted in a separate PR.

# PR Checklist\*

- [X] I have tested the changes locally.
- [X] I have formatted the changes with [Prettier](https://prettier.io/) and/or `cargo fmt` on default settings.

### CODE REVIEW

File: compiler/noirc_evaluator/src/acir/acir_context/mod.rs [hunk 1]
```diff
@@ -1169,6 +1169,17 @@ impl<F: AcirField, B: BlackBoxFunctionSolver<F>> AcirContext<F, B> {
...
 
+        // Issue #9847 - The quotient must be a valid signed integer.
+        // For instance -128/-1 = 128, but 128 is not a valid i8
+        // Because it is the only possible overflow that can happen due to signed representation,
+        // we simply check for this case: quotient is negative, or distinct from 2^{bit_size-1}
+        let assert_message =
+            self.generate_assertion_message_payload("Attempt to divide with overflow".to_string());
+        let unsigned = self.not_var(q_sign, AcirType::unsigned(1))?;
+        // We just use `unsigned` for the predicate of assert_neq_var because if the `predicate` is false, the quotient
+        // we get from the unsigned division under the predicate will not be 2^{bit_size-1 anyways.
```
Comment (vezenovm) [inline compiler/noirc_evaluator/src/acir/acir_context/mod.rs]:
```suggestion
        // we get from the unsigned division under the predicate will not be 2^{bit_size-1} anyways.
```

File: compiler/noirc_evaluator/src/acir/acir_context/mod.rs [hunk 2]
```diff
@@ -1169,6 +1169,17 @@ impl<F: AcirField, B: BlackBoxFunctionSolver<F>> AcirContext<F, B> {
         let r_is_not_0 = self.not_var(r_is_0, AcirType::unsigned(1))?;
         let remainder = self.mul_var(remainder, r_is_not_0)?;
 
+        // Issue #9847 - The quotient must be a valid signed integer.
+        // For instance -128/-1 = 128, but 128 is not a valid i8
+        // Because it is the only possible overflow that can happen due to signed representation,
+        // we simply check for this case: quotient is negative, or distinct from 2^{bit_size-1}
```
Comment (vezenovm) [inline compiler/noirc_evaluator/src/acir/acir_context/mod.rs:1175]: maybe we can add a brief comment that it is assumed any signed integer smaller than `-2^{bit_size - 1}` will have been rejected as a value for that type.

File: compiler/noirc_evaluator/src/acir/acir_context/mod.rs (hunk 1 above)
Comment (guipublic) [reply compiler/noirc_evaluator/src/acir/acir_context/mod.rs]: Done

File: compiler/noirc_evaluator/src/acir/acir_context/mod.rs (hunk 2 above)
Comment (guipublic) [reply compiler/noirc_evaluator/src/acir/acir_context/mod.rs:1175]: I added a small comment

File: compiler/noirc_evaluator/src/acir/acir_context/mod.rs [hunk 3]
```diff
@@ -1169,6 +1169,18 @@ impl<F: AcirField, B: BlackBoxFunctionSolver<F>> AcirContext<F, B> {
         let r_is_not_0 = self.not_var(r_is_0, AcirType::unsigned(1))?;
         let remainder = self.mul_var(remainder, r_is_not_0)?;
 
+        // Issue #9847 - The quotient must be a valid signed integer.
```
Comment (vezenovm) [inline compiler/noirc_evaluator/src/acir/acir_context/mod.rs]: This is a very minor nit, but I think it would better if the issue was linked as part of the test instead, with a link to Github itself not just the issue number. I thought I left this comment with the original review but I must have accidentally deleted it.

**Review by vezenovm — APPROVED** [review]

File: compiler/noirc_evaluator/src/acir/acir_context/mod.rs (hunk 3 above)
Comment (TomAFrench) [reply compiler/noirc_evaluator/src/acir/acir_context/mod.rs]: Definitely agree that we should be linking rather than posting just the numbers for ease of whoever reads this code in future.

Comment (guipublic) [reply compiler/noirc_evaluator/src/acir/acir_context/mod.rs]: Done
