### PR TITLE
fix: Fix nargo not showing compiler errors or warnings

### LINKED ISSUE #1645: "Failed to compile circuit" and no errors shown when compiling code with any errors or warnings
### Aim

Tried to run `nargo prove --experimental-ssa` on the code
```rs
fn main() -> pub u32 {
    let x = foo();
    bar(x).1
}

fn foo(){}

fn bar<T>(x: T, y: u32, z: (u32, T)) -> (T, u32) {
    (x, y + z.0)
}
```

### Expected Behavior

Expected the code to compile and prove

### Bug

The compiler errors with the only output being
```
Error: Failed to compile circuit

Location:
    crates/nargo_cli/src/cli/mod.rs:72:5
exit 1
```

### PR DESCRIPTION
**Pull request by jfecher**
# Description

## Problem\*

Fixes an issue where if there are any compiler errors or warnings Nargo would map them into a CompilationError without reporting them first, leading to no errors being reported.

Resolves #1645

## Documentation

- [ ] This PR requires documentation updates when merged.

  

  - [ ] I will submit a noir-lang/docs PR.

  

  - [ ] I will request for and support Dev Rel's help in documenting this PR.

  
  

## Additional Context

# PR Checklist\*

- [x] I have tested the changes locally.
- [x] I have formatted the changes with [Prettier](https://prettier.io/) and/or `cargo fmt` on default settings.

### CODE REVIEW

File: crates/nargo_cli/src/cli/compile_cmd.rs [hunk 1]
```diff
@@ -49,9 +50,11 @@ pub(crate) fn run<B: Backend>(
     // If contracts is set we're compiling every function in a 'contract' rather than just 'main'.
     if args.contracts {
         let mut driver = setup_driver(backend, &config.program_dir)?;
-        let compiled_contracts = driver
-            .compile_contracts(&args.compile_options)
-            .map_err(|_| CliError::CompilationError)?;
+        let compiled_contracts =
+            driver.compile_contracts(&args.compile_options).map_err(|errors| {
+                reporter::report_all(driver.file_manager(), &errors, false);
```
Comment (phated) [inline crates/nargo_cli/src/cli/compile_cmd.rs:55]: In the check command, we need to do 
```rs
let error_count = reporter::report_all(file_manager, &errs, compile_options.deny_warnings);
if error_count != 0 {
        reporter::finish_report(error_count);
        return Err(CliError::CompilationError);
}
```
I'm guessing the same will need to be done here?

**Review by phated — CHANGES_REQUESTED** [review]
Question about the `finish_report` and checking error_cound

File: crates/nargo_cli/src/cli/compile_cmd.rs (hunk 1 above)
Comment (jfecher) [reply crates/nargo_cli/src/cli/compile_cmd.rs:55]: Right. I'm also realizing that this PR does not fix the case where we abort compilation if there were warnings but no errors. I'll add a commit to fix this as well.

Comment (phated) [reply crates/nargo_cli/src/cli/compile_cmd.rs:55]: Yeah, the driver code is extremely gnarly since we can return success + warnings and error + warnings.

Comment (jfecher) [reply crates/nargo_cli/src/cli/compile_cmd.rs]: Ok, I've pushed the slightly larger rework to avoid failing when only warnings are issued.

Instead of `(Option<T>, Vec<FileDiagnostic>)` I opted to go with `Result<(T, Vec<FileDiagnostic>), Vec<FileDiagnostic>>` where we return `(T, warnings)` on success, and on error the file diagnostic list will contain errors as well. To make it a bit easier to read I've added some type alises: `Result<(T, Warnings), ErrorsAndWarnings>`.

File: crates/noirc_driver/src/lib.rs [hunk 2]
```diff
@@ -169,18 +166,46 @@ impl Driver {
...
+        result: Result<(T, Warnings), ErrorsAndWarnings>,
+        deny_warnings: bool,
+    ) -> Result<T, ReportedErrors> {
+        let (t, warnings) = result.map_err(|errors| {
+            noirc_errors::reporter::report_all(self.file_manager(), &errors, deny_warnings)
+        })?;
+
+        noirc_errors::reporter::report_all(self.file_manager(), &warnings, deny_warnings);
+        Ok(t)
+    }
```
Comment (phated) [inline crates/noirc_driver/src/lib.rs:207]: We'll want this inside of nargo_cli, as this should be pure from stdout/stderr stuff. We can add it as a utility over there.

**Review by phated — APPROVED** [review]
This looks great 😄

**Review by joss-aztec — APPROVED** [review]
LGTM
