### PR TITLE
fix: unify macro call type with actual type in comptime blocks

### LINKED ISSUE #11409: Generic not found after unquote, inside comptime block
### Aim

In this code:

```noir
struct Foo<let N: u32> {}

impl<let N: u32> Foo<N> {
    fn len(self) -> u32 {
        N
    }
}

fn main() {
    comptime {
        let foo: Foo<_> = unquote!(quote { Foo::<10> {} });
        println(foo.len())
    }
}
```

we get:

```
error: Type annotation needed
   ┌─ src/main.nr:28:17
   │
28 │         println(foo.len())
   │                 ------- Could not determine the value of the generic argument `N` declared on the struct `Foo`
   │

error: Invalid numeric generic
   ┌─ src/main.nr:21:9
   │
21 │         N
   │         - Expected a constant, but found `_`
```

However, outside a comptime code it works fine:

```noir
use std::meta::unquote;

struct Foo<let N: u32> {}

impl<let N: u32> Foo<N> {
    fn len(_self: Self) -> u32 {
        N
    }
}

fn main() {
    let foo: Foo<_> = unquote!(quote { Foo::<10> {} });
    println(foo.len());
}
```

### Expected Behavior

It should compile.

### Bug

For some reason `N` can't be solved, even though it should be known after unifying the result of `unquote` with the variable.

### To Reproduce

1.
2.
3.
4.

### Workaround

None

### Workaround Description

_No response_

### Additional Context

_No response_

### Project Impact

None

### Blocker Context

_No response_

### Nargo Version

_No response_

### NoirJS Version

_No response_

### Proving Backend Tooling & Version

_No response_

### Would you like to submit a PR for this Issue?

None

### Support Needs

_No response_

### PR DESCRIPTION
**Pull request by asterite**
# Description

## Problem

Resolves #11409

## Summary

This is a follow-up to #6105

#6105 is good but because we don't unify types, some type variables end up unbound. That's why #11409 was failing.

The solution here is:
- To unify the types
- We store the bindings that resulted from that unification. We associate those to the macro expression (an ExprId)
- If we bump into that macro expression again, we first undo those bindings

This allows a variable to change types across macro loop iterations.

For this I also had to relax the checking of unbound generics when a function context is popped, only in comptime code. The reason is that in the new test here, in `foo.len()` we end up with `foo` without a known `N`, but it's fine because it's that `N` that we want to infer later on. In this case, if `N` ends up being used when interpreting the block and it's not bound, we'll get an error anyway.

## User Documentation

Check one:
- [x] No user documentation needed.
- [ ] Changes in _docs/_ included in this PR.
- [ ] **[For Experimental Features]** Changes in _docs/_ to be submitted in a separate PR.

# PR Checklist

- [x] I have tested the changes locally.
- [x] I have formatted the changes with [Prettier](https://prettier.io/) and/or `cargo fmt` on default settings.

### CODE REVIEW

File: compiler/noirc_frontend/src/elaborator/function_context.rs [hunk 1]
```diff
@@ -87,13 +87,23 @@ impl Elaborator<'_> {
...
         typ: Type,
         kind: BindableTypeVariableKind,
         location: Location,
     ) {
+        if self.in_comptime_context() {
+            return;
+        }
+
         let var = RequiredTypeVariable { type_variable_id, typ, kind, location };
         self.get_function_context_mut().required_type_variables.push(var);
```
Comment (jfecher) [inline compiler/noirc_frontend/src/elaborator/function_context.rs]:
```suggestion
        if !self.in_comptime_context() {
            let var = RequiredTypeVariable { type_variable_id, typ, kind, location };
            self.get_function_context_mut().required_type_variables.push(var);
        }
```

File: compiler/noirc_frontend/src/elaborator/function_context.rs [hunk 2]
```diff
@@ -87,13 +87,23 @@ impl Elaborator<'_> {
 
     /// Push a type variable (its ID and type) as a required type variable: it must be
     /// bound after type-checking the current function.
+    ///
+    /// The type variable is only pushed if the elaborator is not in a comptime context.
+    /// The reason is that in a comptime context the type of a variable might change
+    /// across a loop's iterations, so a type can temporarily remain as `Type<_>` where
+    /// `_` is bound by the interpreter evaluating an expression's type being unified with
+    /// that type.
```
Comment (jfecher) [inline compiler/noirc_frontend/src/elaborator/function_context.rs:95]: Does this open us up to regular unbound type variables though? E.g. the case this was meant to originally catch may no longer be caught in comptime code?

File: compiler/noirc_frontend/src/hir/comptime/interpreter.rs [hunk 3]
```diff
@@ -1163,7 +1163,36 @@ impl<'local, 'interner> Interpreter<'local, 'interner> {
...
+                                .macro_call_expression_bindings
+                                .insert(id, bindings.clone());
+                            Type::apply_type_bindings(bindings);
+                        }
+                        Err(UnificationError) => {
+                            let error = TypeCheckError::TypeMismatch {
+                                expected_typ: expected_type.to_string(),
+                                expr_typ: actual_type.to_string(),
+                                expr_location: location,
+                            };
```
Comment (jfecher) [inline compiler/noirc_frontend/src/hir/comptime/interpreter.rs]: Can you factor out all or some of this code? It makes `elaborate_call` longer and more difficult to understand by getting very involved in a corner case.

File: compiler/noirc_frontend/src/elaborator/function_context.rs (hunk 2 above)
Comment (asterite) [reply compiler/noirc_frontend/src/elaborator/function_context.rs:95]: I think not. For example this code:

```noir
struct Foo<let N: u32> {}

impl<let N: u32> Foo<N> {
    fn len(_self: Self) -> u32 {
        N
    }
}

fn main() {
    comptime {
        let foo: Foo<_> = std::meta::unquote!(quote { Foo {} });
        println(foo.len())
    }
}
```

correctly errors in `Foo { }` saying "Could not determine the value of the generic argument `N` declared on the struct `Foo`".

Also, I remember adding the `push_required_type_variable` logic to improve the error message we get when an unbound type variable is used later on. In monomorphization it would say that a type variable is unbound but I can't remember if the location was not clear or what that type var belonged to wasn't clear. So us not doing that here would, in a worse case scenario, just lead to a bit worse error messages.

File: compiler/noirc_frontend/src/elaborator/function_context.rs (hunk 1 above)
Comment (asterite) [reply compiler/noirc_frontend/src/elaborator/function_context.rs]: Done!

File: compiler/noirc_frontend/src/hir/comptime/interpreter.rs (hunk 3 above)
Comment (asterite) [reply compiler/noirc_frontend/src/hir/comptime/interpreter.rs]: Done!
