### PR TITLE
fix: avoid duplicating constant arrays

### LINKED ISSUE #5286: Constant arrays are duplicated
### Problem

In the following snippet, the `tableY` array is duplicated for every read done in the loop `0..6`:

```
struct ScalarField {
    base4_slices: [u8; 63]
}

impl ScalarField {
    fn new() -> Self {
        Self { base4_slices: [0; 63] }
    }
    fn from_field(x: Field) -> Self {
        let bytes: [u8] = x.to_le_radix(4, 63);
        let mut result: Self = ScalarField { base4_slices: [0; 63] };
        for i in 0..63 {
            result.base4_slices[i] = bytes[62 - i];
        }
        result
    }
    fn get(self, idx: u64) -> u8 {
        self.base4_slices[idx]
    }
}

fn mul(scalar: ScalarField) -> Field {
    let mut tableY: [Field; 8] = [0; 8];
    for i in 0..8 {
        tableY[i] = i as Field;
    }
    let mut foo = 0;
    for i in 0..6 {
        let idx: u64 = scalar.get(i) as u64;
        foo += tableY[idx];
    }
    foo
}

fn main(x: Field) -> pub Field {
    let scalar = ScalarField::from_field(x);
    mul(scalar)
}
```

This generates multiple MemoryInit on ACIR side while we could use only one.

### Happy Case

Array is not duplicated

### Project Impact

None

### Impact Context

_No response_

### Workaround

None

### Workaround Description

_No response_

### Additional Context

_No response_

### Would you like to submit a PR for this Issue?

Yes

### Support Needs

_No response_

### PR DESCRIPTION
**Pull request by guipublic**
# Description

## Problem\*

Resolves #5286 

## Summary\*
Keep track of constant arrays and the array they resolve to in mem2reg, so that another constant array is not created for the same array.

## Documentation\*

Check one:
- [X] No documentation needed.
- [ ] Documentation included in this PR.
- [ ] **[For Experimental Features]** Documentation to be submitted in a separate PR.

# PR Checklist\*

- [X] I have tested the changes locally.
- [X] I have formatted the changes with [Prettier](https://prettier.io/) and/or `cargo fmt` on default settings.

### CODE REVIEW

**Review by TomAFrench — APPROVED** [review]
LGTM

File: compiler/noirc_evaluator/src/ssa/ir/function_inserter.rs [hunk 1]
```diff
@@ -34,10 +35,17 @@ impl<'f> FunctionInserter<'f> {
...
                     let array = array.clone();
                     let typ = typ.clone();
-                    let new_array = array.iter().map(|id| self.resolve(*id)).collect();
-                    let new_id = self.function.dfg.make_array(new_array, typ);
-                    self.values.insert(value, new_id);
-                    new_id
+                    let new_array: im::Vector<ValueId> =
+                        array.iter().map(|id| self.resolve(*id)).collect();
+                    if self.const_arrays.get(&new_array) == Some(&value) {
+                        value
```
Comment (jfecher) [inline compiler/noirc_evaluator/src/ssa/ir/function_inserter.rs:41]: Shouldn't this be `if let Some(value) = self.const_arrays.get(&new_array) {`?
As it is we're only checking if the value in the map exactly matches the original resolved array value. That'd work for when we have one existing array that resolves multiple times but it wouldn't catch the case when we have two identical arrays with different IDs to begin with.

Comment (guipublic) [reply compiler/noirc_evaluator/src/ssa/ir/function_inserter.rs:41]: Indeed, and this is intentional. If it is the same original value, then it is fine to use the same array.

Comment (jfecher) [reply compiler/noirc_evaluator/src/ssa/ir/function_inserter.rs:41]: Wouldn't we rather use the value stored in the map though? To deduplicate more arrays

Comment (jfecher) [reply compiler/noirc_evaluator/src/ssa/ir/function_inserter.rs:41]: It should be correct since arrays are immutable. Maybe it was failing in brillig where arrays are copy-on-write. I suppose it's not important enough to be worth investigating.
