### PR TITLE
fix: Fix assignment when both `mut` and `&mut` are used

### LINKED ISSUE #2255: Wrong SSA generated for mutable parameters of type MutableReference
### Aim

The following code should set `x` to 100 and the assert should pass. However, x's value remains unchanged.
This only happens if the a parameter of become_100 is declared as mutable.

```
fn become_100(mut a: &mut u32) {
    *a = 100;
}

fn main() {
    let mut x: u32 = 50;
    become_100(&mut x);
    assert(x == 100);
}
```

### Expected Behavior

Assert should pass

### Bug

SSA generated if the parameter is declared as mutable (incorrect):
```
acir fn become_100 f1 {
  b0(v0: reference):
    v1 = allocate
    store v0 at v1
    store u32 100 at v1
    return
}
```

SSA if the parameter is immutable (correct)
```
acir fn become_100 f1 {
  b0(v0: reference):
    store u32 100 at v0
    return
}
```

### To Reproduce

1.
2.
3.
4.

### Installation Method

Compiled from source

### Nargo Version

_No response_

### Additional Context

_No response_

### Would you like to submit a PR for this Issue?

No

### Support Needs

_No response_

### PR DESCRIPTION
**Pull request by jfecher**
# Description

## Problem\*

The use of `self.dereference` when handling lvalues could lead to a double dereference in one step since `self.dereference` calls `value.eval()` before dereferencing, which automatically dereferences `mut`able values. I've separated out a new `dereference_lvalue` function to avoid this.

Resolves #2255

## Documentation

- [ ] This PR requires documentation updates when merged.

  

  - [ ] I will submit a noir-lang/docs PR.

  

  - [ ] I will request for and support Dev Rel's help in documenting this PR.

  
  

## Additional Context

# PR Checklist\*

- [x] I have tested the changes locally.
- [x] I have formatted the changes with [Prettier](https://prettier.io/) and/or `cargo fmt` on default settings.

### CODE REVIEW

File: crates/noirc_evaluator/src/ssa/ssa_gen/context.rs [hunk 1]
```diff
@@ -537,7 +537,14 @@ impl<'a> FunctionContext<'a> {
...
         match lvalue {
-            ast::LValue::Ident(ident) => LValue::Ident(self.ident_lvalue(ident)),
+            ast::LValue::Ident(ident) => {
+                let (reference, should_auto_deref) = self.ident_lvalue(ident);
+                if should_auto_deref {
+                    LValue::Dereference { reference }
+                } else {
+                    LValue::Ident
+                }
+            }
```
Comment (jfecher) [inline crates/noirc_evaluator/src/ssa/ssa_gen/context.rs:547]: Instead of having both identifiers and dereferences being possibly assigned to, I thought it was simple to always only assign to LValue::Dereferences. Note that in the case of e.g. `let x = &mut 0`, the identifier `x` itself is not mutable, so the reverse of always only assigning to identifiers is not possible.

File: crates/noirc_evaluator/src/ssa/ssa_gen/context.rs [hunk 2]
```diff
@@ -614,7 +627,7 @@ impl<'a> FunctionContext<'a> {
     /// `extract_current_value` for more details.
     pub(super) fn assign_new_value(&mut self, lvalue: LValue, new_value: Values) {
         match lvalue {
-            LValue::Ident(references) => self.assign(references, new_value),
+            LValue::Ident => unreachable!("Cannot assign to a variable without a reference"),
```
Comment (jfecher) [inline crates/noirc_evaluator/src/ssa/ssa_gen/context.rs:630]: This is possible now because mutable variables return a `LValue::Dereference` instead

**Review by kevaundray — APPROVED** [review]
