### PR TITLE
fix: prevent infinite recursion checks in many cases

### LINKED ISSUE #11447: Mutually recursive structs crash the compiler
### Aim

This code:

```noir
struct Foo {
    bar: Bar,
}

struct Bar {
    foo: Foo,
}
```

when doing `nargo check`, leads to:

```
thread '<unknown>' has overflowed its stack
fatal runtime error: stack overflow
```

### Expected Behavior

I think it should say that the types form a cycle. I feel that this is how it used to work in the past and maybe at one point it broke? In any case the compiler shouldn't crash.

### Bug

The compiler crashes.

### To Reproduce

1.
2.
3.
4.

### Workaround

None

### Workaround Description

_No response_

### Additional Context

_No response_

### Project Impact

None

### Blocker Context

_No response_

### Nargo Version

_No response_

### NoirJS Version

_No response_

### Proving Backend Tooling & Version

_No response_

### Would you like to submit a PR for this Issue?

None

### Support Needs

_No response_

### PR DESCRIPTION
**Pull request by asterite**
# Description

## Problem

Resolves #11447

## Additional Context

I'm not sure if this is the best way. Another way could have been a recursion limit, but I think this might be better as it's more accurate.

## User Documentation

Check one:
- [x] No user documentation needed.
- [ ] Changes in _docs/_ included in this PR.
- [ ] **[For Experimental Features]** Changes in _docs/_ to be submitted in a separate PR.

# PR Checklist

- [x] I have tested the changes locally.
- [x] I have formatted the changes with [Prettier](https://prettier.io/) and/or `cargo fmt` on default settings.

### CODE REVIEW

File: compiler/noirc_frontend/src/elaborator/lints.rs [hunk 1]
```diff
@@ -157,27 +157,42 @@ pub(super) fn oracle_returns_multiple_vectors(
         return None;
     }
 
-    fn vector_count(typ: &Type) -> usize {
+    fn vector_count(
+        typ: &Type,
+        seen_data_types: &mut rustc_hash::FxHashSet<(TypeId, Vec<Type>)>,
```
Comment (jfecher) [inline compiler/noirc_frontend/src/elaborator/lints.rs]: Can you import this type?

**Review by jfecher — APPROVED** [review]
I wish we could have a helper for this, e.g. some traversal method but it is non-trivial for trees and all the different cases we have.

File: compiler/noirc_frontend/src/elaborator/lints.rs (hunk 1 above)
Comment (asterite) [reply compiler/noirc_frontend/src/elaborator/lints.rs]: I ended up adding a type alias.

File: compiler/noirc_frontend/src/elaborator/lints.rs [hunk 2]
```diff
@@ -157,27 +157,39 @@ pub(super) fn oracle_returns_multiple_vectors(
...
+                            .map(|typ| vector_count(typ, seen_data_types))
+                            .sum()
+                    } else {
+                        0
+                    }
                 } else {
+                    // If we bump into a recursive type, we stop counting.
+                    // "zero" isn't strictly correct here, but the recursive type will be an error
+                    // already so this count won't matter in the end.
                     0
```
Comment (aakoshh) [inline compiler/noirc_frontend/src/elaborator/lints.rs:185]: What happens if we have a type like this, returned from the oracle:
```noir
struct Foo { a: [u32] }
struct Bar { b: Foo, c: Foo }

#[oracle(bar)]
unconstrained fn bar() -> Bar {}
```

Looking at the way `seen_data_types: &mut SeenDataTypes` is used, my expectation would be:
* `vector_count(Bar)`:
  * `b` -> `vector_count(Foo)`:
    * `a` -> `vector_count(Vec<u32>)`:
      * `1 + vector_count(u32)`
  * `c` -> `vector_count(Foo)`:
    * `0` because `Foo` was already seen once

The result is that we think `Bar` contains 1 vector, and we don't reject the oracle.

Comment (aakoshh) [reply compiler/noirc_frontend/src/elaborator/lints.rs:185]: I would change `SeenDataTypes` like this:

```rust
#[derive(Clone)]
struct TypeRecursionContext {
  depth: u32, 
  seen_data_types: im::HashSet<(TypeId, Vec<Type>)>
}

impl TypeRecursionContext {
  fn recur(mut self) -> Self {
    self.depth += 1;
    self
  }
  fn insert_data_type(&mut self, date_type_id: TypeId, generics: Vec<Type>) -> bool {
    self.seen_data_type.insert((data_type_id, generics))
  }
}
```

and then use it like this:
```rust
fn vector_count(typ: &Type, ctx: mut TypeRecursionContext) -> usize {
...
            Type::DataType(def, args) => {
                let struct_type = def.borrow();
                if ctx.insert_data_type(struct_type.id, args.clone()) {
                    if let Some(fields) = struct_type.get_fields(args) {
                        fields.iter().map(|(_, typ, _)| vector_count(typ, ctx.clone().recur())).sum()
                    } else if let Some(variants) = struct_type.get_variants(args) {
                        variants
                            .iter()
                            .flat_map(|(_, types)| types)
                            .map(|typ| vector_count(typ, ctx.clone().recur()))
                            .sum()
                    } else {
                        0
                    }
                } else {
                    // If we bump into a recursive type, we stop counting.
                    // "zero" isn't strictly correct here, but the recursive type will be an error
                    // already so this count won't matter in the end.
                    0
                }
            }
```

Comment (aakoshh) [reply compiler/noirc_frontend/src/elaborator/lints.rs:185]: A real example:
```noir
struct Foo {
    xs: [u32],
}
struct Bar {
    a: Foo,
    b: Foo,
}

#[oracle(bar)]
unconstrained fn bar() -> Bar {}

unconstrained fn main() {
    let _bar = bar();
}
```

```console
❯ cargo run -p nargo_cli -- compile --show-monomorphized --force --show-ssa-pass Initial
    Finished `dev` profile [optimized + debuginfo] target(s) in 0.24s
     Running `/Users/aakoshh/Work/aztec/noir/target/debug/nargo compile --show-monomorphized --force --show-ssa-pass Initial`
unconstrained fn main$f0() -> () {
    let _bar$l0 = bar$bar()
}

After Initial SSA:
brillig(inline) fn main f0 {
  b0():
    v1, v2, v3, v4 = call bar() -> (u32, [u32], u32, [u32])
    return
}

The application panicked (crashed).
Message:  a previous vector has already been allocated at the free memory pointer
Location: compiler/noirc_evaluator/src/brillig/brillig_gen/brillig_call/mod.rs:87
```

Comment (aakoshh) [reply compiler/noirc_frontend/src/elaborator/lints.rs:185]: Created https://github.com/noir-lang/noir/issues/11507 to track this ☝️
