### PR TITLE
fix(LSP): references/rename only when underlying span has the correct…

### LINKED ISSUE #7557: LSP rename sometimes incorrectly renames comptime code
### Aim

Image

### Expected Behavior

The quote code shouldn't be changed.

### Bug

The quote code is changed.

### To Reproduce

1.
2.
3.
4.

### Workaround

None

### Workaround Description

_No response_

### Additional Context

_No response_

### Project Impact

None

### Blocker Context

_No response_

### Nargo Version

_No response_

### NoirJS Version

_No response_

### Proving Backend Tooling & Version

_No response_

### Would you like to submit a PR for this Issue?

None

### Support Needs

_No response_

### PR DESCRIPTION
**Pull request by asterite**
… name

# Description

## Problem

Resolves #7557

## Documentation

Check one:
- [x] No documentation needed.
- [ ] Documentation included in this PR.
- [ ] **[For Experimental Features]** Documentation to be submitted in a separate PR.

# PR Checklist

- [x] I have tested the changes locally.
- [x] I have formatted the changes with [Prettier](https://prettier.io/) and/or `cargo fmt` on default settings.

### CODE REVIEW

File: tooling/lsp/src/requests/mod.rs [hunk 1]
```diff
@@ -590,68 +591,104 @@ pub(crate) fn find_all_references_in_workspace(
...
-        .map(|locations| {
-            locations
-                .iter()
-                .filter_map(|location| to_lsp_location(files, location.file, location.span))
-                .collect()
-        })
         .unwrap_or_default()
 }
 
+fn get_reference_name(reference: ReferenceId, interner: &NodeInterner) -> Option<String> {
```
[the remark this answers is not in the document]
Comment (asterite) [reply tooling/lsp/src/requests/mod.rs:665]: Since it's only used here and it doesn't require anything internal to `interner` I thought of putting it here. Otherwise the method on `interner` needs to be public and if we later change how this is implemented we might forget to remove that method.

File: tooling/lsp/src/requests/references.rs [hunk 2]
```diff
@@ -170,4 +169,65 @@ mod references_tests {
...
+        let (mut state, noir_text_document) = test_utils::init_lsp_server("document_symbol").await;
+
+        let (line, column) = src
+            .lines()
+            .enumerate()
+            .filter_map(|(line_index, line)| {
+                line.find(">|<").map(|char_index| (line_index, char_index))
+            })
+            .next()
+            .expect("Expected to find one >|< in the source code");
```
Comment (aakoshh) [inline tooling/lsp/src/requests/references.rs:200]: This pattern of finding the location of `">|<"` appears quite a few times now, along with the `apply_text_edits(&src.replace(">|<", ""), &item.additional_text_edits.unwrap());` replacement. Perhaps two helper functions wouldn't be a bad idea?

Comment (asterite) [reply tooling/lsp/src/requests/references.rs:200]: Good point, I was being lazy here. I thought it's only used in completion tests but even then there's no excuse for duplicating this. I'll update it.

**Review by aakoshh — APPROVED** [review]
I think I understand what's happening in the gif, the fix makes sense to me, although I'm not that familiar with the interner and its reference graph.

File: tooling/lsp/src/requests/references.rs (hunk 2 above)
Comment (asterite) [reply tooling/lsp/src/requests/references.rs]: Done!

**Review by TomAFrench — APPROVED** [review]
