### PR TITLE
fix: check func env for references/vectors

### LINKED ISSUE #11257: Compiler crash: return lambda with reference in env from oracle
### Aim

Discovered trying to come up with an example in https://github.com/noir-lang/noir/pull/11255/changes#r2705059079

The following code crashes the compiler:

```noir
use std::test::OracleMock;

fn main() {

}

#[oracle(choose_func)]
unconstrained fn choose_func<Env>(f: fn[Env](Field) -> (), g: fn[Env](Field) -> ()) -> fn[Env](Field) -> () {}

#[test]
unconstrained fn test_function_pointer() {
    let y = &mut 10;
    // Create lambdas which capture the environment. They become global function with an ID, taking extra env arguments.
    let add = |x: Field| { *y = *y + x; };
    let mul = |x: Field| { *y = *y * x; };

    // Set the expectation that we will pass the `add` lambda, surrounded by other numbers
    // to make sure deserialization does not affect them.
    let _mock = OracleMock::mock("choose_func").with_params((add, mul)).returns(add);

    // Call the oracle with the expected parameters.
    let f = choose_func(add, mul);

    // Check that calling the return function gives the expected result.
    f(20);
    assert_eq(*y, 30);
}
```

Or without mocks:
```noir

unconstrained fn main() {
    let y = &mut 10;
    let add = |x: Field| { *y = *y + x; };
    let mul = |x: Field| { *y = *y * x; };

    // Call the oracle with the expected parameters.
    let f = choose_func(add, mul);

    f(20);
}

#[oracle(choose_func)]
unconstrained fn choose_func<Env>(f: fn[Env](Field) -> (), g: fn[Env](Field) -> ()) -> fn[Env](Field) -> () {}
```

### Expected Behavior

The code should either return a function pointer to one of the available lambdas, or it should reject this code with a compilation error. 

NB the code works in either of the following cases:
* Remove the `#[oracle]` and just have the function return one of the args
* Change `y` into a non-reference value (the oracle is allowed to return an environment, which will be passed onto the calls)

Because an environment is actually returned by the oracle, along with the function ID, it makes sense that we should reject the case where the environment has a reference in it, as there is no ID to their combination.

### Bug

```console
❯ cargo run -q -p nargo_cli -- test --force 

[fuzz_testing] Running 1 test function
The application panicked (crashed).
Message:  internal error: entered unreachable code: ICE: unsupported return type for black box call Reference(Numeric(NativeField))
Location: compiler/noirc_evaluator/src/brillig/brillig_gen/brillig_call/mod.rs:98

This is a bug. We may have already fixed this in newer versions of Nargo so try searching for similar issues at https://github.com/noir-lang/noir/issues/.
If there isn't an open issue for this bug, consider opening one at https://github.com/noir-lang/noir/issues/new?labels=bug&template=bug_report.yml
[fuzz_testing] Testing test_function_pointer ... FAIL
An unexpected error happened


[fuzz_testing] Failures:
     test_function_pointer

[fuzz_testing] 1 test failed
```

### To Reproduce

See above.

### Workaround

None

### Workaround Description

_No response_

### Additional Context

_No response_

### Project Impact

None

### Blocker Context

_No response_

### Nargo Version

nargo version = 1.0.0-beta.18 noirc version = 1.0.0-beta.18+80026cfca7b7480bc1ad1277f68710e167226216 (git version hash: d4e0cc394e26e64c27a31c5385b797b083a662f2, is dirty: true)

### NoirJS Version

_No response_

### Proving Backend Tooling & Version

_No response_

### Would you like to submit a PR for this Issue?

None

### Support Needs

_No response_

### PR DESCRIPTION
**Pull request by asterite**
# Description

## Problem

See https://github.com/noir-lang/noir/pull/11189#discussion_r2704842826
Fixes #11257

## User Documentation

Check one:
- [x] No user documentation needed.
- [ ] Changes in _docs/_ included in this PR.
- [ ] **[For Experimental Features]** Changes in _docs/_ to be submitted in a separate PR.

# PR Checklist

- [x] I have tested the changes locally.
- [x] I have formatted the changes with [Prettier](https://prettier.io/) and/or `cargo fmt` on default settings.

### CODE REVIEW

File: compiler/noirc_frontend/src/elaborator/lints.rs [hunk 1]
```diff
@@ -194,48 +194,7 @@ pub(super) fn oracle_returns_reference(
...
-            | Type::Integer(_, _)
-            | Type::Bool
-            | Type::String(_)
-            | Type::FmtString(_, _)
-            | Type::Unit => false,
-        }
-    }
-
-    if contains_reference(func.return_type()) {
+    if func.return_type().contains_reference() {
```
Comment (aakoshh) [inline compiler/noirc_frontend/src/elaborator/lints.rs:197]: We agreed in https://github.com/noir-lang/noir/pull/10178 that oracles should be able to return function pointers, at least the type system should allow it. This is limited to basically selecting a function already available in the circuit. 

With the change below, this would prevent it from working any more.

Comment (asterite) [reply compiler/noirc_frontend/src/elaborator/lints.rs:197]: We can revert this. But I think with this change function pointers can still be returned? Just not ones that contain mutable references in their env.

Comment (asterite) [reply compiler/noirc_frontend/src/elaborator/lints.rs:197]: Or, hmm.. is there a test that shows this functionality?

Comment (aakoshh) [reply compiler/noirc_frontend/src/elaborator/lints.rs:197]: No, I'm just trying to write one to see what happens.

Comment (aakoshh) [reply compiler/noirc_frontend/src/elaborator/lints.rs:197]: Here, it works:
```noir
use std::test::OracleMock;

fn main() {

}

#[oracle(choose_func)]
unconstrained fn choose_func<Env>(f: fn[Env](u32) -> Field, g: fn[Env](u32) -> Field) -> fn[Env](u32) -> Field {}

#[test]
unconstrained fn test_function_pointer() {
    let y = 10;
    // Create lambdas which capture the environment. They become global function with an ID, taking extra env arguments.
    let add = |x: u32| (x as Field) + y;
    let mul = |x: u32| (x as Field) * y;

    // Safety: testing that and oracle can take and return a function with a closure env as an ID.
    unsafe {
        // Set the expectation that we will pass the `add` lambda, surrounded by other numbers
        // to make sure deserialization does not affect them.
        let _mock = OracleMock::mock("choose_func").with_params((add, mul)).returns(add);

        // Call the oracle with the expected parameters.
        let f = choose_func(add, mul);

        // Check that calling the return function gives the expected result.
        assert_eq(f(20), 30);
    }
}
```

Comment (aakoshh) [reply compiler/noirc_frontend/src/elaborator/lints.rs:197]: Sorry, I captured a value not a reference.

Comment (aakoshh) [reply compiler/noirc_frontend/src/elaborator/lints.rs:197]: Changed it to this:
```noir
    let y = &mut 10;
    // Create lambdas which capture the environment. They become global function with an ID, taking extra env arguments.
    let add = |x: u32| (x as Field) + *y;
    let mul = |x: u32| (x as Field) * *y;
```

Now it crashes:
```
The application panicked (crashed).
Message:  internal error: entered unreachable code: ICE: unsupported return type for black box call Reference(Numeric(NativeField))
Location: compiler/noirc_evaluator/src/brillig/brillig_gen/brillig_call/mod.rs:98

This is a bug. We may have already fixed this in newer versions of Nargo so try searching for similar issues at https://github.com/noir-lang/noir/issues/.
If there isn't an open issue for this bug, consider opening one at https://github.com/noir-lang/noir/issues/new?labels=bug&template=bug_report.yml
[fuzz_testing] Testing test_function_pointer ... FAIL
An unexpected error happened
```

Comment (aakoshh) [reply compiler/noirc_frontend/src/elaborator/lints.rs:197]: Okay, then I can't see why we should bend over backwards to support a sketchy use case 👍

Comment (aakoshh) [reply compiler/noirc_frontend/src/elaborator/lints.rs:197]: I'll open a ticket with a failing test to capture it.

Comment (aakoshh) [reply compiler/noirc_frontend/src/elaborator/lints.rs:197]: https://github.com/noir-lang/noir/issues/11257

**Comment by aakoshh** [comment]
Perhaps you can use the ticket I made as a `compile_failure` test (without the mock)?

File: compiler/noirc_frontend/src/elaborator/lints.rs (hunk 1 above)
Comment (asterite) [reply compiler/noirc_frontend/src/elaborator/lints.rs:197]: Sounds good. Does this also crash in master? I think yes. If so, should this be fixed in a separate PR?

Comment (asterite) [reply compiler/noirc_frontend/src/elaborator/lints.rs:197]: (I'll spend a bit of time trying to fix it in this PR as it kind of seems to be related)

Comment (asterite) [reply compiler/noirc_frontend/src/elaborator/lints.rs:197]: Done! It's now fixed, if you want to re-review this.

Comment (asterite) [reply compiler/noirc_frontend/src/elaborator/lints.rs:197]: I'll merge this. Worse case we can revert this, though I think it's fine and it also fixes the other issue you captured.

File: compiler/noirc_frontend/src/monomorphization/mod.rs [hunk 2]
```diff
@@ -2231,6 +2181,19 @@ impl<'interner> Monomorphizer<'interner> {
...
     }
 
+    fn check_return_type_returned_from_oracle(
+        &mut self,
+        return_type: &Type,
+        location: Location,
+    ) -> Result<(), MonomorphizationError> {
+        if return_type.contains_reference() {
+            let typ = return_type.to_string();
+            return Err(MonomorphizationError::ReferenceReturnedFromOracle { typ, location });
```
Comment (aakoshh) [inline compiler/noirc_frontend/src/monomorphization/mod.rs:2191]: I thought that this was now caught by the elaborator 🤔

Comment (asterite) [reply compiler/noirc_frontend/src/monomorphization/mod.rs:2191]: It is!... if the type is not a generic parameter. If it is, the Elaborator can't know if the generic parameter will later be replaced with something that has mutable references.

I wish we'd introduce some traits for all of this, so that all these checks could happen during elaboration.

Comment (aakoshh) [inline compiler/noirc_frontend/src/monomorphization/mod.rs:2191]: And from the new tests it looks like it is. 

Ah, is it added so that it catches the case where the env type is generic and the elaborator can't inspect it fully?

Comment (asterite) [reply compiler/noirc_frontend/src/monomorphization/mod.rs:2191]: Right. We do the same in other cases: we error in the Elaborator if we can, but otherwise always check again during monomorphization.
