### PR TITLE
fix(ssa): Use `Type::element_size` instead of `Type::flattened_size` for `optimize_length_one_array_read`

### LINKED ISSUE #10141: Compile crash: Can only cast numeric types, got Array
### Aim

Reproduce a nightly error from https://github.com/noir-lang/noir/actions/runs/18364410000/job/52314440291

The following Noir code crashes the compiler:

```rust
global G_A: [(str<0>, u16); 1] = [("", 50744_u16)];
fn main(a: u32) -> pub Field {
    G_A[a].1 as Field
}
```

### Expected Behavior

It should compile and return 50744.

### Bug

```console
❯ cargo run -q -p nargo_cli -- compile --force --silence-warnings

The application panicked (crashed).
Message:  Can only cast numeric types, got Array([Numeric(Unsigned { bit_size: 8 })], 0)
Location: compiler/noirc_evaluator/src/ssa/ir/dfg/simplify/cast.rs:20
```

I'm also sure why it says `bit_size: 8` since it's a `u16`. 

The assertion was added in https://github.com/noir-lang/noir/pull/10087

### To Reproduce

```
NOIR_AST_FUZZER_SEED=0xeb6a882d00100000 cargo test -q -p noir_ast_fuzzer_fuzz orig_vs_morph -- --nocapture
```

### Workaround

None

### Workaround Description

_No response_

### Additional Context

_No response_

### Project Impact

None

### Blocker Context

_No response_

### Nargo Version

nargo version = 1.0.0-beta.14 noirc version = 1.0.0-beta.14+9527675b5cde080fc7ad0f36f7e1128391327077 (git version hash: a4e966573812324da6c59274e89b9702907273da, is dirty: true)

### NoirJS Version

_No response_

### Proving Backend Tooling & Version

_No response_

### Would you like to submit a PR for this Issue?

None

### Support Needs

_No response_

### PR DESCRIPTION
**Pull request by aakoshh**
# Description

## Problem\*

Resolves #10141 

## Summary\*

Fixes the condition for using `optimize_length_one_array_read` to use `element_size` instead of `flattened_size`. 

## Additional Context

In the failing example we had this SSA:
```rust
After Initial SSA:
g0 = u32 0
g1 = u32 1
g2 = u32 3
g3 = make_array [u32 0, u32 1, u32 3] : [u32; 3]
g4 = u1 1
g5 = u1 0
g6 = make_array [u1 1, u1 0] : [u1; 2]
g7 = make_array [g3, g6] : [([u32; 3], [u1; 2]); 1]

acir(inline) fn main f0 {
  b0(v8: u32):
    v10 = call f1() -> [([u64; 0], u16); 1]
    v12 = mul v8, u32 2
    constrain v12 == u32 0, "Index out of bounds"
    v13 = array_get v10, index u32 0 -> [u64; 0]
    v14 = add v12, u32 1
    constrain v14 == u32 0, "Index out of bounds"
    v15 = array_get v10, index u32 0 -> u16
    v16 = cast v15 as Field
    return v16
}
acir(inline) fn foo f1 {
  b0():
    v8 = make_array [] : [u64; 0]
    v10 = make_array [v8, u16 50744] : [([u64; 0], u16); 1]
    return v10
}
```

The `v10` array has 2 elements: `[v8, u16 50744]`, so its `.element_size()` is 2, but the `.flattened_size()` is just 1, because a 0 length array like `v8` flattens into an empty sequence. 

`v12` is the base index 0, and `v14` is `0+1`, which would give us the 1st and 2nd items of the array. However this optimisation falsely concluded that the array is 1 long based on `flattened_size`, and therefore it can get its only element at index `0`, and inserted constraints that both `v12` and `v14` must be 0, which caused 1) a constraint failure and 2) the casting error, since getting the 0 element returned a `[u64; 0]` which then went into the cast of the `u16` and caused a type error during codegen.

The flattened stuff is a bit confusing; it looks like it's only relevant for ACIR, which I also commented on [here](https://github.com/noir-lang/noir/pull/10128#discussion_r2416300183). @guipublic and me both got confused for a moment whether v10 is really 1 or 2 long.

## Documentation\*

Check one:
- [x] No documentation needed.
- [ ] Documentation included in this PR.
- [ ] **[For Experimental Features]** Documentation to be submitted in a separate PR.

# PR Checklist\*

- [x] I have tested the changes locally.
- [ ] I have formatted the changes with [Prettier](https://prettier.io/) and/or `cargo fmt` on default settings.

### CODE REVIEW

File: compiler/noirc_evaluator/src/ssa/ir/dfg/simplify.rs [hunk 1]
```diff
@@ -117,7 +117,7 @@ pub(crate) fn simplify(
 
             let array_or_slice_type = dfg.type_of_value(*array);
             if matches!(array_or_slice_type, Type::Array(_, 1))
-                && array_or_slice_type.flattened_size() == 1
+                && array_or_slice_type.element_size() == 1
```
Comment (asterite) [inline compiler/noirc_evaluator/src/ssa/ir/dfg/simplify.rs:120]: We could maybe add a regression unit test for this

Comment (aakoshh) [reply compiler/noirc_evaluator/src/ssa/ir/dfg/simplify.rs:120]: Done 👍
