### PR TITLE
fix: check fold types during monomorphization

### LINKED ISSUE #10414: Generic non-main ACIR entrypoints are allowed
### Aim

In this way we can crash the compiler:

```noir
fn main() {
    foo(&[1]);
}

#[fold]
fn foo<T>(_: T) {}
```

produces:

```
The application panicked (crashed).
Message:  internal error: entered unreachable code: This type cannot exist as a parameter to main
Location: compiler/noirc_frontend/src/hir_def/types.rs:1577
```

Alternatively, maybe they can be allowed but this error should be caught during monomorphization.

Slightly related to #10413

### Expected Behavior

The code should not compile.

### Bug

The code crashes the compiler.

### To Reproduce

1.
2.
3.
4.

### Workaround

None

### Workaround Description

_No response_

### Additional Context

_No response_

### Project Impact

None

### Blocker Context

_No response_

### Nargo Version

_No response_

### NoirJS Version

_No response_

### Proving Backend Tooling & Version

_No response_

### Would you like to submit a PR for this Issue?

None

### Support Needs

_No response_

### PR DESCRIPTION
**Pull request by asterite**
# Description

## Problem

Resolves #10414

## Additional Context

After 1.0 it would be nice to have traits for all these restrictions, so they could always be caught during elaboration.

## User Documentation

Check one:
- [x] No user documentation needed.
- [ ] Changes in _docs/_ included in this PR.
- [ ] **[For Experimental Features]** Changes in _docs/_ to be submitted in a separate PR.

# PR Checklist

- [x] I have tested the changes locally.
- [x] I have formatted the changes with [Prettier](https://prettier.io/) and/or `cargo fmt` on default settings.

### CODE REVIEW

File: compiler/noirc_frontend/src/monomorphization/mod.rs [hunk 1]
```diff
@@ -538,20 +538,50 @@ impl<'interner> Monomorphizer<'interner> {
...
+                if let Some(invalid_type) = typ.program_input_validity(allow_empty_arrays) {
+                    let location = pattern.location();
+                    return Err(MonomorphizationError::InvalidTypeForEntryPoint {
+                        invalid_type,
+                        location,
+                    });
+                }
+            }
+
+            if !matches!(return_type, Type::Unit) {
```
Comment (vezenovm) [inline compiler/noirc_frontend/src/monomorphization/mod.rs]: Why do we only check for validity if the return type is not a `Type::Unit`? How about if the return_type contains a nested `Type::Unit`? This `matches!` would not catch those types.

Comment (asterite) [reply compiler/noirc_frontend/src/monomorphization/mod.rs]: Yes, it will catch those. I copied this from how it's done in the elaborator:

https://github.com/noir-lang/noir/blob/0b31117f9cb98bfee60e5c06ed6625991d5178d3/compiler/noirc_frontend/src/elaborator/function.rs#L427-L444

But I'm seeing now it's not exactly the same as we don't follow bindings. In any case, this duplication isn't good so I'll try to refactor it.

Comment (vezenovm) [reply compiler/noirc_frontend/src/monomorphization/mod.rs]: > Yes, it will catch those. I copied this from how it's done in the elaborato

Ah I misunderstood the logic. We still desire to allow single `Type::Unit` return values, just not when they are contained within other types.

File: compiler/noirc_frontend/src/hir_def/types/validity.rs [hunk 2]
```diff
@@ -127,16 +205,14 @@ impl Type {
     /// The inputs allowed for a function entry point differ from those allowed as input to a program as there are
     /// certain types which through compilation we know what their size should be.
     /// This includes types such as numeric generics.
-    pub(crate) fn non_inlined_function_input_validity(&self) -> Option<InvalidType> {
+    pub(crate) fn non_inlined_program_input_validity(&self) -> Option<InvalidType> {
```
Comment (vezenovm) [inline compiler/noirc_frontend/src/hir_def/types/validity.rs]:
```suggestion
    pub(crate) fn non_inlined_function_input_validity(&self) -> Option<InvalidType> {
```
"non inlined program" does not really make sense to me. `#[fold]` functions still act as "entry points" but only due to their non-inlined nature. They still are not the program entry point. It may be clearer to stop referring to them as entry points and rather just "never-inlined ACIR functions".

File: compiler/noirc_frontend/src/hir_def/types/validity.rs [hunk 3]
```diff
@@ -127,16 +205,14 @@ impl Type {
     /// The inputs allowed for a function entry point differ from those allowed as input to a program as there are
     /// certain types which through compilation we know what their size should be.
     /// This includes types such as numeric generics.
```
Comment (vezenovm) [inline compiler/noirc_frontend/src/hir_def/types/validity.rs:212]:
```suggestion
   /// This check is intentionally more permissive than [Self::program_validity]:
   /// - It does not enforce entry-point sizing rules (e.g. concrete array/string lengths).
   /// - It allows symbolic size expressions such as [Type::InfixExpr].
   /// - It does not special-case entry point only rules like allowing [Type:Unit] outputs.
   ///
   /// The inputs allowed for a function entry point differ from those allowed as input to a program as there are
   /// certain types which through compilation we know what their size should be.
   /// This includes types such as numeric generics.
```
It looks like this comment has been out of date as `TypeVariable` and `NamedGeneric` are handled the same in this check and the program entry point validity check. However, we still ban generics in program entry points just with a different error, so the comment is not entirely incorrect (only when referring to the methods themselves). Should we just document the differences between the methods explicitly?
