### PR TITLE
fix: Differentiate stdlib `CrateId` from others

### LINKED ISSUE #1894: Primitive types can have `impl` inside dependencies
### Aim

I tested adding `impl Field` to a dependency and including it into my project and the compiler did not error.

### Expected Behavior

The compiler should error if primitives are `impl`d in a dependency.

### Bug

The compiler doesn't error.

### To Reproduce

1.
2.
3.
4.

### Installation Method

None

### Nargo Version

_No response_

### Additional Context

Inside of `collect_impls` there is a note about this behavior but no TODO or issue that I could find.

### Would you like to submit a PR for this Issue?

Yes

### Support Needs

_No response_

### PR DESCRIPTION
**Pull request by phated**
# Description

## Problem\*

Resolves #1894  
Towards #1838 

## Summary\*

This removes the concept of `LOCAL_CRATE` being a fixed `CrateId(0)` and instead uses the crate id generated by adding a crate to the graph. The only place where hardcoding the value was useful was checking for `impl` on primitive values; however, as noted in #1894, this was a bad solution and the stdlib should be a special case of `CrateId` so it has become an enum and solves that bug.

## Documentation

- [ ] This PR requires documentation updates when merged.

  

  - [ ] I will submit a noir-lang/docs PR.

  

  - [ ] I will request for and support Dev Rel's help in documenting this PR.

  
  

## Additional Context

# PR Checklist\*

- [x] I have tested the changes locally.
- [x] I have formatted the changes with [Prettier](https://prettier.io/) and/or `cargo fmt` on default settings.

### CODE REVIEW

File: crates/noirc_frontend/src/graph/mod.rs [hunk 1]
```diff
@@ -50,7 +49,11 @@ pub struct CrateGraph {
 
 impl CrateGraph {
     pub fn is_last_crate(&self, crate_id: CrateId) -> bool {
-        (self.arena.len() - 1) == crate_id.0
+        match crate_id {
+            CrateId::Crate(crate_id) | CrateId::Stdlib(crate_id) => {
```
Comment (TomAFrench) [inline crates/noirc_frontend/src/graph/mod.rs:53]:
```suggestion
        let crate_id = crate_id.id();
```

Add a method for this? Although we need some clarification on what this inner id means.

File: crates/noirc_driver/src/main.rs [hunk 2]
```diff
@@ -14,18 +11,19 @@ fn main() {
     let mut context = Context::default();
 
     // Add local crate to dep graph
-    create_local_crate(&mut context, ROOT_DIR_MAIN, CrateType::Binary);
+    let local_crate_id = create_local_crate(&mut context, ROOT_DIR_MAIN, CrateType::Binary);
```
Comment (TomAFrench) [inline crates/noirc_driver/src/main.rs:14]: Should we store the root crate id in the context instead? When would we pass a different id instead when compiling?

**Review by TomAFrench — COMMENTED** [review]
Nice to break out the stdlib more explicitly. Not sure we need to pass around the root crate id however.

File: crates/nargo_cli/tests/test_data/config.toml [hunk 3]
```diff
@@ -5,3 +5,6 @@ exclude = ["bit_shifts_runtime", "comptime_fail", "poseidonsponge_x5_254", "sha2
 
 # List of tests (as their directory name in test_data) expecting to fail: if the test pass, we report an error.
 fail = ["range_fail"]
+
+# List of tests (as their directory name in test_data) expecting to panic: if the test pass, we report an error.
+panic = ["dep_impl_primitive"]
```
Comment (jfecher) [inline crates/nargo_cli/tests/test_data/config.toml:10]: Should we expect this to panic? I'd expect a compiler error but not a panic

File: crates/noirc_frontend/src/graph/mod.rs [hunk 4]
```diff
@@ -97,7 +100,23 @@ impl CrateGraph {
         }
 
         let data = CrateData { root_file_id: file_id, crate_type, dependencies: Vec::new() };
-        let crate_id = CrateId(self.arena.len());
+        let crate_id = CrateId::Crate(self.arena.len());
+        let prev = self.arena.insert(crate_id, data);
+        assert!(prev.is_none());
```
Comment (jfecher) [inline crates/noirc_frontend/src/graph/mod.rs:105]: Does this insert fix anything? I'm curious why we didn't insert before this change

File: crates/noirc_driver/src/main.rs (hunk 2 above)
Comment (phated) [reply crates/noirc_driver/src/main.rs:14]: No. The we should be working with whatever crate_id is created in the graph and it should not be stored. This moves us towards being able to compile any node in the graph.

File: crates/noirc_frontend/src/graph/mod.rs (hunk 1 above)
Comment (phated) [reply crates/noirc_frontend/src/graph/mod.rs:53]: With this change, the "crate id" is the entirety of the type and usize id and they don't make sense separated. This match is fine

File: crates/noirc_frontend/src/graph/mod.rs (hunk 4 above)
Comment (phated) [reply crates/noirc_frontend/src/graph/mod.rs:105]: It did, you are just looking at the diff wrong. Most of the code was duplicated except creating a `CrateId::Stdlib(self.arena.len());` instead of `CrateId::Crate(self.arena.len());`

File: crates/noirc_frontend/src/hir/def_collector/dc_crate.rs [hunk 5]
```diff
@@ -237,10 +237,8 @@ fn collect_impls(
                         errors.push(err.into_file_diagnostic(unresolved.file_id));
                     }
                 }
-            // Prohibit defining impls for primitive types if we're in the local crate.
-            // We should really prevent it for all crates that aren't the noir stdlib but
-            // there is no way of checking if the current crate is the stdlib currently.
-            } else if typ != Type::Error && crate_id == LOCAL_CRATE {
+            // Prohibit defining impls for primitive types if we're not in the stdlib
+            } else if typ != Type::Error && matches!(crate_id, CrateId::Crate(_)) {
```
[the remark this answers is not in the document]
Comment (phated) [reply crates/noirc_frontend/src/hir/def_collector/dc_crate.rs:241]: Good idea. I'll do that after the rebase

**Review by TomAFrench — APPROVED** [review]

**Review by TomAFrench — APPROVED** [review]
