### PR TITLE
fix: do not predicate safe index on non-homogenous arrays

### LINKED ISSUE #11402: Discrepancy between ACIR and brillig pipeline
I've taken the fuzzer failure from https://github.com/noir-lang/noir/actions/runs/21504399531/job/61957526337 and minimised it to the following program

```noir
fn main(mut a: [(bool, str<2>); 2], b: str<1>, active: bool, index: u32) -> pub str<2> {
    a[index].1 = "cc";
    if active {
        unsafe { func_4(func_2b(), (0, b, a[0].1)) };
    };
    a[0].1
}
unconstrained fn func_2b() -> str<1> {
    "d"
}
unconstrained fn func_4(_a: str<1>, b: (u32, str<1>, str<2>)) -> u32 {
    let (_, _, _) = b;
    b.0
}
```

```
// Prover.toml
a = [[true, "v*"], [false, "f{"]]
b = "x"
active = false
index = 1
```

This returns "\u{1}v" on the default compilation flow but with `--force-brillig` it returns "v*"

### PR DESCRIPTION
**Pull request by guipublic**
# Description

## Problem

Resolves #11402

## Summary
For non-homogenous array, we first read into the element_type_sizes array, and predicate the index for reading this array.
However, when the index is safe, array-get are de-duplicated, so we may end up using a predicated index in a place without enable-side-effect.
We just need to check if the index is safe before 'predicating' it.

## User Documentation

Check one:
- [X] No user documentation needed.
- [ ] Changes in _docs/_ included in this PR.
- [ ] **[For Experimental Features]** Changes in _docs/_ to be submitted in a separate PR.

# PR Checklist

- [X] I have tested the changes locally.
- [X] I have formatted the changes with [Prettier](https://prettier.io/) and/or `cargo fmt` on default settings.

### CODE REVIEW

File: compiler/noirc_evaluator/src/acir/call/intrinsics/vector_ops.rs [hunk 1]
```diff
@@ -852,4 +861,35 @@ impl Context<'_> {
 
         Ok(result)
     }
+
+    /// Returns true if the user-facing index is less than the vector capacity
+    fn is_index_safe(
```
Comment (asterite) [inline compiler/noirc_evaluator/src/acir/call/intrinsics/vector_ops.rs:866]: Can we always use `dfg.is_safe_index` instead? I just tried it and at least the new test passes.

Comment (asterite) [reply compiler/noirc_evaluator/src/acir/call/intrinsics/vector_ops.rs:866]: This is what I tried (not sure if it's the best way to write it, but i was just trying things out):

```diff
diff --git a/compiler/noirc_evaluator/src/acir/arrays.rs b/compiler/noirc_evaluator/src/acir/arrays.rs
index 24caeda176..9d57286069 100644
--- a/compiler/noirc_evaluator/src/acir/arrays.rs
+++ b/compiler/noirc_evaluator/src/acir/arrays.rs
@@ -426,9 +426,8 @@ impl Context<'_> {
 
         let shift = ElementTypeSizesArrayShift::None;
         let index_var = self.convert_numeric_value(index, dfg)?;
-        let is_safe_index = dfg.is_safe_index(index, array_id);
         let index_var =
-            self.get_flattened_index(&array_typ, array_id, index_var, dfg, is_safe_index, shift)?;
+            self.get_flattened_index(&array_typ, array_id, index_var, index, dfg, shift)?;
 
         // Side-effects are always enabled so we do not need to do any predication
         if self.acir_context.is_constant_one(&self.current_side_effects_enabled_var) {
@@ -1126,8 +1125,8 @@ impl Context<'_> {
         array_typ: &Type,
         array_id: ValueId,
         var_index: AcirVar,
+        index: ValueId,
         dfg: &DataFlowGraph,
-        is_safe_index: bool,
         shift: ElementTypeSizesArrayShift,
     ) -> Result<AcirVar, RuntimeError> {
         if let Some(step_size) = array_has_constant_element_size(array_typ) {
@@ -1137,7 +1136,7 @@ impl Context<'_> {
             let element_type_sizes =
                 self.init_element_type_sizes_array(array_typ, array_id, None, dfg, shift)?;
 
-            let predicate_index = if is_safe_index {
+            let predicate_index = if dfg.is_safe_index(index, array_id) {
                 var_index
             } else {
                 self.acir_context.mul_var(var_index, self.current_side_effects_enabled_var)?
diff --git a/compiler/noirc_evaluator/src/acir/call/intrinsics/vector_ops.rs b/compiler/noirc_evaluator/src/acir/call/intrinsics/vector_ops.rs
index 7c16d00e1c..d849fd89ae 100644
--- a/compiler/noirc_evaluator/src/acir/call/intrinsics/vector_ops.rs
+++ b/compiler/noirc_evaluator/src/acir/call/intrinsics/vector_ops.rs
@@ -514,7 +514,6 @@ impl Context<'_> {
 
         // Fetch the flattened index from the user provided index argument.
         let item_size = self.acir_context.add_constant(elements_to_insert.len());
-        let is_safe_index = Self::is_index_safe(arguments[2], dfg, &vector_typ, vector_size);
         let insert_index = self.acir_context.mul_var(insert_index, item_size)?;
 
         // Because the insert index might be at the end of the slice, the element type sizes we
@@ -524,8 +523,8 @@ impl Context<'_> {
             &vector_typ,
             vector_contents,
             insert_index,
+            arguments[2],
             dfg,
-            is_safe_index,
             shift,
         )?;
 
@@ -767,15 +766,14 @@ impl Context<'_> {
         let item_size = vector_typ.element_size().to_usize();
         let item_size_var = self.acir_context.add_constant(item_size);
         let remove_index = self.acir_context.mul_var(remove_index, item_size_var)?;
-        let is_safe_index = Self::is_index_safe(arguments[2], dfg, &vector_typ, vector_size);
 
         // Fetch the flattened index from the user provided index argument.
         let flat_user_index = self.get_flattened_index(
             &vector_typ,
             vector_contents,
             remove_index,
+            arguments[2],
             dfg,
-            is_safe_index,
             ElementTypeSizesArrayShift::None,
         )?;
 
@@ -861,35 +859,4 @@ impl Context<'_> {
 
         Ok(result)
     }
-
-    /// Returns true if the user-facing index is less than the vector capacity
-    fn is_index_safe(
-        index: ValueId,
-        dfg: &DataFlowGraph,
-        vector_typ: &Type,
-        vector_size: FlattenedLength,
-    ) -> bool {
-        // Compute the number of logical elements in the vector by dividing the fully flattened size (in ACIR)
-        // by the vector's elements size (in ACIR), and checking that value against the SSA index.
-        let acir_fields_per_element: usize = match vector_typ {
-            Type::Array(elements, _) | Type::Vector(elements) => {
-                elements.iter().map(|typ| typ.flattened_size().to_usize()).sum()
-            }
-            _ => unreachable!("element_flattened_size: Expected array or vector"),
-        };
-
-        if let Some(index_const) = dfg.get_numeric_constant(index) {
-            let index_const = index_const.to_u128() as usize;
-            // A vector with zero-sized elements has a flattened_size of 0 because of the multiplication with element size.
-            // As a result, every index will be out-of-bound.
-            if acir_fields_per_element == 0 {
-                false
-            } else {
-                let num_logical_elements = vector_size.to_usize() / acir_fields_per_element;
-                index_const < num_logical_elements
-            }
-        } else {
-            false
-        }
-    }
 }
```

Comment (guipublic) [reply compiler/noirc_evaluator/src/acir/call/intrinsics/vector_ops.rs:866]: Unfortunately that does not work, the tuples are flattened in SSA, and the vector's array is fully flattened in ACIR. The index corresponds to none of these, but to the non-flattened vector instead.
