### PR TITLE
fix(mem2reg): Updating referenced value invalidate addresses with unknown aliases

### LINKED ISSUE #10070: Incorrect alias set calculation for ArraySet instruction
See https://audithub.veridise.com/app/organizations/146/projects/434/project-viewer?version=1038&issue=424&bpt=1

--- 

Similar to [Incorrect alias set calculation for MakeArray instruction](https://audithub.veridise.com/app/organizations/146/projects/434/project-viewer?version=1007&issue=413&bpt=1), in the Mem2Reg pass, the wrong alias sets are updated in the ArraySet instruction. Conceptually, the alias set of the value that is set in the array should be updated to contain the result of the ArraySet instruction. This is because by dereferencing the updated array, it is possible to obtain a reference to the location referred to by the value.

# Impact

For example, consider the following SSA code snippet:

An example of SSA code that uses ArraySet, ArrayLoad, Load, and Store instructions. The input array v0 is an array of a single &mut Field, which makes it practically similar to a reference. The element v0[0] is assigned to either v3 or v4 depending on which branch is taken; therefore, the resulting load v8 = v0[0] can be either v3 or v4. Because the values 2 and 3 are stored to v3 and v4, respectively, it follows that it is unsafe to substitute the load v8 instruction with any of the constants in the Store instructions.

```
brillig(inline) fn main f0 {
  b0(v0: [&mut Field; 1], v1: u1):
    v3 = allocate -> &mut Field
    v4 = allocate -> &mut Field
    jmpif v1 then: b1, else: b2
  b1():
    v7 = array_set v0, index u32 0, value v3
    jmp b3(v7)
  b2():
    v6 = array_set v0, index u32 0, value v4
    jmp b3(v6)
  b3(v2: [&mut Field; 1]):
    v8 = array_get v2, index u32 0 -> &mut Field
    store Field 1 at v8
    store Field 2 at v3
    store Field 3 at v4
    v12 = load v8 -> Field
    return v12
}
```

When the Mem2Reg pass is applied to the above code, the resulting SSA code has the load incorrectly replaced with a constant:

```
brillig(inline) fn main f0 {
  b0(v0: [&mut Field; 1], v1: u1):
    v3 = allocate -> &mut Field
    v4 = allocate -> &mut Field
    jmpif v1 then: b1, else: b2
  b1():
    v7 = array_set v0, index u32 0, value v3
    jmp b3(v7)
  b2():
    v6 = array_set v0, index u32 0, value v4
    jmp b3(v6)
  b3(v2: [&mut Field; 1]):
    v8 = array_get v2, index u32 0 -> &mut Field
    store Field 1 at v8
    store Field 2 at v3
    store Field 3 at v4
    return Field 1
}
```

In practice, it is difficult to construct such input SSA code, because the Noir frontend does not allow updating an array of references or returning a reference from an if-then-else. However, the input SSA could potentially result from a combination of earlier optimizations in the pass pipeline.

# Recommendation

Ensure that the alias sets that contain the array are updated with the result of the array set. The change should also include the alias set of the value that is stored in the array. This would ensure, for example, that the stores to v3 and v4 in the above example would invalidate the known value of v8.

### PR DESCRIPTION
**Pull request by guipublic**
# Description

## Problem\*

Resolves #10070
## Summary\*
When a value pointed by an address is modified, we invalidate values of addresses that alias this same address or that have unknown alias.

## Additional Context
In the linked issue, the link between v8 and v3 or v4 is not known because v2 is simply given an unknown alias set. So the suggestion in the issue, which is to properly link v0, v3, and v6 (and same for v0, v4, and v7)  will not work because v2 does not know about them.
Tracking aliases across branches could be done in future but not as part of this bug fixe I think.

## Documentation\*

Check one:
- [X] No documentation needed.
- [ ] Documentation included in this PR.
- [ ] **[For Experimental Features]** Documentation to be submitted in a separate PR.

# PR Checklist\*

- [X] I have tested the changes locally.
- [X] I have formatted the changes with [Prettier](https://prettier.io/) and/or `cargo fmt` on default settings.

### CODE REVIEW

File: compiler/noirc_evaluator/src/ssa/opt/mem2reg.rs [hunk 1]
```diff
@@ -2509,4 +2509,68 @@ mod tests {
...
+        }
+        ";
+        assert_ssa_does_not_change(src, Ssa::mem2reg);
+    }
+
+    #[test]
+    fn regression_10020() {
+        // v14 = add v12, v13 is NOT replaced by v13 = add v12, Field 1
+        let src = "
+acir(inline) predicate_pure fn main f0 {
```
Comment (asterite) [inline compiler/noirc_evaluator/src/ssa/opt/mem2reg.rs]: Could this code be aligned to the `let`?
