### PR TITLE
fix(acir): Attach locations to MemoryOps in ACIR

### LINKED ISSUE #2133: Noir program attempts to read uninitialised memory
Reopening @ax0's issue #2099 based on the new error.

### Aim

Generate a proof for [this program](https://github.com/aragonzkresearch/noir-trie-proofs/tree/main/tests/depth_8_storage_proof).

### Expected Behavior

A proof is successfully generated.

### Bug

We get the following error:
```
$ nargo execute
The application panicked (crashed).
Message:  Should not read uninitialized memory
Location: /home/tom/.cargo/registry/src/github.com-1ecc6299db9ec823/acvm-0.21.0/src/pwg/memory_op.rs:26

This is a bug. We may have already fixed this in newer versions of Nargo so try searching for similar issues at https://github.com/noir-lang/noir/issues/.
If there isn't an open issue for this bug, consider opening one at https://github.com/noir-lang/noir/issues/new?labels=bug&template=bug_report.yml
```

### To Reproduce

1. `git clone https://github.com/aragonzkresearch/noir-trie-proofs`
2. `cd noir-trie-proofs/tests/depth_8_storage_proof`
3. `nargo execute`

### Installation Method

Compiled from source

### Nargo Version

nargo 0.9.0 (git version hash: a07b8a48924865d8425d35e40c75f48a13a81935, is dirty: false)

### Would you like to submit a PR for this Issue?

No

### Support Needs

_No response_

### PR DESCRIPTION
**Pull request by vezenovm**
# Description

## Problem\*

Initial work towards resolving #2133. Pushing for visibility in case we want to merge this now as this does fix reporting for index out of bounds errors from ACVM, but does not fully resolve #2133. Read the summary for more details.

## Summary\*

I have added reporting for IndexOutOfBounds errors triggered by ACVM. These occur when there is an index out of bounds on a dynamic arrray that uses the MemoryOp ACIR opcode. The reporting essentially extends the work for unsatisfied constrain statements, but I felt a true refactor of how nargo execute handles ACVM errors can be left for another PR. 

In order to report the error accurately, a couple other changes had to be made as well. When we were creating MemoryOp's to work with dynamic arrays in ACIR we were pushing to the list of opcodes directly and not attaching location information. I have switched to calling the `push_opcode` method when adding opcodes that deal with memory. I have also restricted the `opcodes` field to now be private with the goal to avoid this error in the future. Any opcodes should be included using the `push_opcode` method that also attaches a location. 

A new `dynamic_array_index` test has been included under `compile_failure` which will now exit with this:
Screenshot 2023-08-21 at 2 46 38 PM

The new location data has also exposed the actual bug that occurs in #2133. It looks like we are not handling locations correctly during flattening. A smaller reproduced snippet of the storage proof example is provided in the `dynamic_array_index`. If the dynamic array is accessed with an index out of bounds later after flattening, only the then case of the array merger is shown. For example

```rust
    if z == 20 {
        x[0] = x[4];
    } else {
        x[idx] = 10;
        for i in 0..5 {
            x[idx] = x[i];
        }
    }
    // TODO(#2133): This line should be where we show the error
    // but instead it will show x[0] == x[4] as the line where there is an index out of bounds
    assert(x[idx] != 0)
```
This bug is also seen in the storage proof example, which will return the below output when calling `nargo execute`:
Screenshot 2023-08-21 at 2 53 15 PM

However, based on the smaller snippet above, it looks to be using the incorrect location, as the array access being reported is within the then case of an if statement:
```rust
        if ((i + n) as u32) < (N as u32)
        {
            out[i] = input[i+n];
        }
```

## Documentation

- [ ] This PR requires documentation updates when merged.

  

  - [ ] I will submit a noir-lang/docs PR.

  

  - [ ] I will request for and support Dev Rel's help in documenting this PR.

  
  

## Additional Context

# PR Checklist\*

- [X] I have tested the changes locally.
- [X] I have formatted the changes with [Prettier](https://prettier.io/) and/or `cargo fmt` on default settings.

### CODE REVIEW

File: crates/noirc_evaluator/src/ssa.rs [hunk 1]
```diff
@@ -87,14 +87,11 @@ pub fn create_circuit(
     enable_brillig_logging: bool,
 ) -> Result<(Circuit, DebugInfo, Abi), RuntimeError> {
     let func_sig = program.main_function_signature.clone();
+    let generated_acir = optimize_into_acir(program, enable_ssa_logging, enable_brillig_logging)?;
+    let opcodes = generated_acir.opcodes().to_vec();
```
Comment (jfecher) [inline crates/noirc_evaluator/src/ssa.rs:91]: Why do we need to clone the opcodes here instead of destructuring them directly like we did previously?

Comment (jfecher) [reply crates/noirc_evaluator/src/ssa.rs:91]: I see they're private now but I'd still like to avoid the clone. Maybe we can have a `take_opcodes` method which does a `std::mem::take` on them.

**Comment by vezenovm** [comment]
> However, based on the smaller snippet above, it looks to be using the incorrect location, as the array access being reported is within the then case of an if statement:

I have found the cause of this bug, and it is not due to misplaced location data during SSA, but rather a missing predicate from MemoryOps. I have a fix locally that I will push based off of this branch after I am done testing the changes.

File: crates/noirc_evaluator/src/ssa.rs (hunk 1 above)
Comment (vezenovm) [reply crates/noirc_evaluator/src/ssa.rs]: I switched to a `take_opcodes` method instead of the clone

**Comment by vezenovm** [comment]
The follow-up PR (https://github.com/noir-lang/noir/pull/2400) requires a breaking ACVM release so I have re-requested review on this PR as we can merge it in separately.

File: crates/nargo_cli/src/cli/execute_cmd.rs [hunk 2]
```diff
@@ -91,42 +90,64 @@ fn execute_package<B: Backend>(
...
+                    }
+                    acvm::pwg::OpcodeResolutionError::UnsatisfiedConstrain { .. } => {
+                        let message = "Failed constraint".into();
+                        CustomDiagnostic::simple_error(message, String::new(), location.span)
+                            .in_file(location.file)
+                            .with_call_stack(locations)
+                            .report(&context.file_manager, false);
+                    }
+                    _ => (),
+                }
```
Comment (jfecher) [inline crates/nargo_cli/src/cli/execute_cmd.rs:150]: These two cases differ only by the message they return, so perhaps we should just return the message from each case then have a single error/report below.

I do see that we are currently ignoring all error types other than these two, although it's not clear to me why. Can we either handle these cases as well or get a comment explaining why we don't handle them here? If we don't want to handle them, it can be an early return so that we can still simplify the match.

Comment (vezenovm) [reply crates/nargo_cli/src/cli/execute_cmd.rs:150]: These are the only two errors that have an `ErrorLocation` associated with them that need to be resolved using the `DebugInfo` struct. The rest of the errors are still reported, but they just use the base message provided from the acvm's `OpcodeResolutionError` enum. 

I will add a comment making this distinction as well as a cleaned up match

Comment (vezenovm) [reply crates/nargo_cli/src/cli/execute_cmd.rs]: done

**Review by jfecher — APPROVED** [review]
