### PR TITLE
fix(parser): error on missing function body

### LINKED ISSUE #7997: Formatter panic on missing braces for oracle function
### Aim

In [this commit](https://github.com/noir-lang/noir/pull/7996/commits/82fb6c455f969bd5cc287e6ff1c3af51b0a84dff) I added a new `get_times_mock_called` and I also added a new `times_called` method to the `OracleMock` impl under `noir_stdlib/src/test.nr`

### Expected Behavior

nargo fmt to format the fiel

### Bug

Running `nargo fmt` on the `noir_stdlib` gives this panic:

Image

### To Reproduce

1. Checkout to the linked commit
2. Build from source
3. cd into `noir_stdlib` and run `nargo fmt`

### Workaround

None

### Workaround Description

_No response_

### Additional Context

_No response_

### Project Impact

None

### Blocker Context

_No response_

### Nargo Version

_No response_

### NoirJS Version

_No response_

### Proving Backend Tooling & Version

_No response_

### Would you like to submit a PR for this Issue?

None

### Support Needs

_No response_

### PR DESCRIPTION
**Pull request by asterite**
# Description

## Problem

Resolves #7997

## Summary

The issue was that when the parser didn't find `{ ... }` for a function, it would return an empty body but not error. Without an error the formatter tried to format it and panicked. Now the parser will produce an error in this case.

## Additional Context

Also fixes a syntax error in a test.

## Documentation

Check one:
- [x] No documentation needed.
- [ ] Documentation included in this PR.
- [ ] **[For Experimental Features]** Documentation to be submitted in a separate PR.

# PR Checklist

- [x] I have tested the changes locally.
- [x] I have formatted the changes with [Prettier](https://prettier.io/) and/or `cargo fmt` on default settings.

### CODE REVIEW

File: compiler/noirc_frontend/src/parser/parser/function.rs [hunk 1]
```diff
@@ -437,7 +451,7 @@ mod tests {
     fn parse_function_unclosed_parentheses() {
         let src = "fn foo(x: i32,";
         let (module, errors) = parse_program_with_dummy_file(src);
-        assert_eq!(errors.len(), 1);
+        assert!(!errors.is_empty());
```
Comment (vezenovm) [inline compiler/noirc_frontend/src/parser/parser/function.rs:454]: We are getting more than one error here now?

Comment (asterite) [reply compiler/noirc_frontend/src/parser/parser/function.rs:454]: Yes, the next error is the missing `{`. I guess we could try to improve this, though in Rust at least in the editor I also get two errors (on the command line I just get one). That said, once you add a parentheses you'll need `{` anyway, so maybe two errors is fine 🤷
