### PR TITLE
fix: `try_unify` no longer binds types on failure

### LINKED ISSUE #3089: Typevariables can be bound while searching for methods
### Aim

```rs
struct Foo<A, B> {
    field: B,
}

impl Foo<u8, u8> {
    fn foo(_self: Self) -> Field { 1 }
}

impl Foo<u16, Field> {
    fn foo(_self: Self) -> Field { 2 }
}

fn main() {
    let field: Field = 0;
    let f = Foo { field };
    assert(f.foo() == 2);
}
```

### Expected Behavior

The program to execute successfully

### Bug

The program non-deterministically fails with:
```
error: No method named 'foo' found for type 'Foo<u8, Field>'
   ┌─ /.../short/src/main.nr:18:12
   │
18 │     assert(f.foo() == 2);
   │            -------
   │

Aborting due to 1 previous error
```
From this we can see:
- In, the original type of `f`, `Foo<_, Field>`, the type variable is being bound to `u8` when seeing if the first method matches. When it does not match, the binding is not undone which causes the second method to fail to type check as well. If the binding was correctly undone, `Foo<_, Field>` would otherwise be compatible with the second method's object type `Foo<u16, Field>`.
- The program only fails sometimes. This means the ordering of the methods in the method search is non-deterministic.

### To Reproduce

1.
2.
3.
4.

### Installation Method

None

### Nargo Version

_No response_

### Additional Context

_No response_

### Would you like to submit a PR for this Issue?

No

### Support Needs

_No response_

### PR DESCRIPTION
**Pull request by jfecher**
# Description

## Problem\*

Resolves #3089. This issue also affected impl search which uses `try_unify` to compare against every impl candidate. In some programs this could cause invalid type bindings, eventually leading to various mismatched/unexpected types panics during SSA.

## Summary\*

I've refactored `try_unify` to instead return a set of type bindings which must be applied afterward if the function was successful. Each caller of `try_unify` must do this manually now. Additionally, `lookup_trait_implementation` must now juggle several sets of type bindings and only commit to those that are not instantiation bindings (otherwise the generic trait would be permanently bound to another type), and even then only commit to them on success.

## Documentation\*

Check one:
- [ ] No documentation needed.
- [ ] Documentation included in this PR.
- [ ] **[Exceptional Case]** Documentation to be submitted in a separate PR.

# PR Checklist\*

- [x] I have tested the changes locally.
- [x] I have formatted the changes with [Prettier](https://prettier.io/) and/or `cargo fmt` on default settings.

### CODE REVIEW

**Review by kevaundray — APPROVED** [review]

**Comment by kevaundray** [comment]
can you add a regression test?

File: compiler/noirc_frontend/src/hir_def/types.rs [hunk 1]
```diff
@@ -1046,6 +1114,34 @@ impl Type {
         }
     }
 
+    /// Try to unify a type variable to `self`.
+    /// This is a helper function factored out from try_unify.
+    fn try_unify_to_type_variable(
+        &self,
+        type_variable: &TypeVariable,
+        bindings: &mut TypeBindings,
+
```
Comment (vezenovm) [inline compiler/noirc_frontend/src/hir_def/types.rs:1123]:
```suggestion
```
Did you want this whitespace?

**Review by vezenovm — APPROVED** [review]

**Comment by jfecher** [comment]
@kevaundray added a regression
