### PR TITLE
fix(security): validate git references in GitHub dependency resolver

### LINKED ISSUE #9042: Insecure validation of github dependencies
### Aim

https://github.com/noir-lang/noir/blob/2d8f14e3bfa0379c1aed2a8d3e32544c87cef101/compiler/wasm/src/noir/dependencies/github-dependency-resolver.ts#L140-L148

if `tag = "../raw/INFECTED_FILENAME"` this file will try to resolve  https://github.com/OWNER/REPO/raw/INFECTED_FILENAME.zip successfully and then unzip it. It can be zipbomb or backdoored package.

### Expected Behavior

validated queries 

### Bug

above

### To Reproduce

1.
2.
3.
4.

### Workaround

None

### Workaround Description

_No response_

### Additional Context

_No response_

### Project Impact

None

### Blocker Context

_No response_

### Nargo Version

_No response_

### NoirJS Version

_No response_

### Proving Backend Tooling & Version

_No response_

### Would you like to submit a PR for this Issue?

None

### Support Needs

_No response_

### PR DESCRIPTION
**Pull request by DeVikingMark**
# Description

## Problem*

Resolves #9042

## Summary*

Fixes a path traversal vulnerability in `resolveGithubCodeArchive` function where `dependency.tag` parameter was directly inserted into URLs without validation. This allowed attackers to use malicious tags like `"../raw/INFECTED_FILENAME"` to access files outside the intended directory.

**Changes:**
- Added validation to reject git references containing `..`, `/`, or `\` characters
- Added comprehensive security tests covering various path traversal attack vectors
- Maintains backward compatibility with all valid git references (`v1.0.0`, `main`, `HEAD`, etc.)

## Documentation*

Check one:
- [x] No documentation needed.
- [ ] Documentation included in this PR.
- [ ] **[For Experimental Features]** Documentation to be submitted in a separate PR.

# PR Checklist*

- [x] I have tested the changes locally.
- [x] I have formatted the changes with [Prettier](https://prettier.io/) and/or `cargo fmt` on default settings.

### CODE REVIEW

File: compiler/wasm/src/noir/dependencies/github-dependency-resolver.ts [hunk 1]
```diff
@@ -144,5 +144,10 @@ export function resolveGithubCodeArchive(dependency: GitDependencyConfig, format
     throw new Error('Invalid Github repository URL');
   }
 
+  // Validate ref to prevent path traversal attacks
+  if (ref.includes('..') || ref.includes('/') || ref.includes('\\')) {
```
Comment (defkit) [inline compiler/wasm/src/noir/dependencies/github-dependency-resolver.ts]: '%2e%2e%5c' == '..\\' urldecoded, but your check does not match this case
image

**Comment by DeVikingMark** [comment]
@defkit did you mean like this?
