### PR TITLE
Handle out-of-bound errors in CSE (#471)

### LINKED ISSUE #471: Compiler panics on out-of-bounds array accesses
# Description

## Aim

Attempted to write an invalid noir program:
```rust
fn main(y: [u32; 5]) {  
    constrain y[6] == 2;
}
```

## Expected behavior

Compiler will issue an error explaining that an out-of-bounds array access has occurred with the original source location of the error, the index value, and the array length.

## Bug

Compiler hits an `unreachable` expression and panics:
```
thread 'main' panicked at 'index out of bounds: the len is 5 but the index is 6', crates/noirc_evaluator/src/ssa/anchor.rs:137:13
stack backtrace:
   0: rust_begin_unwind
   [...]
```

# To reproduce

1. Run the example code above with `nargo prove p`

# Additional context

The current panic message is fine, but being issued from a panic is confusing to users since calls to `unreachable` are usually indicative of a compiler crash rather than an intended error reporting. We should thread `Location` data down to these Load/Store instructions in SSA so that we can issue an error in the same format as other compiler errors.

### PR DESCRIPTION
**Pull request by guipublic**
# Related issue(s)

Resolves #471

# Description

## Summary of changes

report an error when trying to access an array with index out-of-bounds during CSE

# Checklist

- [X] I have tested the changes locally.
- [X] I have formatted the changes with [Prettier](https://prettier.io/) and/or `cargo fmt` with default settings.
- [X] I have [linked](https://docs.github.com/en/issues/tracking-your-work-with-issues/linking-a-pull-request-to-an-issue) this PR to the issue(s) that it resolves.
- [X] I have reviewed the changes on GitHub, line by line.
- [X] I have ensured all changes are covered in the description.

### CODE REVIEW

**Review by vezenovm — CHANGES_REQUESTED** [review]
Could we thread location data into instructions so that we can display where the error has occurred as per the issue description? 

Having the error
```
error: index out of bounds
```
is definitely better than a panic, but in a large circuit it might be hard to find this problem.

**Comment by guipublic** [comment]
>Could we thread location data into instructions (or rather NodeObj) so that we can display where the error has occurred as per the issue description?

Yes, we have already an issue open for this: #472

> For some reason it looks like the secondary message of the diagnostic is not outputting for me. Is what I pasted above what you see or is your error more descriptive? I also did not get a secondary message for the diagnostic you added here: #672.

Yes I have the same, it is due to what I said in #672:

> Note that the error is less user-friendly than the previous panic message, this is because errors with no location do not print the secondary message.

**Comment by vezenovm** [comment]
> Yes I have the same, it is due to what I said in #672:

Ah I missed the additional context. Ok in this case I am fine with these PRs then and a PR fixing #472 will alleviate my concerns.

File: crates/noirc_evaluator/src/ssa/anchor.rs [hunk 1]
```diff
@@ -175,6 +191,12 @@ impl Anchor {
                 MemItem::Const(p) | MemItem::ConstLoad(p) => {
                     let a = self.get_mem_map(array_id);
                     let b_idx = b_value.to_u128() as usize;
+                    if b_idx >= a.len() {
+                        return Some(CseAction::Error(RuntimeErrorKind::ArrayOutOfBounds {
```
Comment (kevaundray) [inline crates/noirc_evaluator/src/ssa/anchor.rs:195]: The function return type should be `Result<Option<CseAction>, RuntimeErrorKind>` since it doesn't matter that the RuntimeError came from a CseAction.

Your code would then roughly be:

```rust
return Err(RuntimeErrorKind::ArrayOutOfBounds{ index : b_idx as u128, bound : a.len() as u128})
```

**Review by kevaundray — CHANGES_REQUESTED** [review]
Added a comment RE not embedding the Error variant in CseAction

**Comment by guipublic** [comment]
> What do you think about moving the secondary messages to the main message until we have a location to associate with the errors?

I was thinking the same, but it should be done when we report the error; if there is no location, we print the secondary message as part of the main message.

File: crates/noirc_evaluator/src/ssa/anchor.rs (hunk 1 above)
Comment (guipublic) [reply crates/noirc_evaluator/src/ssa/anchor.rs]: Done.

Note that IMHO handling both an Option and a Result at the same time is confusing and makes the code less readable.

Comment (jfecher) [reply crates/noirc_evaluator/src/ssa/anchor.rs]: I've yet to read the code but I'll note that I usually find `Result<Option<...>, Error>` to be fine as long as the Option is indeed a successful case still. If `None` is meant to indicate an overall failure of some kind it should likely be part of the error enum instead.

File: crates/noirc_evaluator/src/ssa/anchor.rs [hunk 2]
```diff
@@ -134,25 +140,34 @@ impl Anchor {
...
-            self.mem_map.get_mut(&array_id).unwrap()[mem_idx].push_front((item_pos, id));
+            let arr = self.mem_map.get_mut(&array_id).unwrap();
+            if mem_idx > arr.len() {
+                return Err(RuntimeErrorKind::ArrayOutOfBounds {
+                    index: mem_idx as u128,
+                    bound: arr.len() as u128,
+                }
+                .into());
+            }
+            arr[mem_idx].push_front((item_pos, id));
```
Comment (jfecher) [inline crates/noirc_evaluator/src/ssa/anchor.rs:151]: Can combine this with the check above, `if let Some(elem) = arr.get(mem_idx) { ... push_front ... } else { return Err(...) }`.

And perhaps I'm evil but instead of `return Err(...).into();` I will sometimes do `Err(...)?;` since `?` calls `.into()` as well. Feel free to keep it as is if you don't like this suggestion.

File: crates/noirc_evaluator/src/ssa/anchor.rs [hunk 3]
```diff
@@ -168,37 +183,43 @@ impl Anchor {
...
         op: &Operation,
-    ) -> Option<CseAction> {
+    ) -> Result<Option<CseAction>, RuntimeErrorKind> {
         let (array_id, index, is_load) = Anchor::get_mem_op(op);
         if let Some(b_value) = ctx.get_as_constant(index) {
             match item {
                 MemItem::Const(p) | MemItem::ConstLoad(p) => {
                     let a = self.get_mem_map(array_id);
                     let b_idx = b_value.to_u128() as usize;
+                    if b_idx >= a.len() {
```
Comment (jfecher) [inline crates/noirc_evaluator/src/ssa/anchor.rs:193]: Same suggestion here.

Since this length handling code is somewhat repeated perhaps we can have a helper for it `fn get_elem(&self, index: ...) -> Result<..., RuntimeError>`

**Review by jfecher — COMMENTED** [review]
Looks good, though I would like to see some `Location` handling as part of this PR though. Adding them to every instruction is out of scope but can we add them to only `Index` ast nodes and the `Operation::Store` and `Operation::Load`s that result from them?

File: crates/noirc_evaluator/src/ssa/anchor.rs (hunk 2 above)
Comment (guipublic) [reply crates/noirc_evaluator/src/ssa/anchor.rs]: Done

File: crates/noirc_evaluator/src/ssa/anchor.rs (hunk 3 above)
Comment (guipublic) [reply crates/noirc_evaluator/src/ssa/anchor.rs]: Done.
I created function helper for this, which does not help much for the code size due to mutability, but it makes the code more readable.

**Review by jfecher — APPROVED** [review]
