### PR TITLE
fix(elaborator): Handle `<Object as Trait}>::<Type>` in function signatures

### LINKED ISSUE #11401: `<Self as Parent>::ident` doesn't work with trait inheritance
### Aim

This is a test added in https://github.com/noir-lang/noir/pull/11383 that should be fixed:

```noir
    pub trait Foo {
        type Bar;
        fn foo() -> Self::Bar;
    }

    pub trait Qux: Foo {
        type Bar;
        // This is rejected by Rust as ambiguous, but is accepted by Noir.
        fn qux() -> Self::Bar;

        // This "works" in Noir: it is treated as `Self::Bar`, which in turn shouldn't work.
        fn quy() -> <Self as Qux>::Bar;

        // This is not working in Noir, but it should; it works in Rust.
        fn quz() -> <Self as Foo>::Bar;
    }
```

### Expected Behavior

* `Self::Bar` should be rejected as ambiguous.
* `<Self as Foo>::Bar` should be handled and resolve to the parent's associated type

### Bug

```console
❯ cargo run -q -p nargo_cli -- compile --force

error: No matching impl found for `Self: Foo<Bar = _>`
   ┌─ src/main.nr:15:26
   │
15 │     fn quz() -> <Self as Foo>::Bar;
   │                          --- No impl for `Self: Foo<Bar = _>`
   │

Aborting due to 1 previous error

```

### To Reproduce

Add the expected errors to this test:
```
cargo test -q -p noirc_frontend trait_inheritance_with_ambiguous_associated_type
```

### Workaround

None

### Workaround Description

_No response_

### Additional Context

_No response_

### Project Impact

None

### Blocker Context

_No response_

### Nargo Version

nargo version = 1.0.0-beta.18 noirc version = 1.0.0-beta.18+ba442d489bdaf51c706115c159b52706365d493f (git version hash: 7b8bbde0c3caba8296b5a54126440fcc4d9ead4e, is dirty: true)

### NoirJS Version

_No response_

### Proving Backend Tooling & Version

_No response_

### Would you like to submit a PR for this Issue?

None

### Support Needs

_No response_

### PR DESCRIPTION
**Pull request by aakoshh**
# Description

## Problem

Resolves #11401
Resolves https://github.com/noir-lang/noir/issues/11348
Fixes https://github.com/noir-lang/noir/issues/11481

## Summary

* Treats parent trait bounds as additional `where` clauses of function definitions during elaboration. (This has an unfortunate side effect of being redundant in the code printed by `nargo expand`; I'll looking into how to do it differently, but perhaps this can be left as a follow-up, or discussed during the review, but I found other existing problems with expand and trait bounds in https://github.com/noir-lang/noir/issues/11492).
* Moved the `Elaborator::prepare_trait_impl_for_function_meta_definition` out of `Elaborator::define_function_metas_for_trait_impl`, so its effects can be observed in all `define_function_metas_for_*` methods
* Added a new `TraitImplKind::Prepared` which we can use to find the ID of a trait implementation and look up the associated types in it, before we have the fully fledged `TraitImplKind::Normal` ready later in `collect_trait_impl`
* Added a new `TraitLookupMode` parameter to `NodeInterner::try_lookup_trait_implementation` with the following variants:
  * `Default` is the normal current behaviour: if a `Type::is_bindable` then it returns an `Err`, otherwise matches any `TraitImplKind`
  * `PreparedOnly` also returns `Err` for `Type::is_bindable`, but only matches `TraitImplKind::Prepared`; this is used in a new `NodeInterner::remove_prepared_trait_implementations` to avoid matching multiple traits and getting error, instead of the single expected `Prepared` variant.
  * `SelfAssumedOnly` serves `TraitConstraint::find_impl`: if the constraint is defined on the _self type_ of a trait definition, in which case it's a `TypeVariable`, then it allows `Type::is_bindable` to be matched against `TraitImplKind::Assumed`; `find_impl` calls `try_lookups_trait_implementation` and does _not_ apply the bindings, so it's simply a check for whether `Self` implements a trait bound.
* Interned the ordered generics from `TraitImpl::resolved_generics` (also called `trait_generics`) into the `NodeInterner`, and added `NodeInterner::get_trait_generics_for_impl` and `NodeInterner::get_ordered_generics_for_impl`. 
* Disabled web security in the Chromium browser used in the `examples/browser` tests to make it able to fetch the Common Reference String from `https://crs.aztec.network/g1.dat`
* Still won't reject ambiguous associated types in traits, to keep this already huge PR a bit simpler.

## Additional Context

Sorry about the size and seemingly random nature of this PR. Any change to the `Elaborator` seemed to have unforeseen consequences and required a lot of experimentation and arm twisting to stay in the green. 

Does not solve https://github.com/noir-lang/noir/issues/11376 because there we have multi-segment paths.

## User Documentation

Check one:
- [x] No user documentation needed.
- [ ] Changes in _docs/_ included in this PR.
- [ ] **[For Experimental Features]** Changes in _docs/_ to be submitted in a separate PR.

# PR Checklist

- [x] I have tested the changes locally.
- [ ] I have formatted the changes with [Prettier](https://prettier.io/) and/or `cargo fmt` on default settings.

### CODE REVIEW

File: compiler/noirc_frontend/src/tests/traits/trait_inheritance.rs [hunk 1]
```diff
@@ -225,17 +224,49 @@ fn trait_inheritance_with_ambiguous_associated_type() {
...
+    impl Qux for Spam {
+        type Bar = str<5>;
+
+        fn quy() -> <Self as Qux>::Bar {
+            "hello"
+        }
+        fn quz() -> <Self as Foo>::Bar {
+            <Self as Foo>::foo()
+        }
+    }
```
Comment (aakoshh) [inline compiler/noirc_frontend/src/tests/traits/trait_inheritance.rs:298]: So with the changes so far, `<Self as Trait>::Type` works in the trait definition itself, but not in the trait impl. 

Note that we are trying to use the pattern in the _function signature_, rather than the function body here; in the body it works, because in `Elaborator::elaborate_items` the bodies are handled in `collect_trait_impl`, and by that time we will have called the `define_function_metas`, which established the associated types.

The reason this seems difficult to fix for the function metas themselves is the following:

`Elaborator::define_function_metas`:
  * call `define_function_metas_for_functions`
  * call `define_function_metas_for_impl`
  * call `define_function_metas_for_trait_impl` 
      * call `prepare_trait_impl_for_function_meta_definition`:
          - sets the `TraitImpl::impl_id`
          * call `setup_trait_impl_generics`
          * call `resolve_trait_impl_associated_types` 
              * call `set_associated_types_for_impl`: 
                  - from this point the trait will be in `NodeInterner::trait_impl_associated_constants` for the `TraitImpl::impl_id` where `NodeInterner::find_associated_type_for_impl` can find it, called by `Elaborator::lookup_associated_type_on_self` 
      * call `define_function_metas_for_functions`:
          - this can look up `Self::Bar` using `lookup_associated_type_on_self` using `TraitImpl::impl_id`, but won't necessarily find `<Self as Foo>::Bar`, because we may no have touched processed the `Foo` trait impl yet

To make sure we can `<Self as Foo>` when we are inside `impl Qux for Spam`, or for example look up `<Qux as Foo>::Bar` in a stand-alone function, we should change the order of definitions, and do the `prepare_trait_impl_for_function_meta_definition` for every trait, before we do anything else.

Comment (aakoshh) [reply compiler/noirc_frontend/src/tests/traits/trait_inheritance.rs:298]: But that's not enough, because unlike `Self::Bar`, which results in `lookup_associated_type_on_self` being called, for `<Self as Foo>::Bar`, we end up in `lookup_trait_implementation_helper`, which looks in `NodeInterner::trait_implementation_map`, and ignores `trait_impl_associated_constants`, and as mentioned the `impl Foo for Qux` won't be entered into this until `collect_trait_impl` is called, after we have already defined the function metas.

Comment (aakoshh) [reply compiler/noirc_frontend/src/tests/traits/trait_inheritance.rs:298]: I think instead of letting things to go the `lookup_trait_implementation`, I need to introduce a `lookup_associated_type_on_trait` that works based on the object type, but doesn't assume the full `TraitImpl` has been completed yet, and just tries to access the  `trait_impl_associated_constants` of the right impl, without knowing its ID.

**Comment by aakoshh** [comment]
Locally the following script seems to work:
```
❯ NUM_RUNS=1 OUTPUT_DIR=output REPO_DIR=../aztec-packages REPO_SLUG=AztecProtocol/aztec-packages PROJECT_TAG=next PROJECT_DIR=noir-projects/noir-protocol-circuits/crates/rollup-checkpoint-root ./scripts/gather_benchmark_data.sh
PROJECT_TAG: e4a6c70dc9e896f76fd4274d3d01e6ebd8f708c6
PROJECT_DIR: noir-projects/noir-protocol-circuits/crates/rollup-checkpoint-root
Note: Prover.toml already exists. Use --overwrite to force overwrite.
Compiling program (ACIR)
Executing program (ACIR)
Copying artifact (ACIR)
mv: rename ./target/*.json to /Users/aakoshh/Work/aztec/noir/output/artifact.json: No such file or directory

```

**Comment by aakoshh** [comment]
Although if I run it on the actual aztec commit hash, it fails on Brillig execution:
```console
❯ NUM_RUNS=1 OUTPUT_DIR=output  REPO_SLUG=AztecProtocol/aztec-packages PROJECT_TAG=e4a6c70dc9e896f76fd4274d3d01e6ebd8f708c6 PROJECT_DIR=noir-projects/noir-protocol-circuits/crates/rollup-checkpoint-root ./scripts/gather_benchmark_data.sh
PROJECT_TAG: e4a6c70dc9e896f76fd4274d3d01e6ebd8f708c6
PROJECT_DIR: noir-projects/noir-protocol-circuits/crates/rollup-checkpoint-root
Cloning into '/var/folders/j2/vrs0ww256c7gg08v4hlc87yr0000gn/T/tmp.JXmv22Tqer'...
remote: Enumerating objects: 662602, done.
remote: Counting objects: 100% (2575/2575), done.
remote: Compressing objects: 100% (709/709), done.
remote: Total 662602 (delta 2186), reused 1866 (delta 1866), pack-reused 660027 (from 2)
Receiving objects: 100% (662602/662602), 1.08 GiB | 29.13 MiB/s, done.
Resolving deltas: 100% (461435/461435), done.
Updating files: 100% (13199/13199), done.
HEAD is now at e4a6c70dc9 chore(docs): cut new aztec and bb docs version for tag v4.0.0-nightly.20260202
Note: Prover.toml already exists. Use --overwrite to force overwrite.
Compiling program (ACIR)
Executing program (ACIR)
[rollup_checkpoint_root] Circuit witness successfully solved
[rollup_checkpoint_root] Witness saved to target/rollup_checkpoint_root.gz
[rollup_checkpoint_root] Circuit output: rollup_lib::abis::checkpoint_rollup_public_inputs::CheckpointRollupPublicInputs {... 
Copying artifact (ACIR)
Compiling program (Brillig)
Executing program (Brillig)
error: Assertion failed: '0 output values were provided as a foreign call result for 1 destination slots'
   ┌─ /private/var/folders/j2/vrs0ww256c7gg08v4hlc87yr0000gn/T/tmp.JXmv22Tqer/noir-projects/noir-protocol-circuits/crates/blob/src/mock_blob_oracle.nr:18:18
   │  
18 │       let fields = evaluate_blobs_oracle(
   │ ╭──────────────────'
19 │ │         NumBlobs,
20 │ │         blobs_as_fields,
21 │ │         num_blob_fields,
   · │
25 │ │         start_accumulator.serialize(), // Serialize makes reading info easier in foreign_call_handler
26 │ │     );
   │ ╰─────'
   │  
   = Call stack:
     1. src/main.nr:6:5
     2. /private/var/folders/j2/vrs0ww256c7gg08v4hlc87yr0000gn/T/tmp.JXmv22Tqer/noir-projects/noir-protocol-circuits/crates/rollup-lib/src/checkpoint_root/checkpoint_root_rollup.nr:97:5
     3. /private/var/folders/j2/vrs0ww256c7gg08v4hlc87yr0000gn/T/tmp.JXmv22Tqer/noir-projects/noir-protocol-circuits/crates/rollup-lib/src/checkpoint_root/components/checkpoint_rollup_public_inputs_composer.nr:90:36
     4. /private/var/folders/j2/vrs0ww256c7gg08v4hlc87yr0000gn/T/tmp.JXmv22Tqer/noir-projects/noir-protocol-circuits/crates/rollup-lib/src/checkpoint_root/components/checkpoint_rollup_public_inputs_composer.nr:182:17
     5. /private/var/folders/j2/vrs0ww256c7gg08v4hlc87yr0000gn/T/tmp.JXmv22Tqer/noir-projects/noir-protocol-circuits/crates/blob/src/mock_blob_oracle.nr:18:18

Failed assertion
```

Same happens if we run it like this:
```shell
cargo run -p nargo_cli -- execute --program-dir /Users/aakoshh/Work/aztec/aztec-packages/noir-projects/noir-protocol-circuits --package rollup_checkpoint_root --force-brillig
```
and actually the same thing happens on noir `master`. I guess the oracle isn't running?

**Comment by aakoshh** [comment]
Apparently the `mv: target '/home/runner/work/noir/noir/output/compilation.jsonl' is not a directory` error we see in the failing reports happens if we have more than 1 file in the source:
```
./tmp/* $OUTPUT_DIR/compilation.jsonl
```

File: compiler/noirc_frontend/src/elaborator/function.rs [hunk 2]
```diff
@@ -49,6 +49,13 @@ impl Elaborator<'_> {
         impls: &mut ImplMap,
         trait_impls: &mut [UnresolvedTraitImpl],
     ) {
+        // Prepare all trait impls, so we can refer to `<Object as Trait>::Type` in function signatures.
+        let mut trait_constraints_and_generics = Vec::new();
+        for trait_impl in trait_impls.iter_mut() {
+            trait_constraints_and_generics
+                .push(self.prepare_trait_impl_for_function_meta_definition(trait_impl));
+        }
```
Comment (asterite) [inline compiler/noirc_frontend/src/elaborator/function.rs]: nit: I think we can use iter_mut + map + collect here.

File: compiler/noirc_frontend/src/elaborator/trait_impls.rs [hunk 3]
```diff
@@ -832,7 +845,10 @@ impl Elaborator<'_> {
 
         self.local_module = previous_local_module;
 
-        new_generics_trait_constraints
+        let generics = self.generics.clone();
+        self.generics.clear();
```
Comment (asterite) [inline compiler/noirc_frontend/src/elaborator/trait_impls.rs]:
```suggestion
        let generics = std::mem::take(&mut self.generics);
```

File: compiler/noirc_frontend/src/elaborator/function.rs (hunk 2 above)
Comment (jfecher) [reply compiler/noirc_frontend/src/elaborator/function.rs]: Or even just `vecmap`

File: compiler/noirc_frontend/src/elaborator/traits.rs [hunk 4]
```diff
@@ -610,6 +615,13 @@ impl Elaborator<'_> {
             }
         }
 
+        if let Type::TypeVariable(self_var) = object {
+            if self_var.borrow().is_unbound() && self.current_trait.is_some() {
+                // This would end up duplicating parent trait bounds we turned into where clauses on Self.
+                return;
+            }
+        }
```
Comment (asterite) [inline compiler/noirc_frontend/src/elaborator/traits.rs]: When does this scenario happen?

Comment (aakoshh) [reply compiler/noirc_frontend/src/elaborator/traits.rs]: The first thing I did in this PR was to push parent bounds as where clauses onto the methods here: 

https://github.com/noir-lang/noir/pull/11417/changes#diff-ef405c31042a9c979b36c7baa5829f7632433b4a35a55e714c55a24b1b535ae4R694

It seemed like that's what it wanted me to do, because of this:
```
                    // Attach any trait constraints on the trait to the function,
                    where_clause.extend(unresolved_trait.trait_def.where_clause.clone());
```

Doing so had the benefit that the setup and teardown were already in place, whereas if I added it as extra somewhere later, I'd have to remember to remove it from the scope. 

So with this change, if we have a trait like this:
```
trait Foo: Bar {
  fn foo();
}
```
it's turned into this:
```
trait Foo: Bar {
  fn foo() where Self: Bar;
}
```
Here the `Self` is like `Self'1`, a `NamedGeneric`. 

When we add the trait constraints to the scope, it always adds self here: 

https://github.com/noir-lang/noir/blob/0a9117b7a80c6c4fa8b809acca39603335d718b2/compiler/noirc_frontend/src/elaborator/traits.rs#L514-L519

But it adds self not as e.g. `Self'1` but just `'1`, an unbound type variable. This gets added as an `Assumed` trait implementation, and then it recurses into the parent bounds like `Bar` and adds that too, also with the `'1`. 

After this, we will have two `Assumed` implementations of `Bar`: for `'1` and `Self'1`. The problem is that when we look up an assumed implementation for `Self'1`, it matches both itself and `'1`, which is an error, because there should be only 1, and it makes `lookup_trait_implementation` fail. 

OTOH if we look up by `'1` we didn't find _any_ implementation, because `'1` is bindable and returns `Err` from `try_lookup_trait_implementation`. 

To avoid the first problem, I thought we should just not add `'1` on parents, because we already did `Self'1`, which unifies with what it needs to unify with, and `'1` shouldn't be needed. 

To avoid the second problem, I added the `TraitLookupMode` later.

Comment (asterite) [reply compiler/noirc_frontend/src/elaborator/traits.rs]: Thanks!

File: compiler/noirc_frontend/src/elaborator/traits.rs [hunk 5]
```diff
@@ -857,6 +882,32 @@ pub(crate) fn check_trait_impl_method_matches_declaration(
             bindings.insert(trait_fn_generic.id(), (trait_fn_generic.clone(), trait_fn_kind, arg));
         }
 
+        // There is special handling expected for parent traits. Say we have code like this:
+        //
+        //    trait Foo { type Bar; }                                      // `Bar`     becomes `Bar'1`
+        //    trait Bar: Foo { fn foo_bar() -> <Self as Foo>::Bar }        // `foo_bar` becomes `forall '7 '3. fn() -> Self::Bar'7`, and we should have '1 as the NamedGeneric::original_type_var
+        //    impl Foo for () { type Bar = u32; }                          // `Bar`     becomes `<Baz as Foo>::Bar'5 -> u32`
+        //    impl Bar for () { fn foo_bar() -> <Self as Foo>::Bar { 0 } } // `foo_bar` becomes `fn() -> <Baz as Foo>::Bar'5 -> u32`
```
Comment (asterite) [inline compiler/noirc_frontend/src/elaborator/traits.rs]: I guess these `Baz` are `()`?

Comment (aakoshh) [reply compiler/noirc_frontend/src/elaborator/traits.rs]: Ah yes, thanks! I wanted to save a line for a dummy struct, but maybe it would be better to add it back for clarity.

File: compiler/noirc_frontend/src/hir_def/types.rs [hunk 6]
```diff
@@ -161,7 +161,13 @@ pub struct NamedGeneric {
     /// to disambiguate from other generics in scope.
     pub name: Rc<String>,
     /// Was this named generic implicitly added?
+    ///
+    /// We add implicit named generics for associated types which aren't specified in trait constraints.
     pub implicit: bool,
+    /// Sometimes we want to preserve the type variable of the original associated type that
+    /// this one refers to, but do so without having to bind them together, which would lead
+    /// to unwanted unification.
+    pub original_type_var_id: Option<TypeVariableId>,
```
Comment (asterite) [inline compiler/noirc_frontend/src/hir_def/types.rs:170]: It seems `implicit` and `original_type_var_id` are correlated. That is, only when `implicit` is `true` then `original_type_var_id` is `Some`, so maybe the two could be collapsed.

Comment (aakoshh) [reply compiler/noirc_frontend/src/hir_def/types.rs:170]: Yes, I thought about it as well, but I don't know if this is a coincidence. I didn't want to disturb the existing pattern matching on implicits, but if you think that this will never come up for a non-implicit, we can maybe keep only this one. 

As I understand implicit are when we have `trait Foo: Bar` and `Bar` has some associated types, they get added by this, but I wasn't sure if I just hadn't seen a code example where the types are not implicitly added, and yet they need their connection to some original.

Comment (asterite) [reply compiler/noirc_frontend/src/hir_def/types.rs:170]: Sounds good, no need to change it 👍

File: compiler/noirc_frontend/src/hir_def/types.rs [hunk 7]
```diff
@@ -2991,6 +3012,91 @@ impl Type {
         }
     }
 
+    /// Visit each [Type], passing them to a function `f`.
+    /// If `f` returns `true`, visit their children, otherwise stop.
+    pub fn visit(&self, f: &mut impl FnMut(&Type) -> bool) {
+        fn go(typ: &Type, f: &mut impl FnMut(&Type) -> bool, mut limit: u32) {
```
Comment (asterite) [inline compiler/noirc_frontend/src/hir_def/types.rs:3014]: I _think_ to prevent recursion we only need to check for `DataType`s we already bumped into. I had to do this in a recent PR: https://github.com/noir-lang/noir/pull/11448

We could do the same here... maybe? Mainly to avoid a potential panic.

**Comment by asterite** [comment]
> Added a new TraitImplKind::Prepared which we can use to find the ID of a trait implementation and look up the associated types in it, before we have the fully fledged TraitImplKind::Normal ready later in collect_trait_impl

I'm wondering if this could be done without a new TraitImplKind. I'm sure you tried it, but I'll give my thoughts anyway :-)

Looking at how we handled Prepared vs. Normal, there are a few situations.

# 1

```noir
Ok((TraitImplKind::Normal(impl_id), _)) => {
    let trait_impl = self.get_trait_implementation(impl_id);
    self.trait_to_impl_bindings_helper(
        trait_id,
        impl_id,
        &trait_impl.borrow().trait_generics,
        impl_self_type,
        recursion_limit,
        visited,
        bindings,
    );
}
Ok((TraitImplKind::Prepared { impl_id, ordered_generics }, _)) => {
    self.trait_to_impl_bindings_helper(
        trait_id,
        impl_id,
        &ordered_generics,
        impl_self_type,
        recursion_limit,
        visited,
        bindings,
    );
}
```

The only difference is that in Normal we reach for the stored trait impl to get the trait generics, while in Prepared we have it in the trait impl kind itself.

# 2

```noir
TraitImplKind::Normal(id) => {
    let shared_impl = self.get_trait_implementation(*id);
    let shared_impl = shared_impl.borrow();
    let named = self.get_associated_types_for_impl(*id).to_vec();
    let ordered = shared_impl.trait_generics.clone();
    TraitGenerics { named, ordered }
}
TraitImplKind::Prepared { impl_id, ordered_generics } => {
    let named = self.get_associated_types_for_impl(*impl_id).to_vec();
    let ordered = ordered_generics.clone();
    TraitGenerics { named, ordered }
}
```

It's the same as above: we reach for the shared impl to get the generics, instead of having them directly in the prepared one.

Then I wonder if we could either use the shared impl in both cases... or maybe at that point the shared impl doesn't exist. So maybe we can also store a trait impl ordered generics separately from the trait impl, like how associated types are? That way we can look up in that map in both cases.

That said, I'm sure I'm also missing some other difference.

File: compiler/noirc_frontend/src/hir_def/types.rs (hunk 7 above)
Comment (aakoshh) [reply compiler/noirc_frontend/src/hir_def/types.rs:3014]: I added recursion protection because I thought it must be causing https://github.com/noir-lang/noir/issues/11491 but that wasn't the case. I followed this pattern based on some of the other type traversal methods, like `follow_bindings`. I see massively refactored recursion 😳 

But I don't see how it could be limited just to `DataType`s; for example the unit test above creates a chain of `TypeAlias`ses which, if `visit`ed, would blow the stack with no `DataType` in sight. It's an artificial case, no doubt about that, but if we keep making these as test cases, I'm not sure how to avoid what this does. 

Perhaps a more general type traversal context could be keeping track of both recursion depth as well as the types encountered.

Comment (asterite) [reply compiler/noirc_frontend/src/hir_def/types.rs:3014]: Sounds good. Yes, the TypeAlias case is true. However, when I tried it it didn't blow up, I'm not sure why (that is, in the other PR where I made that change). I'll try to figure out why next week.

**Comment by aakoshh** [comment]
> Then I wonder if we could either use the shared impl in both cases... or maybe at that point the shared impl doesn't exist. 

That is indeed the reason why I needed the new one. Perhaps my comment shows where these come into existence: https://github.com/noir-lang/noir/pull/11417#discussion_r2758837767

The shared `TraitImpl` won't be available until `collect_trait_impl` is called by `Elaborator::elaborate_items`, whereas _just_ the associated types are inserted by `resolve_trait_impl_associated_types`, where we already know the `TraitImplId`, but I guess not all the other stuff needed to produce a full `TraitImpl`. By keeping the associated types in a map it was able to look it up for _self only_ in `define_function_metas_for_functions`, but not for other traits. 

My change is to do insert the associated types first for _every_ trait, and then go define the metas. I chose to add the new `TraitImplKind` to piggy back on `lookup_trait_implementation`. I had to keep the `ordered_generics` on it because they are required for the matching, and had nowhere else to go. 

The only reason associated types they were kept separate from `Normal` in the `NodeInterner` was so they can be looked up before `Normal` was available. I suppose we could also intern the ordered generics, since they too, are required.

**Comment by aakoshh** [comment]
Perhaps by interning the ordered generics, we could keep only the `Normal` one, but insert it as soon as it's been prepared, except I don't know if at any point the code assumes that if we have a `Normal` one then it 100% should be able to retrieve the `TraitImpl`. From that perspective, maybe for the sake of clarity keeping both, even if they were both just IDs, is not a bad thing. OTOH keeping only one would mean I wouldn't have to work so hard to _remove_ the `Prepared` one.

**Comment by aakoshh** [comment]
One difference between `add_trait_implementation` and `add_preapred_trait_implementation` is that the former does this:
```
// The object type is generalized so that a generic impl will apply
// to any type T, rather than just the generic type named T.
let generalized_object_type = object_type.generalize_from_substitutions(substitutions);
```
I didn't do that, not sure what the effect of it would be on the prepared stage. Maybe I should have. But I didn't investigate how to get the `substitutions`, `collect_trait_impl` is complicated, although the input seems to be just `self.generics`, but then `add_trait_implementation` does things to it I haven't grokked.

File: compiler/noirc_frontend/src/hir_def/types.rs (hunk 7 above)
Comment (asterite) [reply compiler/noirc_frontend/src/hir_def/types.rs:3014]: Hm, `extreme_type_alias_chain_stack_overflow` in frontend tests fails for me. I wonder if I broke it in that PR... and why it didn't break CI.

Comment (asterite) [reply compiler/noirc_frontend/src/hir_def/types.rs:3014]: I mean in `master`, not in this PR (or, well, I didn't try). Just saying that maybe what I did in that other PR isn't completely right, as you mentioned.

Comment (aakoshh) [reply compiler/noirc_frontend/src/hir_def/types.rs:3014]: > in frontend tests fails for me... I mean in master,

Yes, that's what Michael said as well. I assume it's due to a difference in stack memory size used on CI: 
https://github.com/noir-lang/noir/blob/f1db9754dd26736a9bdbfd41c5ce15fe5d62ba6b/.github/workflows/test-rust-workspace-msrv.yml#L100

**Review by asterite — APPROVED** [review]
Looks great! Though I'd prefer someone else to review this too because the changes here are significant.

**Comment by aakoshh** [comment]
As it happens, the changes in this PR alone removed the need for the controversial workaround that it originally inherited from https://github.com/noir-lang/noir/pull/11383 so at least it's not forcing in something we know is unwanted. 

The only downside I see is the duplication of the `where` clause, for which I'll open a follow up ticket. 

Other than that, I think this should be safe to merge, as we all agreed the way it was handling lookups for self-type of traits was broken. I'd rather get this in before the code starts to accumulate conflicts.
