### PR TITLE
fix: share closure environment for constrained/unconstrained variants of a lambda function

### LINKED ISSUE #10556: Set locations in monomorphizer function `lambda_with_setup`
### Problem

In [`lambda_with_setup`](https://github.com/noir-lang/noir/blob/ed5853fd1204c91bff3eca421c7f3b11159a3dc7/compiler/noirc_frontend/src/monomorphization/mod.rs#L2253) in `monomorphization/mod.rs`:

https://github.com/noir-lang/noir/blob/ed5853fd1204c91bff3eca421c7f3b11159a3dc7/compiler/noirc_frontend/src/monomorphization/mod.rs#L2323

https://github.com/noir-lang/noir/blob/ed5853fd1204c91bff3eca421c7f3b11159a3dc7/compiler/noirc_frontend/src/monomorphization/mod.rs#L2350

### Happy Case

Ensure that those locations match the location of the lambda expression

### Workaround

None

### Workaround Description

_No response_

### Additional Context

_No response_

### Project Impact

Nice-to-have

### Blocker Context

_No response_

### Would you like to submit a PR for this Issue?

None

### Support Needs

_No response_

### LINKED ISSUE #11205: Closure chains cause exponential type blowup during monomorphization
### Aim

Take a program that has 11 levels of a closure chain
```rust
#[test]
fn closure_capture_chain_oom() {
    let src = "
    fn main() {
        let x: Field = 1;
        let f0 = || x;
        let f1 = || f0();
        let f2 = || f1();
        let f3 = || f2();
        let f4 = || f3();
        let f5 = || f4();
        let f6 = || f5();
        let f7 = || f6();
        let f8 = || f7();
        let f9 = || f8();
        let f10 = || f9();
        let _ = f10();
    }
    ";
    let _ = get_monomorphized(&code);
}
```
The following test will fail when memory is limited to 8 GB.

We can see how types blow up with a smaller example and running `nargo compile --show-monomorphized`:
```noir
fn main() {
    let x: Field = 1;
    let f0 = || x;
    let f1 = || f0();
    let f2 = || f1();
    let _ = || f2();
}
```
Produces the following output:
<details><summary>Details</summary>
<p>

```
fn main$f0() -> () {
    let x$l0 = 1;
    let f0$l5 = ({
        let closure_variable$l2 = {
            let env$l1 = (x$l0);
            (env$l1, lambda$f1)
        };
        closure_variable$l2
    }, {
        let closure_variable$l4 = {
            let env$l3 = (x$l0);
            (env$l3, lambda$f2)
        };
        closure_variable$l4
    });
    let f1$l12 = ({
        let closure_variable$l8 = {
            let env$l6 = (f0$l5);
            (env$l6, lambda$f3)
        };
        closure_variable$l8
    }, {
        let closure_variable$l11 = {
            let env$l9 = (f0$l5);
            (env$l9, lambda$f4)
        };
        closure_variable$l11
    });
    let f2$l19 = ({
        let closure_variable$l15 = {
            let env$l13 = (f1$l12);
            (env$l13, lambda$f5)
        };
        closure_variable$l15
    }, {
        let closure_variable$l18 = {
            let env$l16 = (f1$l12);
            (env$l16, lambda$f6)
        };
        closure_variable$l18
    });
    let _$l26 = ({
        let closure_variable$l22 = {
            let env$l20 = (f2$l19);
            (env$l20, lambda$f7)
        };
        closure_variable$l22
    }, {
        let closure_variable$l25 = {
            let env$l23 = (f2$l19);
            (env$l23, lambda$f8)
        };
        closure_variable$l25
    })
}
fn lambda$f1(mut env$l1: (Field,)) -> Field {
    env$l1.0
}
unconstrained fn lambda$f2(mut env$l3: (Field,)) -> Field {
    env$l3.0
}
fn lambda$f3(mut env$l6: ((((Field,), fn() -> Field with closure environment (Field,)), ((Field,), unconstrained fn() -> Field with closure environment (Field,))),)) -> Field {
    let tmp$l7 = env$l6.0.0;
    tmp$l7.1(tmp$l7.0)
}
unconstrained fn lambda$f4(mut env$l9: ((((Field,), fn() -> Field with closure environment (Field,)), ((Field,), unconstrained fn() -> Field with closure environment (Field,))),)) -> Field {
    let tmp$l10 = env$l9.0.1;
    tmp$l10.1(tmp$l10.0)
}
fn lambda$f5(mut env$l13: (((((((Field,), fn() -> Field with closure environment (Field,)), ((Field,), unconstrained fn() -> Field with closure environment (Field,))),), fn() -> Field with closure environment ((((Field,), fn() -> Field with closure environment (Field,)), ((Field,), unconstrained fn() -> Field with closure environment (Field,))),)), (((((Field,), fn() -> Field with closure environment (Field,)), ((Field,), unconstrained fn() -> Field with closure environment (Field,))),), unconstrained fn() -> Field with closure environment ((((Field,), fn() -> Field with closure environment (Field,)), ((Field,), unconstrained fn() -> Field with closure environment (Field,))),))),)) -> Field {
    let tmp$l14 = env$l13.0.0;
    tmp$l14.1(tmp$l14.0)
}
unconstrained fn lambda$f6(mut env$l16: (((((((Field,), fn() -> Field with closure environment (Field,)), ((Field,), unconstrained fn() -> Field with closure environment (Field,))),), fn() -> Field with closure environment ((((Field,), fn() -> Field with closure environment (Field,)), ((Field,), unconstrained fn() -> Field with closure environment (Field,))),)), (((((Field,), fn() -> Field with closure environment (Field,)), ((Field,), unconstrained fn() -> Field with closure environment (Field,))),), unconstrained fn() -> Field with closure environment ((((Field,), fn() -> Field with closure environment (Field,)), ((Field,), unconstrained fn() -> Field with closure environment (Field,))),))),)) -> Field {
    let tmp$l17 = env$l16.0.1;
    tmp$l17.1(tmp$l17.0)
}
fn lambda$f7(mut env$l20: ((((((((((Field,), fn() -> Field with closure environment (Field,)), ((Field,), unconstrained fn() -> Field with closure environment (Field,))),), fn() -> Field with closure environment ((((Field,), fn() -> Field with closure environment (Field,)), ((Field,), unconstrained fn() -> Field with closure environment (Field,))),)), (((((Field,), fn() -> Field with closure environment (Field,)), ((Field,), unconstrained fn() -> Field with closure environment (Field,))),), unconstrained fn() -> Field with closure environment ((((Field,), fn() -> Field with closure environment (Field,)), ((Field,), unconstrained fn() -> Field with closure environment (Field,))),))),), fn() -> Field with closure environment (((((((Field,), fn() -> Field with closure environment (Field,)), ((Field,), unconstrained fn() -> Field with closure environment (Field,))),), fn() -> Field with closure environment ((((Field,), fn() -> Field with closure environment (Field,)), ((Field,), unconstrained fn() -> Field with closure environment (Field,))),)), (((((Field,), fn() -> Field with closure environment (Field,)), ((Field,), unconstrained fn() -> Field with closure environment (Field,))),), unconstrained fn() -> Field with closure environment ((((Field,), fn() -> Field with closure environment (Field,)), ((Field,), unconstrained fn() -> Field with closure environment (Field,))),))),)), ((((((((Field,), fn() -> Field with closure environment (Field,)), ((Field,), unconstrained fn() -> Field with closure environment (Field,))),), fn() -> Field with closure environment ((((Field,), fn() -> Field with closure environment (Field,)), ((Field,), unconstrained fn() -> Field with closure environment (Field,))),)), (((((Field,), fn() -> Field with closure environment (Field,)), ((Field,), unconstrained fn() -> Field with closure environment (Field,))),), unconstrained fn() -> Field with closure environment ((((Field,), fn() -> Field with closure environment (Field,)), ((Field,), unconstrained fn() -> Field with closure environment (Field,))),))),), unconstrained fn() -> Field with closure environment (((((((Field,), fn() -> Field with closure environment (Field,)), ((Field,), unconstrained fn() -> Field with closure environment (Field,))),), fn() -> Field with closure environment ((((Field,), fn() -> Field with closure environment (Field,)), ((Field,), unconstrained fn() -> Field with closure environment (Field,))),)), (((((Field,), fn() -> Field with closure environment (Field,)), ((Field,), unconstrained fn() -> Field with closure environment (Field,))),), unconstrained fn() -> Field with closure environment ((((Field,), fn() -> Field with closure environment (Field,)), ((Field,), unconstrained fn() -> Field with closure environment (Field,))),))),))),)) -> Field {
    let tmp$l21 = env$l20.0.0;
    tmp$l21.1(tmp$l21.0)
}
unconstrained fn lambda$f8(mut env$l23: ((((((((((Field,), fn() -> Field with closure environment (Field,)), ((Field,), unconstrained fn() -> Field with closure environment (Field,))),), fn() -> Field with closure environment ((((Field,), fn() -> Field with closure environment (Field,)), ((Field,), unconstrained fn() -> Field with closure environment (Field,))),)), (((((Field,), fn() -> Field with closure environment (Field,)), ((Field,), unconstrained fn() -> Field with closure environment (Field,))),), unconstrained fn() -> Field with closure environment ((((Field,), fn() -> Field with closure environment (Field,)), ((Field,), unconstrained fn() -> Field with closure environment (Field,))),))),), fn() -> Field with closure environment (((((((Field,), fn() -> Field with closure environment (Field,)), ((Field,), unconstrained fn() -> Field with closure environment (Field,))),), fn() -> Field with closure environment ((((Field,), fn() -> Field with closure environment (Field,)), ((Field,), unconstrained fn() -> Field with closure environment (Field,))),)), (((((Field,), fn() -> Field with closure environment (Field,)), ((Field,), unconstrained fn() -> Field with closure environment (Field,))),), unconstrained fn() -> Field with closure environment ((((Field,), fn() -> Field with closure environment (Field,)), ((Field,), unconstrained fn() -> Field with closure environment (Field,))),))),)), ((((((((Field,), fn() -> Field with closure environment (Field,)), ((Field,), unconstrained fn() -> Field with closure environment (Field,))),), fn() -> Field with closure environment ((((Field,), fn() -> Field with closure environment (Field,)), ((Field,), unconstrained fn() -> Field with closure environment (Field,))),)), (((((Field,), fn() -> Field with closure environment (Field,)), ((Field,), unconstrained fn() -> Field with closure environment (Field,))),), unconstrained fn() -> Field with closure environment ((((Field,), fn() -> Field with closure environment (Field,)), ((Field,), unconstrained fn() -> Field with closure environment (Field,))),))),), unconstrained fn() -> Field with closure environment (((((((Field,), fn() -> Field with closure environment (Field,)), ((Field,), unconstrained fn() -> Field with closure environment (Field,))),), fn() -> Field with closure environment ((((Field,), fn() -> Field with closure environment (Field,)), ((Field,), unconstrained fn() -> Field with closure environment (Field,))),)), (((((Field,), fn() -> Field with closure environment (Field,)), ((Field,), unconstrained fn() -> Field with closure environment (Field,))),), unconstrained fn() -> Field with closure environment ((((Field,), fn() -> Field with closure environment (Field,)), ((Field,), unconstrained fn() -> Field with closure environment (Field,))),))),))),)) -> Field {
    let tmp$l24 = env$l23.0.1;
    tmp$l24.1(tmp$l24.0)
}
```

</p>
</details> 

### Expected Behavior

I would expect the code above to compile. This is a flat closure chain where each closure captures and calls the previous one.

Closure chains are a very common pattern (e.g., middleware pattern, callback handlers, iterators). The minimal example above should not trigger an OOM on 8 GB and users should be able to utilize long closure chains.

### Bug

OOM crash on 8 GB:
```
memory allocation of 96 bytes failed
[1]    310290 IOT instruction (core dumped)  bash -c 
```

Closure chains are much more realistic than deeply nested closures (https://github.com/noir-lang/noir/issues/11204). It is also different than https://github.com/noir-lang/noir/issues/11174 where we have a contrived example of type size blowup. In https://github.com/noir-lang/noir/issues/11174 we can defend against type blow-ups with an error limit of some kind. Usually, we can assume that a type blow-up is unintended and thus it is ok to error. 

However, a flat chain of closures is something we should allow and the fact that the type representation blows up is not desired. We probably need some solution that changes how closure envs are represented. Right now, a closure will take the full type of the captured closure in its env. 

I confirmed we enter monomorphization with a debug statement and running the test with `--nocapture`. 

### To Reproduce

On Ubuntu 24

1. Paste the unit test above into the monomorphization unit tests module
2. cargo test -p noirc_frontend --lib --no-run
3. Fetch the commit from the executable (Executable unittests src/lib.rs (target/debug/deps/noirc_frontend-8d6e7e33bab84c72))
4. Run `bash -c 'ulimit -v 8000000 && ./target/debug/deps/noirc_frontend-8d6e7e33bab84c72 closure_capture_chain_oom'` with the relevant commit. This runs the test with a 8 GB limit.

### Workaround

None

### Workaround Description

_No response_

### Additional Context

_No response_

### Project Impact

Blocker

### Blocker Context

It is only a blocker for API designs that utilize closure chains as in the snippet above.

### Nargo Version

nargo version = 1.0.0-beta.17 noirc version = 1.0.0-beta.17+c2b99a8593d70abda260c91ca51a69ff8e10ca2d (git version hash: c2b99a8593d70abda260c91ca51a69ff8e10ca2d, is dirty: false)

### NoirJS Version

_No response_

### Proving Backend Tooling & Version

_No response_

### Would you like to submit a PR for this Issue?

None

### Support Needs

_No response_

### PR DESCRIPTION
**Pull request by guipublic**
# Description

## Problem

Resolves #11205
Also fix #10556

## Summary
Share the environment between constrained and unconstrained variants to avoid exponential blowup.

## User Documentation

Check one:
- [X] No user documentation needed.
- [ ] Changes in _docs/_ included in this PR.
- [ ] **[For Experimental Features]** Changes in _docs/_ to be submitted in a separate PR.

# PR Checklist

- [X] I have tested the changes locally.
- [X] I have formatted the changes with [Prettier](https://prettier.io/) and/or `cargo fmt` on default settings.

### CODE REVIEW

File: compiler/noirc_frontend/src/monomorphization/mod.rs [hunk 1]
```diff
@@ -2474,79 +2458,163 @@ impl<'interner> Monomorphizer<'interner> {
...
+            true,
         );
-        let lambda_fn = ast::Expression::Ident(ast::Ident {
-            definition: Definition::Function(id),
+
+        // Build closure tuples: (env, fn) for each variant
+        let constrained_closure_typ =
+            ast::Type::Tuple(vec![env_typ.clone(), constrained_fn_typ.clone()]);
+        let unconstrained_closure_typ =
+            ast::Type::Tuple(vec![env_typ.clone(), unconstrained_fn_typ.clone()]);
```
Comment (aakoshh) [inline compiler/noirc_frontend/src/monomorphization/mod.rs]: Maybe this `.clone()` can be removed?

Comment (aakoshh) [reply compiler/noirc_frontend/src/monomorphization/mod.rs]: In any case, does this mean it wasn't a "type explosion" but rather an AST explosion? As I understand, previously we had 2 separate `env` tuples, each capturing the same variables from various lambda contexts, and now we only have one, but their types are the same? Or was there an exponential profusion of the types in the tuples itself?

Comment (guipublic) [reply compiler/noirc_frontend/src/monomorphization/mod.rs]: Yes there is also an exponential blowup for the types, and this PR only deal with the environments. My first implementation tried to handle the types but it did not work out. The type is not used too much, mainly for type checking, so for example the test case from the issue is working properly.

File: compiler/noirc_frontend/src/monomorphization/mod.rs [hunk 2]
```diff
@@ -2489,79 +2473,163 @@ impl<'interner> Monomorphizer<'interner> {
...
+                name: lambda_name.to_owned(),
+                parameters: unconstrained_params,
+                body: unconstrained_body,
+                return_type: ret_type.clone(),
+                return_visibility: Visibility::Private,
+                unconstrained: true,
+                inline_type: InlineType::default(),
+                is_entry_point: false,
+            };
+            self.push_function(unconstrained_id, unconstrained_fn);
```
Comment (asterite) [inline compiler/noirc_frontend/src/monomorphization/mod.rs]: This looks to be a duplicate of the above, with slight changes.

I wonder if we could do it this way:
1. Keep `constrained_fn` and only push functions after this `if` statement
2. In the `else` branch here, clone `constrained_fn` and only modify the properties that are different
3. Finally push both functions

Comment (asterite) [reply compiler/noirc_frontend/src/monomorphization/mod.rs]: This is optional, though, I'm not sure it's possible, and also it's not a lot of duplicated code so it's fine.

Comment (guipublic) [reply compiler/noirc_frontend/src/monomorphization/mod.rs]: Done
