### PR TITLE
fix: unconstrained fn mismatch is now a warning

### LINKED ISSUE #5763: Passing a `unconstrained fn` to an argument that expects `fn` errors
### Aim

Passing a `unconstrained fn` to an argument that expects `fn` shouldn't be allowed, but currently it errors instead of giving a warning.

### Expected Behavior

This code:

```rust
fn main() {
    foo(baz);
}

fn foo(f: fn(i32) -> i32) -> i32 {
    f(1)
}

unconstrained fn baz(x: i32) -> i32 {
    x + 1
}
```

gives a warning, not an error.

### Bug

The code gives an error.

### To Reproduce

1.
2.
3.
4.

### Workaround

None

### Workaround Description

_No response_

### Additional Context

_No response_

### Project Impact

None

### Blocker Context

_No response_

### Nargo Version

_No response_

### NoirJS Version

_No response_

### Proving Backend Tooling & Version

_No response_

### Would you like to submit a PR for this Issue?

None

### Support Needs

_No response_

### PR DESCRIPTION
**Pull request by asterite**
# Description

## Problem

Resolves #5763

## Summary

This code is handled differently than the other `unsafe` checks, and I forgot about that.

## Additional Context

This issue is preventing noir syncs on Aztec Packages.

## Documentation

Check one:
- [x] No documentation needed.
- [ ] Documentation included in this PR.
- [ ] **[For Experimental Features]** Documentation to be submitted in a separate PR.

# PR Checklist

- [x] I have tested the changes locally.
- [x] I have formatted the changes with [Prettier](https://prettier.io/) and/or `cargo fmt` on default settings.

### CODE REVIEW

File: compiler/noirc_frontend/src/hir_def/types.rs [hunk 1]
```diff
@@ -1792,28 +1799,42 @@ impl Type {
...
-                .then(|| Type::Function(params, ret, env, unconstrained_expected))
+            let coerced_type = Type::Function(params, ret, env, unconstrained_expected);
+
+            if !unconstrained_self && unconstrained_expected {
+                FunctionCoercionResult::Coerced(coerced_type)
+            } else if unconstrained_self != unconstrained_expected {
+                FunctionCoercionResult::UnconstrainedMismatch(coerced_type)
+            } else {
+                FunctionCoercionResult::NoCoercion
+            }
```
Comment (TomAFrench) [inline compiler/noirc_frontend/src/hir_def/types.rs:1835]:
```suggestion
            match (unconstrained_self, unconstrained_expected) {
                (true, true) | (false, false) => FunctionCoercionResult::NoCoercion,
                (false, true) => FunctionCoercionResult::Coerced(coerced_type)
                (true, false) => FunctionCoercionResult::UnconstrainedMismatch(coerced_type)
            }
```

I find that `match` statements are good for this kind of logic rather than if-else chains.

**Review by TomAFrench — APPROVED** [review]
