### PR TITLE
fix(ssa): Do not use inner else condition when collapsing IfElse based upon the then condition

### LINKED ISSUE #7961: ACIR and Brillig return different values (involves indexing arrays and conditions)
### Aim

Potentially related to https://github.com/noir-lang/noir/issues/7952

Another program discovered by the AST fuzzer in https://github.com/noir-lang/noir/pull/7890, minimised by hand:

`main.nr`:
```rust
fn main(a: bool, b: [[bool; 2]; 3]) -> pub [bool; 2] {
    if (!(!a)) {
        if (!(!a)) {
            b[0]
        } else {
            b[0]
        }
    } else {
        b[0]
    }
}
```

`Prover.toml`:
```
a = 0
b = [[1, 0], [1, 0], [1, 1]]

return = [1, 0]
```

### Expected Behavior

The circuit should return `[1, 0]` on all paths, regardless of the value of `a`.

### Bug

ACIR returns `[0, 0]`, Brillig is fine. With `a = 1` ACIR is fine as well, and also if the outer layer of `if` is removed.

```console
bash-5.2$ nargo execute
[regression_fuzz_testing] Circuit witness successfully solved
[regression_fuzz_testing] Witness saved to target/regression_fuzz_testing.gz
[regression_fuzz_testing] Circuit output: Vec([Field(0), Field(0)])
Unexpected return value: expected Vec([Field(1), Field(0)]); got Some(Vec([Field(0), Field(0)]))

bash-5.2$ nargo execute --force-brillig
[regression_fuzz_testing] Circuit witness successfully solved
[regression_fuzz_testing] Witness saved to target/regression_fuzz_testing.gz
[regression_fuzz_testing] Circuit output: Vec([Field(1), Field(0)])
```

Looking at the SSA, something goes wrong in `Remove IfElse`:
```console
bash-5.2$ nargo compile --show-ssa
After Initial SSA:
acir(inline) fn main f0 {
  b0(v0: u1, v1: [[u1; 2]; 3]):
    v4 = not v0
    jmpif v0 then: b1, else: b2
  b1():
    v7 = not v0
    jmpif v0 then: b3, else: b4
  b2():
    v6 = array_get v1, index u32 0 -> [u1; 2]
    jmp b6(v6)
  b3():
    v9 = array_get v1, index u32 0 -> [u1; 2]
    jmp b5(v9)
  b4():
    v8 = array_get v1, index u32 0 -> [u1; 2]
    jmp b5(v8)
  b5(v2: [u1; 2]):
    jmp b6(v2)
  b6(v3: [u1; 2]):
    return v3
}
...
After Inlining (2nd):
acir(inline) pure fn main f0 {
  b0(v0: u1, v1: [[u1; 2]; 3]):
    v2 = not v0
    enable_side_effects v0
    v3 = not v0
    enable_side_effects v0
    v5 = array_get v1, index u32 0 -> [u1; 2]
    v6 = not v0
    v7 = mul v0, v6
    enable_side_effects v7
    v8 = array_get v1, index u32 0 -> [u1; 2]
    enable_side_effects v0
    v9 = if v0 then v5 else (if v7) v8
    enable_side_effects v6
    v10 = array_get v1, index u32 0 -> [u1; 2]
    enable_side_effects u1 1
    v12 = if v0 then v5 else (if v7) v10
    return v12
}

After Remove IfElse:
acir(inline) pure fn main f0 {
  b0(v0: u1, v1: [[u1; 2]; 3]):
    v2 = not v0
    enable_side_effects v0
    v3 = not v0
    enable_side_effects v0
    v5 = array_get v1, index u32 0 -> [u1; 2]
    v6 = not v0
    v7 = mul v0, v6
    enable_side_effects v7
    v8 = array_get v1, index u32 0 -> [u1; 2]
    enable_side_effects v0
    v10 = array_get v5, index Field 0 -> u1
    v11 = array_get v8, index Field 0 -> u1
    v12 = mul v0, v10
    v13 = mul v7, v11
    v14 = unchecked_add v12, v13
    v16 = array_get v5, index Field 1 -> u1
    v17 = array_get v8, index Field 1 -> u1
    v18 = mul v0, v16
    v19 = mul v7, v17
    v20 = unchecked_add v18, v19
    v21 = make_array [v14, v20] : [u1; 2]
    enable_side_effects v6
    v22 = array_get v1, index u32 0 -> [u1; 2]
    enable_side_effects u1 1
    v24 = array_get v5, index Field 0 -> u1
    v25 = array_get v22, index Field 0 -> u1
    v26 = mul v0, v24
    v27 = mul v7, v25
    v28 = unchecked_add v26, v27
    v29 = array_get v5, index Field 1 -> u1
    v30 = array_get v22, index Field 1 -> u1
    v31 = mul v0, v29
    v32 = mul v7, v30
    v33 = unchecked_add v31, v32
    v34 = make_array [v28, v33] : [u1; 2]
    return v34
}
```

`v28 = v26+v27 = v0*v24 + v7*v25 = (v0 + v7) * v1[0] = (v0 + v0*v6) * v1[0] = (v0 + v0*!v0) * v1[0] = v0 * v1[0]`

It should be just `v28 = v1[0]`.

### To Reproduce

See above.

### Workaround

None

### Workaround Description

_No response_

### Additional Context

_No response_

### Project Impact

None

### Blocker Context

_No response_

### Nargo Version

nargo version = 1.0.0-beta.4 noirc version = 1.0.0-beta.4+a1f125de1e553ab33dd0291f4ff13e993f87608f (git version hash: a1f125de1e553ab33dd0291f4ff13e993f87608f, is dirty: true)

### NoirJS Version

_No response_

### Proving Backend Tooling & Version

_No response_

### Would you like to submit a PR for this Issue?

None

### Support Needs

_No response_

### PR DESCRIPTION
**Pull request by vezenovm**
# Description

## Problem\*

Resolves #7961 

The issue description is correct that the bug shows itself in the RemoveIfElse pass, however, the issue is much earlier during flattening when we are initially setting up the `IfElse` instructions. 

We can see the following SSA on master before and after flattening:
<details><summary>Details</summary>
<p>

```
After Mem2Reg (3rd):
acir(inline) pure fn main f0 {
  b0(v0: u1, v1: [[u1; 2]; 3]):
    v4 = not v0
    jmpif v0 then: b1, else: b2
  b1():
    v7 = not v0
    jmpif v0 then: b3, else: b4
  b2():
    v6 = array_get v1, index u32 0 -> [u1; 2]
    jmp b5(v6)
  b3():
    v9 = array_get v1, index u32 0 -> [u1; 2]
    jmp b6(v9)
  b4():
    v8 = array_get v1, index u32 0 -> [u1; 2]
    jmp b6(v8)
  b5(v2: [u1; 2]):
    return v2
  b6(v3: [u1; 2]):
    jmp b5(v3)
}

After Flattening:
acir(inline) pure fn main f0 {
  b0(v0: u1, v1: [[u1; 2]; 3]):
    v2 = not v0
    enable_side_effects v0
    v3 = not v0
    enable_side_effects v0
    v5 = array_get v1, index u32 0 -> [u1; 2]
    v6 = not v0
    v7 = unchecked_mul v0, v6
    enable_side_effects v7
    v8 = array_get v1, index u32 0 -> [u1; 2]
    enable_side_effects v0
    v9 = if v0 then v5 else (if v7) v8
    enable_side_effects v6
    v10 = array_get v1, index u32 0 -> [u1; 2]
    enable_side_effects u1 1
    v12 = if v0 then v5 else (if v7) v10
    return v12
}
```

</p>
</details> 

We have two if-else instructions that use the same conditions:
```
    enable_side_effects v0
    v9 = if v0 then v5 else (if v7) v8
    enable_side_effects v6
    v10 = array_get v1, index u32 0 -> [u1; 2]
    enable_side_effects u1 1
    v12 = if v0 then v5 else (if v7) v10
``` 
However, the second one should not have `else (if v7)` it should be `else (if v6)`.

## Summary\*

We keep the original else condition when collapse and if else based upon the then condition.
Comparing to the SSA post flattening above we now have this SSA:
```
After Flattening:
acir(inline) pure fn main f0 {
  b0(v0: u1, v1: [[u1; 2]; 3]):
    v2 = not v0
    enable_side_effects v0
    v3 = not v0
    enable_side_effects v0
    v5 = array_get v1, index u32 0 -> [u1; 2]
    v6 = not v0
    v7 = unchecked_mul v0, v6
    enable_side_effects v7
    v8 = array_get v1, index u32 0 -> [u1; 2]
    enable_side_effects v0
    v9 = if v0 then v5 else (if v7) v8
    enable_side_effects v6
    v10 = array_get v1, index u32 0 -> [u1; 2]
    enable_side_effects u1 1
    v12 = if v0 then v5 else (if v6) v10
    return v12
}
```
You will note that the last if-else has `else (if v6)` instead of `v7`. 

Still a draft as I want to add a test for when we collapse the else value where we are still using 

## Additional Context

Some extra info regarding a nested if-else with the else block value: https://github.com/noir-lang/noir/pull/8040#discussion_r2040252375

## Documentation\*

Check one:
- [X] No documentation needed.
- [ ] Documentation included in this PR.
- [ ] **[For Experimental Features]** Documentation to be submitted in a separate PR.

# PR Checklist\*

- [X] I have tested the changes locally.
- [X] I have formatted the changes with [Prettier](https://prettier.io/) and/or `cargo fmt` on default settings.

### CODE REVIEW

File: compiler/noirc_evaluator/src/ssa/ssa_gen/mod.rs [hunk 1]
```diff
@@ -687,6 +687,7 @@ impl FunctionContext<'_> {
     /// ```
     fn codegen_if(&mut self, if_expr: &ast::If) -> Result<Values, RuntimeError> {
         let condition = self.codegen_non_tuple_expression(&if_expr.condition)?;
+
```
Comment (vezenovm) [inline compiler/noirc_evaluator/src/ssa/ssa_gen/mod.rs:690]:
```suggestion
```

File: compiler/noirc_evaluator/src/ssa/opt/flatten_cfg.rs [hunk 2]
```diff
@@ -648,6 +648,7 @@ impl<'f> Context<'f> {
                 self.inserter.function.dfg.make_constant(FieldElement::one(), NumericType::bool())
             }
         };
+
```
Comment (vezenovm) [inline compiler/noirc_evaluator/src/ssa/opt/flatten_cfg.rs:651]:
```suggestion
```

File: compiler/noirc_evaluator/src/ssa/ir/dfg/simplify.rs [hunk 3]
```diff
@@ -259,7 +257,7 @@ pub(crate) fn simplify(
                         let instruction = Instruction::IfElse {
                             then_condition,
                             then_value,
-                            else_condition: inner_else_condition,
+                            else_condition,
```
[the remark this answers is not in the document]
Comment (vezenovm) [reply compiler/noirc_evaluator/src/ssa/ir/dfg/simplify.rs:260]: Maybe we can try to fuzz some if exprs like the one above @aakoshh

**Review by TomAFrench — CHANGES_REQUESTED** [review]
Can you create a more focused SSA regression test for this?

**Comment by asterite** [comment]
@vezenovm Support for parsing `if ... else` in the SSA parser was missing so I added it and updated this branch so you can now write tests with that.

Also, if it's not too much to ask, could you add general tests for `if ... else`? There are none right now and it would be nice to see how it works through examples. I have a [PR](https://github.com/noir-lang/noir/pull/8041) where I try to move away from `set_value_from_id` and the SSA for some programs changes and I don't understand if it's a bug in the new code or the old one.

**Comment by vezenovm** [comment]
> Also, if it's not too much to ask, could you add general tests for `if ... else`? There are none right now and it would be nice to see how it works through examples. I have a [PR](https://github.com/noir-lang/noir/pull/8041) where I try to move away from `set_value_from_id` and the SSA for some programs changes and I don't understand if it's a bug in the new code or the old one.

Thanks for the parser update! And yes I can add some general tests for IfElse, I'll do it in a separate PR.

**Review by jfecher — APPROVED** [review]
LGTM

**Review by TomAFrench — APPROVED** [review]
