### PR TITLE
fix: for `T::Assoc` search trait bounds instead of trait associated types

### LINKED ISSUE #11545: `T::AssociatedType` shorthand fails in type positions (return, parameter, local variable, struct field, impl method)
## Description                                                                                                                                                                                               

  The `T::AssociatedType` shorthand syntax (e.g., `T::Output` instead of `<T as Trait>::Output`) fails in most type positions outside of where clauses. The fully-qualified `<T as Trait>::Output` syntax works
   correctly, but the shorthand produces errors.

  **Affected positions:**
  - Function return types: `fn foo<T>(t: T) -> T::Output`
  - Function parameter types: `fn foo<T>(t: T, key: T::Key)`
  - Local variable type annotations: `let x: T::Item = ...`
  - Struct field types: `struct Derived<T> { val: T::Item }`
  - Method return types in generic impl blocks: `fn process(self) -> T::Item`

  For return types, the error is particularly confusing: "expected type `<T as Trait>::Output`, found type `<T as Trait>::Output`" — both sides appear identical but the compiler treats them as distinct types
   that fail to unify.

  ## Reproduction

  ```noir
  trait HasItem {
      type Item;
      fn item(self) -> Self::Item;
  }

  impl HasItem for Field {
      type Item = bool;
      fn item(self) -> Self::Item {
          true
      }
  }

  // Using T::Item shorthand in return type fails
  fn get_item<T>(t: T) -> T::Item where T: HasItem {
      t.item()
  }

  // Workaround: use fully-qualified syntax
  // fn get_item<T>(t: T) -> <T as HasItem>::Item where T: HasItem {
  //     t.item()
  // }

  fn main() {
      let _ = get_item(1 as Field);
  }
```

  Relevant should_panic tests

  - tests::traits::trait_associated_items::associated_type_shorthand_in_return_type
  - tests::traits::trait_associated_items::associated_type_shorthand_in_return_type_with_trait_having_constant
  - tests::traits::trait_associated_items::associated_type_shorthand_simple_identity
  - tests::traits::trait_associated_items::associated_type_of_generic_in_param_position
  - tests::traits::trait_associated_items::associated_type_shorthand_in_param_position
  - tests::traits::trait_associated_items::associated_type_in_generic_function_local_var
  - tests::traits::trait_associated_items::associated_type_shorthand_used_as_struct_field_type
  - tests::traits::trait_associated_items::generic_impl_with_associated_type_in_method_signature

  ---

### LINKED ISSUE #11546: Where clause constraining `T::AssociatedType` shorthand is ignored for method resolution
## Description

  When a where clause uses the `T::AssociatedType` shorthand to constrain an associated type (e.g., `C::Elem: Printable`), the compiler ignores the constraint for method resolution. This means methods from
  the constraining trait are not found on the associated type.

  The fully-qualified syntax `<C as Collection>::Elem: Printable` also fails in this position — the compiler does not use the constraint to resolve method calls on the associated type value.

  ## Reproduction

  ```noir
  trait Collection {
      type Elem;
      fn first(self) -> Self::Elem;
  }

  trait Printable {
      fn to_field(self) -> Field;
  }

  struct Bag {
      item: Field,
  }

  impl Collection for Bag {
      type Elem = Field;
      fn first(self) -> Self::Elem {
          self.item
      }
  }

  impl Printable for Field {
      fn to_field(self) -> Field {
          self
      }
  }

  fn first_as_field<C>(c: C) -> Field
  where
      C: Collection,
      C::Elem: Printable,  // This constraint is ignored
  {
      c.first().to_field()  // Error: no method `to_field` found
  }

  fn main() {
      let b = Bag { item: 42 };
      assert(first_as_field(b) == 42);
  }
```

  Relevant should_panic tests

  - tests::traits::trait_bounds::where_clause_on_associated_type_shorthand_ignored
  - tests::traits::trait_bounds::where_clause_on_associated_type_shorthand_in_function
  - tests::traits::trait_bounds::multiple_associated_types_in_where_clause
  - tests::traits::trait_bounds::where_clause_on_associated_type_of_generic_in_trait_impl

### LINKED ISSUE #11550: ICE when returning tuple containing `T::AssociatedType`
## Description

  Using `T::AssociatedType` shorthand inside a tuple return type causes an internal compiler error (ICE) with the message: "expected some trait_method_id when use_impl is true". This is a crash rather than a
   type error — the compiler panics during elaboration.

  ## Reproduction

  ```noir
  trait HasOutput {
      type Out;
      fn produce(self) -> Self::Out;
  }

  impl HasOutput for Field {
      type Out = bool;
      fn produce(self) -> Self::Out {
          self != 0
      }
  }

  fn produce_pair<T>(a: T, b: T) -> (T::Out, T::Out) where T: HasOutput {
      (a.produce(), b.produce())
  }

  fn main() {
      let (x, y) = produce_pair(1 as Field, 0 as Field);
      assert(x);
      assert(!y);
  }
```
  Relevant should_panic tests

  - tests::traits::trait_associated_items::generic_fn_returning_tuple_with_associated_type

### PR DESCRIPTION
**Pull request by asterite**
Based on top of #11544

# Description

## Problem

Resolves #11545
Resolves #11546
Resolves #11550

## User Documentation

Check one:
- [x] No user documentation needed.
- [ ] Changes in _docs/_ included in this PR.
- [ ] **[For Experimental Features]** Changes in _docs/_ to be submitted in a separate PR.

# PR Checklist

- [x] I have tested the changes locally.
- [x] I have formatted the changes with [Prettier](https://prettier.io/) and/or `cargo fmt` on default settings.

### CODE REVIEW

**Comment by asterite** [comment]
I turned this into a draft just to avoid merging it (we should merge the base PR first)

File: compiler/noirc_frontend/src/tests/traits/trait_associated_items.rs [hunk 1]
```diff
@@ -1706,37 +1693,9 @@ fn associated_type_in_generic_function_local_var() {
...
-        val: T::Item,
-    }
-
-    fn main() {
-        let d: Derived<Field> = Derived { val: true };
-        assert(d.val);
-    }
-    "#;
-    assert_no_errors(src);
-}
```
Comment (asterite) [inline compiler/noirc_frontend/src/tests/traits/trait_associated_items.rs:1733]: I removed this test because struct where clause isn't supported in Noir. I guess AI did it as it if were Rust.

File: compiler/noirc_frontend/src/tests/traits/trait_associated_items.rs [hunk 2]
```diff
@@ -1611,8 +1600,8 @@ fn associated_type_shorthand_in_param_position() {
 
     impl Container for Bag {
         type Item = Field;
-        fn contains(self, item: Self::Item) -> bool {
-            self.val == item
```
Comment (asterite) [inline compiler/noirc_frontend/src/tests/traits/trait_associated_items.rs:1615]: The code here worked fine after this PR changes when I copied it to a file and ran `nargo compile`. The problem in the test was that `self.val == item` relies on the `Eq` trait, which doesn't exist in frontend tests. I changed this comparison to `true` because the test is really checking that `Self::Item` works in a parameter type position.

File: compiler/noirc_frontend/src/tests/traits/trait_associated_items.rs (hunk 1 above)
Comment (TomAFrench) [reply compiler/noirc_frontend/src/tests/traits/trait_associated_items.rs:1733]: Ah, apologies. I must have missed this.

**Comment by asterite** [comment]
I extracted #11562 from #11544 so we can mark the latter as fixed by this PR. #11562 is much more complex than the fix in this PR.
