### PR TITLE
fix: Various fixes for defunctionalization & brillig gen

### LINKED ISSUE #1974: Defunctionalization should ignore the runtime of the functions being called
### Problem

This is a valid structure:
```

fn increment(x: Field) -> Field {
    x + 1
}

unconstrained fn wrapper(func: fn (Field) -> Field, x: Field) -> Field {
    func(x)
}

unconstrained fn main(x: Field) -> pub Field {
    wrapper(increment, x)
}

```

### Happy Case

Should be compilable

### Alternatives Considered

_No response_

### Additional Context

_No response_

### Would you like to submit a PR for this Issue?

Yes

### Support Needs

_No response_

### LINKED ISSUE #1975: Defunctionalization breaks if a function is used both as literal and as a value
### Aim

Compiling
```

unconstrained fn increment(x: Field) -> Field {
    x + 1
}

unconstrained fn wrapper(func: fn (Field) -> Field, x: Field) -> Field {
    func(x)
}

unconstrained fn main(x: Field) -> pub Field {
    wrapper(increment, x) + increment(x)
}
```

### Expected Behavior

Should compile

### Bug

```
The application panicked (crashed).
Message:  Could not find apply function
Location: crates/noirc_evaluator/src/ssa_refactor/opt/defunctionalize.rs:177
```

### To Reproduce

1.
2.
3.
4.

### Installation Method

None

### Nargo Version

_No response_

### Additional Context

_No response_

### Would you like to submit a PR for this Issue?

Yes

### Support Needs

_No response_

### LINKED ISSUE #1976: Calling a function that returns more than two registers corrupts the registers of the caller
### Aim

Running this:
```
global VALUE_NOTE_LEN: Field = 4;

struct ValueNote {
    value: Field,
    x: Field,
    y: Field,
    is_real: bool,
}

impl ValueNote {
    fn deserialise(preimage: [Field; VALUE_NOTE_LEN]) -> Self {
        ValueNote {
            value: preimage[0],
            x: preimage[1],
            y: preimage[2],
            is_real: preimage[3] as bool,
        }
    }
}

unconstrained fn main(fields: [Field; VALUE_NOTE_LEN]) -> pub ValueNote {
    ValueNote::deserialise(fields)
}

```

### Expected Behavior

With this prover.toml :
```
fields = [0x0000000000000000000000000000000000000000000000000000000000000001, 0x0000000000000000000000000000000000000000000000000000000000000002, 0x0000000000000000000000000000000000000000000000000000000000000003, 0x0000000000000000000000000000000000000000000000000000000000000001]
```

the verifier.toml should be
```
[return]
is_real = true
value = "0x0000000000000000000000000000000000000000000000000000000000000001"
x = "0x0000000000000000000000000000000000000000000000000000000000000002"
y = "0x0000000000000000000000000000000000000000000000000000000000000003"

```

### Bug

actual returned value:
```
[return]
is_real = false
value = "0x0000000000000000000000000000000000000000000000000000000000000001"
x = "0x0000000000000000000000000000000000000000000000000000000000000002"
y = "0x0000000000000000000000000000000000000000000000000000000000000001"


```

### To Reproduce

1.
2.
3.
4.

### Installation Method

None

### Nargo Version

_No response_

### Additional Context

_No response_

### Would you like to submit a PR for this Issue?

Yes

### Support Needs

_No response_

### LINKED ISSUE #1977: Iterating with a literal range in brillig panics the compiler
### Aim

To be able to compile this:
```

unconstrained fn main() -> pub Field {
    let mut x = 0;
    for i in 0..10 {
        x += i;
    }
    x
}


```

### Expected Behavior

Should be compilable

### Bug

```
The application panicked (crashed).
Message:  internal error: entered unreachable code: Field type cannot be used with lt. This should have been caught by the frontend
Location: crates/noirc_evaluator/src/brillig/brillig_gen/brillig_block.rs:854
```

### To Reproduce

1.
2.
3.
4.

### Installation Method

None

### Nargo Version

_No response_

### Additional Context

_No response_

### Would you like to submit a PR for this Issue?

Yes

### Support Needs

_No response_

### PR DESCRIPTION
**Pull request by sirasistant**
# Description

 - Fix register overwrite when returning from functions that return more than two registers (Resolves #1976)
 - Extract convert function call to its own method
 - Allow lessthan operations for comparisons of fields issued by the compiler (loops) (Resolves #1977)
 - Refactor defunctionalization 
   - No longer try to guess runtime of callees (Resolves #1974)
   - Use Signature struct of ssa ir 
   - Fix dynamic dispatch collection
   - Fix transformation of functions as values to numeric constants (Resolves #1975)

## Documentation

- [ ] This PR requires documentation updates when merged.

  

  - [ ] I will submit a noir-lang/docs PR.

  

  - [ ] I will request for and support Dev Rel's help in documenting this PR.

  
  

## Additional Context

# PR Checklist\*

- [ ] I have tested the changes locally.
- [ ] I have formatted the changes with [Prettier](https://prettier.io/) and/or `cargo fmt` on default settings.

### CODE REVIEW

File: crates/noirc_evaluator/src/brillig/brillig_gen/brillig_block.rs [hunk 1]
```diff
@@ -697,11 +714,27 @@ impl<'block> BrilligBlock<'block> {
...
-        let left = self.convert_ssa_register_value(binary.lhs, dfg);
-        let right = self.convert_ssa_register_value(binary.rhs, dfg);
+        let mut left = self.convert_ssa_register_value(binary.lhs, dfg);
+        let mut right = self.convert_ssa_register_value(binary.rhs, dfg);
 
         let brillig_binary_op =
-            convert_ssa_binary_op_to_brillig_binary_op(binary.operator, binary_type);
+            convert_ssa_binary_op_to_brillig_binary_op(binary.operator, &binary_type);
+
+        // Some binary operations with fields are issued by the compiler, such as loop comparisons, cast those to the bit size here
```
Comment (ludamad) [inline crates/noirc_evaluator/src/brillig/brillig_gen/brillig_block.rs:723]: The use of mut variables indicates this might have some helper method possible, but just something to keep in mind for future passes

File: crates/noirc_evaluator/src/ssa_refactor/opt/defunctionalize.rs [hunk 2]
```diff
@@ -173,72 +159,129 @@ impl DefunctionalizationContext {
...
 }
 
-/// Collects all functions used as a value by their signatures
-fn find_variants(ssa: &Ssa) -> HashMap<FunctionSignature, Vec<FunctionId>> {
-    let mut variants: HashMap<FunctionSignature, Vec<FunctionId>> = HashMap::new();
-    let mut functions_used_as_values = HashSet::new();
+/// Collects all functions used as values that can be called by their signatures
+fn find_variants(ssa: &Ssa) -> HashMap<Signature, Vec<FunctionId>> {
+    let mut dynamic_dispatches: HashSet<Signature> = HashSet::new();
+    let mut functions_as_values: HashSet<FunctionId> = HashSet::new();
```
Comment (ludamad) [inline crates/noirc_evaluator/src/ssa_refactor/opt/defunctionalize.rs:171]: Wonder if this code could be more abstract, e.g. an abstraction over HashMap that has builder methods used here, but good with this for this pass

**Review by ludamad — DISMISSED** [review]
Some stuff with defunctionalize seem that they could use a pass to read less like the raw data structure manipulation operations or raw SSA traversal for function values, but I rather merge fast and let you ponder that longer

LGTM

File: crates/noirc_evaluator/src/brillig/brillig_gen/brillig_block.rs (hunk 1 above)
Comment (sirasistant) [reply crates/noirc_evaluator/src/brillig/brillig_gen/brillig_block.rs:723]: This should be removed when we stop generating Field comparisons for loops upstream, so I thought that this way it was easily removable

Comment (jfecher) [reply crates/noirc_evaluator/src/brillig/brillig_gen/brillig_block.rs:723]: This comment reads like the compiler is inserting instructions of the wrong type when creating loops. If that's the case we should fix the problem at the root rather than only fixing the brillig generated from it.

**Review by ludamad — DISMISSED** [review]

File: crates/noirc_evaluator/src/ssa_refactor/opt/defunctionalize.rs [hunk 3]
```diff
@@ -58,26 +42,35 @@ struct ApplyFunction {
...
 }
 
+fn signature_from_call_params(
+    caller: &Function,
+    params: &[ValueId],
+    results: &[ValueId],
+) -> Signature {
+    let params = vecmap(params, |param| caller.dfg.type_of_value(*param));
+    let returns = vecmap(results, |result| caller.dfg.type_of_value(*result));
+    Signature { params, returns }
```
Comment (jfecher) [inline crates/noirc_evaluator/src/ssa_refactor/opt/defunctionalize.rs:52]: Looks like mostly a copy of the From impl. Either we only need one of these or the From impl can reuse this logic.

File: crates/noirc_evaluator/src/ssa_refactor/opt/defunctionalize.rs [hunk 4]
```diff
@@ -173,72 +159,129 @@ impl DefunctionalizationContext {
...
+
+        match block.terminator() {
+            Some(TerminatorInstruction::Jmp { arguments, .. }) => {
+                process_values(arguments);
+            }
+            Some(TerminatorInstruction::Return { return_values }) => {
+                process_values(return_values);
+            }
+            _ => {}
+        }
```
Comment (jfecher) [inline crates/noirc_evaluator/src/ssa_refactor/opt/defunctionalize.rs:235]:
```rs
block.unwrap_terminator().for_each_value(process_value)
```

**Review by jfecher — CHANGES_REQUESTED** [review]

**Comment by jfecher** [comment]
Also, can we split this up into smaller PRs next time (ideally one per issue)? This PR solving several issues makes each individual fix more difficult to isolate. It's also easier reviewing several smaller PRs than one larger one, especially if part of the larger PR becomes blocking for the rest of it.

File: crates/noirc_evaluator/src/brillig/brillig_gen/brillig_block.rs (hunk 1 above)
Comment (sirasistant) [reply crates/noirc_evaluator/src/brillig/brillig_gen/brillig_block.rs:723]: Yes, this is related to https://github.com/noir-lang/noir/issues/1977 , where the compiler accepts as a valid type for the range of the loop a field type, so the inherent comparison between the iterator and the range is a comparison of fields. I was told when discussing this with @kevaundray that not allowing field ranges & iterators would be a rather big breaking change, so I think supporting it until fixed upstream with a breaking change could be the best option

File: crates/noirc_evaluator/src/brillig/brillig_gen/brillig_block.rs [hunk 5]
```diff
@@ -845,18 +878,20 @@ pub(crate) fn convert_ssa_binary_op_to_brillig_binary_op(
...
+        match op {
+            BinaryOp::Add => BrilligBinaryOp::Field { op: BinaryFieldOp::Add },
+            BinaryOp::Sub => BrilligBinaryOp::Field { op: BinaryFieldOp::Sub },
+            BinaryOp::Mul => BrilligBinaryOp::Field { op: BinaryFieldOp::Mul },
+            BinaryOp::Div => BrilligBinaryOp::Field { op: BinaryFieldOp::Div },
+            BinaryOp::Eq => BrilligBinaryOp::Field { op: BinaryFieldOp::Equals },
+            BinaryOp::Lt => BrilligBinaryOp::Integer {
+                op: BinaryIntOp::LessThan,
+                bit_size: BRILLIG_INTEGER_ARITHMETIC_BIT_SIZE,
+            },
```
[the remark this answers is not in the document]
Comment (sirasistant) [reply crates/noirc_evaluator/src/brillig/brillig_gen/brillig_block.rs:890]: This is for supporting https://github.com/noir-lang/noir/pull/1973#discussion_r1268542220

File: crates/noirc_evaluator/src/brillig/brillig_gen/brillig_block.rs (hunk 1 above)
Comment (sirasistant) [reply crates/noirc_evaluator/src/brillig/brillig_gen/brillig_block.rs:723]: Opened bug to track https://github.com/noir-lang/noir/issues/1979

File: crates/noirc_evaluator/src/ssa_refactor/opt/defunctionalize.rs (hunk 3 above)
Comment (sirasistant) [reply crates/noirc_evaluator/src/ssa_refactor/opt/defunctionalize.rs]: It was just used in two places and not gaining much, so I just removed it

File: crates/noirc_evaluator/src/brillig/brillig_gen/brillig_block.rs (hunk 1 above)
Comment (jfecher) [reply crates/noirc_evaluator/src/brillig/brillig_gen/brillig_block.rs:723]: Thanks for the issue. Let's come back to it at a different time then.

File: crates/noirc_evaluator/src/ssa_refactor/opt/defunctionalize.rs [hunk 6]
```diff
@@ -173,72 +151,120 @@ impl DefunctionalizationContext {
...
+            match instruction {
+                Instruction::Call { func: target, arguments } => {
+                    if let Value::Param { .. } | Value::Instruction { .. } = &func.dfg[*target] {
+                        dispatches.insert(Signature {
+                            params: vecmap(arguments, |param| func.dfg.type_of_value(*param)),
+                            returns: vecmap(
+                                func.dfg.instruction_results(*instruction_id),
+                                |result| func.dfg.type_of_value(*result),
+                            ),
+                        });
```
Comment (jfecher) [inline crates/noirc_evaluator/src/ssa_refactor/opt/defunctionalize.rs:239]:
```suggestion
                        let results = func.dfg.instruction_results(*instruction_id);
                        dispatches.insert(Signature {
                            params: vecmap(arguments, |param| func.dfg.type_of_value(*param)),
                            returns: vecmap(results, |result| func.dfg.type_of_value(*result)),
                        });
```

**Review by jfecher — APPROVED** [review]
