### PR TITLE
fix(ssa): Handle right shift with constants

### LINKED ISSUE #2250: Panic when using right shift operator
### Aim

There's a regression in the newer versions of the compiler where the following code panics with `Message:  attempt to divide by zero`
```rust
fn main() {
    let a: u1 = 1 >> 1;
    let b: u32 = 1 >> 32;
}
```

### Expected Behavior

The code shouldn't panic and return 0

### Bug

I think what's probably happening is that the bit shift is getting optimized to a division and the divisor is getting truncated to the type of the dividend. So `>> 1` becomes `/ (2^1 as u1)` which is 0 and hence the panic.

### To Reproduce

1. Copy the code above
2. Run `nargo execute main`

### Installation Method

Compiled from source

### Nargo Version

nargo 0.9.0 (git version hash: 90c5d182b578b6d512e4b5dc2c07810e6815f31e, is dirty: false)

### Additional Context

_No response_

### Would you like to submit a PR for this Issue?

Maybe

### Support Needs

_No response_

### PR DESCRIPTION
**Pull request by vezenovm**
# Description

## Problem\*

Resolves #2250 

## Summary\*

The poster of the issue this PR aims to solve was correct in their assessment as to what was causing the panic. We were truncating the divisor into the operand type (which comes from the dividend). This caused the rhs to be `0`. When we have `0` in the divisor we should not simplify and instead leave the computation to runtime so we can handle it correctly. In this case, both bit shifts should result in `0`. This is similar to one of the fixes that had to be done in PR https://github.com/noir-lang/noir/pull/2475

## Documentation

- [ ] This PR requires documentation updates when merged.

  

  - [ ] I will submit a noir-lang/docs PR.

  

  - [ ] I will request for and support Dev Rel's help in documenting this PR.

  
  

## Additional Context

# PR Checklist\*

- [X] I have tested the changes locally.
- [X] I have formatted the changes with [Prettier](https://prettier.io/) and/or `cargo fmt` on default settings.

### CODE REVIEW

File: crates/noirc_evaluator/src/ssa/ir/instruction.rs [hunk 1]
```diff
@@ -756,6 +756,16 @@ impl Binary {
...
                 let rhs = truncate(rhs.try_into_u128()?, *bit_size);
+
+                // The divisor is being truncated into the type of the operand, which can potentially
+                // lead to the rhs being zero.
+                // If the rhs of a division is zero, attempting to evaluate the divison will cause a compiler panic.
+                // Thus, we do not evaluate the division in this method, as we want to avoid triggering a panic,
+                // and the operation should be handled by ACIR generation.
+                if matches!(self.operator, BinaryOp::Div) && rhs == 0 {
+                    return None;
+                }
```
Comment (jfecher) [inline crates/noirc_evaluator/src/ssa/ir/instruction.rs:767]: I don't think this is the right solution to the problem. The problem is that code like `1 >> 8` is getting turned into `1 / (2^8 mod 256)` for u8, and checking for zero here would cause ACIR-gen to fail due to https://github.com/noir-lang/noir/pull/2475, when the correct behavior should be returning zero.

I think the right solution here would be to fix `self.pow` in the ssa gen context to avoid the `mod 256` after the pow.

**Review by jfecher — CHANGES_REQUESTED** [review]

File: crates/noirc_evaluator/src/ssa/ir/instruction.rs (hunk 1 above)
Comment (vezenovm) [reply crates/noirc_evaluator/src/ssa/ir/instruction.rs:767]: It will not fail during ACIR gen as the rhs is in fact `2` not `0` (I added a test under `execution_success/bit_shifts_comptime/src/main.nr` to show that the code still passes). During `eval_constants` we have the constant `2` but it is being truncated to `0` as the operand type is `u1`.

Comment (vezenovm) [reply crates/noirc_evaluator/src/ssa/ir/instruction.rs:767]: I don't see that any truncations on the rhs of the bit shift (https://github.com/noir-lang/noir/blob/b55f3998258e9c82a0312fc138e3c6b5cf1a7c74/crates/noirc_evaluator/src/ssa/ssa_gen/context.rs#L251) unless you are looking somewhere else?

Comment (vezenovm) [reply crates/noirc_evaluator/src/ssa/ir/instruction.rs:767]: For this code:
```
	let b: u8 = 1 >> 8;
	assert(b == 0);
```
you will have this SSA:
```
After Dead Instruction Elimination:
acir fn main f2 {
  b0(v0: u64):
    v8 = div u8 1, Field 2⁸
    constrain v8 == u8 0
    return 
}
```

Comment (jfecher) [reply crates/noirc_evaluator/src/ssa/ir/instruction.rs:767]: Hmm ok. I thought pow may have been inserting them. It seems a bit odd that acir-gen is fine with u8 values being larger than a u8 can hold but it works for our usecase here.

**Review by jfecher — APPROVED** [review]
LGTM

File: crates/noirc_evaluator/src/ssa/ir/instruction.rs (hunk 1 above)
Comment (vezenovm) [reply crates/noirc_evaluator/src/ssa/ir/instruction.rs:767]: Yeah I think it is because the result of `pow` is a field. Perhaps it is worth to explore being a bit more restrictive and inserting a truncate on the result of `pow`.

**Comment by TomAFrench** [comment]
Looks like the regression test added in this PR fails in debug mode.

https://github.com/noir-lang/noir/issues/2745
