### PR TITLE
fix!: unify comptime expression/statement with target type

### LINKED ISSUE #8369: Comptime code ends up with the wrong type?
Consider this code:

```noir
fn main() {
    let x: i32 = comptime {
        let y = -1;
        y
    };
}
```

If we look at the type hints in LSP, we see this:

Image

Note how `y` is `Field`. The reason is that the entire comptime block is elaborated inside a `elaborate_in_comptime_context` call. That call pushes a new function context and then pops it. When popping it, any unbound polymorphic integer type variables are bound to their default type. In this case, that `-1` ends up being a `Field`.

It compiles fine because the comptime value of the comptime block (in this case `Value::Field(1)`) it turned into an expression (a literal "1"), that expression is type-checked and we get a polymorphic integer that works fine in this context.

However, `Field` doesn't unify with `i32` so I don't know if the code above should compile. For example, this code is a bit more explicit:

```noir
fn main() {
    let x: i32 = comptime { a_field() };
}

fn a_field() -> Field {
    0
}
```

That should probably not compile, but it does (this is https://github.com/noir-lang/noir/issues/8340).

This one is stranger but also compiles fine (and we have such a case in our test programs):

```noir
fn main() {
    let x: str<_> = comptime { f"Hello" };
}
```

The reason is that the comptime value for `f"Hello"`, when turned into an expression, ends up being the string literal "Hello", whose type is `str<_>`. But I feel like maybe that format string should be converted to a string type before existing the comptime context.

But, regardless of these types mismatch, I'm not sure it's correct to elaborate the comptime block in a nested function where unbound types end up with a default type. In this code:

```noir
fn main() {
    let x: i32 = comptime {
        let y = -1;
        y
    };
}
```

I feel that `y` should be bound with `x` so it takes the type `i32`.

Alternatively... maybe all of this is fine? That is, it's fine that the types don't match, as long as the value, turned into an expression, and that expression typed, matches the outside type. That would mean that https://github.com/noir-lang/noir/issues/8340 is not a bug, as there's nothing unsafe about it.

### LINKED ISSUE #10624: Fails to bind method call types when in comptime block return value
### Aim

I want to run this code:
```noir
fn main() -> pub [u1; 1] {
    comptime {
        let large_number: Field = 2;
        large_number.to_be_bits()
    }
}
```

### Expected Behavior

I would expect the code to compile (even if it may fail at execution).

### Bug

The code fails with these errors:
```
error: Type annotation needed
   ┌─ src/main.nr:10:9
   │
10 │         large_number.to_be_bits()
   │         ----------------------- Could not determine the value of the generic argument `N` declared on the function `to_be_bits`
   │

error: Object type is unknown in method call
   ┌─ std/field/mod.nr:64:20
   │
64 │         let bits = __to_be_bits(self);
   │                    ------------------ Type must be known by this point to know which method to call
   │
   = Try adding a type annotation for the object type before this method call

Aborting due to 2 previous errors
```

This may be related to https://github.com/noir-lang/noir/issues/8369, however, I felt this case was a bit different as the method signature is known and we should be able to bind the type to the result of the comptime block.

### To Reproduce

1. Run the test above with `nargo compile`

### Workaround

None

### Workaround Description

We can use turbofish:
```noir
fn main() -> pub [u1; 1] {
    comptime {
        let large_number: Field = 2;
        large_number.to_be_bits::<1>()
    }
}
```

### Additional Context

_No response_

### Project Impact

Nice-to-have

### Blocker Context

_No response_

### Nargo Version

nargo version = 1.0.0-beta.15 noirc version = 1.0.0-beta.15+1a930357477fc0c210dc5a8960680282d4cfa24e (git version hash: 1a930357477fc0c210dc5a8960680282d4cfa24e, is dirty: true)

### NoirJS Version

_No response_

### Proving Backend Tooling & Version

_No response_

### Would you like to submit a PR for this Issue?

None

### Support Needs

_No response_

### PR DESCRIPTION
**Pull request by asterite**
# Description

## Problem

Resolves #8369
Resolves #10624

## Summary

This is just an experimental PR but I want to see if existing code breaks.

The idea here is that if a comptime statement or expression is in a position where there's an explicit type (for example a `let` statement with an explicit type, or a return type, or a comptime block given to a function argument) then we unify that comptime statement/expression with that target type.

Before this PR this didn't compile:

```noir
fn main() {
    let x: u8 = comptime { 1 };
}
```

The reason was that "1" was typed as Field because the "u8" information was inaccessible to the block. Now we unify that "1" with "u8" so it ends up being "u8".

This PR is a breaking change because previously this was valid:

```noir
fn main() {
  let _: str<5> = comptime { f"Hello" };
}
```

The reason it worked is that format strings were lowered to string literals. Well, that still happens, but now it fails to compile because a fmtstr doesn't unify with a str. We can fix this in two ways. The first is not using a type annotation, in which case the type will be inferred, and because a fmtstr lowers into a str, it works:

```noir
fn main() {
  let _ = comptime { f"Hello" };
}
```

The second way to fix this is using `as_quoted_str`:

```noir
fn main() {
  let _: str<5> = comptime { f"Hello".as_quoted_str!() };
}
```

The docs for "as_quoted_str" say:

> Returns the format string contents (with the leading and trailing double quotes) as a Quoted string literal (not a format string literal).

So here we are effectively transforming that format string into a string literal, whose type is `str<5>`, and now everything compiles.

Given that inferring types of `let` is more common than explicitly specifying their types, in the vast majority of cases this should work out of the box (external repos checked here all work, so it's likely not common to return format strings from a comptime context).

The only odd thing now is that the comptime block is type-checked in one way or another depending on an explicit type. But maybe that's fine: in the example above, and before this PR, to fix the above we could change "1" to "1_u8" so we have to specify the type somewhere if we want a different type.

## Additional Context

1. This PR uncovered a bug in the `aes128_encrypt` implementation in the comptime interpreter: it was returning a slice, but it should return an array. It worked because lowering a slice to an array seems to work (not sure why the error happened just now and not before, though).
2. If we go with this, we should probably update the [lowering](https://noir-lang.org/docs/noir/concepts/comptime#lowering) docs to explain how comptime blocks are type-checked.
3. I feel https://github.com/noir-lang/noir/issues/6990 is related to this issue/PR (though it's not solved here) as globals are comptime values that are lowered, so the code in #6990 should give an error because the final type of the global is `str`, not `fmtstr` (to fix it one would need to use `as_quoted_str!()`)

## User Documentation

Check one:
- [ ] No user documentation needed.
- [ ] Changes in _docs/_ included in this PR.
- [ ] **[For Experimental Features]** Changes in _docs/_ to be submitted in a separate PR.

# PR Checklist

- [ ] I have tested the changes locally.
- [ ] I have formatted the changes with [Prettier](https://prettier.io/) and/or `cargo fmt` on default settings.

### CODE REVIEW

File: compiler/noirc_frontend/src/elaborator/expressions.rs [hunk 1]
```diff
@@ -1532,8 +1532,22 @@ impl Elaborator<'_> {
...
+            // This for example allows this code to compile: `let x: u8 = comptime { 1 }`.
+            // If we don't do this, "1" will end up with the default integer or field type,
+            // which is Field.
+            if let Some(target_type) = target_type {
+                this.unify(&block_type, target_type, || TypeCheckError::TypeMismatch {
+                    expected_typ: target_type.to_string(),
+                    expr_typ: block_type.to_string(),
+                    expr_location: location,
+                });
+            }
```
Comment (jfecher) [inline compiler/noirc_frontend/src/elaborator/expressions.rs:1553]: Another place for this would be when checking `Statement::Expression`, as most comptime blocks would have to be blocks returning an expression anyway, and that'd potentially allow even more non-comptime code with similar issues to compile.
Then again, since we're not changing FunctionContexts there, maybe it isn't necessary.

File: test_programs/compile_success_empty/comptime_fmt_strings/src/main.nr [hunk 2]
```diff
@@ -1,6 +1,6 @@
 fn main() {
     // format strings are lowered as normal strings
-    let (s1, s2): (str<39>, str<4>) = comptime {
```
Comment (jfecher) [inline test_programs/compile_success_empty/comptime_fmt_strings/src/main.nr:3]: Need to update the comment here too

**Comment by asterite** [comment]
> One thing I am concerned with (preventing me from approving) is lowering format strings into regular strings. If they keep their old format string type but are lowered as a normal string literal, does this mean our runtime can get confused if it later tries to format these strings by looking at their types? They would no longer have an environment to format.

Good point. I wonder if it could still be lowered to a format string... 🤔

Let's say we have this:

```noir
fn main() {
    let f = comptime {
        let x = 1;
        f"x is {x}"
    };
}
```

Right now `f"x is {x}"` is immediately evaluated to "x is 1". But maybe at comptime we could still keep the fragments, except that now fragments are either strings or values, so in this case we'd have `[String("x is "), Value(1)]`. Then when we lower it, in `into_expression`, we create this expression:

```noir
{
  let fragment1: Field = 1;
  f"x is {fragment1}"
}
```

That is, we create a block expression with one temporary value for each Value fragment.

Then, _I think_, all comptime values lower to their type.

You'd have to call `as_quoted_str!()` to get a `str`, but maybe that's fine, or at least less unexpected than the current situation.

**Comment by asterite** [comment]
@jfecher I tried the above in https://github.com/noir-lang/noir/pull/11002

File: compiler/noirc_frontend/src/elaborator/expressions.rs (hunk 1 above)
Comment (asterite) [reply compiler/noirc_frontend/src/elaborator/expressions.rs:1553]: > Another place for this would be when checking Statement::Expression

Where is that?

**Comment by asterite** [comment]
This is ready for review again

**Comment by asterite** [comment]
@jfecher Actually, I noticed one "inconsistency" remains: `CtString` is still lowered to `str`. For example this compiles and works fine:

```noir
use std::append::Append;

fn main() {
    let s: str<_> = comptime {
        let ct_string = CtString::new().append("Hello");
        ct_string
    };
    println(s);
}
```

Should we keep that, or should we lower `CtString` to something of type `CtString` (it's doable). Maybe with `CtString` this is less of an issue because `CtString` only works in comptime, so the type can't escape the comptime block and, for example, you can't use it in a global.
