### PR TITLE
fix(ssa): Validate signed mul overflow

### LINKED ISSUE #8088: Multiplication without `range_check` causes difference between ACIR and Brillig
### Aim

.

### Expected Behavior

Both failed or both succeeded

### Bug

The following SSA fails in ACIR and succeeds in Brillig
```
acir(inline) predicate_pure fn main f0 {
  b0(v0: Field):
    v1 = truncate v0 to 16 bits, max_bit_size: 254
    v2 = cast v1 as i16
    v3 = mul v2, v2
    v4 = div v3, v2
    return v4
}
```
```
brillig(inline) predicate_pure fn main f0 {
  b0(v0: Field):
    v1 = truncate v0 to 16 bits, max_bit_size: 254
    v2 = cast v1 as i16
    v3 = mul v2, v2
    v4 = div v3, v2
    return v4
}
```

With `v0 = 47811`

Brillig returned 0
ACIR: Execution failed: Failed to solve program: 'Cannot satisfy constraint'

### To Reproduce

in `tooling/ssa_fuzzer/lib.rs`
```rs
mod tests {
    .........
    use noirc_evaluator::ssa::ir::types::NumericType;
    use noirc_evaluator::ssa::ir::instruction::BinaryOp;
   
    #[test]
    fn regression_multiplication_without_range_check() {
        let mut acir_builder = FuzzerBuilder::new_acir();
        let mut brillig_builder = FuzzerBuilder::new_brillig();

        let field_acir_var = acir_builder.insert_variable(ValueType::Field.to_ssa_type()).value_id;
        let field_brillig_var =
            brillig_builder.insert_variable(ValueType::Field.to_ssa_type()).value_id;

        let truncated_acir = acir_builder.builder.insert_truncate(field_acir_var, 16, 254);
        let truncated_brillig = brillig_builder.builder.insert_truncate(field_brillig_var, 16, 254);

        let field_casted_i16_acir =
            acir_builder.builder.insert_cast(truncated_acir, NumericType::Signed { bit_size: 16 });
        let field_casted_i16_brillig = brillig_builder
            .builder
            .insert_cast(truncated_brillig, NumericType::Signed { bit_size: 16 });

        let casted_pow_2_acir = acir_builder.builder.insert_binary(
            field_casted_i16_acir,
            BinaryOp::Mul { unchecked: false },
            field_casted_i16_acir,
        );
        let casted_pow_2_brillig = brillig_builder.builder.insert_binary(
            field_casted_i16_brillig,
            BinaryOp::Mul { unchecked: false },
            field_casted_i16_brillig,
        );

        let last_var = acir_builder.builder.insert_binary(
            casted_pow_2_acir,
            BinaryOp::Div,
            field_casted_i16_acir,
        );
        let last_var_brillig = brillig_builder.builder.insert_binary(
            casted_pow_2_brillig,
            BinaryOp::Div,
            field_casted_i16_brillig,
        );

        acir_builder.builder.terminate_with_return(vec![last_var]);
        brillig_builder.builder.terminate_with_return(vec![last_var_brillig]);

        let acir_program = acir_builder.compile().unwrap();
        let brillig_program = brillig_builder.compile().unwrap();

        let mut initial_witness = WitnessMap::new();
        initial_witness.insert(Witness(0), FieldElement::from(47811_u32));

        let result_witness = Witness(1);
        let compare_results = run_and_compare(
            &acir_program.program,
            &brillig_program.program,
            initial_witness,
            result_witness,
            result_witness,
        );
        println!("{:?}", compare_results);
        match compare_results {
            CompareResults::Agree(_result) => {
                return;
            }
            CompareResults::BothFailed(_acir_error, _brillig_error) => {
                return;
            }
            _ => panic!("Should fail or agree in both"),
        }
    }
}
```

### Workaround

None

### Workaround Description

_No response_

### Additional Context

_No response_

### Project Impact

None

### Blocker Context

_No response_

### Nargo Version

_No response_

### NoirJS Version

_No response_

### Proving Backend Tooling & Version

_No response_

### Would you like to submit a PR for this Issue?

None

### Support Needs

_No response_

### PR DESCRIPTION
**Pull request by vezenovm**
# Description

## Problem\*

Resolves #8088 

Builds upon https://github.com/noir-lang/noir/pull/8765.

## Summary\*

This adds validation similar to https://github.com/noir-lang/noir/pull/8706, except for signed multiplication. The semantics for which are seen here. We could be more strict with these checks by checking this code gen as well:
```rust
self.check_signed_overflow(result, lhs, rhs, operator, bit_size, location);
self.insert_safe_cast(result, result_type, location)
```
However, for now I have chosen to simply check up to the truncate point to simplify our "state machine". We also mainly want to guarantee that we have truncated the result of an operation appropriately so that someone cannot code gen an overflow.

## Documentation\*

Check one:
- [ ] No documentation needed.
- [X] Documentation included in this PR.
- [ ] **[For Experimental Features]** Documentation to be submitted in a separate PR.

# PR Checklist\*

- [X] I have tested the changes locally.
- [X] I have formatted the changes with [Prettier](https://prettier.io/) and/or `cargo fmt` on default settings.

### CODE REVIEW

File: compiler/noirc_evaluator/src/ssa/validation/mod.rs [hunk 1]
```diff
@@ -172,6 +228,7 @@ impl<'f> Validator<'f> {
 ///
 /// Panics on malformed functions.
 pub(crate) fn validate_function(function: &Function) {
+    dbg!(function.id());
```
Comment (vezenovm) [inline compiler/noirc_evaluator/src/ssa/validation/mod.rs]:
```suggestion
```

File: compiler/noirc_evaluator/src/ssa/parser/into_ssa.rs [hunk 2]
```diff
@@ -558,10 +557,6 @@ impl Translator {
         // before each print.
         ssa.normalize_ids();
 
-        for function in ssa.functions.values() {
-            validate_function(function);
-        }
```
Comment (asterite) [inline compiler/noirc_evaluator/src/ssa/parser/into_ssa.rs:563]: Why is this gone? (maybe it's already done somewhere else and this was redundant?)

**Review by asterite — APPROVED** [review]
Looks good? Would a test for `mul` followed by `truncate` but not by any cast be worth having?

**Comment by asterite** [comment]
> Looks good?

Argh, I meant to type "!" instead of "?" 😅

File: compiler/noirc_evaluator/src/ssa/parser/into_ssa.rs (hunk 2 above)
Comment (vezenovm) [reply compiler/noirc_evaluator/src/ssa/parser/into_ssa.rs:563]: It was redundant. It was being done in `FunctionBuilder::finish`

**Comment by vezenovm** [comment]
> Would a test for `mul` followed by `truncate` but not by any cast be worth having?

Yes, I will add one.

**Comment by vezenovm** [comment]
Added a test for a mul followed by a truncate with no cast. I also added a test that a lone truncate compiles:
```
        acir(inline) pure fn main f0 {
          b0(v0: i16):
            v1 = truncate v0 to 8 bits, max_bit_size: 8
            return v1
        }
```
