### PR TITLE
fix(ssa): Avoid going through `i128` when casting signed to `u128`

### LINKED ISSUE #9926: SSA interpreter fails on test: `cast_to_u128`
### Aim

Blocks https://github.com/noir-lang/noir/pull/9912

The SSA interpreter fails on `execution_success/cast_to_u128 `

### Expected Behavior

All passes should succeed. 

### Bug

```
❯ cargo run -q -p nargo_cli -- interpret --silence-warnings --force
--- Interpreter result after Initial SSA:
Err(Unsupported numeric type `i128`)
...
```

### To Reproduce

1.
2.
3.
4.

### Workaround

None

### Workaround Description

_No response_

### Additional Context

_No response_

### Project Impact

None

### Blocker Context

_No response_

### Nargo Version

nargo version = 1.0.0-beta.12 noirc version = 1.0.0-beta.12+c63b10c83263f3cf1ea2368b011fae2625be8ea3 (git version hash: b361eb6ad9fb4101d4a1d0874cdfd40a001c55b1, is dirty: true)

### NoirJS Version

_No response_

### Proving Backend Tooling & Version

_No response_

### Would you like to submit a PR for this Issue?

None

### Support Needs

_No response_

### PR DESCRIPTION
**Pull request by aakoshh**
# Description

## Problem\*

Resolves #9926 

## Summary\*

Changes the codegen for casting signed numeric types to unsigned to avoid going through the sign extended signed type, and rather go directly to the unsigned type after sign extension. 

Changes `simplify_cast` to recognise when we are casting back and forth and just use the value as-is. 

Disallows `i128` in SSA

## Additional Context

Casting from e.g. `i8` to `u128` worked like this:
1. sign extend `i8` to `i128`
2. cast from `i128` to `u128`. 

This isn't wrong, but the front end doesn't allow `i128`, and while `FunctionBuilder::insert_cast` calls `validate_numeric_type` which did allow it, the SSA interpreter didn't expect this type and returned an error.

Sign extension itself works by casting to unsigned and adding the offsets necessary to transform the value to the correct two complement based on the target bit size. In itself the sign-extended value is already unsigned, so what was really going on is 
1. cast from `i8` to `u8`
2. cast from `u8` to `u128`
3. cast from `u128` to `i128`
4. cast from `i128` to `u128`

In this form it is clear that all we need to do to avoid `i128` appearing in the SSA is to leave out the last 2 steps. 

## Documentation\*

Check one:
- [x] No documentation needed.
- [ ] Documentation included in this PR.
- [ ] **[For Experimental Features]** Documentation to be submitted in a separate PR.

# PR Checklist\*

- [x] I have tested the changes locally.
- [ ] I have formatted the changes with [Prettier](https://prettier.io/) and/or `cargo fmt` on default settings.

### CODE REVIEW

**Comment by vezenovm** [comment]
Looks like we could use a snap update and a master merge.

**Comment by aakoshh** [comment]
@vezenovm thanks, it's updated now.

File: compiler/noirc_evaluator/src/ssa/opt/expand_signed_math.rs [hunk 1]
```diff
@@ -519,17 +519,16 @@ mod tests {
...
-            v26 = unchecked_mul v25, u8 2
-            v27 = unchecked_add v21, v26
-            v29 = eq v21, u8 0
-            v30 = not v29
-            v31 = cast v30 as u8
-            v32 = unchecked_mul v27, v31
-            v33 = cast v32 as i8
-            return v33
+            v23 = unchecked_sub u8 128, v21
+            v24 = unchecked_mul v23, v10
```
Comment (vezenovm) [inline compiler/noirc_evaluator/src/ssa/opt/expand_signed_math.rs:523]: This looks safe as we are assuming we have appropriately laid down other instructions. Doing `v22 = cast v10 as u1` would truncate our `v10` but `v10` already comes from a division against `u8 128`. If we were make a reduced test with a different divisor (like u8 1) could we get `v24` to return a different result before and after simplifying the casts?

Comment (aakoshh) [reply compiler/noirc_evaluator/src/ssa/opt/expand_signed_math.rs:523]: I thought `cast` doesn't truncate anything, just changes the type, and if we want to get rid of bits we have to use `truncate` 🤔 

`v22` is also unused as far as I can see. All we really removed was the `v23 = cast v10 as u8`, because `v10` is already a `u8`, so instead we use it directly in `v24 = unchecked_mul v23, v10`.

> If we were make a reduced test with a different divisor (like u8 1) could we get v24 to return a different result before and after simplifying the casts?

I thought not.
```
v2 = cast v0 as u8
v10 = div v2, u8 128
v23 = cast v10 as u8
```
I thought v23 is definitely the same as `v10`.

Comment (vezenovm) [reply compiler/noirc_evaluator/src/ssa/opt/expand_signed_math.rs:523]: > `v22` is also unused as far as I can see. All we really removed was the `v23 = cast v10 as u8`

Apologies I misread the test and thought we removed the cast to u1 🤦
