### PR TITLE
fix: increment ref count when hoisting instructions returning array

### LINKED ISSUE #10988: LICM does not emits an inc_rc for a Call returning an array
## Finding Description

Similar to the `MakeArray` if the `Call` instruction can be hoisted but returns an array, we need to return `WithRefCount`.

## Proof of Concept

```rust
#[test]
fn call_func_make_arr_inc_rc() {
    for expr in &[
        "make_array [u8 0, u8 1, u8 2, u8 3] : [u8; 4]",
        "call f1() -> [u8; 4]"
    ] {
        let src = format!(r#"
        brillig(inline) impure fn main f0 {{
          b0():
            v2 = make_array [u8 0, u8 0, u8 0, u8 0] : [u8; 4]
            v3 = allocate -> &mut [u8; 4]
            store v2 at v3
            jmp b1(u32 0)
          b1(v0: u32):
            v6 = lt v0, u32 10
            jmpif v6 then: b2, else: b3
          b2():
            v11 = {expr}
            store v11 at v3
            v13 = unchecked_add v0, u32 1
            jmp b1(v13)
          b3():
            v7 = load v3 -> [u8; 4]
            v9 = call black_box(v7) -> [u8; 4]
            return
        }}
        brillig(inline) predicate_pure fn ret_arr f1 {{
          b0():
            v4 = make_array [u8 0, u8 1, u8 2, u8 3] : [u8; 4]
            return v4
        }}
        "#);
        let ssa = Ssa::from_str(&src).unwrap();
        let ssa = ssa.loop_invariant_code_motion();
        let ssa_string = ssa.to_string();
        assert!(ssa_string.contains("inc_rc"), "failed on {}", expr);
    }
}
```

## Recommendation

Make sure that if the call returns an array, an `inc_rs` instruction is emitted.

### PR DESCRIPTION
**Pull request by guipublic**
# Description

## Problem

Resolves #10988

## Summary
Generalise ref count increase when hoisting MakeArray instructions to all instructions returning array.

## User Documentation

Check one:
- [X] No user documentation needed.
- [ ] Changes in _docs/_ included in this PR.
- [ ] **[For Experimental Features]** Changes in _docs/_ to be submitted in a separate PR.

# PR Checklist

- [X] I have tested the changes locally.
- [X] I have formatted the changes with [Prettier](https://prettier.io/) and/or `cargo fmt` on default settings.

### CODE REVIEW

File: compiler/noirc_evaluator/src/ssa/opt/loop_invariant.rs [hunk 1]
```diff
@@ -691,11 +694,23 @@ impl<'f> LoopInvariantContext<'f> {
             return (true, false);
         }
 
-        match can_be_hoisted(&instruction, &self.inserter.function.dfg) {
-            Yes => (true, false),
+        // In Brillig, if the instruction returns an array, we need to insert an inc_rc
+        // to handle potential mutations.
+        let dfg = &self.inserter.function.dfg;
+        let returns_array = if dfg.runtime().is_brillig() {
```
Comment (vezenovm) [inline compiler/noirc_evaluator/src/ssa/opt/loop_invariant.rs:694]: To be defensive maybe we can perform this before the early return from `self.can_be_hoisted_from_loop_bounds(loop_context, &instruction)` and assert that `returns_array` is false. Or just return `returns_array` instead of `false` (although it should always be `false` so I prefer an assertion on this invariant).

File: compiler/noirc_evaluator/src/ssa/opt/loop_invariant.rs [hunk 2]
```diff
@@ -3612,4 +3627,42 @@ mod control_dependence {
         );
         assert_ssa_does_not_change(&src, Ssa::loop_invariant_code_motion);
     }
+
+    #[test]
+    fn call_func_make_arr_inc_rc() {
+        for expr in &["make_array [u8 0, u8 1, u8 2, u8 3] : [u8; 4]", "call f1() -> [u8; 4]"] {
```
Comment (vezenovm) [inline compiler/noirc_evaluator/src/ssa/opt/loop_invariant.rs]: We already have a `insert_inc_rc_when_moving_make_array` test so inserting `make_array [u8 0, u8 1, u8 2, u8 3] : [u8; 4]` here feels redundant. 

I think this test would be better if `call f1() -> [u8; 4]` returned two arguments with `[u8; 4]` being the second as the previous `if insert_rc` check would only have inserting an inc_rc for the first result.

**Review by vezenovm — COMMENTED** [review]
Looks good, just a couple nits regarding the tests and asserting invariants

File: compiler/noirc_evaluator/src/ssa/opt/loop_invariant.rs (hunk 1 above)
Comment (guipublic) [reply compiler/noirc_evaluator/src/ssa/opt/loop_invariant.rs:694]: Done

File: compiler/noirc_evaluator/src/ssa/opt/loop_invariant.rs (hunk 2 above)
Comment (guipublic) [reply compiler/noirc_evaluator/src/ssa/opt/loop_invariant.rs]: Done.
The test was the one from the issue.

File: compiler/noirc_evaluator/src/ssa/opt/loop_invariant.rs [hunk 3]
```diff
@@ -428,21 +428,24 @@ impl<'f> LoopInvariantContext<'f> {
...
-                            .get_instruction_call_stack_id(instruction_id);
-                        self.inserter
-                            .function
-                            .dfg
-                            .insert_instruction_and_results(inc_rc, *block, None, call_stack);
+                        let dfg = &self.inserter.function.dfg;
+                        let results: Vec<_> = dfg
+                            .instruction_results(instruction_id)
+                            .iter()
+                            .filter(|result| dfg.type_of_value(**result).contains_an_array())
```
Comment (aakoshh) [inline compiler/noirc_evaluator/src/ssa/opt/loop_invariant.rs]: This will return `true` for a function returning a reference to an array. Is that a valid input for `inc_rc`?

File: compiler/noirc_evaluator/src/ssa/opt/loop_invariant.rs [hunk 4]
```diff
@@ -685,17 +688,30 @@ impl<'f> LoopInvariantContext<'f> {
...
         // into the pre-header of a nested loop even if the nested loop does not execute.
         if self.can_be_hoisted_from_loop_bounds(loop_context, &instruction) {
+            assert!(!returns_array);
             return (true, false);
         }
 
-        match can_be_hoisted(&instruction, &self.inserter.function.dfg) {
-            Yes => (true, false),
+        match can_be_hoisted(&instruction, dfg) {
+            Yes => (true, returns_array),
```
Comment (aakoshh) [inline compiler/noirc_evaluator/src/ssa/opt/loop_invariant.rs:716]: Just curious: why did you decide to make this decision here, instead of returning `WithRefCount` from `can_be_hoisted` for a `Call` that returns an array? It looks like `can_be_hoisted` now returns a misleading answer: it has `WithRefCount`, but it doesn't cover all cases where a ref-count is needed.

Comment (aakoshh) [reply compiler/noirc_evaluator/src/ssa/opt/loop_invariant.rs:716]: I'd perhaps consider changing `CanBeHoistedResult` be `Yes(bool) | WithPredicate(bool) | No`, if the ref-count applies to `ArraySet`, `Call` and `MakeArray`, or whatever else that returns an array.

File: compiler/noirc_evaluator/src/ssa/opt/loop_invariant.rs (hunk 3 above)
Comment (aakoshh) [reply compiler/noirc_evaluator/src/ssa/opt/loop_invariant.rs]: NB `Context::increase_rc` in `constant_folding` has a similar filtering and uses `dfg.type_of_value(...).is_array()` as criteria.

File: compiler/noirc_evaluator/src/ssa/opt/loop_invariant.rs (hunk 4 above)
Comment (guipublic) [reply compiler/noirc_evaluator/src/ssa/opt/loop_invariant.rs:716]: It was simpler to do add this logic outside `can_be_hoisted`, and in fact the ref-count needs also to be managed before.
But yes I agree that it can be confusing so I suggest remove entirely ref-count from `can_be_hoisted`.

Comment (aakoshh) [reply compiler/noirc_evaluator/src/ssa/opt/loop_invariant.rs:716]: What should it return for `MakeArray` after?

Comment (aakoshh) [reply compiler/noirc_evaluator/src/ssa/opt/loop_invariant.rs:716]: I suppose it would be just `Yes` and let the caller attach the `return_array` decision.

File: compiler/noirc_evaluator/src/ssa/opt/loop_invariant.rs (hunk 3 above)
Comment (guipublic) [reply compiler/noirc_evaluator/src/ssa/opt/loop_invariant.rs]: Good point, I don't think issuing an inc_rc for a reference to an array is useful because it will be for the pointer to the array, not the array itself. I changed to `is_array()`

File: compiler/noirc_evaluator/src/ssa/opt/loop_invariant.rs (hunk 4 above)
Comment (guipublic) [reply compiler/noirc_evaluator/src/ssa/opt/loop_invariant.rs:716]: Yes, it's updated now.

File: compiler/noirc_evaluator/src/ssa/opt/loop_invariant.rs (hunk 3 above)
Comment (aakoshh) [inline compiler/noirc_evaluator/src/ssa/opt/loop_invariant.rs]: Did you say this was going to be `is_array`?

Comment (aakoshh) [reply compiler/noirc_evaluator/src/ssa/opt/loop_invariant.rs]: Ah, it was updated further down when the `returns_array` decision is made, but then it's applied on array-references as well as arrays.

**Comment by aakoshh** [comment]
Have you looked at the increase in circuit size for `global_var_regression_entry_points` and `global_var_regression_simple`?

I had a quick look at `global_var_regression_entry_points`. It looks like the extra `inc_rc` instructions prevented the loop in `check_acc_entry_point` from being unrolled, which resulted in that block staying in place. Seems like bad luck. 

The hoisting itself is the `array_get` from a global array, so perhaps it shouldn't happen, as we know global arrays are read-only, and while an `inc_rc` seems defensive, I think there already are other mechanisms to protect them. For example if we pass them to a function, they get cloned, or if we read a sub-array into a variable, it gets cloned, but in this case we just have `EXPONENTIATE[i][j]` in the loop and hoisted `EXPONENTIATE[i]` into the other loop, leaving an `inc_rc` on the sub-array in the loop. If we did this: `let sub = EXPONENTIATE[i]; sub[j]` then we would get a clone already, so I'm just thinking that maybe not everything that can be hoisted needs this new `inc_rc` being inserted?

**Comment by aakoshh** [comment]
To illustrate my point about the cloning already done by ownership, consider this code:
```noir
unconstrained fn main(i: u32, j: u32, k: u32) {
    let mut a = [[[1], [2]], [[3], [4]]];
    let _a_i = a[i];
    let _a_ij = a[i][j];
    let _a_ijk = a[i][j][k];
    a[i][j][k] = 5;
}
```
With `--show-monomorphized` we can see that there are `.clone()`s inserted:
* in RHS for the final sub-array that gets referred to by a new variable
* in the LHS for assignment
```noir
unconstrained fn main$f0(i$l0: u32, j$l1: u32, k$l2: u32) -> () {
    let mut a$l3 = [[[1], [2]], [[3], [4]]];
    let _a_i$l4 = a$l3[i$l0].clone();
    let _a_ij$l5 = a$l3[i$l0][j$l1].clone();
    let _a_ijk$l6 = a$l3[i$l0][j$l1][k$l2];
    a$l3[i$l0].clone()[j$l1].clone()[k$l2] = 5
}
```
This PR would insert further clones for the interim sub-arrays as well, which the ownership tried to avoid.

File: compiler/noirc_evaluator/src/ssa/opt/loop_invariant.rs (hunk 3 above)
Comment (guipublic) [reply compiler/noirc_evaluator/src/ssa/opt/loop_invariant.rs]: Yes we must use the same filter here.
Done.

**Comment by guipublic** [comment]
> Have you looked at the increase in circuit size for `global_var_regression_entry_points` and `global_var_regression_simple`?

I have investigated this and indeed it is due to the inc_rc for ArrayGet, as you said. In fact an ArrayGet that returns an array is returning a nested array from a parent array, and in that case the reference count is already taken care by the parent.
So I have taken a more conservative approach. The idea is to add the inc_rc only for new arrays, and this should only happen with Call, MakeArray and ArraySet.

File: compiler/noirc_evaluator/src/ssa/opt/loop_invariant.rs [hunk 5]
```diff
@@ -428,21 +428,24 @@ impl<'f> LoopInvariantContext<'f> {
                 if hoist_invariant {
                     self.inserter.push_instruction(instruction_id, pre_header, false);
 
-                    // If we are hoisting a MakeArray instruction,
-                    // we need to issue an extra inc_rc in case they are mutated afterward.
+                    // If we are hoisting an instruction which returns an array,
```
Comment (aakoshh) [inline compiler/noirc_evaluator/src/ssa/opt/loop_invariant.rs]:
```suggestion
                    // If we are hoisting an instruction which returns a new array,
```

File: compiler/noirc_evaluator/src/ssa/opt/loop_invariant.rs [hunk 6]
```diff
@@ -685,17 +688,37 @@ impl<'f> LoopInvariantContext<'f> {
...
+        let returns_array = if dfg.runtime().is_brillig() {
+            // Add inc_rc for instructions that create new arrays
+            match &instruction {
+                Instruction::MakeArray { .. } | Instruction::ArraySet { .. } => true,
+                Instruction::Call { .. } => {
+                    let results = dfg.instruction_results(instruction_id);
+                    results.iter().any(|r| dfg.type_of_value(*r).is_array())
+                }
+                // ArrayGet can return an array but it does not create it
+                // In that case, the refcount is managed by the parent array.
```
Comment (aakoshh) [inline compiler/noirc_evaluator/src/ssa/opt/loop_invariant.rs]:
```suggestion
                // In that case, the refcount is managed by the ownership analysis.
```
I wanted to ask last week what you meant when you said "managed by the parent array". 

If we have a nested array, and the RC of the parent array is increased, the inner sub-arrays don't get their RC increased at the same time. There was a PR which did that, but it was abandoned in favour of the ownership making decisions and inserting clones when the sub-array is accessed. So, in what way is the parent responsible for the inner in your comment?

File: compiler/noirc_evaluator/src/ssa/opt/loop_invariant.rs [hunk 7]
```diff
@@ -3612,4 +3628,75 @@ mod control_dependence {
         );
         assert_ssa_does_not_change(&src, Ssa::loop_invariant_code_motion);
     }
+
+    #[test]
+    fn call_func_make_arr_inc_rc() {
```
Comment (aakoshh) [inline compiler/noirc_evaluator/src/ssa/opt/loop_invariant.rs]: Is function named like this because it is supposed to test both `call` and `make_array`? It only tests `call`, right? IIRC there was an earlier variant which did both.

**Review by aakoshh — APPROVED** [review]
LGTM, apart from clarifying some comments. 

Last week I was trying to come up with an example to convince myself that `ArraySet` needs `inc_rc`. I think it went something like this:

```noir
let mut a = [[1, 2], [3, 4]];
for i in 0..2 {
  for j in 0..2 {
    a[i] = [5, 6];
    a[i][j] = 7; 
    println(a);
  }
}
```
My thinking was that LICM would hoist `a[i]` out of the inner loop, thus it would only be set once, and then the inner loop would modify the `[5, 6]` array, overwriting one item and then the other, with the previous iteration's changes visible, and the prints eventually becoming all 7s. By leaving an `inc_rc` we make sure that the assignment to `a[i][j]` acts on a fresh copy of `a[i]` every time.

But this is not a good example, as any wrongdoing is currently prevented by the ownership analysis monomorphizing to this:
```
a$l0[i$l1].clone()[j$l2] = 7;
```

File: compiler/noirc_evaluator/src/ssa/opt/loop_invariant.rs (hunk 6 above)
Comment (guipublic) [reply compiler/noirc_evaluator/src/ssa/opt/loop_invariant.rs]: I thought it was the case, but in fact whatever mechanism is in place, it is fine. So the comment could have been: " the refcount is managed **with** the parent array."

File: compiler/noirc_evaluator/src/ssa/opt/loop_invariant.rs (hunk 7 above)
Comment (guipublic) [reply compiler/noirc_evaluator/src/ssa/opt/loop_invariant.rs]: Yes I updated the test per a review comment, but now the name is not correct. Thank you.

**Comment by guipublic** [comment]
I could not either get a failure with ArraySet. As you say, it is managed by the ownership analysis pass, so I have excluded it.
