### PR TITLE
fix(frontend): Resolve object types from method calls a single time

### LINKED ISSUE #4732: Chained constructors give Expression type is ambiguous
### Aim

Code like this used to compile:
```rust
use dep::aztec::{prelude::{NoteViewerOptions, PrivateSet}};
use dep::value_note::value_note::ValueNote;

fn main() -> pub Field {
    let set: PrivateSet<ValueNote> = PrivateSet::new(dep::std::unsafe::zeroed(), 0);
    let options = NoteViewerOptions::new().set_limit(1); // chained construction happening here
    let notes = set.view_notes(options);
    notes[0].unwrap_unchecked().value
}
```
With this in dependencies:
```toml

[dependencies]
aztec = { git = "https://github.com/AztecProtocol/aztec-packages", tag = "master", directory = "noir-projects/aztec-nr/aztec" }
value_note = { git = "https://github.com/AztecProtocol/aztec-packages", tag = "master", directory = "noir-projects/aztec-nr/value-note" }

```

Here is the code for NoteViewerOptions and private set:
https://github.com/AztecProtocol/aztec-packages/blob/master/noir-projects/aztec-nr/aztec/src/note/note_viewer_options.nr
https://github.com/AztecProtocol/aztec-packages/blob/master/noir-projects/aztec-nr/aztec/src/state_vars/private_set.nr

### Expected Behavior

I think it should compile, since the generic of NoteViewerOptions should be resolved to the generic of set that is ValueNote

### Bug

Instead it errors with `Expression type is ambiguous`

### To Reproduce

1.
2.
3.
4.

### Project Impact

Nice-to-have

### Impact Context

_No response_

### Workaround

Some

### Workaround Description

Splitting it in two lines works:
```rust
use dep::aztec::{prelude::{NoteViewerOptions, PrivateSet}};
use dep::value_note::value_note::ValueNote;

fn main() -> pub Field {
    let set: PrivateSet<ValueNote> = PrivateSet::new(dep::std::unsafe::zeroed(), 0);
    let mut options = NoteViewerOptions::new();
    options = options.set_limit(1);
    let notes = set.view_notes(options);
    notes[0].unwrap_unchecked().value
}
```

### Additional Context

_No response_

### Installation Method

None

### Nargo Version

_No response_

### NoirJS Version

_No response_

### Would you like to submit a PR for this Issue?

None

### Support Needs

_No response_

### LINKED ISSUE #5065: Type inference fails without intermediate variable
### Aim

I want to rely on type inference, but in some cases it only works if I have unnecessary intermediate variables.

### Bug

In the following program, `concise_but_does_not_compile` errors out with `Expression type is ambiguous`. This is fixed in `verbose_but_compiles`, which introduces an intermediate variable `a`. I'm providing zero new type information, so this looks like a bug.

```rust
struct Wrapper<T> {
    _value: T,
}

impl<T> Wrapper<T> {
    fn new(value: T) -> Self {
        Self { _value: value }
    }

    fn unwrap(self) -> T {
        self._value
    }
}

trait MyTrait {
    fn new() -> Self;
}

struct MyType {

}

impl MyTrait for MyType {
    fn new() -> Self {
        MyType {}
    }
}

fn foo<T>() -> T where T: MyTrait {
    MyTrait::new()
}

fn verbose_but_compiles() -> MyType {
    let a = Wrapper::new(foo());
    a.unwrap()
}

fn concise_but_does_not_compile() -> MyType {
    Wrapper::new(foo()).unwrap()
}

fn main() {
    let _ = verbose_but_compiles();
    let _ = concise_but_does_not_compile();
}
```

### PR DESCRIPTION
**Pull request by vezenovm**
# Description

## Problem\*

Resolves #5065 

Probably resolves #4732 but need to test it or have aztec team test it.

## Summary\*

When working with a program like such where `MyType` implements `MyTrait`:
```rust
fn foo<T>() -> T where T: MyTrait {
    MyTrait::new()
}
fn concise_regression() -> MyType {
    Wrapper::new(foo()).unwrap()
}
```
We should be able to infer the return type of `foo`. We currently always push trait constraints onto a a `Vec<(TraitConstraint, ExprId)>`. We need to do this as we can have multiple trait constraints that need to be handled during monomorphization due to generics. However, when working with a method call this can cause us to store an old trait constraint that does not necessarily apply to the expression. 

The nested function call in `concise_regression` initially adds a trait constraint simply for `foo` due to the call to `Wrapper::new(foo())` and then another constraint for `Wrapper::new(foo()).unwrap()`. The call to `Wrapper::new(foo())` cannot be bound to anything unless we introduce an intermediate variable. This felt like it would be overly complex and we just need to follow the accurate trait constraint for a function call expression. 

Taking the test in the issue and this PR we have the following trait constraints on master for the `foo` expression:
```
TraitConstraint {
        typ: '23646 -> '23647,
        trait_id: TraitId(
            ModuleId {
                krate: Root(
                    1,
                ),
                local_id: LocalModuleId(
                    Index(
                        1,
                    ),
                ),
            },
        ),
        trait_generics: [],
    },
    TraitConstraint {
        typ: '23648 -> '23649 -> '23650 -> MyType,
        trait_id: TraitId(
            ModuleId {
                krate: Root(
                    1,
                ),
                local_id: LocalModuleId(
                    Index(
                        1,
                    ),
                ),
            },
        ),
        trait_generics: [],
    }
```
This is occurring due to an unnecessary type check on a method call's object type. This is cause a repeated trait constraint where one has incorrect type variables that cannot be resolved. 

I have altered how MethodCall's and Call's are resolved as to avoid repeated type checks on the object type.

## Documentation\*

Check one:
- [X] No documentation needed.
- [ ] Documentation included in this PR.
- [ ] **[For Experimental Features]** Documentation to be submitted in a separate PR.

# PR Checklist\*

- [X] I have tested the changes locally.
- [X] I have formatted the changes with [Prettier](https://prettier.io/) and/or `cargo fmt` on default settings.

### CODE REVIEW

File: compiler/noirc_frontend/src/hir/type_check/mod.rs [hunk 1]
```diff
@@ -36,7 +37,10 @@ pub struct TypeChecker<'interner> {
     /// verified at the end of a function. This is because constraints arise
     /// on each variable, but it is only until function calls when the types
     /// needed for the trait constraint may become known.
-    trait_constraints: Vec<(TraitConstraint, ExprId)>,
+    // trait_constraints: Vec<(TraitConstraint, ExprId)>,
+    // TODO, change this to a hashmap
+    // trait_constraints: HashMap<(TraitId, ExprId), TraitConstraint>,
+    trait_constraints: HashMap<ExprId, Vec<TraitConstraint>>,
```
Comment (vezenovm) [inline compiler/noirc_frontend/src/hir/type_check/mod.rs:43]: I also switched from a vec of all trait constraints to a hash map of ExprId -> Vec. I felt this was a clearer association between expressions and trait constraints, however, I can switch it back as I realized it is not necessary.

File: compiler/noirc_frontend/src/hir/type_check/mod.rs [hunk 2]
```diff
@@ -36,7 +37,7 @@ pub struct TypeChecker<'interner> {
     /// verified at the end of a function. This is because constraints arise
     /// on each variable, but it is only until function calls when the types
     /// needed for the trait constraint may become known.
-    trait_constraints: Vec<(TraitConstraint, ExprId)>,
+    trait_constraints: HashMap<ExprId, Vec<TraitConstraint>>,
```
Comment (vezenovm) [inline compiler/noirc_frontend/src/hir/type_check/mod.rs:40]: I also switched from a vec of all trait constraints to a hash map of ExprId -> Vec. I originally did it as I thought it may be necessary but I realized it was not. I felt this was a clearer association between expressions and trait constraints so I kept it. However, I can switch it back if we want as the vec is simpler

**Review by jfecher — CHANGES_REQUESTED** [review]
I think this approach misses the real bug. Looking at this again (and testing the example without the same `new` name used for both the impl and trait methods) I think this bug is actually caused by how we handle method calls currently.

To type check method calls we currently change the method call `foo.bar(args..)` into a function call `bar(foo, args..)` and then type check that. Perhaps it is related - e.g. a wrong ID is used there or we type check twice pushing a repeat trait constraint with a bad id. Notably, testing the example with `.unwrap()` replaced with `MyType::unwrap(...)` also fixes the issue.

**Comment by vezenovm** [comment]
> Notably, testing the example with `.unwrap()` replaced with `MyType::unwrap(...)` also fixes the issue.

Thanks that is helpful info, I had not noticed that.

**Comment by vezenovm** [comment]
> I think this bug is actually caused by how we handle method calls currently.

Good catch, this does look to be the case. Calling `check_expression` on the method_call.object a second time causes a second " error to occur. Updating this PR with a new fix.

**Comment by jfecher** [comment]
Interestingly, the elaborator already works a bit differently here since I took the liberty of merging a few methods and changing control flow a bit there. As a result it doesn't have this error either.

**Comment by vezenovm** [comment]
> Interestingly, the elaborator already works a bit differently here since I took the liberty of merging a few methods so that we don't resolve a method/function twice in this case. As a result it doesn't have this error either.

I was able to get all tests passing with logic similar to the evaluator. We now avoid checking a call expression's arguments a second time.

File: compiler/noirc_frontend/src/hir/type_check/expr.rs [hunk 3]
```diff
@@ -164,6 +165,7 @@ impl<'interner> TypeChecker<'interner> {
                                 trait_generics: Vec::new(),
                             };
                             self.trait_constraints.push((constraint, *expr_id));
+
```
Comment (jfecher) [inline compiler/noirc_frontend/src/hir/type_check/expr.rs:168]:
```suggestion
```

**Review by jfecher — APPROVED** [review]
LGTM
