### PR TITLE
fix: Implement auto-dereferencing when calling methods

### LINKED ISSUE #2560: `error: Expected type Vec<_>, found type &mut Vec<Field>` when calling `Vec::len` on a `&mut Vec`
### Aim

Calling `vec.len()` when `vec: &mut Vec<Field>`

### Expected Behavior

The length to be returned

### Bug

The compiler error in the title appears. It seems the Vec isn't being automatically dereferenced in this case.

### To Reproduce

1.
2.
3.
4.

### Installation Method

None

### Nargo Version

_No response_

### Additional Context

_No response_

### Would you like to submit a PR for this Issue?

No

### Support Needs

_No response_

### PR DESCRIPTION
**Pull request by jfecher**
# Description

## Problem\*

Resolves #2560 

## Summary\*

We had auto-dereferencing before for field access `a.b`, but since method calls `a.b()` are a different form, these were missed. I've added support for these and a small test for them.

## Documentation

- [ ] This PR requires documentation updates when merged.

  

  - [ ] I will submit a noir-lang/docs PR.

  

  - [ ] I will request for and support Dev Rel's help in documenting this PR.

  
  

## Additional Context

# PR Checklist\*

- [x] I have tested the changes locally.
- [x] I have formatted the changes with [Prettier](https://prettier.io/) and/or `cargo fmt` on default settings.

### CODE REVIEW

File: crates/noirc_frontend/src/hir/type_check/expr.rs [hunk 1]
```diff
@@ -350,10 +350,38 @@ impl<'interner> TypeChecker<'interner> {
...
+            let location = self.interner.id_location(object);
+
+            let object = self.interner.push_expr(HirExpression::Prefix(HirPrefixExpression {
+                operator: UnaryOp::Dereference { implicitly_added: true },
+                rhs: object,
+            }));
+            self.interner.push_expr_type(&object, element.as_ref().clone());
+            self.interner.push_expr_location(object, location.span, location.file);
+
+            // Recursively derference to allow for converting &mut &mut T to T
```
Comment (TomAFrench) [inline crates/noirc_frontend/src/hir/type_check/expr.rs:378]:
```suggestion
            // Recursively dereference to allow for converting &mut &mut T to T
```

File: crates/noirc_frontend/src/hir/type_check/expr.rs [hunk 2]
```diff
@@ -350,10 +350,38 @@ impl<'interner> TypeChecker<'interner> {
...
+                argument_types[0].0 = new_type;
             }
         }
     }
 
+    /// Insert as many dereference operations as necessary to automatically dereference a method
+    /// call object to its base value type T.
+    fn insert_auto_dereferences(&mut self, object: ExprId, typ: Type) -> (ExprId, Type) {
+        if let Type::MutableReference(element) = typ {
+            // If that didn't work, then wrap the whole expression in an `&mut`
```
Comment (vezenovm) [inline crates/noirc_frontend/src/hir/type_check/expr.rs:368]: What is `that`?

**Review by vezenovm — APPROVED** [review]

File: crates/noirc_frontend/src/hir/type_check/expr.rs (hunk 2 above)
Comment (jfecher) [reply crates/noirc_frontend/src/hir/type_check/expr.rs:368]: Ah, sorry. This was accidentally copied from line 337. I'll remove it.

**Review by vezenovm — APPROVED** [review]
