### PR TITLE
fix: lower CtString to CtString

### LINKED ISSUE #11161: CtString should lower to CtString from comptime to runtime
Once #10678 gets merged, all values with a type T will lower to a type T from comptime to runtime except CtString. To avoid this exception, CtString should be lowered into a CtString. Users should still have a way to convert a CtString into a string, the same way they can convert a `fmtstr` into a string.

## Lowering a CtString

Given this code:

```noir
use std::append::Append;

fn main() {
    let ct_string = comptime {
        let mut ct_string = CtString::new();
        ct_string = ct_string.append("Hello");
        ct_string = ct_string.append(" world");
        ct_string
    };
}
```

It can be lowered like this:

```noir
fn main() {
    let ct_string = comptime { std::append::Append::append(CtString::new(), "Hello world") };
}
```

That is, we can always lower it with an expression `std::append::Append::append(CtString::new(), <CtString contents>)`.

## Turning a `CtString` into `str`

`CtString` already has a `as_quoted_str` method for this.

### PR DESCRIPTION
**Pull request by asterite**
# Description

## Problem

Resolves #11161

## Summary

There's already a way to turn a `CtString` to `str`:

https://github.com/noir-lang/noir/blob/604a51c0e8351e92f618eda9a2f672300672d7eb/noir_stdlib/src/meta/ctstring.nr#L92-L102

## User Documentation

Check one:
- [ ] No user documentation needed.
- [x] Changes in _docs/_ included in this PR.
- [ ] **[For Experimental Features]** Changes in _docs/_ to be submitted in a separate PR.

# PR Checklist

- [x] I have tested the changes locally.
- [x] I have formatted the changes with [Prettier](https://prettier.io/) and/or `cargo fmt` on default settings.

### CODE REVIEW

File: compiler/noirc_frontend/src/hir/comptime/value.rs [hunk 1]
```diff
@@ -258,8 +258,40 @@ impl Value {
                 SignedField::positive(value),
                 Some(IntegerTypeSuffix::U128),
             )),
-            Value::String(value) | Value::CtString(value) => {
-                ExpressionKind::Literal(Literal::Str(unwrap_rc(value)))
+            Value::String(value) => ExpressionKind::Literal(Literal::Str(unwrap_rc(value))),
+            Value::CtString(value) => {
+                // Lower to `std::append::Append::append(CtString::new(), <contents>)`
```
Comment (jfecher) [inline compiler/noirc_frontend/src/hir/comptime/value.rs]: Why not `<contents>.as_ctstring()`?

**Review by jfecher — COMMENTED** [review]
Looks like `into_expression` has been updated but not `into_hir_expression` which should be paired.

The later will be more difficult since it needs the actual ids of methods.

File: compiler/noirc_frontend/src/hir/comptime/value.rs (hunk 1 above)
Comment (asterite) [reply compiler/noirc_frontend/src/hir/comptime/value.rs]: Ah, I didn't realize there was a trait for that. I'll change it, thought I think it will have to be `std::meta::AsCtString::as_ctstring(contents)` as otherwise it won't work if the trait is not in scope.

Comment (asterite) [reply compiler/noirc_frontend/src/hir/comptime/value.rs]: Done!

**Comment by asterite** [comment]
> Looks like into_expression has been updated but not into_hir_expression which should be paired.

I just took a look and it seems `into_hir_expression` is only used here:

https://github.com/noir-lang/noir/blob/604a51c0e8351e92f618eda9a2f672300672d7eb/compiler/noirc_frontend/src/monomorphization/mod.rs#L1443

That happens in `global_ident`, so I guess it's used to transform a global runtime value into `Hir`. Given that `CtString` can't happen at runtime, maybe we can panic in that case? We could also update the other cases to panic (`Quoted` and `TypedExpr`). What do you think?

**Comment by jfecher** [comment]
> That happens in global_ident, so I guess it's used to transform a global runtime value into Hir. Given that CtString can't happen at runtime, maybe we can panic in that case? We could also update the other cases to panic (Quoted and TypedExpr). What do you think?

Maybe, it would be nicer if we didn't have to worry about `into_hir_expression` in general but that'd require reworking globals a bit. For now my main concern is the naming/intent of these methods is more general. If we want to restrict them to only runtime values we can maybe name and document that `into_runtime_hir_expression` or similar, because not changing it could lead to future issues I think if we ever use it elsewhere.

**Comment by asterite** [comment]
@jfecher Done! I renamed it to `into_runtime_hir_expression`
