### PR TITLE
fix: disable comptime printing when requesting json output

### LINKED ISSUE #9380: Comptime printing breaks brillig bytecode benchmarks
Jake and I noticed that the `regression_cancelling` contains some comptime prints which pollute the output of stdout. [This then prevents `jq` from properly parsing the output](https://github.com/noir-lang/noir/actions/runs/16724041622/job/47335279780#step:4:20).

We already disable the runtime prints (by directing them into `std::io::empty()`) but we don't have any equivalent for comptime printing so these all go into stdout. We should allow passing a custom writer for the comptime interpreter to use as well.

### PR DESCRIPTION
**Pull request by TomAFrench**
# Description

## Problem\*

Resolves #9380 

## Summary\*

We now specify that we expect zero comptime printing when requesting a machine readable output.

## Documentation\*

Check one:
- [x] No documentation needed.
- [ ] Documentation included in this PR.
- [ ] **[For Experimental Features]** Documentation to be submitted in a separate PR.

# PR Checklist\*

- [x] I have tested the changes locally.
- [x] I have formatted the changes with [Prettier](https://prettier.io/) and/or `cargo fmt` on default settings.

### CODE REVIEW

File: tooling/nargo_cli/src/cli/info_cmd.rs [hunk 1]
```diff
@@ -61,6 +61,11 @@ impl WorkspaceCommand for InfoCommand {
 }
 
 pub(crate) fn run(mut args: InfoCommand, workspace: Workspace) -> Result<(), CliError> {
+    if args.json {
+        // In order to have a machine readable output, we cannot allow the program print arbitrary data to stdout.
```
Comment (TomAFrench) [inline tooling/nargo_cli/src/cli/info_cmd.rs]:
```suggestion
        // In order to have a machine readable output, we cannot allow the program to print arbitrary data to stdout.
```

**Review by jfecher — APPROVED** [review]
