### PR TITLE
fix: handle multiple imports in the same file

### LINKED ISSUE #3889: Re-exports don't work
### Aim

Compiling a structure like this one
```rust
mod Foo {
    struct NewType{
        a: Field,
    }
}

mod Bar {
    use crate::Foo::NewType as BarStruct;
    use crate::Foo::NewType;
}

mod Baz {
    struct Works {
        a: Field,
    }
    use crate::Bar::BarStruct;
    use crate::Bar::NewType;
}

fn main(works: Baz::Works, fails: Baz::BarStruct, also_fails: Baz::NewType) -> pub Field {
    works.a + fails.a + also_fails.a
}

```

### Expected Behavior

Should compile

### Bug

```
% nargo compile                                                                                                                                                                                ~/constructor mainframe
error: Could not resolve 'BarStruct' in path
   ┌─ /mnt/user-data/alvaro/constructor/src/main.nr:23:21
   │
23 │     use crate::Bar::BarStruct;
   │                     ---------
   │

error: Could not resolve 'NewType' in path
   ┌─ /mnt/user-data/alvaro/constructor/src/main.nr:24:21
   │
24 │     use crate::Bar::NewType;
   │                     -------
   │

error: Could not resolve 'BarStruct' in path
   ┌─ /mnt/user-data/alvaro/constructor/src/main.nr:27:40
   │
27 │ fn main(works: Baz::Works, fails: Baz::BarStruct, also_fails: Baz::NewType) -> pub Field {
   │                                        ---------
   │

error: Could not resolve 'NewType' in path
   ┌─ /mnt/user-data/alvaro/constructor/src/main.nr:27:68
   │
27 │ fn main(works: Baz::Works, fails: Baz::BarStruct, also_fails: Baz::NewType) -> pub Field {
   │                                                                    -------
   │
```

### To Reproduce

1.
2.
3.
4.

### Installation Method

None

### Nargo Version

_No response_

### Additional Context

_No response_

### Would you like to submit a PR for this Issue?

No

### Support Needs

_No response_

### PR DESCRIPTION
**Pull request by guipublic**
# Description

## Problem\*

Resolves #3889

## Summary\*

An import of an imported object in the same file would not work because the imports are added to the module after they are resolved. To fix this we simply process the imports one-by-one.

## Documentation\*

Check one:
- [X] No documentation needed.
- [ ] Documentation included in this PR.
- [ ] **[Exceptional Case]** Documentation to be submitted in a separate PR.

# PR Checklist\*

- [X] I have tested the changes locally.
- [X] I have formatted the changes with [Prettier](https://prettier.io/) and/or `cargo fmt` on default settings.

### CODE REVIEW

File: compiler/noirc_frontend/src/hir/def_collector/dc_crate.rs [hunk 1]
```diff
@@ -259,37 +259,39 @@ impl DefCollector {
...
-                    let err = DefCollectorErrorKind::Duplicate {
-                        typ: DuplicateType::Import,
-                        first_def,
-                        second_def,
-                    };
-                    errors.push((err.into(), root_file_id));
+        // Resolve unresolved imports collected from the crate, one by one.
+        for collected_import in def_collector.collected_imports {
+            let (resolved, unresolved_imports) =
+                resolve_imports(crate_id, vec![collected_import], &context.def_maps);
```
Comment (jfecher) [inline compiler/noirc_frontend/src/hir/def_collector/dc_crate.rs:265]: Can you change this function to `resolve_import` and take a single import so that we don't need the Vec?

Comment (guipublic) [reply compiler/noirc_frontend/src/hir/def_collector/dc_crate.rs]: Done

**Review by jfecher — APPROVED** [review]
