### PR TITLE
fix(elaborator): Make `<Self as {trait}>::{ident}` work as `Self::{ident}`

### LINKED ISSUE #10858: `<Self as Trait>` with associated type in trait impl method where clause failing to resolve
### Aim

I attempted to compile the following programs:

1.

```noir
pub trait Foo {
    type Bar;

    fn foo() where Self::Bar: Foo;
}

fn main() { }
```

2.

```noir
pub trait Foo {
    type Bar;

    fn foo() where <Self as Foo>::Bar: Foo;
}

fn main() { }
```

### Expected Behavior

I expected that compiling these two programs would succeed or fail equivalently

### Bug

1.

```
❯ ~/.nargo/bin/nargo compile
```

2.

```
❯ ~/.nargo/bin/nargo compile
error: No matching impl found for `Self: Foo<Bar = _>`
  ┌─ src/main.nr:4:29
  │
4 │     fn foo() where <Self as Foo>::Bar: Foo;
  │                             --- No impl for `Self: Foo<Bar = _>`
  │
```

### To Reproduce

1.
2.
3.
4.

### Workaround

None

### Workaround Description

_No response_

### Additional Context

_No response_

### Project Impact

None

### Blocker Context

_No response_

### Nargo Version

nargo version = 1.0.0-beta.16 noirc version = 1.0.0-beta.16+a4c13872630141d6e728cfff3b36f004e013e4bb (git version hash: a4c13872630141d6e728cfff3b36f004e013e4bb, is dirty: false)

### NoirJS Version

_No response_

### Proving Backend Tooling & Version

_No response_

### Would you like to submit a PR for this Issue?

None

### Support Needs

_No response_

### PR DESCRIPTION
**Pull request by aakoshh**
# Description

## Problem

Resolves #10858 

## Summary

Adds a new `Elaborator::try_resolve_self_as_trait_path` method which is called by `Elaborator::resolve_self_as_trait_path` and forwards the `AsTraitPath` to `Elaborator::resolve_named_type` in the following circumstances:
* the object in the path is `Self`, and
* the trait in the path is the one currently being elaborated, and
* if the trait in the path has generics, they are all unbound and generally just a repeat of the traits generics

## Additional Context

The motivation for this was that it works in Rust, and that Rust in particular reports associated type mismatches this way: `<Self as Foo<Bar>>::Bar`, but we rejected that format, so to report report errors we had to use just `Self::Bar`.

Note that this version still does not compile:
```noir
    pub trait Foo<Baz> {
        type Bar;
        fn bar() -> <Self as Foo>::Bar;
    }
    fn main() {}
```

It says:
```
error: Foo expects 1 generic but 0 were given
  ┌─ src/main.nr:3:26
  │
3 │     fn bar() -> <Self as Foo>::Bar;
  │                          ---
```
It works in Rust, but not in Noir. I thought it would be beyond the scope of this PR to try to change it.

## User Documentation

Check one:
- [x] No user documentation needed.
- [ ] Changes in _docs/_ included in this PR.
- [ ] **[For Experimental Features]** Changes in _docs/_ to be submitted in a separate PR.

# PR Checklist

- [x] I have tested the changes locally.
- [ ] I have formatted the changes with [Prettier](https://prettier.io/) and/or `cargo fmt` on default settings.

### CODE REVIEW

File: compiler/noirc_frontend/src/ast/statement.rs [hunk 1]
```diff
@@ -399,15 +399,19 @@ pub struct UnsafeExpression {
...
-/// refers to an associated type of a particular impl, or in a value
-/// context where `ident` may refer to an associated constant or a
-/// function within the impl.
+/// An `AsTraitPath` may be used in in the following contexts:
+/// * in a type context where the `ident` refers to an associated type of a particular impl
+/// * in a value context where `ident` may refer to an associated constant or a function within the impl
+/// * in the trait definition itself, referring to an associated type of the same trait
 #[derive(Debug, PartialEq, Eq, Clone, Hash)]
 pub struct AsTraitPath {
+    /// The `MyObject` in the path.
```
Comment (asterite) [inline compiler/noirc_frontend/src/ast/statement.rs]:
```suggestion
    /// The `MyType` in the path.
```

(or change the other one)

File: compiler/noirc_frontend/src/hir_def/types.rs [hunk 2]
```diff
@@ -39,7 +39,7 @@ pub use unification::UnificationError;
 /// Types form trees but are not likely to be more deep than just a few levels in real code.
 pub const TYPE_RECURSION_LIMIT: u32 = 100;
 
-#[derive(Eq, Clone, Ord, PartialOrd)]
+#[derive(Eq, Clone, Ord, PartialOrd, Debug)]
```
Comment (asterite) [inline compiler/noirc_frontend/src/hir_def/types.rs]: I thought I was the only one who had to make this change to be able to understand types while debugging, but apparently not :-)

File: compiler/noirc_frontend/src/ast/statement.rs [hunk 3]
```diff
@@ -439,7 +443,7 @@ impl Path {
         self.segments.pop().unwrap()
     }
 
-    fn join(mut self, ident: Ident) -> Path {
+    pub fn join(mut self, ident: Ident) -> Path {
```
Comment (asterite) [inline compiler/noirc_frontend/src/ast/statement.rs:446]: Maybe `pub(crate)` would be enough here?

File: compiler/noirc_frontend/src/hir_def/types.rs (hunk 2 above)
Comment (jfecher) [reply compiler/noirc_frontend/src/hir_def/types.rs]: I'm curious what about the existing Debug impl is insufficient here. It is meant to be explicit like the derived Debug while significantly more terse (and thus more practical for large types)

File: compiler/noirc_frontend/src/hir_def/types.rs [hunk 4]
```diff
@@ -3175,107 +3175,107 @@ impl From<&Type> for PrintableType {
...
-            Type::Reference(element, true) => {
-                write!(f, "&mut {element:?}")
-            }
-            Type::Quoted(quoted) => write!(f, "{quoted}"),
-            Type::InfixExpr(lhs, op, rhs, _) => write!(f, "({lhs:?} {op} {rhs:?})"),
-        }
-    }
-}
+// impl std::fmt::Debug for Type {
+//     fn fmt(&self, f: &mut std::fmt::Formatter<'_>) -> std::fmt::Result {
```
Comment (jfecher) [inline compiler/noirc_frontend/src/hir_def/types.rs]: Old impl is still commented out

**Review by jfecher — CHANGES_REQUESTED** [review]
Blocking while we still have the commented code (I'd prefer us to keep the old impl)

File: compiler/noirc_frontend/src/hir_def/types.rs (hunk 2 above)
Comment (asterite) [reply compiler/noirc_frontend/src/hir_def/types.rs]: I can't remember now, but maybe it's that for bound type variables we get to see their bound value but we don't see what the type variable ID is. And sometimes when I see `'T -> ...` I can't remember that's it's a named generic, etc.

Comment (aakoshh) [reply compiler/noirc_frontend/src/hir_def/types.rs]: Oops, I didn't want to check this in 😬 

The existing debug wants to be readable, but for someone unfamiliar with the types, it's hard to be sure what exactly I'm looking at. I can't bring examples either, but I always have to do this to save time.

File: compiler/noirc_frontend/src/ast/statement.rs (hunk 3 above)
Comment (aakoshh) [reply compiler/noirc_frontend/src/ast/statement.rs:446]: I used `pub` because every other method, and the fields themselves, are `pub`, and this seems like a useful one that one would be able to do themselves, so we aren't actually hiding anything here.

File: compiler/noirc_frontend/src/hir_def/types.rs (hunk 4 above)
Comment (aakoshh) [reply compiler/noirc_frontend/src/hir_def/types.rs]: Sorry, removed.

File: compiler/noirc_frontend/src/hir_def/types.rs (hunk 2 above)
Comment (aakoshh) [reply compiler/noirc_frontend/src/hir_def/types.rs]: It only affected generics and type variables, it seemed cryptic at the beginning. I wanted to know what `Self::Bar` was represented as without having to reverse engineer the debug format. Or maybe it was the stuff in the `TraitGenerics`, I'm not sure.

Comment (jfecher) [reply compiler/noirc_frontend/src/hir_def/types.rs]: I see - maybe using it more would help with identification and save time in the future then?

I do wish there was a way to derive Debug but keep this more terse format by default.
