### PR TITLE
fix(ssa refactor): Implement array equality in SSA-gen

### LINKED ISSUE #1625: Array equality
### Problem

Array equality isn't implemented in the ssa refactor's acir gen. Currently binary ops only support numerics, and not arrays.

### Happy Case

The following program should compile (taken from `array_neq` test):
```nr
// Simple example of checking where two arrays are different
fn main(a: [Field; 32], b: [Field; 32]) {
     assert(a != b);
}
```

### Alternatives Considered

_No response_

### Additional Context

_No response_

### Would you like to submit a PR for this Issue?

No

### Support Needs

_No response_

### PR DESCRIPTION
**Pull request by jfecher**
# Description

## Problem\*

Resolves #1625

## Summary\*

Implements array equality in ssa-gen. This way we should not need a separate pass in brillig.

We could still improve this code-gen with, e.g. an early exit if any `eq` returns false but I elected for the more straightforward approach for now since this code is temporary.

## Documentation

- [ ] This PR requires documentation updates when merged.

  

  - [ ] I will submit a noir-lang/docs PR.

  

  - [ ] I will request for and support Dev Rel's help in documenting this PR.

  
  

## Additional Context

# PR Checklist\*

- [x] I have tested the changes locally.
- [x] I have formatted the changes with [Prettier](https://prettier.io/) and/or `cargo fmt` on default settings.

### CODE REVIEW

File: crates/noirc_evaluator/src/ssa_refactor/ssa_gen/context.rs [hunk 1]
```diff
@@ -255,6 +259,88 @@ impl<'a> FunctionContext<'a> {
...
+        rhs: ValueId,
+    ) -> Values {
+        let lhs_type = self.builder.type_of_value(lhs);
+        let rhs_type = self.builder.type_of_value(rhs);
+
+        let (array_length, element_type) = match (lhs_type, rhs_type) {
+            (Type::Array(lhs_elements, lhs_length), Type::Array(rhs_elements, rhs_length)) => {
+                assert_eq!(lhs_elements.len(), 1, "== is unimplemented for arrays of structs");
+                assert_eq!(rhs_elements.len(), 1, "== is unimplemented for arrays of structs");
+                assert_eq!(lhs_elements[0], rhs_elements[0]);
```
Comment (joss-aztec) [inline crates/noirc_evaluator/src/ssa_refactor/ssa_gen/context.rs:297]: Instead of `lhs_elements` & `rhs_elements`, could we call them `lhs_composite_type` & `lhs_composite_type`. Otherwise the length == 1 assert is unintuitive to read.

**Review by joss-aztec — CHANGES_REQUESTED** [review]
Only a minor naming comment

File: crates/noirc_evaluator/src/ssa_refactor/ssa_gen/context.rs (hunk 1 above)
Comment (joss-aztec) [reply crates/noirc_evaluator/src/ssa_refactor/ssa_gen/context.rs]: Hope you'll forgive me for editing - wanted to get this merged!

**Review by joss-aztec — APPROVED** [review]
