### PR TITLE
fix(ssa): Count params as loop header defined variables when folding

### LINKED ISSUE #11629: Constant folding hoists instruction into immediate dominator without considering param definition dominance
### Aim

Take this constant folding unit test:
```rust
 #[test]
    #[should_panic(expected = "`v3` should already be in scope")]
    fn hoisting_instruction_using_param_into_dominator_of_param() {
      let src = "
      brillig(inline) impure fn main f0 {
        b0(v0: [Field; 2]):
          inc_rc v0
          v6 = array_get v0, index u32 1 -> Field
          v8 = add Field 3, v6
          v9 = array_set v0, index u32 1, value v8
          jmp b1(v9, u1 1)
        b1(v1: [Field; 2], v2: u1):
          jmpif v2 then: b2, else: b3
        b2():
          v18 = array_get v1, index u32 0 -> Field
          v19 = add Field 3, v18
          v20 = array_set v1, index u32 0, value v19
          jmp b1(v20, u1 0)
        b3():
          v11 = array_set v0, index u32 1, value v8
          jmp b4(v11, u1 1)
        b4(v3: [Field; 2], v4: u1):
          jmpif v4 then: b5, else: b6
        b5():
          v14 = array_get v3, index u32 0 -> Field
          v15 = add Field 3, v14
          v16 = array_set v3, index u32 0, value v15
          jmp b4(v16, u1 0)
        b6():
          v13 = array_get v3, index u32 0 -> Field
          return v13
      }
      ";
      let ssa = Ssa::from_str(src).unwrap();
      let ssa = ssa.fold_constants_with_brillig(DEFAULT_MAX_ITER);
      let elements = vec![Value::field((-2i128).into()), Value::field((-1i128).into())];
      let inputs = Value::array(elements, vec![Type::field()]);
      let _ = ssa.interpret(vec![inputs]).unwrap();
    }
```

### Expected Behavior

The test will pass as I added `should_panic`, but I would expect the interpreter to succeed after constant folding this program. 

### Bug

An instruction using v3 is being hoisted past its definition in a block parameter. 

### To Reproduce

1. Run the test above in our constant folding unit tests module

### Workaround

None

### Workaround Description

_No response_

### Additional Context

_No response_

### Project Impact

Blocker

### Blocker Context

_No response_

### Nargo Version

nargo version = 1.0.0-beta.19 noirc version = 1.0.0-beta.19+a9bd0754e257aad2a7fe19764432aefbcb6d8129 (git version hash: 161f152105f34f8926cef20bc30c33ab41d6da20, is dirty: false)

### NoirJS Version

_No response_

### Proving Backend Tooling & Version

_No response_

### Would you like to submit a PR for this Issue?

Yes

### Support Needs

_No response_

### PR DESCRIPTION
**Pull request by vezenovm**
# Description

## Problem

Resolves #11629

## Summary

Cleanup for https://github.com/noir-lang/noir/pull/11616

Block parameters of loop headers are now included in defined in the header preventing the hoisting logic from moving instructions that use those parameters past the loop header into the pre-header.

## User Documentation

Check one:
- [X] No user documentation needed.
- [ ] Changes in _docs/_ included in this PR.
- [ ] **[For Experimental Features]** Changes in _docs/_ to be submitted in a separate PR.

# PR Checklist

- [X] I have tested the changes locally.
- [X] I have formatted the changes with [Prettier](https://prettier.io/) and/or `cargo fmt` on default settings.

### CODE REVIEW

**Review by jfecher — APPROVED** [review]
Straightforward fix

File: compiler/noirc_evaluator/src/ssa/opt/constant_folding/mod.rs [hunk 1]
```diff
@@ -3028,4 +3032,79 @@ mod tests {
...
+          jmp b4(v16, u1 0)
+        b6():
+          v13 = array_get v3, index u32 0 -> Field
+          return v13
+      }
+      ";
+        let ssa = Ssa::from_str(src).unwrap();
+        let ssa = ssa.fold_constants_with_brillig(DEFAULT_MAX_ITER);
+        // ssa.normalize_ids();
+        // println!("{}", ssa.print_with(None));
```
Comment (aakoshh) [inline compiler/noirc_evaluator/src/ssa/opt/constant_folding/mod.rs]: Leftover?

Comment (vezenovm) [reply compiler/noirc_evaluator/src/ssa/opt/constant_folding/mod.rs]: yes removed
