### PR TITLE
fix(ssa): Type check ToRadix and ToBits intrinsic calls

### LINKED ISSUE #8517: `Simplification should not alter return type` panic from fuzzing input
### Aim

Attempted to test the following program (from AFL fuzzer):
```
brillig(inline) predicate_pure fn mayn f0 {
  b0(v0: Field, v1: [u8; 3], x2: [Field; 4]):
    inc_rc v1 call f5(u1 1, v0)
    return
}
brillig(inline) fn svhpw_uzciqwtrained f5 {
  b0(v0: u1, v1: [u4; 2]):
    vOOOOJGOHKWIPGMXT = call to_le_radix(v0, u32 256) -> [u7; 1]
    return
}
```

### Expected Behavior

Expected invalid input or similar errors

### Bug

Simplification panics: is this due to missing type checks before the simplification of calls is run?

```bash
    Finished `dev` profile [optimized + debuginfo] target(s) in 0.16s
     Running `/home/michael/coding/rust/noir/target/debug/ssa_afl_fuzzer ../../target/debug/ssa_afl_fuzzer`

thread 'main' panicked at compiler/noirc_evaluator/src/ssa/ir/dfg/simplify/call.rs:361:9:
assertion `left == right` failed: Simplification should not alter return type
  left: Array([Numeric(Unsigned { bit_size: 8 })], 1)
 right: Array([Numeric(Unsigned { bit_size: 7 })], 1)
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
```

### To Reproduce

1.
2.
3.
4.

### Workaround

None

### Workaround Description

_No response_

### Additional Context

based off commit `a68685690bd65c204260944087214b3ca0899a59`

### Project Impact

None

### Blocker Context

_No response_

### Nargo Version

_No response_

### NoirJS Version

_No response_

### Proving Backend Tooling & Version

_No response_

### Would you like to submit a PR for this Issue?

None

### Support Needs

_No response_

### PR DESCRIPTION
**Pull request by vezenovm**
# Description

## Problem\*

Resolves #8517 

Builds upon #8765 

## Summary\*

We simply now type check calls to the ToRadix and ToBits intrinsics that their first arguments is a field type and the second argument is an unsigned 32 bit integer.

## Documentation\*

Check one:
- [ ] No documentation needed.
- [ ] Documentation included in this PR.
- [X] **[For Experimental Features]** Documentation to be submitted in a separate PR.

# PR Checklist\*

- [X] I have tested the changes locally.
- [X] I have formatted the changes with [Prettier](https://prettier.io/) and/or `cargo fmt` on default settings.

### CODE REVIEW

**Review by TomAFrench — APPROVED** [review]

File: compiler/noirc_evaluator/src/ssa/validation/mod.rs [hunk 1]
```diff
@@ -148,6 +148,24 @@ impl<'f> Validator<'f> {
...
+                        assert_eq!(arguments.len(), 2);
+                        let radix_typ = dfg.type_of_value(arguments[1]);
+                        assert!(matches!(
+                            radix_typ,
+                            Type::Numeric(NumericType::Unsigned { bit_size: 32 })
+                        ));
+                    } else {
+                        // Intrinsic::ToBits always has a set radix
+                        assert_eq!(arguments.len(), 1);
+                    }
```
Comment (TomAFrench) [inline compiler/noirc_evaluator/src/ssa/validation/mod.rs]: This should be a `match` rather than `if-else` so we don't hit all the other intrinsics.
