### PR TITLE
fix: greenlight `remove_bit_shifts`

### LINKED ISSUE #9525: Greenlight `remove_bit_shifts` for audits
Prepare https://github.com/noir-lang/noir/blob/master/compiler/noirc_evaluator/src/ssa/opt/remove_bit_shifts.rs for audits:

- [ ] Code shall be cleanly **implemented**:
  - [ ] Code pre-conditions shall be simple to test for
  - [ ] Code shall require minimal constraint injections from elsewhere
    - Counter-example: the `remove_bit_shifts` SSA pass undesirably relies on constraints injected during SSAgen to secure the final output
  - [ ] Main logic flow shall be simple to understand
    - If applicable, use helpers to encapsulate internal logics and abstract away noise from implementation details
  - [ ] No big brain needed to read the code
- [ ] Code shall be clearly **documented**, covering:
  - [ ] Purpose of the code
  - [ ] Design decisions made
  - [ ] Interfaces with other code (e.g. dependencies, downstream integrations)
  - [ ] Expected (or the lack of) pre- and post-conditions
  - [ ] If applicable, expected ACIR/Brillig differences or implications
- [ ] Code shall be logically **unit tested** for every feature of the code

**Target Date:** 12 Sep 2025

Close this Issue when the requirements above are met. That is, the code piece is ready for audits.

### PR DESCRIPTION
**Pull request by asterite**
# Description

## Problem

Resolves #9525

## Summary

This PR also fixes a bug: when simplifying shr/shl we were not checking if the result overflowed. It worked by change because we always truncated the result to fit the target bit size, which explains why just removing that truncation led to a failure.

## Documentation

Check one:
- [x] No documentation needed.
- [ ] Documentation included in this PR.
- [ ] **[For Experimental Features]** Documentation to be submitted in a separate PR.

# PR Checklist

- [x] I have tested the changes locally.
- [x] I have formatted the changes with [Prettier](https://prettier.io/) and/or `cargo fmt` on default settings.

### CODE REVIEW

File: compiler/noirc_evaluator/src/ssa/opt/remove_bit_shifts.rs [hunk 1]
```diff
@@ -1,3 +1,65 @@
...
+//! for i in 1 .. bit_size + 1 {
+//!     let r_squared = r * r;
+//!     let b = exponent_bits[bit_size - i];
+//!     r = if b { 2 * r_squared } else { r_squared };
+//! }
+//! ```
+//!
+//! ## Unsigned shift-left
+//!
+//! Shifting an unsigned integer to the right by N is the same as multipling by 2^N.
```
Comment (asterite) [inline compiler/noirc_evaluator/src/ssa/opt/remove_bit_shifts.rs]:
```suggestion
//! Shifting an unsigned integer to the right by N is the same as multiplying by 2^N.
```

**Review by TomAFrench — CHANGES_REQUESTED** [review]
blocking on above

File: compiler/noirc_evaluator/src/ssa/opt/remove_bit_shifts.rs [hunk 2]
```diff
@@ -1,3 +1,65 @@
...
+//! ```
+//!
+//! Like in the previous case, if the shift amount is not a constant it's computed
+//! via square&multiply.
+//!
+//! ## Signed shift-right
+//!
+//! This case is similar to unsigned shift-right except that for negative numbers we
+//! slightly adjust the value to shift, then adjust it again after performing the division,
+//! so the results are the exepcted ones.
```
Comment (TomAFrench) [inline compiler/noirc_evaluator/src/ssa/opt/remove_bit_shifts.rs]:
```suggestion
//! so the results are the expected ones.
```

**Review by TomAFrench — APPROVED** [review]
