### PR TITLE
fix(brillig): Globals entry point reachability analysis 

### LINKED ISSUE #7158: Reachability analysis for Brillig entry point globals initialization
### Aim

If I have multiple Brillig entry points, I should only initialize globals for the entry points that use those globals. For example let's take this program:
```
global EXPONENTIATE: [[Field; 2]; 2] = [[1, 1], [0, 0]];

fn main(x: u32, y: pub Field) {
     /// Safety: testing context
    unsafe {
        check_acc_entry_point(x as Field, y);
        assert(entry_point(x) == 2);
    }
}
unconstrained fn check_acc_entry_point(x: Field, y: Field) {
    let mut acc: Field = 0;
    for i in 0..2 {
        for j in 0..2 {
            acc += EXPONENTIATE[i][j];
        }
    }
    assert(acc != 0);
    assert(x != y);
}
fn inner(x: u32) -> u32 {
    x + 1
}
unconstrained fn entry_point(x: u32) -> u32 {
    inner(x + 1)
}
```
I have two entry points: `check_acc_entry_point` and `entry_point`. I want to be able to initialize the appropriate globals for the given entry point without any repeat initialization.  

### Expected Behavior

I should initialize all the globals for `check_acc_entry_point`, however, this is unnecessary for `entry_point` which does not use all of the globals like the `EXPONENTIATE` array. I should also be able to differentiate which globals are used in which entry points. For example, the `1` constant in `entry_point` can be shared with the global space `1` constant. We should be able to only initialize the globals used in a given a entry point.

### Bug

Currently we are executing all the Brillig necessary to initialize _all_ globals for _every_ entry point.  

Taking the ACIR for the program above:

<details><summary>Details</summary>
<p>
unconstrained func 0

[Const { destination: Direct(2), bit_size: Integer(U32), value: 1 }, Const { destination: Direct(1), bit_size: Integer(U32), value: 49221 }, Const { destination: Direct(0), bit_size: Integer(U32), value: 3 }, Const { destination: Relative(3), bit_size: Integer(U32), value: 2 }, Const { destination: Relative(4), bit_size: Integer(U32), value: 0 }, CalldataCopy { destination_address: Direct(49219), size_address: Relative(3), offset_address: Relative(4) }, Mov { destination: Relative(1), source: Direct(49219) }, Mov { destination: Relative(2), source: Direct(49220) }, Call { location: 13 }, Call { location: 43 }, Const { destination: Relative(1), bit_size: Integer(U32), value: 49221 }, Const { destination: Relative(2), bit_size: Integer(U32), value: 0 }, Stop { return_data: HeapVector { pointer: Relative(1), size: Relative(2) } }, Const { destination: Direct(32835), bit_size: Field, value: 1 }, Mov { destination: Direct(32836), source: Direct(1) }, Const { destination: Direct(32837), bit_size: Integer(U32), value: 3 }, BinaryIntOp { destination: Direct(1), op: Add, bit_size: U32, lhs: Direct(1), rhs: Direct(32837) }, IndirectConst { destination_pointer: Direct(32836), bit_size: Integer(U32), value: 1 }, BinaryIntOp { destination: Direct(32837), op: Add, bit_size: U32, lhs: Direct(32836), rhs: Direct(2) }, Mov { destination: Direct(32838), source: Direct(32837) }, Store { destination_pointer: Direct(32838), source: Direct(32835) }, BinaryIntOp { destination: Direct(32838), op: Add, bit_size: U32, lhs: Direct(32838), rhs: Direct(2) }, Store { destination_pointer: Direct(32838), source: Direct(32835) }, Const { destination: Direct(32837), bit_size: Field, value: 0 }, Mov { destination: Direct(32838), source: Direct(1) }, Const { destination: Direct(32839), bit_size: Integer(U32), value: 3 }, BinaryIntOp { destination: Direct(1), op: Add, bit_size: U32, lhs: Direct(1), rhs: Direct(32839) }, IndirectConst { destination_pointer: Direct(32838), bit_size: Integer(U32), value: 1 }, BinaryIntOp { destination: Direct(32839), op: Add, bit_size: U32, lhs: Direct(32838), rhs: Direct(2) }, Mov { destination: Direct(32840), source: Direct(32839) }, Store { destination_pointer: Direct(32840), source: Direct(32837) }, BinaryIntOp { destination: Direct(32840), op: Add, bit_size: U32, lhs: Direct(32840), rhs: Direct(2) }, Store { destination_pointer: Direct(32840), source: Direct(32837) }, Mov { destination: Direct(32839), source: Direct(1) }, Const { destination: Direct(32840), bit_size: Integer(U32), value: 3 }, BinaryIntOp { destination: Direct(1), op: Add, bit_size: U32, lhs: Direct(1), rhs: Direct(32840) }, IndirectConst { destination_pointer: Direct(32839), bit_size: Integer(U32), value: 1 }, BinaryIntOp { destination: Direct(32840), op: Add, bit_size: U32, lhs: Direct(32839), rhs: Direct(2) }, Mov { destination: Direct(32841), source: Direct(32840) }, Store { destination_pointer: Direct(32841), source: Direct(32836) }, BinaryIntOp { destination: Direct(32841), op: Add, bit_size: U32, lhs: Direct(32841), rhs: Direct(2) }, Store { destination_pointer: Direct(32841), source: Direct(32838) }, Return, Call { location: 89 }, Mov { destination: Relative(4), source: Direct(1) }, BinaryIntOp { destination: Direct(1), op: Add, bit_size: U32, lhs: Direct(1), rhs: Direct(2) }, Const { destination: Relative(5), bit_size: Field, value: 0 }, Store { destination_pointer: Relative(4), source: Relative(5) }, Const { destination: Relative(6), bit_size: Integer(U32), value: 1 }, Const { destination: Relative(7), bit_size: Integer(U32), value: 0 }, Const { destination: Relative(8), bit_size: Integer(U32), value: 2 }, Mov { destination: Relative(3), source: Relative(7) }, Jump { location: 53 }, BinaryIntOp { destination: Relative(9), op: LessThan, bit_size: U32, lhs: Relative(3), rhs: Relative(8) }, JumpIf { condition: Relative(9), location: 69 }, Jump { location: 56 }, Load { destination: Relative(3), source_pointer: Relative(4) }, BinaryFieldOp { destination: Relative(4), op: Equals, lhs: Relative(3), rhs: Relative(5) }, Const { destination: Relative(3), bit_size: Integer(U1), value: 0 }, BinaryIntOp { destination: Relative(5), op: Equals, bit_size: U1, lhs: Relative(4), rhs: Relative(3) }, JumpIf { condition: Relative(5), location: 63 }, Const { destination: Relative(6), bit_size: Integer(U32), value: 0 }, Trap { revert_data: HeapVector { pointer: Direct(1), size: Relative(6) } }, BinaryFieldOp { destination: Relative(4), op: Equals, lhs: Relative(1), rhs: Relative(2) }, BinaryIntOp { destination: Relative(1), op: Equals, bit_size: U1, lhs: Relative(4), rhs: Relative(3) }, JumpIf { condition: Relative(1), location: 68 }, Const { destination: Relative(2), bit_size: Integer(U32), value: 0 }, Trap { revert_data: HeapVector { pointer: Direct(1), size: Relative(2) } }, Return, Const { destination: Relative(10), bit_size: Integer(U32), value: 2 }, BinaryIntOp { destination: Relative(11), op: LessThan, bit_size: U32, lhs: Relative(3), rhs: Relative(10) }, JumpIf { condition: Relative(11), location: 73 }, Call { location: 95 }, BinaryIntOp { destination: Relative(10), op: Add, bit_size: U32, lhs: Direct(32839), rhs: Direct(2) }, BinaryIntOp { destination: Relative(11), op: Add, bit_size: U32, lhs: Relative(10), rhs: Relative(3) }, Load { destination: Relative(9), source_pointer: Relative(11) }, Load { destination: Relative(10), source_pointer: Relative(4) }, BinaryIntOp { destination: Relative(12), op: Add, bit_size: U32, lhs: Relative(9), rhs: Direct(2) }, BinaryIntOp { destination: Relative(13), op: Add, bit_size: U32, lhs: Relative(12), rhs: Relative(7) }, Load { destination: Relative(11), source_pointer: Relative(13) }, BinaryFieldOp { destination: Relative(12), op: Add, lhs: Relative(10), rhs: Relative(11) }, BinaryIntOp { destination: Relative(11), op: Add, bit_size: U32, lhs: Relative(9), rhs: Direct(2) }, BinaryIntOp { destination: Relative(13), op: Add, bit_size: U32, lhs: Relative(11), rhs: Relative(6) }, Load { destination: Relative(10), source_pointer: Relative(13) }, BinaryFieldOp { destination: Relative(9), op: Add, lhs: Relative(12), rhs: Relative(10) }, Store { destination_pointer: Relative(4), source: Relative(9) }, BinaryIntOp { destination: Relative(9), op: Add, bit_size: U32, lhs: Relative(3), rhs: Relative(6) }, Mov { destination: Relative(3), source: Relative(9) }, Jump { location: 53 }, Const { destination: Direct(32772), bit_size: Integer(U32), value: 30720 }, BinaryIntOp { destination: Direct(32771), op: LessThan, bit_size: U32, lhs: Direct(0), rhs: Direct(32772) }, JumpIf { condition: Direct(32771), location: 94 }, IndirectConst { destination_pointer: Direct(1), bit_size: Integer(U64), value: 17843811134343075018 }, Trap { revert_data: HeapVector { pointer: Direct(1), size: Direct(2) } }, Return, IndirectConst { destination_pointer: Direct(1), bit_size: Integer(U64), value: 16761564377371454734 }, Trap { revert_data: HeapVector { pointer: Direct(1), size: Direct(2) } }, Return]

unconstrained func 1

[Const { destination: Direct(2), bit_size: Integer(U32), value: 1 }, Const { destination: Direct(1), bit_size: Integer(U32), value: 49221 }, Const { destination: Direct(0), bit_size: Integer(U32), value: 3 }, Const { destination: Relative(2), bit_size: Integer(U32), value: 1 }, Const { destination: Relative(3), bit_size: Integer(U32), value: 0 }, CalldataCopy { destination_address: Direct(49219), size_address: Relative(2), offset_address: Relative(3) }, Cast { destination: Direct(49219), source: Direct(49219), bit_size: Integer(U32) }, Mov { destination: Relative(1), source: Direct(49219) }, Call { location: 14 }, Call { location: 44 }, Mov { destination: Direct(49220), source: Relative(1) }, Const { destination: Relative(2), bit_size: Integer(U32), value: 49220 }, Const { destination: Relative(3), bit_size: Integer(U32), value: 1 }, Stop { return_data: HeapVector { pointer: Relative(2), size: Relative(3) } }, Const { destination: Direct(32835), bit_size: Field, value: 1 }, Mov { destination: Direct(32836), source: Direct(1) }, Const { destination: Direct(32837), bit_size: Integer(U32), value: 3 }, BinaryIntOp { destination: Direct(1), op: Add, bit_size: U32, lhs: Direct(1), rhs: Direct(32837) }, IndirectConst { destination_pointer: Direct(32836), bit_size: Integer(U32), value: 1 }, BinaryIntOp { destination: Direct(32837), op: Add, bit_size: U32, lhs: Direct(32836), rhs: Direct(2) }, Mov { destination: Direct(32838), source: Direct(32837) }, Store { destination_pointer: Direct(32838), source: Direct(32835) }, BinaryIntOp { destination: Direct(32838), op: Add, bit_size: U32, lhs: Direct(32838), rhs: Direct(2) }, Store { destination_pointer: Direct(32838), source: Direct(32835) }, Const { destination: Direct(32837), bit_size: Field, value: 0 }, Mov { destination: Direct(32838), source: Direct(1) }, Const { destination: Direct(32839), bit_size: Integer(U32), value: 3 }, BinaryIntOp { destination: Direct(1), op: Add, bit_size: U32, lhs: Direct(1), rhs: Direct(32839) }, IndirectConst { destination_pointer: Direct(32838), bit_size: Integer(U32), value: 1 }, BinaryIntOp { destination: Direct(32839), op: Add, bit_size: U32, lhs: Direct(32838), rhs: Direct(2) }, Mov { destination: Direct(32840), source: Direct(32839) }, Store { destination_pointer: Direct(32840), source: Direct(32837) }, BinaryIntOp { destination: Direct(32840), op: Add, bit_size: U32, lhs: Direct(32840), rhs: Direct(2) }, Store { destination_pointer: Direct(32840), source: Direct(32837) }, Mov { destination: Direct(32839), source: Direct(1) }, Const { destination: Direct(32840), bit_size: Integer(U32), value: 3 }, BinaryIntOp { destination: Direct(1), op: Add, bit_size: U32, lhs: Direct(1), rhs: Direct(32840) }, IndirectConst { destination_pointer: Direct(32839), bit_size: Integer(U32), value: 1 }, BinaryIntOp { destination: Direct(32840), op: Add, bit_size: U32, lhs: Direct(32839), rhs: Direct(2) }, Mov { destination: Direct(32841), source: Direct(32840) }, Store { destination_pointer: Direct(32841), source: Direct(32836) }, BinaryIntOp { destination: Direct(32841), op: Add, bit_size: U32, lhs: Direct(32841), rhs: Direct(2) }, Store { destination_pointer: Direct(32841), source: Direct(32838) }, Return, Call { location: 55 }, Const { destination: Relative(2), bit_size: Integer(U32), value: 1 }, BinaryIntOp { destination: Relative(3), op: Add, bit_size: U32, lhs: Relative(1), rhs: Relative(2) }, BinaryIntOp { destination: Relative(4), op: LessThanEquals, bit_size: U32, lhs: Relative(1), rhs: Relative(3) }, JumpIf { condition: Relative(4), location: 50 }, Call { location: 61 }, BinaryIntOp { destination: Relative(1), op: Add, bit_size: U32, lhs: Relative(3), rhs: Relative(2) }, BinaryIntOp { destination: Relative(4), op: LessThanEquals, bit_size: U32, lhs: Relative(3), rhs: Relative(1) }, JumpIf { condition: Relative(4), location: 54 }, Call { location: 61 }, Return, Const { destination: Direct(32772), bit_size: Integer(U32), value: 30720 }, BinaryIntOp { destination: Direct(32771), op: LessThan, bit_size: U32, lhs: Direct(0), rhs: Direct(32772) }, JumpIf { condition: Direct(32771), location: 60 }, IndirectConst { destination_pointer: Direct(1), bit_size: Integer(U64), value: 17843811134343075018 }, Trap { revert_data: HeapVector { pointer: Direct(1), size: Direct(2) } }, Return, IndirectConst { destination_pointer: Direct(1), bit_size: Integer(U64), value: 5019202896831570965 }, Trap { revert_data: HeapVector { pointer: Direct(1), size: Direct(2) } }, Return]
</p>
</details> 

If you run a diff on the Brillig for unconstrained func 0 and 1 you will be see a large chunk of identical Brillig code (it starts with `Const { destination: Direct(32835), bit_size: Field, value: 1 }`). This is the globals initialization. 

To outline this more clearly this is the output of `--show-brillig`

<details><summary>Details</summary>
<p>

GlobalInit:
  CONST M32835 = 1
  MOV M32836, FreeMem
  CONST M32837 = 3
  FreeMem = FreeMem + M32837
  ICONST M32836 = 1
  M32837 = M32836 + M2
  MOV M32838, M32837
  STORE *M32838 = M32835
  M32838 = M32838 + M2
  STORE *M32838 = M32835
  CONST M32837 = 0
  MOV M32838, FreeMem
  CONST M32839 = 3
  FreeMem = FreeMem + M32839
  ICONST M32838 = 1
  M32839 = M32838 + M2
  MOV M32840, M32839
  STORE *M32840 = M32837
  M32840 = M32840 + M2
  STORE *M32840 = M32837
  MOV M32839, FreeMem
  CONST M32840 = 3
  FreeMem = FreeMem + M32840
  ICONST M32839 = 1
  M32840 = M32839 + M2
  MOV M32841, M32840
  STORE *M32841 = M32836
  M32841 = M32841 + M2
  STORE *M32841 = M32838
  RETURN
Function(Id(1), None):
  CALL Procedure(CheckMaxStackDepth)

... continued Brillig

</p>
</details> 

`GlobalsInit` is the first external call of every entry point. You can see that the `globals_init` flag is set to true for all calls to `gen_brillig_for`:

https://github.com/noir-lang/noir/blob/c8d5ce5e72f3171f24e4fe2b94ac098ba6d99ef6/compiler/noirc_evaluator/src/brillig/brillig_gen.rs#L65 

### To Reproduce

1. Make a new program with `nargo` and copy the program above
2. Run `nargo execute --show-ssa --show-brillig --print-acir` to see all the relevant output.
3. Observe that there is only one `GlobalsInit` function and it is reused for the two different Brillig entry points called from ACIR

### Workaround

None

### Workaround Description

_No response_

### Additional Context

_No response_

### Project Impact

Blocker

### Blocker Context

I am marking this is a blocker as it is a pretty meaningful cost that cannot be avoided when using globals

### Nargo Version

nargo version = 1.0.0-beta.1 noirc version = 1.0.0-beta.1+02056d6a3ca2932a0062552859195a4e3b11f9dc (git version hash: 02056d6a3ca2932a0062552859195a4e3b11f9dc, is dirty: true)

### NoirJS Version

_No response_

### Proving Backend Tooling & Version

_No response_

### Would you like to submit a PR for this Issue?

None

### Support Needs

_No response_

### PR DESCRIPTION
**Pull request by vezenovm**
# Description

## Problem\*

Resolves #7158 

Was not sure whether to label this as a feat or a fix. It fixes repeated global initialization across multiple Brillig entry points, however, it is a pretty meaningful change in how we generate globals so I thought about labelling it a feat. As I labelled the issue a bug I have used the fix prefix. 

## Summary\*

We now track globals Brillig artifacts by their entry point rather than having a single globals artifact for all entry points. 

A few changes have been made:
1. We now track the `used_globals` by function rather than over the entire program.
2. We made a new `BrilligGlobals` context structure to simplify code gen for globals.
3. When generating `BrilligGlobals` we create some initial state from the function call graph.
```
    /// Both `used_globals` and `brillig_entry_points` need to be built
    /// from a function call graph.
    /// 
    /// Maps a Brillig function to the globals used in that function.
    /// This includes all globals used in functions called internally.
    used_globals: HashMap<FunctionId, HashSet<ValueId>>,
    /// Maps a Brillig entry point to all functions called in that entry point.
    /// This includes any nested calls as well, as we want to be able to associate
    /// any Brillig function with the appropriate global allocations.
    brillig_entry_points: HashMap<FunctionId, HashSet<FunctionId>>,
```
4. We then declare the globals for each entry point by looping over `brillig_entry_points`. 
5. We construct a new mapping `inner_call_to_entry_point`
```
    /// Maps an inner call to its Brillig entry point
    /// This is simply used to simplify fetching global allocations when compiling
    /// individual Brillig functions.
    inner_call_to_entry_point: HashMap<FunctionId, Vec<FunctionId>>,
```
6. After compiling the globals we instantiate a map of entry points to global allocations.
7. The `GlobalInit` label has been updated to be associated with a function id representing an entry point. We now have `GlobalInit(entry_point: FunctionId)`. 

## Additional Context

Most of the line additions are from the large global array included in `test_programs/execution_success/global_var_regression_entry_points/src/consts.nr` file. This change is most meaningful when tested with a large amount of globals across many entry points. 

I compiled `global_var_regression_entry_points` with `nargo compile --force --inliner-aggressiveness -100000000000000`.
Running `NOIR_LOG=trace nargo execute` looking at `nargo::ops::execute: close time.busy` for multiple runs:
On master:
~35ms
This PR:
~7ms

About a 5x improvement in this example.

Looking at the execution report for `rollup-block-root` we look to see a large benefit:
This PR:
```
  {
    "artifact_name": "rollup-block-root",
    "time": "36.700s"
  },
``` 
While on master we are at ~41s. So about a 12% improvement. 

## Documentation\*

Check one:
- [X] No documentation needed.
- [ ] Documentation included in this PR.
- [ ] **[For Experimental Features]** Documentation to be submitted in a separate PR.

# PR Checklist\*

- [X] I have tested the changes locally.
- [X] I have formatted the changes with [Prettier](https://prettier.io/) and/or `cargo fmt` on default settings.

### CODE REVIEW

File: compiler/noirc_evaluator/src/brillig/brillig_ir.rs [hunk 1]
```diff
@@ -221,11 +221,18 @@ impl<F: AcirField + DebugToString> BrilligContext<F, ScratchSpace> {
...
 /// Special brillig context to codegen global values initialization
 impl<F: AcirField + DebugToString> BrilligContext<F, GlobalSpace> {
-    pub(crate) fn new_for_global_init(enable_debug_trace: bool) -> BrilligContext<F, GlobalSpace> {
+    pub(crate) fn new_for_global_init(
+        enable_debug_trace: bool,
+        entry_point: FunctionId,
+        // start_memory_address: usize,
+        // Global registers are declared externally as to be shared across
+        // multiple Brillig contexts
+        // registers: GlobalSpace,
```
Comment (vezenovm) [inline compiler/noirc_evaluator/src/brillig/brillig_ir.rs:230]:
```suggestion
```

File: compiler/noirc_evaluator/src/brillig/brillig_gen/brillig_globals.rs [hunk 2]
```diff
@@ -31,13 +220,218 @@ pub(crate) fn convert_ssa_globals(
...
+
+        assert_eq!(
+            brillig.globals.len(),
+            2,
+            "Should have a globals artifact associated with each entry point"
+        );
+        for (func_id, mut artifact) in brillig.globals {
+            let labels = artifact.take_labels();
+            // When entering a context two labels are created.
+            // One is a context label and another is a section albel.
```
Comment (vezenovm) [inline compiler/noirc_evaluator/src/brillig/brillig_gen/brillig_globals.rs:282]:
```suggestion
            // One is a context label and another is a section label.
```

File: compiler/noirc_evaluator/src/brillig/brillig_gen/brillig_globals.rs [hunk 3]
```diff
@@ -31,13 +220,218 @@ pub(crate) fn convert_ssa_globals(
...
+
+        assert_eq!(
+            brillig.globals.len(),
+            3,
+            "Should have a globals artifact associated with each entry point"
+        );
+        for (func_id, mut artifact) in brillig.globals {
+            let labels = artifact.take_labels();
+            // When entering a context two labels are created.
+            // One is a context label and another is a section albel.
```
Comment (vezenovm) [inline compiler/noirc_evaluator/src/brillig/brillig_gen/brillig_globals.rs:398]:
```suggestion
            // One is a context label and another is a section label.
```

File: compiler/noirc_evaluator/src/brillig/brillig_gen/brillig_globals.rs [hunk 4]
```diff
@@ -1,24 +1,213 @@
...
+
+impl BrilligGlobals {
+    pub(crate) fn new(
+        functions: &BTreeMap<FunctionId, Function>,
+        mut used_globals: HashMap<FunctionId, HashSet<ValueId>>,
+        main_id: FunctionId,
+    ) -> Self {
+        let mut brillig_entry_points = HashMap::default();
+        for (_, function) in functions.iter() {
+            if function.runtime().is_acir() {
```
Comment (TomAFrench) [inline compiler/noirc_evaluator/src/brillig/brillig_gen/brillig_globals.rs:48]:
```suggestion
        let brillig_functions = functions.iter().filter(|func| func.is_brillig());
        for (_, function) in brillig_functions {
```

I'd prefer to use iterators to do any initial preprocessing like this.

File: compiler/noirc_evaluator/src/brillig/mod.rs [hunk 5]
```diff
@@ -89,17 +92,25 @@ impl Ssa {
...
-        brillig.globals_memory_size = globals_size;
+        let globals_dfg = DataFlowGraph::from(globals);
+        brillig_globals.declare_globals(&globals_dfg, &mut brillig, enable_debug_trace);
 
         for brillig_function_id in brillig_reachable_function_ids {
+            let mut globals_allocations = HashMap::default();
+            let entry_point_allocations = brillig_globals.get_brillig_globals(brillig_function_id);
+            for map in entry_point_allocations {
+                globals_allocations.extend(map);
+            }
```
Comment (TomAFrench) [inline compiler/noirc_evaluator/src/brillig/mod.rs:110]: Should `get_brillig_global` return a `HashMap` directly? This is the only place we call it afaik.

File: compiler/noirc_evaluator/src/brillig/mod.rs [hunk 6]
```diff
@@ -74,7 +77,7 @@ impl std::ops::Index<FunctionId> for Brillig {
 impl Ssa {
     /// Compile Brillig functions and ACIR functions reachable from them
     #[tracing::instrument(level = "trace", skip_all)]
-    pub(crate) fn to_brillig(&self, enable_debug_trace: bool) -> Brillig {
+    pub(crate) fn to_brillig(&mut self, enable_debug_trace: bool) -> Brillig {
```
Comment (TomAFrench) [inline compiler/noirc_evaluator/src/brillig/mod.rs:80]: This makes me a little sad.

Comment (TomAFrench) [reply compiler/noirc_evaluator/src/brillig/mod.rs:80]: If it's necessary it's necessary but I guess it raises the question on whether we need to store the global usage tracker on the `Ssa` struct.

File: compiler/noirc_evaluator/src/brillig/brillig_gen/brillig_globals.rs [hunk 7]
```diff
@@ -1,24 +1,213 @@
...
+        used_globals: &mut HashMap<FunctionId, HashSet<ValueId>>,
+        brillig_entry_points: &mut HashMap<FunctionId, HashSet<FunctionId>>,
+        mut explored_functions: im::HashSet<FunctionId>,
+    ) {
+        if explored_functions.contains(&called_function.id()) {
+            return;
+        }
+        explored_functions.insert(called_function.id());
+
+        let inner_calls = called_functions_vec(called_function).into_iter().collect::<HashSet<_>>();
```
[the remark this answers is not in the document]
Comment (vezenovm) [reply compiler/noirc_evaluator/src/brillig/brillig_gen/brillig_globals.rs:116]: Yeah I had originally used `called_functions` as I did not need a `BTreeSet`. It should not have a big difference on performance though and I can switch over if we prefer.

File: compiler/noirc_evaluator/src/brillig/mod.rs [hunk 8]
```diff
@@ -89,17 +92,25 @@ impl Ssa {
             return brillig;
         }
 
+        let used_globals_map = std::mem::take(&mut self.used_globals);
+        let mut brillig_globals =
+            BrilligGlobals::new(&self.functions, used_globals_map, self.main_id);
+
         // Globals are computed once at compile time and shared across all functions,
         // thus we can just fetch globals from the main function.
```
[the remark this answers is not in the document]
Comment (vezenovm) [reply compiler/noirc_evaluator/src/brillig/mod.rs:100]: This is still accurate. They are computed once at compile time for SSA. I will provide some more context though as to not cause confusion.

File: compiler/noirc_evaluator/src/brillig/brillig_gen/brillig_globals.rs [hunk 9]
```diff
@@ -1,24 +1,213 @@
...
+
+            brillig.globals.insert(entry_point, artifact);
+            brillig.globals_memory_size.insert(entry_point, globals_size);
+        }
+
+        self.inner_call_to_entry_point = inner_call_to_entry_point;
+        self.entry_point_globals_map = entry_point_globals_map;
+    }
+
+    pub(crate) fn get_brillig_globals(
```
[the remark this answers is not in the document]
Comment (vezenovm) [reply compiler/noirc_evaluator/src/brillig/brillig_gen/brillig_globals.rs:173]: done

File: compiler/noirc_evaluator/src/brillig/mod.rs (hunk 5 above)
Comment (vezenovm) [reply compiler/noirc_evaluator/src/brillig/mod.rs:111]: yup that is cleaner. `get_brillig_global` returns a map now.

File: compiler/noirc_evaluator/src/brillig/mod.rs (hunk 6 above)
Comment (vezenovm) [reply compiler/noirc_evaluator/src/brillig/mod.rs:80]: I could avoid it by cloning `self.used_globals` if we desire, that is really the only reason I did this. I could also do it outside of `to_brillig`.

Comment (vezenovm) [reply compiler/noirc_evaluator/src/brillig/mod.rs:80]: I made a `to_brillig` and a `to_brillig_with_globals` method that takes in the used globals map. Let me know if that is preferred.

**Review by TomAFrench — APPROVED** [review]
LGTM
