### PR TITLE
fix: check trait constraints with type and generics

### LINKED ISSUE #10643: Potential issue when checking impl where clauses against trait constraint
### Problem

In trait_impls.rs/check_where_clause_against_trait(), when checking that a where clause is not stricter than the trait constraints, we skip the check when the bound traits match: `impl_constraint.trait_bound.trait_id == override_trait_constraint.trait_bound.trait_id`
E.g in this code:
```noir
    impl<A> Foo<A> for () where A: ToField {
        fn foo<B>(x: B) -> Field where B: ToField {
            x.to_field()
        }
    }
```
The impl specifies A: ToField, and foo has B: ToField, so the B: ToField constraint will be skipped, allowing to call foo for an i32 that (hypothetically) does not implement ToField.

### Happy Case

We should skip the check when the full constraint match (type + trait_id + generics), not just trait_id.

### Workaround

None

### Workaround Description

_No response_

### Additional Context

_No response_

### Project Impact

None

### Blocker Context

_No response_

### Would you like to submit a PR for this Issue?

None

### Support Needs

_No response_

### PR DESCRIPTION
**Pull request by guipublic**
# Description

## Problem

Resolves #10643

## User Documentation

Check one:
- [X] No user documentation needed.
- [ ] Changes in _docs/_ included in this PR.
- [ ] **[For Experimental Features]** Changes in _docs/_ to be submitted in a separate PR.

# PR Checklist

- [X] I have tested the changes locally.
- [ ] I have formatted the changes with [Prettier](https://prettier.io/) and/or `cargo fmt` on default settings.

### CODE REVIEW

File: compiler/noirc_frontend/src/elaborator/trait_impls.rs [hunk 1]
```diff
@@ -454,8 +454,11 @@ impl Elaborator<'_> {
         for override_trait_constraint in override_meta.trait_constraints.clone() {
             let override_constraint_is_from_impl =
                 trait_impl_where_clause.iter().any(|impl_constraint| {
-                    impl_constraint.trait_bound.trait_id
-                        == override_trait_constraint.trait_bound.trait_id
+                    impl_constraint.typ == override_trait_constraint.typ
+                        && impl_constraint.trait_bound.trait_id
+                            == override_trait_constraint.trait_bound.trait_id
+                        && impl_constraint.trait_bound.trait_generics
+                            == override_trait_constraint.trait_bound.trait_generics
```
Comment (jfecher) [inline compiler/noirc_frontend/src/elaborator/trait_impls.rs:461]: Raw equality on a Type won't catch `A == B` where A and B are generics used in equivalent locations just with different names.

Can you add another test which shows we don't error for a similar case when different names are used?

Comment (guipublic) [reply compiler/noirc_frontend/src/elaborator/trait_impls.rs:461]: Done
