### PR TITLE
fix(ssa): Cast to `u64` when inserting OOB checks in DIE

### LINKED ISSUE #10307: Min != Full: Index out of bounds on branch that never runs in a loop
### Aim

Reproduce nightly failure from https://github.com/noir-lang/noir/actions/runs/18863031928/job/53825277430

The following program fails with the normal workflow, but succeeds with `--minimal-ssa`:

```rust
fn main(mut a: [(bool, bool); 3], b: u32, c: bool) -> pub bool {
    for _ in 0..1 {
        let _ = if c { a[b] } else { a[0] };
    }
    false
}
```

inputs:
```toml
a = [[true, false], [false, false], [false, true]]
b = "0x00000000000000000000000000000000000000000000000000000000d98e8c43"
c = false
```

### Expected Behavior

It should return `false` because `c` is false.

### Bug

```console
$ cargo run -q -p nargo_cli -- execute --force --silence-warnings

error: Failed constraint
  ┌─ src/main.nr:3:24
  │
3 │         let _ = if c { a[b] } else { a[0] };
  │                        ----
  │
  = Call stack:
    1. src/main.nr:3:24

$ cargo run -q -p nargo_cli -- execute --force --silence-warnings --minimal-ssa
For more information about this error, try `rustc --explain E0602`.
[fuzz_testing] Circuit witness successfully solved
[fuzz_testing] Witness saved to target/fuzz_testing.gz
[fuzz_testing] Circuit output: false
```

### To Reproduce

```shell
RUST_LOG=debug NOIR_AST_FUZZER_SEED=0x633da51500100000 cargo test -q -p noir_ast_fuzzer_fuzz min_vs_full
```

### Workaround

None

### Workaround Description

_No response_

### Additional Context

_No response_

### Project Impact

None

### Blocker Context

_No response_

### Nargo Version

nargo version = 1.0.0-beta.14 noirc version = 1.0.0-beta.14+c3bcbc3bdc2f7dde1a9c9faf6cc68a7b61b57001 (git version hash: dd8b7e81c3249cbaef557b734220aac44e361090, is dirty: true)

### NoirJS Version

_No response_

### Proving Backend Tooling & Version

_No response_

### Would you like to submit a PR for this Issue?

Maybe

### Support Needs

_No response_

### PR DESCRIPTION
**Pull request by aakoshh**
# Description

## Problem

Resolves #10307 

## Summary

Changes the `replace_array_instructions_with_out_of_bounds_checks` to cast to `u64` instead of `u32` before putting a constraint on the maximum of the index, which should handle values that have potentially overflown when we calculate the flattened index of composite types.

## Additional Context

In the failing Noir example, we have the following code:
```rust
    for _ in 0..1 {
        let _ = if c { a[b] } else { a[0] };
    }
```
`c` is going to be false, so during execution we should always access `a[0]`, which should be fine, however `b` is a large number, and `a` is a `[(bool, bool); 3]`, which means it has 2 elements per item, so to access `b` we have to look up `2*b`, which is where the overflow happens: `2*b > u32::MAX`. 

Since https://github.com/noir-lang/noir/pull/10110 we again use unchecked operations to calculate the index, so this overflow will not cause an immediate failure. Instead, we rely on ACIR protecting against OOB lookups during `ArrayGet`:

```
After Initial SSA:
acir(inline) fn main f0 {
  ...
  b4():
    v14 = load v6 -> [(u1, u1); 3]
    v16 = unchecked_mul v1, u32 2
    v17 = array_get v14, index v16 -> u1
  ...
}
``` 

The problem is that here the result of the lookup is unused, so the DIE pass removes the lookup, but because it could fail with OOB, it leaves behind a constraint that the index has to be less than 6, which is the number of slots in the array (3*2). 

```
After Dead Instruction Elimination (1) (step 10):
acir(inline) predicate_pure fn main f0 {
...
  b4():
    v9 = unchecked_mul v1, u32 2
    v11 = lt v9, u32 6
    constrain v11 == u1 1, "Index out of bounds"
...
}
```

If we look at the generated ACIR opcodes, we see that a range constraint is inserted to check that the result of a division fits into 32 bits:
```
Compiled ACIR for main (non-transformed):
func 0
private parameters: [w0, w1, w2, w3, w4, w5, w6, w7]
public parameters: []
return values: [w8]
...
BRILLIG CALL func: 0, inputs: [2*w6 + 4294967290, 4294967296], outputs: [w9, w10]
BLACKBOX::RANGE input: w9, bits: 1
BLACKBOX::RANGE input: w10, bits: 32
ASSERT w10 = 2*w6 - 4294967296*w9 + 4294967290
ASSERT 0 = -w7*w9
...
```

With the changes in this PR, we'll have the following opcodes instead:
```
BRILLIG CALL func: 0, inputs: [2*w6 + 18446744073709551610, 18446744073709551616], outputs: [w9, w10]
BLACKBOX::RANGE input: w9, bits: 1
BLACKBOX::RANGE input: w10, bits: 64
ASSERT w10 = 2*w6 - 18446744073709551616*w9 + 18446744073709551610
ASSERT 0 = -w7*w9
```

We considered other alternatives:
* change all ops back to `checked`: but this is what we wanted to avoid by introducing the `Unfit` values into the SSA interpreter
* change any ops to `checked` for only those indexes which were protected by the array operations we remove in DIE: this would be more complex as we would have to revisit instructions we already inserted when we decide we are removing something

The approach in the PR is easy, since it only involves casting the index and the constant before we insert the constraint.

## User Documentation

Check one:
- [x] No user documentation needed.
- [ ] Changes in _docs/_ included in this PR.
- [ ] **[For Experimental Features]** Changes in _docs/_ to be submitted in a separate PR.

# PR Checklist

- [x] I have tested the changes locally.
- [ ] I have formatted the changes with [Prettier](https://prettier.io/) and/or `cargo fmt` on default settings.

### CODE REVIEW

File: compiler/noirc_evaluator/src/ssa/interpreter/mod.rs [hunk 1]
```diff
@@ -1464,6 +1464,22 @@ macro_rules! apply_int_comparison_op {
...
+/// and a `Constrain` in its place. `LessThan` implicitly includes a `RangeCheck` on
+/// the operands during ACIR generation, which an `Unfit` value would fail, so we
+/// cannot treat them differently here, even if we could compare the values as `u128`
+/// or `i128`.
+///
+/// Instead we `Cast` the values in SSA, which should have converted our `Unfit` value
+/// back to a `Fit` one with an acceptable number of bits (e.g. an `Unfit` `u32` into a `u64`).
+///
+/// If we still hit this method, we have a problem.
+fn unfit_lt(a: NumericValue, b: NumericValue) -> bool {
```
Comment (vezenovm) [inline compiler/noirc_evaluator/src/ssa/interpreter/mod.rs]: nit: Did we chose to leave this method as to have doc comments rather than making these comments inline in the match statement?

File: compiler/noirc_evaluator/src/ssa/opt/die/array_oob_checks.rs [hunk 2]
```diff
@@ -95,7 +95,16 @@ impl Context {
                 // let array_length = function.dfg.type_of_value(*array).flattened_size();
```
Comment (vezenovm) [inline compiler/noirc_evaluator/src/ssa/opt/die/array_oob_checks.rs]: this looks leftover from past reviews, we can delete it

File: compiler/noirc_evaluator/src/ssa/opt/die/array_oob_checks.rs [hunk 3]
```diff
@@ -95,7 +95,16 @@ impl Context {
...
 
                 // If we are here it means the index is dynamic, so let's add a check that it's less than length
-                let length_type = NumericType::length_type();
+
+                // Normally the indexes are expected to be u32, however if the array element is a composite type,
+                // the value could have overflown due to the unchecked multiplication with the element size.
+                // In ACIR, we relied on the ArrayGet itself to fail the circuit if it encounters an overflown value,
```
Comment (vezenovm) [inline compiler/noirc_evaluator/src/ssa/opt/die/array_oob_checks.rs]: nit: can say "we rely" as we still do rely on this

File: compiler/noirc_evaluator/src/ssa/interpreter/mod.rs (hunk 1 above)
Comment (aakoshh) [reply compiler/noirc_evaluator/src/ssa/interpreter/mod.rs]: Yeah that's the only reason. I'll move the comments into the match.
