### PR TITLE
fix: Prevent calling contract functions from outside the contract

### LINKED ISSUE #955: Disallow methods not in a contract scope to call methods in contract scope
### Problem

Methods and state variables in a contract scope have functionality and semantics that does not apply when you are not speaking about contracts. 

Consider the following program copied from Jake's awesome PR:

```rust
fn main(x : Field, y : pub Field) {
     constrain Foo::xy(x) == Foo::triple(y);
 }

 contract Foo {
      y : Field
     fn double(x: Field) -> Field { x * 2 }
     fn xy(x: Field) -> Field { x * y }
 }
```

Calling xy outside a contract brings forth a few question:

- What does it mean when one calls `xy` and accesses the state variable `y` in this context?
- Does this behaviour differ in anyways if `xy` was called by another contract?
- Can a regular Noir program modify the state of `y`?

I think we could _possibly_ define semantics for this however since there is no usecase for it and it would lead to additional complexity, its better to not allow it now and allow it in the future if we need to.

### Proposed solution

Noir contracts can call other contracts and programs. However, Noir programs cannot call Noir contracts.

### Alternatives considered

_No response_

### Additional context

_No response_

### PR DESCRIPTION
**Pull request by jfecher**
# Related issue(s)

Resolves #955

# Description

## Summary of changes

Prevents referencing items defined within a contract's scope from outside of a contract. Note that this currently will still allow calling these functions within another contract in the same program.

## Test additions / changes

Updated contracts test to no longer reference contract functions within main.

# Checklist

- [x] I have tested the changes locally.
- [x] I have formatted the changes with [Prettier](https://prettier.io/) and/or `cargo fmt` with default settings.
- [x] I have [linked](https://docs.github.com/en/issues/tracking-your-work-with-issues/linking-a-pull-request-to-an-issue) this PR to the issue(s) that it resolves.
- [x] I have reviewed the changes on GitHub, line by line.
- [x] I have ensured all changes are covered in the description.

## Documentation needs
- [x] This PR requires documentation updates when merged.

# Additional context

### CODE REVIEW

File: crates/noirc_frontend/src/hir/def_collector/errors.rs [hunk 1]
```diff
@@ -1,4 +1,5 @@
-use crate::{hir::resolution::import::ImportDirective, Ident};
```
Comment (kevaundray) [inline crates/noirc_frontend/src/hir/def_collector/errors.rs:1]: why was Ident separated?

**Review by kevaundray — APPROVED** [review]
LGTM - one small nit
