### PR TITLE
fix(brillig): Defensive assertion against call arguments heap corruption

### LINKED ISSUE #11201: Heap memory can be corrupted before trap
### Description

Brillig uses a fixed memory layout with a bounded stack region followed by the heap. Stack frame accesses use `MemoryAddress::relative(..)` offsets from `ReservedRegisters::stack_pointer()`. During calls, `BrilligContext::codegen_call()` (in @compiler/noirc_evaluator/src/brillig/brillig_ir/codegen_calls.rs) prepares the callee frame by copying the prior stack pointer to slot 0, placing arguments in subsequent slots, advancing the stack pointer, then issuing the call.

The stack/heap boundary is enforced by the `CheckMaxStackDepth` procedure compiled in @compiler/noirc_evaluator/src/brillig/brillig_ir/procedures/check_max_stack_depth.rs. This procedure constrains the stack pointer to stay within the maximum stack region and will trap execution when the next frame would encroach on the heap.

The vulnerability is that `codegen_call()` writes call arguments using `MemoryAddress::relative(..)` before it advances `ReservedRegisters::stack_pointer()` to the callee frame. The argument offsets are derived from the would-be callee frame size (`stack_size + 1`, `stack_size + 2`, …), but they are applied relative to the current frame’s stack pointer. If those offsets exceed the current frame’s bounds, the writes can cross out of the stack region and into heap memory.

Because the subsequent `CheckMaxStackDepth` procedure is designed to detect this boundary violation and trap, the VM is expected to halt. However, the heap corruption happens before the trap is triggered.

### Impact

Although execution is expected to trap due to stack-depth enforcement, the memory state at failure time is not reliable because heap cells may have been overwritten before the trap. Any debugging, tracing, or failure inspection that relies on heap contents at the time of the trap can be manipulated by a program that triggers this path, reducing trust in forensic outputs.

### Recommendation

1. **Add defensive bounds validation**: ensure the maximum argument/return slot used by `codegen_call()` cannot exceed the configured stack frame bounds, and trap before performing any out-of-frame writes.
2. **VM-side enforcement**: treat any relative memory access resolving outside the current stack region as an immediate fault to prevent pre-trap heap corruption even if codegen emits unsafe offsets.

### PR DESCRIPTION
**Pull request by vezenovm**
# Description

## Problem

Resolves #11201

## Summary

For now I felt an assertion during code gen is sufficient. This should only mostly affect already invalid programs (e.g., Stack too deep). 

## Additional Context

We could rewrite the code gen for calls to check the stack bounds before arguments are written rather than when entering the function. However, this feels like a larger rewrite that is not necessary for protecting programs and should come post-1.0.

Another option would be the other recommendation in #11201 which is VM-side enforcement. This would provide defense in depth against malformed inputs, however, downstream consumers (AVM) would be heavily affected. This feature has already been captured in https://github.com/noir-lang/noir/issues/9814.

## User Documentation

Check one:
- [X] No user documentation needed.
- [ ] Changes in _docs/_ included in this PR.
- [ ] **[For Experimental Features]** Changes in _docs/_ to be submitted in a separate PR.

# PR Checklist

- [X] I have tested the changes locally.
- [X] I have formatted the changes with [Prettier](https://prettier.io/) and/or `cargo fmt` on default settings.

### CODE REVIEW

File: compiler/noirc_evaluator/src/brillig/brillig_ir/codegen_calls.rs [hunk 1]
```diff
@@ -28,6 +28,16 @@ impl<F: AcirField + DebugToString, Registers: RegisterAllocator> BrilligContext<
...
 
+        // Ensure that writing call arguments won't exceed the current stack frame bounds.
+        // This check prevents heap corruption that could occur if arguments are written
+        // beyond the frame boundary before CheckMaxStackDepth runs in the called function.
+        let max_frame_size = self.registers().layout().max_stack_frame_size();
+        let arguments_len = arguments.len();
+        assert!(
+            (stack_size as usize) + arguments_len < max_frame_size,
+            "Call arguments would exceed stack frame bounds: frame_size={stack_size}, arguments={arguments_len}, max={max_frame_size}",
+        );
```
Comment (aakoshh) [inline compiler/noirc_evaluator/src/brillig/brillig_ir/codegen_calls.rs]: As I understand, this check is more conservative than it needs to be: it should be okay to write to the next stack frame, beyond the limits of the current stack frame, _except_ if we are already in the last viable stack frame, in which case we would be writing to the heap, and the `CheckMaxStackDepth` procedure would only trigger after we have already corrupted the heap. 

Say we have a `max_stack_size` of 1000 and a `max_frame_size` of 100. We don't know which frame we will be in here, just that because of [this check](https://github.com/noir-lang/noir/blob/d844fb00370606aed08e0d4081a96855f5d78196/compiler/noirc_evaluator/src/brillig/brillig_ir/procedures/check_max_stack_depth.rs#L41) it must be less than 900. 

(On a different note, shouldn't that be "not greater" rather than "less than"?)

Since this frame could have started at 890, and we could currently be at 985, we don't know if we would be pushing beyond 1000 if we wrote more than 5 arguments (with `stack_size` being 95).

If this is correct, it would be good to comment about it for clarity. 

Alternatively would it be possible to bring the max-stack-depth check forward here, to check if the _next_ frame would be viable, and then we could alter the assertion to be `arguments_len < max_frame_size`? I guess we would need to pass the next frame start as an argument via scratch space.

Comment (vezenovm) [reply compiler/noirc_evaluator/src/brillig/brillig_ir/codegen_calls.rs]: > As I understand, this check is more conservative than it needs to be: it should be okay to write to the next stack frame, beyond the limits of the current stack frame, except if we are already in the last viable stack frame

Yes good catch. You are correct this is very conservative and this assumes we are in the last viable frame. I could go off of the max stack size rather than the stack frame size. That is what `CheckMaxStackDepth` does as well. However, at compile time we do not know the runtime position of the stack pointer. We would need to code gen an additional check (which redundant with `CheckMaxStackDepth`). 

We have heap corruption when `stack_pointer + stack_size + arguments_len >= heap_start`.
If we assume the stack_pointer is at its limit we have `(stack_start + max_stack_size - max_frame_size) + stack_size + arguments_len >= stack_start + max_stack_size`. That simplifies down to `stack_size + arguments_len >= max_frame_size`. I have expanded the comments above this check. Let me know if those make sense. 

> On a different note, shouldn't that be "not greater" rather than "less than"?)

We want to assert that we remain less than the max stack size so that we do not corrupt the heap. Is this not just a reversal of the condition? Heap corruption occurs when `stack_pointer + stack_size + arguments_len >= heap_start`. We are just asserting the LHS is less than the RHS. 

> Alternatively would it be possible to bring the max-stack-depth check forward here, to check if the next frame would be viable

In the additional context of the PR description I mentioned that one solution would be to re-order when we call into `CheckMaxStackDepth`. What you are proposing is slightly different but along the same lines. However, at this stage I am trying to minimize structural code gen changes where possible. I also think #9814 is a valid long term alternative that should be explored as well so I would rather avoid code churn especially as programs that would hit this assert are already violating Brillig's memory bounds (would fail later stack depth check).

Comment (aakoshh) [reply compiler/noirc_evaluator/src/brillig/brillig_ir/codegen_calls.rs]: > Is this not just a reversal of the condition?

I meant in general, without considering arguments, if we assume `stack_start = 0` for simplicity, and my earlier example of `max_stack_size=1000` and `max_frame_size=100`, I'd expect the legal stack address range to be `[0, 999]`. 
Then if we look at this formula:
```
let last_possible_stack_start = stack_start + max_stack_size - max_frame_size;
``` 
then `last_possible_stack_start` would be 900, which means the last stack frame can go `[900, 999]`, and yet we assert that `stack_pointer < 900`, which looks like the last frame cannot be used.

By the reversal I wanted to suggest asserting `stack_pointer <= 900`.

File: compiler/noirc_evaluator/src/brillig/brillig_ir/codegen_calls.rs [hunk 2]
```diff
@@ -28,6 +28,34 @@ impl<F: AcirField + DebugToString, Registers: RegisterAllocator> BrilligContext<
...
+        //
+        // At compile time, we don't know the runtime stack_pointer position. The worst case
+        // is when we're in the last viable stack frame (last possible stack start in the `CheckMaxStackDepth` procedure).
+        // In that case, writing arguments could still overflow into the heap before the next `CheckMaxStackDepth` runs.
+        //
+        // Given that `CheckMaxStackDepth` ensures:
+        //   `stack_pointer < stack_start + max_stack_size - max_frame_size`
+        //
+        // Heap corruption occurs when:
+        //   `stack_pointer + stack_size + arguments_len >= stack_start + max_stack_size``
```
Comment (aakoshh) [inline compiler/noirc_evaluator/src/brillig/brillig_ir/codegen_calls.rs]:
```suggestion
        //   `stack_pointer + stack_size + arguments_len >= stack_start + max_stack_size`
```

File: compiler/noirc_evaluator/src/brillig/brillig_ir/codegen_calls.rs (hunk 1 above)
Comment (vezenovm) [reply compiler/noirc_evaluator/src/brillig/brillig_ir/codegen_calls.rs]: Ok I see what you mean. Yeah we would need to check against `ReservedRegisters::stack_pointer` in that case which is the condition in `CheckMaxStackDepth` (just after arguments are written). At that point I would rather re-write code gen or add VM-side enforcement. 

> the legal stack address range to be `[0, 999]`

For the stack pointer yes but not for a relative address on the stack. `stack_size` will be the relative address which is expected to be less than the max stack frame size (100 in your example) or we panic that the register is out of the stack bounds. So by asserting against the stack size we are only checking the current frame in the compile-time check here. 

> yet we assert that stack_pointer < 900, which looks like the last frame cannot be used

Well in that case the last possible stack start would just be 899. We go 0-99, 100-199, ..., 800-899.

Comment (aakoshh) [reply compiler/noirc_evaluator/src/brillig/brillig_ir/codegen_calls.rs]: > Well in that case the last possible stack start would just be 899. We go 0-99, 100-199, ..., 800-899.

Yes, that's sort of my point, that we lose out on the last stack frame, but only in a very edge case where the previous frame went to 899. We can end up with 899-998 being the last frame. So it's just a pedantic point to make sure I'm not insane.

I understood to `stack_size` effect, that's okay.
