### PR TITLE
fix: let LSP read `noirfmt.toml` for formatting files

### LINKED ISSUE #7340: LSP formatter always uses the default configuration
### Aim

If there's a `noirfmt.toml` file in a package or its workspace, that configuration should be picked up when a file is formatted via the LSP.

### Expected Behavior

`noirfmt.toml` is picked up from the package the file is in or, if it doesn't exist, from the parent workspace.

### Bug

The default formatter configuration is currently used, making it impossible to customize formatting while also using an IDE.

### To Reproduce

1.
2.
3.
4.

### Workaround

None

### Workaround Description

_No response_

### Additional Context

_No response_

### Project Impact

None

### Blocker Context

_No response_

### Nargo Version

_No response_

### NoirJS Version

_No response_

### Proving Backend Tooling & Version

_No response_

### Would you like to submit a PR for this Issue?

None

### Support Needs

_No response_

### PR DESCRIPTION
**Pull request by asterite**
# Description

## Problem

Resolves #7340

## Summary

Also changes the logic of `nargo fmt` to try to find the configuration file in the current directory or parent directories.

## Additional Context

It seems `rustfmt` also allows the config file to be called ".rustfmt.toml", or for it to be placed in the global config directory (`.config/rustfmt/`) but those could be done in follow-up PRs.

## Documentation

Check one:
- [x] No documentation needed.
- [ ] Documentation included in this PR.
- [ ] **[For Experimental Features]** Documentation to be submitted in a separate PR.

# PR Checklist

- [x] I have tested the changes locally.
- [x] I have formatted the changes with [Prettier](https://prettier.io/) and/or `cargo fmt` on default settings.

### CODE REVIEW

File: tooling/lsp/src/requests/mod.rs [hunk 1]
```diff
@@ -301,6 +301,7 @@ fn on_formatting_inner(
     state: &LspState,
     params: lsp_types::DocumentFormattingParams,
 ) -> Result<Option<Vec<lsp_types::TextEdit>>, ResponseError> {
+    let file_path = params.text_document.uri.to_file_path();
```
Comment (aakoshh) [inline tooling/lsp/src/requests/mod.rs:304]: Are you deliberately passing the path of the document being edited to `Config::read`, rather than the directory containing the document? I suppose it works, e.g. `/foo/bar/baz.nr` will try `/foo/bar/baz.nr/noirfmt.toml` first, then `/foo/bar/noirfmt.toml`, but it's a bit confusing.

File: tooling/nargo_fmt/src/config.rs [hunk 2]
```diff
@@ -56,16 +56,24 @@ config! {
...
-    pub fn read(path: &Path) -> Result<Self, ConfigError> {
-        let config_path = path.join("noirfmt.toml");
+    /// Reads a Config starting at the given path and going through the path parents
+    /// until a `noirfmt.toml` file is found in one of them or the root is reached.
+    pub fn read(mut path: &Path) -> Result<Self, ConfigError> {
+        loop {
+            let config_path = path.join("noirfmt.toml");
+            if config_path.exists() {
+                match std::fs::read_to_string(&config_path) {
+                    Ok(input) => return Self::of(&input),
```
Comment (aakoshh) [inline tooling/nargo_fmt/src/config.rs:66]: Conceptual question: should the format files be merged all the way from the bottom to the top, so you an place ` noirfmt.toml` file in a subdirectory to override a subset of the settings, but still apply the defaults from the workspace, similarly to how `.gitignore` works? I didn't see the docs of `rustfmt` mention this, but just thinking it might be a nice feature.

Comment (aakoshh) [reply tooling/nargo_fmt/src/config.rs:66]: For example I can imagine someone wanted to override some of the defaults for their entire project, but in a particular module with lots of array literals they find themselves unhappy with the default width. Should they now have to copy their workspace level config into that subdirectory so as not to revert back to the noir defaults?

Instead it could be something like this:

```
let mut toml_configs = Vec::new();
let mut path = document_file_path;
loop {
  path = match path.parent() {
    Some(path) => path,
    None => break,
  };
  match read_config_toml(path) { 
    Ok(toml) => toml_configs.push(toml_config),
    Err(Missing) => {},
    Err(e) => eprintln!("failed to parse {path}: {e}"), 
  }
}
toml_configs.reverse();
let config = toml_configs.fold(Config::default(), |mut cfg, toml| { cfg.fill_from_toml(toml); cfg });
```

File: tooling/lsp/src/requests/mod.rs (hunk 1 above)
Comment (asterite) [reply tooling/lsp/src/requests/mod.rs:304]: Ah, good point. I initially did it to make sure it checked parent paths but it makes sense to start with the parent.

File: tooling/nargo_fmt/src/config.rs (hunk 2 above)
Comment (asterite) [reply tooling/nargo_fmt/src/config.rs:66]: I like that idea! But I don't know if we should do it in this PR.

There's also a chance that a workspace configures the maximum width to 80, but a sub-project wants the default. They put an empty config file but it doesn't work because it's merged with the parent values. So maybe being explicit about inheritance might be desired (with an `inherit = true` or similar).

File: tooling/lsp/src/requests/mod.rs (hunk 1 above)
Comment (asterite) [reply tooling/lsp/src/requests/mod.rs]: Done!

File: tooling/lsp/src/requests/mod.rs [hunk 3]
```diff
@@ -327,6 +332,19 @@ fn on_formatting_inner(
     }
 }
 
+fn read_config(file_path: Option<&Path>) -> Config {
+    match file_path {
+        Some(file_path) => match Config::read(file_path) {
+            Ok(config) => config,
+            Err(err) => {
+                eprintln!("Failed to parse noirfmt.toml: {}", err);
```
Comment (aakoshh) [inline tooling/lsp/src/requests/mod.rs:340]: I'd print the full path, otherwise if there are multiple the user wouldn't know which one failed exactly.

Comment (aakoshh) [reply tooling/lsp/src/requests/mod.rs:340]: Ah never mind, that is part of the error 👍

Comment (asterite) [reply tooling/lsp/src/requests/mod.rs:340]: Ah, I thought about it but we don't always get the path in the error 😅 I'll change it to include it.

**Review by aakoshh — APPROVED** [review]
Great, let's consider the overrides in a follow up!

File: tooling/lsp/src/requests/mod.rs (hunk 3 above)
Comment (asterite) [reply tooling/lsp/src/requests/mod.rs]: Done! I change it to just print `err`, which now always includes the full path.

Comment (aakoshh) [reply tooling/lsp/src/requests/mod.rs]: Okay! A consequence here is that if there is an error in a deeply nested config, it reverts all of it to defaults, even if there is a non-default in one of the ancestors.

Comment (asterite) [reply tooling/lsp/src/requests/mod.rs]: I guess we could try again starting from the grandparent directory of the file that errored... but maybe for now this is good enough, if there's an error it might be noticeable and the user would fix it before continuing formatting everything.
