### PR TITLE
fix(lsp): Pass `--program-dir` to test command from codelens

### LINKED ISSUE #2291: The LSP should add the `--program-dir` flag to the test command
### Problem

Currently, if you have a vscode project that doesn't have a `Nargo.toml` file at the root, the `nargo test` command panics because it does not think there is any nargo package in the project. However, there could be a subdirectory that contains a nargo package and we're running a test inside of it. Since the LSP knows where the root of that workspace is, we can add `--program-dir` to the `nargo test` command and it'll work.

See also https://github.com/noir-lang/vscode-noir/issues/28 for more information.

### Happy Case

Using the `Run Test` lens in vscode should always work.

### Alternatives Considered

_No response_

### Additional Context

_No response_

### Would you like to submit a PR for this Issue?

Yes

### Support Needs

_No response_

### PR DESCRIPTION
**Pull request by phated**
# Description

## Problem\*

Resolves #2291  
Resolves https://github.com/noir-lang/vscode-noir/issues/28

## Summary\*

This passes the `--program-dir` flag when a user runs a test via a codelens. This ensures that the `Run Test` lens will always work, even if there is no Nargo.toml file at the root of the vscode workspace.

## Documentation

- [ ] This PR requires documentation updates when merged.

  

  - [ ] I will submit a noir-lang/docs PR.

  

  - [ ] I will request for and support Dev Rel's help in documenting this PR.

  
  

## Additional Context

# PR Checklist\*

- [x] I have tested the changes locally.
- [x] I have formatted the changes with [Prettier](https://prettier.io/) and/or `cargo fmt` on default settings.

### CODE REVIEW

File: crates/lsp/src/lib.rs [hunk 1]
```diff
@@ -199,6 +199,9 @@ fn on_code_lens_request(
                 title: TEST_CODELENS_TITLE.into(),
                 command: TEST_COMMAND.into(),
                 arguments: Some(vec![
+                    // TODO: Change this if we change the flag
```
Comment (TomAFrench) [inline crates/lsp/src/lib.rs:202]: How would we change this flag?

Comment (phated) [reply crates/lsp/src/lib.rs:202]: I believe @kobyhallx wants to rename it to `--root` or `--root-dir` in the future. This is trying to have a reminder to change this. But maybe the TODO should be at the location of the clap macro instead

**Review by kobyhallx — APPROVED** [review]
