### PR TITLE
fix(ssa refactor): Fix stack overflow during loop unrolling

### LINKED ISSUE #1650: Stack overflow
### Aim

Test named `9_conditional` should compile

### Expected Behavior

^

### Bug

The compiler crashes at some point after the inlining pass:
```
thread 'main' has overflowed its stack
fatal runtime error: stack overflow

```

### To Reproduce

1.
2.
3.
4.

### Installation Method

None

### Nargo Version

_No response_

### Additional Context

_No response_

### Would you like to submit a PR for this Issue?

No

### Support Needs

_No response_

### PR DESCRIPTION
**Pull request by jfecher**
# Description

## Problem\*

Resolves #1650 

## Summary\*

Fixes an issue causing loop unrolling to overflow the stack. Note that this does not fix 9_conditional completely since it runs into issues with the flatten_cfg pass. I believe this may be related to #1420.

### Example

Before:

```

```

After:

```

```

## Documentation

- [ ] This PR requires documentation updates when merged.

  

  - [ ] I will submit a noir-lang/docs PR.

  

  - [ ] I will request for and support Dev Rel's help in documenting this PR.

  
  

## Additional Context

# PR Checklist\*

- [ ] I have tested the changes locally.
- [ ] I have formatted the changes with [Prettier](https://prettier.io/) and/or `cargo fmt` on default settings.

### CODE REVIEW

File: crates/noirc_evaluator/src/ssa_refactor/ir/instruction.rs [hunk 1]
```diff
@@ -237,7 +237,9 @@ impl Instruction {
         match self {
             Instruction::Binary(binary) => binary.simplify(dfg),
             Instruction::Cast(value, typ) => {
-                if let Some(value) = (*typ == dfg.type_of_value(*value)).then_some(*value) {
+                if let Some(constant) = dfg.get_numeric_constant(*value) {
+                    SimplifiedTo(dfg.make_constant(constant, typ.clone()))
+                } else if let Some(value) = (*typ == dfg.type_of_value(*value)).then_some(*value) {
```
Comment (jfecher) [inline crates/noirc_evaluator/src/ssa_refactor/ir/instruction.rs:242]: This is not needed but is a small change I saw was missing when seeing `v0 = cast Field 0 as u32` in the output.

File: crates/noirc_evaluator/src/ssa_refactor/opt/unrolling.rs [hunk 2]
```diff
@@ -86,8 +86,10 @@ fn find_all_loops(function: &Function) -> Loops {
         }
     }
 
-    // Sort loops by block size so that we unroll the smaller, nested loops first as an optimization.
-    loops.sort_by(|loop_a, loop_b| loop_b.blocks.len().cmp(&loop_a.blocks.len()));
+    // Sort loops by block size so that we unroll the larger, outer loops of nested loops first.
+    // This is needed because inner loops may use the induction variable from their outer loops in
+    // their loop range.
+    loops.sort_by_key(|loop_| loop_.blocks.len());
```
Comment (jfecher) [inline crates/noirc_evaluator/src/ssa_refactor/opt/unrolling.rs:92]: This is the main fix for the bug

File: crates/noirc_evaluator/src/ssa_refactor/opt/unrolling.rs [hunk 3]
```diff
@@ -241,11 +243,11 @@ fn unroll_loop_header<'a>(
                 // unroll_into block from now on.
                 context.insert_block = unroll_into;
 
-                loop_.blocks.contains(&context.source_block).then_some(context)
+                Ok(loop_.blocks.contains(&context.source_block).then_some(context))
             } else {
                 // If this case is reached the loop either uses non-constant indices or we need
                 // another pass, such as mem2reg to resolve them to constants.
-                None
+                Err(())
```
Comment (jfecher) [inline crates/noirc_evaluator/src/ssa_refactor/opt/unrolling.rs:250]: This returning a `None` value instead of `Err` was signalling the loop was finished unrolling (successfully) rather than finished with an error.

This lead to the loop still being present in the program and kept being picked up again by find_all_loops. Signalling an error instead adds it to the list of loops that failed to unroll and prevents it from being unrolled again.

**Review by joss-aztec — APPROVED** [review]
LGTM

File: crates/noirc_evaluator/src/ssa_refactor/opt/unrolling.rs (hunk 2 above)
Comment (joss-aztec) [reply crates/noirc_evaluator/src/ssa_refactor/opt/unrolling.rs:92]: Makes sense
