### PR TITLE
fix(print): Print enums

### LINKED ISSUE #9294: Compiler crash: Trying to print enum
### Aim

Trying to understand how a slice of enums would be serialised for printing. I'm curious because the `decode_printable_value` consumes a varying number of items based on the tag, and I'm wondering what the capacity of such a slice would be. For tuples it looks like the slice capacity is flattened, e.g. for `[(1,2), (3,4)]` the slice capacity is 4, even though there are only 2 items in it, but at least it can be known up front.

The following program crashes the compiler:

```rust
enum Foo {
    One(i32),
    Two(i32, i32),
}

fn main() {
    let c: [Foo] = &[Foo::One(1), Foo::Two(2, 3)];
    println(c);
}
```

### Expected Behavior

Not crash.

### Bug

```console
❯ cargo run -q -p nargo_cli -- execute --force --silence-warnings
The application panicked (crashed).
Message:  a formatting trait implementation returned an error when the underlying stream did not: Error
Location: library/alloc/src/fmt.rs:650
```

### To Reproduce

1.
2.
3.
4.

### Workaround

None

### Workaround Description

_No response_

### Additional Context

_No response_

### Project Impact

None

### Blocker Context

_No response_

### Nargo Version

nargo version = 1.0.0-beta.8 noirc version = 1.0.0-beta.8+f7a772916e46d7d12637097c49d0509c23e971b8 (git version hash: f7a772916e46d7d12637097c49d0509c23e971b8, is dirty: true)

### NoirJS Version

_No response_

### Proving Backend Tooling & Version

_No response_

### Would you like to submit a PR for this Issue?

None

### Support Needs

_No response_

### PR DESCRIPTION
**Pull request by aakoshh**
# Description

## Problem

Resolves #9294

## Summary

* Fixes `decode_printable_value` to consume the correct number of fields when an enum is encountered.
* Fixes `to_string` to format enums, rather than return `None`.
* Adds a new `PrintableValue::Enum` to communicate the `tag` from the decoder to the formatter.
* Refactored `to_string` to so it can force us to implement handling for any new printable type.

## Additional Context

`decode_printable_value` looked at the `tag` and picked the corresponding list of fields from the variants, then consumed those fields. This assumes that we will see a varying number of fields, depending on which variant was serialised. 

I can't remember now what kind of repercussions this would have on slices and arrays, which generally assume that each element has a fixed size when we calculate the flattened size as `length * element_size`. It would have worked in the decoder, but it was suspicious. 

It turns out that Noir in fact passes a fixed number of fields regardless of the variant. I thought maybe this would be a number of `Field`s to accommodate the largest variant, but instead it is the concatenation of all variants, with all but one being defaults.

For example the following program:
```rust
enum Foo {
    One(Field),
    Two(u32, u64),
    Three,
}

fn main() {
    let c: [Foo; 3] = [Foo::One(10), Foo::Two(20, 30), Foo::Three];
    println(c);
}
```
turns into the following monomorphized AST:
```rust
fn main$f0() -> () {
    let c$l0 = [One$f1(10), Two$f2(20, 30), Three$g0];
    println$f3(c$l0);
}
fn One$f1($0$l1: Field) -> (Field, (Field,), (u32, u64), ()) {
    (0, ($0$l1), (0, 0), ())
}
fn Two$f2($0$l2: u32, $1$l3: u64) -> (Field, (Field,), (u32, u64), ()) {
    (1, (0), ($0$l2, $1$l3), ())
}
fn println$f3(input$l4: [(Field, (Field,), (u32, u64), ()); 3]) -> () {
    {
        print_unconstrained$f4(true, input$l4);
    }
}
unconstrained fn print_unconstrained$f4(with_newline$l5: bool, input$l6: [(Field, (Field,), (u32, u64), ()); 3]) -> () {
    print_oracle$print(with_newline$l5, input$l6, r#"{"kind":"array","length":3,"type":{"kind":"enum","name":"Foo","variants":[["One",[{"kind":"field"}]],["Two",[{"kind":"unsignedinteger","width":32},{"kind":"unsignedinteger","width":64}]],["Three",[]]]}}"#, false);
}
```
It clearly shows that `One` and `Two` are constructors return identical data structures with `(<tag>, (<One fields>,), (<Two fields>,), (<Three has no fields>))`. 

In SSA these are further flattened:
```rust
g0 = Field 2
g1 = Field 0
g2 = u32 0
g3 = u64 0

acir(inline) impure fn main f0 {
  b0():
    v8 = make_array [Field 0, Field 10, u32 0, u64 0, Field 1, Field 0, u32 20, u64 30, Field 2, Field 0, u32 0, u64 0] : [(Field, Field, u32, u64); 3]
    call f1(u1 1, v8)
    return
}
brillig(inline) impure fn print_unconstrained f1 {
  b0(v4: u1, v5: [(Field, Field, u32, u64); 3]):
    v40 = make_array b"{\"kind\":\"array\",\"length\":3,\"type\":{\"kind\":\"enum\",\"name\":\"Foo\",\"variants\":[[\"One\",[{\"kind\":\"field\"}]],[\"Two\",[{\"kind\":\"unsignedinteger\",\"width\":32},{\"kind\":\"unsignedinteger\",\"width\":64}]],[\"Three\",[]]]}}"
    call print(v4, v5, v40, u1 0)
    return
}
```

The array `[(Field, Field, u32, u64); 3]` has the `tag`, followed by the single `Field` in `One`, then two fields in `Two`:
```rust
make_array [
  Field 0,   Field 10,   u32 0, u64 0,   // One
  Field 1,   Field 0,    u32 20, u64 30, // Two
  Field 2,   Field 0,    u32 0, u64 0    // Three
] : [(Field, Field, u32, u64); 3]
```

## User Documentation

Check one:
- [x] No user documentation needed.
- [ ] Changes in _docs/_ included in this PR.
- [ ] **[For Experimental Features]** Changes in _docs/_ to be submitted in a separate PR.

# PR Checklist

- [x] I have tested the changes locally.
- [ ] I have formatted the changes with [Prettier](https://prettier.io/) and/or `cargo fmt` on default settings.

### CODE REVIEW

File: compiler/noirc_printable_type/src/lib.rs [hunk 1]
```diff
@@ -253,6 +258,27 @@ fn to_string<F: AcirField>(value: &PrintableValue<F>, typ: &PrintableType) -> Op
...
+                if elements.peek().is_some() {
+                    output.push_str(", ");
+                }
+            }
+            if has_fields {
+                output.push(')');
+            }
+        }
+
         _ => return None,
```
Comment (asterite) [inline compiler/noirc_printable_type/src/lib.rs]: I wonder if we could avoid this `_` so we can't forget to handle new types.

(this is really minor though!)

File: compiler/noirc_printable_type/src/lib.rs [hunk 2]
```diff
@@ -418,15 +444,18 @@ pub fn decode_printable_value<F: AcirField>(
...
+            //  [tag, variant0.field0, ..., variant0.fieldN, variant1.field0, ..., variant1.fieldM, ...]
+            // So the number of fields are always the same, and we have to consume all of them;
+            // the tag tells us which ones are non-default values.
+
+            let mut all_variants: Vec<Vec<PrintableValue<F>>> =
+                vecmap(variants, |(_, variant_types)| {
+                    vecmap(variant_types, |typ| decode_printable_value(field_iterator, typ))
+                });
+
+            PrintableValue::Enum { tag, elements: all_variants.swap_remove(tag) }
```
Comment (asterite) [inline compiler/noirc_printable_type/src/lib.rs]: Do we need to build all variants to get the one at `tag`?

File: compiler/noirc_printable_type/src/lib.rs (hunk 1 above)
Comment (aakoshh) [reply compiler/noirc_printable_type/src/lib.rs]: I agree, that would be nice. The obvious pattern would be something like:
```
match typ {
  NoircPrintableType::Array => match value {
    NoircPrintableValue::Array => ...,
    _ => return None,
  }
  NoircPrintableType::Enum => match value {
     NoircPrintableValue::Enum => ...,
     _ => return None
  }
}
```
First I thought it would be too noisy, but I'll give it a go and try to keep it non-distracting.

File: compiler/noirc_printable_type/src/lib.rs (hunk 2 above)
Comment (aakoshh) [reply compiler/noirc_printable_type/src/lib.rs]: Yes, I'll add a comment to emphasise this: the `field_iterator` is an `Iterator` and the main thing that drives parsing doesn't know how many fields the next item is going to be, it just passes it to the parser indicated by the type. If we consume less fields, then the next parser will resume parsing at the wrong spot.

Because the next variant is the only one that knows how to parse, we have to call it. 

I guess I could try to finesse to not have to _remember_ the variants that will be discarded, I just thought it would look more clunky.

Comment (asterite) [reply compiler/noirc_printable_type/src/lib.rs]: I see, I missed that! No need to change anything 👍

Comment (aakoshh) [reply compiler/noirc_printable_type/src/lib.rs]: Rewrote with a mutable option.

File: compiler/noirc_printable_type/src/lib.rs (hunk 1 above)
Comment (aakoshh) [reply compiler/noirc_printable_type/src/lib.rs]: Refactored to match on the type first. It's actually more readable this way 👍

File: compiler/noirc_printable_type/src/lib.rs [hunk 3]
```diff
@@ -138,13 +139,22 @@ impl<F: AcirField> std::fmt::Display for PrintableValueDisplay<F> {
     }
 }
 
+/// Format a given [PrintableValue] according to an expected [PrintableType].
+///
+/// Returns `None` if the value not what we expect based on the type.
```
Comment (aakoshh) [inline compiler/noirc_printable_type/src/lib.rs]:
```suggestion
/// Returns `None` if the value is not what we expect based on the type.
```

File: compiler/noirc_printable_type/src/lib.rs [hunk 4]
```diff
@@ -418,14 +470,25 @@ pub fn decode_printable_value<F: AcirField>(
...
+            // the tag tells us which ones are non-default values.
+
+            let mut elements = None;
+            for (i, (_, types)) in variants.iter().enumerate() {
+                // We have to consume all elements, so that the item that follows the enum can start at the right place in the iterator.
+                let variant_elements =
+                    vecmap(types, |typ| decode_printable_value(field_iterator, typ));
+                if i == tag {
+                    elements = Some(variant_elements);
+                }
```
Comment (asterite) [inline compiler/noirc_printable_type/src/lib.rs]: Nice! I guess one last thing we could do is to only create the vector if `i == tag`. Otherwise we can read from the iterator without building anything. Like in the rest of the comments, this is totally optional.

Comment (aakoshh) [reply compiler/noirc_printable_type/src/lib.rs]: Done, found a nicer way than the option as well 👍

**Comment by aakoshh** [comment]
It took me a while to realise that the `noir_wasm` failures are not temporary: https://github.com/noir-lang/noir/actions/runs/19297373404/job/55184101587?pr=10472

They fail because this test requires the `enums` unstable feature, which is given in `Nargo.toml` as `compiler_unstable_features = ["enums"]`, however this field is ignored in Wasm [here](https://github.com/noir-lang/noir/blob/794b685f77ec3b4c1c885c4131ee7792e949511d/compiler/wasm/src/types/noir_package_config.ts#L19). 

I thought about adding it, but the `Package` type never makes it into the Wasm [compile_program](https://github.com/noir-lang/noir/blob/794b685f77ec3b4c1c885c4131ee7792e949511d/compiler/wasm/src/compile.rs#L164-L170). 

Even if we passed that package somehow, we aren't [passing](https://github.com/noir-lang/noir/blob/794b685f77ec3b4c1c885c4131ee7792e949511d/compiler/wasm/src/noir/noir-wasm-compiler.ts#L97-L114) packages of the dependencies. The dependency setup in Wasm works by building up an in-memory source map and dependency map. Packages would at that point be redundant. 

Perhaps it's okay if Wasm doesn't have access to unstable features for now.
