### PR TITLE
fix: disable underflow fix for fields

### LINKED ISSUE #8519: ACIR != Brillig: u128 as Field negated as u128
### Aim

Discovered by running `cargo test -p noir_ast_fuzzer_fuzz acir_vs_brillig`.

The following program returns different results when executed with `--force-brillig`:

```rust
fn main(a: u128) -> pub u128 {
    let c = (-(a as Field));
    c as u128
}
```

`Prover.toml`:
```
a = "0x000000000000000000000000000000000000000000000000131640459367fd34"
```

### Expected Behavior

ACIR and Brillig should agree.

### Bug

```console
$ cargo run -q -p nargo_cli -- execute --force --silence-warnings ; cargo run -q -p nargo_cli -- execute --force --silence-warnings --force-brillig
[regression_fuzz_testing] Circuit witness successfully solved
[regression_fuzz_testing] Witness saved to target/regression_fuzz_testing.gz
[regression_fuzz_testing] Circuit output: Field(340282366920938463461999250027989959372)
[regression_fuzz_testing] Circuit witness successfully solved
[regression_fuzz_testing] Witness saved to target/regression_fuzz_testing.gz
[regression_fuzz_testing] Circuit output: Field(53438638232309528388129535304893203149)
```

### To Reproduce

See above.

### Workaround

None

### Workaround Description

_No response_

### Additional Context

_No response_

### Project Impact

None

### Blocker Context

_No response_

### Nargo Version

nargo version = 1.0.0-beta.6 noirc version = 1.0.0-beta.6+e796dfd67726cbc28eb9991782533b211025928d (git version hash: bb532cc1c0e314c13a7f8a79610d3592d7ba3d4d, is dirty: true)

### NoirJS Version

_No response_

### Proving Backend Tooling & Version

_No response_

### Would you like to submit a PR for this Issue?

None

### Support Needs

_No response_

### PR DESCRIPTION
**Pull request by guipublic**
# Description

## Problem\*

Resolves #8519

## Summary\*
Do not  add the 'bit size' modulo to avoid undeflow for field elements.
Furthermore, I changed it to use the 'max_bit_size' instead of the bit_size, because the input is supposed to have 'max_bit_size'.

## Documentation\*

Check one:
- [X] No documentation needed.
- [X] Documentation included in this PR.
- [ ] **[For Experimental Features]** Documentation to be submitted in a separate PR.

# PR Checklist\*

- [X] I have tested the changes locally.
- [X] I have formatted the changes with [Prettier](https://prettier.io/) and/or `cargo fmt` on default settings.

### CODE REVIEW

File: compiler/noirc_evaluator/src/acir/mod.rs [hunk 1]
```diff
@@ -1165,10 +1165,14 @@ impl<'a> Context<'a> {
                 ) {
                     // Subtractions must first have the integer modulus added before truncation can be
                     // applied. This is done in order to prevent underflow.
-                    let integer_modulus = power_of_two::<FieldElement>(bit_size);
-                    let integer_modulus = self.acir_context.add_constant(integer_modulus);
-                    var = self.acir_context.add_var(var, integer_modulus)?;
-                    max_bit_size += 1;
+                    // There is no underflow for field elements. Besides,
```
Comment (vezenovm) [inline compiler/noirc_evaluator/src/acir/mod.rs:1168]: Could we just expand this comment slightly? Something about how we expect the `max_bit_size` for a cast from a field to be `max_num_bits` and that is how we are gating this integer modulus addition?

Comment (guipublic) [reply compiler/noirc_evaluator/src/acir/mod.rs]: I updated the comment

**Review by vezenovm — APPROVED** [review]
