### PR TITLE
fix: error on returning unit type in empty array

### LINKED ISSUE #10814: Panic when compiling a program where `main` returns an empty array of unit values
### Aim

I attempted to compile the following program:

```noir
fn main() -> pub [(); 0] {
    [(); 0]
}
```

### Expected Behavior

I expected an error similar to when compiling the following:

```noir
fn main() -> pub (bool, ()) {
    (true, ())
}
```

```
❯ ~/.nargo/bin/nargo compile
error: Invalid type found in the entry point to a program
  ┌─ src/main.nr:1:4
  │
1 │ fn main() -> pub (bool, ()) {
  │    ---- Unit is not a valid entry point type
  │
  = Note: slices, references, empty arrays, empty strings, or any type containing them may not be used in main, contract functions, test functions, fuzz functions or foldable functions.
```

### Bug

```
❯ ~/.nargo/bin/nargo compile
The application panicked (crashed).
Message:  internal error: entered unreachable code: () cannot be used in the abi
Location: compiler/noirc_driver/src/abi_gen.rs:139
```

### To Reproduce

1.
2.
3.
4.

### Workaround

None

### Workaround Description

_No response_

### Additional Context

_No response_

### Project Impact

None

### Blocker Context

_No response_

### Nargo Version

nargo version = 1.0.0-beta.16 noirc version = 1.0.0-beta.16+7615632df856497750d6c0f856643a93df7dc40f (git version hash: 7615632df856497750d6c0f856643a93df7dc40f, is dirty: false)

### NoirJS Version

_No response_

### Proving Backend Tooling & Version

_No response_

### Would you like to submit a PR for this Issue?

None

### Support Needs

_No response_

### PR DESCRIPTION
**Pull request by guipublic**
# Description

## Problem

Resolves #10814 

## User Documentation

Check one:
- [X] No user documentation needed.
- [ ] Changes in _docs/_ included in this PR.
- [ ] **[For Experimental Features]** Changes in _docs/_ to be submitted in a separate PR.

# PR Checklist

- [X] I have tested the changes locally.
- [X] I have formatted the changes with [Prettier](https://prettier.io/) and/or `cargo fmt` on default settings.

### CODE REVIEW

File: compiler/noirc_frontend/src/elaborator/function.rs [hunk 1]
```diff
@@ -410,9 +410,20 @@ impl Elaborator<'_> {
     ) {
         match typ {
             Type::Unit => return,
-            Type::Array(length, _) | Type::String(length) => {
+            Type::Array(_, element_type) => {
+                if let Some(InvalidType::EmptyArray(_)) = typ.program_input_validity() {
```
Comment (aakoshh) [inline compiler/noirc_frontend/src/elaborator/function.rs]:
```suggestion
            Type::Array(length, element_type) => {
                if length_is_zero(length) {
```

I think it is easier to see that this is the same as it was before, except now we demand that the element type is valid. 

For example if we use `typ.program_input_validity()`, then it could be complaining about an empty _nested_ array, whereas previously we only checked the top level one. I'm not sure if we wanted to allow nested empty arrays or not 🤷

File: compiler/noirc_frontend/src/elaborator/function.rs [hunk 2]
```diff
@@ -410,9 +410,20 @@ impl Elaborator<'_> {
...
+                        element_type,
+                        is_entry_point,
+                        has_inline_attribute,
+                        location,
+                    );
+                    return;
+                }
+            }
+            Type::String(length) => {
                 if length_is_zero(length) {
```
Comment (aakoshh) [inline compiler/noirc_frontend/src/elaborator/function.rs]: I notice that `length_is_zero` looks like this:
```
length.evaluate_to_u32(Location::dummy()).unwrap_or(0) == 0
```

It is perhaps worth pointing that that if we cannot evaluate the value to a `u32`, then:
* `program_input_validity` returns an error, and thus `check_if_type_is_valid_for_program_input` registers an error as well, but
* `check_if_type_is_valid_for_program_output` accepts the value

I'm not sure what value I could use in Noir to make this pass, the 2nd handling doesn't sound correct.

File: compiler/noirc_frontend/src/elaborator/function.rs (hunk 1 above)
Comment (guipublic) [reply compiler/noirc_frontend/src/elaborator/function.rs]: I agree with you, but I think that checking for `InvalidType::EmptyArray(_)` is better than doing `length_is_zero(length)`. As you mentioned, it now works for nested arrays as well.

File: compiler/noirc_frontend/src/elaborator/function.rs (hunk 2 above)
Comment (guipublic) [reply compiler/noirc_frontend/src/elaborator/function.rs]: I can check against `InvalidType::EmptyString(_)` instead of using `length_is_zero`

Comment (aakoshh) [reply compiler/noirc_frontend/src/elaborator/function.rs]: It wouldn't matter, the `program_input_validity` uses `length_is_zero` to decide if something is an `EmptyString`. 

What I was trying to point out that a string can be empty because we know its length is `0`, or because we can't even tell what number the length is. It's okay to reject based on this, but when we use it as a criteria to _allow_ a type, then we allow the things we couldn't evaluate.

Not that I can produce an example where this is wrong, it was probably just defensive coding.

File: compiler/noirc_frontend/src/elaborator/function.rs (hunk 1 above)
Comment (aakoshh) [reply compiler/noirc_frontend/src/elaborator/function.rs]: I added some tests. They demonstrate that returning `pub [[u32; 0]; 0]` is not OK, but returning `pub [u32; 0]` is fine, so a nested empty array is rejected, but a top level empty array is accepted. 

Perhaps we could add some comments about _why_ we allow the return of empty arrays _only_ in the top level position. Previously we allowed an empty array of _anything_ to be returned: what does it matter, it cannot contain anything anyway. Now it has to contain 0 number of _valid_ types 🧑‍⚖️ 

For whoever asked for `[_; 0]` to be an acceptable return type, this could be a breaking change 🤷

Comment (guipublic) [reply compiler/noirc_frontend/src/elaborator/function.rs]: Thank you, I have refactored the validation to allow nested empty arrays.
I think the new process is clearer now, there is a special case for empty arrays and empty string, the rest is the same as input validation.

File: compiler/noirc_frontend/src/elaborator/function.rs (hunk 2 above)
Comment (guipublic) [reply compiler/noirc_frontend/src/elaborator/function.rs]: I don't know why `length_is_zero()` is like this. I changed it so that it returns false when the length is not known, as it look safer to me.

File: compiler/noirc_frontend/src/elaborator/function.rs [hunk 3]
```diff
@@ -407,24 +412,40 @@ impl Elaborator<'_> {
...
+                    Err(TypeCheckError::InvalidTypeForEntryPoint {
+                        invalid_type: InvalidType::EmptyArray(_),
+                        ..
+                    }) => self.check_if_type_is_valid_for_program_output(
+                        element_type,
+                        is_entry_point,
+                        has_inline_attribute,
+                        location,
+                    ),
+                    Err(err) => Err(err),
```
Comment (aakoshh) [inline compiler/noirc_frontend/src/elaborator/function.rs]: I'm not sure if this does what we wanted. IIUC the current idea is to allow empty arrays anywhere in the return type. The way the check is done, this only works for arrays immediately nested into each other, but not further down: 
* We have an array `[item; _]`, so we check if `item` is a valid _input_ by calling `check_if_type_is_valid_for_program_input(item)`:
  * if it contains an empty array, we check if it's a valid _output_ by recursively calling `check_if_type_is_valid_for_program_output(item)`:
    * if the `item` is _not_ an array, then we just call `check_if_type_is_valid_for_program_input(item)` again, and the answer is the same
    * if the `item` is an array, we peel off the outer array with the potential 0 length and check the nested item

Comment (aakoshh) [reply compiler/noirc_frontend/src/elaborator/function.rs]: It is supremely annoying 😄 
I think we might have an easier time passing a parameter to `program_input_validity` to tell if empty stuff is accepted or not.

File: compiler/noirc_frontend/src/elaborator/function.rs (hunk 2 above)
Comment (aakoshh) [reply compiler/noirc_frontend/src/elaborator/function.rs]: But now, `length_is_zero` returns `false` when it cannot evaluate the type to a `u32`, and when that happens, `program_input_validity` can return `None` for a string whose length it cannot tell, and then `check_if_type_is_valid_for_program_input` doesn't log any error.

Comment (aakoshh) [reply compiler/noirc_frontend/src/elaborator/function.rs]: Added a test to show an example where we now accept an input string with nonsensical length.

File: compiler/noirc_frontend/src/elaborator/function.rs (hunk 3 above)
Comment (guipublic) [reply compiler/noirc_frontend/src/elaborator/function.rs]: Thank you for keeping on checking my ramblings..

So I added the parameter to allow empty arrays or not, and I think (and hope) it is starting to look OK now..

File: compiler/noirc_frontend/src/elaborator/function.rs (hunk 2 above)
Comment (guipublic) [reply compiler/noirc_frontend/src/elaborator/function.rs]: ah yes, so it depends on whether we allow or not empty strings: when we allow, we want the more strict check, and when we disallow, we want the relaxed check...
It is indeed easier to use the parameter as you suggest in the other discussion.

Comment (aakoshh) [reply compiler/noirc_frontend/src/elaborator/function.rs]: I added one more test that shows that it still may be improved. 

* The latest logic with `length_may_be_zero()` returns `true` if the length is 0 or not a `u32`, and we use it like ` if !allow_empty_arrays && length_may_be_zero(length) { Err(...) } else { ... }`. 
* For `input` we set `allow_empty_arrays` to `false`, so a non-u32 is rejected ✅ 
* For `output` we set `allow_empty_arrays` to `true`, which means a non-u32 is ignored ❌ 

I believe `length_may_be_zero` should return something like `Option<bool>` where: 
* `Some(true)` means it was 0 -> we should accept this based on `allow_empty_arrays`
* `Some(false)` means it was a non-zero `u32` -> we should always accept this
* `None` means it wasn't a `u32` -> we should always reject this

Comment (guipublic) [reply compiler/noirc_frontend/src/elaborator/function.rs]: I am not sure this case (non u32) should be resolved here as an error.
The example you added is properly failing with a correct error:
`error: Could not determine array length `-1`, encountered error: `The value `-1` cannot fit into `numeric u32` which has a minimum size of `0```

Comment (guipublic) [reply compiler/noirc_frontend/src/elaborator/function.rs]: I added a specific check for negative lengths

**Review by aakoshh — APPROVED** [review]
🎉
