### PR TITLE
fix: treat nested comptime blocks as regular blocks

### LINKED ISSUE #10397: Nested comptime block fails to capture outer comptime block variables
### Aim

Run the following frontend unit test:
```rust
#[test]
fn nested_comptime_accesses_outer_comptime_variable() {
    let src = r#"
        fn main() {
            comptime {
                let x = 5;
                comptime {
                    let y = x + 1;
                    assert_eq(y, 6);
                }
            }
        }
    "#;
    assert_no_errors(src);
}
```

Or this variation:
<details><summary>Details</summary>
<p>

```rust
#[test]
fn nested_comptime_accesses_outer_comptime_func_variable() {
    let src = r#"
    comptime fn main() {
        let x = 0;
        comptime {
            let y = x + 1;
            assert_eq(y, 6);
        }
    }
    "#;
    assert_no_errors(src);
}
```

</p>
</details> 

The example is a bit contrived and there really is no purpose for nested comptime blocks like in the test above. So perhaps the best solution would be to simply ban nested comptime blocks. However, this does limit the user and this is something that should be possible to write. For example, what if a user has a function with inline comptime blocks mixed with runtime code. That user then decides that in some instances calls to that function can occur at runtime but then in other instances can occur at comptime. I would be curious how much code is out in the wild that has nested comptime blocks. If the solution is simple, I would rather maintain support for nested comptime blocks. We could then have a separate enhancement similar to Zig where we detect redundant comptime blocks and provide an error for the user. 

We can also test for mutable comptime variables in nested comptime blocks:
<details><summary>Details</summary>
<p>

```rust
#[test]
fn nested_comptime_with_mut_variable() {
    let src = r#"
        fn main() {
            comptime {
                let mut x = 0;
                comptime {
                    x = 5;
                }
                assert_eq(x, 5);
            }
        }
    "#;
    assert_no_errors(src);
}
```

```rust
#[test]
fn comptime_func_with_mut_in_nested_comptime() {
    let src = r#"
    comptime fn main() {
        let mut x = 0;
        comptime {
            x = 5;
        }
        assert_eq(x, 5);
    }
    "#;
    assert_no_errors(src);
}
```
</p>
</details> 

These examples of calling functions containing comptime blocks in comptime blocks will also fail similarly:
<details><summary>Details</summary>
<p>

```rust
#[test]
fn comptime_function_with_comptime_block_called_from_comptime() {
    let src = r#"
        comptime fn helper(x: Field) -> Field {
            comptime {
                assert_eq(x, 5);
            }
        }

        fn main() {
            comptime {
                let x = 5;
                let result = helper(x);
                assert_eq(result, 6);
            }
        }
    "#;
    assert_no_errors(src);
}

#[test]
fn runtime_function_with_comptime_block_called_from_comptime() {
    let src = r#"
        fn helper(x: Field) -> Field {
            comptime {
                assert_eq(x, 5);
            }
        }

        fn main() {
            comptime {
                let x = 5;
                let result = helper(x);
                assert_eq(result, 6);
            }
        }
    "#;
    assert_no_errors(src);
}

```

</p>
</details> 

### Expected Behavior

I would expect the above program to succeed. `x` is a comptime variable declared in an outer block so I would it expect it to be in scope for the nested comptime block. 

### Bug

We will get the following error output:
```
error: Non-comptime variable `x` referenced in comptime code
  ┌─ /test_file:6:29
  │
6 │                     let y = x + 1;
  │                             - Non-comptime variables can't be used in comptime code
  │

error: Internal Compiler Error: Error node encountered
  ┌─ /test_file:5:17
  │  
5 │ ╭                 comptime {
6 │ │                     let y = x + 1;
7 │ │                     assert_eq(y, 6);
8 │ │                 }
  │ ╰─────────────────' This is a bug, please report this if found!
  │  
```
We look to be mixing our runtime and comptime contexts when it comes to nested comptime blocks. 

For more context, the following test passes:
```rust
#[test]
fn comptime_let_used_in_separate_comptime_block() {
    let src = r#"
        fn main() {
            comptime let x = 5;
            comptime {
                let y = x + 1;
                assert_eq(y, 6);
            }
        }
    "#;
    assert_no_errors(src);
}
```

The mutable variable tests fail with a different error but it is most likely the same root cause:
```
error: Variable not in scope
  ┌─ /test_file:5:13
  │
5 │             x = 5;
  │             - Could not find variable
  │
```

For context, this test passes:
```rust
#[test]
fn comptime_let_mut_in_separate_comptime_block() {
    let src = r#"
        fn main() {
            comptime let mut x = 0;
            comptime {
                x = 5;
            }
            assert_eq(x, 5);
        }
    "#;
    assert_no_errors(src);
}
```

### To Reproduce

1. Run the tests above in the `noirc_frontend/src/tests` suite 

### Workaround

Yes

### Workaround Description

Do not use nested comptime blocks

### Additional Context

_No response_

### Project Impact

Nice-to-have

### Blocker Context

_No response_

### Nargo Version

nargo version = 1.0.0-beta.14 noirc version = 1.0.0-beta.14+35a913f5261c84b9bbaa404b2f29e398a9daee99 (git version hash: e64f3ccc26dd7bb4a331739e5b9c5c025fa19585, is dirty: true)

### NoirJS Version

_No response_

### Proving Backend Tooling & Version

_No response_

### Would you like to submit a PR for this Issue?

None

### Support Needs

_No response_

### PR DESCRIPTION
**Pull request by asterite**
# Description

## Problem

Resolves #10397

## User Documentation

Check one:
- [x] No user documentation needed.
- [ ] Changes in _docs/_ included in this PR.
- [ ] **[For Experimental Features]** Changes in _docs/_ to be submitted in a separate PR.

# PR Checklist

- [x] I have tested the changes locally.
- [x] I have formatted the changes with [Prettier](https://prettier.io/) and/or `cargo fmt` on default settings.

### CODE REVIEW

File: compiler/noirc_frontend/src/elaborator/statements.rs [hunk 1]
```diff
@@ -45,7 +45,14 @@ impl Elaborator<'_> {
             StatementKind::Break => self.elaborate_jump(true, statement.location),
             StatementKind::Continue => self.elaborate_jump(false, statement.location),
             StatementKind::Comptime(statement) => {
-                self.elaborate_comptime_statement(*statement, target_type)
+                if self.in_comptime_context() {
+                    // Treat a nested comptime block as a regular block. Nesteed comptime blocks
```
Comment (vezenovm) [inline compiler/noirc_frontend/src/elaborator/statements.rs]:
```suggestion
                    // Treat a nested comptime block as a regular block. Nested comptime blocks
```

File: compiler/noirc_frontend/src/elaborator/expressions.rs [hunk 2]
```diff
@@ -102,8 +102,15 @@ impl Elaborator<'_> {
                 return self.elaborate_expression_with_target_type(*expr, target_type);
             }
             ExpressionKind::Quote(quote) => self.elaborate_quote(quote, expr.location),
-            ExpressionKind::Comptime(comptime, _) => {
-                return self.elaborate_comptime_block(comptime, expr.location, target_type);
+            ExpressionKind::Comptime(block, _) => {
+                if self.in_comptime_context {
+                    // Treat a nested comptime block as a regular block. Nesteed comptime blocks
```
Comment (vezenovm) [inline compiler/noirc_frontend/src/elaborator/expressions.rs]:
```suggestion
                    // Treat a nested comptime block as a regular block. Nested comptime blocks
```
