### PR TITLE
fix: several comptime interpreter fixes

### LINKED ISSUE #10614: as_witness is not implemented in comptime
### Aim

This code:

```noir
fn main() {
    comptime {
        let _ = std::as_witness(1);
    }
}
```

gives this error:

```
error: Comptime evaluation for builtin function 'as_witness' is currently unimplemented
  ┌─ src/main.nr:3:17
  │
3 │         let _ = std::as_witness(1);
  │                 ------------------
```

However, it should compile: `as_witness` should simply return the input argument in comptime code.

Used in these test programs: as_witness, regression_10156, regression_6451, poseidon_bn254_hash_width_3, poseidonsponge_x5_254, regression_5252

### Expected Behavior

The code should compile.

### Bug

It doesn't compile.

### To Reproduce

1.
2.
3.
4.

### Workaround

None

### Workaround Description

_No response_

### Additional Context

_No response_

### Project Impact

None

### Blocker Context

_No response_

### Nargo Version

_No response_

### NoirJS Version

_No response_

### Proving Backend Tooling & Version

_No response_

### Would you like to submit a PR for this Issue?

None

### Support Needs

_No response_

### LINKED ISSUE #10615: multi_scalar_mul_array_return doesn't work in comptime
### Aim

This code:

```noir
fn main() {
    comptime {
        let _ = std::hash::pedersen_hash([1, 2, 3]);
    }
}
```

gives this error:

```
error: Expected `bool` but a value of type `Field` was given
   ┌─ std/hash/mod.nr:95:35
   │
95 │     multi_scalar_mul_array_return(generators, scalars, true)[0].x
   │                                   ----------
```

It seems there's something wrong in the interpreter related to this foreign call.
 
Used in these test programs: brillig_cow_regression, brillig_pedersen, import, merkle_insert, pedersen_check, pedersen_commitment, pedersen_hash, simple_shield, strings

### Expected Behavior

The code should compile.

### Bug

It doesn't compile.

### To Reproduce

1.
2.
3.
4.

### Workaround

None

### Workaround Description

_No response_

### Additional Context

_No response_

### Project Impact

None

### Blocker Context

_No response_

### Nargo Version

_No response_

### NoirJS Version

_No response_

### Proving Backend Tooling & Version

_No response_

### Would you like to submit a PR for this Issue?

None

### Support Needs

_No response_

### LINKED ISSUE #10616: Struct pattern matching defines non-comptime variables in comptime code
### Aim

This code:

```noir
struct Foo {
    x: Field,
}

fn main() {
    comptime {
        let Foo { x } = Foo { x: 1 };
        println(x);
    }
}
```

gives this error:

```
error: Non-comptime variable `x` referenced in comptime code
  ┌─ src/main.nr:8:17
  │
8 │         println(x);
  │                 - Non-comptime variables can't be used in comptime code
```

It seems the variable ends up being a non-comptime variable.

Used in these test programs: generics, poseidon_bn254_hash_width_3, poseidonsponge_x5_254, regression_5252, struct

### Expected Behavior

The code should compile.

### Bug

It doesn't compile.

### To Reproduce

1.
2.
3.
4.

### Workaround

None

### Workaround Description

_No response_

### Additional Context

_No response_

### Project Impact

None

### Blocker Context

_No response_

### Nargo Version

_No response_

### NoirJS Version

_No response_

### Proving Backend Tooling & Version

_No response_

### Would you like to submit a PR for this Issue?

None

### Support Needs

_No response_

### LINKED ISSUE #10618: black_box is currently unimplemented in comptime
### Aim

This code:

```noir
fn main() {
    comptime {
        let _ = std::hint::black_box(1);
    }
}
```

gives this error:

```
error: Comptime evaluation for builtin function 'black_box' is currently unimplemented
  ┌─ src/main.nr:3:17
  │
3 │         let _ = std::hint::black_box(1);
  │                 -----------------------
```

However, it should work (black_box should return its input argument).

Used in these test programs: hint_black_box

### Expected Behavior

The code should compile.

### Bug

It doesn't compile.

### To Reproduce

1.
2.
3.
4.

### Workaround

None

### Workaround Description

_No response_

### Additional Context

_No response_

### Project Impact

None

### Blocker Context

_No response_

### Nargo Version

_No response_

### NoirJS Version

_No response_

### Proving Backend Tooling & Version

_No response_

### Would you like to submit a PR for this Issue?

None

### Support Needs

_No response_

### PR DESCRIPTION
**Pull request by asterite**
# Description

## Problem

Resolves #10615
Resolves #10618
Resolves #10614
Resolves #10616

## Summary

I grouped these fixes in a single PR because each was relatively trivial to fix.

## User Documentation

Check one:
- [x] No user documentation needed.
- [ ] Changes in _docs/_ included in this PR.
- [ ] **[For Experimental Features]** Changes in _docs/_ to be submitted in a separate PR.

# PR Checklist

- [x] I have tested the changes locally.
- [x] I have formatted the changes with [Prettier](https://prettier.io/) and/or `cargo fmt` on default settings.

### CODE REVIEW

File: compiler/noirc_frontend/src/hir/comptime/interpreter.rs [hunk 1]
```diff
@@ -497,44 +497,38 @@ impl<'local, 'interner> Interpreter<'local, 'interner> {
...
+                        let field_type = field.get_type().into_owned();
+                        let result = self.define_pattern(
+                            field_pattern,
+                            &field_type,
+                            field.clone(),
+                            location,
+                        );
+                        if result.is_err() {
+                            self.pop_scope();
+                            return result;
```
Comment (jfecher) [inline compiler/noirc_frontend/src/hir/comptime/interpreter.rs]:
```suggestion
                        self.define_pattern(
                            field_pattern,
                            &field_type,
                            field.clone(),
                            location,
                        )?;
```
(It won't let me select the ending `}` line so this suggestion is incomplete)

Looks like you removed the `push_scope` but not the `pop_scope`.

I'm not sure I remember why we had `push_scope` to begin with. I suppose with it the variables defined may not be visible at all (if the scope is popped afterward), leading to the "variable is not comptime" error. Either way, it seems this should be removed too.

**Review by jfecher — APPROVED** [review]

File: compiler/noirc_frontend/src/hir/comptime/interpreter.rs (hunk 1 above)
Comment (asterite) [reply compiler/noirc_frontend/src/hir/comptime/interpreter.rs]: Good catch! This pop was for the error case, there was another one a bit below.

I pushed a separate commit as it also produced a different formatting.
