### PR TITLE
fix: apply predicate to over/underflow checks

### LINKED ISSUE #3493: Over/underflow checks are performed in inactive conditional branches resulting in unwanted constraints
### Aim

Consider the program 

```rust
fn main(x: u4) {
    if x == 10 {
        x + 15;
    }
}
```

### Expected Behavior

We should expect that this program should execute correctly for `x != 10` but fail in the case of `x == 10` due to an overflow.

### Bug

The ACIR generated for this program is as below (annotated)

```
Compiled ACIR for main (unoptimized):
current witness index : 5
public parameters indices : []
return value indices : []
BLACKBOX::RANGE [(_1, num_bits: 4)] [ ]

// Processing `if` condition.
EXPR [ (-1, _1) (-1, _2) 10 ]
BRILLIG: inputs: [Single(Expression { mul_terms: [], linear_combinations: [(1, Witness(2))], q_c: 0 })]
outputs: [Simple(Witness(3))]
[JumpIfNot { condition: RegisterIndex(0), location: 3 }, Const { destination: RegisterIndex(1), value: Value { inner: 1 } }, BinaryFieldOp { destination: RegisterIndex(0), op: Div, lhs: RegisterIndex(1), rhs: RegisterIndex(0) }, Stop]
EXPR [ (1, _2, _3) (1, _4) -1 ]
EXPR [ (1, _2, _4) 0 ]

// Addition inside the if statement.
EXPR [ (1, _1) (-1, _5) 15 ]
BLACKBOX::RANGE [(_5, num_bits: 4)] [ ]
```

We can see that we're not actually applying the condition to the addition which results in the range check failing due to an overflow in all cases.

The simplest solution to this is to just multiply the value being range checked by the condition which will turn off any under/overflow checks. The value which is being written to witness 5 will still be an invalid `u32` but we won't use this outside of the conditional branch so this isn't important. This then gives the ACIR:

```
Compiled ACIR for main (unoptimized):
current witness index : 6
public parameters indices : []
return value indices : []
BLACKBOX::RANGE [(_1, num_bits: 4)] [ ]
EXPR [ (-1, _1) (-1, _2) 10 ]
BRILLIG: inputs: [Single(Expression { mul_terms: [], linear_combinations: [(1, Witness(2))], q_c: 0 })]
outputs: [Simple(Witness(3))]
[JumpIfNot { condition: RegisterIndex(0), location: 3 }, Const { destination: RegisterIndex(1), value: Value { inner: 1 } }, BinaryFieldOp { destination: RegisterIndex(0), op: Div, lhs: RegisterIndex(1), rhs: RegisterIndex(0) }, Stop]

EXPR [ (1, _2, _3) (1, _4) -1 ]
EXPR [ (1, _2, _4) 0 ]
EXPR [ (1, _1) (-1, _5) 15 ]
EXPR [ (1, _4, _5) (-1, _6) 0 ] // Application of condition
BLACKBOX::RANGE [(_6, num_bits: 4)] [ ]
```

We could potentially be a bit smarter about this in order to avoid unnecessary constraints but this is fine for the time being.

### To Reproduce

`nargo execute` supplied program on master.

### Installation Method

None

### Nargo Version

_No response_

### Additional Context

_No response_

### Would you like to submit a PR for this Issue?

No

### Support Needs

_No response_

### PR DESCRIPTION
**Pull request by TomAFrench**
# Description

## Problem\*

Resolves #3493 

## Summary\*

This PR applies a predicate to `Instruction::RangeCheck` appropriately to disable it on inactive codepaths similarly to how it is done for explicit assertions.

## Additional Context

Fixes issue introduced in https://github.com/noir-lang/noir/pull/2713

## Documentation\*

Check one:
- [x] No documentation needed.
- [ ] Documentation included in this PR.
- [ ] **[Exceptional Case]** Documentation to be submitted in a separate PR.

# PR Checklist\*

- [x] I have tested the changes locally.
- [x] I have formatted the changes with [Prettier](https://prettier.io/) and/or `cargo fmt` on default settings.

### CODE REVIEW

File: compiler/noirc_evaluator/src/ssa/opt/flatten_cfg.rs [hunk 1]
```diff
@@ -662,6 +662,22 @@ impl<'f> Context<'f> {
                     self.remember_store(address, value);
                     Instruction::Store { address, value }
                 }
+                Instruction::RangeCheck { value, max_bit_size, assert_message } => {
```
Comment (vezenovm) [inline compiler/noirc_evaluator/src/ssa/opt/flatten_cfg.rs:665]: Is there a performance difference if we simply multiplied by `current_side_effects_enabled_var` in acir gen when converting an `Instruction::RangeCheck` rather than inserting a mul instruction here which requires us to also add a cast?

Comment (guipublic) [reply compiler/noirc_evaluator/src/ssa/opt/flatten_cfg.rs:665]: the cast should not impact acir opcodes since we cast from a value of 1 bit

**Review by guipublic — APPROVED** [review]

File: compiler/noirc_evaluator/src/ssa/opt/flatten_cfg.rs (hunk 1 above)
Comment (TomAFrench) [reply compiler/noirc_evaluator/src/ssa/opt/flatten_cfg.rs:665]: Yep, the cast doesn't affect the outputted ACIR as we're expanding the bit size.
