### PR TITLE
fix(nargo): `nargo test` now only runs test functions defined in the current module

### LINKED ISSUE #759: `nargo test` runs test functions defined in dependencies
# Description

## Aim

I wanted to run tests which I have written for my noir crate.

## Expected behavior

`nargo test` should compile and run all the test functions which I have defined locally. It should not run test cases from any crates in my dependency tree (as I assume that these are correct).

## Bug

As all functions are exposed from the library crate I'm importing, nargo sees these test functions and runs them as part of my test suite as if I wrote them myself.

# To reproduce

1. clone https://github.com/TomAFrench/keccak256-noir
2. cd into `circuits`
3. read `main.nr` to see no test functions
4. run `nargo test` and see output from tests in `lib` directory.

# Environment

- [x] Using `nargo`:

  - [ ] Binary: 
  - [x] Compiled from source: beedae66
  
- [ ] Using TypeScript:

  - @noir-lang/noir_wasm: 
  - @noir-lang/barretenberg: 
  - @noir-lang/aztec_backend: 

# Additional context

### PR DESCRIPTION
**Pull request by jfecher**
# Related issue(s)

Resolves #759

# Description

## Summary of changes

Fixes the filtering of test functions to only use functions defined in the current module.

# Checklist

- [x] I have tested the changes locally.
- [x] I have formatted the changes with [Prettier](https://prettier.io/) and/or `cargo fmt` with default settings.
- [x] I have [linked](https://docs.github.com/en/issues/tracking-your-work-with-issues/linking-a-pull-request-to-an-issue) this PR to the issue(s) that it resolves.
- [x] I have reviewed the changes on GitHub, line by line.
- [x] I have ensured all changes are covered in the description.
- [x] This PR requires documentation updates when merged.

# Additional context

### CODE REVIEW

File: crates/noirc_driver/src/lib.rs [hunk 1]
```diff
@@ -225,7 +225,7 @@ impl Driver {
         let interner = &self.context.def_interner;
         self.context
             .def_map(LOCAL_CRATE)
-            .unwrap()
+            .expect("The local crate should be analyzed already")
```
Comment (kevaundray) [inline crates/noirc_driver/src/lib.rs:228]: Nice

**Review by kevaundray — APPROVED** [review]
Looks good -- Also ran it on Toms Keccak example and it runs no tests in the `circuits` dir and 9 tests in the `lib` dir as expected

**Review by kevaundray — APPROVED** [review]
