### PR TITLE
fix: Reject invalid expression with in CLI parser

### LINKED ISSUE #5560: Nargo panics if you specify an expression-width < 3 during compile
### Aim

When compiling a noir program and specifying the expression-width (amount of witnesses in an expression), the compiler expects a width > 2. This is most likely the correct behaviour, but nargo panics with the following message:
```
The application panicked (crashed).
Message:  assertion failed: width > 2
Location: acvm-repo/acvm/src/compiler/transformers/csat.rs:27

This is a bug. We may have already fixed this in newer versions of Nargo so try searching for similar issues at https://github.com/noir-lang/noir/issues/.
If there isn't an open issue for this bug, consider opening one at https://github.com/noir-lang/noir/issues/new?labels=bug&template=bug_report.yml
```

### Expected Behavior

The program should terminate and tell me that nargo expects an expression-width > 2, instead of a panic and indicating that there is a bug.

### Bug

The problem is here:
```
 acvm-repo/acvm/src/compiler/transformers/csat.rs:27
```

Here the CSat Solver asserts that the expression-width is > 2. It should return an Result instead telling the user to provide an expression-width > 2

### To Reproduce

1. ```nargo new wrong_expr_width && cd wrong_expr_width```
2. ```nargo compile --expression-width 1```

### Project Impact

None

### Impact Context

_No response_

### Workaround

None

### Workaround Description

_No response_

### Additional Context

_No response_

### Installation Method

Binary (`noirup` default)

### Nargo Version

noirc version = 0.30.0+af57471035e4fa7eaffa71693219df6d029dbcde

### NoirJS Version

_No response_

### Would you like to submit a PR for this Issue?

Maybe

### Support Needs

_No response_

### PR DESCRIPTION
**Pull request by aakoshh**
# Description

## Problem\*

Resolves #5560

## Summary\*

Rejects an invalid `--expression-value` in the CLI, which would later cause a panic in `acvm::compiler::transformers::csat`. 

An example error message looks like:

```text
error: invalid value '1' for '--expression-width <EXPRESSION_WIDTH>': minimum value is 3
```

## Additional Context

The issue suggests that [CSatTransformer::new](https://github.com/noir-lang/noir/blob/ae87d287ab1fae0f999dfd0d1166fbddb927ba97/acvm-repo/acvm/src/compiler/transformers/csat.rs#L24-L27) should return a `Result` explaining the problem it has with `width`, rather than doing an `assert!` (without any message) and crashing the program. I agree, however looking at the chain of calls, none of the half-dozen functions we go through to reach this use `Result`, and the `CSatTransformer` is the only option we have. This suggests to me that this limitation is perhaps supposed to be well-known to the user, ie. it's not the case that one transformer has X limit and another has Y limit. 

For this reason I added a `pub const MIN_EXPRESSION_WIDTH: usize = 3;` to the `acvm::compiler` module and using that as a common value for the assertion as well as the validation in the CLI. Should the assumption of a single global value change, removing that will force us to update the validation logic as well. 

That said if you prefer going the `Result` route I'm not against it, it just seemed like an overkill for this single use case.
 
## Documentation\*

Check one:
- [x] No documentation needed.
- [ ] Documentation included in this PR.
- [ ] **[For Experimental Features]** Documentation to be submitted in a separate PR.

# PR Checklist\*

- [x] I have tested the changes locally.
- [ ] I have formatted the changes with [Prettier](https://prettier.io/) and/or `cargo fmt` on default settings.

### CODE REVIEW

File: tooling/nargo_cli/benches/criterion.rs [hunk 1]
```diff
@@ -23,6 +23,8 @@ fn compile_program(test_program_dir: &Path) {
     cmd.arg("--program-dir").arg(test_program_dir);
     cmd.arg("compile");
     cmd.arg("--force");
+    cmd.arg("--expression-width");
+    cmd.arg("1");
```
Comment (asterite) [inline tooling/nargo_cli/benches/criterion.rs:27]: What does this "1" mean here?

File: tooling/nargo_cli/src/cli/mod.rs [hunk 2]
```diff
@@ -112,3 +112,20 @@ pub(crate) fn start_cli() -> eyre::Result<()> {
     println!("{markdown}");
     Ok(())
 }
+
+#[cfg(test)]
+mod tests {
+    use clap::Parser;
+    /// Test that parsing an invalid option doesn't
```
Comment (asterite) [inline tooling/nargo_cli/src/cli/mod.rs:119]: Unfinished sentence :-)

We could either finish it or remove this comment, your choice.

File: tooling/nargo_cli/benches/criterion.rs (hunk 1 above)
Comment (TomAFrench) [reply tooling/nargo_cli/benches/criterion.rs:27]: I don't think this should be here right?

**Review by TomAFrench — COMMENTED** [review]
LGTM pending removal of changes which break benchmarks.

File: tooling/nargo_cli/benches/criterion.rs (hunk 1 above)
Comment (aakoshh) [reply tooling/nargo_cli/benches/criterion.rs:27]: Good cat, I think this is what I used to trigger the error and accidentally checked it in, thanks!

File: tooling/nargo_cli/src/cli/mod.rs (hunk 2 above)
Comment (aakoshh) [reply tooling/nargo_cli/src/cli/mod.rs]: Thanks, removed. I wanted to say "doesn't cause a panic" but then realised that it never did, froze mid sentence.

**Review by TomAFrench — APPROVED** [review]
