### PR TITLE
fix(cli): fail when interpret output or results change across SSA passes

### LINKED ISSUE #12124: Assert interpreter side effects are unchanged after SSA passes
### Problem

In https://github.com/noir-lang/noir/pull/12011 we had a failing test where the stdout changed https://github.com/noir-lang/noir/actions/runs/23961166350/job/69892846944?pr=12011:
```
0x00
0x03
0x04
0x06
0x06
0x07
8
0x06
0x06
0x04
--- Interpreter result after Removing Unreachable Functions (step 5):
Ok()
---
0x00
0x03
0x04
0x05
0x06
0x07
8
0x05
0x06
0x04
--- Interpreter result after Mem2Reg Simple (step 6):
Ok()
```
We can see that the fourth value has changed from `0x06` to `0x05` yet `nargo interpret` succeeded. 

### Happy Case

Check SSA stdout snapshots against the previous pass to make sure the pass did not alter the intended side effects of a program. Perhaps there is a more general way to do this but a quick initial solution can just be stdout snapshot checks like we do for our integration tests. 

### Workaround

None

### Workaround Description

_No response_

### Additional Context

_No response_

### Project Impact

None

### Blocker Context

_No response_

### Would you like to submit a PR for this Issue?

None

### Support Needs

_No response_

### PR DESCRIPTION
**Pull request by 0xwonj**
# Description

## Problem

Resolves #12124

`nargo interpret` currently runs the SSA interpreter after selected passes, but it does not compare interpreter observations between passes.

In practice:

- printed output can change between passes without being flagged
- if `Prover.toml` has no `return`, the interpreter result can also change between passes without being flagged

That means a pass can change observable interpreter behavior and `nargo interpret` can still appear to succeed.

## Summary

This change adds pass-to-pass checks in `nargo interpret`:

- capture the printed output for each checked pass
- compare printed output against the previous checked pass, including passes that return `Err`
- when `Prover.toml` has no `return`, also compare interpreter results against the previous checked pass
- report discrepancies as they occur, but continue through the selected passes instead of failing fast
- always advance the comparison baseline to the current checked pass

When `Prover.toml` does provide a `return`, that expected result remains the stronger oracle and is still checked directly.

## Additional Context

The original report came from a historical CI reproduction in #12011, specifically [this failing Actions job](https://github.com/noir-lang/noir/actions/runs/23961166350/job/69892846944?pr=12011). The exact pass-to-pass output drift no longer reproduces on current `master`, but `nargo interpret` should still detect this class of regression when it happens.

This PR keeps the implementation local to `nargo interpret`, which matches the quick initial direction in #12124 and the follow-up discussion on the issue.

## User Documentation
Check one:
- [x] No user documentation needed.
- [ ] Changes in _docs/_ included in this PR.
- [ ] **[For Experimental Features]** Changes in _docs/_ to be submitted in a separate PR.

# PR Checklist
- [x] I have tested the changes locally.
- [x] I have formatted the changes with [Prettier](https://prettier.io/) and/or `cargo fmt` on default settings.

### CODE REVIEW

File: tooling/nargo_cli/src/cli/interpret_cmd.rs [hunk 1]
```diff
@@ -321,10 +363,45 @@ fn interpret_ssa(
                 return Err(CliError::Generic(error));
             }
         }
-        Ok(is_ok)
+        Ok(Some(InterpretedPassOutput {
+            is_ok,
+            print_output: String::from_utf8(print_output).expect("from_utf8 of interpreter print"),
```
Comment (aakoshh) [inline tooling/nargo_cli/src/cli/interpret_cmd.rs:392]: It would be good to capture the actual result as well. If the `Prover.toml` file has no `return` value in it, then we can compare the results of the passes as well, similarly to how inputs are compared. If the result is an `Ok(value)` then it shouldn't change, although `Err` can be different.

File: tooling/nargo_cli/src/cli/interpret_cmd.rs [hunk 2]
```diff
@@ -321,10 +363,45 @@ fn interpret_ssa(
...
+
+    if let Some(previous_snapshot) = previous_interpreted_pass_snapshot {
+        if previous_snapshot.print_output != current_output.print_output {
+            let error = format!(
+                "Error: interpreter printed output changed between SSA passes.\nPrevious checked pass: {}\nCurrent checked pass: {msg}\nPrevious output:\n{}\nCurrent output:\n{}",
+                previous_snapshot.pass_name,
+                previous_snapshot.print_output,
+                current_output.print_output
+            );
+            return Err(CliError::Generic(error));
```
Comment (aakoshh) [inline tooling/nargo_cli/src/cli/interpret_cmd.rs]: Note that unless `Prover.toml` has a `return` value that we can compare the results against, we do currently execute all passes, displaying without judgement which one succeeded and which one failed, and only at the end do we fail the entire `nargo interpret` command if at least one of the results was an error. 

By contrast, here we exit as soon as there is a disagreement in printed output, which is a change in the behaviour of the command. 

Perhaps a `--fail-fast` option could be added to tell whether we want it to fail on the first error, or let it go all the way, showing any discrepancies as they occur, and only fail at the end if there was a disagreement along the way.

File: tooling/nargo_cli/src/cli/interpret_cmd.rs [hunk 3]
```diff
@@ -321,10 +363,45 @@ fn interpret_ssa(
...
+/// successful pass snapshot. Returns an error if the outputs differ, otherwise
+/// advances the snapshot to the current pass.
+fn check_and_advance_snapshot(
+    previous_interpreted_pass_snapshot: &mut Option<InterpretedPassSnapshot>,
+    msg: &str,
+    current_output: &InterpretedPassOutput,
+) -> Result<(), CliError> {
+    if !current_output.is_ok {
+        return Ok(());
+    }
```
Comment (aakoshh) [inline tooling/nargo_cli/src/cli/interpret_cmd.rs]: I don't think we should ignore the output if the interpretation result was an error: it just means that some constraint failed, but we still want the rest of the execution to have the same side effects. That's because they represent oracle calls which could be effectful, and we want those to be deterministic. The fuzzer works this way as well, comparing both positive or negative results along with the outputs.

File: tooling/nargo_cli/src/cli/interpret_cmd.rs [hunk 4]
```diff
@@ -371,3 +456,104 @@ fn flatten_databus_value(value: Value, flattened_values: &mut Vec<Value>) {
...
+        )
+        .unwrap();
+
+        let previous_interpreted_pass_snapshot =
+            previous_interpreted_pass_snapshot.expect("expected baseline to remain untouched");
+        assert_eq!(
+            previous_interpreted_pass_snapshot.pass_name,
+            "Removing Unreachable Functions (step 5)"
+        );
+        assert_eq!(previous_interpreted_pass_snapshot.print_output, "0x06");
```
Comment (aakoshh) [inline tooling/nargo_cli/src/cli/interpret_cmd.rs]: I reckon it would be okay to advance unconditionally, so that we only flag up the cases where subsequent passes disagree, but then keep silent when the result does not change (it makes it potentially easier to see where the behaviour changes).

File: tooling/nargo_cli/src/cli/interpret_cmd.rs (hunk 1 above)
Comment (0xwonj) [reply tooling/nargo_cli/src/cli/interpret_cmd.rs:392]: Updated this. `interpret_ssa` now records both the printed output and the interpreter result for each checked pass, and when `Prover.toml` has no `return` we compare pass results as well.

File: tooling/nargo_cli/src/cli/interpret_cmd.rs (hunk 2 above)
Comment (0xwonj) [reply tooling/nargo_cli/src/cli/interpret_cmd.rs]: You’re right that this had changed the existing behavior.

I updated it so disagreements no longer stop the command immediately: it now keeps going through the selected passes, reports discrepancies as they occur, and only fails the overall run at the end.

I left `--fail-fast` out of this PR.

File: tooling/nargo_cli/src/cli/interpret_cmd.rs (hunk 3 above)
Comment (0xwonj) [reply tooling/nargo_cli/src/cli/interpret_cmd.rs]: Updated this. Printed output is now still compared even when interpretation returns `Err`, so failing passes still participate in the side-effect check.

File: tooling/nargo_cli/src/cli/interpret_cmd.rs (hunk 4 above)
Comment (0xwonj) [reply tooling/nargo_cli/src/cli/interpret_cmd.rs]: I changed this to advance the baseline unconditionally.

File: tooling/nargo_cli/src/cli/interpret_cmd.rs [hunk 5]
```diff
@@ -179,13 +182,62 @@ pub(crate) fn run(args: InterpretCommand, workspace: Workspace) -> Result<(), Cl
...
+    print_output: String,
+    result: Option<Vec<Value>>,
+}
+
+impl PassSnapshot {
+    fn result_string(&self) -> String {
+        match &self.result {
+            Some(values) => {
+                let values = vecmap(values, ToString::to_string).join(", ");
+                format!("Ok({values})")
```
Comment (aakoshh) [inline tooling/nargo_cli/src/cli/interpret_cmd.rs:237]:
```suggestion
                format!("Ok([{values}])")
```
EDIT: nvm, I see it's been like this before, it's okay.

File: tooling/nargo_cli/src/cli/interpret_cmd.rs [hunk 6]
```diff
@@ -285,48 +337,113 @@ fn print_ssa(
...
+    compare_results: bool,
+) -> Option<String> {
+    let discrepancy = previous_snapshot.as_ref().and_then(|previous_snapshot| {
+        let output_changed = previous_snapshot.print_output != current_snapshot.print_output;
+        let result_changed = compare_results
+            && match (&previous_snapshot.result, &current_snapshot.result) {
+                (Some(previous_result), Some(current_result)) => previous_result != current_result,
+                (Some(_), None) | (None, Some(_)) => true,
+                (None, None) => false,
+            };
```
Comment (aakoshh) [inline tooling/nargo_cli/src/cli/interpret_cmd.rs]:
```suggestion
            && previous_snapshot.result != &current_snapshot.result;
```

**Comment by jfecher** [comment]
@aakoshh did you want to merge this?
