### PR TITLE
fix(hir): Do not ignore the name in `PartialEq` for `Type::NamedGeneric` for implicit unbound

### LINKED ISSUE #11347: Mixup of associated types across different traits not rejected
### Aim

Discovered testing https://github.com/noir-lang/noir/pull/11346

The following code should not compile:
```noir
pub trait Spam {
    type Item;
    fn spam(self) -> Self::Item;
}

pub trait Eggs {
    type Item;
    fn eggs(self) -> Self::Item;
    fn add_eggs(&mut self, eggs: Self::Item);
}

pub fn mix<T: Spam + Eggs>(mut value: T) {
    let spam = value.spam();
    let eggs = value.eggs();
    value.add_eggs(eggs);
    value.add_eggs(spam); // Spam!
}

fn main() {}

```

### Expected Behavior

It should be rejected, like it is in Rust: https://play.rust-lang.org/?version=stable&mode=debug&edition=2024&gist=4f848a7a84c6a9ff853e01d254bbb8b9

It should be something like this:
```
error[E0308]: mismatched types
  --> src/main.rs:16:20
   |
16 |     value.add_eggs(spam);
   |           -------- ^^^^ expected `Eggs::Item`, found `Spam::Item`
   |           |
   |           arguments to this method are incorrect
   |
   = note: expected associated type `<T as Eggs>::Item`
              found associated type `<T as Spam>::Item`
```

### Bug

```console
❯ cargo run -q -p nargo_cli -- compile --force && echo "ok"

ok
```

It also compiles if we rename one of the `Items` to something else.

### To Reproduce

See above.

### Workaround

None

### Workaround Description

_No response_

### Additional Context

_No response_

### Project Impact

None

### Blocker Context

_No response_

### Nargo Version

nargo version = 1.0.0-beta.18 noirc version = 1.0.0-beta.18+a796408a0d6eca324c036e59ac4d5ea1505a50c8 (git version hash: e1b2904367e55e88385af7905c2ded8e86920b49, is dirty: true)

### NoirJS Version

_No response_

### Proving Backend Tooling & Version

_No response_

### Would you like to submit a PR for this Issue?

None

### Support Needs

_No response_

### PR DESCRIPTION
**Pull request by aakoshh**
# Description

## Problem

Resolves #11347 

## Summary

Changes the `PartialEq` implementation for `Type` to compare the `name` of `NamedGeneric`s when both are unbound and implicitly added. 

## Additional Context

I read the explanation in https://github.com/noir-lang/noir/pull/8184 and seemed to revolve around creating named generics for the ordered generics of a trait that appears in the type bound. I'm not sure if by considering implicitly added variables different we will be rejecting something that should compile, but as it is today, it presents a soundness bug, where there are no comparisons on two generics, so we can pass invalid data to functions as long as they expect generics and the source is generic as well. Being a bit more conservative doesn't seem to hurt any tests. 

Note that this builds on https://github.com/noir-lang/noir/pull/11346 where the named generics were changed to be named e.g. `<A as Eggs>::Item`, but without that PR their name would just be `Item`, in which case the test I added here would still consider them equivalent to any other type with the same name.

Also noting that the ticket showcases _ordered_ generics, but here we have associated types. 

## User Documentation

Check one:
- [x] No user documentation needed.
- [ ] Changes in _docs/_ included in this PR.
- [ ] **[For Experimental Features]** Changes in _docs/_ to be submitted in a separate PR.

# PR Checklist

- [x] I have tested the changes locally.
- [ ] I have formatted the changes with [Prettier](https://prettier.io/) and/or `cargo fmt` on default settings.

### CODE REVIEW

File: compiler/noirc_frontend/src/tests/traits/trait_associated_items.rs [hunk 1]
```diff
@@ -517,3 +517,25 @@ fn associated_and_generic_type_share_name() {
...
+        type Item;
+        fn take_eggs(eggs: Self::Item);
+    }
+
+    pub fn mix<A: Spam, B: Eggs>() {
+        B::take_eggs(A::give_spam());
+                     ^^^^^^^^^^^^^^ Expected type <B as Eggs>::Item, found type <A as Spam>::Item
+    }
+    "#;
+    // TODO: Add error markup
```
Comment (jfecher) [inline compiler/noirc_frontend/src/tests/traits/trait_associated_items.rs]: Seems this is resolved?

**Comment by jfecher** [comment]
We should likely remove this equality check when checking traits entirely eventually but it doesn't need to be this PR
