### PR TITLE
fix: allow usage of decimal string encoding for fields larger than a `i128`

### LINKED ISSUE #2545: Large Field Input Causes Error
### Aim

Noir throws an exception when you try to use a large field value as input to the program. However, if you use a large field value as input in the `#[test]` function, the test will pass.

### Expected Behavior

Noir should not error when using a large field value as input to the program.

### Bug

Save the following code in `src/main.nr`:

```rust
fn main(x : Field, y : pub Field) {
    assert(x != y);
}

#[test]
fn test_main() {
    main(38635681773907251013895061801454257562916000962161246236232113416393728196608, 2);
}
```

Then run `nargo check`, you would see the following message:

```bash
[hello] Constraint system successfully built!
```

, meaning that the test case in `#[test]` passes.

Then, save the following in `Prover.toml` with exactly the same input as the test case:

```toml
x = "38635681773907251013895061801454257562916000962161246236232113416393728196608"
y = "2"
```

Then run `nargo prove`, you would see the following message:

```bash
Error: Expected witness values to be integers, provided value causes `number too large to fit in target type` error

Location:
    crates/nargo_cli/src/cli/mod.rs:79:5
```

### To Reproduce

1. Create a new project with `nargo new hello`
2. Save the code in `src/main.nr`
3. Run `nargo check`
4. Save the code in `Prover.toml`
5. Run `nargo prove`

### Installation Method

Binary

### Nargo Version

nargo 0.10.5 (git version hash: 9fe4cfd05b46d1d8867bc2583a11da32480366fc, is dirty: false)

### Additional Context

_No response_

### Would you like to submit a PR for this Issue?

No

### Support Needs

_No response_

### PR DESCRIPTION
**Pull request by TomAFrench**
# Description

## Problem\*

Resolves #2545
Resolves partly #2456 

## Summary\*

When parsing fields from strings, we're currently converting the string into an `i128` temporarily if it's a decimal representation. This limits the size of values which can be passed in as a decimal string compared to hex strings.

We now instead parse using a `BigUint` to ensure that we can handle all inputs.

## Documentation

- [ ] This PR requires documentation updates when merged.

  

  - [ ] I will submit a noir-lang/docs PR.

  

  - [ ] I will request for and support Dev Rel's help in documenting this PR.

  
  

## Additional Context

Note that `FieldElement` has a `try_from_str` implementation but as it returns an `Option<FieldElement>` rather than a `Result<FieldElement, Err>`, it's then not suitable for dealing with user input.

https://github.com/noir-lang/acvm/blob/5ad18bf8b365b57ba4c6f84004b5178e54562e7e/acir_field/src/generic_ark.rs#L204-L211

# PR Checklist\*

- [x] I have tested the changes locally.
- [x] I have formatted the changes with [Prettier](https://prettier.io/) and/or `cargo fmt` on default settings.

### CODE REVIEW

File: crates/noirc_abi/src/input_parser/mod.rs [hunk 1]
```diff
@@ -183,20 +186,52 @@ fn parse_str_to_field(value: &str) -> Result<FieldElement, InputParserError> {
     if value.starts_with("0x") {
         FieldElement::from_hex(value).ok_or_else(|| InputParserError::ParseHexStr(value.to_owned()))
     } else {
-        value
-            .parse::<i128>()
+        BigUint::from_str_radix(value, 10)
             .map_err(|err_msg| InputParserError::ParseStr(err_msg.to_string()))
-            .map(FieldElement::from)
+            // Note that we're reducing here. Should we reject inputs that don't fit in the field?
```
Comment (kevaundray) [inline crates/noirc_abi/src/input_parser/mod.rs:191]: Yeah I think its better to be more restrictive initially unless there is a need -- this means that the input needs to be canonical

Comment (TomAFrench) [reply crates/noirc_abi/src/input_parser/mod.rs:191]: Ah, I left this as I thought the hex wasn't performing this check. Looks like it does so will reduce here as well.

**Review by kevaundray — APPROVED** [review]
