### PR TITLE
fix(ssa refactor): Fix panic in acir-gen from multiplying values of different types

### LINKED ISSUE #1768: (SSA Refactor) Assert in acir gen after flattening pass merges two values
### Aim

Compiling code with if's with conditions that are witnesses:
```
fn main(a: bool, b: u32, c: u32) -> u32 {
    if a { b } else { c }
}
```

### Expected Behavior

Expected the code to compile

### Bug

The compiler panics with
```
Message:  assertion failed: `(left == right)`
  left: `Unsigned { bit_size: 1 }`,
 right: `Unsigned { bit_size: 32 }`: lhs and rhs types in Binary { lhs: Id(7176), rhs: Id(7183), operator: Mul } are not the same
Location: crates/noirc_evaluator/src/ssa_refactor/acir_gen/mod.rs:484
```
since the desugaring into `a*b + (!a)*c`, `a` and `b` are different types in the multiplication. `a` is a bool and `b` is a `u32`.

This affects: `9_conditional`, `8_arrays`, and `regression` after #1767 is merged.

### To Reproduce

1.
2.
3.
4.

### Installation Method

None

### Nargo Version

_No response_

### Additional Context

_No response_

### Would you like to submit a PR for this Issue?

No

### Support Needs

_No response_

### PR DESCRIPTION
**Pull request by jfecher**
# Description

## Problem\*

Resolves #1768

## Summary\*

Fixes an issue where acir_gen panics after the SSA flattening pass generates a multiplication of a boolean condition and non-boolean value.

## Documentation

- [ ] This PR requires documentation updates when merged.

  

  - [ ] I will submit a noir-lang/docs PR.

  

  - [ ] I will request for and support Dev Rel's help in documenting this PR.

  
  

## Additional Context

# PR Checklist\*

- [x] I have tested the changes locally.
- [x] I have formatted the changes with [Prettier](https://prettier.io/) and/or `cargo fmt` on default settings.

### CODE REVIEW

File: crates/noirc_evaluator/src/ssa_refactor/opt/flatten_cfg.rs [hunk 1]
```diff
@@ -459,6 +459,17 @@ impl<'f> Context<'f> {
...
         let block = self.inserter.function.entry_block();
+        let then_type = self.inserter.function.dfg.type_of_value(then_value);
+        let else_type = self.inserter.function.dfg.type_of_value(else_value);
+        assert_eq!(
+            then_type, else_type,
+            "Expected values merged to be of the same type but found {then_type} and {else_type}"
+        );
+
+        // We must cast the bool conditions to the actual numeric type used by each value.
+        let then_condition = self.insert_instruction(Instruction::Cast(then_condition, then_type));
```
Comment (kevaundray) [inline crates/noirc_evaluator/src/ssa_refactor/opt/flatten_cfg.rs:470]: LGTM -- this will always be a widening cast which is free

**Review by kevaundray — DISMISSED** [review]

**Review by kevaundray — APPROVED** [review]
