### PR TITLE
fix(brillig): prevent premature register deallocation in coalesced pairs

### LINKED ISSUE #11653: fix(brillig): premature register deallocation in block param coalescing
## Bug

The block parameter coalescing pass introduced in #11621 has a register lifetime bug that causes VM failures like:

```
Bit size for lhs 8 does not match op bit size 64
```

Found by the `min_vs_full` fuzzer: https://github.com/noir-lang/noir/actions/runs/22249715548/job/64370789033

## Root Cause

When arg-side coalescing maps `arg → param` (so the arg's defining instruction writes directly to the param's register), the dead variable handler only recognized the **arg** as a coalescing participant. When the **param** died first, `is_coalesced(param)` returned `false` (it only checked map keys), so the shared register was deallocated via `remove_variable`. If the arg was still live in a later block, its register could be reassigned to a new variable with a different bit_size.

Concretely, given:

```
b0(v0: u8):
  v1 = cast v0 as u32    // arg-coalesced to v4 → shares v4's register
  v2 = cast v0 as u32
  jmp b1(v1)
b1(v4: u32):              // param, register shared with v1
  v5 = lt v4, v2          // v4's last use → register freed ← BUG
  v6 = cast v0 as u8      // allocator reuses freed register with bit_size 8
  ...
b3():
  v8 = add v1, v2         // v1's register now has wrong bit_size → VM error
```

### PR DESCRIPTION
**Pull request by TomAFrench**
# Description

## Problem

Resolves #11653 

## Summary

When arg-side coalescing maps an argument to a block parameter's register, the parameter dying first would incorrectly free the shared register even though the argument still needed it. The freed register could then be reassigned with a different bit_size, causing VM errors like "Bit size for lhs 8 does not match op bit size 64".

The fix checks both directions of the coalescing map when a variable dies: the register is only deallocated if the coalescing partner is also dead. This is done via a new `get_partner` method that performs bidirectional lookup using a reverse map.

## User Documentation

Check one:
- [ ] No user documentation needed.
- [ ] Changes in _docs/_ included in this PR.
- [ ] **[For Experimental Features]** Changes in _docs/_ to be submitted in a separate PR.

# PR Checklist

- [ ] I have tested the changes locally.
- [ ] I have formatted the changes with [Prettier](https://prettier.io/) and/or `cargo fmt` on default settings.

### CODE REVIEW

File: compiler/noirc_evaluator/src/brillig/brillig_gen/tests/mod.rs [hunk 1]
```diff
@@ -6,21 +6,81 @@
...
 }
 
+/// Compile SSA source to a fully linked entry point and execute it with the given calldata.
+/// Returns the return data from the VM.
+pub(crate) fn execute_brillig_from_ssa(
+    src: &str,
+    calldata: Vec<FieldElement>,
+) -> Vec<FieldElement> {
+    let ssa = Ssa::from_str(src).unwrap();
+    let brillig = ssa.to_brillig(&BrilligOptions::default());
```
Comment (jfecher) [inline compiler/noirc_evaluator/src/brillig/brillig_gen/tests/mod.rs:42]: Can reuse `ssa_to_brillig_artifacts` here

**Review by jfecher — COMMENTED** [review]
LGTM but I'll wait for @vezenovm to approve

File: compiler/noirc_evaluator/src/brillig/brillig_gen/tests/mod.rs (hunk 1 above)
Comment (TomAFrench) [reply compiler/noirc_evaluator/src/brillig/brillig_gen/tests/mod.rs:42]: We need access to `ssa` so that we can construct `arguments`

File: compiler/noirc_evaluator/src/brillig/brillig_gen/tests/mod.rs [hunk 2]
```diff
@@ -6,21 +6,81 @@
...
+        .map(|&value_id| {
+            let typ = func.dfg.type_of_value(value_id);
+            FunctionContext::ssa_type_to_parameter(&typ)
+        })
+        .collect();
+    let generated = gen_brillig_for(func, arguments, &brillig, &BrilligOptions::default()).unwrap();
+    execute_bytecode(&generated.byte_code, calldata)
+}
+
+fn execute_bytecode(
```
Comment (aakoshh) [inline compiler/noirc_evaluator/src/brillig/brillig_gen/tests/mod.rs:56]: Could this be reused? 

https://github.com/noir-lang/noir/blob/427e343366d1749013d411865541eb6ac0937b45/compiler/noirc_evaluator/src/brillig/brillig_ir.rs#L438-L441
