### PR TITLE
fix(noirc_driver): Move error printing into nargo

### LINKED ISSUE #1537: Move printing errors to nargo_cli
### Problem

Currently errors are printed in noirc_driver to stdout, which is counter-intuitive for a crate that should be a library.

### Happy Case

We can move the printing of errors to `nargo_cli` instead

### Alternatives Considered

_No response_

### Additional Context

_No response_

### Would you like to submit a PR for this Issue?

No

### Support Needs

_No response_

### PR DESCRIPTION
**Pull request by phated**
# Description

## Problem\*

Resolves #1537 

## Summary\*

This refactors `noirc_driver` functions to return `Vec<FileDiagnostic>` if there is a problem compiling. The error reporter calls are then moved into `nargo_cli` since that is the only place we'd want them reported on stderr.

These changes make it possible for the LSP server to compile a file and send diagnostics back to the client (ref #1584).

I wasn't super happy to return non-Error types in the `Err` of the result, but I also don't think that these make sense to be an error, since we have to use a custom reporter to display them. I'm open to suggestions on how to clean this up.

Additional work:
* Added some `impl From` because it made converting between diagnostics/RuntimeError nicer.
* Removed `try_vecmap` because it bails at the first error, but we want to collect all of the FileDiagnostic errors that could occur and then only return a successful result it the errors are empty.
* Added a `file_manager()` function to `Driver` so I could get a reference to the internal file manager. This isn't great and the FileManager should instead be controlled by Nargo and passed by reference to the driver. I'll open an issue for this.
* Switched the `unwrap_or_else` calls in the wasm crate to use expect. The `unwrap_or_else` doesn't work consistently when I switched an API to Option instead of Result and expect does the exact same thing.

## Documentation

- [ ] This PR requires documentation updates when merged.

  

  - [ ] I will submit a noir-lang/docs PR.

  

  - [ ] I will request for and support Dev Rel's help in documenting this PR.

  
  

## Additional Context

# PR Checklist\*

- [x] I have tested the changes locally.
- [x] I have formatted the changes with [Prettier](https://prettier.io/) and/or `cargo fmt` on default settings.

### CODE REVIEW

File: crates/noirc_driver/src/lib.rs [hunk 1]
```diff
@@ -71,13 +70,17 @@ impl Driver {
         Driver { context: Context::default(), language: language.clone(), is_opcode_supported }
     }
 
+    pub fn file_manager(&self) -> &FileManager {
```
Comment (phated) [inline crates/noirc_driver/src/lib.rs:73]:
```suggestion
    // TODO(#1599): Move control of the FileManager into nargo
    pub fn file_manager(&self) -> &FileManager {
```

**Review by TomAFrench — DISMISSED** [review]
LGTM

**Review by kevaundray — APPROVED** [review]
re-approving and running CI again
