### PR TITLE
fix: compiler identifying imported functions as being part of a contract

### LINKED ISSUE #1111: Compiler sees imported functions as being part of the contract
### Aim

Trying to compile a contract with one function:
```rs
contract foo {
    use dep::bar::baz;

    fn desired_contract_function() { }
}
```

### Expected behavior

Expected the contract to contain 1 function - `desired_contract_function`

### Bug

The contract actually contains 2 functions, `desired_contract_function`, and `baz` provided `baz` is a function imported in scope.

A similar error can be made for `#[test]` functions, although this does not trigger as often since all imported functions without the `#[test]` attribute are filtered out.

### To reproduce

1.
2.
3.
4.

### Installation method

None

### Nargo version

_No response_

### @noir-lang/noir_wasm version

_No response_

### @noir-lang/barretenberg version

_No response_

### @noir-lang/aztec_backend version

_No response_

### Additional context

_No response_

### Submission Checklist

- [ ] Once I hit submit, I will assign this issue to the Project Board with the appropriate tags.

### PR DESCRIPTION
**Pull request by jfecher**
…the module

# Related issue(s)

Resolves #1111

# Description

## Summary of changes

Separates imported items in a module's scope from those originally defined within the module. Then we can use this separate list of items defined within the module to find all functions that should be part of the contract.

Previously we were using the module's scope which can include imported functions as well. I've separated these two constructs and made ModuleData more of an opaque wrapper to prevent this error in the future.

## Dependency additions / changes

None

## Test additions / changes

None

# Checklist

- [x] I have tested the changes locally.
- [x] I have formatted the changes with [Prettier](https://prettier.io/) and/or `cargo fmt` with default settings.
- [x] I have [linked](https://docs.github.com/en/issues/tracking-your-work-with-issues/linking-a-pull-request-to-an-issue) this PR to the issue(s) that it resolves.
- [x] I have reviewed the changes on GitHub, line by line.
- [x] I have ensured all changes are covered in the description.

## Documentation needs
- [ ] This PR requires documentation updates when merged.

# Additional context

### CODE REVIEW

File: crates/noirc_frontend/src/hir/def_collector/dc_mod.rs [hunk 1]
```diff
@@ -137,8 +136,7 @@ impl<'a> ModCollector<'a> {
 
             // Add function to scope/ns of the module
             let result = self.def_collector.def_map.modules[self.module_id.0]
-                .scope
-                .define_func_def(name, func_id);
+                .declare_function(name, func_id);
```
Comment (jfecher) [inline crates/noirc_frontend/src/hir/def_collector/dc_mod.rs:139]: I also changed these method names to declare_xxx rather than define_xxx as technically we are not actually defining the items, only declaring them. Defining them would entail adding the FuncMeta and function body as well.

**Review by kevaundray — APPROVED** [review]
