### PR TITLE
fix: Parsing nested generics

### LINKED ISSUE #1316: Nested generic syntax broken?
### Aim

Here's a minimal example. I want to write `A<B<C>>` for some concrete type `C`, but the compiler complains with `error: Unexpected <, expected one of >, ,, ::, binary operator`; I.e. it didn't expect to see `<` twice.

I conjured this example just as a way of being able to justify writing `A<B<Field>>`.

```rust
    struct A<T> {
        b: T,
    }

    impl<T> A<T> {
        fn new(b: T) -> Self {
            A { b }
        }
    }

    struct B<T> {
        c: T,
    }

    impl<T> B<T> {
        fn new(c: T) -> Self {
            B { c }
        }
    }


    fn main (c: Field, d: Field) -> pub A<B<Field>> {
        let mut b = B::new(c);
        let mut a = A::new(b);
        
        let mut ab = a.b;
        ab.c *= d;
        ab
    }
```

```
error: Unexpected <, expected one of >, ,, ::, binary operator
   ┌─ /mnt/user-data/mike/packages/yarn-project/noir-contracts/src/contracts/zk_nft_contract/src/main.nr:50:44
   │
50 │     fn main (c: Field, d: Field) -> pub A<B<Field>> {
   │                                            -

```

### Installation method

noirup

### Nargo version

nargo 0.4.1 (git version hash: 3d2233de810ab6d4a0f4f83007232133c88a49fe, is dirty: false)

### PR DESCRIPTION
**Pull request by jfecher**
# Related issue(s)

Resolves #1316

# Description

## Summary of changes

Generics always expect to end with a `Token::Greater`, however nested generics would use the syntax `A<B<T>>` where the final token(s) would be a `Token::ShiftRight` rather than two separate greater-than tokens.

Changing the type parser to also handle right shifts would be difficult as the shift would have to terminate two levels of nesting in the recursive parser. I opted instead for the other route of changing the lexer to always issue two greater-than tokens rather than combining them. From there I needed to add a few special cases in expression operators and the assign-operator shorthands.

## Test additions / changes

Added a small regression test line in the generics test.

# Checklist

- [x] I have tested the changes locally.
- [x] I have formatted the changes with [Prettier](https://prettier.io/) and/or `cargo fmt` with default settings.
- [x] I have [linked](https://docs.github.com/en/issues/tracking-your-work-with-issues/linking-a-pull-request-to-an-issue) this PR to the issue(s) that it resolves.
- [x] I have reviewed the changes on GitHub, line by line.
- [x] I have ensured all changes are covered in the description.

## Documentation needs
- [ ] This PR requires documentation updates when merged.

# Additional context

### CODE REVIEW

File: crates/noirc_frontend/src/lexer/lexer.rs [hunk 1]
```diff
@@ -162,9 +162,8 @@ impl<'a> Lexer<'a> {
                 if self.peek_char_is('=') {
                     self.next_char();
                     Ok(Token::GreaterEqual.into_span(start, start + 1))
-                } else if self.peek_char_is('>') {
-                    self.next_char();
-                    Ok(Token::ShiftRight.into_span(start, start + 1))
+                    // Note: There is deliberately now case for RightShift. We always lex >> as
```
Comment (kevaundray) [inline crates/noirc_frontend/src/lexer/lexer.rs:165]:
```suggestion
                    // Note: There is deliberately no case for RightShift. We always lex >> as
```

File: crates/noirc_frontend/src/parser/errors.rs [hunk 2]
```diff
@@ -147,7 +147,7 @@ impl chumsky::Error<Token> for ParserError {
             self.reason = other.reason;
         }
 
-        assert_eq!(self.span, other.span);
+        // assert_eq!(self.span, other.span);
```
Comment (kevaundray) [inline crates/noirc_frontend/src/parser/errors.rs:150]: Commented out line

Comment (jfecher) [reply crates/noirc_frontend/src/parser/errors.rs]: I've replaced it with a commit to merge the spans since otherwise we were running into the assert. I'm not exactly sure why this PR caused us to start hitting the assert but merging the spans should be correct since we're in the merge function.

File: crates/noirc_frontend/src/parser/parser.rs [hunk 3]
```diff
@@ -517,9 +517,22 @@ where
...
+/// lexed as two separate greater-than operators rather than a single right-shift.
 fn assign_operator() -> impl NoirParser<Token> {
     let shorthand_operators = Token::assign_shorthand_operators();
-    let shorthand_syntax = one_of(shorthand_operators).then_ignore(just(Token::Assign));
+    // We need to explicitly check for right_shift here since it is actually
+    // two separate greater-than operators.
+    let shorthand_operators = right_shift_operator().or(one_of(shorthand_operators));
+    let shorthand_syntax = shorthand_operators.then_ignore(just(Token::Assign));
+
+    // Since >> is lexed as two separte greater-thans, >>= is lexed as > >=, so
```
Comment (kevaundray) [inline crates/noirc_frontend/src/parser/parser.rs:530]:
```suggestion
    // Since >> is lexed as two separate greater-thans, >>= is lexed as > >=, so
```

**Review by kevaundray — APPROVED** [review]
