### PR TITLE
fix: Fix tokenization of unquoted types in macros

### LINKED ISSUE #5309: Convert a `Type` object into a token stream
### Aim

We'll need some way to convert a `Type` into a `Quoted` object to be able to splice it into another quoted token stream.

### Expected Behavior

This conversion should ideally be automatic so that:
```
comptime fn foo(typ: Type, code: Quoted) -> Quoted {
    quote {
        let _: $typ = $code;
    }
}
```
Works without needing to call `let typ = typ.into_quoted()` or similar.

### Bug

Currently the conversion used just calls `typ.to_string()` then lexes the string, but this doesn't work for type variables and seems to tightly coupled.

### To Reproduce

1.
2.
3.
4.

### Project Impact

None

### Impact Context

_No response_

### Workaround

None

### Workaround Description

_No response_

### Additional Context

_No response_

### Installation Method

None

### Nargo Version

_No response_

### NoirJS Version

_No response_

### Would you like to submit a PR for this Issue?

None

### Support Needs

_No response_

### PR DESCRIPTION
**Pull request by jfecher**
# Description

## Problem\*

Resolves #5309

## Summary\*

Fixes the tokenization of types by converting them to a new `QuotedType` token. We can get the original (resolved) type from this token so that we don't need to re-resolve a type after it is inserted into a macro's token stream. A QuotedType token holds onto an ID for the type rather than the type itself since our `Type` type does not implement Send or Sync, which is required through ParseError and UnresolvedTypeData.

## Documentation\*

Check one:
- [x] No documentation needed.
- [ ] Documentation included in this PR.
- [ ] **[For Experimental Features]** Documentation to be submitted in a separate PR.

# PR Checklist\*

- [x] I have tested the changes locally.
- [x] I have formatted the changes with [Prettier](https://prettier.io/) and/or `cargo fmt` on default settings.

### CODE REVIEW

File: compiler/noirc_frontend/src/hir/comptime/interpreter.rs [hunk 1]
```diff
@@ -98,7 +98,8 @@ impl<'a> Interpreter<'a> {
             .expect("all builtin functions must contain a function  attribute which contains the opcode which it links to");
 
         if let Some(builtin) = func_attrs.builtin() {
-            builtin::call_builtin(self.interner, builtin, arguments, location)
+            let builtin = builtin.clone();
+            builtin::call_builtin(self.interner, &builtin, arguments, location)
```
Comment (jfecher) [inline compiler/noirc_frontend/src/hir/comptime/interpreter.rs:102]: This clone is required since `interner` is passed in as mutable now.

**Review by TomAFrench — APPROVED** [review]
