### PR TITLE
fix: Implement handling of array aliasing in the mem2reg optimization pass

### LINKED ISSUE #2431: Handle references stored in arrays in new mem2reg pass
### Problem

The new mem2reg needs to track aliases throughout the program but does not track arrays at all.

### Happy Case

We should add support for tracking array values and the references that may be stored within them.

### Alternatives Considered

_No response_

### Additional Context

_No response_

### Would you like to submit a PR for this Issue?

No

### Support Needs

_No response_

### PR DESCRIPTION
**Pull request by jfecher**
# Description

## Problem\*

Resolves #2431

## Summary\*

This is the first of two PRs containing updates to the mem2reg pass. This one expands it to handle array aliasing (primitively - individual elements are not tracked). The next PR implements constant folding within mem2reg and contains the main regression test case which requires both PRs to pass. I've elected to split up the PRs so that the functionality split is a bit clearer and there is less code to review.

## Documentation

- [ ] This PR requires documentation updates when merged.

  

  - [ ] I will submit a noir-lang/docs PR.

  

  - [ ] I will request for and support Dev Rel's help in documenting this PR.

  
  

## Additional Context

# PR Checklist\*

- [x] I have tested the changes locally.
- [x] I have formatted the changes with [Prettier](https://prettier.io/) and/or `cargo fmt` on default settings.

### CODE REVIEW

File: crates/noirc_evaluator/src/ssa/opt/mem2reg.rs [hunk 1]
```diff
@@ -298,22 +300,85 @@ impl PerFunctionContext {
...
+                    let result = function.dfg.instruction_results(instruction)[0];
+                    let array = function.dfg.resolve(*array);
+
+                    let expression = Expression::ArrayElement(Box::new(Expression::Other(array)));
+
+                    if let Some(aliases) = references.aliases.get_mut(&expression) {
+                        aliases.insert(result);
+                    } else if let Some((elements, _)) = function.dfg.get_array_constant(array) {
+                        // TODO: This should be a unification of each alias set
+                        // If any are empty, the whole should be as well.
```
Comment (vezenovm) [inline crates/noirc_evaluator/src/ssa/opt/mem2reg.rs:329]: Is this handled in the followup PR or should we make an issue?

Comment (jfecher) [reply crates/noirc_evaluator/src/ssa/opt/mem2reg.rs:329]: I'll make an issue for it, its not handled in the mem2reg constant folding PR. In general we still need to handle other operations such as the builtin slice functions as well in case these return slices with references in them.

File: crates/noirc_evaluator/src/ssa/opt/mem2reg.rs [hunk 2]
```diff
@@ -298,22 +300,85 @@ impl PerFunctionContext {
...
-        &self,
-        values: &[ValueId],
-        function: &Function,
-        references: &mut Block,
-        last_stores: &mut BTreeMap<ValueId, InstructionId>,
-    ) {
+    fn check_array_aliasing(&self, function: &Function, references: &mut Block, array: ValueId) {
+        if let Some((elements, typ)) = function.dfg.get_array_constant(array) {
+            if Self::contains_references(&typ) {
+                // TODO: Check if type directly holds references or holds arrays that hold references
```
Comment (vezenovm) [inline crates/noirc_evaluator/src/ssa/opt/mem2reg.rs:345]: Is this handled in the followup PR or should we make an issue?

File: crates/noirc_evaluator/src/ssa/opt/mem2reg.rs (hunk 1 above)
Comment (jfecher) [reply crates/noirc_evaluator/src/ssa/opt/mem2reg.rs:329]: https://github.com/noir-lang/noir/issues/2477

**Review by vezenovm — APPROVED** [review]
LGTM. Is this issue (https://github.com/noir-lang/noir/issues/2221) resolved after this PR?

**Comment by jfecher** [comment]
@vezenovm, unfortunately not, looks like it needs the constant folding change as well
