### PR TITLE
fix: support turbofish on `<Ty as Trait>::method::<T>()` paths

### LINKED ISSUE #12395: Unable to use turbofish with `AsTrait` call syntax
I ran into this while testing #12394 

```noir
// does not compile
fn main() {
    <MyStruct as MyTrait>::foo::<Field>();
}

// compiles
// fn main() {
//     MyStruct::foo::<Field>();
// }

pub struct MyStruct {}

pub trait MyTrait {
    fn foo<T>();
}

impl MyTrait for MyStruct {
    fn foo<T>() {}
}
```

This fails to compile with the following errors.

```
error: No method named '' found for type 'Field'
  ┌─ src/main.nr:2:40
  │
2 │     <MyStruct as MyTrait>::foo::<Field>();
  │                                        -
  │

error: Type annotation needed
  ┌─ src/main.nr:2:28
  │
2 │     <MyStruct as MyTrait>::foo::<Field>();
  │                            --- Could not determine the type of the generic argument `T` declared on the function `foo`
  │

error: Expected an identifier but found '<'
  ┌─ src/main.nr:2:33
  │
2 │     <MyStruct as MyTrait>::foo::<Field>();
  │                                 -
  │

error: Expected a '::' but found '('
  ┌─ src/main.nr:2:40
  │
2 │     <MyStruct as MyTrait>::foo::<Field>();
  │                                        -
  │

error: Expected an identifier but found '('
  ┌─ src/main.nr:2:40
  │
2 │     <MyStruct as MyTrait>::foo::<Field>();
  │                                        -
  │

error: Expected a ; separating these two statements
  ┌─ src/main.nr:2:28
  │
2 │     <MyStruct as MyTrait>::foo::<Field>();
  │                            ---
  │

Aborting due to 6 previous errors
```

### PR DESCRIPTION
**Pull request by AztecBot**
## Summary

Closes https://github.com/noir-lang/noir/issues/12395 (and unblocks https://github.com/noir-lang/noir/issues/9562).

`<MyStruct as MyTrait>::foo::<Field>()` previously failed to parse with six cascading errors, because the `AsTraitPath` parser/AST had no notion of a trailing turbofish. Sibling `TypePath` already supports this (`Field::foo::<T>()`); this PR brings `AsTraitPath` in line.

- Add `turbofish: Option<GenericTypeArgs>` to `AsTraitPath` and parse an optional `::<...>` after the `impl_item` in `parse_as_trait_path_for_type_after_as_keyword`.
- In `elaborate_as_trait_path`, resolve the turbofish generics via `use_type_args` when the impl item is a function, error with `PathResolutionError::TurbofishNotAllowedOnItem` otherwise, and thread the resolved `Vec<Type>` through `HirExpression::Ident` and `type_check_variable_with_bindings` (they were previously hard-coded to `None`, which is why explicit generics were ignored even when syntactically accepted).
- Propagate the new field through `Display`, the AST visitor, the comptime display passes, the LSP `with_file` copy, and the formatter.

## Test plan

- Re-enabled `as_trait_path_with_method_turbofish` (was `#[should_panic]` tracking #9562) — now passes.
- Added `as_trait_path_with_turbofish_no_args` — the exact reproducer from #12395.
- Added `as_trait_path_turbofish_on_associated_constant_errors` — verifies turbofish on an associated constant surfaces `TurbofishNotAllowedOnItem` rather than being silently accepted.
- Added `format_as_trait_path_with_turbofish` in `nargo_fmt`.
- `cargo nextest run -p noirc_frontend` — 1709/1709 pass.
- `cargo nextest run -p nargo_fmt -p noir_lsp` — all pass.
- `cargo clippy` and `cargo fmt` clean on the touched crates.

Details: https://gist.github.com/AztecBot/ca78d7e1928e7131bef5a794a01f186f

Closes #12395

ClaudeBox log: https://claudebox.work/s/26f6d84c9a5c69bc?run=1

### CODE REVIEW

File: compiler/noirc_frontend/src/tests/traits/trait_qualified_paths.rs [hunk 1]
```diff
@@ -272,9 +270,9 @@ fn as_trait_path_self_type() {
     assert_no_errors(src);
 }
 
-/// TODO(https://github.com/noir-lang/noir/issues/9562): Reactivate once the issue is resolved
+/// Regression test for https://github.com/noir-lang/noir/issues/9562
+/// and https://github.com/noir-lang/noir/issues/12395
```
Comment (TomAFrench) [inline compiler/noirc_frontend/src/tests/traits/trait_qualified_paths.rs]:
```suggestion
```

**Comment by TomAFrench** [comment]
@asterite This solution looks pretty clean to me, can you give it a quick look over?

**Review by asterite — APPROVED** [review]
