### PR TITLE
fix: apply check on truncating output of unchecked sub only to signed types

### LINKED ISSUE #11850: Bug: truncation of unchecked subtraction
### Aim

The fuzzer found this (this is the reduced code):

```noir
fn main(a: u8, c: [Field; 1]) {
    let _ = c[(255 - (a as u32)) % 4];
}
```

`nargo compile` gives:

```
The application panicked (crashed).
Message:  internal error: entered unreachable code: Truncation of unchecked subtraction
Location: compiler/noirc_evaluator/src/acir/mod.rs:860
```

### Expected Behavior

The code should compile.

### Bug

It crashes.

### To Reproduce

1.
2.
3.
4.

### Workaround

None

### Workaround Description

_No response_

### Additional Context

_No response_

### Project Impact

None

### Blocker Context

_No response_

### Nargo Version

_No response_

### NoirJS Version

_No response_

### Proving Backend Tooling & Version

_No response_

### Would you like to submit a PR for this Issue?

None

### Support Needs

_No response_

### PR DESCRIPTION
**Pull request by TomAFrench**
# Description

## Problem

Resolves #11850

## User Documentation

Check one:
- [ ] No user documentation needed.
- [ ] Changes in _docs/_ included in this PR.
- [ ] **[For Experimental Features]** Changes in _docs/_ to be submitted in a separate PR.

# PR Checklist

- [ ] I have tested the changes locally.
- [ ] I have formatted the changes with [Prettier](https://prettier.io/) and/or `cargo fmt` on default settings.

### CODE REVIEW

File: compiler/noirc_evaluator/src/acir/mod.rs [hunk 1]
```diff
@@ -853,11 +853,25 @@ impl<'a> Context<'a> {
...
+                if let Instruction::Binary(Binary {
+                    operator: BinaryOp::Sub { unchecked: true },
+                    lhs,
+                    rhs,
+                }) = &dfg[*instruction]
+                {
+                    // An unchecked subtraction feeding into a truncate is safe only if the
+                    // subtraction cannot underflow. We re-verify the same safety condition
+                    // that the checked_to_unchecked pass uses to convert subs to unchecked.
+                    let mut value_max_num_bits = Default::default();
```
Comment (TomAFrench) [inline compiler/noirc_evaluator/src/acir/mod.rs]: This looks like we can still have false positives due to the fact that `checked_to_unchecked` tracks this state which can result in `is_unsigned_sub_safe` returning true within the SSA pass but not here.

Comment (guipublic) [reply compiler/noirc_evaluator/src/acir/mod.rs]: I was fixing this by rather doing the check only for signed operations, assuming unsigned  unchecked sub are already proven to not underflow.

File: compiler/noirc_evaluator/src/ssa/opt/checked_to_unchecked.rs [hunk 2]
```diff
@@ -28,6 +28,33 @@ impl Ssa {
...
 
+/// Returns true if an unsigned subtraction `lhs - rhs` is guaranteed not to underflow.
+///
+/// This is the case when `lhs` is a constant that is >= the maximum possible value of `rhs`
+/// (determined by its bit width). For example, `256 - (x as u32)` where `x: u8` cannot
+/// underflow because `256 >= 255`.
+///
+/// This function is used both by the `checked_to_unchecked` pass (to decide whether to convert)
+/// and by ACIR generation (to verify the conversion was sound).
+pub(crate) fn is_unsigned_sub_safe(
```
Comment (TomAFrench) [inline compiler/noirc_evaluator/src/ssa/opt/checked_to_unchecked.rs]:
```suggestion
fn is_unsigned_sub_safe(
```

File: compiler/noirc_evaluator/src/acir/tests/instructions.rs [hunk 3]
```diff
@@ -347,14 +347,14 @@ fn make_array() {
     ");
 }
 
-/// An integer-typed unchecked sub whose result feeds a truncate is an SSA invariant violation;
+/// A signed-typed unchecked sub whose result feeds a truncate is an SSA invariant violation;
 /// the SSA validator must reject it before ACIR generation even starts.
 #[test]
 #[should_panic(expected = "Truncate follows an integer-typed unchecked Sub, which may underflow")]
```
Comment (aakoshh) [inline compiler/noirc_evaluator/src/acir/tests/instructions.rs]:
```suggestion
#[should_panic(expected = "Truncate follows a signed integer-typed unchecked Sub, which may underflow")]
```

File: compiler/noirc_evaluator/src/ssa/validation/mod.rs [hunk 4]
```diff
@@ -277,18 +277,16 @@ impl<'f> Validator<'f> {
...
                         ..
                     }) = &dfg[*instruction]
-                    && matches!(
-                        dfg.type_of_value(*lhs),
-                        Type::Numeric(NumericType::Unsigned { .. } | NumericType::Signed { .. })
-                    )
+                    && matches!(dfg.type_of_value(*lhs), Type::Numeric(NumericType::Signed { .. }))
                 {
                     panic!(
                         "Truncate follows an integer-typed unchecked Sub, which may underflow. \
```
Comment (aakoshh) [inline compiler/noirc_evaluator/src/ssa/validation/mod.rs]:
```suggestion
                        "Truncate follows a signed integer-typed unchecked Sub, which may underflow. \
```

File: compiler/noirc_evaluator/src/ssa/opt/checked_to_unchecked.rs [hunk 5]
```diff
@@ -28,6 +28,33 @@ impl Ssa {
...
 }
 
+/// Returns true if an unsigned subtraction `lhs - rhs` is guaranteed not to underflow.
+///
+/// This is the case when `lhs` is a constant that is >= the maximum possible value of `rhs`
+/// (determined by its bit width). For example, `256 - (x as u32)` where `x: u8` cannot
+/// underflow because `256 >= 255`.
+///
+/// This function is used both by the `checked_to_unchecked` pass (to decide whether to convert)
+/// and by ACIR generation (to verify the conversion was sound).
```
Comment (aakoshh) [inline compiler/noirc_evaluator/src/ssa/opt/checked_to_unchecked.rs]: I only saw this being called once in this PR.

Comment (guipublic) [reply compiler/noirc_evaluator/src/ssa/opt/checked_to_unchecked.rs]: Done
