### PR TITLE
fix: allow using Self for function calls

### LINKED ISSUE #1791: `Self` doesn't resolve when calling static struct methods as `Self::f`
### Aim

I was trying to use the `Self` keyword as a path to call the static `one()` method in noir

```rust
struct S { }

impl S {
    fn one() -> Field {
        1
    }

    fn two() -> Field {
        Self::one() + Self::one()
        // This compiles
        // S::one() + S::one()
    }
}

fn main() { }
```

### Expected Behavior

`Self` keyword should be resolved in the path, allowing for the method to be called, just as it would be in Rust.

### Bug

When attempting to use the `Self` keyword in noir, the following error is thrown: 
```
error: Could not resolve 'Self' in path.
```

### To Reproduce

1. Copy the code above
2. Run `nargo compile --allow-warnings`

### Installation Method

Compiled from source

### Nargo Version

nargo 0.6.0 (git version hash: 0181813203a9e3e46c6d8c3169ad5d25971d4282, is dirty: false)

### Additional Context

_No response_

### Would you like to submit a PR for this Issue?

No

### Support Needs

_No response_

### PR DESCRIPTION
**Pull request by asterite**
# Description

## Problem

Resolves #1791

## Summary

When resolving a path (any path), we now check if the first segment is `Self` (a similar check is done in another places of our codebase). If so, resolve the next path segments relative to that type. Only struct types are supported here... in theory a trait type can also show up, but that case is handled as a special case in the compiler. I'll create a follow-up PR removing that special case and seeing if it works.

## Additional Context

None.

## Documentation\*

Check one:
- [x] No documentation needed.
- [ ] Documentation included in this PR.
- [ ] **[For Experimental Features]** Documentation to be submitted in a separate PR.

# PR Checklist\*

- [x] I have tested the changes locally.
- [x] I have formatted the changes with [Prettier](https://prettier.io/) and/or `cargo fmt` on default settings.

### CODE REVIEW

File: compiler/noirc_frontend/src/elaborator/scope.rs [hunk 1]
```diff
@@ -43,7 +43,34 @@ impl<'context> Elaborator<'context> {
     }
 
     pub(super) fn resolve_path(&mut self, path: Path) -> Result<ModuleDefId, ResolverError> {
-        let resolver = StandardPathResolver::new(self.module_id());
+        let mut module_id = self.module_id();
+        let mut path = path;
+
+        if path.kind == PathKind::Plain && path.first_name() == SELF_TYPE_NAME {
+            if let Some(Type::Struct(struct_type, _)) = &self.self_type {
```
Comment (michaeljklein) [inline compiler/noirc_frontend/src/elaborator/scope.rs:50]: Should we output a specific user error if `Self` points to an unresolvable `Type`?

File: compiler/noirc_frontend/src/tests.rs [hunk 2]
```diff
@@ -2729,3 +2729,23 @@ fn incorrect_generic_count_on_type_alias() {
...
+    let src = r#"
+    struct S { }
+
+    impl S {
+        fn one() -> Field {
+            1
+        }
+
+        fn two() -> Field {
+            Self::one() + Self::one()
```
Comment (michaeljklein) [inline compiler/noirc_frontend/src/tests.rs:2744]: Please add a test to access a struct member from `Self` to make sure those resolve properly, e.g. an impl method `fn foo(self) { self.x + self.y }` .. `fn main() { assert(something.foo() == expected) }`.

And also perhaps the other cases discussed in slack:
```rust
trait Foo {
  fn foo() {}
}

impl Foo for T { } // <- T here

// OR
trait Foo where Self: EQ { // <- Self here
  fn foo(self) -> bool {
    self == self
  }
}

// OR
trait Foo {
  fn foo() {
    Self::bar() // <-- this Self
  }
}

**Review by michaeljklein — CHANGES_REQUESTED** [review]

File: compiler/noirc_frontend/src/elaborator/scope.rs (hunk 1 above)
Comment (asterite) [reply compiler/noirc_frontend/src/elaborator/scope.rs:50]: Right now the error is "Could not resolve 'Self' in path". 

Checking Rust, if you have this:

```rust
fn foo() -> Self {}
```

the error is "cannot find type `Self` in this scope" with some more helpful comments like "`Self` is only available in impls, traits, and type definitions" and "`Self` not allowed in a function".

If you have this:

```rust
fn foo() {
    Self::bar();
}
```

the error is "failed to resolve: `Self` is only available in impls, traits, and type definitions".

I guess in both cases we could say "cannot find type `Self` in this scope. `Self` is only available in impls, traits, and type definitions".

What do you think?

File: compiler/noirc_frontend/src/tests.rs (hunk 2 above)
Comment (asterite) [reply compiler/noirc_frontend/src/tests.rs:2744]: > e.g. an impl method fn foo(self) { self.x + self.y }

I think that goes through a different code path, so maybe the changes in this PR don't affect that. For example there's a test that uses `self.a`:

https://github.com/noir-lang/noir/blob/cca89c10b476fbf500dcf471c7b2271717a6cf61/compiler/noirc_frontend/src/tests.rs#L129

> And also perhaps the other cases discussed in slack

👍

File: compiler/noirc_frontend/src/elaborator/scope.rs (hunk 1 above)
Comment (asterite) [reply compiler/noirc_frontend/src/elaborator/scope.rs:50]: Put another way, do you think a more specific error than "Could not resolve 'Self' in path" is worth it? The current error message isn't wrong either...

File: compiler/noirc_frontend/src/tests.rs (hunk 2 above)
Comment (asterite) [reply compiler/noirc_frontend/src/tests.rs:2744]: Done!

File: compiler/noirc_frontend/src/elaborator/scope.rs (hunk 1 above)
Comment (jfecher) [reply compiler/noirc_frontend/src/elaborator/scope.rs:50]: Rust's error is better and if possible we should emulate it. That being said, I think our error is also fine and we don't need to bend over backwards trying to emulate rust's error if it is overly cumbersome to do so.

**Review by michaeljklein — APPROVED** [review]
LGTM
