### PR TITLE
fix(mem2reg): Update array set value alias set and propagate array get result as alias 

### LINKED ISSUE #10020: Incorrect alias set calculation for MakeArray instruction
This is an issue reported by Veridise ([audithub](https://audithub.veridise.com/app/organizations/146/projects/434/project-viewer?version=1007&bpt=1&issue=413))

---

When the `PerFunctionContext::analyze_possibly_simplified_instruction` method processes a `MakeArray` instruction, it initializes the alias set of the result of the instruction (i.e., the newly created array) as containing the union of all of the alias sets of its elements. Conceptually, this is equivalent to stating that "the set of pointers that point to the array consists of the pointers that point to the array elements," which is a false statement.

For example, suppose there is a program with two variables--a mutable variable x and a (mutable) array variable a which contains a reference to x. The current implementation would consider a to be referred to by x and a, which is incorrect since there is no way to get a reference to the newly initialized value a from x. Rather, the correct reasoning is to consider a as the only reference to itself. It is x that is now referred to by x and a, because it is possible to obtain a reference to the location of x by indexing into a.

# Impact

The alias set information computed by the Mem2Reg pass is used in order to determine when it is safe to (1) replace a load instruction with a previous load's result; or (2) remove a store instruction. Since the alias set is computed incorrectly, writes and reads involving references that are contained in arrays may be silently and erroneously removed by the compiler, resulting in a change in the semantics of the program. The following example illustrates this in more detail:

Example Noir code involving an array of references. The array is accessed using a for-loop with just one iteration, so that the reference variable p always points to the location of x. Thus, the value of v should always be 2 because of the x = 2 line before the addition to v.

```
fn main() -> pub Field {
  let mut x = 0;
  let mut y = 0;
  let a: [&mut Field; 2] = [&mut x, &mut y];
  let mut v = 0;
  for i in 0..1 {
    let p = a[i];
    *p = 1;
    x = 2;
    v += *p
  }
  v
}

#[test]
fn test_main() {
    assert_eq(main(), 2);
}
```

The nargo test command reports a failure on this example:

```
$ nargo test
[testcases] Running 1 test function
[testcases] Testing test_main ... FAIL
Failed to solve program: 'Cannot satisfy constraint'

error: Failed constraint
   ┌─ src/main.nr:17:15
   │
17 │     assert_eq(main(), 2);
   │               ---------
   │
   = Call stack:
	1. src/main.nr:17:15
```

As shown by the SSA code that is emitted after the Mem2Reg pass, the Mem2Reg pass incorrectly replaces the dereference of p with the constant 1.

```
After Inlining simple functions (1) (step 4):
acir(inline) fn test_main f0 {
  b0():
    v1 = call f1() -> Field
    v3 = eq v1, Field 2
    constrain v1 == Field 2
    return
}
acir(inline) fn main f1 {
  b0():
    v1 = allocate -> &mut Field
    store Field 0 at v1
    v3 = allocate -> &mut Field
    store Field 0 at v3
    v4 = make_array [v1, v3] : [&mut Field; 2]
    v5 = allocate -> &mut Field
    store Field 0 at v5
    jmp b1(u32 0)
  b1(v0: u32):
    v7 = eq v0, u32 0
    jmpif v7 then: b2, else: b3
  b2():
    v9 = array_get v4, index v0 -> &mut Field
    store Field 1 at v9
    store Field 2 at v1
    v12 = load v5 -> Field
    v13 = load v9 -> Field
    v14 = add v12, v13
    store v14 at v5
    v16 = unchecked_add v0, u32 1
    jmp b1(v16)
  b3():
    v8 = load v5 -> Field
    return v8
}

After Mem2Reg (1) (step 5):
acir(inline) fn test_main f0 {
  b0():
    v1 = call f1() -> Field
    v3 = eq v1, Field 2
    constrain v1 == Field 2
    return
}
acir(inline) fn main f1 {
  b0():
    v1 = allocate -> &mut Field
    store Field 0 at v1
    v3 = allocate -> &mut Field
    store Field 0 at v3
    v4 = make_array [v1, v3] : [&mut Field; 2]
    v5 = allocate -> &mut Field
    store Field 0 at v5
    jmp b1(u32 0)
  b1(v0: u32):
    v7 = eq v0, u32 0
    jmpif v7 then: b2, else: b3
  b2():
    v9 = array_get v4, index v0 -> &mut Field
    store Field 1 at v9
    store Field 2 at v1
    v12 = load v5 -> Field
    v13 = add v12, Field 1
    store v13 at v5
    v15 = unchecked_add v0, u32 1
    jmp b1(v15)
  b3():
    v8 = load v5 -> Field
    return v8
}
```

Recommendation

The alias set of each of the array elements should be updated to include the result of the MakeArray, because the array itself acts like a reference to its elements.

### LINKED ISSUE #10070: Incorrect alias set calculation for ArraySet instruction
See https://audithub.veridise.com/app/organizations/146/projects/434/project-viewer?version=1038&issue=424&bpt=1

--- 

Similar to [Incorrect alias set calculation for MakeArray instruction](https://audithub.veridise.com/app/organizations/146/projects/434/project-viewer?version=1007&issue=413&bpt=1), in the Mem2Reg pass, the wrong alias sets are updated in the ArraySet instruction. Conceptually, the alias set of the value that is set in the array should be updated to contain the result of the ArraySet instruction. This is because by dereferencing the updated array, it is possible to obtain a reference to the location referred to by the value.

# Impact

For example, consider the following SSA code snippet:

An example of SSA code that uses ArraySet, ArrayLoad, Load, and Store instructions. The input array v0 is an array of a single &mut Field, which makes it practically similar to a reference. The element v0[0] is assigned to either v3 or v4 depending on which branch is taken; therefore, the resulting load v8 = v0[0] can be either v3 or v4. Because the values 2 and 3 are stored to v3 and v4, respectively, it follows that it is unsafe to substitute the load v8 instruction with any of the constants in the Store instructions.

```
brillig(inline) fn main f0 {
  b0(v0: [&mut Field; 1], v1: u1):
    v3 = allocate -> &mut Field
    v4 = allocate -> &mut Field
    jmpif v1 then: b1, else: b2
  b1():
    v7 = array_set v0, index u32 0, value v3
    jmp b3(v7)
  b2():
    v6 = array_set v0, index u32 0, value v4
    jmp b3(v6)
  b3(v2: [&mut Field; 1]):
    v8 = array_get v2, index u32 0 -> &mut Field
    store Field 1 at v8
    store Field 2 at v3
    store Field 3 at v4
    v12 = load v8 -> Field
    return v12
}
```

When the Mem2Reg pass is applied to the above code, the resulting SSA code has the load incorrectly replaced with a constant:

```
brillig(inline) fn main f0 {
  b0(v0: [&mut Field; 1], v1: u1):
    v3 = allocate -> &mut Field
    v4 = allocate -> &mut Field
    jmpif v1 then: b1, else: b2
  b1():
    v7 = array_set v0, index u32 0, value v3
    jmp b3(v7)
  b2():
    v6 = array_set v0, index u32 0, value v4
    jmp b3(v6)
  b3(v2: [&mut Field; 1]):
    v8 = array_get v2, index u32 0 -> &mut Field
    store Field 1 at v8
    store Field 2 at v3
    store Field 3 at v4
    return Field 1
}
```

In practice, it is difficult to construct such input SSA code, because the Noir frontend does not allow updating an array of references or returning a reference from an if-then-else. However, the input SSA could potentially result from a combination of earlier optimizations in the pass pipeline.

# Recommendation

Ensure that the alias sets that contain the array are updated with the result of the array set. The change should also include the alias set of the value that is stored in the array. This would ensure, for example, that the stores to v3 and v4 in the above example would invalidate the known value of v8.

### PR DESCRIPTION
**Pull request by vezenovm**
# Description

## Problem\*

Alternative to #10175
Resolves #10070 
Resolves #10020

Fix to timed out tests https://github.com/noir-lang/noir/pull/10175#pullrequestreview-3331581074

## Summary\*

We were appropriately setting the initial alias sets for the results of make_array, array_get, and array_set with arrays of references. We just were not also setting the alias sets of the array elements themselves to also include the result of `array_get` and `array_set` in their alias sets. 

For example in this code:
```
        brillig(inline) fn main f0 {
          b0(v0: [&mut Field; 1], v1: u1):
            v3 = allocate -> &mut Field
            v4 = allocate -> &mut Field
            jmpif v1 then: b1, else: b2
          b1():
            v7 = array_set v0, index u32 0, value v3
            jmp b3(v7)
          b2():
            v6 = array_set v0, index u32 0, value v4
            jmp b3(v6)
          b3(v2: [&mut Field; 1]):
            v8 = array_get v2, index u32 0 -> &mut Field
            store Field 1 at v8
            store Field 2 at v3
            store Field 3 at v4
            v12 = load v8 -> Field
            return v12
        }
```
`v6` and `v7` have the appropriate alias sets. However, v3 and v4 were not being updated to include v6 and v7 in their own alias sets. This PR makes that change and #10070 passes.

Same thing for this case:
```
        acir(inline) predicate_pure fn main f0 {
          b0():
            v1 = allocate -> &mut Field
            store Field 0 at v1
            v3 = allocate -> &mut Field
            store Field 0 at v3
            v4 = make_array [v1, v3] : [&mut Field; 2]
            v5 = allocate -> &mut Field
            store Field 0 at v5
            jmp b1(u32 0)
          b1(v0: u32):
            v7 = eq v0, u32 0
            jmpif v7 then: b2, else: b3
          b2():
            v9 = array_get v4, index v0 -> &mut Field
            store Field 1 at v9
            store Field 2 at v1
            v12 = load v5 -> Field
            v13 = load v9 -> Field
            v14 = add v12, v13
            store v14 at v5
            v16 = unchecked_add v0, u32 1
            jmp b1(v16)
          b3():
            v8 = load v5 -> Field
            return v8
        }
```
`v4` and `v9` had the appropriate alias sets post the array_get in b2. However, the aliases of `v4` (which are `v1` and `v3`) were not being updated to include `v9` in their alias sets. Once making this update #10020 passes.

## Additional Context

We can see in https://github.com/noir-lang/noir/pull/10242#pullrequestreview-3356982197 that the `rollup-checkpoint-root-*` tests are back. 

## Documentation\*

Check one:
- [X] No documentation needed.
- [ ] Documentation included in this PR.
- [ ] **[For Experimental Features]** Documentation to be submitted in a separate PR.

# PR Checklist\*

- [X] I have tested the changes locally.
- [X] I have formatted the changes with [Prettier](https://prettier.io/) and/or `cargo fmt` on default settings.

### CODE REVIEW

File: compiler/noirc_evaluator/src/ssa/opt/mem2reg/block.rs [hunk 1]
```diff
@@ -81,43 +82,6 @@ impl Block {
...
-                None
-            })
-            .collect();
-        // Invalidate addresses with possible aliasing to `address`
-        for addr in addresses_to_invalidate {
-            self.references.remove(&addr);
-        }
-
-        // We always know address points to value
-        self.set_reference_value(address, value);
```
Comment (jfecher) [inline compiler/noirc_evaluator/src/ssa/opt/mem2reg/block.rs:120]: The original motivation for this last bit at least was that even if you have a reference with multiple aliases, when you do `*v1 = 2;` you know the value of the next `*v1` should be 2 regardless of aliases to it.

I think the fix in this PR is an improvement since we won't have to maintain the large chunk of removed code above, but I'm curious on the motivation for this change / where my intuition is incorrect. The linked issues seem to be for arrays rather than references directly so I wonder how related it is - e.g. would it be fine if we did this only for proper references?

**Review by jfecher — APPROVED** [review]

File: compiler/noirc_evaluator/src/ssa/opt/mem2reg/block.rs (hunk 1 above)
Comment (vezenovm) [reply compiler/noirc_evaluator/src/ssa/opt/mem2reg/block.rs:120]: > I'm curious on the motivation for this change

It felt like the least intrusive change that maintains safety. The code above this line comes from #10175 that caused our `rollup-checkpoint-root-*` tests to all timeout. Yes you are correct the linked issues are for arrays rather than references directly. Let me see if I can break this assumption with regular aliases before merging. 

To give more context, here is the `regression_10070` unit test: 
```
        brillig(inline) fn main f0 {
          b0(v0: [&mut Field; 1], v1: u1):
            v3 = allocate -> &mut Field
            v4 = allocate -> &mut Field
            jmpif v1 then: b1, else: b2
          b1():
            v7 = array_set v0, index u32 0, value v3
            jmp b3(v7)
          b2():
            v6 = array_set v0, index u32 0, value v4
            jmp b3(v6)
          b3(v2: [&mut Field; 1]):
            v8 = array_get v2, index u32 0 -> &mut Field
            store Field 1 at v8
            store Field 2 at v3
            store Field 3 at v4
            v12 = load v8 -> Field
            return v12
        }
``` 
We do correctly mark `v8` as being unknown. Yet, we still store into v8 and resolve its later load to be `1`. This still seems like it would be correct for standard reference aliases, not just those that come from arrays.

Comment (jfecher) [reply compiler/noirc_evaluator/src/ssa/opt/mem2reg/block.rs:120]:
```
store Field 1 at v8
store Field 2 at v3
store Field 3 at v4
```
For code like this I'd expect the first store to have `v8`'s value become known, but then for the second store to invalidate that value as it should have `v8` as a potential alias - same for `v4`.
This sounds like an alias set issue rather than an issue with the final set_known_value call

Comment (vezenovm) [reply compiler/noirc_evaluator/src/ssa/opt/mem2reg/block.rs:120]: > I'd expect the first store to have `v8`'s value become known, but then for the second store to invalidate that value as it should have `v8` as a potential alias - same for `v4`

Good point. This does look to be a more general alias set issue.

Comment (vezenovm) [reply compiler/noirc_evaluator/src/ssa/opt/mem2reg/block.rs:120]: Ok thanks for the catch. I switched to simply updating the alias sets of the array values in both `ArraySet` and `ArrayGet`.

**Review by jfecher — APPROVED** [review]
Yeah, this looks a lot more like the common problem of "we need to update the alias set in both directions" now. I think this version of the fix is more likely to fix the core issue.
