### PR TITLE
fix: Check for overlapping implementations

### LINKED ISSUE #10540: Overlapping impls are not detected by the compiler
### Aim

This code:

```noir
struct Foo<T> {}

impl Foo<i32> {
    fn foo(self) {}
}

impl<T> Foo<T> {
    fn foo(self) {}
}

fn main() {}
```

gives no error. However, the impls are ambiguous.

An equivalent Rust code does error:

```
error[E0592]: duplicate definitions with name `foo`
 --> foo/src/main.rs:4:5
  |
4 |     fn foo(self) {}
  |     ^^^^^^^^^^^^ duplicate definitions for `foo`
...
8 |     fn foo(self) {}
  |     ------------ other definition for `foo`
```

### Expected Behavior

The compiler should error on overlapping impls.

### Bug

The compiler does not error.

### To Reproduce

1.
2.
3.
4.

### Workaround

None

### Workaround Description

_No response_

### Additional Context

_No response_

### Project Impact

None

### Blocker Context

_No response_

### Nargo Version

_No response_

### NoirJS Version

_No response_

### Proving Backend Tooling & Version

_No response_

### Would you like to submit a PR for this Issue?

None

### Support Needs

_No response_

### PR DESCRIPTION
**Pull request by guipublic**
# Description

## Problem

Resolves #10540

## User Documentation

Check one:
- [X] No user documentation needed.
- [ ] Changes in _docs/_ included in this PR.
- [ ] **[For Experimental Features]** Changes in _docs/_ to be submitted in a separate PR.

# PR Checklist

- [X] I have tested the changes locally.
- [X] I have formatted the changes with [Prettier](https://prettier.io/) and/or `cargo fmt` on default settings.

### CODE REVIEW

File: compiler/noirc_frontend/src/node_interner/methods.rs [hunk 1]
```diff
@@ -43,6 +47,116 @@ impl Methods {
...
+    pub(super) fn find_overlapping_method(
+        &self,
+        typ: &Type,
+        interner: &NodeInterner,
+    ) -> Option<(FuncId, Type)> {
+        for existing in &self.direct {
+            // Check if two types overlap, by instantiating both types (replacing NamedGenerics
+            // with fresh TypeVariables) and then checking if they can unify.
+            let instantiate_existing = Self::instantiate_named_generics(&existing.typ, interner);
+            let instantiate_typ = Self::instantiate_named_generics(typ, interner);
```
Comment (aakoshh) [inline compiler/noirc_frontend/src/node_interner/methods.rs]:
```suggestion
        if self.direct.is_empty() {
            return None;
        }
        let instantiate_typ = Self::instantiate_named_generics(typ, interner);
        for existing in &self.direct {
            // Check if two types overlap, by instantiating both types (replacing NamedGenerics
            // with fresh TypeVariables) and then checking if they can unify.
            let instantiate_existing = Self::instantiate_named_generics(&existing.typ, interner);            
```

File: compiler/noirc_frontend/src/node_interner/methods.rs [hunk 2]
```diff
@@ -43,6 +47,116 @@ impl Methods {
...
+    fn collect_named_generics(
+        typ: &Type,
+        result: &mut Vec<(TypeVariableId, crate::TypeVariable, Kind)>,
+        seen: &mut HashSet<TypeVariableId>,
+    ) {
+        match typ {
+            Type::NamedGeneric(NamedGeneric { type_var, .. }) => {
+                let id = type_var.id();
+                if !seen.contains(&id) {
+                    seen.insert(id);
```
Comment (aakoshh) [inline compiler/noirc_frontend/src/node_interner/methods.rs]:
```suggestion
                if !seen.insert(id) {
```

File: compiler/noirc_frontend/src/node_interner/methods.rs [hunk 3]
```diff
@@ -43,6 +47,116 @@ impl Methods {
...
+                Self::collect_named_generics(right, result, seen);
+            }
+            // These types don't contain NamedGenerics
+            Type::FieldElement
+            | Type::Integer(..)
+            | Type::Bool
+            | Type::Unit
+            | Type::Quoted(..)
+            | Type::Error
+            | Type::TypeVariable(..)
```
Comment (aakoshh) [inline compiler/noirc_frontend/src/node_interner/methods.rs]: I think I have seen a `TypeVariable` be bound to a `NamedGeneric`

File: compiler/noirc_frontend/src/node_interner/methods.rs [hunk 4]
```diff
@@ -43,6 +47,116 @@ impl Methods {
...
+        // Create substitutions from each NamedGeneric to a fresh type variable
+        let substitutions: TypeBindings = named_generics
+            .into_iter()
+            .map(|(id, type_var, kind)| {
+                let fresh = interner.next_type_variable_with_kind(kind.clone());
+                (id, (type_var, kind, fresh))
+            })
+            .collect();
+
+        typ.substitute(&substitutions)
```
Comment (aakoshh) [inline compiler/noirc_frontend/src/node_interner/methods.rs:101]: Just for my understanding: `substitute` does not actually _bind_ type variables in the `typ`, it _replaces_ the types that have them (`TypeVariable` and `NamedGeneric`) with the substitutions, so `NamedGeneric` itself is unchanged, right? 

If that's right, the docs of `substitute` could be made clearer.

File: compiler/noirc_frontend/src/node_interner/methods.rs (hunk 3 above)
Comment (aakoshh) [reply compiler/noirc_frontend/src/node_interner/methods.rs]: Can't explain it, but the example was here: https://github.com/noir-lang/noir/pull/11385#discussion_r2747518308

File: compiler/noirc_frontend/src/node_interner/methods.rs (hunk 4 above)
Comment (guipublic) [reply compiler/noirc_frontend/src/node_interner/methods.rs:101]: Yes that is correct. However, because `substitute` only use references (and no mutable reference), I think it is quite clear that it does not change anything.

File: compiler/noirc_frontend/src/node_interner/methods.rs (hunk 2 above)
Comment (guipublic) [reply compiler/noirc_frontend/src/node_interner/methods.rs]: Done, but I inverted the condition

File: compiler/noirc_frontend/src/node_interner/methods.rs (hunk 3 above)
Comment (guipublic) [reply compiler/noirc_frontend/src/node_interner/methods.rs]: Thank you, I have added this case.

File: compiler/noirc_frontend/src/node_interner/methods.rs (hunk 1 above)
Comment (guipublic) [reply compiler/noirc_frontend/src/node_interner/methods.rs]: Done

File: compiler/noirc_frontend/src/node_interner/methods.rs [hunk 5]
```diff
@@ -43,6 +47,122 @@ impl Methods {
...
+        interner: &NodeInterner,
+    ) -> Option<(FuncId, Type)> {
+        if self.direct.is_empty() {
+            return None;
+        }
+        let instantiate_typ = Self::instantiate_named_generics(typ, interner);
+        for existing in &self.direct {
+            // Check if two types overlap, by instantiating both types (replacing NamedGenerics
+            // with fresh TypeVariables) and then checking if they can unify.
+            let instantiate_existing = Self::instantiate_named_generics(&existing.typ, interner);
```
Comment (aakoshh) [inline compiler/noirc_frontend/src/node_interner/methods.rs]: There is a `Type::replace_named_generics_with_type_variables` method. Superficially it sounds like it's doing the same thing.

File: compiler/noirc_frontend/src/node_interner/methods.rs [hunk 6]
```diff
@@ -43,6 +47,122 @@ impl Methods {
...
+                let fresh = interner.next_type_variable_with_kind(kind.clone());
+                (id, (type_var, kind, fresh))
+            })
+            .collect();
+
+        typ.substitute(&substitutions)
+    }
+
+    /// Recursively collect all NamedGenerics from a type.
+    fn collect_named_generics(
```
Comment (aakoshh) [inline compiler/noirc_frontend/src/node_interner/methods.rs:105]: Ah, I was looking for this method, I didn't know where I saw it. 

FYI I added a `Type::visit` method in https://github.com/noir-lang/noir/pull/11417 which I'm using for almost the same thing as you are doing here.

File: compiler/noirc_frontend/src/node_interner/methods.rs [hunk 7]
```diff
@@ -43,6 +47,122 @@ impl Methods {
...
+            }
+            // These types don't contain NamedGenerics
+            Type::FieldElement
+            | Type::Integer(..)
+            | Type::Bool
+            | Type::Unit
+            | Type::Quoted(..)
+            | Type::Error
+            | Type::Constant(..)
+            | Type::TraitAsType(..) => {}
```
Comment (aakoshh) [inline compiler/noirc_frontend/src/node_interner/methods.rs]: In my `Type::visit` I included `TraitAsType` because `Type::replace_named_generics_with_type_variables` does it as well.

File: compiler/noirc_frontend/src/node_interner/methods.rs (hunk 5 above)
Comment (guipublic) [reply compiler/noirc_frontend/src/node_interner/methods.rs]: It's not clear if they do the same thing?

File: compiler/noirc_frontend/src/node_interner/methods.rs (hunk 7 above)
Comment (guipublic) [reply compiler/noirc_frontend/src/node_interner/methods.rs]: Interesting, but I'd rather have an exemple that shows that this is needed.

Comment (guipublic) [reply compiler/noirc_frontend/src/node_interner/methods.rs]: I added some tests that demonstrate TraitAsType behave properly.

File: compiler/noirc_frontend/src/node_interner/methods.rs (hunk 6 above)
Comment (guipublic) [reply compiler/noirc_frontend/src/node_interner/methods.rs:105]: done

File: compiler/noirc_frontend/src/node_interner/methods.rs [hunk 8]
```diff
@@ -43,6 +47,76 @@ impl Methods {
...
+            return None;
+        }
+        let instantiate_typ = Self::instantiate_named_generics(typ, interner);
+        for existing in &self.direct {
+            // Check if two types overlap, by instantiating both types (replacing NamedGenerics
+            // with fresh TypeVariables) and then checking if they can unify.
+            let instantiate_existing = Self::instantiate_named_generics(&existing.typ, interner);
+            let mut bindings = TypeBindings::default();
+            let types_can_unify =
+                instantiate_existing.try_unify(&instantiate_typ, &mut bindings).is_ok();
```
Comment (aakoshh) [inline compiler/noirc_frontend/src/node_interner/methods.rs:74]: I was looking for a `Type::can_unify` method, but curiously it doesn't exist, even though there definitely are some places where we don't use `bindings` afterwards. Maybe we should add it?

OTOH there was a `Methods::types_can_unify` method right here in this file, but it was removed in https://github.com/noir-lang/noir/pull/11636

File: compiler/noirc_frontend/src/node_interner/methods.rs (hunk 5 above)
Comment (asterite) [reply compiler/noirc_frontend/src/node_interner/methods.rs]: Instead of this we can do what I did in `method_matches`:

https://github.com/noir-lang/noir/blob/fa33ce4eb3f28fd2280c5cffb5862da69fb1a88f/compiler/noirc_frontend/src/node_interner/methods.rs#L129-L133

Essentially, `existing` has a `method: FuncId`. From it we can get the function and its generics, if it's a `Forall`, then we know the generics that appear in the function type must be those in the `Forall`. So there's no need to search for all named generics to replace.

File: compiler/noirc_frontend/src/node_interner/methods.rs [hunk 9]
```diff
@@ -43,6 +47,76 @@ impl Methods {
...
+            if types_can_unify {
+                return Some((existing.method, existing.typ.clone()));
+            }
+        }
+        None
+    }
+
+    /// Instantiate a type by finding all NamedGenerics and replacing them with
+    /// fresh type variables.
+    fn instantiate_named_generics(typ: &Type, interner: &NodeInterner) -> Type {
```
Comment (aakoshh) [inline compiler/noirc_frontend/src/node_interner/methods.rs]: I'd repeat what I said in https://github.com/noir-lang/noir/pull/11636/changes#r2872252282 

It's not clear what "instantiate" means: previously it seemed to be about `Forall`, but here we deal with any `NamedGenerics`. It's nice that it says so, but I wonder if we are incidentally muddying the meaning of "instantiate" in the process. It had a clear opposite in `generalize` as well. 

On top of this we have the `replace_named_generics_with_type_vars` as well, and it seems like a right mess where we have to read every single method to understand what exactly gets replaced.

File: compiler/noirc_frontend/src/node_interner/trait_impl.rs [hunk 10]
```diff
@@ -239,8 +232,9 @@ impl NodeInterner {
                 let existing_impl = existing_impl.borrow();
                 return Ok(Err(existing_impl.ident.location()));
             }
-            Ok((TraitImplKind::Prepared(impl_id), ..)) => {
-                unreachable!("ICE: Prepared should have been removed; found {impl_id:?}");
+            Ok((TraitImplKind::Prepared(_), ..)) => {
+                // A different Prepared impl matched — this is expected because
+                // prepared impls are placeholders and don't count as real overlap.
```
Comment (aakoshh) [inline compiler/noirc_frontend/src/node_interner/trait_impl.rs]: Prepared implementations have real IDs, they are precursors of what implementations will exist, and if they overlap then I'd have thought there was at least an error in my understanding of what I was trying to achieve.

Do you have an example of where overlaps happened?

File: compiler/noirc_frontend/src/tests/structs.rs [hunk 11]
```diff
@@ -91,10 +97,10 @@ fn check_impl_duplicate_method_without_self() {
 
     impl Foo {
         fn foo() {}
-           ~~~ first definition found here
+           ~~~ Previous impl defined here
         fn foo() {}
-           ^^^ duplicate definitions of foo found
-           ~~~ second definition found here
+           ^^^ Impl for type `Foo` overlaps with existing impl
+           ~~~ Overlapping impl
```
Comment (aakoshh) [inline compiler/noirc_frontend/src/tests/structs.rs:103]: In the `enum` test above, we preserved the "Duplicate definitions of enum variant with name Bar found" message, in addition to the "Impl for type `Foo` overlaps with existing impl", but here the "duplicate definitions of foo found" is gone. 

Can we keep it?

File: compiler/noirc_frontend/src/node_interner/trait_impl.rs (hunk 10 above)
Comment (aakoshh) [reply compiler/noirc_frontend/src/node_interner/trait_impl.rs]: The idea was that when we look up a trait implementation, we use the prepared ones to be able to find out what the associated types on them are going to be. The lookup mechanism was supposed to be as close as we can make it to the normal lookup, which is the one we will eventually find, so their types should match. 

The `existing` here is the result of a regular lookup, which we will perform everywhere else. If we can match a `Prepared` one that isn't the one we just removed, then I'd assume that after we add this normal one, if we repeated the lookup, it would fail with `MultipleMatching` due to finding a mix of normal and prepared implementations.

To put in in a different perspective: if we don't consider prepared implementation overlaps as "real" overlaps, then how could we tell which associated type to use?

Comment (guipublic) [reply compiler/noirc_frontend/src/node_interner/trait_impl.rs]: Yes, the example is one of the unit tests that I added. I think it is this one: `non_overlapping_trait_impls_with_generic()`

File: compiler/noirc_frontend/src/tests/structs.rs (hunk 11 above)
Comment (guipublic) [reply compiler/noirc_frontend/src/tests/structs.rs:103]: which other test are you talking about?

Comment (aakoshh) [reply compiler/noirc_frontend/src/tests/structs.rs:103]: Sorry, should have said;  it's `error_with_duplicate_enum_variant` in the file above this one.

File: compiler/noirc_frontend/src/node_interner/methods.rs (hunk 9 above)
Comment (guipublic) [reply compiler/noirc_frontend/src/node_interner/methods.rs]: It seems that this previous comment was not resolved?
I can't find `replace_named_generics_with_type_vars()`

Comment (aakoshh) [reply compiler/noirc_frontend/src/node_interner/methods.rs]: My bad, it wasn't the exact spelling:

https://github.com/noir-lang/noir/blob/703fc5c8f4eb017d75483544a572d3e2641b6281/compiler/noirc_frontend/src/hir_def/types.rs#L2956

File: compiler/noirc_frontend/src/node_interner/methods.rs (hunk 5 above)
Comment (guipublic) [reply compiler/noirc_frontend/src/node_interner/methods.rs]: I don't think it applies directly here, I am handling types, not `FuncId`.
In the following, I care about T, not U:
```
impl<T> Foo<T> {
    fn bar<U>(self, x: U) { ... }
}
```

File: compiler/noirc_frontend/src/tests/structs.rs [hunk 12]
```diff
@@ -390,3 +441,191 @@ fn deny_cyclic_structs() {
...
+    pub struct Bar<T, let N: u32> {}
+
+    impl<T> Foo for Bar<T, 0> { }
+    impl<T> Foo for Bar<T, 1> { }
+    impl<T, let N: u32> Foo for Bar<T, N> { }
+    impl Foo for Bar<(), 0> { }
+    impl<let N: u32> Foo for Bar<(), N> { }
+    "#;
+    assert_no_errors(src);
+}
```
Comment (aakoshh) [inline compiler/noirc_frontend/src/tests/structs.rs:637]: This code doesn't compile on Rust: https://play.rust-lang.org/?version=stable&mode=debug&edition=2024&gist=c11e6f97522ec8e1816de0e830cd30e1

```noir
impl<T> Foo for Bar<T, 0> { }
impl<T> Foo for Bar<T, 1> { }
```
These are fine, because the const generics are different.
```noir
impl<T, let N: u32> Foo for Bar<T, N> { }
```
This is in conflict with the two above: `N` matches `0` and `1` as well, so it's an overlap.
```noir
impl Foo for Bar<(), 0> { }
```
This is in conflict with the 1st one, because `T` unifies with `()`, and `0` is the same.
```noir
impl<let N: u32> Foo for Bar<(), N> { }
```
This is in conflict with both of them, because `T` unifies with `()` and `N` unifies with `0` and `1`.

If we add back this code then we get a panic, which is not nice, so maybe we should return an error instead, which isn't nice:
```noir
            Ok((TraitImplKind::Prepared(_), ..)) => {
                // A different Prepared impl matched — this is expected because
                // prepared impls are placeholders and don't count as real overlap.
                unreachable!("found prepared impl: {existing:?}");
            }
```
I reckon we should save the `Location` into the `Prepared` and then we can at least point out where a conflict is, similar to the `Normal` one.

File: compiler/noirc_frontend/src/tests/structs.rs [hunk 13]
```diff
@@ -390,3 +441,191 @@ fn deny_cyclic_structs() {
...
+            let _ = self;
+        }
+    }
+
+    type Bar<T> = T;
+
+    impl<T> Foo for T { }
+    impl<T> Foo for Bar<T> { }
+    "#;
+    assert_no_errors(src);
```
Comment (aakoshh) [inline compiler/noirc_frontend/src/tests/structs.rs:610]: This doesn't compile in Rust.

Comment (aakoshh) [reply compiler/noirc_frontend/src/tests/structs.rs:610]: And I mean due to the overlap: basically it is equivalent to having `impl<T> Foo for T { }` twice.

File: compiler/noirc_frontend/src/tests/structs.rs (hunk 12 above)
Comment (aakoshh) [reply compiler/noirc_frontend/src/tests/structs.rs:637]: I'll try to make this change and push here.

Comment (aakoshh) [reply compiler/noirc_frontend/src/tests/structs.rs:637]: Pushed. I'm still trying to figure out why I just return in `add_prepared_trait_implementation` when there is an overlap instead of returning an error. 

It doesn't solve the `type_alias_resolves_to_same_type_in_trait_impl` though

Comment (aakoshh) [reply compiler/noirc_frontend/src/tests/structs.rs:637]: > I'm still trying to figure out why I just return in add_prepared_trait_implementation when there is an overlap instead of returning an error.

I don't actually know. I suppose because `prepare_trait_impl_for_function_meta_definition` doesn't return a `Result`, but it could still register an error. But if I change it to push to the vector anyway, then even the errors we have today disappear.

File: compiler/noirc_frontend/src/tests/structs.rs (hunk 13 above)
Comment (aakoshh) [reply compiler/noirc_frontend/src/tests/structs.rs:610]: Right, I checked why this doesn't get rejected: it is because `lookup_trait_implementation` return an `Err` if the `object_type` is _bindable_, which `Bar<T>` is, which `add_trait_implementation` ignores, so even if we literally repeat `impl<T> Foo for Bar<T> { }` multiple times, it won't reject it. I'll create a bug ticket for this.

What was the goal of this test by the way? As I understand your check only looks for direct implementations, which `foo` is not?

File: compiler/noirc_frontend/src/tests/structs.rs (hunk 12 above)
Comment (aakoshh) [reply compiler/noirc_frontend/src/tests/structs.rs:637]: So the reason this does not compile is because `Bar<(), 0>` is _not_ bindable, so for this we do get a conflict with the trait implementation registered for `Bar<T, 0>`. 

But now I understand you weren't even trying to match these. Still I think my change here makes sense: if we match multiple prepared implementations, we might as well report them as an error. Shame that if both types are generics then they won't be reported at the moment.

File: compiler/noirc_frontend/src/tests/structs.rs (hunk 13 above)
Comment (aakoshh) [reply compiler/noirc_frontend/src/tests/structs.rs:610]: You could add a test for aliases and direct methods.

File: compiler/noirc_frontend/src/node_interner/methods.rs (hunk 9 above)
Comment (guipublic) [reply compiler/noirc_frontend/src/node_interner/methods.rs]: These functions do different things, `replace_named_generics_with_type_variables()` mutates the type in-place, to get the monomorphised types and does not create fresh variables.
`instantiate_named_generics()` does not modify the type and copy it with new type variables, using unification to find overlap.

File: compiler/noirc_frontend/src/tests/structs.rs (hunk 11 above)
Comment (guipublic) [reply compiler/noirc_frontend/src/tests/structs.rs:103]: Thank you, the duplicate error in error_with_duplicate_enum_variant() is a different check, done elsewhere (def collection), so I am not sure what is the impact to remove it. May be we can create an issue if we want to remove it.
In check_impl_duplicate_method_without_self(), the previous check has been replaced by the overlapping check, which subsumes it. I think it is better to have only one error

File: compiler/noirc_frontend/src/node_interner/methods.rs (hunk 9 above)
Comment (aakoshh) [reply compiler/noirc_frontend/src/node_interner/methods.rs]: I know, what I was trying to point out is that it is very hard to have an idea what they will do based on their names. I thought `instantiate` deals with `Forall`. I merely wanted to make an observation that it's hard to come up with a good name because e.g. `replace_named_generics_with_type_variables` sounded similar, but it's different, so maybe this one is `replace_named_generics_with_fresh_type_variables` then? 

@asterite renamed the one's he added to `self_type.substitute_type_vars_with_fresh_type_vars` in https://github.com/noir-lang/noir/pull/11729 so we don't clash on `instantiate`

File: compiler/noirc_frontend/src/tests/structs.rs (hunk 13 above)
Comment (aakoshh) [reply compiler/noirc_frontend/src/tests/structs.rs:610]: https://github.com/noir-lang/noir/issues/11730

File: compiler/noirc_frontend/src/tests/structs.rs (hunk 12 above)
Comment (guipublic) [reply compiler/noirc_frontend/src/tests/structs.rs:637]: There is no panic currently. The overlapping check allows these cases, but they will be catch because each implementation will unify to the same type.
I think the behaviour is fine.

File: compiler/noirc_frontend/src/node_interner/trait_impl.rs (hunk 10 above)
Comment (aakoshh) [reply compiler/noirc_frontend/src/node_interner/trait_impl.rs]: I pushed a change to this, in relation to the above test.

File: compiler/noirc_frontend/src/tests/structs.rs (hunk 12 above)
Comment (aakoshh) [reply compiler/noirc_frontend/src/tests/structs.rs:637]: Right, what I meant was that there was a panic with the `unimplemented!` in place. There isn't one now, but to be clear I changed what was `unimplemented!` before to return an `Err` instead, so the duplicate is caught early. This is different from your change which allowed it to compile. 

If you believe the current behaviour of showing an error is fine, then great, I agree!

Comment (guipublic) [reply compiler/noirc_frontend/src/tests/structs.rs:637]: It's included in the issue you linked, so I am closing this.
If returning an Error works in all cases, then  it's perfect.
If not, if the current behaviour is sound, which it seems so (you get a compilation error using the overlapping types), then it's acceptable.
For the rest, there is the issue.

File: compiler/noirc_frontend/src/node_interner/methods.rs (hunk 9 above)
Comment (guipublic) [reply compiler/noirc_frontend/src/node_interner/methods.rs]: I renamed it in a similar way.

File: compiler/noirc_frontend/src/node_interner/methods.rs (hunk 5 above)
Comment (asterite) [reply compiler/noirc_frontend/src/node_interner/methods.rs]: Right, but both `T` and `U` will appear in the forall of the function. I'll try to do this in a follow-up (it's optional, we can reject it if it's not desired).
