### PR TITLE
fix: handle large arrays in the monomorphiser and limit their length

### LINKED ISSUE #11173: Unbounded array allocation with repeated array syntax kills process
### Aim

Take a program with a massive array like such:
```noir
fn main() {
    // 1.3 billion elements 
    let _arr: [Field; 1294967295] = [0; 1294967295];
}
```

### Expected Behavior

I would expect the compiler to fail gracefully with an error rather than crashing. We should not rely on the OS for termination.  

### Bug

The process was killed with `zsh: killed     nargo compile --force`. This is most likely due to being OOM. This test was run on my local machine which has 48GB. Machines with less memory would be expected to fail at much smaller array sizes. 

I also added debug statements that showed us going into monomorphization. This looks to be happening due to our desugaring of the repeated array syntax in monomorphization: https://github.com/noir-lang/noir/blob/2c2a7b8fd4aff6fe1591b90a7f276cbf71ac3eb0/compiler/noirc_frontend/src/monomorphization/mod.rs#L938

The majority of times the compiler is run in a trusted environment, but this is a DoS vector that can be triggered in one line. 

### To Reproduce

1. Run the test above using `nargo`. 

### Workaround

None

### Workaround Description

_No response_

### Additional Context

_No response_

### Project Impact

None

### Blocker Context

_No response_

### Nargo Version

nargo version = 1.0.0-beta.17 noirc version = 1.0.0-beta.17+c2b99a8593d70abda260c91ca51a69ff8e10ca2d (git version hash: c2b99a8593d70abda260c91ca51a69ff8e10ca2d, is dirty: false)

### NoirJS Version

_No response_

### Proving Backend Tooling & Version

_No response_

### Would you like to submit a PR for this Issue?

None

### Support Needs

_No response_

### PR DESCRIPTION
**Pull request by guipublic**
# Description

## Problem

Resolves #11173 and #10524
It also address part of #10522, but we should still add error handling in brillig generation.

## Summary
A safe limit has been added in acir_gen to error on very large arrays.
The monomorphizer avoids creating repeated elements in an array.

## User Documentation

Check one:
- [X] No user documentation needed.
- [ ] Changes in _docs/_ included in this PR.
- [ ] **[For Experimental Features]** Changes in _docs/_ to be submitted in a separate PR.

# PR Checklist

- [X] I have tested the changes locally.
- [X] I have formatted the changes with [Prettier](https://prettier.io/) and/or `cargo fmt` on default settings.

### CODE REVIEW

File: compiler/noirc_evaluator/src/brillig/brillig_ir/codegen_control_flow.rs [hunk 1]
```diff
@@ -22,6 +22,18 @@ use super::{
     registers::RegisterAllocator,
 };
 
+/// Computes the size of a parameter if it was flattened
+pub(crate) fn flattened_size(param: &BrilligParameter) -> usize {
```
Comment (vezenovm) [inline compiler/noirc_evaluator/src/brillig/brillig_ir/codegen_control_flow.rs]: nit: could put this method on BrilligParameter

File: compiler/noirc_evaluator/src/acir/mod.rs [hunk 2]
```diff
@@ -284,6 +305,25 @@ impl<'a> Context<'a> {
...
+            .map(|result_id| dfg.type_of_value(*result_id).flattened_size().to_usize())
+            .sum();
+        if num_return_values > MAX_ELEMENTS {
+            let entry_block = &dfg[main_func.entry_block()];
+            let call_stack_id = match entry_block.unwrap_terminator() {
+                TerminatorInstruction::Return { call_stack, .. } => *call_stack,
+                _ => unreachable!("ICE: expected return terminator"),
+            };
+            let call_stack = dfg.call_stack_data.get_call_stack(call_stack_id);
+            return Err(RuntimeError::ReturnWitnessLimitExceeded {
```
Comment (vezenovm) [inline compiler/noirc_evaluator/src/acir/mod.rs]: nit: This error feels like it may be confusing to users. It will mention "witnesses" when we are in an unconstrained environment. We probably want a different error here. Or should we just generalize this error to say "return value limit of ... has been hit".

File: compiler/noirc_evaluator/src/brillig/brillig_gen.rs [hunk 3]
```diff
@@ -46,7 +51,27 @@ pub(crate) fn gen_brillig_for(
...
+    // each element in the return arrays.
+    let num_return_witnesses: usize = return_parameters.iter().map(flattened_size).sum();
+    if num_return_witnesses > MAX_ELEMENTS {
+        let entry_block = &func.dfg[func.entry_block()];
+        let call_stack_id = match entry_block.unwrap_terminator() {
+            TerminatorInstruction::Return { call_stack, .. } => *call_stack,
+            _ => unreachable!("ICE: expected return terminator"),
+        };
+        let call_stack = func.dfg.call_stack_data.get_call_stack(call_stack_id);
+        return Err(RuntimeError::ReturnWitnessLimitExceeded {
```
Comment (vezenovm) [inline compiler/noirc_evaluator/src/brillig/brillig_gen.rs]: Same as https://github.com/noir-lang/noir/pull/11279/changes#r2713156530

File: compiler/noirc_evaluator/src/brillig/brillig_gen.rs [hunk 4]
```diff
@@ -46,7 +51,27 @@ pub(crate) fn gen_brillig_for(
...
-) -> Result<GeneratedBrillig<FieldElement>, InternalError> {
+) -> Result<GeneratedBrillig<FieldElement>, RuntimeError> {
+    let return_parameters = FunctionContext::return_values(func);
+
+    // Check if the return value size exceeds the limit before generating the entry point.
+    // This is done early to avoid the expensive entry point codegen which iterates over
+    // each element in the return arrays.
+    let num_return_witnesses: usize = return_parameters.iter().map(flattened_size).sum();
+    if num_return_witnesses > MAX_ELEMENTS {
+        let entry_block = &func.dfg[func.entry_block()];
```
Comment (vezenovm) [inline compiler/noirc_evaluator/src/brillig/brillig_gen.rs]: It looks like this could possibly be placed in a helper with the check in ACIR gen

File: tooling/nargo_cli/tests/snapshots/compile_failure/regression_10524/execute__tests__stderr.snap [hunk 5]
```diff
@@ -0,0 +1,16 @@
+---
+source: tooling/nargo_cli/tests/execute.rs
+expression: stderr
+---
+error: The return value has 4294967294 witnesses which exceeds the limit of 16777216
```
Comment (vezenovm) [inline tooling/nargo_cli/tests/snapshots/compile_failure/regression_10524/execute__tests__stderr.snap]: So we can declare the type, but cannot return the type? This feels like it may confuse users as they may have a type declared with no issue and then once they use the type they start getting an error. I think it would be better to error on the type itself. Wdyt @jfecher?

File: compiler/noirc_evaluator/src/ssa/ssa_gen/mod.rs [hunk 6]
```diff
@@ -281,6 +281,21 @@ impl FunctionContext<'_> {
                     _ => unreachable!("ICE: unexpected vector literal type, got {}", array.typ),
                 })
             }
+            ast::Literal::Repeated { element, length, is_vector, typ } => {
```
Comment (aakoshh) [inline compiler/noirc_evaluator/src/ssa/ssa_gen/mod.rs:284]: Is this `length` already checked somewhere?

File: compiler/noirc_frontend/src/monomorphization/mod.rs [hunk 7]
```diff
@@ -923,43 +923,14 @@ impl<'interner> Monomorphizer<'interner> {
...
-            let ident =
-                ast::Ident { location: Some(location), definition, mutable: false, name, typ, id };
-            ast::Expression::Ident(ident)
-        });
-        let array = if is_vector {
-            ast::Expression::Literal(ast::Literal::Vector(ast::ArrayLiteral { contents, typ }))
-        } else {
-            ast::Expression::Literal(ast::Literal::Array(ast::ArrayLiteral { contents, typ }))
-        };
-        Ok(ast::Expression::Block(vec![let_expr, array]))
```
Comment (aakoshh) [inline compiler/noirc_frontend/src/monomorphization/mod.rs:997]: So now instead of creating variable with the expression, and then N references to it in an array, we do the same thing in SSA. As I understand the only reason you do this is to save the memory required by the the N `Ident` instances, right?

File: compiler/noirc_frontend/src/monomorphization/ast.rs [hunk 8]
```diff
@@ -268,6 +269,14 @@ pub struct While {
...
     Array(ArrayLiteral),
     Vector(ArrayLiteral),
+    /// A repeated array like `[expr; N]` where the element is repeated N times.
+    /// This avoids creating N copies of the element expression in memory.
+    Repeated {
+        element: Box<Expression>,
+        length: u32,
+        is_vector: bool,
+        typ: Type,
+    },
```
Comment (aakoshh) [inline compiler/noirc_frontend/src/monomorphization/ast.rs:280]: It would be nice to add this to the AST fuzzer [here](https://github.com/noir-lang/noir/blob/bb296ffb0711bac26d801882ca0932da530923dc/tooling/ast_fuzzer/src/program/func.rs#L579) and [here](https://github.com/noir-lang/noir/blob/bb296ffb0711bac26d801882ca0932da530923dc/tooling/ast_fuzzer/src/program/expr.rs#L91-L105)

File: compiler/noirc_frontend/src/monomorphization/tests.rs [hunk 9]
```diff
@@ -636,10 +636,7 @@ fn repeated_array() {
     let program = get_monomorphized(src).unwrap();
     insta::assert_snapshot!(program, @r"
     fn main$f0() -> () {
-        let _a$l1 = {
-            let repeated_element$l0 = (1 + 2);
-            [repeated_element$l0, repeated_element$l0, repeated_element$l0]
```
Comment (aakoshh) [inline compiler/noirc_frontend/src/monomorphization/tests.rs:661]: I wonder if this change could have any effect on ownership. 

If we look at this program, it inserts clones:
```noir
unconstrained fn main() {
    let a = [1, 2];
    let _ = [a; 3];
}
```

```console
❯ cargo run -q -p nargo_cli -- compile --force --show-monomorphized --show-ssa-pass Initial

unconstrained fn main$f0() -> () {
    let a$l0 = [1, 2];
    let _$l2 = {
        let repeated_element$l1 = a$l0;
        [repeated_element$l1.clone(), repeated_element$l1.clone(), repeated_element$l1]
    }
}

After Initial SSA:
brillig(inline) fn main f0 {
  b0():
    v2 = make_array [Field 1, Field 2] : [Field; 2]
    inc_rc v2
    inc_rc v2
    v3 = make_array [v2, v2, v2] : [[Field; 2]; 3]
    return
}
```

I think in the new `ssa_gen` for `Repeated` the `inc_rc` will be missing.

File: compiler/noirc_evaluator/src/acir/mod.rs (hunk 2 above)
Comment (guipublic) [reply compiler/noirc_evaluator/src/acir/mod.rs]: Done, I replaced 'witness' by 'elements' in the error message.

File: compiler/noirc_evaluator/src/brillig/brillig_gen.rs (hunk 4 above)
Comment (guipublic) [reply compiler/noirc_evaluator/src/brillig/brillig_gen.rs]: Done

File: compiler/noirc_evaluator/src/brillig/brillig_ir/codegen_control_flow.rs (hunk 1 above)
Comment (guipublic) [reply compiler/noirc_evaluator/src/brillig/brillig_ir/codegen_control_flow.rs]: Done

File: compiler/noirc_evaluator/src/brillig/brillig_gen.rs (hunk 3 above)
Comment (guipublic) [reply compiler/noirc_evaluator/src/brillig/brillig_gen.rs]: Done

File: compiler/noirc_evaluator/src/ssa/ssa_gen/mod.rs (hunk 6 above)
Comment (guipublic) [reply compiler/noirc_evaluator/src/ssa/ssa_gen/mod.rs:284]: Yes, the check is done when returning values from the program.

File: compiler/noirc_frontend/src/monomorphization/mod.rs (hunk 7 above)
Comment (guipublic) [reply compiler/noirc_frontend/src/monomorphization/mod.rs:997]: Yes, creating a big array was failing in the monomorphiser, now it works in the monomorphiser, and SSA is able to handle the arrays, at least for the examples of the issues.
The problem is now with ACIR generation, where I added a conservative limit for what is returned.

File: compiler/noirc_frontend/src/monomorphization/ast.rs (hunk 8 above)
Comment (guipublic) [reply compiler/noirc_frontend/src/monomorphization/ast.rs:280]: Done

File: compiler/noirc_evaluator/src/ssa/ssa_gen/mod.rs (hunk 6 above)
Comment (aakoshh) [reply compiler/noirc_evaluator/src/ssa/ssa_gen/mod.rs:284]: I saw that, but what if the values are not returned, but just used internally? For example:
```noir
fn main(i: u32) -> pub Field {
  let a = [1 + 2; 9999999999999999];
  a[i]
}
```
I thought maybe it would reject it simply based on the fact that this array is too large.

Comment (aakoshh) [reply compiler/noirc_evaluator/src/ssa/ssa_gen/mod.rs:284]: Maybe I got the wrong impression, I thought it's a general language feature, but as I understand now it's more about the number of witnesses, so in Brillig we may get away with something that in ACIR we cannot.

File: compiler/noirc_frontend/src/monomorphization/tests.rs (hunk 9 above)
Comment (guipublic) [reply compiler/noirc_frontend/src/monomorphization/tests.rs:661]: Done: I have added clones when the repeated array contains arrays.

Comment (aakoshh) [reply compiler/noirc_frontend/src/monomorphization/tests.rs:661]: Cool; I tried to come up in my head with something that could exploit there not being any increment, but haven't found an obvious attack. I thought that whatever wants to modify a sub-array would have to either get it first, at which point it get cloned again, or assign with a sub-index in the lvalue, where clones are also inserted, so I'm not sure if it was unsafe, but as a piece of mind it's better to have it I suppose.

File: compiler/noirc_frontend/src/ownership/tests.rs [hunk 10]
```diff
@@ -493,3 +493,58 @@ fn dereference_immutable_reference() {
...
+
+    fn use_var<T>(_x: T) {}
+    ";
+
+    let program = get_monomorphized(src).unwrap();
+    // `a` should be cloned twice (for the 2nd and 3rd elements)
+    insta::assert_snapshot!(program, @r"
+    unconstrained fn main$f0() -> () {
+        let a$l0 = [1, 2];
+        let b$l1 = [a$l0.clone().clone(); 3];
```
Comment (aakoshh) [inline compiler/noirc_frontend/src/ownership/tests.rs]: I'm surprised you opted for this, rather than handling it in the SSA. It seems strange to introduce a new AST to capture repeated expressions, and delay their turning into multiple elements until the SSA so that the AST doesn't have N occurrences of `Ident` nodes, and then to insert N `Clone` nodes anyway. 

I was wondering how this will potentially affect https://github.com/noir-lang/noir/pull/11124 where I unwrap 1 layer of `Clone`, but didn't expect it to be nested. It looks like it wouldn't interact with that as this isn't a call argument.

File: compiler/noirc_frontend/src/monomorphization/tests.rs [hunk 11]
```diff
@@ -1337,3 +1331,14 @@ fn out_of_order_globals() {
     }
     ");
 }
+
+#[test]
+fn very_large_array() {
+    let src = r#"
+    fn main() {
+        // 1.3 billion elements 
+        let _arr: [Field; 1294967295] = [0; 1294967295];
```
Comment (aakoshh) [inline compiler/noirc_frontend/src/monomorphization/tests.rs:1360]: If you change this into something like `[[0]; 1294967295]`, would it be happy with the number of `Clone`s inserted?

File: compiler/noirc_frontend/src/ownership/tests.rs (hunk 10 above)
Comment (guipublic) [reply compiler/noirc_frontend/src/ownership/tests.rs]: It's easy to handle it in SSA, but I wanted to keep this inside the ownership pass. However I see your point, and may be it is cleaner to do it in SSA, where the repeated is handled. I'll do it.

Comment (guipublic) [reply compiler/noirc_frontend/src/ownership/tests.rs]: Done

File: compiler/noirc_frontend/src/monomorphization/tests.rs (hunk 11 above)
Comment (guipublic) [reply compiler/noirc_frontend/src/monomorphization/tests.rs:1360]: not relevant anymore now that the clones are not inserted for Repeated array.

File: compiler/noirc_evaluator/src/ssa/ir/dfg.rs [hunk 12]
```diff
@@ -853,6 +862,31 @@ impl DataFlowGraph {
         let results = self.instruction_results(instruction_id);
         results.contains(&return_data)
     }
+
+    /// Computes the number of flattened values returned by the SSA terminator
+    /// Error if it exceeds MAX_ELEMENTS
```
Comment (aakoshh) [inline compiler/noirc_evaluator/src/ssa/ir/dfg.rs]:
```suggestion
    /// Computes the number of flattened values returned by the SSA terminator.
    /// 
    /// Returns [RuntimeError::ReturnLimitExceeded] if it exceeds [MAX_ELEMENTS].
```
Not sure about the proper formatting, but I thought it would be nice to give the reader a link to the value.

File: compiler/noirc_evaluator/src/ssa/ssa_gen/mod.rs [hunk 13]
```diff
@@ -281,6 +281,34 @@ impl FunctionContext<'_> {
...
+                }
+
+                let elements: Vec<_> =
+                    std::iter::repeat(element_value).take(*length as usize).collect();
+
+                let converted_typ = Self::convert_type(typ).flatten();
+                if *is_vector {
+                    let vector_length = self.builder.length_constant(u128::from(*length));
+                    let vector_contents =
+                        self.codegen_array_checked(elements, converted_typ[1].clone())?;
```
Comment (aakoshh) [inline compiler/noirc_evaluator/src/ssa/ssa_gen/mod.rs]: Do we need these `converted_typ[?].clone()`? Can we not take the items, since we don't use the vector any more?

**Review by aakoshh — APPROVED** [review]
LGTM!

File: tooling/nargo_cli/tests/snapshots/compile_failure/regression_10524/execute__tests__stderr.snap (hunk 5 above)
Comment (vezenovm) [reply tooling/nargo_cli/tests/snapshots/compile_failure/regression_10524/execute__tests__stderr.snap]: On second thought this is fine. You should be able to declare the type and use it in code if you are not going to return it. Otherwise, it feels like an arbitrary restriction on the type.

File: compiler/noirc_evaluator/src/ssa/ssa_gen/mod.rs (hunk 13 above)
Comment (guipublic) [reply compiler/noirc_evaluator/src/ssa/ssa_gen/mod.rs]: Done

File: compiler/noirc_evaluator/src/ssa/ir/dfg.rs (hunk 12 above)
Comment (guipublic) [reply compiler/noirc_evaluator/src/ssa/ir/dfg.rs]: Done

**Comment by vezenovm** [comment]
> `private-kernel-reset`	`453.66` MB	`306.98` MB	`1.48`
> `rollup-checkpoint-root-single-block`	`11290` MB	`1750` MB	`6.45`
> `rollup-checkpoint-root`	`11300` MB	`1750` MB	`6.46`
> `rollup-tx-base-private`	`994.05` MB	`525.96` MB	`1.89`
> `rollup-tx-base-public`	`3030` MB	`467.15` MB	`6.49`
> `sha512_100_bytes`	`186.09` MB	`72.48` MB	`2.57`

I added `bench-show` as these alerts show some large degradations. Could you push a commit to force the benchmarks to run?
