### PR TITLE
fix(comptime): Validate that radix decomposition fits in the specified limbs

### LINKED ISSUE #10625: Bits and byte decomposition missing output size validation
### Aim

I wanted to run the following Noir code:
```noir
fn main() -> pub [u1; 1] {
    comptime {
        let large_number: Field = 2;
        large_number.to_be_bits::<1>()
    }
}
```
and its counterpart:
```noir
fn main() -> pub [u8; 1] {
    comptime {
        let large_number: Field = 256;
        large_number.to_be_bytes::<1>()
    }
}
```

### Expected Behavior

I would expect both to fail with `error: Assertion failed: Field failed to decompose into specified 1 limbs`. This is what occurs if you take away the comptime block.

### Bug

The program succeeds execution. 

### To Reproduce

1. Run `nargo execute --force-compile` on the programs above

### Workaround

None

### Workaround Description

_No response_

### Additional Context

_No response_

### Project Impact

Nice-to-have

### Blocker Context

_No response_

### Nargo Version

nargo version = 1.0.0-beta.15 noirc version = 1.0.0-beta.15+1a930357477fc0c210dc5a8960680282d4cfa24e (git version hash: 1a930357477fc0c210dc5a8960680282d4cfa24e, is dirty: true)

### NoirJS Version

_No response_

### Proving Backend Tooling & Version

_No response_

### Would you like to submit a PR for this Issue?

None

### Support Needs

_No response_

### PR DESCRIPTION
**Pull request by vezenovm**
# Description

## Problem

Resolves #10625 

## Summary

Adds the same check that we have in our ACIR and Brillig runtimes. Now `invalid_comptime_bits_decomposition` and `invalid_comptime_bytes_decomposition` fail with the following:
```
error: Field failed to decompose into specified 1 limbs
    ┌─ std/field/mod.nr:175:9
    │
175 │         __to_be_radix(self, radix)
    │         -------------------------- Assertion failed
    │
    = Call stack:
      1. src/main.nr:1:4
      2. src/main.nr:3:5
      3. std/field/mod.nr:138:21
      4. std/field/mod.nr:175:9
```

## User Documentation

Check one:
- [X] No user documentation needed.
- [ ] Changes in _docs/_ included in this PR.
- [ ] **[For Experimental Features]** Changes in _docs/_ to be submitted in a separate PR.

# PR Checklist

- [X] I have tested the changes locally.
- [X] I have formatted the changes with [Prettier](https://prettier.io/) and/or `cargo fmt` on default settings.

### CODE REVIEW

File: tooling/nargo_cli/build.rs [hunk 1]
```diff
@@ -153,11 +153,7 @@ const IGNORED_COMPTIME_INTERPRET_EXECUTION_TESTS: [&str; 11] = [
     "regression_7323",
 ];
 
-const IGNORED_COMPTIME_INTERPRET_EXECUTION_FAILURE_TESTS: [&str; 2] = [
-    // TODO(https://github.com/noir-lang/noir/issues/10625): Bits and byte decomposition does not validate output size in comptime
-    "invalid_comptime_bits_decomposition",
-    "invalid_comptime_bytes_decomposition",
-];
+const IGNORED_COMPTIME_INTERPRET_EXECUTION_FAILURE_TESTS: [&str; 0] = [];
```
Comment (vezenovm) [inline tooling/nargo_cli/build.rs:156]: I chose to leave this in while we continue on auditing as we may want to add failing tests, but I can take it out if we feel it is pointless.

File: compiler/noirc_frontend/src/hir/comptime/interpreter/builtin.rs
Comment (asterite) [inline compiler/noirc_frontend/src/hir/comptime/interpreter/builtin.rs:1025]: Now that we check that `limb_count_size < decomposed_integer.len()` I think `get` should always succeed, so we can simplify this to:

```suggestion
    let decomposed_integer = vecmap(&decomposed_integer[0..limb_count_usize], |&digit| {
        // The only built-ins that use these either return `[u1; N]` or `[u8; N]`
        if return_type_is_bits { Value::U1(digit != 0) } else { Value::U8(digit) }
    });
```

Comment (TomAFrench) [reply compiler/noirc_frontend/src/hir/comptime/interpreter/builtin.rs:1025]: @vezenovm can you take a quick look at this and then we can get this PR merged?

Comment (vezenovm) [reply compiler/noirc_frontend/src/hir/comptime/interpreter/builtin.rs:1025]: We only return early if `limb_count_size` is less than `decomposed_integer.len()`. If `limb_count_size` is 32 and `decomposed_integer.len()` is 4, get would return None.

Comment (asterite) [reply compiler/noirc_frontend/src/hir/comptime/interpreter/builtin.rs:1025]: Aaah... you are right, I read the comparison inverted somehow. I missed that if `limb_count_size` is greater than the actual bit size then we fill the remaining bytes with zero.
