### PR TITLE
fix: improve error message when failing to save program/contract

### LINKED ISSUE #11315: Failed to save contract panic
### Aim

Tried to call `nargo e` in `aztec-packages/noir-projects/noir-contracts/contracts/app/lending_contract`

### Expected Behavior

A user-facing success or error

### Bug

The compile command panics:
```
$ nargo e --force
The application panicked (crashed).
Message:  failed to save contract: FilesystemError(IoError(Os { code: 13, kind: PermissionDenied, message: "Permission denied" }))
Location: tooling/nargo_cli/src/cli/compile_cmd.rs:302
```

### To Reproduce

1.
2.
3.
4.

### Workaround

None

### Workaround Description

_No response_

### Additional Context

_No response_

### Project Impact

None

### Blocker Context

_No response_

### Nargo Version

_No response_

### NoirJS Version

_No response_

### Proving Backend Tooling & Version

_No response_

### Would you like to submit a PR for this Issue?

None

### Support Needs

_No response_

### PR DESCRIPTION
**Pull request by asterite**
# Description

## Problem

Resolves #11315

## Summary

Doesn't panic anymore, and handles this errors more gracefully.

Now when a program can't be saved you get:

```
Failed to save program 'one':
Failed to write file '/Users/asterite/Sandbox/one/target/one.json':
Permission denied (os error 13)
```

When a contract can't be saved:

```
Failed to save contract 'ecdsa_k_account_contract-EcdsaKAccount':
Failed to write file '/Users/asterite/Projects/aztec-packages/noir-projects/noir-contracts/target/ecdsa_k_account_contract-EcdsaKAccount.json':
Permission denied (os error 13)
```

## User Documentation

Check one:
- [x] No user documentation needed.
- [ ] Changes in _docs/_ included in this PR.
- [ ] **[For Experimental Features]** Changes in _docs/_ to be submitted in a separate PR.

# PR Checklist

- [x] I have tested the changes locally.
- [x] I have formatted the changes with [Prettier](https://prettier.io/) and/or `cargo fmt` on default settings.

### CODE REVIEW

File: tooling/artifact_cli/src/errors.rs [hunk 1]
```diff
@@ -28,8 +28,14 @@ pub enum FilesystemError {
...
 
-    #[error(transparent)]
-    IoError(#[from] std::io::Error),
+    #[error("Failed to read file '{0}':\n{1}")]
+    FailedToReadFile(PathBuf, std::io::Error),
+
+    #[error("Failed to write file '{0}':\n{1}")]
+    FailedToWriteFile(PathBuf, std::io::Error),
+
+    #[error("Failed to creator directory '{0}':\n{1}")]
```
Comment (aakoshh) [inline tooling/artifact_cli/src/errors.rs]:
```suggestion
    #[error("Failed to create directory '{0}':\n{1}")]
```

**Review by aakoshh — APPROVED** [review]
👍
