### PR TITLE
fix: slice push_back when length is not known

### LINKED ISSUE #10170: bug(ACIR): repeated slice push_back/pop_back constantly increases slice length and leads to incorrect results
### Aim

Take a look at this test that currently passes (which doesn't exist, but we can write it):

```noir
#[test]
fn slice_push_back_and_pop_front() {
    let src = "
    acir(inline) predicate_pure fn main f0 {
      b0(v0: u32, v1: u32):
        v3 = make_array [Field 2, Field 3] : [Field]
        v5 = array_set v3, index v0, value Field 4

        v8, v9 = call slice_push_back(u32 2, v5, Field 5) -> (u32, [Field])
        v11 = array_set v9, index v0, value Field 6

        v12, v13, v14 = call slice_pop_back(u32 3, v11) -> (u32, [Field], Field)
        v15 = array_set v13, index v0, value Field 7
        
        v16, v17 = call slice_push_back(u32 2, v15, Field 8) -> (u32, [Field])
        v18 = array_set v17, index v0, value Field 9

        v19, v20, v21 = call slice_pop_back(u32 3, v18) -> (u32, [Field], Field)
        v22 = array_set v20, index v0, value Field 10

        v23, v24 = call slice_push_back(u32 2, v22, Field 11) -> (u32, [Field])
        v25 = array_set v24, index v0, value Field 11
        
        return
    }
    ";
    let program = ssa_to_acir_program(src);

    assert_circuit_snapshot!(program, @r"
    func 0
    private parameters: [w0, w1]
    public parameters: []
    return values: []
    BLACKBOX::RANGE input: w1, bits: 32
    ASSERT w2 = 2
    ASSERT w3 = 3
    INIT b1 = [w2, w3]
    ASSERT w4 = 4
    WRITE b1[w0] = w4
    ASSERT w5 = 0
    READ w6 = b1[w5]
    ASSERT w7 = 1
    READ w8 = b1[w7]
    ASSERT w9 = 5
    INIT b3 = [w6, w8, w9]
    ASSERT w10 = 6
    WRITE b3[w0] = w10
    READ w11 = b3[w2]
    READ w12 = b3[w5]
    READ w13 = b3[w7]
    READ w14 = b3[w2]
    INIT b5 = [w12, w13, w14]
    ASSERT w15 = 7
    WRITE b5[w0] = w15
    READ w16 = b5[w5]
    READ w17 = b5[w7]
    READ w18 = b5[w2]
    ASSERT w19 = 8
    INIT b7 = [w16, w17, w18, w19]
    ASSERT w20 = 9
    WRITE b7[w0] = w20
    READ w21 = b7[w2]
    READ w22 = b7[w5]
    READ w23 = b7[w7]
    READ w24 = b7[w2]
    READ w25 = b7[w3]
    INIT b9 = [w22, w23, w24, w25]
    ASSERT w26 = 10
    WRITE b9[w0] = w26
    READ w27 = b9[w5]
    READ w28 = b9[w7]
    READ w29 = b9[w2]
    READ w30 = b9[w3]
    ASSERT w31 = 11
    INIT b11 = [w27, w28, w29, w30, w31]
    WRITE b11[w0] = w31
    ");
}
```

Note how we push and pop from the "same" slice. However, note how in ACIR we create increasingly large memory INIT ops.

The reason is that when we pop_back from a slice we only change its length and its contents remain the same. Then when we push_back, we append the new element(s) at the end... maybe after elements that werre previously removed! That means that newly pushed elements will never be seen by the user because they'll be behind the actual slice length.

This bug can actually be reproduced with the following Noir program:

```noir
fn main(cond: bool) {
    let mut slice = &[0, 1];
    if cond {
        slice = slice.push_back(10);
    }
    for i in 0..2 {
        slice = slice.push_back(i);
        assert_eq(slice[slice.len() - 1], i);
        let (new_slice, _) = slice.pop_back();
        slice = new_slice;
    }
}
```

`cond` can be `false` or `true`, it doesn't matter.

When we `nargo execute` the above program we get:

```
error: Failed constraint
  ┌─ src/main.nr:8:19
  │
8 │         assert_eq(slice[slice.len() - 1], i);
  │                   -------------------------
  │
  = Call stack:
    1. src/main.nr:8:19

Failed to solve program: 'Cannot satisfy constraint'
```

However, it's impossible for that assertion to fail given that we just pushed `i` at the end of the slice.

Also, commenting `if cond { ... }` makes the program pass, but the previously pushed elements shouldn't matter.

### Expected Behavior

The above Noir program executes successfully.

### Bug

The Noir program doesn't execute successfully.

### To Reproduce

1.
2.
3.
4.

### Workaround

None

### Workaround Description

_No response_

### Additional Context

_No response_

### Project Impact

None

### Blocker Context

_No response_

### Nargo Version

_No response_

### NoirJS Version

_No response_

### Proving Backend Tooling & Version

_No response_

### Would you like to submit a PR for this Issue?

None

### Support Needs

_No response_

### PR DESCRIPTION
**Pull request by guipublic**
# Description

## Problem\*

Resolves #10170 

## Summary\*
'Slice push_back' push after the slice length, which is not the same as the slice end when the capacity is bigger than the slice length.

## Documentation\*

Check one:
- [X] No documentation needed.
- [ ] Documentation included in this PR.
- [ ] **[For Experimental Features]** Documentation to be submitted in a separate PR.

# PR Checklist\*

- [X] I have tested the changes locally.
- [X] I have formatted the changes with [Prettier](https://prettier.io/) and/or `cargo fmt` on default settings.

### CODE REVIEW

File: compiler/noirc_evaluator/src/acir/tests/intrinsics.rs [hunk 1]
```diff
@@ -44,6 +44,56 @@ fn slice_push_back() {
...
+    INIT b2 = [w7, w9, w6]
+    ASSERT w10 = 10
+    WRITE b2[w2] = w10
+    ASSERT w2 = w1 - 1
+    READ w11 = b2[w6]
+    READ w12 = b2[w8]
+    READ w13 = b2[w3]
+    READ w14 = b2[w6]
+    READ w15 = b2[w8]
+    READ w16 = b2[w3]
```
Comment (asterite) [inline compiler/noirc_evaluator/src/acir/tests/intrinsics.rs]: @guipublic I added a test to see the generated ACIR in the new case.

As you can see, it seems we read from `b2` twice (here we read at positions 0, 1 and 2, twice).
(this might be easier to notice with https://github.com/noir-lang/noir/pull/10068 but that fails for a reason I don't understand)

Just mentioning because there might be an opportunity to optimize this, reducing the memory performance loss (though I'm not sure if it'll affect it in practice).

Comment (asterite) [reply compiler/noirc_evaluator/src/acir/tests/intrinsics.rs]: Hm, or maybe this code is from before this PR, not sure...

Comment (asterite) [reply compiler/noirc_evaluator/src/acir/tests/intrinsics.rs]: Right, it seems these opcodes come after the intrinsic 🤷

Comment (asterite) [reply compiler/noirc_evaluator/src/acir/tests/intrinsics.rs]: Aaaah... it's because `slice_push_back` creates a new block ID without any relation to any SSA value, but it could be related to the result.

I'll push a commit to try this, if it doesn't work we can revert it.

Comment (asterite) [reply compiler/noirc_evaluator/src/acir/tests/intrinsics.rs]: Done! It seems this slightly improved things.

File: compiler/noirc_evaluator/src/acir/call/intrinsics/slice_ops.rs [hunk 2]
```diff
@@ -24,25 +28,146 @@ impl Context<'_> {
...
+                        elements_var.push(acir_var);
+                    }
+                    AcirValue::Array(vector) => {
+                        let zero_value = self.array_zero_value(&ssa_typ)?;
+                        new_slice.push_back(zero_value);
+                        for acir_value in vector {
+                            let acir_vars = self.flatten(&acir_value)?;
+                            for var in acir_vars {
+                                elements_var.push(var);
+                            }
```
Comment (asterite) [inline compiler/noirc_evaluator/src/acir/call/intrinsics/slice_ops.rs]:
```suggestion
                            elements_var.extend(acir_vars);
```

File: compiler/noirc_evaluator/src/acir/call/intrinsics/slice_ops.rs [hunk 3]
```diff
@@ -24,25 +28,146 @@ impl Context<'_> {
...
+                        let var = self.acir_context.add_constant(type_size);
+                        AcirValue::Var(var, AcirType::field())
+                    });
+                    let element_type_sizes_len = init_values.len();
+                    self.initialize_array(
+                        element_type_sizes,
+                        element_type_sizes_len,
+                        Some(AcirValue::Array(init_values.into())),
+                    )?;
+                    Some(element_type_sizes)
```
Comment (asterite) [inline compiler/noirc_evaluator/src/acir/call/intrinsics/slice_ops.rs]: It seems this logic is the same as https://github.com/noir-lang/noir/blob/6424d4ac90d4a78560d3689066762d5fb6a2640d/compiler/noirc_evaluator/src/acir/arrays.rs#L882-L896

Maybe we can extract both to a helper method?

**Comment by asterite** [comment]
I think there's still something to improve here (I'll write this and then investigate it a bit more).

Given this code:

```noir
fn main(cond: bool, index: u32) -> pub Field {
    let mut slice = &[0, 1];
    if cond {
        slice = slice.push_back(2);
    }

    let slice = slice.push_back(3);
    let (slice, _) = slice.pop_back();

    let slice = slice.push_back(4);
    let (slice, _) = slice.pop_back();

    let slice = slice.push_back(5);
    let (slice, _) = slice.pop_back();

    let slice = slice.push_back(6);
    let (slice, _) = slice.pop_back();

    slice[index]
}
```

statically we can determine that the slice max length won't exceed 4, because we start with 2 elements, then conditionally push one more, then push one more and remove it, etc.

However, the generated ACIR has this:

```
func 0
private parameters: [w0, w1]
public parameters: []
return values: [w2]
...
INIT b0 = [w6, w7, w8, w9]
...
INIT b1 = [w15, w16, w17, w18]
...
INIT b3 = [w15, w16, w17, w18, w6]
...
INIT b5 = [w23, w24, w25, w26, w27, w6]
...
INIT b7 = [w30, w31, w32, w33, w34, w35, w6]
...
INIT b8 = [w38, w39, w40, w41, w42, w43, w44]
...
```

I'm not exactly sure why this happens. Maybe it's because when we do `slice_pop_back` we don't remove any elements from the back of the array. If we write the same Noir code but using `slice_pop_front` then the array stays at a maximum length of 4.

Out of curiosity, I'm going to try applying the change from #10179 in this PR to see what happens (I'll do it after running all tests locally).

File: compiler/noirc_evaluator/src/acir/call/intrinsics/slice_ops.rs (hunk 3 above)
Comment (asterite) [inline compiler/noirc_evaluator/src/acir/call/intrinsics/slice_ops.rs]: I think all of this can be replaced with `init_element_type_sizes_array` (similar logic to what's done in `convert_slice_insert`)

**Comment by asterite** [comment]
Cool, it improved things a tiny bit :-)

File: compiler/noirc_evaluator/src/acir/call/intrinsics/slice_ops.rs [hunk 4]
```diff
@@ -24,25 +27,136 @@ impl Context<'_> {
...
+
+            // 3. Write to the dynamic array
+
+            // 3.1 Computes the flatten_idx where to write into the dynamic array:
+            // Use element_type_size if it exists; convert the user index (slice_length) into the AcirValues index,
+            // and then flatten it with element_type_size
+            let mut flatten_idx = if let Some(element_type_sizes) = element_type_sizes {
+                let predicate_index = self
+                    .acir_context
+                    .mul_var(slice_length, self.current_side_effects_enabled_var)?;
```
Comment (asterite) [inline compiler/noirc_evaluator/src/acir/call/intrinsics/slice_ops.rs:140]: Is the side effects var needed here? I find it strange because no other slice intrinsic seems to rely on it.

File: compiler/noirc_evaluator/src/acir/call/intrinsics/slice_ops.rs [hunk 5]
```diff
@@ -484,6 +609,10 @@ impl Context<'_> {
             "ICE: The read flattened slice should match the computed size"
         );
 
+        let item_size = slice_typ.element_size();
+        let item_size = self.acir_context.add_constant(item_size);
+        let remove_index = self.acir_context.mul_var(remove_index, item_size)?;
```
Comment (asterite) [inline compiler/noirc_evaluator/src/acir/call/intrinsics/slice_ops.rs:614]: Is this needed? Was there a bug related to this? Same for the other intrinsics where this was changed.

File: compiler/noirc_evaluator/src/acir/call/intrinsics/slice_ops.rs [hunk 6]
```diff
@@ -24,25 +27,136 @@ impl Context<'_> {
...
-        // We must directly push back elements for non-nested slices
-        for elem in elements_to_push {
-            let element = self.convert_value(*elem, dfg);
-            new_slice.push_back(element);
-        }
+        let (new_slice_length, new_slice_val) = if let Some(len_const) =
+            dfg.get_numeric_constant(arguments[0])
+        {
+            // Length is known at compile time - we can precisely determine where to write
+            let mut new_slice = self.read_array_with_type(slice, &slice_typ)?;
```
Comment (asterite) [inline compiler/noirc_evaluator/src/acir/call/intrinsics/slice_ops.rs:46]: Why is the new `read_array_with_type` function needed? I'm mainly asking because all other intrinsics didn't need to use it so I wonder why we can't use the flattened values.

File: compiler/noirc_evaluator/src/ssa/ir/dfg/simplify/call.rs [hunk 7]
```diff
@@ -133,16 +134,28 @@ pub(super) fn simplify_call(
...
                 if element_type.element_size() != 1 {
-                    // Old code before implementing multiple slice mergers
-                    for elem in &arguments[2..] {
-                        slice.push_back(*elem);
+                    if let Some(IntegerConstant::Unsigned { value: slice_len, .. }) =
+                        dfg.get_integer_constant(arguments[0])
+                    {
+                        // This simplification, which push back directly on the slice, only works if the real slice_len is the
+                        // the length of the slice.
+                        if slice_len as usize == slice.len() {
```
Comment (asterite) [inline compiler/noirc_evaluator/src/ssa/ir/dfg/simplify/call.rs:142]: Couldn't this optimization also be done if `slice_len` is less than `slice.len()`? In that case we need to overwrite the values of the existing slice... I guess similar to what we do in the ACIR implementation.

Comment (asterite) [reply compiler/noirc_evaluator/src/ssa/ir/dfg/simplify/call.rs:142]: Ah, nevermind. There's still an optimization for the general case when it doesn't enter this `if`.

In any case this is very strange. Why is the optimization done only when `element_size` is not one? But... this is probably outside of this PR's scope.

File: compiler/noirc_evaluator/src/acir/call/intrinsics/slice_ops.rs (hunk 4 above)
Comment (guipublic) [reply compiler/noirc_evaluator/src/acir/call/intrinsics/slice_ops.rs:140]: Yes they do, for instance when they use `get_flattened_index()` which uses `self.current_side_effects_enabled_var`. This is why I added it here.

File: compiler/noirc_evaluator/src/acir/call/intrinsics/slice_ops.rs (hunk 5 above)
Comment (guipublic) [reply compiler/noirc_evaluator/src/acir/call/intrinsics/slice_ops.rs:614]: Yes, there were several issues that I had to fix regarding this, when a Slice contains complex types.
The input index (to the slice operation) is the 'user index'.
However tuples are flattened in SSA, so if the slice has a struct, the inner array of the slice in SSA will have a composite type of the elements in the structure.
This multiplication corresponds to the SSA flattening.

File: compiler/noirc_evaluator/src/acir/call/intrinsics/slice_ops.rs (hunk 6 above)
Comment (guipublic) [reply compiler/noirc_evaluator/src/acir/call/intrinsics/slice_ops.rs:46]: A dynamic write to the inner array needs to be done on the fully flattened structure, so DynamicArrays are fully flattened:
Arrays in SSA are flattened because of the tuples, as I said before. But if the structure contains an array, it will be one element in the SSA (the array). For instance, a slice of Foos: &[Foo], where Foo = {x: Field, y:Field, a=[u32;3]} has elements of size 3 when the tuple is flattened in SSA. A full flattening in ACIR will have elements of size 5 to count for the 3 elements of the inner array 'a'.
So read_array_with_type account for the mismatch between Arrays in ACIR which are similar to SSA Arrays, and Dynamic Arrays which are fully flattened.
It is not used for all other intrinsic because I added it only for push_back and pop_back. I think there are issues with Slices having complexe types in the other slice operations (as long as they require dynamic access) because precisely they do not do this conversion. However, I think this PR is big enough and wanted to look at the other operations once this PR would be merged.

**Review by asterite — APPROVED** [review]
Looks good!
