### PR TITLE
fix(parser): Handle member access in `Parser::parse_statement_or_expression_or_lvalue` 

### LINKED ISSUE #11827: Modifying member access at comptime causes circuit failure
### Aim

Discovered during a comptime exercise. 

The following code fails to compile:
```noir
comptime fn foo(f: FunctionDefinition) -> Quoted {
    let body = f.body();
    let body = body.modify(|_| Option::none());
    f.set_body(body);
    quote { }
}

struct Spam {
    eggs: u32,
}

fn main() {
    let mut spams = @[Spam { eggs: 0 }];
    bar(&mut spams);
}

#[foo]
fn bar(spams: &mut [Spam]) {
    spams[0].eggs += 1;
}
```

### Expected Behavior

It should compile and execute without an error. 

### Bug

```console
❯ cargo run -q -p nargo_cli -- compile --force
error: Assertion failed
   ┌─ std/option.nr:33:16
   │
33 │         assert(self._is_some);
   │                -------------
   │
   = Call stack:
     1. src/main.nr:17:1
     2. src/main.nr:3:16
     3. std/meta/expr.nr:251:22
     4. std/option.nr:131:13
     5. std/meta/expr.nr:251:40
     6. std/meta/expr.nr:343:5
     7. std/option.nr:72:26
     8. std/meta/expr.nr:344:21
     9. std/meta/expr.nr:500:5
     10. std/vector.nr:65:33
     11. std/meta/expr.nr:500:22
     12. std/meta/expr.nr:249:22
     13. std/option.nr:131:13
     14. std/meta/expr.nr:249:40
     15. std/meta/expr.nr:326:5
     16. std/option.nr:72:26
     17. std/meta/expr.nr:328:19
     18. std/meta/expr.nr:262:22
     19. std/option.nr:131:13
     20. std/meta/expr.nr:262:40
     21. std/meta/expr.nr:435:5
     22. std/option.nr:72:26
     23. std/meta/expr.nr:437:9
     24. std/meta/expr.nr:620:5

Aborting due to 1 previous error
```

### To Reproduce

Place a comptime attribute over a function with member access such as `obj.field` and call `.modify` on its body that _does not_ modify that statement/expression. When the existing member access is reconstructed as the default option, the circuit fails, because `.as_expr()` return `None`, because `$obj.$field` cannot be parsed, and then the `.unwrap()` fails.

### Workaround

None

### Workaround Description

_No response_

### Additional Context

_No response_

### Project Impact

None

### Blocker Context

_No response_

### Nargo Version

nargo version = 1.0.0-beta.19 noirc version = 1.0.0-beta.19+4aabf98178cf7ad48d67f3d20ef718e0c548fdfb (git version hash: 4aabf98178cf7ad48d67f3d20ef718e0c548fdfb, is dirty: true)

### NoirJS Version

_No response_

### Proving Backend Tooling & Version

_No response_

### Would you like to submit a PR for this Issue?

Yes

### Support Needs

_No response_

### PR DESCRIPTION
**Pull request by aakoshh**
# Description

## Problem

Resolves #11827 

## Summary

Changes `parse_statement_or_expression_or_lvalue` to handle the case where an interned `LValue` is followed by a `Dot`. 

## User Documentation

Check one:
- [x] No user documentation needed.
- [ ] Changes in _docs/_ included in this PR.
- [ ] **[For Experimental Features]** Changes in _docs/_ to be submitted in a separate PR.

# PR Checklist

- [x] I have tested the changes locally.
- [ ] I have formatted the changes with [Prettier](https://prettier.io/) and/or `cargo fmt` on default settings.

### CODE REVIEW

File: compiler/noirc_frontend/src/parser/parser/statement_or_expression_or_lvalue.rs [hunk 1]
```diff
@@ -26,20 +26,35 @@ impl Parser<'_> {
...
+                            lvalue: interned_lvalue(),
+                            expression,
+                        });
                         return StatementOrExpressionOrLValue::Statement(Statement {
                             kind,
                             location: self.location_since(start_location),
                         });
-                    } else {
-                        return StatementOrExpressionOrLValue::LValue(lvalue);
+                    } else if self.current_is(Token::Dot) {
```
Comment (TomAFrench) [inline compiler/noirc_frontend/src/parser/parser/statement_or_expression_or_lvalue.rs:44]:
```suggestion
                    } else if self.eat(Token::Dot) {
```

Is this done on purpose as opposed to eating?

Comment (aakoshh) [reply compiler/noirc_frontend/src/parser/parser/statement_or_expression_or_lvalue.rs:44]: Yes, because the method that parses the member access wants to be the one to eat it:

https://github.com/noir-lang/noir/blob/556fb622a439140eaff16ccbeb6859a7fba328b9/compiler/noirc_frontend/src/parser/parser/expression.rs#L242-L243

**Comment by asterite** [comment]
CI still fails, but it should get resolved with https://github.com/noir-lang/noir/pull/11829
