### PR TITLE
fix(comptime): Attribute macro expansion depth limit

### LINKED ISSUE #10542: Compiler stack overflow when evaluating attributes infinitely
### Aim

This code:

```noir
#[foo]
comptime fn foo(_: FunctionDefinition) -> Quoted {
    quote {
        #[foo]
        fn bar() {}
    }
}

fn main() {}
```

leads to a stack overflow on `nargo compile`.

### Expected Behavior

The compiler should have a maximum recursion limit, and produce an error instead of crashing.

An error is important here as if one accidentally produces this infinite recursion, it's hard to tell where the issue is.

A similar Rust code where a `proc_macro_attribute` expands to itself gives this error:

```
error: recursion limit reached while expanding `#[expand]`
 --> foo/src/main.rs:3:1
  |
3 | #[expand]
  | ^^^^^^^^^
  |
  = help: consider increasing the recursion limit by adding a `#![recursion_limit = "256"]` attribute to your crate (`foo`)
  = note: this error originates in the attribute macro `expand` (in Nightly builds, run with -Z macro-backtrace for more info)
```

### Bug

The compiler should error instead of crashing.

### To Reproduce

1.
2.
3.
4.

### Workaround

None

### Workaround Description

_No response_

### Additional Context

_No response_

### Project Impact

None

### Blocker Context

_No response_

### Nargo Version

_No response_

### NoirJS Version

_No response_

### Proving Backend Tooling & Version

_No response_

### Would you like to submit a PR for this Issue?

None

### Support Needs

_No response_

### PR DESCRIPTION
**Pull request by vezenovm**
# Description

## Problem

Resolves #10542 
Alternative to #11186

## Summary

Changes:
- Global macro expansion depth tracking. Tracks the recursion depth globally (per-Elaborator instance) rather than per-function. This correctly catches both single-function recursion and mutual recursion at the same depth limit. Programs with many sequential (non-recursive) uses of the same attribute still work because we track nesting depth, not total calls.  
- Expansion limit check. Set the limit at 32 for now. Of course this should be user-adjustable in the future but I leave that to later work.
- Added various tests under `compiler/noirc_frontend/src/tests/metaprogramming.rs`
- I added error deduplication to prevent exponential growth of "While running this function attribute" labels which bubble up through nested recursion.

Without error deduplication we would get this error output:
<details><summary>Details</summary>
<p>

```
warning: unused function bar
   ┌─ src/main.nr:20:16
   │
20 │             fn bar() {}
   │                --- unused function
   │

error: Duplicate definitions of function with name bar found
   ┌─ src/main.nr:16:1
   │
16 │ #[foo]
   │ ------
   │ │
   │ While running this function attribute
   │ While running this function attribute
   ·
19 │             #[foo]
   │             ------ While running this function attribute
20 │             fn bar() {}
   │                ---
   │                │
   │                Second function found here
   │                First function found here
   │

error: Duplicate definitions of function with name bar found
   ┌─ src/main.nr:16:1
   │
16 │ #[foo]
   │ ------
   │ │
   │ While running this function attribute
   │ While running this function attribute
   │ While running this function attribute
   ·
19 │             #[foo]
   │             ------
   │             │
   │             While running this function attribute
   │             While running this function attribute
   │             While running this function attribute
20 │             fn bar() {}
   │                ---
   │                │
   │                Second function found here
   │                First function found here
   │

error: Duplicate definitions of function with name bar found
   ┌─ src/main.nr:16:1
   │
16 │ #[foo]
   │ ------
   │ │
   │ While running this function attribute
   │ While running this function attribute
   │ While running this function attribute
   │ While running this function attribute
   ·
19 │             #[foo]
   │             ------
   │             │
   │             While running this function attribute
   │             While running this function attribute
   │             While running this function attribute
   │             While running this function attribute
   │             While running this function attribute
   │             While running this function attribute
20 │             fn bar() {}
   │                ---
   │                │
   │                Second function found here
   │                First function found here
   │
```

</p>
</details> 
The above would continue with the number of "While running this function attribute" labels growing exponentially. The final output would be > 7k lines and "Attribute recursion limit exceeded" would not even fit in my shell.

After deduplication we clearly see the error:
```
error: Duplicate definitions of function with name bar found
   ┌─ src/main.nr:16:1
   │
16 │ #[foo]
   │ ------ While running this function attribute
   ·
19 │             #[foo]
   │             ------ While running this function attribute
20 │             fn bar() {}
   │                ---
   │                │
   │                Second function found here
   │                First function found here
   │

error: Attribute recursion limit exceeded
   ┌─ src/main.nr:16:1
   │
16 │ #[foo]
   │ ------ While running this function attribute
   ·
19 │             #[foo]
   │             ------
   │             │
   │             This attribute generates code with the same attribute, causing infinite recursion
   │             While running this function attribute
   │
```
"Attribute recursion limit exceeded" is still preceded by 31 errors (attributes run until limit of 32 recursions), but that the output is at least manageable now.

## User Documentation

Check one:
- [X] No user documentation needed.
- [ ] Changes in _docs/_ included in this PR.
- [ ] **[For Experimental Features]** Changes in _docs/_ to be submitted in a separate PR.

# PR Checklist

- [X] I have tested the changes locally.
- [X] I have formatted the changes with [Prettier](https://prettier.io/) and/or `cargo fmt` on default settings.

### CODE REVIEW

File: compiler/noirc_frontend/src/elaborator/comptime.rs [hunk 1]
```diff
@@ -737,6 +737,27 @@ impl<'context> Elaborator<'context> {
...
+            // infinite recursion when an attribute generates code with the same attribute.
+            //
+            // Note: This check is intentionally here in `run_attributes` rather than in
+            // `run_attribute` because the recursion path is:
+            //   run_attributes -> run_attribute -> elaborate_items -> run_attributes
+            // If we put the increment/decrement in `run_attribute`, the decrement would
+            // happen before `elaborate_items` is called, so the depth counter would reset
+            // before the recursive call and fail to detect the recursion.
+            let current_depth =
+                self.attribute_recursion_depth.get(&attr.function).copied().unwrap_or(0);
```
Comment (jfecher) [inline compiler/noirc_frontend/src/elaborator/comptime.rs]: Having this be per-function seems a bit odd to me. It seems simpler and more correct to have a single, probably thread-local global counter so that mutually recursive functions are counted more accurately.

Tracking each function separately we could have a simple recursive function error after 30 stack frames but a set of 3 mutually recursive functions only error after 90 stack frames, potentially stack overflowing beforehand.

Comment (vezenovm) [reply compiler/noirc_frontend/src/elaborator/comptime.rs]: > Tracking each function separately we could have a simple recursive function error after 30 stack frames but a set of 3 mutually recursive functions only error after 90 stack frames, potentially stack overflowing beforehand.

Ah yes you are right. I was trying to prevent the situation in the new `many_non_recursive_attributes_do_not_trigger_recursion_limit` test but did not consider mutually recursive functions at a greater distance then having different behavior than basic recursion. I will update. 

EDIT: I guess technically this would still count "attribute recursion" correctly. It depends if we want to consider this limit to be more of a call limit or a recursion limit.

Comment (vezenovm) [reply compiler/noirc_frontend/src/elaborator/comptime.rs]: I switched to a single counter that is now more of a "macro expansion depth limit". This should provide a reasonable limit that has the same expected behavior under the different scenarios listed above. This aligns more closely with Rust. Although, the macro expansion limit can be configured through the recursion limit field (as per the error message in #10542, it is really more of a expansion depth limit). I added an additional `mutually_recursive_attributes_cause_expansion_limit_error` test that checks we hit the same expansion limit as recursion with a single function.

I ultimately still went with a field on the Elaborator rather than a thread local counter. I found this to be more extensible and easier to keep track of for thread-safety in the future. The counter lives on the elaborator and we can synchronize the counter as part of the Elaborator. It felt like extra complexity to have a separate global counter when we have the Elaborator.
