### PR TITLE
fix: go to definition from `use` statement

### LINKED ISSUE #5389: LSP go to definition doesn't work from `use` statement
### Aim

Given this program:

```rust
mod foo {
    pub fn another_function() -> Field {
        3 + 4
    }
}

use foo::another_function; // <--- here

fn main() {
    let _ = another_function();
}
```

trying "go to definition" at the pointed location doesn't work

### Expected Behavior

It should take you to the second line of the program.

### Bug

Described above.

### To Reproduce

_No response_

### Project Impact

None

### Impact Context

_No response_

### Workaround

None

### Workaround Description

_No response_

### Additional Context

_No response_

### Installation Method

None

### Nargo Version

_No response_

### NoirJS Version

_No response_

### Would you like to submit a PR for this Issue?

Yes

### Support Needs

_No response_

### PR DESCRIPTION
**Pull request by asterite**
# Description

## Problem

Resolves #5389

## Summary

"Go to definition" works by scanning some `id_to_location` hash map where all expressions and statements locations are stored. However, "use" statement locations aren't captured there.

Then, we recently implemented rename functionality which works by building a graph that connects references to referenced nodes. This same graph can be used for "go to definition"! So that's what this PR does. However, it will first check the graph, then try the other approach because I think that other approach works for trait impls and other things which aren't captured in the reference graph. I'm still trying to understand that part and to avoid breaking things I left it as is (there are also no tests for those things so it's hard to know if we break something... but I plan to add more tests in the future).

https://github.com/noir-lang/noir/assets/209371/1dd2cb7e-7f41-4065-8761-4a0478937166

## Additional Context

None.

## Documentation\*

Check one:
- [x] No documentation needed.
- [ ] Documentation included in this PR.
- [ ] **[For Experimental Features]** Documentation to be submitted in a separate PR.

# PR Checklist\*

- [x] I have tested the changes locally.
- [x] I have formatted the changes with [Prettier](https://prettier.io/) and/or `cargo fmt` on default settings.

### CODE REVIEW

File: tooling/lsp/src/test_utils.rs [hunk 1]
```diff
@@ -37,3 +37,23 @@ pub(crate) async fn init_lsp_server(directory: &str) -> (LspState, Url) {
 
     (state, noir_text_document)
 }
+
+pub(crate) fn search_in_file(filename: &str, search_string: &str) -> Vec<Range> {
```
Comment (TomAFrench) [inline tooling/lsp/src/test_utils.rs:41]:
```suggestion
/// Searches for all instances of `search_string` in file `file_name` and returns a list of their locations.
pub(crate) fn search_in_file(filename: &str, search_string: &str) -> Vec<Range> {
```

File: tooling/lsp/src/test_utils.rs [hunk 2]
```diff
@@ -37,3 +37,23 @@ pub(crate) async fn init_lsp_server(directory: &str) -> (LspState, Url) {
...
+    let file_contents = std::fs::read_to_string(filename)
+        .unwrap_or_else(|_| panic!("Couldn't read file {}", filename));
+    let file_lines: Vec<&str> = file_contents.lines().collect();
+    file_lines
+        .iter()
+        .enumerate()
+        .filter_map(|(line_num, line)| {
+            line.find(search_string).map(|index| {
```
Comment (TomAFrench) [inline tooling/lsp/src/test_utils.rs:49]:
```suggestion
            // Note: this only finds the first instance of `search_string` on this line.
            line.find(search_string).map(|index| {
```

No need to fix this but good to flag this up imo.

File: tooling/lsp/src/requests/mod.rs [hunk 3]
```diff
@@ -251,6 +258,51 @@ pub(crate) fn on_shutdown(
     async { Ok(()) }
 }
 
+pub(crate) fn process_request<F, T>(
```
Comment (TomAFrench) [inline tooling/lsp/src/requests/mod.rs:261]: Love this refactor.

**Review by TomAFrench — APPROVED** [review]
LGTM. Small documentation suggestions

**Comment by TomAFrench** [comment]
Something I noticed when testing this, we don't allow "go to definition" in the case where the import is renamed, i.e. `use foo::bar as baz;`
