### PR TITLE
fix: expand unquote inside nested quote

### LINKED ISSUE #11365: Unable to use closure arguments in nested closure in comptime.
This is an issue encountered by Alvaro when attempting to make a comptime loop unroller function which broke when attempting to unroll a nested loop.

---

If we attempt to access the argument of the closure passed to the outer `do_func` call inside of the closure being passed to the `do_func` call then program then fails to compile with the below error message.

```noir
fn main() {
    do_func!(
        0_u32,
        |i: u32| {
            quote {
                $do_func!(0u32, |_| {
                    quote {
                        println($i);
                    }
                });
            }
        },
    );
}

pub comptime fn do_func(arg: u32, body: fn(u32) -> Quoted) -> Quoted {
    body(arg)
}
```

```
% nargo compile                                                                                                                                                                                                                                                                                                                                                                  ~/noir/temp tf/track-elaboration-times-in-benchmarks + tom-box
warning: unused variable i
  ┌─ src/main.nr:4:10
  │
4 │         |i: u32| {
  │          - unused variable
  │

error: cannot find `i` in this scope
  ┌─ src/main.nr:8:34
  │
8 │                         println($i);
  │                                  - not found in this scope
  │

Aborting due to 1 previous error

```

This can be worked around however by assigning `i` to an intermediate variable and then using that. 

```noir

fn main() {
    do_func!(
        0_u32,
        |i: u32| {
            quote {
                $do_func!(0u32, |_| {
                    let j = $i;
                    quote {
                        println($j);
                    }
                });
            }
        },
    );
}

pub comptime fn do_func(arg: u32, body: fn(u32) -> Quoted) -> Quoted {
    body(arg)
}

```

It's not immediately obvious why this is the case and we should aim to support using `$i` directly.

### PR DESCRIPTION
**Pull request by asterite**
# Description

## Problem

Resolves #11365

## User Documentation

Check one:
- [x] No user documentation needed.
- [ ] Changes in _docs/_ included in this PR.
- [ ] **[For Experimental Features]** Changes in _docs/_ to be submitted in a separate PR.

# PR Checklist

- [x] I have tested the changes locally.
- [x] I have formatted the changes with [Prettier](https://prettier.io/) and/or `cargo fmt` on default settings.

### CODE REVIEW

**Comment by asterite** [comment]
Hm, it seems the program in #11369 still doesn't compile, so there must be something else too.

**Comment by asterite** [comment]
Or maybe it's a different issue now? I get:

```
error: Non-comptime variable `i` referenced in comptime code
  ┌─ src/main.nr:8:34
  │
8 │                         println($i);
  │                                  - Non-comptime variables can't be used in comptime code
```

File: compiler/noirc_frontend/src/hir/comptime/interpreter/unquote.rs [hunk 1]
```diff
@@ -16,13 +16,19 @@ impl Interpreter<'_, '_> {
...
                 Token::UnquoteMarker(id) => {
-                    let value = self.evaluate(*id)?;
-                    let tokens = value.into_tokens(self.elaborator.interner, token.location())?;
+                    let value = self.evaluate(id)?;
+                    let tokens = value.into_tokens(self.elaborator.interner, location)?;
                     new_tokens.extend(tokens);
                 }
-                _ => new_tokens.push(token),
+                Token::Quote(tokens) => {
+                    // Make sure to susbtitute in nested `quote { ... }` as well.
```
Comment (TomAFrench) [inline compiler/noirc_frontend/src/hir/comptime/interpreter/unquote.rs]:
```suggestion
                    // Make sure to substitute in nested `quote { ... }` as well.
```
