### PR TITLE
fix(brillig): Use temp registers when passing block arguments

### LINKED ISSUE #11484: SSA Interpreter differs from brillig in loop program
### Aim

SSA:
```
brillig(inline) impure fn main f0 {
  b0(v1: [Field; 32], v2: [Field; 32], v3: [Field; 3], v4: [Field; 5]):
    jmp b1(u32 0, u32 5, u32 32)
  b1(v5: u32, v6: u32, v7: u32):
    v11 = lt v5, u32 17
    jmpif v11 then: b2, else: b3
  b2():
    v38 = unchecked_add v5, u32 1
    jmp b1(v38, v5, u32 10)
  b3():
    v31 = make_array b"{\"kind\":\"unsignedinteger\",\"width\":32}"
    call print(u1 1, v6, v31, u1 0)
    constrain v6 == u32 16
    constrain v7 == u32 10
    return
}
```
Source code:
```noir
fn main() {
    let mut y = 0;
    let mut x = 0;
    let n = 17;
    for i in 0..n {
        x = 10u32;
        y = i;
    }

    println(y);
    assert(y == n - 1);
    assert(x == 10);
}
```
Note that `n = 17` is the minimum n this occurs on, anything smaller and loop unrolling unrolls the loop resulting in code that runtimes agree successfully executes.

Also note that the above source code only produces the given SSA with the mem2reg_simple pass and after all 50 SSA passes

### Expected Behavior

Expected both runtimes to pass

### Bug

The SSA interpreter correctly passes (and at every ssa step)

Brillig fails to execute with
```
17
error: Failed to solve program: 'Failed to solve brillig function'
   ┌─ src/main.nr:58:12
   │
58 │     assert(y == n - 1);
   │            ----------
   │
   = Call stack:
     1. src/main.nr:58:12
```
From the above printout, it seems brillig ran the loop 1 extra time or assigned an already updated value of i when doing `y = i;`

### To Reproduce

1.
2.
3.
4.

### Workaround

None

### Workaround Description

_No response_

### Additional Context

_No response_

### Project Impact

None

### Blocker Context

_No response_

### Nargo Version

_No response_

### NoirJS Version

_No response_

### Proving Backend Tooling & Version

_No response_

### Would you like to submit a PR for this Issue?

None

### Support Needs

_No response_

### PR DESCRIPTION
**Pull request by vezenovm**
# Description

## Problem

Resolves #11484

## Summary

The `TerminatorInstruction::Jmp` handler in Brillig codegen passes arguments to block parameters via sequential mov instructions. When a source register is also the destination of another move in the same batch, the sequential execution overwrites the original value. This is a classic parallel move problem.

Block parameter assignments at a jmp must happen "simultaneously". 
A naive sequential loop can lose values when a source register
is overwritten by an earlier move in the same batch. For example, with:
  `jmp b1(v1, v2, u32 10)` where `b1(v2, v3, v4)`:
Sequential execution would:
     1. mov reg(v2), reg(v1) — overwrites old v3
     2. mov reg(v3), reg(v2) — reads the NEW v2 instead of old
To prevent this, we save any source that would be overwritten into a temporary first.

## User Documentation

Check one:
- [X] No user documentation needed.
- [ ] Changes in _docs/_ included in this PR.
- [ ] **[For Experimental Features]** Changes in _docs/_ to be submitted in a separate PR.

# PR Checklist

- [X] I have tested the changes locally.
- [X] I have formatted the changes with [Prettier](https://prettier.io/) and/or `cargo fmt` on default settings.

### CODE REVIEW

**Comment by jfecher** [comment]
> To prevent this, we save any source that would be overwritten into a
temporary first.

If there's a large regression here maybe we could also add a check if any register shows up in both the src and destination and only use temporary registers in that case

**Comment by vezenovm** [comment]
> If there's a large regression here maybe we could also add a check if any register shows up in both the src and destination and only use temporary registers in that case

Yeah this is similar to what we do in `codegen_mov_registers_to_registers` when we `codegen_return`. However, we can't use that method out right because in there we require that destinations are relative addresses, starting from 1 and consecutively incremented by one. While, in jmp destinations we can't make this assumption as we consider block parameter allocation in liveness analysis https://github.com/noir-lang/noir/pull/5097.

File: compiler/noirc_evaluator/src/brillig/brillig_ir.rs [hunk 1]
```diff
@@ -895,4 +895,87 @@ pub(crate) mod tests {
...
+    }
+
+    /// Test that the parallel-move fix preserves temporary registers across all moves.
+    ///
+    /// When two block parameters are swapped (`jmp b1(v1, v0, ...)`  where `b1(v0, v1, ...)`),
+    /// both sources are also destinations, so both need temporaries. If the temporaries are
+    /// freed too early, the register allocator can reuse the same address for the second
+    /// temp, overwriting the first saved value.
+    #[test]
+    fn jmp_block_params_parallel_move_swap() {
```
Comment (vezenovm) [inline compiler/noirc_evaluator/src/brillig/brillig_ir.rs:949]: This test will panic without the `temps` Vec in Brillig gen, but `jmp_block_params_parallel_move` will succeed. I guess that test is kind of redundant now and we have the integration test as the actual regression. Should I remove the one above?

Comment (jfecher) [reply compiler/noirc_evaluator/src/brillig/brillig_ir.rs:949]: I'd rather the unit test - the integration test is already a minified version of the `global_consts` test, and we'd currently produce different SSA for it on this PR without the mem2reg_simple changes anyway. So the unit test is more direct.

Comment (jfecher) [reply compiler/noirc_evaluator/src/brillig/brillig_ir.rs:949]: The `n` constant on the integration test should probably be increased greatly as well since we're looking to make loop unrolling more aggressive in the future.
