### PR TITLE
fix(SSA): show and parse range_check's assert_message

### LINKED ISSUE #8620: SSA Printer does not display the assertion message of range checks
### Aim

Discovered testing https://github.com/noir-lang/noir/pull/8610

### Expected Behavior

The printed SSA should represent the instruction faithfully. 

### Bug

I get an error like this:
```
Range check of v164 = Field 781294165659571600 failed.
  Max bits allowed by range check = 32
  Actual bit count = 60
  attempt to multiply with overflow
```
or in Debug format:
```
RangeCheckFailedWithMessage { value: "Field 781294165659571600", value_id: Id(164), actual_bits: 60, max_bits: 32, message: "attempt to multiply with overflow" }
```

but in the SSA it only shows up like so:
```
range_check Field 781294165659571600 to 32 bits
```

### To Reproduce

1.
2.
3.
4.

### Workaround

None

### Workaround Description

```shell
NOIR_ARBTEST_SEED=0x1c9d6d5800100000 cargo test -p noir_ast_fuzzer_fuzz pass_vs_prev
```

### Additional Context

_No response_

### Project Impact

None

### Blocker Context

_No response_

### Nargo Version

nargo version = 1.0.0-beta.6 noirc version = 1.0.0-beta.6+b2bfdb7bb0fc661bfb27da365f108cf131771295 (git version hash: ef1c8dc, is dirty: true)

### NoirJS Version

_No response_

### Proving Backend Tooling & Version

_No response_

### Would you like to submit a PR for this Issue?

None

### Support Needs

_No response_

### PR DESCRIPTION
**Pull request by asterite**
# Description

## Problem

Resolves #8620

## Documentation

Check one:
- [x] No documentation needed.
- [ ] Documentation included in this PR.
- [ ] **[For Experimental Features]** Documentation to be submitted in a separate PR.

# PR Checklist

- [x] I have tested the changes locally.
- [x] I have formatted the changes with [Prettier](https://prettier.io/) and/or `cargo fmt` on default settings.

### CODE REVIEW

File: compiler/noirc_evaluator/src/ssa/ir/printer.rs [hunk 1]
```diff
@@ -264,8 +264,10 @@ fn display_instruction_inner(
         Instruction::DecrementRc { value } => {
             writeln!(f, "dec_rc {}", show(*value))
         }
-        Instruction::RangeCheck { value, max_bit_size, .. } => {
-            writeln!(f, "range_check {} to {} bits", show(*value), *max_bit_size,)
+        Instruction::RangeCheck { value, max_bit_size, assert_message } => {
+            let message =
+                assert_message.as_ref().map(|message| format!(", {message:?}")).unwrap_or_default();
```
Comment (aakoshh) [inline compiler/noirc_evaluator/src/ssa/ir/printer.rs:269]:
```suggestion
                assert_message.as_ref().map(|message| format!(", {message}")).unwrap_or_default();
```
Doesn't seem to make any difference, but it confused me.

**Review by aakoshh — APPROVED** [review]
Nice 👏
