### PR TITLE
fix(print): Convert `HirType::Function` into `PrintableType::Tuple` 

### LINKED ISSUE #10158: Garbled output when passing function to `println`
### Aim

Noticed while testing https://github.com/noir-lang/noir/issues/10156

The following program will not print what we expect:
```rust
pub fn main() {
    println((foo, 10));
}

fn foo() -> Field {
    0
}
```

### Expected Behavior

It should print something like:
```
(<<fn([]) -> Field>>, 0x0a)
```

### Bug

```
❯ cargo run -q -p nargo_cli -- interpret --force --silence-warnings --show-monomorphized --show-ssa-pass Initial --ssa-pass Initial
warning[E0602]: unknown lint: `mismatched_lifetime_syntaxes`
  |
  = note: requested on the command line with `-A mismatched_lifetime_syntaxes`
  = note: `#[warn(unknown_lints)]` on by default

For more information about this error, try `rustc --explain E0602`.
fn main$f0() -> () {
    println$f1(((foo$f2, foo$f3), 10));
}
fn println$f1(input$l0: ((fn() -> Field, unconstrained fn() -> Field), Field)) -> () {
    {
        print_unconstrained$f4(true, input$l0);
    }
}
fn foo$f2() -> Field {
    0
}
unconstrained fn foo$f3() -> Field {
    0
}
unconstrained fn print_unconstrained$f4(with_newline$l1: bool, input$l2: ((fn() -> Field, unconstrained fn() -> Field), Field)) -> () {
    print_oracle$print(with_newline$l1, input$l2, r#"{"kind":"tuple","types":[{"kind":"function","arguments":[],"return_type":{"kind":"field"},"env":{"kind":"unit"},"unconstrained":false},{"kind":"field"}]}"#, false);
}

After Initial SSA:
acir(inline) fn main f0 {
  b0():
    call f1(f2, f3, Field 10)
    return
}
acir(inline) fn println f1 {
  b0(v0: function, v1: function, v2: Field):
    call f4(u1 1, v0, v1, v2)
    return
}
acir(inline) fn foo f2 {
  b0():
    return Field 0
}
brillig(inline) fn foo f3 {
  b0():
    return Field 0
}
brillig(inline) fn print_unconstrained f4 {
  b0(v0: u1, v1: function, v2: function, v3: Field):
    v31 = make_array b"{\"kind\":\"tuple\",\"types\":[{\"kind\":\"function\",\"arguments\":[],\"return_type\":{\"kind\":\"field\"},\"env\":{\"kind\":\"unit\"},\"unconstrained\":false},{\"kind\":\"field\"}]}"
    call print(v0, v1, v2, v3, v31, u1 0)
    return
}

(<<fn([]) -> Field>>, 0x03)
--- Interpreter result after Initial SSA:
Ok()
---
```

We can see that due to how we turn function pointers into `(constrained, unconstrained)` tuples, the monomorphized AST passes both to the `println` function: ` println$f1(((foo$f2, foo$f3), 10));` . 

However, the type descriptor only contains one argument in `print_oracle$print(`:
```json
{
  "kind":"tuple",
  "types":[
    {"kind":"function","arguments":[],"return_type":{"kind":"field"},"env":{"kind":"unit"},"unconstrained":false},
    {"kind":"field"}
  ]
}
```

The result is that we pass 2 types in the description but 3 values: `[2, 3, 10]` (two function IDs and the value), so it consumes `3` instead of `10`.

We should either pass only one value, instead of a tuple, or change the type descriptor to contain two function signatures. I guess seeing one signature printed would be more in line with user expectations.

### To Reproduce

See above.

### Workaround

None

### Workaround Description

_No response_

### Additional Context

_No response_

### Project Impact

None

### Blocker Context

_No response_

### Nargo Version

nargo version = 1.0.0-beta.14 noirc version = 1.0.0-beta.14+f74b106670c64b83aa9c3136a96413c27639dad7 (git version hash: dbc6cfe7f0ead4e6780167de99e184909a486db8, is dirty: true)

### NoirJS Version

_No response_

### Proving Backend Tooling & Version

_No response_

### Would you like to submit a PR for this Issue?

None

### Support Needs

_No response_

### PR DESCRIPTION
**Pull request by aakoshh**
# Description

## Problem\*

Resolves #10158 

## Summary\*

* Fixes the display of functions values to appear as a tuple, the way they are passed, and not leave unconsumed values in the foreign params. 
* Adds the display `unconstrained` to the type, to make it more intuitive why we see two versions. 
* Implement `Display` format for `PrintedType` to make function and reference displays more readable.

## Documentation\*

Check one:
- [x] No documentation needed.
- [ ] Documentation included in this PR.
- [ ] **[For Experimental Features]** Documentation to be submitted in a separate PR.

# PR Checklist\*

- [x] I have tested the changes locally.
- [ ] I have formatted the changes with [Prettier](https://prettier.io/) and/or `cargo fmt` on default settings.

### CODE REVIEW

File: compiler/noirc_frontend/src/monomorphization/printer.rs [hunk 1]
```diff
@@ -494,11 +494,47 @@ impl AstPrinter {
...
     ) -> Result<(), std::fmt::Error> {
+        if self.print_function_tuple(tuple, f)? {
+            return Ok(());
+        }
         write!(f, "(")?;
         self.print_comma_separated(tuple, f)?;
         write!(f, ")")
     }
 
+    /// Check if a tuple is a tuple of (constrained, unconstrained) functions and if we want to print specials as std calls,
```
Comment (vezenovm) [inline compiler/noirc_frontend/src/monomorphization/printer.rs]:
```suggestion
    /// Check if we have a tuple of (constrained, unconstrained) functions and if we want to print specials as std calls,
```

File: compiler/noirc_frontend/src/monomorphization/printer.rs [hunk 2]
```diff
@@ -494,11 +494,47 @@ impl AstPrinter {
...
+    /// then assume that we would rather see `println(foo)` than `println((foo, foo))`, so we can render the AST as Noir
+    /// without duplicating into `println(((foo, foo), (foo, foo)))` on re-parsing.
```
Comment (vezenovm) [inline compiler/noirc_frontend/src/monomorphization/printer.rs]: I get how we are avoiding `println((foo, foo))` but how are we duplicating into `println(((foo, foo), (foo, foo)))`?

**Review by vezenovm — APPROVED** [review]
Looks good just one question

File: compiler/noirc_frontend/src/monomorphization/printer.rs (hunk 2 above)
Comment (aakoshh) [reply compiler/noirc_frontend/src/monomorphization/printer.rs]: Maybe that was a bit obscure, the crux is in the "on re-parsing".

The `comptime_vs_brillig_*` targets of the AST fuzzer generate a random AST, then compare the execution results of the following two cases:
* use `DisplayAstAsNoir` to print it to string, then use the parsing facilities to run it at comptime
* execute as is using Brillig (to support `loop` and `while`)

If we did not have the special handling here, then we would end up with this:
1. Generate a random AST, which happens to want to `print` the `foo` function.
2. This appears in the AST as something like `println((f1, f1));`. 
3. Render the AST to string, which would contain `println((foo, foo));` as Noir
4. Parse the Noir code, which involves monomorphizing it: to the monomorphizer it looks like we are trying to print the tuple `(foo, foo)`, so it replaces each appearance of `foo` with `(f1, f1)`, resulting in `println(((f1, f1), (f1, f1))` in the AST. 
5. If we render it again to show the AST e.g. if there was an error, we see `println(((foo, foo), (foo, foo)))`. 

By undoing it here, we make sure we don't keep expanding every time we do a print-and-parse roundtrip.

File: compiler/noirc_frontend/src/monomorphization/printer.rs [hunk 3]
```diff
@@ -494,11 +494,47 @@ impl AstPrinter {
...
+            return Ok(());
+        }
         write!(f, "(")?;
         self.print_comma_separated(tuple, f)?;
         write!(f, ")")
     }
 
+    /// Check if we have a tuple of (constrained, unconstrained) functions and if we want to print specials as std calls,
+    /// then assume that we would rather see `println(foo)` than `println((foo, foo))`, so we can render the AST as Noir
+    /// without duplicating into `println(((foo, foo), (foo, foo)))` on re-parsing.
```
Comment (aakoshh) [inline compiler/noirc_frontend/src/monomorphization/printer.rs]:
```suggestion
    /// without duplicating into `println(((foo, foo), (foo, foo)))` if we print the AST and re-parse it, for example for comptime tests.
```
