### PR TITLE
fix(comptime): lower fmtstr to fmtstr, not str

### LINKED ISSUE #6990: Cannot print global fmtstr
### Aim

Try and run this function:
```noir
global ONE: Field = 50;
global TWO: Field = 100;
global GLOBAL: fmtstr<18, (Field, Field)> = f"i: {ONE}, j: {TWO}";

fn main() {
    let string = "i: {i}, j: {j}";
    println(string);

    println(GLOBAL);
}
```

### Expected Behavior

I expect to see this output:
```
i: {i}, j: {j}
i: 0x32, j: 0x64
```

### Bug

Instead I get this panic:
```
The application panicked (crashed).
Message:  assertion `left == right` failed
  left: 4
 right: 1
Location: compiler/noirc_evaluator/src/ssa/opt/inlining.rs:428
```
The SSA produced is the following:
```
After Initial SSA::
brillig(inline) fn main f0 {
  b0(v0: Field, v1: Field):
    v9 = make_array b"i: {i}, j: {j}"
    inc_rc v9
    call f1(v9)
    v14 = make_array b"i: 50, j: 100"
    call f2(v14)
    return
}
brillig(inline) fn println f1 {
  b0(v0: [u8; 14]):
    call f4(u1 1, v0)
    return
}
brillig(inline) fn println f2 {
  b0(v0: [u8; 18], v1: Field, v2: Field, v3: Field):
    call f3(u1 1, v0, v1, v2, v3)
    return
}
brillig(inline) fn print_unconstrained f3 {
  b0(v0: u1, v1: [u8; 18], v2: Field, v3: Field, v4: Field):
    v16 = make_array b"{\"kind\":\"field\"}"
    v17 = make_array b"{\"kind\":\"field\"}"
    call print(v0, v1, v2, v3, v4, v16, v17, u1 1)
    return
}
brillig(inline) fn print_unconstrained f4 {
  b0(v0: u1, v1: [u8; 14]):
    v20 = make_array b"{\"kind\":\"string\",\"length\":14}"
    call print(v0, v1, v20, u1 0)
    return
}
```
As you can see a global fmtstr is lowered into a basic string. This is also noted here https://github.com/noir-lang/noir/blob/101f2d4a134b9c43f11de1653f8ab02574dca312/compiler/noirc_frontend/src/hir/comptime/value.rs#L365

However, the function type still sees a fmtstr so we have a discrepancy in the number of parameters we generate for the monomorphized println and the actual arguments passed to the function. Thus, we fail in inlining where we check that the number of arguments and parameters match.

### To Reproduce

1. Copy the snippet above
2. Run `nargo compile`

### Workaround

Yes

### Workaround Description

Use a local fmtstr. e.g. this function will print accurately:
```noir
global ONE: Field = 50;
global TWO: Field = 100;

fn main(x: Field, y: pub Field) {
    let string = "i: {i}, j: {j}";
    println(string);

    let GLOBAL: fmtstr<18, (Field, Field)> = f"i: {ONE}, j: {TWO}";
    println(GLOBAL);
}
```
Here is an example of valid SSA:
```
After Initial SSA::
brillig(inline) fn main f0 {
  b0():
    v7 = make_array b"i: {i}, j: {j}"
    inc_rc v7
    call f1(v7)
    v14 = make_array b"i: {ONE}, j: {TWO}"
    inc_rc v14
    call f2(v14, u32 2, Field 50, Field 100)
    return
}
brillig(inline) fn println f1 {
  b0(v0: [u8; 14]):
    call f4(u1 1, v0)
    return
}
brillig(inline) fn println f2 {
  b0(v0: [u8; 18], v1: Field, v2: Field, v3: Field):
    call f3(u1 1, v0, v1, v2, v3)
    return
}
brillig(inline) fn print_unconstrained f3 {
  b0(v0: u1, v1: [u8; 18], v2: Field, v3: Field, v4: Field):
    v16 = make_array b"{\"kind\":\"field\"}"
    v17 = make_array b"{\"kind\":\"field\"}"
    call print(v0, v1, v2, v3, v4, v16, v17, u1 1)
    return
}
brillig(inline) fn print_unconstrained f4 {
  b0(v0: u1, v1: [u8; 14]):
    v20 = make_array b"{\"kind\":\"string\",\"length\":14}"
    call print(v0, v1, v20, u1 0)
    return
}
```

### Additional Context

_No response_

### Project Impact

Nice-to-have

### Blocker Context

_No response_

### Nargo Version

nargo version = 1.0.0-beta.1 noirc version = 1.0.0-beta.1+77441793fac75cc2e891ec1ee59e4224310ed037 (git version hash: 101f2d4a134b9c43f11de1653f8ab02574dca312, is dirty: true)

### NoirJS Version

_No response_

### Proving Backend Tooling & Version

_No response_

### Would you like to submit a PR for this Issue?

None

### Support Needs

_No response_

### PR DESCRIPTION
**Pull request by asterite**
# Description

## Problem

Resolves #6990

## Summary

See https://github.com/noir-lang/noir/pull/10678#issuecomment-3682760922

## Additional Context

If we agree to go forward with this I'll update the docs about lowering of comptime values into runtime values.

## User Documentation

Check one:
- [ ] No user documentation needed.
- [ ] Changes in _docs/_ included in this PR.
- [ ] **[For Experimental Features]** Changes in _docs/_ to be submitted in a separate PR.

# PR Checklist

- [x] I have tested the changes locally.
- [x] I have formatted the changes with [Prettier](https://prettier.io/) and/or `cargo fmt` on default settings.

### CODE REVIEW

File: compiler/noirc_frontend/src/hir/printer/mod.rs [hunk 1]
```diff
@@ -881,11 +882,51 @@ impl<'context, 'string> ItemPrinter<'context, 'string> {
...
             Value::String(string) => self.push_str(&format!("{string:?}")),
-            Value::FormatString(string, _typ) => {
-                // Note: at this point the format string was already expanded so we can't recover the original
-                // interpolation and this will result in a compile-error. But... the expanded code is meant
-                // to be browsed, not compiled.
-                self.push_str(&format!("f{string:?}"));
+            Value::FormatString(fragments, _typ, _) => {
+                let has_values = fragments
+                    .iter()
+                    .any(|fragment| matches!(fragment, FormatStringFragment::Value { .. }));
```
Comment (jfecher) [inline compiler/noirc_frontend/src/hir/printer/mod.rs:888]: Don't need to change this but I'm curious: shouldn't this be equivalent to `fragments.len() > 1`?
Or do we trim the empty strings such that `"{x}"` would be a single Value item and no string items?

File: test_programs/compile_success_empty/comptime_fmt_strings/src/main.nr [hunk 2]
```diff
@@ -8,7 +8,7 @@ fn main() {
         // compiling breaks the test runner.
         let s1 = f"x is {x}, fake interpolation: {{y}}, y is {y}";
         let s2 = std::mem::zeroed::<fmtstr<4, ()>>();
-        (s1, s2)
+        (s1.as_quoted_str(), s2.as_quoted_str())
```
Comment (jfecher) [inline test_programs/compile_success_empty/comptime_fmt_strings/src/main.nr]: Shouldn't this be:
```suggestion
        (s1.as_quoted_str!(), s2.as_quoted_str!())
```

**Review by jfecher — APPROVED** [review]
LGTM. This does make handling format strings a bit more complex unfortunately but maybe it is more expected for users at least. It also makes it possible to lower into a struct with a format string field.

I didn't mention this elsewhere but the old format strings used a `Rc<String>` equivalent, maybe the new one should use a `Rc<Vec<Fragment>>` to avoid cloning the entire Vec every time the value is used (e.g. we clone values when a variable lookup occurs).

File: compiler/noirc_frontend/src/hir/printer/mod.rs (hunk 1 above)
Comment (asterite) [reply compiler/noirc_frontend/src/hir/printer/mod.rs:888]: I just checked and yes, `f"{x}"` has just one fragment with a single interpolation.

File: test_programs/compile_success_empty/comptime_fmt_strings/src/main.nr (hunk 2 above)
Comment (asterite) [reply test_programs/compile_success_empty/comptime_fmt_strings/src/main.nr]: Good point! Just now I didn't understand how it worked then, but it seems we lower `Quoted` values by parsing its tokens into an Expression. I guess that's why it works. Is that expected? Should I still change this?

Comment (asterite) [reply test_programs/compile_success_empty/comptime_fmt_strings/src/main.nr]: I changed it, it's a bit more clear.

File: compiler/noirc_frontend/src/hir/comptime/value.rs [hunk 3]
```diff
@@ -251,9 +258,55 @@ impl Value {
             Value::String(value) | Value::CtString(value) => {
                 ExpressionKind::Literal(Literal::Str(unwrap_rc(value)))
             }
-            // Format strings are lowered as normal strings since they are already interpolated.
-            Value::FormatString(value, _) => {
-                ExpressionKind::Literal(Literal::Str(unwrap_rc(value)))
+            Value::FormatString(fragments, _, length) => {
+                // Format strings are lowered to format strings. The interpolated values are assigned
```
Comment (vezenovm) [inline compiler/noirc_frontend/src/hir/comptime/value.rs]: nit: This is roundabout. Comptime format string fragments are lowered to HIR format string literals?

Comment (asterite) [reply compiler/noirc_frontend/src/hir/comptime/value.rs]: Haha, good point, I think I tried to lower it to something else first but eventually ended up being able to lower them to "themselves". I'll remove this comment.

Comment (asterite) [reply compiler/noirc_frontend/src/hir/comptime/value.rs]: Ah, I thought this was another part of the code. They are lowered to a format string literal, but inside a block with temporary let statements. I'll find a better way to explain this.

Comment (asterite) [reply compiler/noirc_frontend/src/hir/comptime/value.rs]: Done! Let me know if it's clearer now.

Comment (vezenovm) [reply compiler/noirc_frontend/src/hir/comptime/value.rs]: Yes great very clear!
