### PR TITLE
fix: error on unbound generics in structs

### LINKED ISSUE #5436: Numeric generic struct parameter panics when accessed uninitialized
### Aim

Attempted to compile the following program:

```rust
struct Foo<let N: u32> { }

impl<let N: u32> Foo<N> {
    fn size(self) -> u32 {
        N
    }
}

fn main() {
    let foo = Foo { };
    assert(foo.size() == 0);
}
```

### Expected Behavior

Expected the program to either compile successfully (having defaulted `N = 0`) or fail with a user error because `N` is uninitialized when declaring `foo`.

### Bug

```bash
The application panicked (crashed).
Message:  Non-numeric type variable used in expression expecting a value
Location: compiler/noirc_frontend/src/monomorphization/mod.rs:909
```

### To Reproduce

1.
2.
3.
4.

### Project Impact

None

### Impact Context

_No response_

### Workaround

None

### Workaround Description

_No response_

### Additional Context

_No response_

### Installation Method

None

### Nargo Version

_No response_

### NoirJS Version

_No response_

### Would you like to submit a PR for this Issue?

None

### Support Needs

_No response_

### PR DESCRIPTION
**Pull request by asterite**
# Description

## Problem

Resolves #5436

## Summary

The monomorphizer checks that no types exist that aren't unbound and can't have a default type. This is also the case for structs, but this check is done on field types after they are paired with generics. For example:

```rust
struct Foo<T> {
  x: T
}

fn main() {
  let _ = Foo { x: 1 };
}
```

Here we pair `T` with the generic type of 1, then it's defaulted to `Field`, no error.

However, it can happen that a generic parameter isn't mentioned at all in a struct field. For example:

```rust
struct Foo<T> {
}

fn main() {
  let _ = Foo {};
}
```

Here `T` isn't paired with anything, so it's left unbound. However, because we only check that the resulting field types aren't unbound, no error happens.

The solution in this PR is to check that generic parameters aren't unbound. This required a method like `convert_type`, called `check_type`, that only checks for this errors. The reason is that I wanted to avoid converting types twice. But let me know if that would be fine (or if there's another solution for this).

## Additional Context

In Rust if a generic parameter isn't used in a field, an error about that is made. However, no error happens if the generic parameter is a `const` (similar to a `let N: u32` parameter in Noir) so here I chose to error un unbound generics, not check if a generic is unused.

## Documentation\*

Check one:
- [x] No documentation needed.
- [ ] Documentation included in this PR.
- [ ] **[For Experimental Features]** Documentation to be submitted in a separate PR.

# PR Checklist\*

- [x] I have tested the changes locally.
- [x] I have formatted the changes with [Prettier](https://prettier.io/) and/or `cargo fmt` on default settings.

### CODE REVIEW

File: compiler/noirc_frontend/src/monomorphization/mod.rs [hunk 1]
```diff
@@ -975,12 +977,37 @@ impl<'interner> Monomorphizer<'interner> {
...
+                //     fn main() {
+                //         let _ = Foo {};
+                //     }
+                //
+                // In the above case args is `[N]` but fields is `[]`, so T will never be checked.
+                // However, we want the above program to not compile.
+                for arg in args {
+                    if let Some(error) = Self::check_type(arg, location) {
+                        return Err(error);
+                    }
```
Comment (jfecher) [inline compiler/noirc_frontend/src/monomorphization/mod.rs:994]: I'd rather `check_type` returned a `Result` to begin with so that this could be:
```suggestion
                    Self::convert_type(arg, location)?;
```
(using convert_type here because of the next suggestion)

File: compiler/noirc_frontend/src/monomorphization/mod.rs [hunk 2]
```diff
@@ -1019,6 +1046,83 @@ impl<'interner> Monomorphizer<'interner> {
         })
     }
 
+    // Similar to `convert_type` but returns an error if any type variable can't be defaulted.
+    fn check_type(typ: &HirType, location: Location) -> Option<MonomorphizationError> {
```
Comment (jfecher) [inline compiler/noirc_frontend/src/monomorphization/mod.rs:1050]: Hmm, looking at this I would rather we only had one function (convert_type) rather than having to maintain two separate functions. The cost of converting a type is usually cheap anyway since types tend not to be deeply nested.

File: test_programs/compile_failure/type_annotation_needed_on_struct_constructor/src/main.nr [hunk 3]
```diff
@@ -0,0 +1,6 @@
+struct Foo<T> {
+}
+
+fn main() {
+    let foo = Foo {};
+}
```
Comment (jfecher) [inline test_programs/compile_failure/type_annotation_needed_on_struct_constructor/src/main.nr:6]: Neither integration test uses the stdlib so let's move them to the frontend tests

**Review by jfecher — CHANGES_REQUESTED** [review]
Some nitpicks

File: compiler/noirc_frontend/src/monomorphization/mod.rs (hunk 1 above)
Comment (asterite) [reply compiler/noirc_frontend/src/monomorphization/mod.rs:994]: Cool! I had it like `Result<(), ...>` in the beginning but I wasn't sure if it was okay to do it. But now that I remember, that's also how `fmt` works.

File: compiler/noirc_frontend/src/monomorphization/mod.rs (hunk 2 above)
Comment (asterite) [reply compiler/noirc_frontend/src/monomorphization/mod.rs:1050]: Sounds good, I'll try it!

File: test_programs/compile_failure/type_annotation_needed_on_struct_constructor/src/main.nr (hunk 3 above)
Comment (asterite) [reply test_programs/compile_failure/type_annotation_needed_on_struct_constructor/src/main.nr:6]: Sounds good. I think I put them here because before this PR, these programs would error during monomorphization and those errors aren't caught in the frontend tests. But... now that they do error, I guess they make sense there.

Comment (jfecher) [reply test_programs/compile_failure/type_annotation_needed_on_struct_constructor/src/main.nr:6]: Ah, we still catch these during monomorphization, right. May need to keep these here then.

File: compiler/noirc_frontend/src/monomorphization/mod.rs (hunk 2 above)
Comment (asterite) [reply compiler/noirc_frontend/src/monomorphization/mod.rs:1041]: Ah, now I remember. The reason I didn't do this is because `convert_type` does this at one point:

```rust
binding.bind(default);
```

and so if we call `convert_type` with `args` and then once more with fields, it will give an error saying you can't bind twice.

Comment (jfecher) [reply compiler/noirc_frontend/src/monomorphization/mod.rs]: The second time it is called it should be already bound, so we shouldn't reach the same code path though, right?

Comment (asterite) [reply compiler/noirc_frontend/src/monomorphization/mod.rs]: Aaaaah... you are right! I'll push another commit

Comment (asterite) [reply compiler/noirc_frontend/src/monomorphization/mod.rs]: I pushed the commit but then reverted it because that produced "unexpected type 2" for some programs. I think if `args` has a numeric constant then `convert_type` fails. In `check_type` I just ignore those cases because those types are fine. But let me know if there's another approach here.

Comment (asterite) [reply compiler/noirc_frontend/src/monomorphization/mod.rs]: Let me know if there's another way around this.

**Review by jfecher — APPROVED** [review]
LGTM
