### PR TITLE
fix: sign extend in signed cast

### LINKED ISSUE #8212: Upcasting negative signed types does not preserve value
Consider the program

```noir
fn main(x: i8) {
    println(x);
    println(x as i16);
}

```

if we run this with the argument `-1` then we get the output

```
-1
255
```

I would expect the value of negative signed numbers to be preserved by this operation. This also manifests in the program below:

```noir
fn main(x: i8) {
   assert_eq(x as i16, -1);
}
```

### PR DESCRIPTION
**Pull request by guipublic**
# Description

## Problem\*

Resolves #8212

## Summary\*
Perform sign extension when casting between signed types.

## Documentation\*

Check one:
- [X] No documentation needed.
- [ ] Documentation included in this PR.
- [ ] **[For Experimental Features]** Documentation to be submitted in a separate PR.

# PR Checklist\*

- [X] I have tested the changes locally.
- [X] I have formatted the changes with [Prettier](https://prettier.io/) and/or `cargo fmt` on default settings.

### CODE REVIEW

File: compiler/noirc_evaluator/src/ssa/ssa_gen/context.rs [hunk 1]
```diff
@@ -625,16 +625,118 @@ impl<'a> FunctionContext<'a> {
...
-        if target_type_size < incoming_type_size {
-            value = self.builder.insert_truncate(value, target_type_size, incoming_type_size);
-        }
-
-        self.builder.insert_cast(value, typ)
+        let incoming_type = self.builder.type_of_value(value);
+
+        let result = match (&incoming_type, typ) {
+            // Casting to field is safe
+            (_, NumericType::NativeField) => value,
```
Comment (TomAFrench) [inline compiler/noirc_evaluator/src/ssa/ssa_gen/context.rs:632]: Can you add some tests for casting from signed types to `Field`? We can't really sign extend on these but we should have tests to enforce some behaviour here.

File: compiler/noirc_evaluator/src/ssa/ssa_gen/context.rs [hunk 2]
```diff
@@ -625,16 +625,118 @@ impl<'a> FunctionContext<'a> {
...
+                            patch,
+                            BinaryOp::Mul { unchecked: true },
+                            sign_not,
+                        );
+                        let value_as_unsigned = self.builder.insert_cast(
+                            value_as_unsigned,
+                            NumericType::unsigned(target_type_size),
+                        );
+                        // Patch the bit sign, which gives a `target_type_size` bit size value, so it does not overflow.
+                        self.builder.insert_binary(
```
Comment (jfecher) [inline compiler/noirc_evaluator/src/ssa/ssa_gen/context.rs:679]: Several instructions here - can you add a comment above the match case maybe on the instructions that are added?
E.g.
```
(for a value v0 of type iN cast to iM)
v1 = cast v0 to uN
v2 = lt v1, 2^(M - 1)
...etc
```

**Review by TomAFrench — COMMENTED** [review]
I think that we should probably add some more comprehensive testing of the behaviours of different casts. It should be possible to proptest various types of casting to ensure that it behaves as we expect.

File: compiler/noirc_evaluator/src/ssa/ssa_gen/context.rs (hunk 2 above)
Comment (guipublic) [reply compiler/noirc_evaluator/src/ssa/ssa_gen/context.rs]: Done

File: compiler/noirc_evaluator/src/ssa/ssa_gen/context.rs [hunk 3]
```diff
@@ -625,16 +625,118 @@ impl<'a> FunctionContext<'a> {
...
+                            patch_with_sign_predicate,
+                            BinaryOp::Add { unchecked: true },
+                            value_as_unsigned,
+                        )
+                    }
+                }
+            }
```
[the remark this answers is not in the document]
Comment (guipublic) [reply compiler/noirc_evaluator/src/ssa/ssa_gen/context.rs]: Done

File: compiler/noirc_evaluator/src/ssa/ssa_gen/context.rs (hunk 1 above)
Comment (guipublic) [reply compiler/noirc_evaluator/src/ssa/ssa_gen/context.rs:632]: Done

File: tooling/nargo_cli/tests/stdlib-props.rs [hunk 4]
```diff
@@ -138,3 +138,544 @@ fn field_vec_strategy(len: usize) -> impl Strategy<Value = Vec<FieldElement>> {
...
+    run_snippet_proptest(unsigned_32_128.to_string(), true, strategy_u32.clone());
+
+    // zero extend 64 bits
+    run_snippet_proptest(unsigned_64_64.to_string(), false, strategy_u64.clone());
+    run_snippet_proptest(unsigned_64_64.to_string(), false, strategy_u64.clone());
+    run_snippet_proptest(unsigned_64_128.to_string(), false, strategy_u64.clone());
+    run_snippet_proptest(unsigned_64_128.to_string(), true, strategy_u64.clone());
+    // zero extend 128 bits
+    run_snippet_proptest(unsigned_128_128.to_string(), false, strategy_u128.clone());
+    run_snippet_proptest(unsigned_128_128.to_string(), true, strategy_u128.clone());
```
[the remark this answers is not in the document]
Comment (guipublic) [reply tooling/nargo_cli/tests/stdlib-props.rs]: Done

**Review by TomAFrench — APPROVED** [review]
