### PR TITLE
fix(ssa): avoid overflow incrementing u128::MAX

### LINKED ISSUE #12494: Completeness bug: nargo execute crashing: Internal Compiler Error on u128::MAX < i in a finite-bounded for loop body, rejecting legitimate programs
### Expected Behavior

main.nr:
```
fn main() -> pub bool {
    let mut hit: bool = false;
    for i in 0..3_u128 {
        if 340282366920938463463374607431768211455 < i {
            hit = true;
        }
    }
    hit
}
```

- **Expected behavior**: The program should iterates i over 0..3_u128 and checks u128::MAX < i, which is trivially false for every u128, so hit is never set and the function returns false. 
- 
- **Actual behavior**: 
```
This is a bug. We may have already fixed this in newer versions of Nargo so try searching for similar issues at https://github.com/noir-lang/noir/issues/.
If there isn't an open issue for this bug, consider opening one at https://github.com/noir-lang/noir/issues/new?labels=bug&template=bug_report.yml
```

### Bug

`nargo execute` produced Internal Compiler Error 

```
The application panicked (crashed).
Message:  ICE: overflow while incrementing constant
Location: compiler/noirc_evaluator/src/ssa/ir/integer.rs:79

This is a bug. We may have already fixed this in newer versions of Nargo so try searching for similar issues at https://github.com/noir-lang/noir/issues/.
If there isn't an open issue for this bug, consider opening one at https://github.com/noir-lang/noir/issues/new?labels=bug&template=bug_report.yml
```

### Workaround

_No response_

### Project Impact

_No response_

### Nargo Version

nargo version = 1.0.0-beta.20 noirc version = 1.0.0-beta.20+5e48b65d3d30ad9ec57ec94e5c7512d86c6e1dc1 (git version hash: dd2b758da04b0a87235d54343710c22f028a8bb0, is dirty: false)

### NoirJS Version

_No response_

### Proving Backend

_No response_

### Would you like to submit a PR for this Issue?

Maybe

### PR DESCRIPTION
**Pull request by asterite**
## Problem Resolved

Resolves https://github.com/noir-lang/noir/issues/12494

## Summary of Changes

I also made a similar change to `dec` since the only place it's used already returns `Option`, so I thought that made sense.

## User Documentation

Check one:
- [x] No user documentation needed.
- [ ] Documented in _docs/_.
- [ ] **[For Experimental Features]** Documentation tracking issue created: 

## PR Checklist

- [x] I have tested the changes locally.
- [x] I have formatted the changes with [Prettier](https://prettier.io/) and/or `cargo fmt` on default settings.

### CODE REVIEW

File: compiler/noirc_evaluator/src/ssa/ir/integer.rs [hunk 1]
```diff
@@ -64,39 +64,27 @@ impl IntegerConstant {
         }
     }
 
-    /// Increment the value by 1
-    ///
-    /// # Panics
-    ///
-    /// Panics if the increment causes an overflow.
-    pub(crate) fn inc(self) -> Self {
+    /// Increment the value by 1. Returns None if the increment would cause an overlfow.
```
Comment (jfecher) [inline compiler/noirc_evaluator/src/ssa/ir/integer.rs]:
```suggestion
    /// Increment the value by 1. Returns None if the increment would cause an overflow.
```

**Review by jfecher — APPROVED** [review]
