### PR TITLE
fix(frontend)!: Ban zero sized arrays and strings as program input

### LINKED ISSUE #8451: Compiler crash: `call_data` and empty arrays
### Aim

This is a minimised version of https://github.com/noir-lang/noir/issues/8450 going through the full compilation pipeline.

I wanted to check what `nargo` does with the program that did not work with the SSA interpreter.

```rust
fn main(a: call_data(0) [(str<0>, str<4>); 3]) -> return_data (str<0>, str<4>) {
    a[0]
}
```

### Expected Behavior

The compiler should not crash.

### Bug

```console
$ cargo run -q -p nargo_cli -- compile --show-ssa-pass Initial
After Initial SSA:
acir(inline) fn main f0 {
  b0(v0: [([u8; 0], [u8; 4]); 3]):
    v2 = array_get v0, index u32 0 -> [u8; 4]
    v3 = array_get v2, index u32 0 -> u8
    v5 = array_get v2, index u32 1 -> u8
    v7 = array_get v2, index u32 2 -> u8
    v9 = array_get v2, index u32 3 -> u8
    v10 = array_get v0, index u32 1 -> [u8; 4]
    v11 = array_get v10, index u32 0 -> u8
    v12 = array_get v10, index u32 1 -> u8
    v13 = array_get v10, index u32 2 -> u8
    v14 = array_get v10, index u32 3 -> u8
    v15 = array_get v0, index u32 2 -> [u8; 4]
    v16 = array_get v15, index u32 0 -> u8
    v17 = array_get v15, index u32 1 -> u8
    v18 = array_get v15, index u32 2 -> u8
    v19 = array_get v15, index u32 3 -> u8
    v20 = make_array [v3, v5, v7, v9, v11, v12, v13, v14, v16, v17, v18, v19] : [Field; 12]
    v21 = array_get v0, index u32 0 -> [u8; 0]
    v22 = array_get v0, index u32 1 -> [u8; 4]
    v23 = array_get v22, index u32 0 -> u8
    v24 = array_get v22, index u32 1 -> u8
    v25 = array_get v22, index u32 2 -> u8
    v26 = array_get v22, index u32 3 -> u8
    v27 = make_array [v23, v24, v25, v26] : [Field; 4]
    return v27
}

The application panicked (crashed).
Message:  internal error: entered unreachable code: ICE: Should have been in cache v20 Instruction { instruction: Id(15), position: 0, typ: Array([Numeric(NativeField)], 12) }
Location: compiler/noirc_evaluator/src/acir/mod.rs:1000
```

### To Reproduce

See above.

### Workaround

None

### Workaround Description

_No response_

### Additional Context

_No response_

### Project Impact

None

### Blocker Context

_No response_

### Nargo Version

nargo version = 1.0.0-beta.5 noirc version = 1.0.0-beta.5+c233781fc1fc6124c6047f30144f74c471eb2dc2 (git version hash: b219fc089deb4cc1ee688fe0b30ac403df67d150, is dirty: true)

### NoirJS Version

_No response_

### Proving Backend Tooling & Version

_No response_

### Would you like to submit a PR for this Issue?

None

### Support Needs

_No response_

### PR DESCRIPTION
**Pull request by vezenovm**
# Description

## Problem\*

Resolves #8451 

## Summary\*

I expanded the `is_valid_for_program_input` cases for array and string by calling a new `array_or_string_len_is_not_zero` method.

## Documentation\*

Check one:
- [ ] No documentation needed.
- [X] Documentation included in this PR.
- [ ] **[For Experimental Features]** Documentation to be submitted in a separate PR.

# PR Checklist\*

- [X] I have tested the changes locally.
- [X] I have formatted the changes with [Prettier](https://prettier.io/) and/or `cargo fmt` on default settings.

### CODE REVIEW

File: compiler/noirc_frontend/src/hir_def/types.rs [hunk 1]
```diff
@@ -1314,6 +1318,24 @@ impl Type {
...
+    /// The point of inputs to entry points is to process input data. 
+    /// Thus, passing empty arrays is pointless and adds extra complexity to the compiler
+    /// for handling them.
+    fn array_or_string_len_is_not_zero(&self) -> bool {
+        match self {
+            Type::Array(length, _) | Type::String(length) => {
+                let length = length
+                .evaluate_to_u32(Location::dummy())
+                .expect("Cannot have variable sized arrays as a parameter to main");
+                length != 0
```
Comment (jfecher) [inline compiler/noirc_frontend/src/hir_def/types.rs:1333]:
```suggestion
                let length = length
                    .evaluate_to_u32(Location::dummy())
                    .unwrap_or(0);
                length != 0
```
I think we should avoid a panic here

**Review by jfecher — APPROVED** [review]
There's no reason to allow these anyway

**Comment by vezenovm** [comment]
> **regression_8261_inliner_max**	-17 ✅	**-8.46%**
> **regression_8261_inliner_min**	-17 ✅	**-8.46%**
> **regression_8261_inliner_zero**	-17 ✅	**-8.46%**

A parameter (emtyp string) was removed from these tests so this makes sense.

**Comment by TomAFrench** [comment]
@vezenovm there's a couple of test failures here.

**Comment by vezenovm** [comment]
> @vezenovm there's a couple of test failures here.

Yeah I'm fixing them right now

**Comment by vezenovm** [comment]
One caveat of this PR is that if someone provides an incorrect numeric generic types to an array we will trigger this error as well now as the array type will have failed to resolve. This snippet is `compile_failure/brillig_vec_to_acir`
```noir
global DEPTH: Field = 40000;
fn main(x: [u32; DEPTH], y: u32) {
    let mut new_x = Vec::new();
    new_x = clear(x, y);
}
unconstrained fn clear(x: [u32; DEPTH], y: u32) -> Vec<u32> {
    let mut a = Vec::new();
    for i in 0..y {
        a.push(x[i]);
    }
    a
}
```
It previously had this stderr:
```
error: The numeric generic is not of type `u32`
  ┌─ src/main.nr:3:12
  │
3 │ fn main(x: [u32; DEPTH], y: u32) {
  │            ------------ expected `u32`, found `Field`
  │

error: The numeric generic is not of type `u32`
  ┌─ src/main.nr:8:27
  │
8 │ unconstrained fn clear(x: [u32; DEPTH], y: u32) -> Vec<u32> {
  │                           ------------ expected `u32`, found `Field`
  │

error: Call to unconstrained function is unsafe and must be in an unconstrained function or unsafe block
  ┌─ src/main.nr:5:13
  │
5 │     new_x = clear(x, y);
  │             -----------
  │

error: Slices cannot be returned from an unconstrained runtime to a constrained runtime
  ┌─ src/main.nr:5:13
  │
5 │     new_x = clear(x, y);
  │             -----------
  │

Aborting due to 4 previous errors
```
It now has this stderr:
```
error: The numeric generic is not of type `u32`
  ┌─ src/main.nr:3:12
  │
3 │ fn main(x: [u32; DEPTH], y: u32) {
  │            ------------ expected `u32`, found `Field`
  │

error: Only sized types may be used in the entry point to a program
  ┌─ src/main.nr:3:12
  │
3 │ fn main(x: [u32; DEPTH], y: u32) {
  │            ------------ Slices, references, or any type containing them may not be used in main, contract functions, or foldable functions
  │

error: The numeric generic is not of type `u32`
  ┌─ src/main.nr:8:27
  │
8 │ unconstrained fn clear(x: [u32; DEPTH], y: u32) -> Vec<u32> {
  │                           ------------ expected `u32`, found `Field`
  │

error: Call to unconstrained function is unsafe and must be in an unconstrained function or unsafe block
  ┌─ src/main.nr:5:13
  │
5 │     new_x = clear(x, y);
  │             -----------
  │

error: Slices cannot be returned from an unconstrained runtime to a constrained runtime
  ┌─ src/main.nr:5:13
  │
5 │     new_x = clear(x, y);
  │             -----------
  │

Aborting due to 5 previous errors
```
For the purpose of the test I switched to using a `u32` type for the array input as that is not what this code is testing. But just noting here.
