### PR TITLE
fix: reference aliases in if_else arrays

### LINKED ISSUE #10606: In Brillig, accessing a mutable reference boolean array element can break
### Aim

The following code:

```rust
fn main() {
    unsafe {
        foo();
    }
}

unconstrained fn foo() {
    bar([&mut false]);
}

unconstrained fn bar(mut c: [&mut bool; 1]) -> bool {
    let mut a = false;
    for _ in 0..3 {
        c = if *c[0_u32] { c } else { [(&mut a)] };
    }
    false
}
```

produces this error:
```
error: Assertion failed: 'Bit size for value 254 does not match the expected bit size 1'
   ┌─ src/main.nr:14:17
   │
14 │         c = if *c[0_u32] { c } else { [(&mut a)] };
   │                 --------
   │
   = Call stack:
     1. src/main.nr:3:9
     2. src/main.nr:8:5
     3. src/main.nr:14:17
```

(resubmitting this as an issue after [publishing](https://github.com/noir-lang/noir/security/advisories/GHSA-r693-v6fg-mvqw))

### Expected Behavior

The code executes successfully.

### Bug

```
$ nargo execute --force
error: Assertion failed: 'Bit size for value 254 does not match the expected bit size 1'
   ┌─ src/main.nr:14:17
   │
14 │         c = if *c[0_u32] { c } else { [(&mut a)] };
   │                 --------
   │
   = Call stack:
     1. src/main.nr:3:9
     2. src/main.nr:8:5
     3. src/main.nr:14:17
```

### To Reproduce

1.
2.
3.
4.

### Workaround

None

### Workaround Description

_No response_

### Additional Context

_No response_

### Project Impact

None

### Blocker Context

_No response_

### Nargo Version

_No response_

### NoirJS Version

_No response_

### Proving Backend Tooling & Version

_No response_

### Would you like to submit a PR for this Issue?

None

### Support Needs

_No response_

### PR DESCRIPTION
**Pull request by guipublic**
# Description

## Problem

Resolves #10606 

## Summary
Track references in arrays returned by if_else

## User Documentation

Check one:
- [X] No user documentation needed.
- [ ] Changes in _docs/_ included in this PR.
- [ ] **[For Experimental Features]** Changes in _docs/_ to be submitted in a separate PR.

# PR Checklist

- [X] I have tested the changes locally.
- [X] I have formatted the changes with [Prettier](https://prettier.io/) and/or `cargo fmt` on default settings.

### CODE REVIEW

File: compiler/noirc_evaluator/src/ssa/opt/mem2reg.rs [hunk 1]
```diff
@@ -489,6 +489,21 @@ impl<'f> PerFunctionContext<'f> {
...
+                        let known_aliases =
+                            references.get_aliases_for_value(known_value).into_owned();
+                        if !known_aliases.is_unknown() {
+                            let expr = Expression::Other(result);
+                            references.expressions.insert(result, expr);
+                            references.aliases.insert(expr, known_aliases);
+                        }
+                    }
+                }
+
```
Comment (vezenovm) [inline compiler/noirc_evaluator/src/ssa/opt/mem2reg.rs]:
```suggestion
```
It is unclear to me why this is needed. If we have a known value for a load address we will immediately remove the result and replace it with the known value. It feels roundabout to insert an alias for that result which will immediately be mapped to a new value. The transferring of aliases is already happening implicitly. The new test also passes for me when I remove this snippet.

Comment (guipublic) [reply compiler/noirc_evaluator/src/ssa/opt/mem2reg.rs]: I confirm that both the unit test and the example in the issue are working without this, so I removed it.
