### PR TITLE
fix(acir): prevent mixed constant/witness scalar pairs in MSM opcode

### LINKED ISSUE #12034: Scalar multiplication leads to assertion failure during `bb write_vk`
### Aim

`embedded_curve_ops::fixed_base_scalar_mul` with scalar `2**128` sometimes leads to assertion failures when executing `bb write_vk`.
It works as expected for other values, like `(2**128) + 1` or `(2**128) - 1`.

### Expected Behavior

`bb write_vk` succeeds.

### Bug

main.nr:
```
use dep::std;

pub fn main(inp : bool) {
    if (inp)
    {
        let scalar = std::embedded_curve_ops::EmbeddedCurveScalar::from_field((340282366920938463463374607431768211456));
        let point = std::embedded_curve_ops::fixed_base_scalar_mul(scalar);
    }
}
```

Nargo.toml:
```
[package]
name = "Test"
type = "bin"
authors = [""]
compiler_version = "1.0.0"

[dependencies]
```

Compilation succeeds, but executing `bb write_vk` leads to the following error:
```
Scheme is: ultra_honk, num threads: 22 (mem: 8.77 MiB)
Assertion failed: (!(scalar_lo.is_constant && !scalar_hi.is_constant))
Reason   : to_grumpkin_scalar: scalar_lo is constant while scalar_hi is not.
```

### To Reproduce

1. `nargo compile`
2. `bb write_vk -b ./target/Test.json -o ./vk`

### Workaround

None

### Workaround Description

_No response_

### Additional Context

_No response_

### Project Impact

None

### Blocker Context

_No response_

### Nargo Version

nargo version = 1.0.0-beta.19 noirc version = 1.0.0-beta.19+a25d8109ab8e8c31d8c6b7bb4d68452cfec113c5

### NoirJS Version

_No response_

### Proving Backend Tooling & Version

bb 4.0.4 and 5.0.0-nightly.20260320

### Would you like to submit a PR for this Issue?

None

### Support Needs

_No response_

### PR DESCRIPTION
**Pull request by TomAFrench**
## Summary

- The backend's `to_grumpkin_scalar` asserts that both halves (lo, hi) of an `EmbeddedCurveScalar` are either both constants or both witnesses. ACIRgen was allowing mixed pairs — e.g. when a scalar with `lo=0, hi=1` is used inside an `if` block, after flattening `0 * predicate` stays constant while `1 * predicate` becomes a witness.
- Apply the same `all_or_nothing_coordinates` pattern already used for `EmbeddedCurveAdd` point coordinates to both MSM point coordinates and scalar pairs.
- Add doc comments on the `MultiScalarMul` and `EmbeddedCurveAdd` ACIR opcodes noting this backend restriction.
- Add regression test `regression_12034`.

Closes #12034

## Test plan

- [x] `cargo nextest run -p nargo_cli --test execute regression_12034` — 16/16 pass
- [x] `cargo nextest run -p nargo_cli --test execute embedded_curve` — 21/21 pass
- [x] ACIR output confirms scalars are `[w3, w0]` (both witnesses) instead of mixed

### CODE REVIEW

File: compiler/noirc_evaluator/src/acir/acir_context/black_box.rs [hunk 1]
```diff
@@ -167,6 +171,43 @@ impl<F: AcirField> AcirContext<F> {
...
+            let inf = AcirValue::Var(chunk[2].0, chunk[2].1);
+            for input in self.all_or_nothing_coordinates(x, y)? {
+                points_inputs.extend(input);
+            }
+            points_inputs.extend(self.prepare_input_for_black_box_func_call(inf, true)?);
+        }
+
+        // Scalars: each is (lo, hi).
+        let mut scalars_inputs = Vec::new();
+        for chunk in self.flatten(scalars)?.chunks(2) {
```
Comment (vezenovm) [inline compiler/noirc_evaluator/src/acir/acir_context/black_box.rs:199]: nit: `all_or_nothing_coordinates` flattens the AcirValue input. This de-structuring feels redundant. I guess we are just trying to follow what we did for `points`. However, there we have the `inf` flag as well.
