### PR TITLE
fix: improve reference coercion logic

### LINKED ISSUE #10529: Ownership: dereferencing `&u32` failing with `Expected type &mut _, found type &u32`
### Aim

I attempted to compile the following program with `-Zownership` enabled:

```noir
fn main() {
  let x: u32 = 0;
  let y: &u32 = &x;
  let _: u32 = *y;
}
```

As per the following documentation at https://noir-lang.org/docs/noir/concepts/data_types/references (Version: `v1.0.0-beta.15`):

```
You can use Rust-like syntax to use pointers in Noir: the & operator references the variable, the * operator dereferences it.
```

### Expected Behavior

I expected the program to compile successfully

### Bug

```bash
❯ ~/.nargo/bin/nargo compile -Zownership
error: Expected type &mut _, found type &u32
  ┌─ src/main.nr:4:16
  │
4 │   let _: u32 = *y;
  │                --
  │

Aborting due to 1 previous error
```

### To Reproduce

1.
2.
3.
4.

### Workaround

None

### Workaround Description

_No response_

### Additional Context

_No response_

### Project Impact

None

### Blocker Context

_No response_

### Nargo Version

nargo version = 1.0.0-beta.15 noirc version = 1.0.0-beta.15+881acee6c8df42adb85ff0b9bc9ad144b43bdf6b (git version hash: 881acee6c8df42adb85ff0b9bc9ad144b43bdf6b, is dirty: false)

### NoirJS Version

_No response_

### Proving Backend Tooling & Version

_No response_

### Would you like to submit a PR for this Issue?

None

### Support Needs

_No response_

### PR DESCRIPTION
**Pull request by guipublic**
# Description

## Problem

Resolves #10529

## Summary
unify immutable references 

## User Documentation

Check one:
- [X] No user documentation needed.
- [ ] Changes in _docs/_ included in this PR.
- [ ] **[For Experimental Features]** Changes in _docs/_ to be submitted in a separate PR.

# PR Checklist

- [X] I have tested the changes locally.
- [X] I have formatted the changes with [Prettier](https://prettier.io/) and/or `cargo fmt` on default settings.

### CODE REVIEW

File: compiler/noirc_frontend/src/hir_def/types/unification.rs [hunk 1]
```diff
@@ -628,23 +628,26 @@ impl Type {
...
-            (&this, &target)
-        {
-            // Still have to ensure the element types match.
-            // Don't need to issue an error here if not, it will be done in unify_with_coercions
-            let mut bindings = TypeBindings::default();
-            if this_elem.try_unify(target_elem, &mut bindings).is_ok() {
-                Self::apply_type_bindings(bindings);
-                return true;
+        match (&this, &target) {
+            // Coerce `&mut T` to `&T`, or unify`&T` with `&T`
```
Comment (vezenovm) [inline compiler/noirc_frontend/src/hir_def/types/unification.rs]:
```suggestion
            // Coerce `&mut T` to `&T`, or unify `&T` with `&T`
```

Comment (jfecher) [inline compiler/noirc_frontend/src/hir_def/types/unification.rs]: Can you elaborate on why we need to match `&T` with `&T`? I would think this should already be done by the normal unification case and we shouldn't need coercions for this.

Comment (guipublic) [reply compiler/noirc_frontend/src/hir_def/types/unification.rs]: The normal unification can fail with unbound type variables.

Comment (jfecher) [reply compiler/noirc_frontend/src/hir_def/types/unification.rs]: Can you give an example?

Comment (guipublic) [reply compiler/noirc_frontend/src/hir_def/types/unification.rs]: the example from the issue (also added in dereference_immutable_reference() unit test)
```
fn main() {
  let x: u32 = 0;
  let y: &u32 = &x;
  let _: u32 = *y;
}
```

Comment (jfecher) [reply compiler/noirc_frontend/src/hir_def/types/unification.rs]: I don't see where the unbound type variables are in this example? Every type should be annotated

Comment (jfecher) [reply compiler/noirc_frontend/src/hir_def/types/unification.rs]: Discussed on slack, the fix is in `try_reference_coercion` because `prefix_operand_type_rules` explicitly calls that function while dereferencing:
```rs
                if !rhs_type.try_reference_coercion(&immutable) {
                    self.unify(rhs_type, &mutable, || TypeCheckError::TypeMismatch {
```
Both these lines could either be replaced with a `unify_with_coercions` or we could fix try_reference_coercion as is done in this PR.
