### PR TITLE
fix: check type instead of assuming a vector

### LINKED ISSUE #10977: Forbid arrays storing inside of `self.slice_sizes`
## Description

We should never store arrays to in the `self.slice_sizes` map because a call to the black_box hint hits an assertion failure that is caught at compilation thanks to the defensive design.

## Proof of Concept

It can be done by calling the `as_slice` intrinsic and then calling the `black_box` function with the same array used:
```noir
fn main(flag: bool, arr: [Field; 4]) {
    let sli = arr.as_slice();
    println(sli);
    std::hint::black_box(arr);
}
```

```sh
The application panicked (crashed).
Message:  assertion failed: matches!(arguments_types.last().unwrap(), Type::Slice(_))
Location: compiler/noirc_evaluator/src/ssa/opt/remove_if_else.rs:372
```

## Recommendation

```diff
diff --git a/compiler/noirc_evaluator/src/ssa/opt/remove_if_else.rs b/compiler/noirc_evaluator/src/ssa/opt/remove_if_else.rs
index 307b230046..82215d5d15 100644
--- a/compiler/noirc_evaluator/src/ssa/opt/remove_if_else.rs
+++ b/compiler/noirc_evaluator/src/ssa/opt/remove_if_else.rs
@@ -267,7 +267,10 @@ impl Context {
             Entry::Occupied(entry) => *entry.get(),
             Entry::Vacant(entry) => {
                 if let Some(length) = dfg.try_get_slice_capacity(value) {
-                    return *entry.insert(length);
+                    if !matches!(dfg.type_of_value(value), Type::Array(_, _)) {
+                        entry.insert(length);
+                    }
+                    return length;
                 }
                 // For non-constant slices we can't tell the size, which would mean we can't merge it.
                 let dbg_value = &dfg[value];
```

### PR DESCRIPTION
**Pull request by guipublic**
# Description

## Problem

Resolves #10977

## Summary
Check for vector type because vector_sizes may also contain arrays

## User Documentation

Check one:
- [X] No user documentation needed.
- [ ] Changes in _docs/_ included in this PR.
- [ ] **[For Experimental Features]** Changes in _docs/_ to be submitted in a separate PR.

# PR Checklist

- [X] I have tested the changes locally.
- [X] I have formatted the changes with [Prettier](https://prettier.io/) and/or `cargo fmt` on default settings.

### CODE REVIEW

File: compiler/noirc_evaluator/src/ssa/opt/remove_if_else.rs [hunk 1]
```diff
@@ -408,10 +408,12 @@ impl Context {
...
-
+ 
                 let mut changes = Vec::new();
                 for (i, argument) in arguments.iter().enumerate() {
-                    if self.vector_sizes.contains_key(argument) {
+                    if self.vector_sizes.contains_key(argument)
+                        && matches!(dfg.type_of_value(*argument), Type::Vector(_))
+                    {
                         assert!(matches!(arguments_types[i - 1], Type::Numeric(_)));
                         assert!(matches!(arguments_types[i], Type::Vector(_)));
```
Comment (asterite) [inline compiler/noirc_evaluator/src/ssa/opt/remove_if_else.rs]: The `matches!` on line 415 is more or less the same as the one in line 418, because `arguments_types[i]` will be `dfg.type_of_value(*argument)`.
```suggestion
                        && matches!(arguments_types[i], Type::Vector(_))
                    {
assert!(matches!(arguments_types[i - 1], Type::Numeric(_)));
```

Comment (guipublic) [reply compiler/noirc_evaluator/src/ssa/opt/remove_if_else.rs]: Done

File: compiler/noirc_evaluator/src/ssa/opt/remove_if_else.rs [hunk 2]
```diff
@@ -411,9 +411,10 @@ impl Context {
 
                 let mut changes = Vec::new();
                 for (i, argument) in arguments.iter().enumerate() {
-                    if self.vector_sizes.contains_key(argument) {
+                    if self.vector_sizes.contains_key(argument)
+                        && matches!(dfg.type_of_value(*argument), Type::Vector(_))
```
Comment (asterite) [inline compiler/noirc_evaluator/src/ssa/opt/remove_if_else.rs]: I still think we can check the type of `argument_types[i]` here instead of calling `dfg.type_of_value` again.

Comment (asterite) [reply compiler/noirc_evaluator/src/ssa/opt/remove_if_else.rs]: (sorry if I did the diff wrong last time)

**Review by asterite — APPROVED** [review]

File: compiler/noirc_evaluator/src/ssa/opt/remove_if_else.rs (hunk 2 above)
Comment (guipublic) [reply compiler/noirc_evaluator/src/ssa/opt/remove_if_else.rs]: Thank you for the clarification, it's done.
