### PR TITLE
fix(frontend): Error on unsupported integer annotation

### LINKED ISSUE #2623: Incorrect range of u128
### Aim

The range of `u128` is incorrectly specified as `0..0`.

To see that, try to compile the following code:

```rust
let x: u128 = 1;
```

The compiler would throw an error:

```text
error: The literal `1` cannot fit into `u128` which has range `0..=0`
```

### Expected Behavior

The compiler should not throw an error on the above code.

### Bug

Create a project with `nargo new range_bug`, then save the following piece of code in to `src/main.nr`:

```rust
fn main() {
    let x: u128 = 1;
}
```

Then run `nargo check` and observe the following error:

```text
warning: unused variable x
  ┌─ /home/Jurarpereurs/range_bug/src/main.nr:2:9
  │
2 │     let x: u128 = 1;
  │         - unused variable
  │

error: The literal `1` cannot fit into `u128` which has range `0..=0`
  ┌─ /home/Jurarpereurs/range_bug/src/main.nr:2:19
  │
2 │     let x: u128 = 1;
  │                   -
  │

Error: Aborting due to 1 previous error

Location:
    crates/nargo_cli/src/cli/mod.rs:91:5
```

### To Reproduce

Run the following commands:

```bash
nargo new range_bug
cd range_bug
cat << EOF > src/main.nr
fn main() {
    let x: u128 = 1;
}
EOF
nargo check
```

### Installation Method

Binary

### Nargo Version

nargo 0.11.1 (git version hash: 39e1433a9c4184b72f3c5ab0368cfaa5d4ce537b, is dirty: false)

### Additional Context

_No response_

### Would you like to submit a PR for this Issue?

No

### Support Needs

_No response_

### PR DESCRIPTION
**Pull request by vezenovm**
# Description

## Problem\*

Resolves #2623 

closes #2638 

## Summary\*

~~We lint on overflowing integer assignment by checking the rhs expr against the annotated type during `check_declaration` in type check. However, this error can be deceiving to users who attempt to annotate their program with `u128` which we do not support.~~

This PR checks the max bits against `FieldElement::max_num_bits() / 2` rather than just `FieldElement::max_num_bits()`

The line in the issue:
```
let q: u128 = 1;
```
will now error out with the below:
Screenshot 2023-09-21 at 10 53 47 PM

## Documentation

- [ ] This PR requires documentation updates when merged.

  

  - [ ] I will submit a noir-lang/docs PR.

  

  - [ ] I will request for and support Dev Rel's help in documenting this PR.

  
  

## Additional Context

# PR Checklist\*

- [X] I have tested the changes locally.
- [X] I have formatted the changes with [Prettier](https://prettier.io/) and/or `cargo fmt` on default settings.

### CODE REVIEW

File: compiler/noirc_frontend/src/hir/type_check/stmt.rs [hunk 1]
```diff
@@ -265,8 +266,17 @@ impl<'interner> TypeChecker<'interner> {
...
-            if annotated_type.is_unsigned() {
-                self.lint_overflowing_uint(&rhs_expr, &annotated_type);
+            if let Some(bit_size) = annotated_type.bit_size() {
+                let max_integer_bit_size = FieldElement::max_num_bits() / 2;
+                if bit_size > max_integer_bit_size {
+                    self.errors.push(TypeCheckError::UnsupportedIntegerSize {
+                        num_bits: bit_size,
+                        max_num_bits: max_integer_bit_size,
+                        span: expr_span,
+                    });
```
Comment (jfecher) [inline compiler/noirc_frontend/src/hir/type_check/stmt.rs:276]: Why do we only check this on a variable declaration? And why do we allow u128 to get all the way to typechecking at all if it is unsupported? Can we just error in the parser or even lexer instead?

Comment (vezenovm) [reply compiler/noirc_frontend/src/hir/type_check/stmt.rs]: Good call. Turns out we have a max bits check in the lexer already but we just check against the FieldElement max bits rather than `FieldElement::max_num_bits / 2`. I ended up just dividing the max bits by 2.

**Review by jfecher — APPROVED** [review]
👍
