### PR TITLE
fix: Improve member access error

### LINKED ISSUE #939: Improve error message for unknown fields of inferred types
# Problem

Trying the code:
```rs
fn main() {
    let _f = |x| x.foo;
}
```
Fails with the error
```
error: Type _ has no member named x
  ┌─ /.../src/main.nr:3:20
  │
3 │     let _f = |foo| foo.x;
  │                    ---

error: aborting due to 1 previous errors
```
which can be made clearer to users that a type annotation should be added before that point.

# Solution

We should special-case this error to suggest adding a type annotation if a user tries to do field access on a type variable.

For reference, rustc's error message here is:
```rs
error[E0282]: type annotations needed
 --> src/main.nr:3:15
  |
3 |     let _f = |foo| foo.x;
  |               ^^^  --- type must be known at this point
  |
help: consider giving this closure parameter an explicit type
  |
3 |     let _f = |foo: _| foo.x;
  |                  +++
```

### PR DESCRIPTION
**Pull request by jfecher**
# Related issue(s)

Resolves #939

# Description

Improves our error message when users try to access fields of an inferred type.

## Summary of changes

The previous error message:
```rs
error: Type _ has no member named x
  ┌─ /.../src/main.nr:3:20
  │
3 │     let _f = |foo| foo.x;
  │                    ---

error: aborting due to 1 previous errors
```
The new error message:
```
error: Type annotations needed before this point.
  ┌─ /.../src/main.nr:3:20
  │
3 │     let _f = |foo| foo.x;
  │                    --- Try adding a type annotation for this value before it is used here

error: aborting due to 1 previous errors
```

## Dependency additions / changes

None

## Test additions / changes

None

# Checklist

- [x] I have tested the changes locally.
- [x] I have formatted the changes with [Prettier](https://prettier.io/) and/or `cargo fmt` with default settings.
- [x] I have [linked](https://docs.github.com/en/issues/tracking-your-work-with-issues/linking-a-pull-request-to-an-issue) this PR to the issue(s) that it resolves.
- [x] I have reviewed the changes on GitHub, line by line.
- [x] I have ensured all changes are covered in the description.
- [ ] This PR requires documentation updates when merged.

# Additional context

None

### CODE REVIEW

File: crates/noirc_frontend/src/hir/type_check/errors.rs [hunk 1]
```diff
@@ -96,6 +98,11 @@ impl From<TypeCheckError> for Diagnostic {
                 format!("return type is {typ}"),
                 span,
             ),
+            TypeCheckError::TypeAnnotationsNeeded { span } => Diagnostic::simple_error(
+                "Type annotations needed before this point.".to_string(),
+                "Try adding a type annotation for this value before it is used here".to_string(),
```
Comment (guipublic) [inline crates/noirc_frontend/src/hir/type_check/errors.rs:103]: I think the rust message is clearer and would prefer that we use it instead:
Replace "Try adding a type annotation for this value before it is used here"
with: "type must be known at this point"

Comment (jfecher) [reply crates/noirc_frontend/src/hir/type_check/errors.rs]: This is a bit repetitive with the first line of the message so I've updated to change both lines

**Review by guipublic — APPROVED** [review]
