### PR TITLE
fix: update `in_contract` flag before handling function metadata in elaborator

### LINKED ISSUE #5288: Elaborator doesn't correctly detect we are in_contract
### Aim

Compile aztec packages with the new elaborator

### Expected Behavior

```rust 
contract ElaboratorContract {
    #[recursive]
    fn contract_entrypoint() -> Field {
        1
    }
}
```

This should compile

### Bug

The new elaborator doesn't correctly detect we are inside a contract, and as such every check for entrypoint functions fail. Most obvious errors come from trying to use attributes such as `#[recursive]` or `#[abi(tag)]`

### To Reproduce

Try to compile the example above, the compiler will return 
Screenshot 2024-06-19 at 12 03 31

### Project Impact

Blocker

### Impact Context

_No response_

### Workaround

None

### Workaround Description

_No response_

### Additional Context

_No response_

### Installation Method

Compiled from source

### Nargo Version

_No response_

### NoirJS Version

_No response_

### Would you like to submit a PR for this Issue?

None

### Support Needs

_No response_

### PR DESCRIPTION
**Pull request by TomAFrench**
…

# Description

## Problem\*

Resolves #5288 

## Summary\*

This PR fixes #5288 by updating `self.in_contract` before we define function metadata to match `self.local_module`. This is mildly hacky and we may want to have a nicer "switch modules and update everything which depends on it" helper function in future.

## Documentation\*

Check one:
- [x] No documentation needed.
- [ ] Documentation included in this PR.
- [ ] **[For Experimental Features]** Documentation to be submitted in a separate PR.

# PR Checklist\*

- [x] I have tested the changes locally.
- [x] I have formatted the changes with [Prettier](https://prettier.io/) and/or `cargo fmt` on default settings.

### CODE REVIEW

File: compiler/noirc_frontend/src/elaborator/mod.rs [hunk 1]
```diff
@@ -1302,6 +1302,7 @@ impl<'context> Elaborator<'context> {
 
         for (local_module, id, func) in &mut function_set.functions {
             self.local_module = *local_module;
+            self.in_contract = self.module_id().module(self.def_maps).is_contract;
```
Comment (jfecher) [inline compiler/noirc_frontend/src/elaborator/mod.rs:1305]: We should set `in_contract` back to false or its previous value after the call as well
