### PR TITLE
fix: Implement constant folding during the mem2reg pass

### LINKED ISSUE #2445: Constant fold during mem2reg pass
### Problem

Even after being updated to handle aliases within arrays (in an experimental branch), the mem2reg pass still fails to fully remove all loads and stores from the following code:
```rs
fn main() {
    let mut var = 0;
    let ref = &mut &mut var;

    let mut array = [ref, ref];

    **array[0] = 1;
    **array[1] = 2;

    assert(var == 2);
    assert(**ref == 2);
    assert(**array[0] == 2);
    assert(**array[1] == 2);
}
```
This is because when optimizing out references stored in arrays, mem2reg can only do one step at a time. That is, it can optimize until it finds a  `v3 = array_get [v1, v2], index 1`. It cannot see which reference is returned until the constant folding pass is done, so it counts `v3` as opaque which prevents further optimizations on it.

The problem occurs when `v3` is later loaded/stored to. We now need another mem2reg pass after the constant folding pass. Then, if there are more gets/sets to the array we'd need another constant folding pass and so on. Each time we run an entire pass, only 1 additional step of this will be optimized each time.

### Happy Case

We should apply instruction simplifications while running the mem2reg pass, like we do with most other optimization passes. This would enable the pass to optimize the code in the snippet in one run without the need of another mem2reg pass or even a constant folding pass after.

### Alternatives Considered

_No response_

### Additional Context

_No response_

### Would you like to submit a PR for this Issue?

No

### Support Needs

_No response_

### PR DESCRIPTION
**Pull request by jfecher**
# Description

## Problem\*

Resolves #2445

## Summary\*

This is the second PR of mem2reg updates and requires the array aliasing PR to work.

This PR changes mem2reg to also perform constant folding while doing the pass instead of calling `set_value_from_id`. The reasoning for this is given in #2445 but in short, you could run into situations before where after mem2reg, constant folding would find and stop at another reference, necessitating another mem2reg and constant folding pass, and so in. So if you had N mem2reg + constant folding passes you could always construct a program that required N + 1. Performing constant folding during mem2reg breaks this dependency as now an `array_get` instruction that can be simplified is simplified out immediately instead of remaining as an opaque alias to some unknown reference.

## Documentation

- [ ] This PR requires documentation updates when merged.

  

  - [ ] I will submit a noir-lang/docs PR.

  

  - [ ] I will request for and support Dev Rel's help in documenting this PR.

  
  

## Additional Context

# PR Checklist\*

- [x] I have tested the changes locally.
- [x] I have formatted the changes with [Prettier](https://prettier.io/) and/or `cargo fmt` on default settings.

### CODE REVIEW

File: crates/noirc_evaluator/src/ssa/ir/function_inserter.rs [hunk 1]
```diff
@@ -30,7 +30,7 @@ impl<'f> FunctionInserter<'f> {
     pub(crate) fn resolve(&mut self, mut value: ValueId) -> ValueId {
         value = self.function.dfg.resolve(value);
         match self.values.get(&value) {
-            Some(value) => *value,
+            Some(value) => self.resolve(*value),
```
Comment (jfecher) [inline crates/noirc_evaluator/src/ssa/ir/function_inserter.rs:33]: Since we're load results to their known results in the mem2reg pass, we can have situations now where a mapped value (e.g. the result of an array_get containing a reference) is itself mapped to another value (the value of that reference).

File: crates/noirc_frontend/src/parser/parser.rs [hunk 2]
```diff
@@ -549,18 +547,16 @@ fn where_clause() -> impl NoirParser<Vec<TraitConstraint>> {
...
             result
         })
 }
 
 fn trait_bounds() -> impl NoirParser<Vec<TraitBound>> {
-    trait_bound()
-        .separated_by(just(Token::Plus))
-        .at_least(1)
-        .allow_trailing()
+    trait_bound().separated_by(just(Token::Plus)).at_least(1).allow_trailing()
```
Comment (jfecher) [inline crates/noirc_frontend/src/parser/parser.rs:559]: These were all done by `cargo fmt`

**Comment by jfecher** [comment]
Also fixes #2221

File: crates/noirc_evaluator/src/ssa/ir/function_inserter.rs [hunk 3]
```diff
@@ -47,12 +47,18 @@ impl<'f> FunctionInserter<'f> {
...
+        if key != value {
+            self.values.entry(key).or_insert(value);
+        }
     }
 
     /// Insert a key, value pair in the map
     pub(crate) fn map_value(&mut self, key: ValueId, value: ValueId) {
-        self.values.insert(key, value);
+        if key == value {
+            self.values.remove(&key);
```
Comment (vezenovm) [inline crates/noirc_evaluator/src/ssa/ir/function_inserter.rs:58]: So for `map_value` we remove the key if `key == value`, but in try_map_value we don't attempt to remove if `key == value`. Could you elaborate a bit more on this reasoning?

Comment (jfecher) [reply crates/noirc_evaluator/src/ssa/ir/function_inserter.rs:58]: We remove the key if `key == value` since if `key` isn't in the map in `resolve`, we default to the key anyway. Previously mapping key to itself was valid and did the same thing explicitly, but now that we resolve recursively it'd lead to an infinite loop.

`try_map_value` only does something if the key isn't already in the map, so if the key isn't already in the map and `key == value`, we want to remove it normally but we already know it isn't in the map

File: crates/noirc_evaluator/src/ssa/opt/mem2reg.rs [hunk 4]
```diff
@@ -899,18 +906,7 @@ mod tests {
...
-                let rhs =
-                    main.dfg.get_numeric_constant(binary.rhs).expect("Expected constant value");
-
-                assert_eq!(lhs, rhs);
-                assert_eq!(lhs, FieldElement::from(2u128));
-            }
-            _ => unreachable!(),
-        }
+        // We expect the last eq to be optimized out
+        assert_eq!(b1_instructions.len(), 1);
```
Comment (vezenovm) [inline crates/noirc_evaluator/src/ssa/opt/mem2reg.rs:910]: Nit: we should update the expected result comment to reflect the assert

**Review by vezenovm — COMMENTED** [review]
LGTM just a couple small comments

File: crates/noirc_evaluator/src/ssa/ir/function_inserter.rs (hunk 3 above)
Comment (vezenovm) [reply crates/noirc_evaluator/src/ssa/ir/function_inserter.rs:58]: Thanks that makes sense

Comment (jfecher) [reply crates/noirc_evaluator/src/ssa/ir/function_inserter.rs:58]: I'll add a comment explaining this

Comment (jfecher) [reply crates/noirc_evaluator/src/ssa/ir/function_inserter.rs:62]: I ended up just adding the case with a small comment. It is technically unneeded but we shouldn't hit that case anyway and it makes the code easier to understand.

**Review by vezenovm — APPROVED** [review]
