### PR TITLE
fix: correctly detect signed/unsigned integer overflows/underflows

### LINKED ISSUE #5372: Integer literal overflow/underflow doesn't always error
### Aim

The compiler should error when integer literals don't fit the target integer type. This is already done in some cases, but not in all of them and not always correctly. Some examples:

```rust
let x: u8 = -1; // Should error, minimum is 0

let x: i8 = 128; // Should error, maximum is 127
let x: i8 = -129; // Should error, minimum is -128

let x: i8 = 256; // Correctly errors, because it checks against 255
let x: u8 = 256; // Correctly errors, because it checks against 255
```

(and similarly for other integer types)

### Expected Behavior

This program should fail to compile:

```rust
fn main() {
    let x: i8 = 128;
    println(x);
}
```

### Bug

The program successfully compiles and executing it prints "-128".

### To Reproduce

_No response_

### Project Impact

None

### Impact Context

_No response_

### Workaround

None

### Workaround Description

_No response_

### Additional Context

_No response_

### Installation Method

None

### Nargo Version

_No response_

### NoirJS Version

_No response_

### Would you like to submit a PR for this Issue?

Yes

### Support Needs

_No response_

### PR DESCRIPTION
**Pull request by asterite**
# Description

## Problem

Resolves #5372

## Summary

Correctly detects overflows/underflows for basic integer types. The sign of a field element value is now also propagated to the ssa phase. But previously, the field value was applied some casting before reaching the ssa phase so checking that value like that was a bit strange. In this PR that conversion is delayed until the ssa phase, and the value can be checked prior to that conversion.

## Additional Context

None.

## Documentation

Check one:
- [x] No documentation needed.
- [ ] Documentation included in this PR.
- [ ] **[For Experimental Features]** Documentation to be submitted in a separate PR.

# PR Checklist\*

- [x] I have tested the changes locally.
- [x] I have formatted the changes with [Prettier](https://prettier.io/) and/or `cargo fmt` on default settings.

### CODE REVIEW

File: compiler/noirc_evaluator/src/ssa/ir/types.rs [hunk 1]
```diff
@@ -31,12 +31,31 @@ impl NumericType {
...
+                    return false;
+                }
                 let max = 2u128.pow(bit_size) - 1;
                 field <= max.into()
             }
+            NumericType::Signed { bit_size } => {
+                if negative {
+                    let base = 1_u128 << bit_size;
+                    // Recover the original value (a similar operation is done in compiler/noirc_frontend/src/monomorphization/mod.rs)
+                    let field = FieldElement::from(base) - field;
```
Comment (asterite) [inline compiler/noirc_evaluator/src/ssa/ir/types.rs:51]: I'm not happy about putting this reverse logic here... maybe `value_is_within_limits` should be called before the logic on the monomorphization side is done... but I didn't want to change things too much.

**Comment by asterite** [comment]
I'll try to avoid doing the double `-` operation here...

File: test_programs/compile_failure/unsigned_integer_literal_underflow/src/main.nr [hunk 2]
```diff
@@ -0,0 +1,5 @@
+fn main() {
+    foo(-1)
+}
+
+fn foo(_x: u8) {}
```
Comment (jfecher) [inline test_programs/compile_failure/unsigned_integer_literal_underflow/src/main.nr:5]: Since you have a few small tests in this PR which do not rely on the stdlib, I think `noirc_frontend/src/tests.rs` may be a better place for them. There, you can still assert that they error but we can place them in smaller unit tests.

**Review by jfecher — COMMENTED** [review]
LGTM

File: test_programs/compile_failure/unsigned_integer_literal_underflow/src/main.nr (hunk 2 above)
Comment (asterite) [reply test_programs/compile_failure/unsigned_integer_literal_underflow/src/main.nr:5]: Ooooh, this is great! I didn't know such file existed. Tomorrow I'll change this PR to use that approach.

Comment (asterite) [reply test_programs/compile_failure/unsigned_integer_literal_underflow/src/main.nr:5]: I tried to do this but it seems errors from the SSA pass don't get captured here... which maybe makes sense! I'm thinking ideally the error happens before SSA, but that refactor doesn't seem that easy to do (I can't find a place where integer ranges are checked on the HIR side, maybe because that code doesn't exist yet).

I'll merge this PR and later if I have some time I can try to do this refactor.

Comment (asterite) [reply test_programs/compile_failure/unsigned_integer_literal_underflow/src/main.nr:5]: Ah, it's not approved yet. I'll try a bit more then 😊

Comment (asterite) [reply test_programs/compile_failure/unsigned_integer_literal_underflow/src/main.nr:5]: Hm, it seems integer literals are assigned a type at the monomorphization stage... and that also doesn't run in these tests. I was thinking about moving the error from SSA to monomorphization, but it wouldn't trigger either.

I think I'll need to understand a bit more all of the compiler passes, what they do and when they run.

Comment (asterite) [reply test_programs/compile_failure/unsigned_integer_literal_underflow/src/main.nr:5]: (so for now I won't make any more changes to this PR... except maybe improving the error message a bit to show what the valid ranges are, when an error happens)

File: test_programs/compile_failure/signed_integer_literal_overflow/src/main.nr
Comment (TomAFrench) [inline test_programs/compile_failure/signed_integer_literal_overflow/src/main.nr:1]: Can you move these tests into this file? https://github.com/noir-lang/noir/blob/master/compiler/noirc_frontend/src/tests.rs 

These run a couple of orders of magnitude faster so we should prefer it for testing anything which only touches the frontend. (plus we can assert on the errors being returned)

Comment (asterite) [reply test_programs/compile_failure/signed_integer_literal_overflow/src/main.nr:1]: Sounds good! I already tried it (see https://github.com/noir-lang/noir/pull/5375#discussion_r1661500992 ) but don't get any errors... I think it's because that file doesn't get errors from the SSA pass?

In any case I'll try once more to refactor the code to move the errors somewhere else, or maybe change the frontend tests to also find ssa errors?

File: test_programs/compile_failure/unsigned_integer_literal_underflow/src/main.nr (hunk 2 above)
Comment (jfecher) [reply test_programs/compile_failure/unsigned_integer_literal_underflow/src/main.nr:5]: > I tried to do this but it seems errors from the SSA pass don't get captured here.

Ah, right. Forgot this check is done in SSA - my bad. Yes, the frontend tests only run name resolution & type checking. They stop before monomorphization so this won't be useful here. No need to refactor this PR.

File: test_programs/compile_failure/signed_integer_literal_overflow/src/main.nr
Comment (asterite) [reply test_programs/compile_failure/signed_integer_literal_overflow/src/main.nr:1]: So... I don't understand how everything connects. Ideally once we know the type of all variables we'd do a pass to check that integer literals fit into types. That seems to be happening right, but during monomorphization/ssa, and I'm not sure how to introduce a new pass before that to check this. Maybe the Elaborator does this? But I'm seeing that the Elaborator unifies types, so maybe all types are known after the Elaborator finishes (at least for each function) and then we'd need to run this check... but I don't know how to do it.

Maybe we could pair on this?

Alternative we could remove these tests, maybe the tests for `value_is_within_limits` are good enough?

Comment (TomAFrench) [reply test_programs/compile_failure/signed_integer_literal_overflow/src/main.nr:1]: Ah my bad, sorry I didn't see the other comment.

**Review by TomAFrench — APPROVED** [review]
