### PR TITLE
fix: allow function calls in global definitions

### LINKED ISSUE #4318: Compiler checking if the current function is constrained
### Aim

Compiling in aztec packages with current noir master.

### Expected Behavior

Should compile!

### Bug

Panics with
```
The application panicked (crashed).
Message:  Can only have call expression inside of a function body
Location: compiler/noirc_frontend/src/hir/type_check/expr.rs:158
```

Patterns like this one might be the culprit:
```rust
global HEADER = Header {
    last_archive: empty_append_only_tree(),
    body_hash: [0; NUM_FIELDS_PER_SHA256],
    state: StateReference {
        l1_to_l2_message_tree: empty_append_only_tree(),
        partial: PartialStateReference {
            note_hash_tree: AppendOnlyTreeSnapshot {
                root: fixtures::note_hash_tree::ROOT,
                next_available_leaf_index: 0, // TODO: should this be populated?
            },
            nullifier_tree: empty_append_only_tree(),
            contract_tree: AppendOnlyTreeSnapshot {
                root: fixtures::contract_tree::ROOT,
                next_available_leaf_index: 0, // TODO: should this be populated?
            },
            public_data_tree: empty_append_only_tree()
        }
    },
    global_variables: GlobalVariables {
        chain_id: 0,
        version: 0,
        block_number: 0,
        timestamp: 0,
        coinbase: empty_eth_address(),
        fee_recipient: empty_aztec_address(),
    }
};

```

### To Reproduce

1.
2.
3.
4.

### Project Impact

None

### Impact Context

_No response_

### Workaround

Yes

### Workaround Description

```rust
    let is_current_func_constrained = self
                    .current_function
                    .map(|func| {
                        let func_mod = self.interner.function_modifiers(&func);
                        !func_mod.is_unconstrained
                    })
                    .unwrap_or(true); // If there is no current function, then we assume it is constrained
```

### Additional Context

_No response_

### Installation Method

None

### Nargo Version

_No response_

### NoirJS Version

_No response_

### Would you like to submit a PR for this Issue?

None

### Support Needs

_No response_

### PR DESCRIPTION
**Pull request by TomAFrench**
# Description

## Problem\*

Resolves #4318 

## Summary\*

I've added the necessary `Option` handling for us to make calls from the global context.

## Documentation\*

Check one:
- [x] No documentation needed.
- [ ] Documentation included in this PR.
- [ ] **[Exceptional Case]** Documentation to be submitted in a separate PR.

# PR Checklist\*

- [x] I have tested the changes locally.
- [x] I have formatted the changes with [Prettier](https://prettier.io/) and/or `cargo fmt` on default settings.

### CODE REVIEW

File: compiler/noirc_frontend/src/hir/type_check/expr.rs [hunk 1]
```diff
@@ -153,11 +153,10 @@ impl<'interner> TypeChecker<'interner> {
...
                 // These flags are later used to type check calls to unconstrained functions from constrained functions
-                let current_func = self
-                    .current_function
-                    .expect("Can only have call expression inside of a function body");
-                let func_mod = self.interner.function_modifiers(&current_func);
-                let is_current_func_constrained = !func_mod.is_unconstrained;
+                let current_func = self.current_function;
+                let func_mod = current_func.map(|func| self.interner.function_modifiers(&func));
+                let is_current_func_constrained =
+                    !func_mod.map_or(false, |func_mod| func_mod.is_unconstrained);
```
Comment (TomAFrench) [inline compiler/noirc_frontend/src/hir/type_check/expr.rs:159]:
```suggestion
                let is_current_func_constrained =
                    func_mod.map_or(false, |func_mod| !func_mod.is_unconstrained);
```

File: compiler/noirc_frontend/src/hir/type_check/expr.rs [hunk 2]
```diff
@@ -153,11 +153,10 @@ impl<'interner> TypeChecker<'interner> {
...
                 // These flags are later used to type check calls to unconstrained functions from constrained functions
-                let current_func = self
-                    .current_function
-                    .expect("Can only have call expression inside of a function body");
-                let func_mod = self.interner.function_modifiers(&current_func);
-                let is_current_func_constrained = !func_mod.is_unconstrained;
+                let current_func = self.current_function;
+                let func_mod = current_func.map(|func| self.interner.function_modifiers(&func));
+                let is_current_func_constrained =
+                    func_mod.map_or(false, |func_mod| !func_mod.is_unconstrained);
```
Comment (TomAFrench) [inline compiler/noirc_frontend/src/hir/type_check/expr.rs:159]:
```suggestion
                let is_current_func_constrained =
                    func_mod.map_or(true, |func_mod| !func_mod.is_unconstrained);
```

**Comment by TomAFrench** [comment]
That's what this PR does. `aztec-packages` uses this in a few places, e.g. https://github.com/AztecProtocol/aztec-packages/blob/47d66f9119cad1a82b621d30acab88f47886e063/yarn-project/noir-protocol-circuits/src/crates/types/src/tests/fixtures.nr#L43-L69

The change made in https://github.com/noir-lang/noir/pull/4281 broke this however.

**Comment by jfecher** [comment]
> That's what this PR does. aztec-packages uses this in a few places

Oof, this code should have been banned before https://github.com/noir-lang/noir/pull/4293 was merged yesterday. I had hoped nobody would discover and use the fact that function calls were banned in globals unless used indirectly in a struct expression.

File: compiler/noirc_frontend/src/hir/type_check/expr.rs [hunk 3]
```diff
@@ -170,15 +169,14 @@ impl<'interner> TypeChecker<'interner> {
...
-                        && is_unconstrained_call
-                        && matches!(&typ, Type::MutableReference(_))
-                    {
-                        self.errors.push(TypeCheckError::ConstrainedReferenceToUnconstrained {
-                            span: self.interner.expr_span(expr_id),
-                        });
-                        return Type::Error;
+                if is_current_func_constrained && is_unconstrained_call {
+                    for (typ, _, _) in args.iter() {
+                        if matches!(&typ, Type::MutableReference(_)) {
```
Comment (jfecher) [inline compiler/noirc_frontend/src/hir/type_check/expr.rs:174]:
```suggestion
                        if matches!(&typ.follow_bindings(), Type::MutableReference(_)) {
```
Didn't catch this in the first PR but we should always call `follow_bindings` before checking a type is a certain variant.

**Comment by TomAFrench** [comment]
Oof, ok then. I can rework this PR to just return an error instead of panicking.

cc @sirasistant on `aztec-packages` patch needing to be permanent.

**Comment by jfecher** [comment]
> Oof, ok then. I can rework this PR to just return an error instead of panicking.

Doesn't this PR already remove a panic?

**Comment by TomAFrench** [comment]
I mean that I'll remove the panic and put an error in its place. Currently the PR allows the function calls to occur.

**Comment by jfecher** [comment]
> Currently the PR allows the function calls to occur.

Function calls in globals are allowed now that #4293 was merged, it's just that they shouldn't have been allowed before then

**Comment by TomAFrench** [comment]
Ah gotcha, sorry misread.

**Review by jfecher — APPROVED** [review]
:+1:
