### PR TITLE
fix(ssa): Recursive shared Brillig entry points 

### LINKED ISSUE #8069: Compiler crash in `brillig_globals`: function has multiple entry points
### Aim

Discovered in https://github.com/noir-lang/noir/pull/8048

The original was reproducible at commit b9cadfe9a31fc848d94fa6b597a65b5e357d4d7f with the following command:
```shell
NOIR_ARBTEST_SEED=0x644ccb3700100000 RUST_BACKTRACE=1 cargo test -p noir_ast_fuzzer --test smoke
```

Below is a minimised Noir code to trigger the bug:

```rust
fn main(a: i32, b: i8) -> pub bool {
    let ctx_depth = 5;
    let g = if (!unsafe { func_1(true, 1, ctx_depth) }) {
        unsafe { func_2(1, true, ctx_depth) }[0]
    } else {
        0
    };
    false
}
unconstrained fn func_1(a: bool, b: i8, mut ctx_depth: u32) -> bool {
    if (ctx_depth == 0) {
        false
    } else {
        ctx_depth = (ctx_depth - 1);
        func_1(false, func_2((a as Field), false, ctx_depth)[3], ctx_depth)
    }
}
unconstrained fn func_2(mut a: Field, mut b: bool, mut ctx_depth: u32) -> [i8; 4] {
    if (ctx_depth == 0) {
        [6, 101, 92, 30]
    } else {
        ctx_depth = (ctx_depth - 1);
        func_2(a, func_1(b, 0, ctx_depth), ctx_depth)
    }
}
```

Here is another example:
```rust
fn main() {
    baz();
}

unconstrained fn foo<Env>(f: fn[Env]()) {
    println("foo");
    bar(f);
}

unconstrained fn bar<Env>(f: fn[Env]()) {
    println("bar");
    f();
}

fn baz() {
    unsafe {
        foo(baz);
        bar(baz);
    }
}
```

### Expected Behavior

The compiler shouldn't crash.

I thought maybe the problem was that I had a function that wasn't called from `main`, but looked like another entry point to reach a brillig function, but in this example everything is called from `main`.

As I understand, looking at the second example, the problem is that we can cross the ACIR->Brillig barrier at `foo` or the `bar` entry point, but `foo` will also call `bar`, so `bar` should have two different global allocations. There is also recursion involved, where `bar` will eventually end up calling `foo`.

### Bug

```console
bash-5.2$ cargo run -q -p nargo_cli -- compile --force
The application panicked (crashed).
Message:  assertion `left == right` failed: f3 has multiple entry points: f1, f2
  left: 2
 right: 1
Location: compiler/noirc_evaluator/src/brillig/brillig_gen/brillig_globals.rs:204
```

To see which entry points it's complaining about I changed the assertion as follows:
```rust
        assert_eq!(
            entry_points.len(),
            1,
            "{brillig_function_id} has multiple entry points: {}",
            entry_points.iter().map(|id| format!("{id}")).collect::<Vec<_>>().join(", ")
        );
```

The SSA before the crash looks like this:
```
After Dead Instruction Elimination (2):
acir(inline) impure fn main f0 {
  b0(v0: i32, v1: i8):
    v6 = call f1(u1 1, i8 1, u32 5) -> u1
    v7 = not v6
    enable_side_effects v7
    v10 = call f2(Field 1, u1 1, u32 5) -> [i8; 4]
    enable_side_effects u1 1
    return u1 0
}
brillig(inline) impure fn func_1 f1 {
  b0(v0: u1, v1: i8, v2: u32):
    v5 = eq v2, u32 0
    jmpif v5 then: b1, else: b2
  b1():
    jmp b3(u1 0)
  b2():
    v7 = sub v2, u32 1
    v8 = cast v0 as Field
    v11 = call f4(v8, u1 0, v7) -> [i8; 4]
    v13 = array_get v11, index u32 4 -> i8
    v15 = call f3(u1 0, v13, v7) -> u1
    jmp b3(v15)
  b3(v3: u1):
    return v3
}
brillig(inline) impure fn func_2 f2 {
  b0(v0: Field, v1: u1, v2: u32):
    v5 = eq v2, u32 0
    jmpif v5 then: b1, else: b2
  b1():
    v17 = make_array [i8 6, i8 101, i8 92, i8 30] : [i8; 4]
    jmp b3(v17)
  b2():
    v7 = sub v2, u32 1
    v10 = call f1(v1, i8 0, v7) -> u1
    v12 = call f2(v0, v10, v7) -> [i8; 4]
    jmp b3(v12)
  b3(v3: [i8; 4]):
    return v3
}
brillig(inline) fn func_1 f3 {
  b0(v0: u1, v1: i8, v2: u32):
    v5 = eq v2, u32 0
    jmpif v5 then: b1, else: b2
  b1():
    jmp b3(u1 0)
  b2():
    v7 = sub v2, u32 1
    v8 = cast v0 as Field
    v11 = call f4(v8, u1 0, v7) -> [i8; 4]
    v13 = array_get v11, index u32 4 -> i8
    v15 = call f3(u1 0, v13, v7) -> u1
    jmp b3(v15)
  b3(v3: u1):
    return v3
}
brillig(inline) fn func_2 f4 {
  b0(v0: Field, v1: u1, v2: u32):
    v5 = eq v2, u32 0
    jmpif v5 then: b1, else: b2
  b1():
    v17 = make_array [i8 6, i8 101, i8 92, i8 30] : [i8; 4]
    jmp b3(v17)
  b2():
    v7 = sub v2, u32 1
    v10 = call f3(v1, i8 0, v7) -> u1
    v12 = call f4(v0, v10, v7) -> [i8; 4]
    jmp b3(v12)
  b3(v3: [i8; 4]):
    return v3
}
```

### To Reproduce

See above.

### Workaround

None

### Workaround Description

_No response_

### Additional Context

_No response_

### Project Impact

None

### Blocker Context

_No response_

### Nargo Version

nargo version = 1.0.0-beta.4 noirc version = 1.0.0-beta.4+b9cadfe9a31fc848d94fa6b597a65b5e357d4d7f (git version hash: b9cadfe9a31fc848d94fa6b597a65b5e357d4d7f, is dirty: true)

### NoirJS Version

_No response_

### Proving Backend Tooling & Version

_No response_

### Would you like to submit a PR for this Issue?

None

### Support Needs

_No response_

### PR DESCRIPTION
**Pull request by vezenovm**
# Description

## Problem\*

Resolves #8069 

For more context surrounding what the Brillig entry point analysis pass is doing and why you can reference https://github.com/noir-lang/noir/pull/7277 and the doc comments on the pass itself. 

The current SSA for the new `brillig_entry_points_regression_8069` test:
<details><summary>Details</summary>
<p>

```
After Array Set Optimizations (1):
acir(inline) impure fn main f0 {
  b0():
    v4 = call f1(u1 1, i8 1, u32 5) -> u1
    v5 = not v4
    enable_side_effects v5
    v8 = call f2(Field 1, u1 1, u32 5) -> [i8; 4]
    enable_side_effects u1 1
    return u1 0
}
brillig(inline) impure fn func_1 f1 {
  b0(v0: u1, v1: i8, v2: u32):
    v5 = eq v2, u32 0
    jmpif v5 then: b1, else: b2
  b1():
    jmp b3(u1 0)
  b2():
    v7 = sub v2, u32 1
    v8 = cast v0 as Field
    v11 = call f2(v8, u1 0, v7) -> [i8; 4]
    v13 = array_get v11, index u32 3 -> i8
    v15 = call f1(u1 0, v13, v7) -> u1
    jmp b3(v15)
  b3(v3: u1):
    return v3
}
brillig(inline) impure fn func_2 f2 {
  b0(v0: Field, v1: u1, v2: u32):
    v5 = eq v2, u32 0
    jmpif v5 then: b1, else: b2
  b1():
    v17 = make_array [i8 6, i8 101, i8 92, i8 30] : [i8; 4]
    jmp b3(v17)
  b2():
    v7 = sub v2, u32 1
    v10 = call f1(v1, i8 0, v7) -> u1
    v12 = call f2(v0, v10, v7) -> [i8; 4]
    jmp b3(v12)
  b3(v3: [i8; 4]):
    return v3
}

After Brillig Entry Point Analysis (1):
acir(inline) impure fn main f0 {
  b0():
    v4 = call f1(u1 1, i8 1, u32 5) -> u1
    v5 = not v4
    enable_side_effects v5
    v8 = call f2(Field 1, u1 1, u32 5) -> [i8; 4]
    enable_side_effects u1 1
    return u1 0
}
brillig(inline) impure fn func_1 f1 {
  b0(v0: u1, v1: i8, v2: u32):
    v5 = eq v2, u32 0
    jmpif v5 then: b1, else: b2
  b1():
    jmp b3(u1 0)
  b2():
    v7 = sub v2, u32 1
    v8 = cast v0 as Field
    v11 = call f4(v8, u1 0, v7) -> [i8; 4]
    v13 = array_get v11, index u32 3 -> i8
    v15 = call f3(u1 0, v13, v7) -> u1
    jmp b3(v15)
  b3(v3: u1):
    return v3
}
brillig(inline) impure fn func_2 f2 {
  b0(v0: Field, v1: u1, v2: u32):
    v5 = eq v2, u32 0
    jmpif v5 then: b1, else: b2
  b1():
    v17 = make_array [i8 6, i8 101, i8 92, i8 30] : [i8; 4]
    jmp b3(v17)
  b2():
    v7 = sub v2, u32 1
    v10 = call f1(v1, i8 0, v7) -> u1
    v12 = call f2(v0, v10, v7) -> [i8; 4]
    jmp b3(v12)
  b3(v3: [i8; 4]):
    return v3
}
brillig(inline) fn func_1 f3 {
  b0(v0: u1, v1: i8, v2: u32):
    v5 = eq v2, u32 0
    jmpif v5 then: b1, else: b2
  b1():
    jmp b3(u1 0)
  b2():
    v7 = sub v2, u32 1
    v8 = cast v0 as Field
    v11 = call f4(v8, u1 0, v7) -> [i8; 4]
    v13 = array_get v11, index u32 3 -> i8
    v15 = call f3(u1 0, v13, v7) -> u1
    jmp b3(v15)
  b3(v3: u1):
    return v3
}
brillig(inline) fn func_2 f4 {
  b0(v0: Field, v1: u1, v2: u32):
    v5 = eq v2, u32 0
    jmpif v5 then: b1, else: b2
  b1():
    v17 = make_array [i8 6, i8 101, i8 92, i8 30] : [i8; 4]
    jmp b3(v17)
  b2():
    v7 = sub v2, u32 1
    v10 = call f3(v1, i8 0, v7) -> u1
    v12 = call f4(v0, v10, v7) -> [i8; 4]
    jmp b3(v12)
  b3(v3: [i8; 4]):
    return v3
}
brillig(inline) fn func_1 f5 {
  b0(v0: u1, v1: i8, v2: u32):
    v5 = eq v2, u32 0
    jmpif v5 then: b1, else: b2
  b1():
    jmp b3(u1 0)
  b2():
    v7 = sub v2, u32 1
    v8 = cast v0 as Field
    v11 = call f2(v8, u1 0, v7) -> [i8; 4]
    v13 = array_get v11, index u32 3 -> i8
    v15 = call f1(u1 0, v13, v7) -> u1
    jmp b3(v15)
  b3(v3: u1):
    return v3
}
brillig(inline) fn func_2 f6 {
  b0(v0: Field, v1: u1, v2: u32):
    v5 = eq v2, u32 0
    jmpif v5 then: b1, else: b2
  b1():
    v17 = make_array [i8 6, i8 101, i8 92, i8 30] : [i8; 4]
    jmp b3(v17)
  b2():
    v7 = sub v2, u32 1
    v10 = call f1(v1, i8 0, v7) -> u1
    v12 = call f2(v0, v10, v7) -> [i8; 4]
    jmp b3(v12)
  b3(v3: [i8; 4]):
    return v3
}
```

</p>
</details> 

We can see how the calls to `f1` and `f2` in `f2` are never replaced with duplicated entry points. 

We currently have a single mapping of old function ids to new function ids. This leads to IDs being muddled across entry points. We clone the functions and set-up the calls that needs updating in each function before actually performing the update. Thus, let's say we updated the function calls for f1, where the calls f1 and f2 map to f3 and f4 respectively. As the calls to update are already set-up, when we go to update the function calls for f2 (which should map to f5 and f6), we will resolve f2 to f3. The calls to update are set-up off the original Brillig entry points call graph, thus there will be no new functions to update for f3. 

## Summary\*

This fix required a couple changes:
1. We now resolve function IDs per entry point. The inner recursive calls in f1 and f2 now resolve to separate specialized entry points as expected. I have added the linked test in the issue under `execution_success` and a unit test to `brillig_entry_points.rs`
2. We also now build our new functions map entirely with the original SSA. We previously would iterate through the Brillig entry points call graph, update call sites, and track the new functions mapping at the same time. Before updating the SSA we already have all this information (as we have already cloned the functions). We should be able to set up the calls to update a single time and the mapping of old functions to new before any updates occur. Only then we do we perform the appropriate updates to all the call sites by iterating `calls_to_update`.
3. We go over the new functions mapping as there may be cloned functions whose call sites were not appropriately updated. Once again, the calls to update we build are only based upon the original SSA so cloned functions are not going to be included. We iterate over the cloned function call sites and use the new functions mapping to resolve the call sites in cloned functions.

New SSA after this PR:

<details><summary>Details</summary>
<p>

```
After Brillig Entry Point Analysis (1):
acir(inline) impure fn main f0 {
  b0():
    v4 = call f1(u1 1, i8 1, u32 5) -> u1
    v5 = not v4
    enable_side_effects v5
    v8 = call f2(Field 1, u1 1, u32 5) -> [i8; 4]
    enable_side_effects u1 1
    return u1 0
}
brillig(inline) impure fn func_1 f1 {
  b0(v0: u1, v1: i8, v2: u32):
    v5 = eq v2, u32 0
    jmpif v5 then: b1, else: b2
  b1():
    jmp b3(u1 0)
  b2():
    v7 = sub v2, u32 1
    v8 = cast v0 as Field
    v11 = call f4(v8, u1 0, v7) -> [i8; 4]
    v13 = array_get v11, index u32 3 -> i8
    v15 = call f3(u1 0, v13, v7) -> u1
    jmp b3(v15)
  b3(v3: u1):
    return v3
}
brillig(inline) impure fn func_2 f2 {
  b0(v0: Field, v1: u1, v2: u32):
    v5 = eq v2, u32 0
    jmpif v5 then: b1, else: b2
  b1():
    v17 = make_array [i8 6, i8 101, i8 92, i8 30] : [i8; 4]
    jmp b3(v17)
  b2():
    v7 = sub v2, u32 1
    v10 = call f5(v1, i8 0, v7) -> u1
    v12 = call f6(v0, v10, v7) -> [i8; 4]
    jmp b3(v12)
  b3(v3: [i8; 4]):
    return v3
}
brillig(inline) fn func_1 f3 {
  b0(v0: u1, v1: i8, v2: u32):
    v5 = eq v2, u32 0
    jmpif v5 then: b1, else: b2
  b1():
    jmp b3(u1 0)
  b2():
    v7 = sub v2, u32 1
    v8 = cast v0 as Field
    v11 = call f4(v8, u1 0, v7) -> [i8; 4]
    v13 = array_get v11, index u32 3 -> i8
    v15 = call f3(u1 0, v13, v7) -> u1
    jmp b3(v15)
  b3(v3: u1):
    return v3
}
brillig(inline) fn func_2 f4 {
  b0(v0: Field, v1: u1, v2: u32):
    v5 = eq v2, u32 0
    jmpif v5 then: b1, else: b2
  b1():
    v17 = make_array [i8 6, i8 101, i8 92, i8 30] : [i8; 4]
    jmp b3(v17)
  b2():
    v7 = sub v2, u32 1
    v10 = call f3(v1, i8 0, v7) -> u1
    v12 = call f4(v0, v10, v7) -> [i8; 4]
    jmp b3(v12)
  b3(v3: [i8; 4]):
    return v3
}
brillig(inline) fn func_1 f5 {
  b0(v0: u1, v1: i8, v2: u32):
    v5 = eq v2, u32 0
    jmpif v5 then: b1, else: b2
  b1():
    jmp b3(u1 0)
  b2():
    v7 = sub v2, u32 1
    v8 = cast v0 as Field
    v11 = call f6(v8, u1 0, v7) -> [i8; 4]
    v13 = array_get v11, index u32 3 -> i8
    v15 = call f5(u1 0, v13, v7) -> u1
    jmp b3(v15)
  b3(v3: u1):
    return v3
}
brillig(inline) fn func_2 f6 {
  b0(v0: Field, v1: u1, v2: u32):
    v5 = eq v2, u32 0
    jmpif v5 then: b1, else: b2
  b1():
    v17 = make_array [i8 6, i8 101, i8 92, i8 30] : [i8; 4]
    jmp b3(v17)
  b2():
    v7 = sub v2, u32 1
    v10 = call f5(v1, i8 0, v7) -> u1
    v12 = call f6(v0, v10, v7) -> [i8; 4]
    jmp b3(v12)
  b3(v3: [i8; 4]):
    return v3
}
```

</p>
</details> 

## Documentation\*

Check one:
- [X] No documentation needed.
- [ ] Documentation included in this PR.
- [ ] **[For Experimental Features]** Documentation to be submitted in a separate PR.

# PR Checklist\*

- [X] I have tested the changes locally.
- [X] I have formatted the changes with [Prettier](https://prettier.io/) and/or `cargo fmt` on default settings.

### CODE REVIEW

File: compiler/noirc_evaluator/src/ssa/opt/brillig_entry_points.rs [hunk 1]
```diff
@@ -80,40 +80,92 @@ impl Ssa {
...
+        for instruction_id in function.dfg[block_id].instructions().to_vec() {
+            let instruction = function.dfg[instruction_id].clone();
+            let Instruction::Call { func: func_value_id, arguments } = instruction else {
+                continue;
+            };
+            let func_value = &function.dfg[func_value_id];
+            let Value::Function(func_id) = func_value else { continue };
+
+            let new_func_id = new_functions_map.get(func_id).copied().unwrap_or(*func_id);
+            if new_func_id == *func_id {
```
Comment (michaeljklein) [inline compiler/noirc_evaluator/src/ssa/opt/brillig_entry_points.rs:159]: This `unwrap_or(*func_id)` followed by `if .. ==` seems a bit roundabout: are there expected to be cases where the function exists in the `new_functions_map` and the `new_func_id == func_id`?

Otherwise, could use the same pattern as above, i.e.:
```rust
let Some(new_func_id) = new_functions_map.get(func_id).copied() else { continue };
```

File: compiler/noirc_evaluator/src/ssa/opt/brillig_entry_points.rs [hunk 2]
```diff
@@ -80,40 +80,92 @@ impl Ssa {
...
+        {
+            let new_function_to_update = if entry_point == function_to_update {
+                entry_point
+            } else {
+                new_functions_map
+                    .entry(entry_point)
+                    .or_default()
+                    .get(&function_to_update)
+                    .copied()
+                    .unwrap_or(function_to_update)
```
Comment (michaeljklein) [inline compiler/noirc_evaluator/src/ssa/opt/brillig_entry_points.rs:108]: Is there any issue if a function is processed twice? I would expect to skip cases when no `get(&function_to_update)` is found

**Review by michaeljklein — CHANGES_REQUESTED** [review]

File: compiler/noirc_evaluator/src/ssa/opt/brillig_entry_points.rs (hunk 2 above)
Comment (vezenovm) [reply compiler/noirc_evaluator/src/ssa/opt/brillig_entry_points.rs:108]: `new_functions_map` only maps new old function call sites to new ones. However, we can still potentially still have an old function we need to update. The function id we are fetching here is for the caller, not the callee. Any new callee's that then need to be updated will be resolved in the follow-up pass.

Comment (vezenovm) [reply compiler/noirc_evaluator/src/ssa/opt/brillig_entry_points.rs:108]: Also due to our mapping of old id -> new id per entry point, it should be fine to process a function twice as we will have the same result.

File: compiler/noirc_evaluator/src/ssa/opt/brillig_entry_points.rs (hunk 1 above)
Comment (vezenovm) [reply compiler/noirc_evaluator/src/ssa/opt/brillig_entry_points.rs]: Switched to using the `let ... else` statement

File: compiler/noirc_evaluator/src/ssa/opt/brillig_entry_points.rs [hunk 3]
```diff
@@ -80,40 +80,94 @@ impl Ssa {
...
             }
         }
 
         self
     }
 }
 
+/// Given that we have already rewritten all the call sites among the original SSA,
+/// this function provides a helper for resolving the call sites within cloned functions.
+/// This function will update  a cloned function according to the supplied function mapping.
```
Comment (vezenovm) [inline compiler/noirc_evaluator/src/ssa/opt/brillig_entry_points.rs:141]:
```suggestion
/// This function will update a cloned function according to the supplied function mapping.
```
