### PR TITLE
fix: remove panic when generic array length is not resolvable

### LINKED ISSUE #4407: Compilation panic: Length of array is unknown when evaluating numeric generic
### Aim

I've tried to compile this code. I understand that it's incorrect, but it should not cause compiler panic.
```
fn main() {
    f();
}

pub fn f<NUM_FIELDS>() -> [Field; NUM_FIELDS] {
    [0; NUM_FIELDS]
}
```

### Expected Behavior

I get the compilation error

### Bug

I get compiler panic

### To Reproduce

1. Compile the program above wit nargo v0.23.0 or 0.24.0

### Project Impact

Blocker

### Impact Context

I've had an issue in my tests that the assertion were firing in the wrong order. I saw that it's fixed in 0.24. Tried to upgrade to 0.24, but encountered a compilation panic. Tried to find the minimal example and found the one here which funnily is also happening on 0.23.

Therefore without this fixed I would be stuck on 0.23 and will need to have wrong assertion messages in test expects

### Workaround

None

### Workaround Description

_No response_

### Additional Context

_No response_

### Installation Method

Binary (`noirup` default)

### Nargo Version

_No response_

### NoirJS Version

_No response_

### Would you like to submit a PR for this Issue?

None

### Support Needs

_No response_

### PR DESCRIPTION
**Pull request by TomAFrench**
# Description

## Problem\*

Resolves #4407 

## Summary\*

We currently have no way to gracefully error during monomorphization and so must panic if we run into any errors.

This PR then adds the `MonomorphizationError` enum with an example error type. We've also added a `CompileError` which unifies `RuntimeError` and `MonomorphizationError` so they can be converted into `FileDiagnostic`s

## Documentation\*

Check one:
- [x] No documentation needed.
- [ ] Documentation included in this PR.
- [ ] **[Exceptional Case]** Documentation to be submitted in a separate PR.

# PR Checklist\*

- [x] I have tested the changes locally.
- [x] I have formatted the changes with [Prettier](https://prettier.io/) and/or `cargo fmt` on default settings.

### CODE REVIEW

File: compiler/noirc_driver/src/lib.rs [hunk 1]
```diff
@@ -107,6 +108,24 @@ fn parse_expression_width(input: &str) -> Result<ExpressionWidth, std::io::Error
...
+
+    #[error(transparent)]
+    RuntimeError(#[from] RuntimeError),
+}
+
+impl From<CompileError> for FileDiagnostic {
+    fn from(error: CompileError) -> FileDiagnostic {
+        match error {
+            CompileError::RuntimeError(err) => err.into(),
+            CompileError::MonomorphizationError(err) => err.into(),
```
Comment (vezenovm) [inline compiler/noirc_driver/src/lib.rs:124]: We will want some way to distinguish that this is an internal error similar to how we do for `InternalError` inside of SSA. cc @jfecher

Comment (vezenovm) [reply compiler/noirc_driver/src/lib.rs:124]: Just when we convert an internal error to a diagnositc we state that we have an internal consistency error and link to our repo that an issue should be opened. A monomorphization bug should be handled in the same way as the pass is not expected to fail.

Comment (TomAFrench) [reply compiler/noirc_driver/src/lib.rs:124]: Not all of the errors in the monomorphisation pass are internal consistency errors though. For example in https://github.com/noir-lang/noir/issues/4407 it's purely down to the input being well defined.

Comment (vezenovm) [reply compiler/noirc_driver/src/lib.rs:124]: They are all errors in the compiler though and should be stated as such. What we do for internal consistency errors was simply an example. We can state "Internal Monomorphization Errors: Please open issue here..." or something similar.

Comment (TomAFrench) [reply compiler/noirc_driver/src/lib.rs:124]: Shall we chat about this on the call after scrum?

Comment (vezenovm) [reply compiler/noirc_driver/src/lib.rs:124]: Let's just talk during/post scrum so @jfecher can comment as well.

**Review by vezenovm — APPROVED** [review]
