### PR TITLE
fix(nargo): correct inconsistent file extension for ACIR hashes

### LINKED ISSUE #993: Error when trying to `nargo prove` a compiled circuit
### Aim

I'm trying to generate a proof (with `nargo prove <proof_name> <circuit_name>` over a previously compiled circuit (compiled with `nargo compile <circuit_name>`).

### Expected behavior

Nargo should prove the cached circuit without exceptions.

### Bug

Compiled circuit fetching fails because [the ACIR hash is stored with a `.json.sha256` extension](https://github.com/noir-lang/noir/tree/master/crates/nargo/src/cli/fs#L30) and [when fetching the keys,  an ACIR hash file with `.json.checksum` extension is being loaded](https://github.com/noir-lang/noir/blob/master/crates/nargo/src/cli/fs/keys.rs#L35).

### To reproduce

1. `nargo new foo`.
2. `nargo compile my_circuit`.
3. `nargo prove my_proof my_circuit`.

### Installation method

Compiled from source

### Nargo version

0.3.1

### @noir-lang/noir_wasm version

_No response_

### @noir-lang/barretenberg version

_No response_

### @noir-lang/aztec_backend version

_No response_

### Additional context

_No response_

### PR DESCRIPTION
**Pull request by ilitteri**
# Related issue(s)

Resolves #993 

# Description

## Summary of changes

- Made `save_and_preprocess_program` public for the crate.
- Renamed the extension for the ACIR hash that is being stored (`json.sha256` -> `json.checksum`). For this point, I have a doubt about which you prefer and I think that it'd be nice to have a constant for this extension in order to avoid the same problem in the future.
- Add integration test that test this flow:
    - `nargo compile <circuit_name>`.
    - `nargo prove <proof_name> <circuit_name>`.
    - `nargo verify <proof_name> <circuit_name>`.
- Added a test helper function for the bullet above.

## Dependency additions / changes

-

## Test additions / changes

- Add integration test that test this flow:
    - `nargo compile <circuit_name>`.
    - `nargo prove <proof_name> <circuit_name>`.
    - `nargo verify <proof_name> <circuit_name>`.
- Added a test helper function for the bullet above.

# Checklist

- [x] I have tested the changes locally.
- [x] I have formatted the changes with [Prettier](https://prettier.io/) and/or `cargo fmt` with default settings.
- [x] I have [linked](https://docs.github.com/en/issues/tracking-your-work-with-issues/linking-a-pull-request-to-an-issue) this PR to the issue(s) that it resolves.
- [x] I have reviewed the changes on GitHub, line by line.
- [x] I have ensured all changes are covered in the description.

## Documentation needs
- [ ] This PR requires documentation updates when merged.

# Additional context
-

### CODE REVIEW

**Comment by ilitteri** [comment]
I'm merging both integration tests into one (`noir_integration`) because there is a problem when running them in parallel.

File: crates/nargo/src/cli/mod.rs [hunk 1]
```diff
@@ -101,6 +101,40 @@ pub fn prove_and_verify(proof_name: &str, prg_dir: &Path, show_ssa: bool) -> boo
     }
 }
 
+// helper function which tests noir programs by trying to compile, generate a proof and verify it
+pub fn cached_prove_and_verify(
```
Comment (TomAFrench) [inline crates/nargo/src/cli/mod.rs:105]: I'm a little wary of ~2x-ing the length of CI time to check that we're saving and loading the cached keys correctly. We don't actually have to prove and verify here to test this. We then don't even need consistent set of ACIR + keys, i.e no need to compile and we can just use dummy ACIR + keys.

At this point we can then make this a unit rather than integration test.

File: crates/nargo/src/cli/fs/program.rs [hunk 2]
```diff
@@ -27,7 +27,7 @@ pub(crate) fn save_acir_hash_to_dir<P: AsRef<Path>>(
     hash_dir: P,
 ) -> PathBuf {
     let acir_hash = hash_constraint_system(circuit);
-    let hash_path = hash_dir.as_ref().join(hash_name).with_extension("json.sha256");
+    let hash_path = hash_dir.as_ref().join(hash_name).with_extension("json.checksum");
```
Comment (TomAFrench) [inline crates/nargo/src/cli/fs/program.rs:30]: > I think that it'd be nice to have a constant for this extension in order to avoid the same problem in the future.

Agreed, I should have done this. Could you add `ACIR_HASH` to `constants.rs`?

**Review by TomAFrench — COMMENTED** [review]
Thanks for catching this @ilitteri, sorry this slipped through.

My main concern with the current PR is that we could get a minor combinatorial explosion of different paths through the compilation->proving->verification flow, e.g. Proving and verifying can either automatically generate the ACIR from source or use a build artifact, verification may read a proof from a file or get passed it directly, etc.

If we run integration tests across all of `test_data` for each potential path we'd end up making CI unnecessarily slow. I think it would be best to have a more focused test just to check that `fetch_pk_and_vk` will always be able to recover the keys saved by `save_and_preprocess_program` if you pass in the same circuit.

File: crates/nargo/src/cli/mod.rs (hunk 1 above)
Comment (ilitteri) [reply crates/nargo/src/cli/mod.rs:105]: 2x is a lot, you are right. I'm looking at how to make the test faster

File: crates/nargo/src/cli/fs/program.rs (hunk 2 above)
Comment (ilitteri) [reply crates/nargo/src/cli/fs/program.rs:30]: Sure!

**Comment by ilitteri** [comment]
> Thanks for catching this @ilitteri, sorry this slipped through.
> 
> My main concern with the current PR is that we could get a minor combinatorial explosion of different paths through the compilation->proving->verification flow if we add more integration tests for cases like this, e.g. Proving and verifying can either automatically generate the ACIR from source or use a build artifact, verification may read a proof from a file or get passed it directly, etc.
> 
> If we run integration tests across all of `test_data` for each potential path we'd end up making CI unnecessarily slow. I think it would be best to have a more focused test just to check that `fetch_pk_and_vk` will always be able to recover the keys saved by `save_and_preprocess_program` if you pass in the same circuit.

I like the idea of just checking `fetch_pk_and_vk`. Another alternative (the one that I was trying right now) is using a `Mutex`. It actually works but it's being polished. If the time is not better, I will go for the `fetch_pk_and_vk` test.

**Comment by ilitteri** [comment]
@TomAFrench ready! Do you want me to file an issue for unit testing the other `fs` submodule functions?

File: crates/nargo/src/cli/fs/keys.rs [hunk 3]
```diff
@@ -66,3 +66,27 @@ pub(crate) fn fetch_pk_and_vk<P: AsRef<Path>>(
...
+        let circuit_name = "my_circuit";
+        let mut circuit_build_path = TempDir::new("temp_circuit_hash_dir").unwrap().into_path();
+
+        save_acir_hash_to_dir(&circuit, circuit_name, circuit_build_path.clone());
+
+        circuit_build_path.push(circuit_name);
+
+        // Here we do not prove nor verify because it is not the scope of this test.
+        assert!(fetch_pk_and_vk(&circuit, circuit_build_path, false, false).is_ok());
+    }
```
[the remark this answers is not in the document]
Comment (ilitteri) [reply crates/nargo/src/cli/fs/keys.rs:91]: I agree!

**Comment by TomAFrench** [comment]
> Do you want me to file an issue for unit testing the other `fs` submodule functions?

Yeah we should roll these out to get more coverage on this submodule, I've added one here https://github.com/noir-lang/noir/issues/995

Thanks again for this :)

**Comment by TomAFrench** [comment]
Sorry, that suggestion was semi-pseudocode. I'll fix up any issues and merge.

**Comment by ilitteri** [comment]
> Sorry, that suggestion was semi-pseudocode. I'll fix up any issues and merge.

I have the fix ready to push, let me know if you're working on it too.

**Comment by TomAFrench** [comment]
> I have the fix ready to push, let me know if you're working on it too.

I've got it ready but github won't let me push to the fork branch for some reason. Feel free to push.

**Review by TomAFrench — APPROVED** [review]
Awesome, LGTM.
