### PR TITLE
fix(examples): Update the `recursion` example to use `bb` version `3.0.0-nightly.20251104`

### LINKED ISSUE #10959: The `recursion` example doesn't work
### Aim

https://github.com/noir-lang/noir/pull/10956#issuecomment-3671285858

The `examples/recursion` doesn't work any more and should be fixed.

### Expected Behavior

It should pass on CI.

### Bug

```
Running recursion
Cloning into '/home/runner/nargo/github.com/aztecprotocol/aztec-packages/v0.87.0'...
[sum] Circuit witness successfully solved
[sum] Witness saved to target/sum_witness.gz
[sum] Circuit output: 3
The following arguments were not expected: bytes_and_fields --output_format --init_kzg_accumulator
Run with --help for more information.
error: Recipe `run-example` failed on line 179 with exit code 109
```

### To Reproduce

1.
2.
3.
4.

### Workaround

None

### Workaround Description

The step was disabled in the `justfile` in https://github.com/noir-lang/noir/pull/10956

### Additional Context

_No response_

### Project Impact

None

### Blocker Context

_No response_

### Nargo Version

nargo version = 1.0.0-beta.17 noirc version = 1.0.0-beta.17+632479b81e6a24333c7b460f42d146449df8bac4 (git version hash: d937743790765fd84cc699b46ff94b42bc5005b1, is dirty: true)

### NoirJS Version

_No response_

### Proving Backend Tooling & Version

_No response_

### Would you like to submit a PR for this Issue?

None

### Support Needs

_No response_

### PR DESCRIPTION
**Pull request by aakoshh**
# Description

## Problem

Resolves #10959 

## Summary

Updates `examples/recursion` to use `bb` version `3.0.0-nightly.20251104`, which is currently on `master` in `install_bb.sh`:
* `bb` no longer expects `--output_format` and  `--init_kzg_accumulator`, so those have been removed 
* `bb` seems to have stopped generating `.json` files for the VK, the proof, etc (this was was `--output_format bytes_and_fields` did). It looks like there were separate commands for these, but they have been removed in https://github.com/AztecProtocol/aztec-packages/pull/13902/changes#diff-d20048eb422624c9073d7bc2c679b2883ccd82030f678bb241aecd8af0b44a1f  
Claude kindly wrote a Python script to produce them from the binary output. Not sure if there is another way to do this via `bb`.
* `bb` now produces a `UltraHonkZKProof` proof, rather than `UltraHonkProof`, as evidenced by the difference in the input sizes, so I changed the Noir circuits to expect these and call a different verification function.
* Both circuits referenced version `v0.87` of `bb_proof_verification` instead of the latest, which is the last time this example was updated by @saleel ; updated to the current `bb` version.
* `bb` has implemented the `vk_hash` check, without which the proofs fail, so I added them to `Prover.toml`. 

It works now: https://github.com/noir-lang/noir/actions/runs/20370307391/job/58535394020?pr=10964

## Additional Context

This is the old interface: https://github.com/AztecProtocol/aztec-packages/blob/v0.87.0/barretenberg/cpp/src/barretenberg/bb/cli.cpp

This is the current one: https://github.com/AztecProtocol/aztec-packages/blob/v3.0.0-nightly.20251104/barretenberg/cpp/src/barretenberg/bb/cli.cpp

This will break again when we update `bb` in https://github.com/noir-lang/noir/pull/7810 like this:
```
+ nargo execute recurse_leaf_witness --package recurse_leaf --pedantic-solving --force
error: Could not resolve 'verify_ultrahonkzk_proof' in path
  ┌─ recurse_leaf/src/main.nr:3:29
  │
3 │ use bb_proof_verification::{verify_ultrahonkzk_proof, UltraHonkZKProof, UltraHonkVerificationKey};
  │                             ------------------------
  │

error: cannot find `verify_ultrahonkzk_proof` in this scope
   ┌─ recurse_leaf/src/main.nr:13:5
   │
13 │     verify_ultrahonkzk_proof(
   │     ------------------------ not found in this scope
   │

Aborting due to 2 previous errors
error: Recipe `run-example` failed on line 182 with exit code 1
```

## User Documentation

Check one:
- [x] No user documentation needed.
- [ ] Changes in _docs/_ included in this PR.
- [ ] **[For Experimental Features]** Changes in _docs/_ to be submitted in a separate PR.

# PR Checklist

- [x] I have tested the changes locally.
- [ ] I have formatted the changes with [Prettier](https://prettier.io/) and/or `cargo fmt` on default settings.

### CODE REVIEW

File: examples/recursion/generate_recursive_proof.sh [hunk 1]
```diff
@@ -6,11 +6,15 @@ BACKEND=${BACKEND:-bb}
...
 # Generate vk for inner circuit
-$BACKEND write_vk -b ./target/sum.json -o ./target/sum --init_kzg_accumulator --output_format fields
+$BACKEND write_vk -b ./target/sum.json -o ./target/sum
+$BACKEND prove -b ./target/sum.json -w ./target/sum_witness.gz -o ./target/sum -k ./target/sum/vk
 
+# Convert binary outputs to JSON format for Noir
+python3 binary_to_fields.py ./target/sum/vk ./target/sum/vk_fields.json
+python3 binary_to_fields.py ./target/sum/vk_hash ./target/sum/vk_hash_fields.json
+python3 binary_to_fields.py ./target/sum/proof ./target/sum/proof_fields.json
+python3 binary_to_fields.py ./target/sum/public_inputs ./target/sum/public_inputs_fields.json
```
Comment (TomAFrench) [inline examples/recursion/generate_recursive_proof.sh]: Can we modify the script to print the result to stdout? we can then pipe directly into Prover.toml

File: examples/recursion/recurse_node/src/main.nr [hunk 2]
```diff
@@ -1,20 +1,20 @@
...
-use bb_proof_verification::{verify_ultrahonk_proof, UltraHonkProof, UltraHonkVerificationKey};
+use bb_proof_verification::{verify_ultrahonkzk_proof, UltraHonkZKProof, UltraHonkVerificationKey};
 
 
 fn main(
     verification_key: UltraHonkVerificationKey,
     public_inputs: pub [Field; NUM_NON_ACCUMULATOR_PUBLIC_INPUTS],
-    key_hash: Field,
-    proof: UltraHonkProof
+    key_hash: [Field; 1],
```
Comment (TomAFrench) [inline examples/recursion/recurse_node/src/main.nr]: We can use `jq` to unwrap the verification key hash in bash to avoid this leaking into the circuit.

File: examples/recursion/binary_to_fields.py
Comment (TomAFrench) [inline examples/recursion/binary_to_fields.py:1]: I hate this so much. Terrible UX for users but 🤷

File: examples/recursion/recurse_node/src/main.nr (hunk 2 above)
Comment (aakoshh) [reply examples/recursion/recurse_node/src/main.nr]: Okay, sure. I thought not using `jq` or `xxd` is one less dependency for the example, and the circuit is here to serve the example, so it doesn't matter that it's a bit overfitted to what we are dealing with, but if you prefer more stuff in the script, why not.

File: examples/recursion/binary_to_fields.py
Comment (aakoshh) [reply examples/recursion/binary_to_fields.py:1]: ➕
