### PR TITLE
fix(mem2reg): Keep last stores used in MakeArray

### LINKED ISSUE #8739: Compiler crash: `condition value is not a boolean: MismatchedBitSize` (without if-then)
### Aim

Similar to #8723 but without involving any if-then-else returning references.

The following program crashes the compiler:

```rust
fn main() {
    unsafe {
        func_2()
    }
}
unconstrained fn func_2() {
    let mut a: [&mut bool; 1] = [(&mut true)];
    let mut idx_b: u32 = 0;
    while (*a[0]) {
        if (idx_b == 0) {
            break
        }
    }
}

```

### Expected Behavior

Not to crash.

### Bug

```console
❯ cargo run -q -p nargo_cli -- compile
The application panicked (crashed).
Message:  condition value is not a boolean: MismatchedBitSize { value_bit_size: 254, expected_bit_size: 1 }
Location: /Users/aakoshh/Work/aztec/noir/acvm-repo/brillig_vm/src/lib.rs:455

```

### To Reproduce

See above. 

The crash does not occur if we use `unconstrained fn main`.

### Workaround

None

### Workaround Description

_No response_

### Additional Context

_No response_

### Project Impact

None

### Blocker Context

_No response_

### Nargo Version

nargo version = 1.0.0-beta.6 noirc version = 1.0.0-beta.6+7e6d7cdb32c806aa0622c1c73e2255a79d93637d (git version hash: 87cb094fa5946e69a77da53494c00547c2949569, is dirty: true)

### NoirJS Version

_No response_

### Proving Backend Tooling & Version

_No response_

### Would you like to submit a PR for this Issue?

None

### Support Needs

_No response_

### LINKED ISSUE #8755: Brillig != minimal: divide by zero; SSA interpeter: InternalError after step mem2reg
### Aim

Discovered testing https://github.com/noir-lang/noir/pull/8728

The following program succeeds with `--minimal-ssa` but fails otherwise:

```rust
unconstrained fn main() -> pub Field {
    func_2([(0, (&mut -292434322542114415011969994633470574393))])
}
unconstrained fn func_2(mut b: [(u32, &mut Field); 1]) -> Field {
    let mut idx_e: u32 = 0;
    loop {
        if (idx_e == 1) {
            break;
        } else {
            idx_e = (idx_e + 1);
        }
    }
    (157653526363045079447323020681982670581 / (*b[0].1))
}
```

### Expected Behavior

They should agree. 

### Bug

```console
❯ cargo run -q -p nargo_cli -- execute
[regression_fuzz_testing] Circuit witness successfully solved
[regression_fuzz_testing] Witness saved to target/regression_fuzz_testing.gz
[regression_fuzz_testing] Circuit output: Field(4740911027145274801807009652820289697178104761561901561018492048924696890497)

  ~/Work/aztec/noir/test_programs/execution_success/regression_fuzz_testing  af/7939-ast-fuzz-ref ⇡2 !1 ?1 ············································································································  23.6.0  1.85.0 15:45:0
❯ cargo run -q -p nargo_cli -- execute
error: Assertion failed: 'Attempted to divide by zero'
   ┌─ src/main.nr:13:6
   │
13 │     (157653526363045079447323020681982670581 / (*b[0].1))
   │      ---------------------------------------------------
   │
   = Call stack:
     1. src/main.nr:2:5
     2. src/main.nr:13:6

Failed assertion

```

### To Reproduce

See above. 

Further clues could be gleaned from the SSA interoperation results:

```console
❯ cargo run -q -p nargo_cli -- interpret 
--- Interpreter result after Initial SSA:
Ok([Numeric(Field(4740911027145274801807009652820289697178104761561901561018492048924696890497))])
---
--- Interpreter result after Removing Unreachable Functions (step 1):
Ok([Numeric(Field(4740911027145274801807009652820289697178104761561901561018492048924696890497))])
---
--- Interpreter result after Defunctionalization (step 2):
Ok([Numeric(Field(4740911027145274801807009652820289697178104761561901561018492048924696890497))])
---
--- Interpreter result after Inlining simple functions (step 3):
Ok([Numeric(Field(4740911027145274801807009652820289697178104761561901561018492048924696890497))])
---
--- Interpreter result after Removing Paired rc_inc & rc_decs (step 4):
Ok([Numeric(Field(4740911027145274801807009652820289697178104761561901561018492048924696890497))])
---
--- Interpreter result after Preprocessing Functions (step 5):
Ok([Numeric(Field(4740911027145274801807009652820289697178104761561901561018492048924696890497))])
---
--- Interpreter result after Inlining (step 6):
Ok([Numeric(Field(4740911027145274801807009652820289697178104761561901561018492048924696890497))])
---
--- Interpreter result after Mem2Reg (step 7):
Err(Internal(UninitializedReferenceValueLoaded { value: "*v17 = None" }))
---
```

### Workaround

None

### Workaround Description

_No response_

### Additional Context

_No response_

### Project Impact

None

### Blocker Context

_No response_

### Nargo Version

nargo version = 1.0.0-beta.6 noirc version = 1.0.0-beta.6+7e6d7cdb32c806aa0622c1c73e2255a79d93637d (git version hash: 393d8c496ace9fd30437ee3088cff6b8e78953d0, is dirty: true)

### NoirJS Version

_No response_

### Proving Backend Tooling & Version

_No response_

### Would you like to submit a PR for this Issue?

None

### Support Needs

_No response_

### LINKED ISSUE #8761: Compiler crash: Could not resolve some references to the array (without any dynamic index)
### Aim

Discovered testing https://github.com/noir-lang/noir/pull/8728

The following program crashes the compiler:

```rust
fn main() -> pub Field {
    let mut d: [&mut bool; 1] = [(&mut false)];

    for _ in 0..1 {} // Without this it compiles

    if (*d[0]) {
        0
    } else {
        1
    }
}
```

This must be related to https://github.com/noir-lang/noir/issues/8750 but unlike there, I don't think the "All references must be resolved at compile time" is justified, as the index is known at compile time.

The problem also goes away if the empty loop is removed.

### Expected Behavior

The circuit should return 1. 

### Bug

```console
❯ cargo run -q -p nargo_cli -- compile --force
The application panicked (crashed).
Message:  Expected RuntimeError to have a location. Error message: Could not resolve some references to the array. All references must be resolved at compile time
Location: compiler/noirc_evaluator/src/errors.rs:214
```

### To Reproduce

See above.

The `interpret` command suggests there might be something going haywire in mem2reg:
```console
❯ cargo run -q -p nargo_cli -- interpret
...
---
--- Interpreter result after Inlining (step 6):
Ok([Numeric(Field(1))])
---
--- Interpreter result after Mem2Reg (step 7):
Err(Internal(UninitializedReferenceValueLoaded { value: "*v15 = None" }))
...
```

### Workaround

None

### Workaround Description

_No response_

### Additional Context

_No response_

### Project Impact

None

### Blocker Context

_No response_

### Nargo Version

nargo version = 1.0.0-beta.6 noirc version = 1.0.0-beta.6+7e6d7cdb32c806aa0622c1c73e2255a79d93637d (git version hash: 393d8c496ace9fd30437ee3088cff6b8e78953d0, is dirty: true)

### NoirJS Version

_No response_

### Proving Backend Tooling & Version

_No response_

### Would you like to submit a PR for this Issue?

None

### Support Needs

_No response_

### PR DESCRIPTION
**Pull request by vezenovm**
# Description

## Problem\*

Resolves #8739 
Resolves #8755
Resolves #8761

## Summary\*

We have an optimization that runs through our remaining last stores and checks whether they are used anywhere. If not, we remove those last stores. This optimization was not accounting for references used in arrays. 

## Documentation\*

Check one:
- [X] No documentation needed.
- [ ] Documentation included in this PR.
- [ ] **[For Experimental Features]** Documentation to be submitted in a separate PR.

# PR Checklist\*

- [X] I have tested the changes locally.
- [X] I have formatted the changes with [Prettier](https://prettier.io/) and/or `cargo fmt` on default settings.

### CODE REVIEW

File: compiler/noirc_evaluator/src/ssa/opt/mem2reg.rs [hunk 1]
```diff
@@ -245,6 +249,12 @@ impl<'f> PerFunctionContext<'f> {
                     return true;
                 }
 
+                let allocation_aliases_parameter =
+                    aliases.any(|alias| self.make_array_references.contains(&alias));
+                if allocation_aliases_parameter == Some(true) {
```
Comment (jfecher) [inline compiler/noirc_evaluator/src/ssa/opt/mem2reg.rs]: Why do we keep naming these `allocation_aliases_parameter` when (it looks like) only the first two check parameters?

The others mention function calls, make_arrays, terminator values, and aliased references. Seems inaccurate.

File: test_programs/execution_success/regression_8739/src/main.nr [hunk 2]
```diff
@@ -0,0 +1,15 @@
...
+    // Safety: testing context
+    unsafe {
+        func_2()
+    }
+}
+unconstrained fn func_2() {
+    let mut a: [&mut bool; 1] = [(&mut true)];
+    let mut idx_b: u32 = 0;
+    while (*a[0]) {
+        if (idx_b == 0) {
```
Comment (jfecher) [inline test_programs/execution_success/regression_8739/src/main.nr]:
```suggestion
    let mut a: [&mut bool; 1] = [&mut true];
    let mut idx_b: u32 = 0;
    while *a[0] {
        if idx_b == 0 {
```
We do not bow to C

(I'm aware this was fuzzer generated)

File: compiler/noirc_evaluator/src/ssa/opt/mem2reg.rs (hunk 1 above)
Comment (vezenovm) [reply compiler/noirc_evaluator/src/ssa/opt/mem2reg.rs]: > The others mention function calls, make_arrays, terminator values, and aliased references. Seems inaccurate.

Oops yes you are correct. This is an oversight. I will update the naming here.

Comment (vezenovm) [reply compiler/noirc_evaluator/src/ssa/opt/mem2reg.rs]: done

File: compiler/noirc_evaluator/src/ssa/opt/mem2reg.rs [hunk 3]
```diff
@@ -140,6 +140,9 @@ struct PerFunctionContext<'f> {
     /// Track whether a reference was passed into another entry point
     /// This is needed to determine whether we can remove a store.
     calls_reference_input: HashSet<ValueId>,
+    /// Track whether a reference was passed into a make array instruction
+    /// This is needed to determine whether we can remove a store.
+    make_array_references: HashSet<ValueId>,
```
Comment (jfecher) [inline compiler/noirc_evaluator/src/ssa/opt/mem2reg.rs]: Does this need to be separate from `calls_reference_input`? Maybe they should be combined into `instructions_referencing_input`

Comment (vezenovm) [reply compiler/noirc_evaluator/src/ssa/opt/mem2reg.rs]: I felt it was clearer to also leave them separate, but I can merge and update the comments if that is preferred.

Comment (jfecher) [reply compiler/noirc_evaluator/src/ssa/opt/mem2reg.rs]: I don't think the distinction adds anything if we're treating them the same either way

Comment (vezenovm) [reply compiler/noirc_evaluator/src/ssa/opt/mem2reg.rs]: I have combined them

**Comment by vezenovm** [comment]
Added a regression test for #8755 that looks to still be broken under a minimum aggressive inliner, so will need to update that that.

**Comment by vezenovm** [comment]
This is ready for review again.

File: compiler/noirc_evaluator/src/ssa/opt/mem2reg.rs [hunk 4]
```diff
@@ -239,26 +239,27 @@ impl<'f> PerFunctionContext<'f> {
                     return true;
                 }
 
-                let allocation_aliases_parameter =
-                    aliases.any(|alias| self.calls_reference_input.contains(&alias));
-                if allocation_aliases_parameter == Some(true) {
+                let allocation_aliases_instr_input =
+                    aliases.any(|alias| self.instruction_input_references.contains(&alias));
+                if allocation_aliases_instr_input == Some(true) {
```
Comment (asterite) [inline compiler/noirc_evaluator/src/ssa/opt/mem2reg.rs:244]: Probably unrelated to this PR, but we always check that the result of `AliasSet::any` is `Some(true)`. We could maybe change `AliasSet::any` to return a bool to simplify this code a bit.

**Review by asterite — APPROVED** [review]
Looks good!

**Review by jfecher — APPROVED** [review]
LGTM
