### PR TITLE
fix(lsp): Improve dependency resolution in context of `Nargo.toml`

### LINKED ISSUE #1838: LSP: Cannot resolve local dependencies outside of the main file
### Aim

The LSP should work with local dependencies in files other than the `main.nr` file.

### Expected Behavior

When I create a file, such as `foo.nr` with this content:
```
use crate::bar::bar;

fn foo(x : Field, y : Field) {
    bar(x, y);
}
```
The dependency should not be a compile error.

### Bug

This bug stems from the fact that we compile the saved file (`foo.nr` in the example above) as the root of the project. Since the root file is expected to contain the `mod` definitions, but those are all specified in `main.nr`, the LSP compilation reports an error because there was no `mod bar`.

Side note: adding `mod bar` makes the file compile with no warnings via the LSP but `nargo compile` would fail because it is not actually the root.

### To Reproduce

1. Create a multi-file noir project
2. Use a `crate::` dependency in a file that is not `main.nr`
3. Save the file with the LSP running
4. Notice the diagnostic warning on the dependency

### Installation Method

None

### Nargo Version

_No response_

### Additional Context

_No response_

### Would you like to submit a PR for this Issue?

No

### Support Needs

_No response_

### PR DESCRIPTION
**Pull request by phated**
# Description

## Problem\*

Resolves #1838 

## Summary\*

This removes `lib_hacky.rs` in the LSP and replaces it with proper resolution of the `Nargo.toml` file and the dependencies in the project.

This is still a WIP as I need to consider how we handle encountering a workspace manifest 🤔 

## Documentation

- [ ] This PR requires documentation updates when merged.

  

  - [ ] I will submit a noir-lang/docs PR.

  

  - [ ] I will request for and support Dev Rel's help in documenting this PR.

  
  

## Additional Context

# PR Checklist\*

- [x] I have tested the changes locally.
- [x] I have formatted the changes with [Prettier](https://prettier.io/) and/or `cargo fmt` on default settings.

### CODE REVIEW

File: crates/lsp/src/lib.rs [hunk 1]
```diff
@@ -134,13 +101,9 @@ impl LspService for NargoLspService {
...
 
 fn on_initialize(
-    state: &mut LspState,
-    params: InitializeParams,
+    _state: &mut LspState,
+    _params: InitializeParams,
 ) -> impl Future<Output = Result<InitializeResult, ResponseError>> {
-    if let Some(root_uri) = params.root_uri {
-        state.root_path = root_uri.to_file_path().ok();
-    }
```
Comment (phated) [inline crates/lsp/src/lib.rs:142]: We could use the root path to build the entire project (even workspace manifest) upon initialize, but I'm not sure if we actually want to do that

File: crates/lsp/src/lib.rs [hunk 2]
```diff
@@ -167,57 +130,52 @@ fn on_shutdown(
...
+    let toml_path = find_package_manifest(program_dir).unwrap();
+    let workspace = resolve_workspace_from_toml(&toml_path, None).unwrap();
 
-    let crate_id = prepare_crate(&mut context, file_path);
+    let mut lenses: Vec<CodeLens> = vec![];
 
-    // We ignore the warnings and errors produced by compilation for producing codelenses
-    // because we can still get the test functions even if compilation fails
-    let _ = check_crate(&mut context, crate_id, false);
+    for package in &workspace {
```
Comment (phated) [inline crates/lsp/src/lib.rs:144]: Not sure what to do if we encounter a workspace manifest instead of a package manifest.

File: crates/lsp/src/lib.rs [hunk 3]
```diff
@@ -167,57 +130,52 @@ fn on_shutdown(
...
+            let location = context.function_meta(&func_id).name.location;
+            let file_id = location.file;
 
-        let range =
-            byte_span_to_range(files, file_id.as_usize(), location.span.into()).unwrap_or_default();
+            // Ignore diagnostics for any file that wasn't the file we saved
+            // TODO: In the future, we could create "related" diagnostics for these files
+            // TODO: This currently just appends the `.nr` file extension that we store as a constant,
+            // but that won't work if we accept other extensions
+            if fm.path(file_id).with_extension(FILE_EXTENSION) != file_path {
```
Comment (phated) [inline crates/lsp/src/lib.rs:162]: I really just wish we stored the extensions 🤦

File: crates/lsp/src/lib.rs (hunk 2 above)
Comment (phated) [reply crates/lsp/src/lib.rs:144]: rust-analyzer just ignores a `.rs` file outside of the workspace. I only have access to vscode-specific stuff like snippets, etc. No compiling or syntax errors are available. No warning is made that it is outside of the workspace.

Comment (kobyhallx) [reply crates/lsp/src/lib.rs:144]: I feel simplistic approach of allowing top-level workspace is enough for now.

**Review by kobyhallx — DISMISSED** [review]

File: crates/lsp/src/lib.rs [hunk 4]
```diff
@@ -167,57 +130,52 @@ fn on_shutdown(
...
-        }
-        None => {
-            let err = ResponseError::new(
-                ErrorCode::REQUEST_FAILED,
-                "Unable to determine the project root path",
-            );
-            return future::ready(Err(err));
-        }
-    };
+    let toml_path = find_package_manifest(program_dir).unwrap();
```
Comment (TomAFrench) [inline crates/lsp/src/lib.rs:139]: Nit. We can pass `file_path` directly into `find_package_manifest` here.

File: crates/lsp/src/lib.rs [hunk 5]
```diff
@@ -264,60 +222,56 @@ fn on_did_save_text_document(
...
-                "Unable to determine the project root path",
-            );
-            return ControlFlow::Break(Err(err.into()));
-        }
-    };
+    let file_path = params.text_document.uri.to_file_path().unwrap();
+    let program_dir = file_path.parent().unwrap();
 
-    let crate_id = prepare_crate(&mut context, file_path);
+    let toml_path = find_package_manifest(program_dir).unwrap();
```
Comment (TomAFrench) [inline crates/lsp/src/lib.rs:228]: Same here.

**Review by TomAFrench — APPROVED** [review]

File: crates/lsp/src/lib.rs (hunk 4 above)
Comment (phated) [reply crates/lsp/src/lib.rs:139]: I'd like to keep it the program dir, but that reminds me that these unwraps need to be handled gracefully 🤦

Comment (phated) [reply crates/lsp/src/lib.rs:139]: I suppose the argument is called `current_path` so that should work. I'll make the change.
