### PR TITLE
fix(mem2reg): Add the value in `ArraySet` to `aliased_references`

### LINKED ISSUE #8974: SSA interpreter: `UninitializedReferenceValueLoaded` after mem2reg, storing mut ref into array
### Aim

Trying to minimise the error in https://github.com/noir-lang/noir/actions/runs/15748645365/job/44389551968

The original error was different: the full pipeline divided by zero, the minimal pipeline did not. This error is gone in the minimised code, but the SSA interpreter reveals what could have been the original reason. 

```rust
unconstrained fn main() {
    let mut a = [&mut 1];
    let mut idx_c: u32 = 0;
    loop {
        if (idx_c == 2) {
            break
        } else {
            idx_c = (idx_c + 1);
            let d: Field = (-(*a[0])) / (*a[0]);
            a[0] = (&mut 2);
        }
    }
}
```

### Expected Behavior

The SSA interpreter should succeed. 

### Bug

```console
❯ cargo run -q -p nargo_cli -- interpret 
...
---
--- Interpreter result after Inlining (step 6):
Ok([])
---
--- Interpreter result after Mem2Reg (step 7):
Err(Internal(UninitializedReferenceValueLoaded { value: "*v41 = None" }))
```

The SSA shows the following:

```
❯ cargo run -q -p nargo_cli -- interpret --show-ssa-pass "step 6)" --show-ssa-pass "step 7)"
...
---
After Inlining (step 6):
brillig(inline) fn main f0 {
  b0():
    v0 = allocate -> &mut Field
    store Field 1 at v0
    v2 = make_array [v0] : [&mut Field; 1]
    v3 = allocate -> &mut [&mut Field; 1]
    store v2 at v3
    v4 = allocate -> &mut u32
    store u32 0 at v4
    jmp b1()
  b1():
    v6 = load v4 -> u32
    v8 = eq v6, u32 2
    jmpif v8 then: b2, else: b3
  b2():
    jmp b4()
  b3():
    v9 = load v4 -> u32
    v11 = add v9, u32 1
    store v11 at v4
    v12 = load v3 -> [&mut Field; 1]
    v13 = array_get v12, index u32 0 -> &mut Field
    v14 = load v13 -> Field
    v16 = sub Field 0, v14
    v17 = load v3 -> [&mut Field; 1]
    v18 = array_get v17, index u32 0 -> &mut Field
    v19 = load v18 -> Field
    v20 = div v16, v19
    v21 = allocate -> &mut Field
    store Field 2 at v21
    v23 = load v3 -> [&mut Field; 1]
    v24 = array_set v23, index u32 0, value v21
    store v24 at v3
    jmp b5()
  b4():
    return
  b5():
    jmp b1()
}

--- Interpreter result after Inlining (step 6):
Ok([])
---
After Mem2Reg (step 7):
brillig(inline) fn main f0 {
  b0():
    v0 = allocate -> &mut Field
    store Field 1 at v0
    v2 = make_array [v0] : [&mut Field; 1]
    v3 = allocate -> &mut [&mut Field; 1]
    store v2 at v3
    v4 = allocate -> &mut u32
    store u32 0 at v4
    jmp b1()
  b1():
    v6 = load v4 -> u32
    v8 = eq v6, u32 2
    jmpif v8 then: b2, else: b3
  b2():
    jmp b4()
  b3():
    v9 = load v4 -> u32
    v11 = add v9, u32 1
    store v11 at v4
    v12 = load v3 -> [&mut Field; 1]
    v13 = array_get v12, index u32 0 -> &mut Field
    v14 = load v13 -> Field
    v16 = sub Field 0, v14
    v17 = array_get v12, index u32 0 -> &mut Field
    v18 = load v17 -> Field
    v19 = div v16, v18
    v20 = allocate -> &mut Field
    v21 = array_set v12, index u32 0, value v20
    store v21 at v3
    jmp b5()
  b4():
    return
  b5():
    jmp b1()
}

```

After mem2reg the `store Field 2 at v21` is gone.

### To Reproduce

See above.

### Workaround

None

### Workaround Description

_No response_

### Additional Context

_No response_

### Project Impact

None

### Blocker Context

_No response_

### Nargo Version

nargo version = 1.0.0-beta.7 noirc version = 1.0.0-beta.7+71ab596c0f6ef955994d0af1c47f8e340a24898c (git version hash: e96b40c4214967f14da5beabf2570a2b082940e7, is dirty: true)

### NoirJS Version

_No response_

### Proving Backend Tooling & Version

_No response_

### Would you like to submit a PR for this Issue?

Maybe

### Support Needs

_No response_

### LINKED ISSUE #8975: Compiler crash: `condition value is not a boolean: MismatchedBitSize` (mem2reg)
### Aim

Minimisation of https://github.com/noir-lang/noir/actions/runs/15744321023/job/44377631767

```
NOIR_AST_FUZZER_SEED=0x8d7b02e200001000 cargo test -p noir_ast_fuzzer --test smoke
```

The following program crashes the compiler:

```rust
fn main() {
    unsafe { func_1() };
}
unconstrained fn func_1() {
    func_2([&mut true])
}
unconstrained fn func_2(mut b: [&mut bool; 1]) {
    b[0] = (&mut false);
    {
        let mut idx_c: u32 = 0;
        while (*b[0]) {
            if (idx_c == 0) {
                break
            }
        }
    };
}
```

### Expected Behavior

Shouldn't crash.

### Bug

```console
❯ cargo run -q -p nargo_cli -- compile
The application panicked (crashed).
Message:  condition value is not a boolean: MismatchedBitSize { value_bit_size: 254, expected_bit_size: 1 }
Location: /Users/aakoshh/Work/aztec/noir/acvm-repo/brillig_vm/src/lib.rs:453
```

The `interpret` command shows where the error happens:
```console
❯ cargo run -q -p nargo_cli -- interpret --show-ssa-pass "step 4)" --show-ssa-pass "step 5)"
warning: Unsafe block must have a safety comment above it
  ┌─ src/main.nr:2:5
  │
2 │     unsafe { func_1() };
  │     ------ The comment must start with the "Safety: " word
  │

--- Interpreter result after Initial SSA:
Ok([])
---
--- Interpreter result after Removing Unreachable Functions (step 1):
Ok([])
---
--- Interpreter result after Defunctionalization (step 2):
Ok([])
---
--- Interpreter result after Inlining simple functions (step 3):
Ok([])
---
After Removing Paired rc_inc & rc_decs (step 4):
acir(inline) fn main f0 {
  b0():
    call f1()
    return
}
brillig(inline) fn func_1 f1 {
  b0():
    v0 = allocate -> &mut u1
    store u1 1 at v0
    v2 = make_array [v0] : [&mut u1; 1]
    call f2(v2)
    return
}
brillig(inline) fn func_2 f2 {
  b0(v0: [&mut u1; 1]):
    v1 = allocate -> &mut [&mut u1; 1]
    store v0 at v1
    v2 = allocate -> &mut u1
    store u1 0 at v2
    v4 = load v1 -> [&mut u1; 1]
    v6 = array_set v4, index u32 0, value v2
    store v6 at v1
    v7 = allocate -> &mut u32
    store u32 0 at v7
    jmp b1()
  b1():
    v8 = load v1 -> [&mut u1; 1]
    v9 = array_get v8, index u32 0 -> &mut u1
    v10 = load v9 -> u1
    jmpif v10 then: b2, else: b3
  b2():
    v11 = load v7 -> u32
    v12 = eq v11, u32 0
    jmpif v12 then: b4, else: b5
  b3():
    return
  b4():
    jmp b3()
  b5():
    jmp b1()
}

--- Interpreter result after Removing Paired rc_inc & rc_decs (step 4):
Ok([])
---
After Preprocessing Functions (step 5):
acir(inline) fn main f0 {
  b0():
    call f1()
    return
}
brillig(inline) fn func_1 f1 {
  b0():
    v0 = allocate -> &mut u1
    store u1 1 at v0
    v2 = make_array [v0] : [&mut u1; 1]
    call f2(v2)
    return
}
brillig(inline) fn func_2 f2 {
  b0(v0: [&mut u1; 1]):
    v1 = allocate -> &mut [&mut u1; 1]
    v2 = allocate -> &mut u1
    v4 = array_set v0, index u32 0, value v2
    store v4 at v1
    v5 = allocate -> &mut u32
    store u32 0 at v5
    jmp b1()
  b1():
    v6 = load v1 -> [&mut u1; 1]
    v7 = array_get v6, index u32 0 -> &mut u1
    v8 = load v7 -> u1
    jmpif v8 then: b2, else: b3
  b2():
    v9 = load v5 -> u32
    v10 = eq v9, u32 0
    jmpif v10 then: b4, else: b5
  b3():
    return
  b4():
    jmp b3()
  b5():
    jmp b1()
}
```

The problem is that `store v0 at v1` is removed, and so is `store u1 0 at v2`.

### To Reproduce

1.
2.
3.
4.

### Workaround

None

### Workaround Description

_No response_

### Additional Context

_No response_

### Project Impact

None

### Blocker Context

_No response_

### Nargo Version

nargo version = 1.0.0-beta.7 noirc version = 1.0.0-beta.7+71ab596c0f6ef955994d0af1c47f8e340a24898c (git version hash: e96b40c4214967f14da5beabf2570a2b082940e7, is dirty: true)

### NoirJS Version

_No response_

### Proving Backend Tooling & Version

_No response_

### Would you like to submit a PR for this Issue?

None

### Support Needs

_No response_

### PR DESCRIPTION
**Pull request by aakoshh**
# Description

## Problem\*

Resolves #8975 
Fixes #8974

I also verified that `NOIR_AST_FUZZER_SEED=0x8d7b02e200001000 cargo test -p noir_ast_fuzzer --test smoke` no longer crashes.

## Summary\*

* Add the input `value` to `ArraySet` to the `aliased_references`. 
* Change `analyze_instruction` so that if the instruction simplifies into a `MakeArray` instruction then it doesn't skip it, because the book keeping might be needed to keep alive stores to references used in the simplified instruction.

I'm not sure if this last step would need to be restricted to only a do a subset of the book keeping. What's sure if that if I allowed the analyse to go ahead as it is on all instruction types, then the compiler started crashing.

## Additional Context

Originally I thought about adding the value to the `instruction_input_references`, but I re-read what @vezenovm [commented](https://github.com/noir-lang/noir/pull/8877#discussion_r2141173498) about why we don't use this technique whenever a variable is an input to an instruction: he suggested that adding to this collection too aggressively would prevent the removal of stores that go into arrays that aren't used.

By contrast the `aliased_references` only prevents the removal of a store if there are outstanding instructions that rely on the value.

In this failure we had an SSA like this:

```rust
acir(inline) fn main f0 {
  b0():
    call f1()
    return u1 1
}
brillig(inline) fn func_1 f1 {
  b0():
    v0 = allocate -> &mut u1
    store u1 1 at v0
    v2 = make_array [v0] : [&mut u1; 1]
    call f2(v2)
    return
}
brillig(inline) fn func_2 f2 {
  b0(v0: [&mut u1; 1]):
    v1 = allocate -> &mut [&mut u1; 1]
    store v0 at v1
    v2 = allocate -> &mut u1
    store u1 0 at v2
    v4 = load v1 -> [&mut u1; 1]
    v6 = array_set v4, index u32 0, value v2
    store v6 at v1
    v7 = allocate -> &mut u32
    store u32 0 at v7
    jmp b1()
  b1():
    v8 = load v1 -> [&mut u1; 1]
    v9 = array_get v8, index u32 0 -> &mut u1
    v10 = load v9 -> u1
    jmpif v10 then: b2, else: b3
  b2():
    v11 = load v7 -> u32
    v12 = eq v11, u32 0
    jmpif v12 then: b4, else: b5
  b3():
    return
  b4():
    jmp b3()
  b5():
    jmp b1()
}
```

After `mem2reg`, the `store u1 0 at v2` was gone, even though `v6 = array_set v4, index u32 0, value v2` clearly uses `v2`. 

## Documentation\*

Check one:
- [x] No documentation needed.
- [ ] Documentation included in this PR.
- [ ] **[For Experimental Features]** Documentation to be submitted in a separate PR.

# PR Checklist\*

- [x] I have tested the changes locally.
- [ ] I have formatted the changes with [Prettier](https://prettier.io/) and/or `cargo fmt` on default settings.

### CODE REVIEW

**Comment by aakoshh** [comment]
It still fails with `--inliner-aggressiveness 0 --force-brillig`:

```console
❯ cargo run -q -p nargo_cli -- interpret --force --inliner-aggressiveness 0 --force-brillig --show-ssa-pass "step 6)" --show-ssa-pass "step 7)"
--- Interpreter result after Initial SSA:
Ok([Numeric(U1(true))])
---
--- Interpreter result after Removing Unreachable Functions (step 1):
Ok([Numeric(U1(true))])
---
--- Interpreter result after Defunctionalization (step 2):
Ok([Numeric(U1(true))])
---
--- Interpreter result after Inlining simple functions (step 3):
Ok([Numeric(U1(true))])
---
--- Interpreter result after Removing Paired rc_inc & rc_decs (step 4):
Ok([Numeric(U1(true))])
---
--- Interpreter result after Preprocessing Functions (step 5):
Ok([Numeric(U1(true))])
---
After Inlining (step 6):
brillig(inline) fn main f0 {
  b0():
    v0 = allocate -> &mut u1
    store u1 1 at v0
    v2 = make_array [v0] : [&mut u1; 1]
    v3 = allocate -> &mut [&mut u1; 1]
    store v2 at v3
    v4 = allocate -> &mut u1
    store u1 0 at v4
    v6 = load v3 -> [&mut u1; 1]
    v8 = array_set v6, index u32 0, value v4
    store v8 at v3
    v9 = allocate -> &mut u32
    store u32 0 at v9
    jmp b1()
  b1():
    v10 = load v3 -> [&mut u1; 1]
    v11 = array_get v10, index u32 0 -> &mut u1
    v12 = load v11 -> u1
    jmpif v12 then: b2, else: b3
  b2():
    v13 = load v9 -> u32
    v14 = eq v13, u32 0
    jmpif v14 then: b4, else: b5
  b3():
    return u1 1
  b4():
    jmp b3()
  b5():
    jmp b1()
}

--- Interpreter result after Inlining (step 6):
Ok([Numeric(U1(true))])
---
After Mem2Reg (step 7):
brillig(inline) fn main f0 {
  b0():
    v0 = allocate -> &mut u1
    v1 = make_array [v0] : [&mut u1; 1]
    v2 = allocate -> &mut [&mut u1; 1]
    v3 = allocate -> &mut u1
    v4 = make_array [v3] : [&mut u1; 1]
    store v4 at v2
    v5 = allocate -> &mut u32
    store u32 0 at v5
    jmp b1()
  b1():
    v7 = load v2 -> [&mut u1; 1]
    v8 = array_get v7, index u32 0 -> &mut u1
    v9 = load v8 -> u1
    jmpif v9 then: b2, else: b3
  b2():
    v10 = load v5 -> u32
    v11 = eq v10, u32 0
    jmpif v11 then: b4, else: b5
  b3():
    return u1 1
  b4():
    jmp b3()
  b5():
    jmp b1()
}

--- Interpreter result after Mem2Reg (step 7):
Err(Internal(UninitializedReferenceValueLoaded { value: "*v3 = None" }))
---
The application panicked (crashed).
Message:  Expected a non-error result: Internal(UninitializedReferenceValueLoaded { value: "*v3 = None" })
Location: tooling/nargo_cli/src/cli/interpret_cmd.rs:272

This is a bug. We may have already fixed this in newer versions of Nargo so try searching for similar issues at https://github.com/noir-lang/noir/issues/.
If there isn't an open issue for this bug, consider opening one at https://github.com/noir-lang/noir/issues/new?labels=bug&template=bug_report.yml


```

**Comment by aakoshh** [comment]
In the above SSA, the `array_set` is optimised into a `make_array`, however because of that, the book keeping in `analyze_instruction` is skipped, which in this case means `make_array [v3]` did not keep around the `store` to `v3` (originally `store u1 0 at v4`) 🤔

File: compiler/noirc_evaluator/src/ssa/opt/mem2reg.rs [hunk 1]
```diff
@@ -401,19 +402,30 @@ impl<'f> PerFunctionContext<'f> {
...
+        // If the instruction was simplified and optimized out of the program we shouldn't analyze it.
+        // Analyzing it could make tracking aliases less accurate if it is e.g. an ArrayGet
         // call that used to hold references but has since been optimized out to a known result.
-        if let Some(new_id) = self.inserter.push_instruction(instruction, block_id) {
-            instruction = new_id;
-        } else {
-            return;
-        }
+        // However, if we don't analyze it, then it may be a MakeArray replacing an ArraySet containing references,
+        // and we need to mark those references as used to keep their stores alive.
```
Comment (asterite) [inline compiler/noirc_evaluator/src/ssa/opt/mem2reg.rs:411]: If we are only interested in the `MakeArray` case when it's been simplified, I wonder if we could use an early return instead of the many `!simplified`. Maybe something like this:

```rust
        let instr = &self.inserter.function.dfg[instruction];
        if simplified && !matches!(instr, Instruction::MakeArray { .. }) {
            return;
        }

        match instr {
```

(though I'd rename `instruction` to `instruction_id`, then `inst` above to `instruction`)

Comment (aakoshh) [reply compiler/noirc_evaluator/src/ssa/opt/mem2reg.rs:411]: I also was going back and forth with this. I thought that maybe we would need to enable parts of the match bodies, like do book keeping but don't insert instructions, and then it would make sense this way. But I agree it would be currently easier to see what's going on the way you suggest. I'll change it.
