### PR TITLE
fix: use correct meta attribute names in contract custom attributes

### LINKED ISSUE #8255: "(quoted)" function custom attribute
### Aim

I was trying to get rid of the full path of the utility function in the function custom attribute by doing the following in the Aztec macros:

Image

Unfortunately I got this in the artifact instead of "utility":

Image

### Expected Behavior

Get "utility" in the custom attributes.

### Bug

...

### To Reproduce

1. Checkout `04-28-chore_utility_func_attr_without_full_path_in_abi` branch in aztec-packages
2. bootstrap the repo
3. in `noir-projects/noir-contracts/target/auth_registry_contract-AuthRegistry.json` in search for `sync_notes` function and you should see "(quoted)" in the function attributes.

### Workaround

None

### Workaround Description

_No response_

### Additional Context

_No response_

### Project Impact

None

### Blocker Context

_No response_

### Nargo Version

_No response_

### NoirJS Version

_No response_

### Proving Backend Tooling & Version

_No response_

### Would you like to submit a PR for this Issue?

None

### Support Needs

_No response_

### PR DESCRIPTION
**Pull request by asterite**
# Description

## Problem

Resolves #8255

## Summary

To do this:
- I wanted a test for this and one thing we can do is to start capturing snapshots of contract artifacts, which is what I did here (second commit)
- However, when I did that I noticed the output of functions was not deterministic. So the first commit makes it deterministic by sorting by function name.
- The third commit is the actual fix to the issue, and you can see in the diff how "(quoted)" changed to "utility" (and also how "super::add_utility" changed to "add_utility"), proving that the fix works 😊 

## Documentation

Check one:
- [x] No documentation needed.
- [ ] Documentation included in this PR.
- [ ] **[For Experimental Features]** Documentation to be submitted in a separate PR.

# PR Checklist

- [x] I have tested the changes locally.
- [x] I have formatted the changes with [Prettier](https://prettier.io/) and/or `cargo fmt` on default settings.

### CODE REVIEW

File: tooling/nargo_cli/tests/execute.rs [hunk 1]
```diff
@@ -341,19 +360,50 @@ mod tests {
...
+        force_brillig: ForceBrillig,
+        inliner: Inliner,
+    ) {
+        let artifact_filename =
+            find_program_artifact_in_dir(target_dir).expect("Expected an artifact to exist");
+
+        let artifact_file = fs::File::open(&artifact_filename).unwrap();
+        let artifact: ContractArtifact = serde_json::from_reader(artifact_file).unwrap();
+
+        let _ = fs::remove_dir_all(target_dir);
```
Comment (michaeljklein) [inline tooling/nargo_cli/tests/execute.rs:381]: Is this silently ignoring failures?

**Review by michaeljklein — CHANGES_REQUESTED** [review]

File: compiler/noirc_driver/src/lib.rs [hunk 2]
```diff
@@ -497,16 +497,19 @@ pub fn compile_contract(
...
             id.as_function().map(|function_id| {
+                let name = context.def_interner.function_name(&function_id);
                 let attrs = context.def_interner.function_attributes(&function_id);
                 let is_entry_point = attrs.is_contract_entry_point();
-                ContractFunctionMeta { function_id, is_entry_point }
+                (ContractFunctionMeta { function_id, is_entry_point }, name)
             })
         })
         .collect();
+    functions.sort_by_key(|(_, name)| *name);
```
[the remark this answers is not in the document]
Comment (asterite) [reply compiler/noirc_driver/src/lib.rs:511]: 1. I don't think so. You can't have two functions named the same inside a contract.
2. It isn't because the values come from a HashMap and that's not ordered.
3. No, because the functions here are just for one contract so it's impossible to end up with functions from different contracts here.

Then I thought: but wait! What if you have more than one contract in the same crate? But it seems that errors with "Packages are limited to a single contract" so I think there's no chance of collition.

File: tooling/nargo_cli/tests/execute.rs (hunk 1 above)
Comment (asterite) [reply tooling/nargo_cli/tests/execute.rs:381]: Yes, but I'm not sure we should fail the test because of a missing cleanup. Or yes?

Comment (michaeljklein) [reply tooling/nargo_cli/tests/execute.rs:381]: Yes, I think so: missing cleanup could cause knock-on effects that we could have trouble debugging otherwise

File: compiler/noirc_driver/src/lib.rs (hunk 2 above)
[the remark this answers is not in the document]
Comment (michaeljklein) [reply compiler/noirc_driver/src/lib.rs:511]: > 2. It isn't because the values come from a HashMap and that's not ordered.

Ah, then would it make sense to use a `BTreeMap` or other more deterministic data structure for this so that we don't accidentally cause other forms of non-determinism by accessing it elsewhere?

File: tooling/nargo_cli/tests/execute.rs (hunk 1 above)
Comment (asterite) [reply tooling/nargo_cli/tests/execute.rs]: Done!

File: compiler/noirc_driver/src/lib.rs (hunk 2 above)
[the remark this answers is not in the document]
Comment (asterite) [reply compiler/noirc_driver/src/lib.rs]: Done!

**Review by michaeljklein — APPROVED** [review]

**Review by jfecher — APPROVED** [review]
:+1:
