### PR TITLE
short circuit for functions

### LINKED ISSUE #474: No `constraint is always false` error within if statement
# Description

## Aim

Running the code in the `9_conditional` test

## Expected behavior

Expected a `constraint is always false` error to be issued on the line
```rs
fn must_be_zero(x: u8) {
    constrain x == 0;
}
```
As a result of this call:
```rust
must_be_zero(1);
```

## Bug

The current ssa pass does not seem to catch this error, it was found when it was caught by the partial evaluator pass in PR #462 .

# To reproduce

(Describe the steps to reproduce the behavior.)

1. `cd crates/nargo/tests/test_data/9_conditional`
2. `nargo prove p`
3. Observe that no error is issued

### PR DESCRIPTION
**Pull request by guipublic**
# Related issue(s)

Resolves #474 and partially solves #472

# Description

## Summary of changes

This PR adds short-circuit for functions and delay error reporting in the SSA pass until the conditional statements are handled.
The location is made optional instead of using a dummy location.
It should be made mandatory again by providing locations to basic blocks, but this should be done in another PR.

## Test additions / changes

Regression test is added to 9_conditional test.

# Checklist

- [X] I have tested the changes locally.
- [X] I have formatted the changes with [Prettier](https://prettier.io/) and/or `cargo fmt` with default settings.
- [X] I have [linked](https://docs.github.com/en/issues/tracking-your-work-with-issues/linking-a-pull-request-to-an-issue) this PR to he issue(s) that it resolves.
- [X] I have reviewed the changes on GitHub, line by line.
- [X] I have ensured all changes are covered in the description.

### CODE REVIEW

File: crates/noirc_evaluator/src/ssa/block.rs [hunk 1]
```diff
@@ -373,6 +376,34 @@ pub fn rewire_block_left(ctx: &mut SsaContext, block_id: BlockId, left: BlockId)
...
+    //return:
+    let ret_pos = ctx[target].instructions.iter().position(|x| {
+        if let Some(ins) = ctx.try_get_instruction(*x) {
+            return ins.operation.opcode() == Opcode::Return;
+        }
+        false
+    });
+    if let Some(ret) = ret_pos {
+        let ret_id = ctx[target].instructions[ret];
+        stack.push(ret_id);
```
Comment (jfecher) [inline crates/noirc_evaluator/src/ssa/block.rs:402]: Can we move this directly into the check on line 396 instead of checking again?

File: crates/noirc_evaluator/src/ssa/context.rs [hunk 2]
```diff
@@ -525,7 +525,7 @@ impl SsaContext {
         //Add a new instruction to the nodes arena
         let mut i = Instruction::new(opcode, optype, Some(self.current_block));
         //Basic simplification
-        optim::simplify(self, &mut i)?;
+        optim::simplify(self, &mut i).err();
```
Comment (jfecher) [inline crates/noirc_evaluator/src/ssa/context.rs:528]: Why was this changed to no longer forward the error?

File: crates/noirc_evaluator/src/ssa/flatten.rs [hunk 3]
```diff
@@ -125,7 +125,7 @@ pub fn unroll_std_block(
                     Operation::Jmp(block) => assert_eq!(block, next),
                     Operation::Nop => (),
                     _ => {
-                        optim::simplify(ctx, &mut new_ins)?;
+                        optim::simplify(ctx, &mut new_ins).err();
```
Comment (jfecher) [inline crates/noirc_evaluator/src/ssa/flatten.rs:128]: And here

File: crates/noirc_evaluator/src/ssa/node.rs [hunk 4]
```diff
@@ -800,7 +804,10 @@ impl Binary {
             }
             BinaryOp::Div => {
                 if r_is_zero {
-                    todo!("Panic - division by zero");
+                    return Err(RuntimeError {
+                        location: None,
```
Comment (jfecher) [inline crates/noirc_evaluator/src/ssa/node.rs:808]: Definitely looks like a RuntimeError constructor taking only a RuntimeErrorKind could be useful here. Perhaps even a `impl From<RuntimeErrorKind> for RuntimeError` where the location defaults to None. We could slowly remove these over time then once we have more locations threaded through SSA.

File: crates/noirc_evaluator/src/ssa/optim.rs [hunk 5]
```diff
@@ -337,7 +345,12 @@ fn cse_block_with_anchor(
             update.parent_block = block_id;
 
             let mut update2 = update.clone();
-            simplify(ctx, &mut update2)?;
+            let err = simplify(ctx, &mut update2).err();
+            if let Some(err) = err {
+                if stop_on_error {
```
Comment (jfecher) [inline crates/noirc_evaluator/src/ssa/optim.rs:350]: Can replace both ifs with
```rs
let result = simplify(ctx, &mut update2);
if stop_on_error {
    result?;
}
```

File: crates/noirc_evaluator/src/errors.rs [hunk 6]
```diff
@@ -22,7 +22,7 @@ impl RuntimeError {
 }
 
 impl RuntimeErrorKind {
-    pub fn add_location(self, location: Location) -> RuntimeError {
+    pub fn add_location(self, location: Option<Location>) -> RuntimeError {
```
[the remark this answers is not in the document]
Comment (guipublic) [reply crates/noirc_evaluator/src/errors.rs:25]: Done

File: crates/noirc_evaluator/src/ssa/block.rs [hunk 7]
```diff
@@ -127,30 +127,33 @@ impl BasicBlock {
...
+                    }
+
+                    if let node::Operation::Constrain(a, _) = ins.operation {
+                        if a == ctx.zero() || Some(a) == cond {
+                            return true;
                         }
                     }
                 }
             }
+            if i > 3 {
```
[the remark this answers is not in the document]
Comment (guipublic) [reply crates/noirc_evaluator/src/ssa/block.rs:152]: Done

File: crates/noirc_evaluator/src/ssa/node.rs (hunk 4 above)
Comment (guipublic) [reply crates/noirc_evaluator/src/ssa/node.rs:808]: Done

File: crates/noirc_evaluator/src/ssa/optim.rs (hunk 5 above)
Comment (guipublic) [reply crates/noirc_evaluator/src/ssa/optim.rs:350]: Done

File: crates/noirc_evaluator/src/ssa/inline.rs [hunk 8]
```diff
@@ -320,14 +321,24 @@ pub fn inline_in_block(
...
                     }
 
-                    optim::simplify(ctx, &mut new_ins)?;
-
+                    let err = optim::simplify(ctx, &mut new_ins);
+                    if err.is_err() {
+                        //add predicate if under condition, else short-circuit the target block.
+                        let ass_value = decision.get_assumption_value(predicate);
+                        #[allow(clippy::unnecessary_unwrap)]
+                        if ass_value.is_some() && ctx.under_assumption(ass_value.unwrap()) {
```
[the remark this answers is not in the document]
Comment (guipublic) [reply crates/noirc_evaluator/src/ssa/inline.rs:334]: Done

File: crates/noirc_evaluator/src/ssa/context.rs (hunk 2 above)
Comment (guipublic) [reply crates/noirc_evaluator/src/ssa/context.rs:528]: That's the main point of the PR; to not send runtime errors until the IF instructions are processed.
Here the function is used to generate the SSA code when processing the AST so we cannot have processed the IF instructions.

File: crates/noirc_evaluator/src/ssa/flatten.rs [hunk 9]
```diff
@@ -41,7 +41,7 @@ fn eval_block(block_id: BlockId, eval_map: &HashMap<NodeId, NodeEval>, ctx: &mut
         if let Some(ins) = ctx.try_get_mut_instruction(*i) {
             ins.operation = update_operator(&ins.operation, eval_map);
             let ins_id = ins.id;
-            optim::simplify_id(ctx, ins_id).unwrap();
+            optim::simplify_id(ctx, ins_id).err();
```
[the remark this answers is not in the document]
Comment (guipublic) [reply crates/noirc_evaluator/src/ssa/flatten.rs:44]: Same answer here, the unrolling is done before the handling of IF statements.

File: crates/noirc_evaluator/src/ssa/function.rs [hunk 10]
```diff
@@ -72,15 +74,54 @@ impl SSAFunction {
...
 
-        //merge blocks
-        let to_remove =
-            super::block::merge_path(&mut igen.context, self.entry_block, BlockId::dummy(), None);
+        let mut to_remove: VecDeque<BlockId> = VecDeque::new();
+
+        let result = decision.make_decision_tree(&mut igen.context, builder);
+        if result.is_err() {
+            //short-circuit for function: false constraint and return 0
+            let unreachable = node::Operation::Constrain(igen.context.zero(), None);
```
[the remark this answers is not in the document]
Comment (guipublic) [reply crates/noirc_evaluator/src/ssa/function.rs]: In fact this part is similar to what is done in block::short_circuit_inline(), so I have created a function which is called in both cases.
While testing this, I realized the short-circuit was deleting its own condition in the else branch, which I fixed in conditional.rs.

File: crates/noirc_evaluator/src/errors.rs [hunk 11]
```diff
@@ -64,7 +64,8 @@ impl RuntimeErrorKind {
 
 impl DiagnosableError for RuntimeError {
     fn to_diagnostic(&self) -> Diagnostic {
-        let span = self.location.span;
+        let span =
+            if let Some(loc) = self.location { loc.span } else { noirc_errors::Span::new(0..0) };
```
[the remark this answers is not in the document]
Comment (guipublic) [reply crates/noirc_evaluator/src/errors.rs:72]: I did not want to do too many changes since we want to revert this so that all errors have location in fine.

File: crates/noirc_evaluator/src/ssa/code_gen.rs [hunk 12]
```diff
@@ -526,7 +526,7 @@ impl IRGenerator {
                 let rhs = self.codegen_expression(&binary.rhs)?.to_node_ids();
                 if lhs.len() != 1 || rhs.len() != 1 {
                     return Err(RuntimeError {
-                        location: noirc_errors::Location::dummy(),
+                        location: None,
```
Comment (jfecher) [inline crates/noirc_evaluator/src/ssa/code_gen.rs:529]: Can use RuntimeErrorKind::into here now

File: crates/noirc_evaluator/src/ssa/conditional.rs [hunk 13]
```diff
@@ -436,12 +448,16 @@ impl DecisionTree {
         stack: &mut StackFrame,
         condition: NodeId,
         error_msg: &str,
-    ) {
+    ) -> Result<(), RuntimeError> {
         if ctx.under_assumption(condition) {
-            block::short_circuit_instructions(ctx, &stack.stack);
+            let avoid = if stack.stack.contains(&condition) { Some(&condition) } else { None };
```
Comment (jfecher) [inline crates/noirc_evaluator/src/ssa/conditional.rs:453]: This can be `stack.stack.contains(&condition).then_some(&condition)`

File: crates/noirc_evaluator/src/ssa/conditional.rs [hunk 14]
```diff
@@ -457,8 +473,12 @@ impl DecisionTree {
                 Some(stack.block),
             ));
             stack.push(ins2);
+            Ok(())
         } else {
-            unreachable!("{}", error_msg);
+            Err(RuntimeError {
+                location: None,
```
Comment (jfecher) [inline crates/noirc_evaluator/src/ssa/conditional.rs:479]: RuntimeErrorKind::into

File: crates/noirc_evaluator/src/ssa/node.rs [hunk 15]
```diff
@@ -787,7 +790,7 @@ impl Binary {
 
             BinaryOp::Udiv => {
                 if r_is_zero {
-                    todo!("Panic - division by zero");
+                    return Err(RuntimeErrorKind::Spanless(zero_div_error).into());
```
Comment (jfecher) [inline crates/noirc_evaluator/src/ssa/node.rs:793]: Since we're constructing the same error in each spot, can we move the construction to the variable zero_div_error as well?

File: crates/noirc_frontend/src/monomorphisation/mod.rs [hunk 16]
```diff
@@ -387,7 +387,7 @@ impl Monomorphiser {
             definitions.push(new_expr);
         }
 
-        ast::Expression::Block(definitions)
+        ast::Expression::Tuple(definitions)
```
Comment (jfecher) [inline crates/noirc_frontend/src/monomorphisation/mod.rs:390]: Why was this changed to a tuple? The intention here was to extract each field of the tuple into a separate let binding in the same block, so:
```rs
let (a, b, c) = (1, 2, 3);
```
becomes
```rs
{
    let _ = (1, 2, 3);
    let a = _.0;
    let b = _.1;
    let c = _.2;
}
```
No need to return a tuple

Comment (guipublic) [reply crates/noirc_frontend/src/monomorphisation/mod.rs:390]: At some point I was experimenting with location in block of expressions and switching to a Tuple allowed me not to handle the case here, and it did not break anything. I decided to keep the change to get your feedback.
Isn't returning a tuple the correct thing to do here?

Comment (jfecher) [reply crates/noirc_frontend/src/monomorphisation/mod.rs:390]: It isn't correct in general since this isn't meant to be returning a tuple. This function is called when compiling let bindings that have a tuple pattern as the lhs, like the first example I gave above. So it is meant to expand it into 3+1 separate let bindings instead so later passes don't have to worry about unpacking/repacking values so much. This allows them to have "1 let binding = 1 DefinitionId" which isn't true if the let binding defines multiple variables in a tuple/struct pattern.

Now, since let bindings only return unit values which are ignored, it is technically fine if they return a tuple instead as it should be ignored as well. However, this means there is no reason to construct the tuple to begin with.

If you want to add a location to block patterns, I'd say it is fine to add a location to let bindings in general and grab that one.

Comment (guipublic) [reply crates/noirc_frontend/src/monomorphisation/mod.rs:390]: I have reverted it

File: crates/noirc_evaluator/src/ssa/node.rs (hunk 15 above)
Comment (guipublic) [reply crates/noirc_evaluator/src/ssa/node.rs:793]: Done

File: crates/noirc_evaluator/src/ssa/code_gen.rs (hunk 12 above)
Comment (guipublic) [reply crates/noirc_evaluator/src/ssa/code_gen.rs:529]: Done

File: crates/noirc_evaluator/src/ssa/context.rs (hunk 2 above)
Comment (jfecher) [reply crates/noirc_evaluator/src/ssa/context.rs:528]: Wouldn't this mean we throw out any errors that may be found before then? E.g. if a constraint is always false?

Perhaps it is expected when we pass through this block again afterward we will regenerate the same error but I wonder if there are cases where this may not be true. E.g. if there are errors that can happen for only these passes or if an instruction generates an error but is deleted and not reviewed again.

Comment (guipublic) [reply crates/noirc_evaluator/src/ssa/context.rs:528]: The different passes should not change the behavior of the code (unless there is a bug), so the false constraint will be fired eventually later on. Even if it is not handled (but it should not happen), it is part of the instruction set (again unless there is a bug) and will fail in the output circuit, so I think we are safe.

Comment (jfecher) [reply crates/noirc_evaluator/src/ssa/context.rs:528]: I'm still somewhat hesitant on this but suppose it is fine if it is limited to `optim::simplify` which is called often. I will say lets change it to `.ok()` which is somewhat more common for ignoring errors, and lets add a comment for each case briefly explaining/justifying why we're ignoring errors in these instances.

File: crates/noirc_evaluator/src/ssa/block.rs (hunk 1 above)
Comment (guipublic) [reply crates/noirc_evaluator/src/ssa/block.rs:410]: you want to put this code in the closure of position()?

Comment (jfecher) [reply crates/noirc_evaluator/src/ssa/block.rs:410]: Yes, I don't think it is necessary to return the optional position then push to the stack afterward when we can do it inside the closure or as for loop in one step.

Comment (guipublic) [reply crates/noirc_evaluator/src/ssa/block.rs:410]: I go for a for loop then

File: crates/noirc_evaluator/src/ssa/context.rs (hunk 2 above)
Comment (guipublic) [reply crates/noirc_evaluator/src/ssa/context.rs]: Done

**Review by jfecher — APPROVED** [review]
