### PR TITLE
fix(ssa): Avoid generating invalid dispatch from ACIR to Brillig lambdas

### LINKED ISSUE #10975: Compiler crashes in remove_if_else for std::hint::black_box
## Summary

There are multiple plausible compiler crashes in the `remove_if_else` pass because of wrong assumptions regarding elements passed to the `std::hint::black_box` function which could be 
- zero-sized items
- not-a-slice
- multiple values (e.g. tuples)
- unexpected values (e.g. closures)

### zero-sized items
```noir
fn main() {
    std::hint::black_box(());
}
```

```sh
The application panicked (crashed).
Message:  expected at least one argument to Hint::BlackBox
Location: compiler/noirc_evaluator/src/ssa/opt/remove_if_else.rs:363
```

### not-a-slice
Another one by tricking the black_box function with more than 1 argument, the last one not being part of the `slices_size`:
```noir
fn main(val: str<3>, flag: bool) {
    let b = val.as_bytes();
    let s = b.as_slice();
    let (_, s1) = s.pop_front();
    let (s2, _) = s.pop_back();
    let (s3, s4, _) = std::hint::black_box((s1, s2, 1));
    let s5 = if flag {
        s3
    } else {
        s4
    };
    println(s5);
}
```

```sh
The application panicked (crashed).
Message:  internal error: entered unreachable code: ICE: No size for slice v17 = Instruction { instruction: Id(3), position: 1, typ: Slice([Numeric(Unsigned { bit_size: 8 })]) }
Location: compiler/noirc_evaluator/src/ssa/opt/remove_if_else.rs:288
```

### multiple values

Another crash for the `assertion failed: arguments.len() == 2` when passing multiple values, the last one being a slice:
```noir
fn main(val: str<1>) {
    let b = val.as_bytes();
    let s = b.as_slice();
    std::hint::black_box((1, s));
}
```
```sh
The application panicked (crashed).
Message:  assertion failed: arguments.len() == 2
Location: compiler/noirc_evaluator/src/ssa/opt/remove_if_else.rs:371
```

### unexpected values

```noir
fn main(val: str<3>, flag: bool) {
    let b = val.as_bytes();
    let s = b.as_slice();
    let (_, s1) = s.pop_front();
    let a = std::hint::black_box(|| {
        s1
    });
    let a = if flag {
        a()
    } else {
        &[123]
    };
    println(a);
}
```

```sh
The application panicked (crashed).
Message:  internal error: entered unreachable code: ICE: No size for slice v14 = Instruction { instruction: Id(2), position: 1, typ: Slice([Numeric(Unsigned { bit_size: 8 })]) }
Location: compiler/noirc_evaluator/src/ssa/opt/remove_if_else.rs:288
```

## Recommendation

It probably doesn't make sense for zero-typed elements to do anything, so you might allow DIE to completely remove them if no arguments are passed to `black_box`, as they wouldn't have side effects.

The process that we would need could be along those line:
- std::hint::black_box can have any number of arguments (potentially > 0 after DIE).
- For each argument, take its index. If it's a slice, assert that is it part of the `slices_size`. Match the `argument[i]` with the `results[i]`, and return a `SizeChange::SetTo` for each. Make sure that for each slice `arguments[i - 1]` and `results[i - 1]` are of `Type::Numeric(_)`.
But we need a reliable to recursively check everything that is passed to the function. For instance, additionally to tuples, we could also pass a "block" that prevents it to be read by the naive `self.slice_sizes.contains_key(&old)`

### PR DESCRIPTION
**Pull request by aakoshh**
# Description

## Problem

Resolves https://github.com/noir-lang/noir/issues/11134
Resolves #10975 

Follow up for the discussion at https://github.com/noir-lang/noir/pull/11221#discussion_r2697994613

## Summary

Changes the `defunctionalize` pass to filter the variants so that when we go from an ACIR caller to a Brillig callee, we avoid dispatching to lambdas that would violate cross-boundary restrictions by taking references, or returning references/vectors. 

## Additional Context

The issue in the ticket was the creation of a lambda that returns a type which would not be a valid value going from Brillig to ACIR, and wrapping it in `black_box`:
```noir
let a = std::hint::black_box(|| @[1, 2, 3]);
```
This creates a pair of (constrained, unconstrained) lambdas, which we can use the following way:
* call the constrained variant from ACIR
* pass them to an unconstrained function and call the unconstrained variant there

We only did the first, yet because `black_box` disabled inlining and simplification, the potential call to Brillig could never be eliminated, resulting in either a panic, or with the changes in #11221 the return of a vector during constant folding (see https://github.com/noir-lang/noir/pull/11221#discussion_r2697994613). 

With this PR, the dispatch from ACIR only goes to the ACIR lambda, because the other call would be invalid anyway. 

Originally I thought that we would only ever dispatch from ACIR to ACIR, but this is not true if we have code such as this:
```noir
fn main () {
  let a: unconstrained fn() -> Field = foo;
  let b = unsafe { a() };
}
unconstrained fn foo() -> Field { 1 }
```
Here the compiler knows not to create a constrained lambda, and will create an (unconstrained, unconstrained) pair, so the dispatcher has no non-Brillig option. 

The reason I do not expect this to clash with the changes in this PR (which would result in no candidates to call) is because if we tried to return an invalid type in such a way, then the frontend would already reject this either in the elaborator or the monomorphizer, so, for example the following does not compile:
```noir
fn main () {
  let a: unconstrained fn() -> &mut Field = foo;
  let b = unsafe { *a() };
}
unconstrained fn foo() -> &mut Field { &mut 1 }
```
We can create `a`, but we cannot call it. We can pass it to another unconstrained function as a value though.

Note that this is not a complete alternative to https://github.com/noir-lang/noir/pull/11221 the discussion in https://github.com/noir-lang/noir/pull/11221#discussion_r2697907617 is still relevant. In particular this PR does nothing to make the following code avoid the panic in `remove_if_else`:
```noir
fn main(c: bool) -> pub Field {
    let a = std::hint::black_box(@[1, 2, 3]);
    let v = if c { a } else { @[4, 5] };
    v[0]
}
```
I'm only proposing this as an alternative fix for https://github.com/noir-lang/noir/issues/11134 , not https://github.com/noir-lang/noir/issues/10975 , which #11221 is also trying to (partially) address. The fix for this is in https://github.com/noir-lang/noir/pull/11273

## User Documentation

Check one:
- [x] No user documentation needed.
- [ ] Changes in _docs/_ included in this PR.
- [ ] **[For Experimental Features]** Changes in _docs/_ to be submitted in a separate PR.

# PR Checklist

- [x] I have tested the changes locally.
- [ ] I have formatted the changes with [Prettier](https://prettier.io/) and/or `cargo fmt` on default settings.

### CODE REVIEW

**Comment by guipublic** [comment]
This solution is elegant and it works surprisingly well. However, the reason it works so well is because it is cheating!

In fact, by removing variants from the lambdas, we end up with only the constrained variant, so the defunctionalisation pass replace any calls to the lambda by this variant. The hint::blackbox() is completely ignored. So the defunctionalisation ruins the hint::blackbox() semantic...

Frankly I am not sure what is the expected behaviour of hint::blackbox on function or pointer arguments. We should probably disallow them in the function.

**Comment by aakoshh** [comment]
Thanks for looking @guipublic It's funny that we both saw these fixes as cheating from various perspectives 🤣 

Let's have a look; say we started with this Noir code (a smaller part of the integration test):
```rust
fn main(c: bool) -> pub Field {
    let f = std::hint::black_box(|| @[1, 2, 3]);
    let v = if c { f() } else { @[4, 5] };
    v[0]
}
```

If we look at the monomorphized form and initial SSA, it is clear that the program knows that it will never call the unconstrained lambda from the constrained `main`.

```noir
fn main$f0(c$l0: bool) -> pub Field {
    let f$l1 = black_box$black_box((lambda$f1, lambda$f2));
    let v$l2 = if c$l0 {
        f$l1.0() // we access the .0 element for calling
    } else {
        @[4, 5]
    };
    v$l2[0]
}
fn lambda$f1() -> [Field] {
    @[1, 2, 3]
}
unconstrained fn lambda$f2() -> [Field] {
    @[1, 2, 3]
}
```

```rust
After Initial SSA:
acir(inline) fn main f0 {
  b0(v0: u1):
    v6, v7 = call black_box(f1, f2) -> (function, function)
    jmpif v0 then: b1, else: b2
  b1():
    v12, v13 = call v6() -> (u32, [Field]) // we call v6 explicitly, which is the left side
    jmp b3(v12, v13)
  b2():
    v10 = make_array [Field 4, Field 5] : [Field]
    jmp b3(u32 2, v10)
  b3(v1: u32, v2: [Field]):
    v15 = eq v1, u32 0
    v16 = not v15
    constrain v15 == u1 0, "Index out of bounds"
    v18 = array_get v2, index u32 0 -> Field
    return v18
}
```

So, even though we call `call black_box(f1, f2)`, we know that the return type is `(constrained, unconstrained)`, and it's not supposed to swap them around, so by calling the left hand side, we _won't_ be calling `f2`. 

Your earlier comment in the other PR was right that we _can_ pass `v7` to another function, and if that function is unconstrained it can even call it, but we won't be calling it form an `acir` function. I added a test to cover this. 

My other test showed that even the left hand side can be unconstrained, but only if we declared it as such, in which case we can also be sure that it won't be illegal to call it, because that would have been rejected by the frontend. 

> The hint::blackbox() is completely ignored.

I don't think that's completely true: the program knows that the only thing it _can_ dispatch to is the list of existing lambdas, it will use the left value returned by the `black_box` call, but it will constrain them to the legal variants. 

For example if I change the program to be this:
```noir
fn main(c: bool) -> pub Field {
    let f = std::hint::black_box(|| @[1, 2, 3]);
    let g = std::hint::black_box(|| @[4, 5]);
    let v = if c { f() } else { g() };
    v[0]
}
```
Then we can look at the dispatch function it creates, you can see that the values returns by the `black_box` are used for dispatching:
```rust
After Defunctionalization (1) (step 3):
acir(inline) fn main f0 {
  b0(v0: u1):
    v6, v7 = call black_box(Field 1, Field 2) -> (Field, Field)
    v10, v11 = call black_box(Field 3, Field 4) -> (Field, Field)
    jmpif v0 then: b1, else: b2
  b1():
    v15, v16 = call f5(v6) -> (u32, [Field]) // Dispatch using the left value returned by the 1st black_box
    jmp b3(v15, v16)
  b2():
    v13, v14 = call f5(v10) -> (u32, [Field]) // Dispatch using the left value returned by the 2nd black_box
    jmp b3(v13, v14)
  b3(v1: u32, v2: [Field]):
    v18 = eq v1, u32 0
    v19 = not v18
    constrain v18 == u1 0, "Index out of bounds"
    v21 = array_get v2, index u32 0 -> Field
    return v21
}
acir(inline) fn lambda f1 {
  b0():
    v3 = make_array [Field 1, Field 2, Field 3] : [Field]
    return u32 3, v3
}
brillig(inline) fn lambda f2 {
  b0():
    v3 = make_array [Field 1, Field 2, Field 3] : [Field]
    return u32 3, v3
}
acir(inline) fn lambda f3 {
  b0():
    v2 = make_array [Field 4, Field 5] : [Field]
    return u32 2, v2
}
brillig(inline) fn lambda f4 {
  b0():
    v2 = make_array [Field 4, Field 5] : [Field]
    return u32 2, v2
}
acir(inline_always) fn apply f5 {
  b0(v0: Field):
    v4 = eq v0, Field 1
    jmpif v4 then: b2, else: b1
  b1():
    constrain v0 == Field 3
    v10, v11 = call f3() -> (u32, [Field])  // Dispatch to the one which returns [4, 5]
    jmp b3(v10, v11)
  b2():
    v6, v7 = call f1() -> (u32, [Field])    // Dispatch to the one which returns [1, 2, 3]
    jmp b3(v6, v7)
  b3(v1: u32, v2: [Field]):
    return v1, v2
}
```

So, I don't think it is bypassed at all, we just recognise that some dispatches would never happen, and thus we allow the "Remove unreachable functions" to get rid of the `brillig` variants, or at least not include them in `IfElse` later.

**Comment by aakoshh** [comment]
> Frankly I am not sure what is the expected behaviour of hint::blackbox on function or pointer arguments. We should probably disallow them in the function.

I think it's okay for it to accept any input. 

For example we agreed in https://github.com/noir-lang/noir/pull/10178 that it was okay for oracle functions to return function pointers, because all they can really do is return a pointer to an existing function in the program. From the code it looks like they are returning a function, but it's just a pointer, and if it's just a pointer, then we know it must be one of the existing ones, because they cannot create functions, and if it's one of the existing ones, then we can assume it's one of the existing _valid_ targets.

**Comment by aakoshh** [comment]
Actually one of the tests provide an example why this fix is needed even without the `black_box`:

```noir
fn main(c: bool) -> pub Field {
    let f = || @[1, 2];
    let g = || @[3, 4];
    let h = if c { f } else { g };
    let x = h();
    x[0]
}
```

Without the changes in this PR, we still end up with an SSA like this:
```
After Inlining (2) (step 24):
acir(inline) predicate_pure fn main f0 {
  b0(v0: u1):
    ...
    enable_side_effects v14
    v16, v17 = call f1() -> (u32, [Field])
    ...
    v45 = if v14 then v17 else (if v19) v39
    ...
}
brillig(inline) predicate_pure fn lambda f1 {
  b0():
    v2 = make_array [Field 1, Field 2] : [Field]
    return u32 2, v2
}
brillig(inline) predicate_pure fn lambda f2 {
  b0():
    v2 = make_array [Field 3, Field 4] : [Field]
    return u32 2, v2
}
```

File: compiler/noirc_evaluator/src/ssa/opt/defunctionalize.rs [hunk 1]
```diff
@@ -528,6 +539,15 @@ fn function_id_to_field(function_id: FunctionId) -> FieldElement {
     u128::from(function_id.to_u32()).into()
 }
 
+/// Check if a [Signature] is valid when the caller is ACIR and the callee is Brillig.
+fn is_valid_across_boundaries(signature: &Signature) -> bool {
+    !signature.params.iter().any(|typ| typ.contains_reference())
+        && !signature
+            .returns
+            .iter()
+            .any(|typ| typ.contains_reference() || typ.contains_vector_element())
```
Comment (vezenovm) [inline compiler/noirc_evaluator/src/ssa/opt/defunctionalize.rs]:
```suggestion
            .any(|typ| typ.contains_reference() || typ.contains_vector_element() || typ.contains_function())
```

Comment (vezenovm) [reply compiler/noirc_evaluator/src/ssa/opt/defunctionalize.rs]: We should really start to collect these rules into a shared ruleset (later work). This can then be shared across modules (e.g., here and SSA validation).

File: compiler/noirc_evaluator/src/ssa/opt/defunctionalize.rs [hunk 2]
```diff
@@ -306,10 +306,10 @@ fn map_function_to_field(func: &mut Function, value: ValueId) -> Option<ValueId>
     None
 }
 
-/// Collects all functions used as values that can be called by their signatures
+/// Collects all functions used as values that can be called by their signatures.
 ///
-/// Groups all [FunctionId]s used as values by their [Signature] and [RuntimeType],
-/// producing a mapping from these tuples to the list of variant functions to be dynamically dispatched.
+/// Groups all [FunctionId]s used as values by their [Signature] and caller [RuntimeType],
+/// producing a mapping from these tuples to the list of target functions to be dynamically dispatched to.
```
Comment (vezenovm) [inline compiler/noirc_evaluator/src/ssa/opt/defunctionalize.rs]:
```suggestion
/// Groups all [FunctionId]s used as values by their [Signature] and caller [RuntimeType],
/// producing a mapping from these tuples to the list of target functions that may be dynamically dispatched.
```
nit: the double "to" is a bit clunky, I would rather reword this if the previous version was confusing.

File: compiler/noirc_evaluator/src/ssa/opt/defunctionalize.rs (hunk 1 above)
Comment (aakoshh) [reply compiler/noirc_evaluator/src/ssa/opt/defunctionalize.rs]: Thanks! I agree, it's hard to keep these rules in my head. I verified this does not compile:
```noir
fn main() -> pub Field {
    let f: unconstrained fn() -> (unconstrained fn() -> Field) = foo;
    let x = unsafe {
        let g = f();
        g()
    };
    x
}
unconstrained fn foo() -> (unconstrained fn() -> Field) {
    || 1
}
```
And now I remember I even argued that we should not allow this, because there is no reasonable way to constrain a function value.
