### PR TITLE
fix: don't resolve to trait method if a direct method exists

### LINKED ISSUE #12393: Infinite loop when trait method attempts to call impl method with colliding name
```noir
unconstrained fn main() {
    <MyStruct as MyTrait>::foo();
}

pub struct MyStruct {}
impl MyStruct {
    pub fn foo() {
        println("in impl method")
    }
}

pub trait MyTrait {
    fn foo();
}

impl MyTrait for MyStruct {
    fn foo() {
        println("in trait impl method");
        MyStruct::foo();
    }
}

```

Prior to https://github.com/noir-lang/noir/pull/12381 this would emit the following output and then terminate

```
in trait impl method
in impl method
```

however since then this now triggers an infinite loop with the trait method repeatedly calling itself until we hit stack too deep.

### PR DESCRIPTION
**Pull request by asterite**
## Problem Resolved

Resolves #12393

## Summary of Changes

Before #12381, `resolve_type_trait_method` used to lookup `Type::method` where `method` resolved to some trait method that `Type` implemented. However, it first checked if a direct method exists and, if so, early returned from that method as the direct method should have precedence (and that is resolved outside of `resolve_type_trait_method`). Then #12381 changed that to return the direct method, but only if the type had turbofish specified on it (in that case we need to find the precise impl that corresponds to those turbofish). But by doing that it removed the check that if there's no turbofish specified, but there's a direct method, then it should early return. This PR brings back that early return.

Note: I'm thinking that here we end up doing a direct method lookup and discarding the result in some cases, only to later do that lookup again (though in a different way). It would be nice to have to do less lookups here, but looking at the code, and especially `resolve_trait_generic_path`, it seems we were already doing many small lookups depending on what the path looks like, so this would be a larger refactor that should be done separately.

## User Documentation

Check one:
- [x] No user documentation needed.
- [ ] Documented in _docs/_.
- [ ] **[For Experimental Features]** Documentation tracking issue created: 

## PR Checklist

- [x] I have tested the changes locally.
- [x] I have formatted the changes with [Prettier](https://prettier.io/) and/or `cargo fmt` on default settings.

### CODE REVIEW

File: compiler/noirc_frontend/src/elaborator/types.rs [hunk 1]
```diff
@@ -1615,6 +1615,10 @@ impl Elaborator<'_> {
             }
 
             trait_methods = Some(type_trait_methods);
+        } else if direct_method.is_some() {
+            // If there's no turbofish, but there's a direct method, let the lookup continue reguarly
```
Comment (TomAFrench) [inline compiler/noirc_frontend/src/elaborator/types.rs]:
```suggestion
            // If there's no turbofish, but there's a direct method, let the lookup continue regularly
```

**Review by TomAFrench — COMMENTED** [review]
The comment calls out that this is only for the "no turbofish" case so I'd like to add another test for the situation where we're calling a generic method. I've got claudebox working on https://github.com/noir-lang/noir/issues/12395 to unblock this.

**Comment by asterite** [comment]
> The comment calls out that this is only for the "no turbofish" case so I'd like to add another test for the situation where we're calling a generic method

Sounds good! I'll add one. In that case I think we just need the method call inside the trait method to be generic. I guess for a real program we'd need to call the trait method, but the compiler will type-check it anyway. In any case it would be nice to have #12395, I tried it in the past (without Claude) and it was a bit tricky, maybe Claude will do it faster.

**Review by TomAFrench — APPROVED** [review]
