### PR TITLE
fix(opt): Collect all nested arrays beforehand

### LINKED ISSUE #12411: [BUG] Circuit size blowup from Aztec v3->v4 (but root cause potentially in Noir compiler)
### Expected Behavior

I flagged this issue a while back in a private communication channel. Ultimately, we worked around the issue by removing the library (json_parser) that caused it. However, I recently checked whether it still occurrs for ` 4.2.0-aztecnr-rc.2` and it does. Then I spent some time having Claude dig into the problem, to try to find out what the issue (and a potential fix) is. I will first share the issue I personally encountered and then share what Claude said the root cause is. 

## The issue
While working on zkTLS related smart contracts we noticed a blowup in gatecount when upgrading from `v3.0.0-devnet.5` to `4.0.0-devnet.2-patch.1`. (We did not change anything in the contracts apart from the necessary for breaking changes in the upgrade.) There were 3 different functions we benchmarked, of which 2 blew up:
- Verify commitments based large example ([ref](https://github.com/primus-labs/zktls-verification-noir/blob/7c61e14494293f651f672a07bc8bd76dd06aca4a/example/real_business_program/src/main.nr#L108-L149)) was 711.763 -> 3,907,426 gates
- Verify hash based example ([ref](https://github.com/primus-labs/zktls-verification-noir/blob/7c61e14494293f651f672a07bc8bd76dd06aca4a/example/real_business_program/src/main.nr#L153-L192)) was 794.646 -> 2,509,592 gates
- Smaller commitment example ([ref](https://github.com/primus-labs/zktls-verification-noir/blob/7c61e14494293f651f672a07bc8bd76dd06aca4a/example/small_comm_business_program/src/main.nr#L84-L125)) was 321.513 -> 396,142 gates

Then, from analyzing the flamegraphs it showed that the issue originated from the json_parser library, specifically a function called `create_json_entries`(code [ref](https://github.com/hashcloak/noir_json_parser/blob/primus_noir/src/json.nr#L263-L530)). Specifically, the opcode `acir::memory::op` now had a huge cost, which previously was not even clearly visible in the flamegraph (e.g the first occurance acir::memory::op v4 costs ~780k gates, was 2k gates in v3). 

To me this seems like a bug, a sudden blowup in gatecount without any changes on our side. 

## Claude analysis

I will share what according to Claude is the problem and a minimal reproduction. However, because I don't have the full understanding of how this part works or code rationale of what is in place, I am not sure this is correct, but I hope it is helpful. 

### Minimal reproducer

```noir
fn fill_local<let N: u32>(enable: [bool; N]) -> ([Field; N], [Field; N]) {
    let mut data_a: [Field; N] = [0; N];
    let mut data_b: [Field; N] = [0; N];
    let mut ptr: u32 = 0;
    for i in 0..N {
        data_a[ptr] = i as Field;
        data_b[ptr] = i as Field;
        ptr += enable[i] as u32;
    }
    (data_a, data_b)
}

fn main(enable: [bool; 256]) -> pub ([Field; 256], [Field; 256]) {
    fill_local(enable)
}
```

Trigger pattern: compile-time loop bound, runtime index, two or more arrays written in the loop body, all returned together. The `create_json_entries` method hits this exactly: `MaxNumTokens` is the bound, `entry_ptr` and `depth` are the runtime indices, and `self.json_entries_packed` and `self.key_data` are struct fields returned together.

### Scaling (`nargo info`)

| N   | Gates  | Ratio vs previous N |
|-----|--------|---------------------|
| 32  | 1,246  | -                   |
| 64  | 4,542  | 3.6x                |
| 128 | 17,278 | 3.8x                |
| 256 | 67,326 | 3.9x                |

Converging on 4x per doubling, consistent with O(N^2). The single-array version of this pattern scales linearly, which pointed at the two-array return as the trigger.

### Trace

The point where the two-chain case diverges from the single-chain case is in `compiler/noirc_evaluator/src/ssa/opt/mutable_array_set.rs`, `Context::analyze_last_uses`, in the `Instruction::ArraySet` arm:

```rust
let mut is_array_in_terminator = false;
let mut is_nested = false;
terminator.for_each_value(|value| {
    let is_value_array_in_terminator = value == *array;
    if !is_value_array_in_terminator && self.dfg.type_of_value(value).is_array() {
        is_nested = true;
        self.set_last_use(value, *instruction_id);
    }
    is_array_in_terminator |= is_value_array_in_terminator;
});

let can_mutate = !is_array_in_terminator && !is_nested;
```

`is_nested` becomes `true` whenever any other array appears in the return terminator, regardless of containment relationship. With two returned arrays, each step of the `data_a` chain sees `data_b`'s final value in the terminator and vice versa, so every `array_set` in both chains ends up with `can_mutate = false`. ACIRgen then emits a full copy at each step, giving N*N memory ops.

The same logic is present in `array_set.rs` on beta.18 and beta.19 and was moved to `mutable_array_set.rs` on beta.20 and next, unchanged.

### Two possibilities

Claude can see two framings for this, and the right fix depends on which is correct:

1. The check is deliberately conservative, a stand-in for a more principled alias analysis, kept broad because a false `mutable: false` is only slower while a false `mutable: true` could be unsound. In that case this is a request to prioritize a narrower check, since the regression is multi-million-gate on real contracts.

2. The check is intended to catch genuine nesting (an array that is a direct element of another returned array, where in-place mutation would corrupt the outer one) and is accidentally over-broad. In that case it can be replaced with a direct containment check.

[The draft PR](https://github.com/noir-lang/noir/pull/12412) assumes (2) and proposes a pre-pass collecting arrays that appear as direct elements of `MakeArray` instructions, then checking `element_arrays.contains(array)` in place of `is_nested`. With that change: reproducer drops to 2,048 gates at N=256 (O(N) scaling confirmed), `verify_comm` drops from 3,897,863 to 693,719 gates, all 13 `mutable_array_set` tests pass along with all 689 `ssa::opt` tests (two snapshot updates required; invariants they were written for are preserved).

### Bug

Blowup in circuit size, as described above. 

### Workaround

_No response_

### Project Impact

Ultimately, we were able to remove the [json_parser](https://github.com/noir-lang/noir_json_parser) from the contracts completely. However, our previous contract versions show that the parser is no longer practical for larger inputs, while it was in previous versions. 

### Nargo Version

v1.0.0-beta.18 - v1.0.0-beta.20. The problem was signaled in .18, but still exists in .20. 

### NoirJS Version

_No response_

### Proving Backend

_No response_

### Would you like to submit a PR for this Issue?

Maybe

### PR DESCRIPTION
**Pull request by jfecher**
## Problem Resolved

Resolves https://github.com/noir-lang/noir/issues/12411

## Summary of Changes

Same fix as in https://github.com/noir-lang/noir/pull/12412 but cleaned up (file has moved & acvm changes are not needed)

## User Documentation

Check one:
- [x] No user documentation needed.
- [ ] Documented in _docs/_.
- [ ] **[For Experimental Features]** Documentation tracking issue created: 

## PR Checklist

- [x] I have tested the changes locally.
- [x] I have formatted the changes with [Prettier](https://prettier.io/) and/or `cargo fmt` on default settings.

### CODE REVIEW

File: compiler/noirc_evaluator/src/ssa/opt/mutable_array_set.rs [hunk 1]
```diff
@@ -156,6 +156,9 @@ impl<'f> Context<'f> {
             }
         }
 
+        // We must prevent mutating arrays after they're stored in other arrays.
+        let mut element_arrays = HashSet::default();
```
Comment (asterite) [inline compiler/noirc_evaluator/src/ssa/opt/mutable_array_set.rs:160]: I wonder if tracking these is actually needed. I just tried commenting this line, then also commenting every line that uses this (and doing `let is_nested = false;`) and all tests still pass.

Here's my thinking: the previous code checked if a terminator had **any** array in it, and blocked the optimization, because the array in the terminator could contain the array in the `array_set` instruction. However, for that to happen the array must have been put inside another array via `make_array`... or maybe via another `array_set`? But I think in that case we already track the last use there.

Not sure, though! But given that `element_arrays` seems to be unused, there's something strange here...

Comment (jfecher) [reply compiler/noirc_evaluator/src/ssa/opt/mutable_array_set.rs:160]: Investigated this some more - its just that the existing tests are optimized differently because they're also last uses. I added a new test for the nested check and verified it doesn't pass without this change.

Comment (asterite) [reply compiler/noirc_evaluator/src/ssa/opt/mutable_array_set.rs:160]: I see now. Thanks, that makes sense!

**Review by asterite — APPROVED** [review]
