### PR TITLE
fix: emit error on oracle functions with function bodies

### LINKED ISSUE #10131: Oracle functions can include bodies that are silently ignored
## Description
Oracle functions are declaration-only by design. However, the compiler currently accepts a function body on such declarations and then silently ignores it. This behavior misleads developers - code written inside the body will never execute - and can mask missing constraints or create false confidence in tests.

## Proof of Concept
```noir
#[oracle(fn1)]
unconstrained fn fn1() {
    // These instructions are accepted syntactically,
    // but the body is ignored at compile time / execution.
    println("this never runs");
    // ...any asserts or logic here are ineffective
}
```

Root Cause:
1. Frontend gap: No diagnostic rejects bodies on oracle/foreign functions.
2. SSA contract not formalized: There is no explicit invariant that an external/oracle function must have no basic blocks/instructions.

## Recommendation
1.	Frontend (primary fix):
	-	Emit a hard error if a `#[oracle]` (or otherwise external/foreign) function includes a body.
2.	SSA invariants & verifier (defense-in-depth)
	-	Define and enforce: If a function is external, it must contain no basic blocks/instructions.

### PR DESCRIPTION
**Pull request by TomAFrench**
# Description

## Problem\*

Resolves #10131

## Summary\*

I've added a quick check where we skip elaboration of a presumed empty function body to ensure that it doesn't include any statements.

## Documentation\*

Check one:
- [x] No documentation needed.
- [ ] Documentation included in this PR.
- [ ] **[For Experimental Features]** Documentation to be submitted in a separate PR.

# PR Checklist\*

- [x] I have tested the changes locally.
- [x] I have formatted the changes with [Prettier](https://prettier.io/) and/or `cargo fmt` on default settings.

### CODE REVIEW

File: compiler/noirc_frontend/src/hir/resolution/errors.rs [hunk 1]
```diff
@@ -808,6 +811,13 @@ impl<'a> From<&'a ResolverError> for Diagnostic {
                     *location,
                 )
             }
+            ResolverError::OracleWithBody { location } => {
+                Diagnostic::simple_error(
+                    "Functions marked with #[builtin] or #[oracle] must have no body".to_string(),
```
Comment (aakoshh) [inline compiler/noirc_frontend/src/hir/resolution/errors.rs]: I also see `#[foreign]`, e.g. in `aes128.nr`.

Comment (TomAFrench) [inline compiler/noirc_frontend/src/hir/resolution/errors.rs]:
```suggestion
                    "Functions marked with #[oracle] must have no body".to_string(),
```

Comment (TomAFrench) [reply compiler/noirc_frontend/src/hir/resolution/errors.rs]: It's impossible for this attributes to be used outside of the stdlib so I'm inlined to keep the error message focused on the situations which users could potentially run into.

**Comment by TomAFrench** [comment]
Huh, I'm having the debugger tests all passing locally so not sure why this is failing in CI.

**Comment by asterite** [comment]
For some reason if you run `cargo test tests::debug_test_mock_oracle_test_multiple_mock_times --package noir_debugger` from the root, it fails... but I still don't know why that would make a difference.

Another thing I noticed is that the new code is put for built-in, low-level, etc., so I thought maybe it's erroring in those cases but no...

**Comment by asterite** [comment]
Ah, no... I think the debugger tests use a compiled `nargo` so after building it running the tests will fail.

**Comment by TomAFrench** [comment]
> the debugger tests use a compiled `nargo`

`assert_cmd::cargo_bin` should use the binary which is compiled from the same source as the test code though.

https://docs.rs/assert_cmd/latest/assert_cmd/cargo/index.html
