### PR TITLE
fix: error if pattern name is bound more than once

### LINKED ISSUE #10530: Variable can be bound more than once in pattern
### Aim

This code:

```noir
fn main() {
    let (x, (x, y)) = (1, (2, 3));
    println(x);
    println(y);
}
```

should error saying that the second `x` is already bound. However, it compiles fine.

A similar Rust code gives an error:

```
error[E0416]: identifier `x` is bound more than once in the same pattern
 --> foo/src/main.rs:2:14
  |
2 |     let (x, (x, y)) = (1, (2, 3));
  |              ^ used in a pattern more than once
```

This isn't unique to tuple patterns. The following code should also error but doesn't:

```noir
struct Foo {
    x: i32,
}

fn main() {
    let (x, Foo { x }) = (1, Foo { x: 1 });
    println(x);
    println(y);
}
```

Finally, it seems this also happens in this code:

```noir
fn main() {
    let (x, x) = (1, 2); // No error
}
```

Oh, and it seems in lambda parameters this is also true. This doesn't error:

```noir
fn main() {
    let _ = |x, x| {};
}
```

### Expected Behavior

The compiler should detect duplicate names in patterns.

### Bug

The compiler doesn't error.

### To Reproduce

1.
2.
3.
4.

### Workaround

None

### Workaround Description

_No response_

### Additional Context

_No response_

### Project Impact

None

### Blocker Context

_No response_

### Nargo Version

_No response_

### NoirJS Version

_No response_

### Proving Backend Tooling & Version

_No response_

### Would you like to submit a PR for this Issue?

None

### Support Needs

_No response_

### PR DESCRIPTION
**Pull request by asterite**
# Description

## Problem

Resolves #10530

## Summary

This required more changes than what I initially thought.

The reason is that lambda parameters are allowed to shadow local variables:

```noir
let x = 1;
let _ = |x| x; // Ok
```

However, we must error if the same name appears twice in the parameter list:

```noir
let x = 1;
let _ x |x, x| x; // Not Ok
```

For that we need to keep track of parameter names across the list.

Separately, we must check if the same name appears twice in the same pattern (nor across multiple patterns).

The two cases produce slightly different error messages.

## Additional Context

This uncovered a bug in the debugger transformation code where duplicate patterns for struct patterns where produced. It's fixed in this PR too.

## User Documentation

Check one:
- [x] No user documentation needed.
- [ ] Changes in _docs/_ included in this PR.
- [ ] **[For Experimental Features]** Changes in _docs/_ to be submitted in a separate PR.

# PR Checklist

- [x] I have tested the changes locally.
- [x] I have formatted the changes with [Prettier](https://prettier.io/) and/or `cargo fmt` on default settings.

### CODE REVIEW

File: compiler/noirc_frontend/src/elaborator/patterns.rs [hunk 1]
```diff
@@ -28,12 +29,16 @@ impl Elaborator<'_> {
     ///
     /// The `expected_type` is always known, because we can first infer the type of the `<expr>` and try to match it to
     /// the pattern.
+    ///
+    /// `parameter_names_in_list` keeps track of parameter names, and their location, accross multiple
```
Comment (TomAFrench) [inline compiler/noirc_frontend/src/elaborator/patterns.rs]:
```suggestion
    /// `parameter_names_in_list` keeps track of parameter names, and their location, across multiple
```

File: compiler/noirc_frontend/src/elaborator/patterns.rs [hunk 2]
```diff
@@ -42,18 +47,24 @@ impl Elaborator<'_> {
...
             warn_if_unused,
+            &mut HashSet::default(),
+            parameter_names_in_list,
         )
     }
 
     /// Equivalent to `elaborate_pattern`, this version just also
     /// adds any new `DefinitionIds` that were created to the given `Vec`.
+    ///
+    /// `parameter_names_in_list` keeps track of parameter names, and their location, accross multiple
```
Comment (TomAFrench) [inline compiler/noirc_frontend/src/elaborator/patterns.rs]:
```suggestion
    /// `parameter_names_in_list` keeps track of parameter names, and their location, across multiple
```

File: compiler/noirc_frontend/src/elaborator/patterns.rs [hunk 3]
```diff
@@ -62,11 +73,19 @@ impl Elaborator<'_> {
...
+            parameter_names_in_list,
         )
     }
 
     /// Elaborate the (potentially mutable) pattern and add the variables
     /// it created to the scope if necessary.
+    ///
+    /// - `pattern_names` keeps track of parameter names within this single pattern (or an outer
+    ///    one, when called recursively). If a name is found multiple times, an error is captured.
+    /// - `parameter_names_in_list` keeps track of parameter names, and their location, accross multiple
```
Comment (TomAFrench) [inline compiler/noirc_frontend/src/elaborator/patterns.rs]:
```suggestion
    /// - `parameter_names_in_list` keeps track of parameter names, and their location, across multiple
```

**Review by TomAFrench — APPROVED** [review]
