### PR TITLE
fix(ssa): Use accurate type during SSA AsSlice simplficiation

### LINKED ISSUE #4609: Cannot append slices
### Aim

My goal is to append one slice to another

### Expected Behavior

I expected it to return a new slice with both slices concatenated

### Bug

I get an error in the form of:
`ICE: should have slice capacity set at address v45 being loaded into v112`

### To Reproduce

1. Use this snippet:
  ```rust
  fn main(a: Field, b: pub Field) {
      let sl = [a, 1, 2, 3].as_slice();
      let sl2 = [b, 5, 6].as_slice();
      let sl3 = sl.append(sl2);
  }
  ```
2. Run nargo test with something such as:

```rust
#[test]
fn test_main() {
    main(0, 4);
}
```

### Project Impact

None

### Impact Context

_No response_

### Workaround

None

### Workaround Description

_No response_

### Additional Context

_No response_

### Installation Method

Binary (`noirup` default)

### Nargo Version

nargo version = 0.25.0 noirc version = 0.25.0+cba1bff95911a7a1d3ea714735786db595a435cf (git version hash: cba1bff95911a7a1d3ea714735786db595a435cf, is dirty: false)

### NoirJS Version

_No response_

### Would you like to submit a PR for this Issue?

None

### Support Needs

_No response_

### PR DESCRIPTION
**Pull request by vezenovm**
# Description

## Problem\*

Resolves #4609 

## Summary\*

We were not accurately converting the type from an array to a slice during `AsSlice` SSA simplification. This led to the slice capacity tracker not accurately tracking the slice size. 

## Documentation\*

Check one:
- [ ] No documentation needed.
- [ ] Documentation included in this PR.
- [ ] **[Exceptional Case]** Documentation to be submitted in a separate PR.

# PR Checklist\*

- [ ] I have tested the changes locally.
- [ ] I have formatted the changes with [Prettier](https://prettier.io/) and/or `cargo fmt` on default settings.

### CODE REVIEW

File: compiler/noirc_evaluator/src/ssa/ir/instruction/call.rs [hunk 1]
```diff
@@ -85,10 +85,11 @@ pub(super) fn simplify_call(
...
         Intrinsic::AsSlice => {
-            let slice = dfg.get_array_constant(arguments[0]);
-            if let Some((slice, element_type)) = slice {
-                let slice_length = dfg.make_constant(slice.len().into(), Type::length_type());
-                let new_slice = dfg.make_array(slice, element_type);
+            let array = dfg.get_array_constant(arguments[0]);
+            if let Some((array, element_type)) = array {
+                let slice_length = dfg.make_constant(array.len().into(), Type::length_type());
+                let inner_element_types = element_type.element_types();
+                let new_slice = dfg.make_array(array, Type::Slice(inner_element_types));
```
Comment (jfecher) [inline compiler/noirc_evaluator/src/ssa/ir/instruction/call.rs:92]: Looks like `element_type` should actually be `array_type`?

Comment (vezenovm) [reply compiler/noirc_evaluator/src/ssa/ir/instruction/call.rs]: Yeah good call I renamed it

**Review by jfecher — APPROVED** [review]
:+1:
