### PR TITLE
fix(ssa): Try not to hoist into loop headers during constant folding

### LINKED ISSUE #11599: ICE: loop unroller panics on MakeArray in header from for-loop with non-constant inclusive range bound
## Aim

Compile and execute a program where an unconstrained function has a `for ..=` loop whose upper bound is a non-constant expression (specifically involving `%` and an `if` expression), with `println` in the loop body.

## Expected Behavior

The program should compile and execute successfully.

## Bug

The compiler panics in the loop unroller:

```
thread panicked at compiler/noirc_evaluator/src/ssa/opt/unrolling.rs:582:22:
Unexpected instruction in header: MakeArray { elements: [...], typ: Array([Numeric(Unsigned { bit_size: 8 })], SemanticLength(38)) }
```

A `MakeArray` instruction (from the `println` format string) ends up in the loop header block, which the unroller doesn't expect.

## Minimum Reproduction

```noir
fn main() {
    // Safety: fuzzer repro
    unsafe {
        func(true)
    };
}
unconstrained fn func(b: bool) {
    for i in 0_u8 ..= (1_u8 % if b { 1_u8 } else { 1_u8 }) {
        println(i);
    };
}
```

### Key ingredients

- Constrained `main` calling an unconstrained function
- `for ..=` (inclusive range) loop in the unconstrained function
- Range upper bound uses `%` (modulo) with a non-constant expression (`if b { ... } else { ... }`)
- Loop body contains `println` (an oracle call)

Removing any of these ingredients prevents the panic.

## Additional Context

Found from the `orig_vs_morph` fuzzer failure: https://github.com/noir-lang/noir/actions/runs/22029224749/job/63651154094 (seed `0x40c7924a00100000`).

## Installation Method

Built from source (master at `230927d295`).

### PR DESCRIPTION
**Pull request by aakoshh**
# Description

## Problem

Resolves #11599

## Summary

During constant folding try to avoid hoisting instructions into loop headers, so that:
* we don't break the assumptions that `unrolling` has on the instructions that can appear in a loop header, and
* we hoist into a block that doesn't get executed in each loop iteration 

## Additional Context

This is an alternative to https://github.com/noir-lang/noir/pull/11600 , which relaxes some of the assumptions taken by `get_const_upper_bound`. In particular in that PR we still return `None` if there isn't just a single instruction in the header, but we no longer assume that we should recognise that instruction as something related to the loop. I suppose there could be a case made for allowing appending instructions to the header, and trying to recognise the first one. 

Here we are trying to avoid getting into a pickle in the first place by hoisting into the pre-header instead, which is also what the LICM does, but the constant folding looked for the first common dominator, which in some cases happened to be a loop header.

I added some conditions in which case it is still allowed to hoist into a loop header: that is if the header defined a variable which is used by the instruction we are hoisting. This the case in the unit test added recently by Tom, but also happened in fuzzing with `while` loops.

As a side note, I originally I thought I would treat as "unsullied header" something where `get_const_bounds` returns `Some`, which means it clearly hasn't violated any assumptions, but that was too restrictive: in the very example in this ticket we do not have what the program considers a constant bound, since it depends on a formula (with public inputs flowing into it). 

## User Documentation

Check one:
- [x] No user documentation needed.
- [ ] Changes in _docs/_ included in this PR.
- [ ] **[For Experimental Features]** Changes in _docs/_ to be submitted in a separate PR.

# PR Checklist

- [x] I have tested the changes locally.
- [ ] I have formatted the changes with [Prettier](https://prettier.io/) and/or `cargo fmt` on default settings.

### CODE REVIEW

**Comment by TomAFrench** [comment]
> This is an alternative to https://github.com/noir-lang/noir/pull/11600 which relaxes some of the assumptions taken by get_const_upper_bound.

I'm in favour of going this route, on second thoughts. We get to benefit from the hoisted instructions not being run on each iteration.

File: compiler/noirc_evaluator/src/ssa/ir/dom.rs [hunk 1]
```diff
@@ -162,6 +162,7 @@ impl DominatorTree {
     /// This approach computes the control flow graph and post-order internally and then
     /// discards them. If either should be retained reuse it is better to instead pre-compute them
     /// and build the dominator tree with `DominatorTree::with_cfg_and_post_order`.
+    #[allow(dead_code)]
```
Comment (TomAFrench) [inline compiler/noirc_evaluator/src/ssa/ir/dom.rs]:
```suggestion
    #[expect(dead_code)]
```

File: compiler/noirc_evaluator/src/ssa/ir/dom.rs [hunk 2]
```diff
@@ -162,6 +162,7 @@ impl DominatorTree {
     /// This approach computes the control flow graph and post-order internally and then
     /// discards them. If either should be retained reuse it is better to instead pre-compute them
     /// and build the dominator tree with `DominatorTree::with_cfg_and_post_order`.
+    #[expect(dead_code)]
```
Comment (TomAFrench) [inline compiler/noirc_evaluator/src/ssa/ir/dom.rs]:
```suggestion
```
