### PR TITLE
fix: check infix expression is valid in program input

### LINKED ISSUE #6438: Can't pass concrete struct to `main`
Please see this PR which exemplifies the issue https://github.com/zkpassport/noir_rsa/pull/2. See the section "A note to the Noir team".

Edit: here's a dedicated repo focusing on the problem: https://github.com/iAmMichaelConnor/example_sized_types_entrypoint_bug

I'll see if I can come up with a more minimal example.

### PR DESCRIPTION
**Pull request by asterite**
# Description

## Problem

Resolves #6438

## Additional Context

This doesn't fix the panic that's mentioned [here](https://github.com/zkpassport/noir_rsa/pull/2) though, I'll see if I can find out why that happens.

## Documentation

Check one:
- [x] No documentation needed.
- [ ] Documentation included in this PR.
- [ ] **[For Experimental Features]** Documentation to be submitted in a separate PR.

# PR Checklist

- [x] I have tested the changes locally.
- [x] I have formatted the changes with [Prettier](https://prettier.io/) and/or `cargo fmt` on default settings.

### CODE REVIEW

File: compiler/noirc_frontend/src/tests.rs [hunk 1]
```diff
@@ -3623,3 +3623,15 @@ fn use_type_alias_to_generic_concrete_type_in_method_call() {
...
 }
+
+#[test]
+fn allows_struct_with_generic_infix_type_as_main_input() {
+    let src = r#"
+        struct Foo<let N: u32> {
+            x: [u64; N * 2],
+        }
+
+        fn main(_x: Foo<18>) {}
```
Comment (michaeljklein) [inline compiler/noirc_frontend/src/tests.rs:3634]: Does this work with cases e.g. `fn main(_x: Foo<2 * 9>)` as well?

**Review by michaeljklein — CHANGES_REQUESTED** [review]
Possible extra test, otherwise LGTM

File: compiler/noirc_frontend/src/tests.rs (hunk 1 above)
Comment (jfecher) [reply compiler/noirc_frontend/src/tests.rs:3634]: Or `(_x: Foo<N * 2>)` where `N` is a constant global?

Comment (asterite) [reply compiler/noirc_frontend/src/tests.rs:3634]: It seems both work. Should I add tests for those too?

Comment (TomAFrench) [reply compiler/noirc_frontend/src/tests.rs:3634]: Yeah, more tests never hurts.

Comment (asterite) [reply compiler/noirc_frontend/src/tests.rs:3634]: Done!

**Review by michaeljklein — APPROVED** [review]
LGTM
