### PR TITLE
fix: use value predicated by range checks

### LINKED ISSUE #8617: ACIR != Brillig: ACIR fails where Brillig returns a value
### Aim

Discovered testing https://github.com/noir-lang/noir/pull/8610

This is the minimised version of the program in https://github.com/noir-lang/noir/issues/8616

The following program fails with an overflow in ACIR but passes and returns a value in Brillig:
```rust
fn main(a: i32, c: bool) -> pub i32 {
    if c {
        a
    } else {
        ((-a) * a)
    }
}
```
Inputs:
```toml
a = "-0x000000000000000000000000000000000000000000000000000000002df86759"
c = true
```

### Expected Behavior

ACIR and Brillig should agree. In this case Brillig is right: if `c` is `true` then it should just return `a`. Changing `c` to `false` causes an overflow in Brillig as well. 

### Bug

```
❯ cargo run -q -p nargo_cli -- execute --force-brillig
[regression_fuzz_testing] Circuit witness successfully solved
[regression_fuzz_testing] Witness saved to target/regression_fuzz_testing.gz
[regression_fuzz_testing] Circuit output: Field(3523713191)

❯ cargo run -q -p nargo_cli -- execute 
error: Failed constraint
  ┌─ src/main.nr:5:10
  │
5 │         ((-a) * a)
  │          --------
  │
  = Call stack:
    1. src/main.nr:5:10

Failed to solve program: 'Cannot satisfy constraint'

```

### To Reproduce

See above.

### Workaround

None

### Workaround Description

_No response_

### Additional Context

_No response_

### Project Impact

None

### Blocker Context

_No response_

### Nargo Version

nargo version = 1.0.0-beta.6 noirc version = 1.0.0-beta.6+b2bfdb7bb0fc661bfb27da365f108cf131771295 (git version hash: ef1c8dc, is dirty: true)

### NoirJS Version

_No response_

### Proving Backend Tooling & Version

_No response_

### Would you like to submit a PR for this Issue?

None

### Support Needs

_No response_

### PR DESCRIPTION
**Pull request by guipublic**
# Description

## Problem\*

Resolves #8617 

## Summary\*
Instead of disabling a range check using a predicate, when a branch is not taken, we predicate the value itself. As a result the range is the same as before, but now we are ensured that this new predicated value respect the range-check.

## Documentation\*

Check one:
- [X] No documentation needed.
- [ ] Documentation included in this PR.
- [ ] **[For Experimental Features]** Documentation to be submitted in a separate PR.

# PR Checklist\*

- [X] I have tested the changes locally.
- [X] I have formatted the changes with [Prettier](https://prettier.io/) and/or `cargo fmt` on default settings.

### CODE REVIEW

**Comment by TomAFrench** [comment]
I'm concerned about how this interacts with other references to this value which aren't under the same predicate. Seems like we can inadvertently modify those as well?

**Comment by guipublic** [comment]
> I'm concerned about how this interacts with other references to this value which aren't under the same predicate. Seems like we can inadvertently modify those as well?

I tried this and indeed the predicated value is also used in the other branch for instance.

**Comment by guipublic** [comment]
I have added a unit test and also made sure the predicated values are not used outside of their branch.

File: compiler/noirc_evaluator/src/ssa/opt/flatten_cfg.rs [hunk 1]
```diff
@@ -781,8 +811,12 @@ impl<'f> Context<'f> {
                     // Condition needs to be cast to argument type in order to multiply them together.
                     let casted_condition =
                         self.cast_condition_to_value_type(condition, value, call_stack);
-                    let value = self.mul_by_condition(value, casted_condition, call_stack);
-                    Instruction::RangeCheck { value, max_bit_size, assert_message }
+                    let predicate_value =
+                        self.mul_by_condition(value, casted_condition, call_stack);
+                    // Issue #8617: update the value to be the predicated value.
+                    // This ensure the value has the correct bit size in all cases.
```
Comment (vezenovm) [inline compiler/noirc_evaluator/src/ssa/opt/flatten_cfg.rs]:
```suggestion
                    // This ensures that the value has the correct bit size in all cases.
```
nit

File: compiler/noirc_evaluator/src/ssa/opt/flatten_cfg.rs [hunk 2]
```diff
@@ -652,6 +660,28 @@ impl<'f> Context<'f> {
...
+    /// to the 'predicated_values' map if not already stored.
+    fn predicate_value(&mut self, value: ValueId, predicated_value: ValueId) {
+        let conditional_context = self.condition_stack.last_mut().unwrap();
+
+        if let std::collections::hash_map::Entry::Vacant(e) =
+            conditional_context.predicated_values.entry(value)
+        {
+            let old_mapping = self.inserter.resolve(value);
+            e.insert(old_mapping);
+        }
```
Comment (vezenovm) [inline compiler/noirc_evaluator/src/ssa/opt/flatten_cfg.rs]:
```suggestion
        conditional_context
            .predicated_values
            .entry(value)
            .or_insert_with(|| self.inserter.resolve(value));
```
We can simplify this here

File: compiler/noirc_evaluator/src/ssa/opt/flatten_cfg.rs [hunk 3]
```diff
@@ -652,6 +660,28 @@ impl<'f> Context<'f> {
...
+        self.inserter.map_value(value, predicated_value);
+    }
+
+    /// Restore the previous mapping of predicated values.
+    fn reset_predicated_values(&mut self, conditional_context: &mut ConditionalContext) {
+        for (value, old_mapping) in conditional_context.predicated_values.drain() {
+            self.inserter.map_value(value, old_mapping);
+        }
+        conditional_context.predicated_values.clear();
```
Comment (vezenovm) [inline compiler/noirc_evaluator/src/ssa/opt/flatten_cfg.rs]:
```suggestion
```
Doesn't drain remove elements as we iterate so this `clear()` is redundant?

Comment (guipublic) [reply compiler/noirc_evaluator/src/ssa/opt/flatten_cfg.rs]: Yes it should, but in that case clearing it does not hurt. However I removed it since it can be confusing. I also checked that drain removed the elements.

File: compiler/noirc_evaluator/src/ssa/opt/flatten_cfg.rs (hunk 2 above)
Comment (guipublic) [reply compiler/noirc_evaluator/src/ssa/opt/flatten_cfg.rs]: Done

File: compiler/noirc_evaluator/src/ssa/opt/flatten_cfg.rs (hunk 1 above)
Comment (guipublic) [reply compiler/noirc_evaluator/src/ssa/opt/flatten_cfg.rs]: Done

**Review by vezenovm — APPROVED** [review]
