### PR TITLE
Handle predicate operator during inlining

### LINKED ISSUE #530: binop.predicate.is_none bug
# Description

## Aim

I ran into this bug while trying to call a function deeply nested in conditionals. See the snippet for more context.

## Expected behavior

Succesful compilation / execution

## Bug

```
thread 'main' panicked at 'assertion failed: binop.predicate.is_none()', crates/noirc_evaluator/src/ssa/conditional.rs:538:21
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
```

# To reproduce

https://gist.github.com/okuyiga/0b7e751d9f9ec9da8ee31cd3fa82524f

# Environment

(Specify your setup and versions of dependencies.)

- OS: Debian running in a docker container on an M1 mac

For `nargo` users

- _noir-lang/noir_ commit cloned:
- Proving backend
  - [x] default
    - Clang: (run `clang --version`)
  - [ ] wasm-base

```
Debian clang version 11.0.1-2
Target: aarch64-unknown-linux-gnu
Thread model: posix
InstalledDir: /usr/bin
```

### PR DESCRIPTION
**Pull request by guipublic**
# Related issue(s)

Resolves #530

# Description

## Summary of changes

We handle predicate in binary instructions during inlining
I also added a small refactor of short_circuit() which was suggested in PR #437 review but was not implemented.

## Test additions / changes

Regression test case added to 9_conditional

# Checklist

- [X] I have tested the changes locally.
- [X] I have formatted the changes with [Prettier](https://prettier.io/) and/or `cargo fmt` with default settings.
- [X] I have [linked](https://docs.github.com/en/issues/tracking-your-work-with-issues/linking-a-pull-request-to-an-issue) this PR to the issue(s) that it resolves.
- [X] I have reviewed the changes on GitHub, line by line.
- [X] I have ensured all changes are covered in the description.

### CODE REVIEW

File: crates/noirc_evaluator/src/ssa/conditional.rs [hunk 1]
```diff
@@ -454,7 +459,7 @@ impl DecisionTree {
             stack.push(ins2);
             true
         } else {
-            false
+            unreachable!("{}", error_msg);
```
Comment (jfecher) [inline crates/noirc_evaluator/src/ssa/conditional.rs:462]: Since this function always returns true now, can we remove the return value and return `false` directly where it is used below?

**Review by jfecher — COMMENTED** [review]
Looks good, just two small suggestions

File: crates/noirc_evaluator/src/ssa/conditional.rs [hunk 2]
```diff
@@ -521,40 +526,60 @@ impl DecisionTree {
...
                     }
                     stack.push(ins_id);
                 }
                 Operation::Binary(binop) => {
                     stack.push(ins_id);
-                    assert!(binop.predicate.is_none());
+                    let mut cond = ass_value;
+                    if let Some(pred) = binop.predicate {
+                        assert_ne!(pred, NodeId::dummy());
+                        if ass_value != NodeId::dummy() {
```
[the remark this answers is not in the document]
Comment (guipublic) [reply crates/noirc_evaluator/src/ssa/conditional.rs]: Done

File: crates/noirc_evaluator/src/ssa/conditional.rs (hunk 1 above)
Comment (guipublic) [reply crates/noirc_evaluator/src/ssa/conditional.rs:461]: Done

**Review by jfecher — APPROVED** [review]
👍

**Review by vezenovm — APPROVED** [review]
